Repository parti-renaissance/espace-adherent, pull requests merged in 2018-02, with the labels that each got.

#2156 [ch2735] Add link "Comités" in nav bar
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#2163 Hotfix - user level should be consistent between mobile and desktop
  src/Twig/AdherentExtension.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#2165 Bugfix - Malformed Client Id for OAuth should 401
  features/oauth.feature
  src/OAuth/Store/ClientStore.php
Labels: Bug, Ready for code review

#2135 [ADMIN] Use an AdminExtension to remove empty translations
  app/config/services/admin.xml
  src/Admin/EmptyTranslationRemoverAdminTrait.php
  src/Admin/Extension/EmptyTranslationRemoverAdminExtension.php
  src/Admin/TimelineMeasureAdmin.php
  src/Admin/TimelineProfileAdmin.php
  src/Admin/TimelineThemeAdmin.php
Labels: Ready for code review

#2140 [ADMIN] Use an AdminExtension to synchronise AMP content
  app/config/services/admin.xml
  app/config/services/services.xml
  src/Admin/AmpSynchronisedAdminTrait.php
  src/Admin/ArticleAdmin.php
  src/Admin/ClarificationAdmin.php
  src/Admin/Extension/AmpSynchronisedAdminExtension.php
  src/Admin/OrderArticleAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/ProposalAdmin.php
  src/Form/EventListener/AmpSynchronisedListener.php
Labels: Ready for code review

#2168 add autodeploy on preprod
  circle.yml
  scripts/deployment.sh
  scripts/deployment_staging.sh
Labels: Ready for code review

#2170 Fixed functional group
  tests/Admin/ArticleCategoryAdminTest.php
  tests/Committee/CommitteeManagementAuthorityTest.php
Labels: Bug

#2167 Image Generator
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/services/platform.xml
  app/data/static/badge/citizen-project.png
  composer.json
  composer.lock
  front/app.js
  front/pages/citizen_project_image_generator.js
  front/style/app.scss
  front/style/layout/_layout.scss
  front/style/pages/_image-generator.scss
  src/Controller/EnMarche/CitizenProjectController.php
  src/Controller/EnMarche/CitizenProjectMediaGeneratorController.php
  src/Form/CitizenProjectImageType.php
  src/Form/CitizenProjectMediaType.php
  src/Form/CitizenProjectTractType.php
  src/Form/ColorChoiceType.php
  src/MediaGenerator/BaseSnappyGenerator.php
  src/MediaGenerator/ColorUtils.php
  src/MediaGenerator/Command/AbstractCitizenProjectMediaCommand.php
  src/MediaGenerator/Command/CitizenProjectImageCommand.php
  src/MediaGenerator/Command/CitizenProjectTractCommand.php
  src/MediaGenerator/Command/MediaCommandInterface.php
  src/MediaGenerator/Image/CitizenProjectCoverGenerator.php
  src/MediaGenerator/MediaContent.php
  src/MediaGenerator/MediaGeneratorInterface.php
  src/MediaGenerator/Pdf/CitizenProjectTractGenerator.php
  templates/citizen_project/cover_image.html.twig
  templates/citizen_project/media_generator.html.twig
  templates/citizen_project/media_generator_image_form.html.twig
  templates/citizen_project/media_generator_tract_form.html.twig
  templates/citizen_project/show_base.html.twig
  templates/citizen_project/tract_pdf.html.twig
  templates/form_theme.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2161 Add command 'app:fix-title-case' to fix some text case
  app/config/services/services.xml
  src/Command/FixTitleCaseCommand.php
  src/Doctrine/DBAL/BatchedConnection.php
  tests/Doctrine/DBAL/BatchedConnectionTest.php
Labels: Ready for code review

#2152 Auth - Add webhook entrypoint
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/repositories.xml
  app/config/services/services.xml
  app/migrations/Version20180125175213.php
  features/webhook.feature
  src/Admin/AdministratorAdmin.php
  src/Admin/CitizenProjectDatagrid.php
  src/Admin/CommitteeDatagrid.php
  src/Admin/DatagridDecorator.php
  src/Admin/WebHookAdmin.php
  src/Admin/WebHookDatagrid.php
  src/Controller/Api/WebHookController.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadClientData.php
  src/DataFixtures/ORM/LoadWebHookData.php
  src/Entity/WebHook/Callback.php
  src/Entity/WebHook/WebHook.php
  src/Form/WebHookCallbackType.php
  src/Repository/WebHookRepository.php
  src/Security/AdherentLoginTimestampRecorder.php
  src/WebHook/Event.php
  templates/admin/webHook/_list_callbacks.html.twig
Labels: Ready for code review

#2175 [Image Generator] Use autowired services
  .php_cs.dist
  app/config/services/platform.xml
  app/config/services/services.xml
  src/Controller/EnMarche/CitizenProjectMediaGeneratorController.php
  src/Form/ColorChoiceType.php
  templates/citizen_project/cover_image.html.twig
  templates/citizen_project/tract_pdf.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2174 [ch2793] Make possible to change committee address in admin.
  app/config/services/admin.xml
  src/Admin/CommitteeAdmin.php
  src/Entity/PostAddress.php
Labels: Ready for code review

#2176 adds preview of file uploads to projets citoyens
  front/app.js
  front/pages/citizen_project_image_generator.js
  front/style/pages/_image-generator.scss
  templates/citizen_project/media_generator_tract_form.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#2179 fix norme
  src/Admin/CommitteeAdmin.php
Labels: Ready for code review

#2171 Added subject in events, committees and citizen projects contact form
  src/CitizenProject/CitizenProjectContactActorsCommand.php
  src/CitizenProject/CitizenProjectContactActorsCommandHandler.php
  src/Committee/CommitteeContactMembersCommand.php
  src/Committee/CommitteeContactMembersCommandHandler.php
  src/Committee/Feed/CommitteeFeedManager.php
  src/Committee/Feed/CommitteeMessage.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Event/EventContactMembersCommand.php
  src/Event/EventContactMembersCommandHandler.php
  src/Form/CitizenProjectContactActorsType.php
  src/Form/CommitteeFeedMessageType.php
  src/Form/ContactMembersType.php
  src/Mailer/Message/CitizenProjectContactActorsMessage.php
  src/Mailer/Message/CommitteeContactMembersMessage.php
  src/Mailer/Message/CommitteeMessageNotificationMessage.php
  src/Mailer/Message/EventContactMembersMessage.php
  templates/citizen_action/list_participants.html.twig
  templates/citizen_project/contact.html.twig
  templates/committee/contact.html.twig
  templates/events/contact_members.html.twig
  templates/referent/users_message.html.twig
  tests/Committee/Feed/CommitteeFeedManagerTest.php
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Mailer/EventSubscriber/EmailPersisterEventSubscriberTest.php
Labels: Ready for code review

#2181 Image generator style & wording
  src/MediaGenerator/Command/CitizenProjectImageCommand.php
  templates/citizen_project/media_generator.html.twig
  templates/citizen_project/media_generator_image_form.html.twig
  templates/citizen_project/media_generator_tract_form.html.twig
  templates/citizen_project/show_base.html.twig
  templates/form_theme.html.twig
  translations/validators.fr.yml
Labels: Devs to merge and add to release, Ready for code review

#2155 [ch2705] Dynamic modification of articles URL after publications.
  app/config/config.yml
  app/config/services/services.xml
  app/config/services/system.xml
  src/Admin/ArticleAdmin.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadOrderArticleData.php
  src/Entity/Article.php
  src/Entity/Redirection.php
  src/EntityListener/ArticleListener.php
  src/EntityListener/RedirectionListener.php
  src/Redirection/Dynamic/RedirectToAdminPanelHandler.php
  src/Redirection/Dynamic/RedirectionManager.php
  src/Repository/RedirectionRepository.php
  tests/Admin/ArticleAdminTest.php
  tests/Redirection/Dynamic/RedirectionManagerTest.php
Labels: Ready for code review

#2185 CP Admin : Added category filter and updated export fields
  src/Admin/CitizenProjectAdmin.php
  src/Entity/CitizenProject.php
  src/Entity/CitizenProjectCommitteeSupport.php
  templates/admin/citizen_project/list_committee_supports.html.twig
Labels: Ready for code review

#2187 Fix wording
  src/Controller/EnMarche/CitizenProjectMediaGeneratorController.php
  templates/citizen_project/media_generator.html.twig
  templates/citizen_project/media_generator_image_form.html.twig
  templates/citizen_project/media_generator_tract_form.html.twig
  templates/citizen_project/show_base.html.twig
  templates/citizen_project/tract_pdf.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2189 Fix wording
  templates/citizen_project/media_generator.html.twig
  templates/citizen_project/media_generator_image_form.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2192 Add Google IP ranges to trusted proxies
  app/trusted_proxies.php
  web/index.php
Labels: Ready for code review

#2191 fix tests committee edit delete
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/Listener/ContainingUserDocumentListener.php
  src/Form/CommitteeFeedItemMessageType.php
  src/Form/CommitteeFeedMessageType.php
  templates/committee/_form_theme.html.twig
  templates/committee/show.html.twig
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Ready for code review

#2195 Change wording in the CKEditor and on the committee message page
  src/Form/CommitteeFeedMessageType.php
  templates/citizen_project/contact.html.twig
  templates/committee/_host_header.html.twig
  templates/committee/contact.html.twig
  templates/javascript.js.twig
Labels: Ready for code review

#2190 Run php-cs-fixer just for modified files
  circle.yml
Labels: Ready for code review

#2194 Quoting string with % character in yml file
  app/config/config.yml
  circle.yml
Labels: Ready for code review

#2196 Change wording and style in CKEditor upload tab
  templates/javascript.js.twig
Labels: Ready for code review

#2200 Add test for Image Generator
  app/config/config.yml
  templates/citizen_project/cover_image.html.twig
  templates/citizen_project/tract_pdf.html.twig
  tests/Controller/EnMarche/CitizenProjectMediaGeneratorControllerTest.php
  tests/MediaGenerator/ColorUtilsTest.php
  tests/MediaGenerator/Image/CitizenProjectCoverGeneratorTest.php
  tests/MediaGenerator/MediaContentTest.php
  tests/MediaGenerator/Pdf/CitizenProjectTractGeneratorTest.php
Labels: Ready for code review

#2201 [ADMIN] Improve Summary list & search performance
  src/Admin/SummaryAdmin.php
  src/DataFixtures/ORM/LoadSummaryData.php
Labels: Ready for code review

#2198 Remove debug statement
  tests/Controller/EnMarche/EventManagerControllerTest.php
Labels: Ready for code review

#2203 Add tract legal notices
  templates/citizen_project/media_generator_tract_form.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2199 Fix commit range separator
  circle.yml
Labels: Ready for code review

#2202 WebHook - Move WebHook admin into OAuth Client
  app/config/security.yml
  app/config/services/admin.xml
  app/migrations/Version20180125175213.php
  src/Admin/AdministratorAdmin.php
  src/Admin/OAuth/ClientAdmin.php
  src/Admin/WebHookAdmin.php
  src/Admin/WebHookDatagrid.php
  src/Controller/Api/WebHookController.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadWebHookData.php
  src/Entity/OAuth/Client.php
  src/Entity/WebHook/Callback.php
  src/Entity/WebHook/WebHook.php
  src/Form/WebHookType.php
  src/Repository/WebHookRepository.php
  templates/admin/oauth/client/_list_webHooks.html.twig
Labels: Ready for code review

#2205 Hotfix - remove call to memberships utils
  src/Controller/EnMarche/DonationController.php
Labels: Ready for code review

#2193 [ch2794] activation mensual donation
  front/components/AmountChooser.js
  src/Form/DonationRequestType.php
Labels: Ready for code review

#2208 [ch2612] Seo optimisation
  templates/citizen_project/_layout.html.twig
  templates/citizen_project/show_base.html.twig
Labels: Ready for code review

#2207 Fix wording - Statuts
  templates/components/_footer.html.twig
Labels: Devs to merge and add to release, Ready for code review

#2206 Add pre-selected category filter from URL on the events page
  app/migrations/Version20180219104140.php
  src/Admin/CitizenActionCategoryAdmin.php
  src/Admin/CitizenProjectCategoryAdmin.php
  src/Admin/EventCategoryAdmin.php
  src/Controller/EnMarche/SearchController.php
  src/Entity/BaseEventCategory.php
  src/Entity/CitizenActionCategory.php
  src/Entity/CitizenProjectCategory.php
  src/Entity/EventCategory.php
  templates/search/_filters.html.twig
  tests/Controller/EnMarche/SearchControllerTest.php
Labels: Ready for code review

#2212 CS microfix
  src/Controller/EnMarche/SearchController.php
Labels: Ready for code review

#2197 [ch2849] Add checkbox to send notification to followers
  src/Committee/Feed/CommitteeFeedManager.php
  src/Committee/Feed/CommitteeMessage.php
  src/Form/CommitteeFeedItemMessageType.php
  src/Form/CommitteeFeedMessageType.php
  templates/committee/_form_theme.html.twig
  templates/committee/_host_header.html.twig
  tests/Committee/Feed/CommitteeFeedManagerTest.php
Labels: Ready for code review

#2217 Hotfix
  src/Entity/FailedLoginAttempt.php
  src/Entity/OAuth/AccessToken.php
  src/Entity/OAuth/AuthorizationCode.php
  src/Entity/OAuth/Client.php
  src/Entity/OAuth/RefreshToken.php
  src/Entity/OAuth/UserAuthorization.php
Labels: Ready for code review

#2215 Change CKEditor file upload wording
  templates/javascript.js.twig
Labels: Ready for code review

#2219 [ADMIN][ch2672] Fix disappearing of coordinator managed area while Adherent edition
  src/Entity/Adherent.php
  src/Form/EventListener/CoordinatorManagedAreaListener.php
Labels: Ready for code review

#2220 Updated sender name
  src/Mailer/Message/BoardMemberMessage.php
  src/Mailer/Message/CitizenProjectCommentMessage.php
  src/Mailer/Message/CommitteeContactMembersMessage.php
  src/Mailer/Message/CommitteeMessageNotificationMessage.php
Labels: Ready for code review

#2216 [ch2848] Change h2 to h1 and move svg outside h1
  front/style/pages/_committee.scss
  templates/committee/_layout.html.twig
  templates/committee/demote_host.html.twig
  templates/committee/promote_host.html.twig
  templates/committee_manager/list_members.html.twig
Labels: Ready for code review

#2214 [ch2618] Modify meta-description for events
  templates/events/show.html.twig
Labels: Ready for code review :+1:

#2210 [ch2655] Modify <title> on all pages
  templates/TwigBundle/Exception/error.html.twig
  templates/TwigBundle/Exception/error404.html.twig
  templates/TwigBundle/Exception/error410.html.twig
  templates/TwigBundle/Exception/error503.html.twig
  templates/amp/_layout.html.twig
  templates/base.html.twig
  templates/components/logo-mini-em.html.twig
  templates/legislative_candidate/platform.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  web/maintenance.html
Labels: Ready for code review :+1:

#2218 Desindex un-needed entities from Algolia
  src/Command/AlgoliaSynchronizeCommand.php
  src/Entity/BoardMember/Role.php
  src/Entity/CitizenProjectCategorySkill.php
  src/Entity/CitizenProjectSkill.php
  src/Entity/Election.php
  src/Entity/ElectionRound.php
  src/Entity/LegislativeDistrictZone.php
  src/Entity/MemberSummary/JobExperience.php
  src/Entity/MemberSummary/Language.php
  src/Entity/MemberSummary/MissionType.php
  src/Entity/MemberSummary/Training.php
  src/Entity/Projection/ReferentManagedUser.php
  src/Entity/PurchasingPowerChoice.php
  src/Entity/ReferentArea.php
  src/Entity/Skill.php
  src/Entity/Summary.php
  src/Entity/Timeline/MeasureTranslation.php
  src/Entity/Unregistration.php
  src/Entity/WebHook/WebHook.php
Labels: Ready for code review

#2221 [ch2891] Design modification for button action in committee timeline
  front/style/layout/_buttons.scss
  front/style/pages/_committee.scss
  src/Controller/EnMarche/CommitteeController.php
  templates/committee/timeline/feed.html.twig
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#2222 Delete client dropbox input from webhook admin
  src/Form/WebHookType.php
Labels: Ready for code review

#2204 [ch2787] Finish implementation of switching follower to organisator.
  src/CitizenProject/CitizenProjectAuthority.php
  src/CitizenProject/CitizenProjectManager.php
  src/Controller/Admin/AdminCitizenProjectController.php
  src/Entity/CitizenProjectMembership.php
  src/Repository/CitizenProjectMembershipRepository.php
  templates/admin/citizen_project/members.html.twig
Labels: Ready for code review

#2225 [SEO] Add GTM on article filters
  templates/article/actualites.html.twig
Labels: Ready for code review

#2226 Modify CKEditor upload dialog
  templates/javascript.js.twig
Labels: Ready for code review

#2224 [ch2849] Committee form, remove text and custome validation depending to a field
  front/app.js
  front/pages/citizen_project_creation.js
  src/Committee/Feed/CommitteeMessage.php
  src/Form/CommitteeFeedMessageType.php
  templates/adherent/create_citizen_project.html.twig
  templates/citizen_project/edit.html.twig
  templates/committee/_host_header.html.twig
  templates/committee/show.html.twig
  templates/javascript.js.twig
Labels: Ready for code review

#2223 [CA] Change link displaying + add link to mail + fix error message
  front/style/layout/_base.scss
  src/CitizenAction/CitizenActionMessageNotifier.php
  src/Form/ContactMembersType.php
  src/Mailer/Message/CitizenActionCancellationMessage.php
  templates/citizen_action/show.html.twig
  templates/citizen_action_manager/contact_participants.html.twig
  templates/committee/contact.html.twig
  templates/events/contact_members.html.twig
Labels: Ready for code review

#2231 Change 'Nos offres' to 'Nos offres d'emploi' in the footer
  templates/components/_footer.html.twig
Labels: Ready for code review

#2232 Add information to connect others docker-compose projects like API
  docker-compose.override.yml.dist
  docker-compose.yml
Labels: Ready for code review

#2233 Hide Board member space link
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#2230 [PROCURATION][ch2470] Show only datas concerning upcoming elections
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Procuration/Filter/ProcurationFilters.php
  src/Repository/ElectionRoundRepository.php
  templates/procuration_manager/_filters.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
Labels: Ready for code review

#2234 [HOTFIX] Add new vote offices
  src/Intl/VoteOfficeBundle.php
Labels: Ready for code review

#2209 [ch1701] Sitemap error fix
  app/config/services/cms.xml
  features/sitemap.feature
  src/Command/ImportReferentBioPictureCommand.php
  src/Command/ImportReferentNominationCommand.php
  src/Controller/Amp/AmpController.php
  src/Controller/EnMarche/HomeController.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadCustomSearchData.php
  src/DataFixtures/ORM/LoadHomeBlockData.php
  src/DataFixtures/ORM/LoadLiveLinkData.php
  src/DataFixtures/ORM/LoadOrderArticleData.php
  src/DataFixtures/ORM/LoadPageData.php
  src/DataFixtures/ORM/LoadProposalData.php
  src/DataFixtures/ORM/LoadSocialShareData.php
  src/Exception/SitemapException.php
  src/Sitemap/SitemapFactory.php
  tests/Controller/EnMarche/HomeControllerTest.php
  tests/Sitemap/SitemapFactoryTest.php
Labels: Ready for code review

#2236 Updated sender name
  src/Mailer/Message/BoardMemberMessage.php
  src/Mailer/Message/CitizenProjectCommentMessage.php
  src/Mailer/Message/CommitteeContactMembersMessage.php
  src/Mailer/Message/CommitteeMessageNotificationMessage.php
Labels: Ready for code review

#2235 [REFERENT][ch2964] Add managed committee postal code and send referent mails to AL of committees in the referent managed zone
  app/migrations/Version20180227110127.php
  src/DataFixtures/ORM/LoadReferentManagedUserData.php
  src/Entity/Projection/ReferentManagedUser.php
  src/Entity/Projection/ReferentManagedUserFactory.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#2239 Display Co-AL label in the drop-down
  src/Entity/Projection/ReferentManagedUser.php
  src/Twig/AdherentExtension.php
Labels: Ready for code review

#2237 [ch3001] Fix display in "my account" for un-adherent
  templates/user/my_account.html.twig
Labels: Ready for code review

#2238 Update of Adherent with Admin must trigger RabbitMQ events
  app/config/services/admin.xml
  features/admin/adherent.feature
  features/registration.feature
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#2241 [CA] Add department to CA participants csv export
  src/CitizenAction/CitizenActionManager.php
  src/CitizenAction/CitizenActionParticipantsExporter.php
Labels: Ready for code review
