Repository parti-renaissance/espace-adherent, pull requests merged in 2018-06, with the labels that each got.

#2472 Add event participants count and committees members count by month with filtering
  app/migrations/Version20180531172925.php
  features/api/committees.feature
  features/api/events.feature
  src/Controller/Api/CommitteesController.php
  src/Controller/Api/EventsController.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Entity/EventRegistration.php
  src/Event/EventRegistrationFactory.php
  src/History/CommitteeMembershipHistoryHandler.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeMembershipHistoryRepository.php
  src/Repository/EventRegistrationRepository.php
  src/Repository/EventRepository.php
  src/Utils/RepositoryUtils.php
  tests/Command/AlgoliaSynchronizeCommandTest.php
  tests/Command/ApiScheduleEventCreationCommandTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Repository/EventRepositoryTest.php
Labels: Ready for code review

#2479 Create Google calendar event with the event platform time as it's done for Apple event creation
  templates/events/_event_header.html.twig
Labels: Bug, Ready for code review

#2480 Bugfix - Add missing lib webmozart/assert
  composer.json
  composer.lock
Labels: Ready for code review

#2475 [MOOC] Added Model and Admin for MOOC, Chapter and Video
  app/config/config.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/migrations/Version20180531173942.php
  src/Admin/AdministratorAdmin.php
  src/Admin/MoocAdmin.php
  src/Admin/MoocChapterAdmin.php
  src/Admin/MoocVideoAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadMoocChapterData.php
  src/DataFixtures/ORM/LoadMoocData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/AttachmentLink.php
  src/Entity/Mooc/BaseElement.php
  src/Entity/Mooc/Chapter.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/Video.php
  src/Form/Mooc/AttachmentLinkType.php
  templates/admin/list/list_thumbnail.html.twig
  templates/admin/media/list_thumbnail.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#2477 [ch3641] monthly event participants
  app/migrations/Version20180604122006.php
  features/api/events.feature
  src/Controller/Api/EventsController.php
  src/Entity/EventRegistration.php
  src/Repository/EventRegistrationRepository.php
  src/Repository/EventRepository.php
  src/Utils/RepositoryUtils.php
Labels: Ready for code review

#2483 Fix color display for CP media creation
  front/style/pages/_image-generator.scss
Labels: Bug, Ready for code review

#2489 [ch4335] current user endpoint
  features/api/adherents.feature
  src/Controller/Api/UserController.php
  src/Entity/Adherent.php
Labels: Ready for code review

#2487 Fix transaction creation when time is encoded.
  src/Entity/Transaction.php
Labels: Ready for code review

#2427 [ch2795] Create a donation limit per year
  app/config/services/services.xml
  features/donation.feature
  src/Donation/DonationRequest.php
  src/Repository/TransactionRepository.php
  src/Validator/MaxFiscalYearDonation.php
  src/Validator/MaxFiscalYearDonationValidator.php
  tests/Repository/TransactionRepositoryTest.php
  tests/Validator/MaxFiscalYearDonationValidatorTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#2490 [MOOC] Added Sortable for Mooc elements
  app/config/config.yml
  app/migrations/Version20180605143145.php
  src/Admin/MoocVideoAdmin.php
  src/DataFixtures/ORM/LoadMoocChapterData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Chapter.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/Video.php
Labels: Ready for code review

#2493 [ch3660] Speed init command
  src/Command/InitializeEmailSubscriptionHistoryCommand.php
Labels: Ready for code review

#2496 [ch3637] count should be done on adherent and total
  features/api/events.feature
  src/Controller/Api/EventsController.php
  src/Repository/EventRegistrationRepository.php
Labels: Ready for code review

#2491 Create a functional test for paybox ipn callback
  app/config/config_test.yml
  tests/Controller/ControllerTestTrait.php
  tests/Donation/TransactionSubscriberTest.php
Labels: Ready for code review

#2481 [ch4261][MOOC] Manager quizz page for
  .gitignore
  Makefile
  app/AppKernel.php
  app/config/routing.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/data/files/.gitkeep
  app/migrations/Version20180608172051.php
  composer.json
  composer.lock
  src/Admin/MoocAdmin.php
  src/Admin/MoocChapterAdmin.php
  src/Admin/MoocElementAdmin.php
  src/Admin/MoocVideoAdmin.php
  src/Controller/AssetsController.php
  src/Controller/MoocController.php
  src/DataFixtures/ORM/LoadMoocChapterData.php
  src/DataFixtures/ORM/LoadMoocQuizzData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/EntityFileInterface.php
  src/Entity/Mooc/AttachmentFile.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Chapter.php
  src/Entity/Mooc/Quizz.php
  src/Entity/Mooc/Video.php
  src/EntityListener/FileListener.php
  src/Form/AttachmentFileType.php
  src/Form/AttachmentLinkType.php
  templates/admin/layout.html.twig
  templates/admin/list/list_thumbnail.html.twig
  templates/form_theme.html.twig
  tests/EventListener/FileListenerTest.php
  web/js/pixsort_ini.js
Labels: Ready for code review

#2497 [MOOC] Added MOOC API endpoint
  app/migrations/Version20180608182855.php
  features/api/mooc.feature
  src/Admin/MoocElementAdmin.php
  src/Controller/Api/MoocController.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/Quizz.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
  src/Repository/MoocRepository.php
Labels: Ready for code review

#2498 [MOOC] Updated BO and API
  app/config/services/admin.xml
  app/migrations/Version20180608222233.php
  features/api/mooc.feature
  src/Admin/MoocAdmin.php
  src/Admin/MoocChapterAdmin.php
  src/Admin/MoocElementAdmin.php
  src/Entity/Mooc/Chapter.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
  translations/validators.fr.yml
Labels: Ready for code review

#2500 Fix Repub silence command by closing all events/actions inside silenc…
  src/Admin/RepublicanSilenceAdmin.php
  src/Command/RepublicanSilenceCloseEventCommand.php
  src/Repository/RepublicanSilenceRepository.php
  translations/messages.fr.yml
Labels: Ready for code review

#2502 [MOOC] Fixed Upload files and updated Mooc Admin
  app/migrations/Version20180611152723.php
  src/Admin/MoocChapterAdmin.php
  src/Admin/MoocElementAdmin.php
  src/Controller/MoocController.php
  src/Entity/Mooc/AttachmentFile.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Normalizer/MoocNormalizer.php
  templates/admin/mooc/list_type.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#2504 Fix donation information
  src/Controller/EnMarche/DonationController.php
  src/Donation/DonationRequestUtils.php
Labels: Ready for code review

#2495 Fix donation admin page
  src/Admin/DonationAdmin.php
  templates/admin/donation/list_status.html.twig
  templates/admin/donation/show_status.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#2506 [MOOC] Updated Chapter published field and Mooc req
  app/migrations/Version20180611202504.php
  src/Admin/MoocChapterAdmin.php
  src/Entity/Mooc/Chapter.php
  src/Repository/MoocRepository.php
Labels: Ready for code review

#2511 [MOOC] Updated Chapter published field for the list view
  src/Admin/MoocChapterAdmin.php
Labels: Ready for code review

#2513 Find all rep silence from command launch date
  src/Command/RepublicanSilenceCloseEventCommand.php
  src/Repository/RepublicanSilenceRepository.php
  src/RepublicanSilence/RepublicanSilenceManager.php
Labels: Bug, Ready for code review

#2510 [ch3779] Change meta descriptions for /comites and /evenements
  templates/search/search_committees.html.twig
  templates/search/search_events.html.twig
Labels: Ready for code review

#2514 [MOOC] Added Twig test extension and Refacto elements
  app/config/services/admin.xml
  app/config/services/twig.xml
  features/api/mooc.feature
  src/Admin/MoocElementAdmin.php
  src/DataFixtures/ORM/LoadMoocChapterData.php
  src/DataFixtures/ORM/LoadMoocQuizData.php
  src/Entity/Mooc/AttachmentFile.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Quiz.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
  src/Twig/MoocElementExtension.php
  templates/admin/mooc/list_type.html.twig
Labels: Ready for code review

#2515 [MOOC] Added new fields for the Mooc
  app/migrations/Version20180614171252.php
  features/api/mooc.feature
  src/Admin/MoocAdmin.php
  src/DataFixtures/ORM/LoadMoocData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
  translations/validators.fr.yml
Labels: Ready for code review

#2516 [MOOC] Added shared buttons text for Mooc elements
  app/migrations/Version20180614182504.php
  features/api/mooc.feature
  src/Admin/MoocElementAdmin.php
  src/DataFixtures/ORM/LoadMoocQuizData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Quiz.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
Labels: Ready for code review

#2519 [MOOC] Fixed Chapter admin
  src/Admin/MoocChapterAdmin.php
Labels: Don't merge, Ready for code review

#2521 [MOOC] Added sharing email body for elements
  app/migrations/Version20180618103523.php
  features/api/mooc.feature
  src/Admin/MoocElementAdmin.php
  src/DataFixtures/ORM/LoadMoocQuizData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Quiz.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
Labels: Ready for code review

#2508 Add deputy tag to adherent admin
  src/Entity/Adherent.php
  templates/admin/adherent/list_status.html.twig
Labels: Ready for code review

#2522 Fix migration: primary key should be auto increment when added
  app/migrations/Version20180524165445.php
Labels: Bug, Ready for code review

#2499 [ch4294] Add autocomplete address via google maps api
  front/pages/donation_informations.js
  front/services/address/GooglePlaceAutocomplete.js
  templates/donation/informations.html.twig
Labels: Ready for code review

#2525 Creates a command to update Donations reference
  app/config/services/services.xml
  app/migrations/Version20180502142950.php
  src/Command/DonationUpdateReferenceCommand.php
  src/Entity/Donation.php
  tests/Command/DonationUpdateReferenceCommandTest.php
Labels: Ready for code review

#2523 [MOOC] Updated share elements fields
  app/migrations/Version20180619100109.php
  features/api/mooc.feature
  src/Admin/MoocElementAdmin.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Quiz.php
  src/Entity/Mooc/Video.php
  src/Normalizer/MoocNormalizer.php
Labels: Ready for code review

#2528 [MOOC] Hidden unpublished chapter elements
  features/api/mooc.feature
  src/DataFixtures/ORM/LoadMoocChapterData.php
  src/Normalizer/MoocNormalizer.php
  src/Repository/MoocRepository.php
Labels: Don't merge

#2534 [MOOC] Added source button and advanced CKEditor instance
  src/Admin/MoocElementAdmin.php
  templates/admin/layout.html.twig
Labels: Ready for code review

#2535 [MOOC] Allowed class and target attributes for editors
  app/config/config.yml
Labels: Ready for code review

#2531 [MOOC] Added share elements for the Mooc introduction
  app/migrations/Version20180620111519.php
  features/api/mooc.feature
  src/Admin/MoocAdmin.php
  src/DataFixtures/ORM/LoadMoocData.php
  src/Entity/Mooc/Mooc.php
  src/Normalizer/MoocNormalizer.php
Labels: Don't merge, Ready for code review

#2532 Reduce memory leak and fix too many connection issue during tests
  app/AppKernel.php
  app/config/config_test.yml
  composer.json
  composer.lock
  src/DataFixtures/ORM/LoadEventData.php
  tests/Api/EventProviderTest.php
  tests/BoardMember/BoardMemberManagerTest.php
  tests/CitizenProject/CitizenProjectManagerTest.php
  tests/Command/AlgoliaSynchronizeCommandTest.php
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Command/ApiScheduleEventCreationCommandTest.php
  tests/Command/DonationUpdateReferenceCommandTest.php
  tests/Command/ImportReferentBioPictureCommandTest.php
  tests/Command/ProcurationSendReminderCommandTest.php
  tests/Command/TimelineSynchronizeCommandTest.php
  tests/Committee/CommitteeManagerTest.php
  tests/Committee/Feed/CommitteeFeedManagerTest.php
  tests/Controller/Api/OAuthServerControllerTest.php
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Controller/EnMarche/InteractiveControllerTest.php
  tests/Entity/AbstractAdherentTokenTest.php
  tests/Entity/AdherentTest.php
  tests/Mailer/Message/AdherentTerminateMembershipMessageTest.php
  tests/Redirection/Dynamic/RedirectionManagerTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/Repository/CommitteeMembershipRepositoryTest.php
  tests/Repository/CommitteeRepositoryTest.php
  tests/Repository/EventRepositoryTest.php
  tests/Repository/NewsletterSubscriptionRepositoryTest.php
  tests/Repository/Projection/ReferentManagedUserRepositoryTest.php
  tests/Repository/PurchasingPowerChoiceRepositoryTest.php
  tests/Repository/TonMacronChoiceRepositoryTest.php
  tests/Repository/TransactionRepositoryTest.php
  tests/TestHelperTrait.php
  tests/Utils/GroupUtilsTest.php
Labels: Ready for code review

#2533 Redis instance is not required anymore for cache warmup
  .dockerignore
  Dockerfile
  app/config/services/cms.xml
  rabbitmq.mk
Labels: Ready for code review

#2539 [MOOC] Added emojis filter
  src/Admin/MoocAdmin.php
  src/Admin/MoocElementAdmin.php
Labels: Ready for code review

#2541 Clear the cache when a Republican silence is deleted
  src/Admin/RepublicanSilenceAdmin.php
Labels: Bug, Ready for code review

#2540 Synchronize Events organizer uuid
  src/Entity/Event.php
Labels: Ready for code review

#2545 Revert "Merge pull request #2499 from EnMarche/alexandrevinet/ch4194/…
  front/pages/donation_informations.js
  front/services/address/GooglePlaceAutocomplete.js
  templates/donation/informations.html.twig
Labels: Ready for code review

#2517 Add deputy role to adherent role filter in admin
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  translations/messages.fr.yml
Labels: Ready for code review

#2536 Remove /campus/mooc page
  features/sitemap.feature
  src/Controller/EnMarche/PageController.php
  src/Sitemap/SitemapFactory.php
  templates/components/_footer.html.twig
  templates/page/campus/mooc.html.twig
  tests/Controller/EnMarche/PageControllerTest.php
Labels: Ready for code review

#2512 Bind deputies to districts
  app/config/services/services.xml
  src/Command/BindDeputiesToDistrictsCommand.php
Labels: Ready for code review

#2538 Add page listing events in the deputy district
  app/config/services/platform.xml
  app/config/services/services.xml
  src/Controller/EnMarche/DeputyController.php
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Entity/Event.php
  src/Referent/ManagedEventsExporter.php
  src/Repository/EventRepository.php
  templates/deputy/events_list.html.twig
  tests/Referent/ManagedEventsExporterTest.php
Labels: Ready for code review

#2550 Removed contact link for not connected users on events pages
  templates/events/show.html.twig
Labels: Ready for code review

#2549 Fixed typo
  templates/membership/choose_committees.html.twig
Labels: Ready for code review

#2551 Add canary mode to deputy space
  src/Controller/EnMarche/DeputyController.php
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#2553 Formation organisation
  features/donation.feature
  front/style/pages/_campus.scss
  src/Controller/EnMarche/PageController.php
  src/DataFixtures/ORM/LoadEventData.php
  templates/components/_footer.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/page/campus/home.html.twig
  tests/Controller/EnMarche/PageControllerTest.php
  web/images/campus/tous-politiques.png
Labels: Ready for code review
