Repository parti-renaissance/espace-adherent, pull requests merged in 2018-07, with the labels that each got.

#2547 Add republican silence for deputy space
  features/admin/adherent.feature
  features/api/adherents.feature
  features/deputy.feature
  features/republican_silence.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/DataFixtures/ORM/LoadRepublicanSilenceData.php
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  src/RepublicanSilence/ReferentTagExtractorFactory.php
  src/RepublicanSilence/TagExtractor/DistrictReferentTagExtractor.php
  src/RepublicanSilence/TagExtractor/ReferentTagExtractorInterface.php
  src/Utils/AreaUtils.php
  tests/BoardMember/BoardMemberManagerTest.php
  tests/CitizenProject/CitizenProjectManagerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/RepublicanSilence/TagExtractor/DistrictReferentTagExtractorTest.php
Labels: Ready for code review

#2554 Send Email confirmation on email changing
  app/config/services/platform.xml
  app/config/services/services.xml
  app/migrations/Version20180627130852.php
  front/style/layout/_layout.scss
  src/Controller/EnMarche/Security/SecurityController.php
  src/Controller/EnMarche/UserController.php
  src/Entity/Adherent.php
  src/Entity/AdherentChangeEmailToken.php
  src/Form/AdherentChangeEmailType.php
  src/Mailer/Message/AdherentChangeEmailMessage.php
  src/Membership/AdherentChangeEmailHandler.php
  src/Membership/AdherentManager.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  src/Repository/AbstractAdherentTokenRepository.php
  src/Repository/AdherentActivationTokenRepository.php
  src/Repository/AdherentChangeEmailTokenRepository.php
  src/Repository/AdherentRepository.php
  src/Repository/AdherentResetPasswordTokenRepository.php
  src/Validator/UniqueMembershipValidator.php
  templates/adherent/profile-email.html.twig
  templates/adherent/profile.html.twig
  templates/base.html.twig
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/CitizenActionManagerControllerTest.php
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/EnMarche/LegislativesControllerTest.php
  tests/Controller/EnMarche/UserControllerTest.php
  translations/messages.fr.yml
Labels: Bug, Ready for code review

#2556 Change Flash message
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  tests/Controller/EnMarche/UserControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#2555 Remove using translate service for flash info message
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/BoardMemberController.php
  src/Controller/EnMarche/CitizenActionController.php
  src/Controller/EnMarche/CitizenActionManagerController.php
  src/Controller/EnMarche/CitizenProjectManagerController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Controller/EnMarche/EventController.php
  src/Controller/EnMarche/EventManagerController.php
  src/Controller/EnMarche/LegislativeCandidateController.php
  src/Controller/EnMarche/MembershipController.php
  src/Controller/EnMarche/ProcurationManagerController.php
  src/Controller/EnMarche/ReferentController.php
  src/Controller/EnMarche/Security/SecurityController.php
  src/Controller/EnMarche/UserController.php
Labels: Ready for code review

#2557 Add recipients filter to mails admin
  src/Admin/EmailAdmin.php
Labels: Needs product go/no go, Ready for code review

#2563 Add recipients column to mails admin
  src/Admin/EmailAdmin.php
  src/Entity/Email.php
Labels: Ready for code review

#2565 Add wait mechanism for "I should be on" step
  features/bootstrap/FeatureContext.php
  features/donation.feature
Labels: Ready for code review

#2561 Removed contact link for not connected users on committee page
  templates/committee/_sidebar.html.twig
  templates/events/show.html.twig
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Needs product go/no go, Ready for code review

#2566 Disable browser form autocomplete feature
  front/services/address/GooglePlaceAutocomplete.js
  templates/donation/informations.html.twig
Labels: Bug, Ready for code review

#2569 [TF] Find event by slug and not by creation date
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#2562 Update GDPR of the forms and add checkboxes
  features/donation.feature
  src/Form/AcceptPersonalDataCollectType.php
  src/Form/DonationRequestType.php
  src/Form/EventRegistrationType.php
  src/Form/InvitationType.php
  src/Form/NewsletterSubscriptionType.php
  src/Form/SummaryType.php
  templates/adherent/create_citizen_project.html.twig
  templates/donation/informations.html.twig
  templates/events/attend.html.twig
  templates/facebook/index.html.twig
  templates/form_theme.html.twig
  templates/home/index.html.twig
  templates/invitation/form.html.twig
  templates/membership/join.html.twig
  templates/newsletter/subscription.html.twig
  templates/procuration/legal.html.twig
  templates/summary_manager/_form/contact.html.twig
  templates/summary_manager/_form/interests.html.twig
  templates/summary_manager/_form/synthesis.html.twig
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Controller/EnMarche/InvitationControllerTest.php
  tests/Controller/EnMarche/NewsletterControllerTest.php
  tests/Controller/EnMarche/SummaryManagerControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#2572 Change canonical links on event invitation and registration pages
  templates/citizen_action/attend.html.twig
  templates/events/attend.html.twig
  templates/events/invitation.html.twig
Labels: Ready for code review

#2564 [Donation] Added alert feature for high amount
  src/Controller/EnMarche/DonationController.php
  src/Donation/DonationRequest.php
  src/Donation/DonationRequestUtils.php
  src/Form/DonationRequestType.php
  templates/donation/informations.html.twig
  templates/donation/result.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#2571 [Donation] Updated civility and removed phone fields
  features/donation.feature
  front/style/pages/_donation.scss
  src/Admin/DonationAdmin.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Entity/Donation.php
  src/Form/DonationRequestType.php
  src/ValueObject/Genders.php
  templates/donation/informations.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Donation/DonationFactoryTest.php
  tests/Donation/DonationRequestTest.php
  tests/Entity/DonationTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#2574 Add page number to the header on the articles list pages
  templates/article/actualites.html.twig
Labels: Ready for code review

#2573 Change GDPR and checkbox position on the forms
  templates/donation/informations.html.twig
  templates/events/attend.html.twig
  templates/form_theme.html.twig
  templates/home/index.html.twig
  templates/invitation/form.html.twig
Labels: Ready for code review

#2576 [Donation] Updated amount render for cents
  templates/donation/informations.html.twig
  templates/donation/result.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#2577 Take good city name from google api response
  front/services/address/GooglePlaceAutocomplete.js
Labels: Bug, Ready for code review

#2575 Fix Event modification by using event date instead of NOW
  src/Event/BaseEventCommand.php
  src/Form/BaseEventCommandType.php
  templates/committee_manager/add_event.html.twig
  templates/events/edit.html.twig
  templates/referent/event_create.html.twig
Labels: Bug, Ready for code review

#2578 Add city and date to the event header
  templates/events/_header.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
Labels: Ready for code review

#2580 [Donation] Updated confirmation text
  templates/donation/result.html.twig
Labels: Ready for code review

#2582 Sync dates on Referent Event page
  templates/referent/event_create.html.twig
Labels: Ready for code review

#2581 [Donation] Fixed confirmation page JS errors
  templates/donation/result.html.twig
Labels: Bug, Ready for code review

#2584 Removed newsletter subscription admin
  app/config/security.yml
  app/config/services/admin.xml
  src/Admin/NewsletterSubscriptionAdmin.php
Labels: Ready for code review

#2588 Change personal data collection to don successful page
  templates/donation/result.html.twig
Labels: Ready for code review

#2587 Updated canonical URLs
  templates/citizen_project/landing.html.twig
  templates/page/layout.html.twig
  templates/procuration/choose_election.html.twig
  templates/program/proposal.html.twig
Labels: Ready for code review

#2592 Add link to replace autocomplete if address is unknown by google
  front/pages/donation_informations.js
  front/services/address/GooglePlaceAutocomplete.js
  src/Form/DonationRequestType.php
  templates/donation/informations.html.twig
Labels: Bug, Ready for code review

#2590 Fix error on events list when an event has no organizer
  src/Doctrine/Hydrators/EventHydrator.php
  templates/search/_events.html.twig
Labels: Ready for code review

#2594 Add check for empty Google api result
  front/services/address/GooglePlaceAutocomplete.js
Labels: Ready for code review

#2593 [ch2260] Keep anonymous followers on track
  .php_cs.dist
  app/config/security.yml
  app/config/services/services.xml
  app/config/services/twig.xml
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/CitizenActionController.php
  src/Controller/EnMarche/CitizenProjectController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/EventController.php
  src/Controller/EnMarche/MembershipController.php
  src/OAuth/CallbackManager.php
  src/Redirection/Dynamic/RedirectToRemoveUuidHandler.php
  src/Security/Http/AnonymousFollowerAuthenticationSuccessHandler.php
  src/Security/Http/Session/AnonymousFollowerSession.php
  src/Security/Voter/AnonymousVoter.php
  src/Twig/AnonymousExtension.php
  src/Twig/AnonymousRuntime.php
  templates/citizen_action/_layout.html.twig
  templates/citizen_action/show.html.twig
  templates/citizen_project/_layout.html.twig
  templates/citizen_project/landing.html.twig
  templates/committee/show.html.twig
  templates/committee/timeline/_event.html.twig
  templates/events/_header.html.twig
  templates/events/attend.html.twig
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/AbstractGroupControllerTest.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Controller/EnMarche/RegistrationTrait.php
Labels: Ready for code review

#2595 Change image on membership join
  templates/membership/join.html.twig
Labels: Ready for code review

#2597 Set FR as default country for autocomplete google place
  front/services/address/GooglePlaceAutocomplete.js
Labels: Bug, Ready for code review

#2598 [Autocomplete] Fix place changed action
  front/services/address/GooglePlaceAutocomplete.js
Labels: Bug, Ready for code review

#2601 Execute runManageParticipants only if host to avoid JS error
  templates/citizen_action/_layout.html.twig
  templates/citizen_action/_participants_list.html.twig
  templates/citizen_action/list_participants.html.twig
  templates/citizen_action/show.html.twig
  templates/citizen_action_manager/print_participants.html.twig
  templates/citizen_project/_layout.html.twig
  templates/citizen_project/_sidebar.html.twig
  templates/citizen_project/list_actors.html.twig
  templates/citizen_project/show_base.html.twig
Labels: Bug, Ready for code review

#2596 [Citizen Projects] Referents can now create citizen projects
  src/Security/Voter/CitizenProject/CreateCitizenProjectVoter.php
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Security/Voter/CitizenProject/CreateCitizenProjectVoterTest.php
Labels: Ready for code review

#2602 Removed useless var
  src/Admin/AdministratorAdmin.php
Labels: Ready for code review

#2603 Remove text about monthly don
  front/components/AmountChooser.js
Labels: Ready for code review

#2604 Added emojis filter
  src/Form/CitizenProjectContactActorsType.php
  src/Form/ContactMembersType.php
  src/Form/EventInvitationType.php
Labels: Ready for code review

#2546 Add SubscriptionType entity for email notification
  app/config/services/services.xml
  app/migrations/Version20180705144501.php
  features/registration.feature
  src/Admin/AdherentAdmin.php
  src/Command/MigrateSubscriptionTypeCommand.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/UserController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadEmailSubscriptionHistoryData.php
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Entity/Adherent.php
  src/Entity/Reporting/EmailSubscriptionHistory.php
  src/Entity/SubscriptionType.php
  src/Event/EventRegistrationCommand.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Form/AdherentRegistrationType.php
  src/Form/AdherentType.php
  src/Form/BecomeAdherentType.php
  src/Form/UserRegistrationType.php
  src/History/EmailSubscriptionHistoryHandler.php
  src/Membership/AdherentEmailSubscription.php
  src/Membership/AdherentFactory.php
  src/Membership/CitizenProjectNotificationDistance.php
  src/Membership/MembershipRequest.php
  src/Membership/MembershipRequestHandler.php
  src/Membership/UserEvent.php
  src/Repository/AdherentRepository.php
  src/Repository/EmailSubscriptionHistoryRepository.php
  src/Repository/SubscriptionTypeRepository.php
  src/Subscription/SubscriptionHandler.php
  src/Subscription/SubscriptionListener.php
  src/Subscription/SubscriptionTypeEnum.php
  templates/adherent/_profile_menu.html.twig
  templates/adherent/list_my_citizen_projects.html.twig
  templates/adherent/list_my_committees.html.twig
  templates/adherent/profile.html.twig
  templates/admin/adherent/list_board_member_roles.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/membership/join.html.twig
  templates/membership/register.html.twig
  templates/user/set_email_notifications.html.twig
  tests/CitizenProject/CitizenProjectManagerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Entity/AdherentTest.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
Labels: Ready for code review

#2606 Added meta description for legislative candidate page
  templates/legislatives/candidate.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#2608 Improve subscription type migration command
  src/Command/MigrateSubscriptionTypeCommand.php
Labels: Ready for code review

#2609 Speed up the execution of the email subscription type migration command
  src/Command/MigrateSubscriptionTypeCommand.php
Labels: Ready for code review

#2599 Add webhook for mailchimp when user change email subscriptions
  app/config/security.yml
  app/config/services/admin.xml
  app/migrations/Version20180705144501.php
  app/migrations/Version20180718152912.php
  features/bootstrap/RabbitMqContext.php
  features/bootstrap/SyncWithAPIContext.php
  features/registration.feature
  features/sync_with_api.feature
  features/webhook.feature
  src/Admin/AdministratorAdmin.php
  src/Admin/SubscriptionTypeAdmin.php
  src/Controller/EnMarche/UserController.php
  src/DataFixtures/ORM/LoadClientData.php
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/DataFixtures/ORM/LoadWebHookData.php
  src/Entity/Adherent.php
  src/Entity/SubscriptionType.php
  src/Entity/WebHook/WebHook.php
  src/Form/WebHookType.php
  src/Membership/EventListener/UserSubscriber.php
  src/Membership/UserEvent.php
  src/Membership/UserEvents.php
  src/Repository/WebHookRepository.php
  src/WebHook/Event.php
  src/WebHook/Service.php
  templates/user/set_email_notifications.html.twig
Labels: Ready for code review

#2607 Added meta description for referent page
  templates/referent/nomination/referent.html.twig
Labels: Ready for code review

#2612 Filter emojis in report comments
  app/config/services/services.xml
  src/Form/ReportCommandType.php
Labels: Bug

#2614 Create an endpoint to expose header & footer markup
  src/Controller/Api/DomController.php
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
Labels: Ready for code review

#2610 [MOOC] Added Sitemap API Endpoint
  app/config/config.yml
  app/config/parameters.yml.dist
  features/api/mooc.feature
  src/Controller/Api/MoocController.php
  src/Repository/MoocRepository.php
  src/Sitemap/SitemapFactory.php
Labels: Ready for code review

#2615 Change e-mail notifications wording + menu width
  app/migrations/Version20180705144501.php
  features/registration.feature
  front/style/layout/_nav.scss
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  templates/user/set_email_notifications.html.twig
Labels: Ready for code review

#2613 Add e-mail subscription changing from external service (Mailchimp)
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/services/services.xml
  features/api/subscription.feature
  src/Controller/Api/SubscriptionController.php
  src/Repository/SubscriptionTypeRepository.php
  src/Subscription/SubscriptionHandler.php
Labels: Ready for code review

#2617 Modify EM charter
  web/charte.pdf
Labels: Ready for code review

#2616 Change email notifications order + menu size
  front/style/layout/_nav.scss
  src/Form/AdherentEmailSubscriptionType.php
Labels: Ready for code review

#2618 Fix menu display
  front/style/layout/_nav.scss
Labels: Ready for code review
