Repository parti-renaissance/espace-adherent, pull requests merged in 2018-12, with the labels that each got.

#2898 [ADMIN] Add Consultation Report admin
  app/config/security.yml
  app/config/services/admin.xml
  src/Admin/IdeasWorkshopConsultationReportAdmin.php
  src/DataFixtures/ORM/LoadConsultationReportData.php
  src/Entity/IdeasWorkshop/ConsultationReport.php
Labels: Ready for code review

#2899 [ADMIN] Add Ideas Workshop Category admin
  app/config/security.yml
  app/config/services/admin.xml
  app/migrations/Version20181203114057.php
  src/Admin/IdeasWorkshopCategoryAdmin.php
  src/Entity/IdeasWorkshop/Category.php
Labels: Ready for code review

#2900 [ADMIN] Add Ideas Workshop Need admin
  app/config/security.yml
  app/config/services/admin.xml
  app/migrations/Version20181203115226.php
  src/Admin/IdeasWorkshopNeedAdmin.php
  src/DataFixtures/ORM/LoadIdeaNeedData.php
  src/Entity/IdeasWorkshop/Need.php
Labels: Ready for code review

#2905 [MOOC] Updated Image constraint options
  src/Entity/Mooc/Mooc.php
Labels: Ready for code review

#2906 [MOOC] Admin : Updated image help
  src/Admin/MoocAdmin.php
Labels: Ready for code review

#2903 [RFR] Add ideas list endpoints
  features/api/ideas_workshop.feature
  src/Controller/Api/IdeasWorkshopController.php
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#2911 Disable map of committees in production
  composer.lock
  src/Controller/EnMarche/MapController.php
  templates/map/events.html.twig
  templates/search/search_committees.html.twig
Labels: Ready for code review

#2915 Add parameter to check abonnement by default
  front/components/AmountChooser.js
  front/components/DonationAmountChooser.js
  front/pages/donation.js
  src/Controller/EnMarche/DonationController.php
  templates/donation/index.html.twig
Labels: Ready for code review

#2924 Remove !important from visibility-hidden
  front/style/layout/_utilities.scss
  templates/search/search.html.twig
Labels: Bug, Ready for code review

#2940 [ADI][RFR] Add idea list api with filter on status
  app/config/config.yml
  app/config/services/services.xml
  app/migrations/Version20171003164518.php
  app/migrations/Version20181214110725.php
  features/api/ideas_workshop.feature
  features/api/ideas_workshop_idea_list.feature
  src/Controller/Api/IdeasWorkshopController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAdherentTagData.php
  src/DataFixtures/ORM/LoadIdeaData.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaVoteData.php
  src/Doctrine/IdeaExtension.php
  src/Entity/Adherent.php
  src/Entity/AdherentTagEnum.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/AuthorCategoryEnum.php
  src/Entity/IdeasWorkshop/Category.php
  src/Entity/IdeasWorkshop/Guideline.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/IdeaStatusEnum.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
  src/Repository/IdeaRepository.php
  src/Serializer/IdeasWorkshopSerializerNormalizer.php
Labels: Ready for code review

#2937 [ADI] Add themes, needs and idea categories list endpoints
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  app/config/routing.yml
  app/config/services/services.xml
  app/migrations/Version20181217174342.php
  features/api/ideas_workshop_categories.feature
  features/api/ideas_workshop_idea_list.feature
  features/api/ideas_workshop_needs.feature
  features/api/ideas_workshop_themes.feature
  src/Doctrine/EnabledExtension.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Entity/EnabledInterface.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/IdeasWorkshop/Category.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#2946 [ADI] Add vote creation and suppression endpoints
  app/config/config.yml
  app/config/routing.yml
  app/config/services/services.xml
  app/migrations/Version20181219114610.php
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_needs.feature
  features/api/ideas_workshop_themes.feature
  features/api/ideas_workshop_votes.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/DataFixtures/ORM/LoadIdeaVoteData.php
  src/Entity/Adherent.php
  src/Entity/AuthorInterface.php
  src/Entity/Committee.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
  src/EntityListener/VoteListener.php
  src/Normalizer/AuthorNormalizer.php
Labels: Ready for code review

#2953 [ADI] Add votes count by type
  features/api/ideas_workshop_ideas.feature
  src/Repository/IdeaRepository.php
  src/Serializer/IdeasWorkshopSerializerNormalizer.php
Labels: Ready for code review

#2949 [ADI] Add author uuid filter on /ideas
  features/api/ideas_workshop_ideas.feature
  src/Doctrine/IdeaExtension.php
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#2942 [ADI] Add consultation report endpoint
  app/config/services/services.xml
  features/api/ideas_workshop_categories.feature
  features/api/ideas_workshop_consultation_reports.feature
  features/api/ideas_workshop_consultations.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_needs.feature
  features/api/ideas_workshop_themes.feature
  src/DataFixtures/ORM/LoadIdeaConsultationReportData.php
  src/Entity/IdeasWorkshop/ConsultationReport.php
  src/Normalizer/IdeasWorkshopNormalizer.php
  src/Normalizer/ItemCollectionNormalizer.php
Labels: Ready for code review

#2939 Add a dropdown to adherent header for committes
  templates/adherent/list_my_committees_al.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#2958 remove ideas workshop test
  features/api/ideas_workshop.feature
Labels: Ready for code review

#2945 [ADI] ReportableInterface for IdeasWorkshop
  app/migrations/Version20181219003017.php
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/report.feature
  src/Controller/Api/ReportController.php
  src/Controller/EnMarche/ReportController.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/Report/IdeasWorkshop/IdeaReport.php
  src/Entity/Report/IdeasWorkshop/ThreadCommentReport.php
  src/Entity/Report/IdeasWorkshop/ThreadReport.php
  src/Entity/Report/Report.php
  src/Report/ReportCommand.php
  src/Report/ReportType.php
Labels: Ready for code review

#2962 [ADI] Duplicat ideas dans le state
  web/apps/atelier-des-idees/src/pages/Home.jsx
Labels: Bug

#2956 [ADI] My committees
  features/api/committees.feature
  src/Controller/Api/CommitteesController.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Entity/Committee.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Repository/CommitteeMembershipRepository.php
Labels: Ready for code review

#2964 [ADI] #17 Improve ideas sort on Landing
  web/apps/atelier-des-idees/src/containers/LatestIdeas/index.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review

#2959 [ADI] Add thumbnail on ideas
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_themes.feature
  src/DataFixtures/ORM/LoadIdeaThemeData.php
  src/Entity/IdeasWorkshop/Theme.php
  src/Normalizer/ThemeNormalizer.php
Labels: Ready for code review

#2957 [ADI] Add /ideas/my-contributions endpoint
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  src/Doctrine/MyIdeaContributionExtension.php
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#2966 [ADI] #20 create ThreeTabs page component
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
  web/apps/atelier-des-idees/src/pages/ThreeTabs/index.jsx
  web/apps/atelier-des-idees/src/style/_variables.scss
Labels: Ready for code review

#2973 [ADI] #21 Page "Contribuer"
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/IdeaCardList/IdeaCardList.stories.js
  web/apps/atelier-des-idees/src/components/IdeaCardList/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/components/Skeletons/IdeaCardSkeleton/_style.scss
  web/apps/atelier-des-idees/src/components/Skeletons/IdeaCardSkeletonList/IdeaCardSkeletonList.stories.js
  web/apps/atelier-des-idees/src/components/Skeletons/IdeaCardSkeletonList/_style.scss
  web/apps/atelier-des-idees/src/components/Skeletons/IdeaCardSkeletonList/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/_style.scss
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/pages/Contribute.jsx
  web/apps/atelier-des-idees/src/pages/Contribute/_style.scss
  web/apps/atelier-des-idees/src/pages/Contribute/index.jsx
  web/apps/atelier-des-idees/src/pages/Home.jsx
  web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
  web/apps/atelier-des-idees/src/redux/actions/ideas.js
  web/apps/atelier-des-idees/src/redux/reducers/ideas.js
  web/apps/atelier-des-idees/src/redux/selectors/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/src/style/_variables.scss
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#2975 fix Bind multi circos
  app/config/services/services.xml
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
  src/Repository/DistrictRepository.php
  tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
Labels: Bug, Ready for code review

#2976 [ADI] Add idea delete endpoint
  app/migrations/Version20181226122053.php
  features/api/ideas_workshop_ideas.feature
  src/Doctrine/VisibleStatusesExtension.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
Labels: Ready for code review

#2978 [ADI] #31 Composant TextEditor
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/TextEditor/TextEditor.stories.js
  web/apps/atelier-des-idees/src/components/TextEditor/_style.scss
  web/apps/atelier-des-idees/src/components/TextEditor/index.jsx
  web/apps/atelier-des-idees/src/style/_variables.scss
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#2985 [ADI] #33 TextArea component
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/TextArea/TextArea.stories.js
  web/apps/atelier-des-idees/src/components/TextArea/_style.scss
  web/apps/atelier-des-idees/src/components/TextArea/index.jsx
Labels: Ready for code review

#2990 [ADI] #41 Change html-draftjs dependencies
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/components/TextEditor/TextEditor.stories.js
  web/apps/atelier-des-idees/src/components/TextEditor/index.jsx
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#2970 [ADI] Add POST/DELETE/PUT to /threads and /thread_comments
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/ThreadCommentController.php
  src/Controller/Api/ThreadController.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/EntityThreadCommentStatusTrait.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#2984 [ADI] #30 Idea creation tool
  src/React/App/IdeasWorkshopApp.php
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/TextArea/_style.scss
  web/apps/atelier-des-idees/src/components/TextArea/index.jsx
  web/apps/atelier-des-idees/src/components/TextEditor/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaActions/CreateIdeaActions.stories.js
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaActions/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaTool/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/QuestionBlock/QuestionBlock.stories.js
  web/apps/atelier-des-idees/src/pages/CreateIdea/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/constants/questions.js
  web/apps/atelier-des-idees/src/pages/CreateIdea/index.jsx
  web/apps/atelier-des-idees/src/style/_variables.scss
Labels: Ready for code review

#2989 [ADI] Add idea publish endpoint
  app/migrations/Version20181227181646.php
  features/api/ideas_workshop_ideas.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Doctrine/VisibleStatusesExtension.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Question.php
  src/IdeasWorkshop/IdeaPermissions.php
  src/Normalizer/IdeaDenormalizer.php
  src/Security/Voter/IdeaPublishVoter.php
  translations/validators.fr.yml
Labels: Ready for code review

#2994 [ADI] Switch thread and comment identifier to uuid
  app/migrations/Version20181228151600.php
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/ThreadCommentController.php
  src/Controller/Api/ThreadController.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#2997 [ADI] Add idea template endpoint
  features/api/ideas_workshop_guidelines.feature
  src/DataFixtures/ORM/LoadIdeaGuidelineData.php
  src/Entity/IdeasWorkshop/Guideline.php
  src/Entity/IdeasWorkshop/Question.php
Labels: Ready for code review

#2999 [ADI] #44 fix baseUrl env variable issue
  web/apps/atelier-des-idees/src/redux/store/configStore.dev.js
  web/apps/atelier-des-idees/src/redux/store/configStore.prod.js
Labels: Ready for code review

#2998 [ADI] #35 Idea page : Reading mode
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/IdeaReader/IdeaReader.stories.js
  web/apps/atelier-des-idees/src/components/IdeaReader/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaReader/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaTool/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/IdeaPageTitle/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/_style.scss
  web/apps/atelier-des-idees/src/pages/CreateIdea/containers/CreateIdeaPage.js
  web/apps/atelier-des-idees/src/pages/CreateIdea/index.jsx
Labels: Ready for code review

#3005 Update league/commonmark
  composer.json
  composer.lock
Labels: Ready for code review

#3007 [ADI] #46 Button loading state
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/Button/Button.stories.js
  web/apps/atelier-des-idees/src/components/Button/_style.scss
  web/apps/atelier-des-idees/src/components/Button/index.jsx
  web/apps/atelier-des-idees/src/style/_button.scss
Labels: Ready for code review

#3001 [ADI] #36 delete idea
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/Modal/DeleteIdeaModal/DeleteIdeaModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/DeleteIdeaModal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/DeleteIdeaModal/index.jsx
  web/apps/atelier-des-idees/src/constants/modalTypes.js
  web/apps/atelier-des-idees/src/containers/ModalRoot/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/containers/CreateIdeaPage.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
Labels: Ready for code review

#3002 [ADI] #34 Authentication
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/hocs/withAuth.js
  web/apps/atelier-des-idees/src/redux/actions/auth.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/auth.js
  web/apps/atelier-des-idees/src/redux/reducers/index.js
  web/apps/atelier-des-idees/src/redux/selectors/auth.js
  web/apps/atelier-des-idees/src/redux/store/configStore.dev.js
  web/apps/atelier-des-idees/src/redux/store/configStore.prod.js
  web/apps/atelier-des-idees/src/redux/thunk/auth.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review, Work in progress

#3008 [ADI] #47 CreateIdeaPage refactor
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/TextArea/TextArea.stories.js
  web/apps/atelier-des-idees/src/components/TextArea/_style.scss
  web/apps/atelier-des-idees/src/components/TextArea/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdea/containers/CreateIdeaPage.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/CreateIdeaActions.stories.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/QuestionBlock.stories.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/constants/questions.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/reducers/auth.js
  web/apps/atelier-des-idees/src/redux/thunk/auth.js
Labels: Ready for code review

#3009 Add theme admin
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/services.xml
  app/migrations/Version20181205101657.php
  features/api/ideas_workshop_ideas.feature
  src/Admin/IdeasWorkshopThemeAdmin.php
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Theme.php
  src/IdeasWorkshop/ThemeManager.php
  translations/validators.fr.yml
Labels: Ready for code review

#3012 [ADI] refactor IdeaCard component to match new data structure
  web/apps/atelier-des-idees/src/components/IdeaCard/IdeaCard.stories.js
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCardList/IdeaCardList.stories.js
Labels: Ready for code review

#3010 [ADI] #36 Improve idea delete
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/index.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/redux/actions/currentIdea.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/currentIdea.js
  web/apps/atelier-des-idees/src/redux/reducers/index.js
  web/apps/atelier-des-idees/src/redux/selectors/currentIdea.js
  web/apps/atelier-des-idees/src/redux/store/configStore.dev.js
  web/apps/atelier-des-idees/src/redux/store/configStore.prod.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#3015 [ADI] #38 Idea page back button
  web/apps/atelier-des-idees/src/constants/api.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review
