Repository parti-renaissance/espace-adherent, pull requests merged in 2018-04, with the labels that each got.

#2307 [ch2291] Fix button position in event page
  front/style/layout/_base.scss
  templates/events/_header.html.twig
Labels: Ready for code review

#2183 Revert "Add command 'app:fix-title-case' to fix some text case"
  app/config/services/services.xml
  src/Command/FixTitleCaseCommand.php
  src/Doctrine/DBAL/BatchedConnection.php
  tests/Doctrine/DBAL/BatchedConnectionTest.php
Labels: Ready for code review

#2308 [ch3011] Fix button visual and text and Canary part of the feature
  app/migrations/Version20180314145201.php
  front/style/layout/_buttons.scss
  src/Entity/Adherent.php
  src/Membership/AdherentEmailSubscription.php
  templates/user/set_email_notifications.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#2313 Test Api synchronization commands
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Command/ApiScheduleEventCreationCommandTest.php
Labels: Ready for code review

#2321 Add category name to Event serialization
  src/Entity/Event.php
Labels: Ready for code review

#2319 [ch2794] Active mensual donnation
  front/components/AmountChooser.js
  src/Form/DonationRequestType.php
Labels: Ready for code review

#2322 Handle ClientException when sending an email
  src/Consumer/AbstractMailerConsumer.php
  tests/Consumer/AbstractMailerConsumerTest.php
Labels: Ready for code review

#2330 [ch3241] Remove CampaignSilence Fonctionality
  app/config/services/system.xml
  src/Campaign/CampaignSilenceProcessor.php
  src/Campaign/CampaignSilenceSubscriber.php
  tests/Campaign/CampaignSilenceProcessorTest.php
Labels: Ready for code review

#2331 Removed h1 tags for articles pages
  templates/amp/_layout.html.twig
Labels: Ready for code review

#2329 [ch3324] Modify errors message in adhesion page.
  features/registration.feature
  front/style/mixins/_text.scss
  front/style/pages/_join.scss
  templates/membership/join.html.twig
Labels: Ready for code review

#2332 Mails consumer requires a routing key
  app/config/config.yml
Labels: Ready for code review

#2333 Updated title tag for events and committees pages
  templates/committee/show.html.twig
  templates/events/show.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
Labels: Ready for code review

#2338 Update link to commitees landing page in navigation
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#2335 Synchronize city names
  src/Entity/BaseEvent.php
  src/Entity/Committee.php
  src/Entity/EntityPostAddressTrait.php
Labels: Ready for code review

#2340 Fixed birthday in tests
  tests/Controller/EnMarche/BoardMemberControllerTest.php
Labels: Bug, Ready for code review

#2337 Hotfix city name field
  front/services/address/AddressForm.js
  src/Address/Address.php
Labels: Bug, Ready for code review

#2341 Docker compose dist
  docker-compose.override.yml.dist
Labels: Ready for code review

#2343 Moved AMP script tags
  templates/amp/_layout.html.twig
Labels: Ready for code review

#2346 Fixed search board member test
  tests/Controller/EnMarche/BoardMemberControllerTest.php
Labels: Bug, Ready for code review

#2342 Makefile : Added assets prod check target
  Makefile
Labels: Ready for code review

#2347 Fix age problem in test
  tests/Controller/EnMarche/BoardMemberControllerTest.php
Labels: Ready for code review

#2334 Add Event tags on serialization
  app/config/services/platform.xml
  src/Event/Serializer/EventSerializationSubscriber.php
  src/Referent/ManagedAreaUtils.php
Labels: Ready for code review

#2348 Makefile : Added colors and removed duplicated targets
  Makefile
Labels: Ready for code review

#2349 [ch3212] Some wording change about organizational chart PR
  app/config/services/admin.xml
  features/referent-organizational-chart.feature
  src/Admin/OrganizationalChartItemAdmin.php
  src/Admin/ReferentAdmin.php
  src/Entity/ReferentOrganizationalChart/GroupOrganizationalChartItem.php
  src/Entity/ReferentOrganizationalChart/PersonOrganizationalChartItem.php
  src/Exporter/ReferentPersonLinkExport.php
  src/Form/ReferentPersonLinkType.php
  templates/admin/referent/export_team_xlsx_button.html.twig
  templates/referent/_layout.html.twig
  templates/referent/organizational_chart.html.twig
  translations/SonataAdminBundle.fr.yml
  translations/messages.fr.yml
Labels: Ready for code review

#2350 Add firstname as a default filter on the adherent admin
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#2351 [ch3212] fix display + wording + link admin
  src/Entity/ReferentOrganizationalChart/PersonOrganizationalChartItem.php
  src/Form/ReferentPersonLinkType.php
  templates/admin/organizational_chart/admin_list.html.twig
  templates/referent/edit_referent_person_link.html.twig
  templates/referent/organizational_chart_macros.html.twig
  translations/SonataAdminBundle.fr.yml
  translations/messages.fr.yml
  web/css/organizational_chart.css
Labels: Ready for code review

#2326 Limit length on CKEditors
  src/Committee/Feed/CommitteeMessage.php
  src/Form/CommitteeFeedMessageType.php
  src/Form/ReferentMessageType.php
  src/Referent/ReferentMessage.php
  templates/committee/show.html.twig
  templates/javascript.js.twig
  templates/referent/users_message.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#2357 fix donation test
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Bug, Ready for code review

#2352 Ordered referents listing
  src/Controller/EnMarche/ReferentNominationController.php
  src/Repository/ReferentRepository.php
Labels: Ready for code review

#2355 Sitemap : Added invitation and event registration pages
  src/Sitemap/SitemapFactory.php
Labels: Ready for code review

#2354 Bugfix - redis memory leak - Add a default TTL of 1 day
  app/config/services/system.xml
Labels: Ready for code review

#2360 Fixed logo for AMP pages
  templates/amp/_layout.html.twig
Labels: Ready for code review

#2361 [ch3212] add roles for admin security for organizational chart
  app/config/security.yml
  src/Admin/AdministratorAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
Labels: Bug, Ready for code review

#2363 Donation : Removed subscription durations to keep only the unlimited
  front/components/AmountChooser.js
  front/style/pages/_donation.scss
  src/Controller/EnMarche/DonationController.php
  src/Donation/PayboxPaymentSubscription.php
  src/Form/DonationSubscriptionRequestType.php
  templates/donation/informations.html.twig
  templates/donation/subscription.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review

#2358 Create endpoint for total adherent count + by gender
  features/api/adherents.feature
  src/Controller/Api/AdherentsController.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#2368 Up Symfony 3.4
  app/config/services/workflows.yml
  composer.json
  composer.lock
  src/Form/TypeExtension/PhoneNumberTypeExtension.php
  src/Twig/FormRuntime.php
  templates/form_theme.html.twig
  tests/Controller/EnMarche/Security/AdminSecurityControllerTest.php
Labels: Ready for code review

#2364 Declare vhosts in app service
  docker-compose.override.yml.dist
Labels: Ready for code review

#2370 Added interests form after the account activation by email
  features/registration.feature
  src/Controller/EnMarche/MembershipController.php
Labels: Ready for code review

#2362 Updated CircleCI configuration
  .circleci/config.yml
Labels: Ready for code review

#2365 Remove configure hosts from circleCI config
  .circleci/config.yml
Labels: Ready for code review

#2184 Introduce Referent tags
  app/config/config_test.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/platform.xml
  app/config/services/repositories.xml
  app/config/services/services.xml
  app/migrations/Version20180214173510.php
  behat.yml.dist
  features/admin/adherent.feature
  features/bootstrap/RabbitMqContext.php
  features/bootstrap/ReferentTagContext.php
  features/registration.feature
  features/sync_with_api.feature
  src/Admin/AdherentAdmin.php
  src/Admin/AdministratorAdmin.php
  src/Admin/ReferentTagAdmin.php
  src/Command/ReferentTagImportCommand.php
  src/Command/ReferentTagInitializeCommand.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadReferentManagedUserData.php
  src/DataFixtures/ORM/LoadReferentTagData.php
  src/Doctrine/Hydrators/EventHydrator.php
  src/Entity/Adherent.php
  src/Entity/ManagedArea.php
  src/Entity/Projection/ReferentManagedUser.php
  src/Entity/Projection/ReferentManagedUserFactory.php
  src/Entity/ReferentManagedArea.php
  src/Entity/ReferentTag.php
  src/Form/Admin/ReferentManagedAreaType.php
  src/Form/EventListener/ReferentManagedAreaListener.php
  src/Membership/MembershipRequestHandler.php
  src/Referent/ManagedAreaUtils.php
  src/Referent/ReferentTagManager.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/EventRepository.php
  src/Repository/GeoFilterTrait.php
  src/Repository/NewsletterSubscriptionRepository.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  src/Repository/ReferentTagRepository.php
  templates/admin/adherent/list_managed_area_tags.html.twig
  templates/admin/procuration/referents_invitation_urls.html.twig
  templates/referent/_layout.html.twig
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Entity/AdherentTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/Repository/Projection/ReferentManagedUserRepositoryTest.php
  tests/SqliteWebTestCase.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
Labels: Work in progress

#2257 WIP: [ch2834] A user can see his own donation
  app/config/services/repositories.xml
  features/user_controller_donation.feature
  front/style/pages/_profile.scss
  src/Controller/EnMarche/UserController.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/Entity/Donation.php
  src/Repository/DonationRepository.php
  templates/adherent/_profile_menu.html.twig
  templates/user/my_donation.html.twig
Labels: Needs design, Work in progress

#2373 Small fix on the donation tab page
  templates/user/my_donation.html.twig
Labels: Ready for code review

#2375 Makefile : Added Behat args
  Makefile
Labels: Ready for code review

#2378 [Admin] Fix choice labels
  src/Admin/CitizenActionAdmin.php
  src/Admin/EventAdmin.php
Labels: Bug, Ready for code review

#2376 Added interests form on profile menu
  templates/adherent/_profile_menu.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
Labels: Ready for code review

#2367 Create endpoint for managed adherent count + by gender
  features/api/adherents.feature
  src/Controller/Api/AdherentsController.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#2381 Assign tags on adherent registration
  src/Membership/MembershipRequestHandler.php
Labels: Ready for code review

#2382 Test referent tag assignation on adhesion
  features/registration.feature
Labels: Ready for code review

#2380 Added adherents counter on adhesion page
  src/Controller/EnMarche/MembershipController.php
  templates/membership/join.html.twig
Labels: Ready for code review

#2379 Add related codes to local codes
  src/Referent/ManagedAreaUtils.php
  src/Referent/ReferentTagManager.php
  src/Repository/ReferentTagRepository.php
  src/Utils/AreaUtils.php
  tests/Referent/ManagedAreaUtilsTest.php
  tests/Utils/AreaUtilsTest.php
Labels: Ready for code review

#2387 Sync Events at Event registrations
  src/Event/EventRegistrationCommandHandler.php
Labels: Ready for code review

#2371 Limit User serialized data
  src/Entity/Adherent.php
Labels: Ready for code review
