Repository parti-renaissance/espace-adherent, pull requests merged in 2019-11, with the labels that each got.

#4051 Oauth password grant type
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
  src/AdherentMessage/Listener/InitialiseMailchimpCampaignEntitySubscriber.php
  src/OAuth/AuthorizationServerFactory.php
  src/OAuth/Repository/OAuthUserRepository.php
  src/Repository/AdherentRepository.php
  templates/message/list.html.twig
Labels: Ready for code review

#4055 [CKEditor] remove MediaEmbed and code features
  .babelrc
  .browserslistrc
  front/app.js
  front/kernel.js
  front/services/form/CKEditor.js
Labels: Ready for code review

#4056 Fix municipal event iCal export
  src/Serializer/EventICalHandler.php
  tests/Serializer/EventIcalHandlerTest.php
Labels: Bug, Ready for code review

#4057 [ReferentUsers] hide phone number for unsubscribed users
  migrations/Version20191106103516.php
  src/Command/PopulateManagedUsersByReferentCommand.php
  src/DataFixtures/ORM/LoadReferentManagedUserData.php
  src/Entity/Projection/ReferentManagedUser.php
  src/Entity/Projection/ReferentManagedUserFactory.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  templates/referent/users_list.html.twig
Labels: Ready for code review

#4052 Add warning for IE browser and improbe webpack build
  templates/base.html.twig
Labels: Ready for code review

#4058 [Mooc] improve admin Mooc panel and add new image field
  app/config/services/admin.xml
  features/api/mooc.feature
  migrations/Version20191107005436.php
  src/Admin/ExecutiveOfficeMemberAdmin.php
  src/Admin/Extension/ImageUploadExtension.php
  src/Admin/ImageUploadAdminInterface.php
  src/Admin/MoocAdmin.php
  src/Admin/TurnkeyProjectAdmin.php
  src/DataFixtures/ORM/LoadMoocData.php
  src/Entity/Image.php
  src/Entity/Mooc/Mooc.php
  src/Form/ImageType.php
  src/Mooc/MoocManager.php
  src/Normalizer/MoocNormalizer.php
  src/Serializer/MoocSerializerSubscriber.php
  src/Validator/ImageObject.php
  src/Validator/ImageObjectValidator.php
  templates/admin/list/list_image_miniature.html.twig
  templates/admin/list/list_mooc_thumbnail.html.twig
  templates/admin/list/list_thumbnail.html.twig
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4062 [MailTransac] fix empty first name
  src/Mailer/Message/DataSurveyAnsweredMessage.php
Labels: Bug, Ready for code review

#4065 [AdherentMessage] add char counter
  front/app.js
  front/services/form/CKEditor.js
  src/Form/AdherentMessage/AdherentMessageType.php
  templates/message/create.html.twig
  yarn.lock
Labels: Ready for code review

#4066 [AdherentMessage] rollback CKEditor to v4
  templates/message/create.html.twig
Labels: Ready for code review

#4067 [Mooc] add image/video validation
  src/Entity/Mooc/Mooc.php
  translations/validators.fr.yml
Labels: Ready for code review

#4068 CSS ajustment
  front/components/ProgrammaticFoundation/Legend.js
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/components/ProgrammaticFoundation/SearchBar.js
  front/components/ProgrammaticFoundation/ToggleLeadingMeasures.js
  front/style/layout/_forms-em.scss
  front/style/pages/_programmatic_foundation.scss
  web/images/icons/icn-form-search.svg
Labels: Work in progress

#4073 [Referent] Always show phone number and display SMS/MMS preferences
  composer.lock
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4075 Socle muni tag filter
  front/components/ProgrammaticFoundation/Breadcrumbs.js
  front/components/ProgrammaticFoundation/Content.js
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/components/ProgrammaticFoundation/SearchBar.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/ToggleLeadingMeasures.js
  front/services/programmatic-foundation/SearchEngine.js
  front/style/app.scss
  front/style/layout/_forms-em.scss
  front/style/layout/_power-select.scss
  front/style/pages/_programmatic_foundation.scss
  package.json
  templates/programmatic_foundation/approaches.html.twig
  templates/programmatic_foundation/view_measure.html.twig
  yarn.lock
Labels: Ready for code review

#4078 Remove Measure slug and fix tag filter
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/Project.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/SubApproach.js
  front/services/programmatic-foundation/SearchEngine.js
  front/style/pages/_programmatic_foundation.scss
  migrations/Version20191118115449.php
  src/Admin/Extension/ImageUploadExtension.php
  src/Controller/EnMarche/ProgrammaticFoundationController.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/ProgrammaticFoundation/Approach.php
  src/Entity/ProgrammaticFoundation/Measure.php
  src/Entity/ProgrammaticFoundation/Project.php
  src/Entity/ProgrammaticFoundation/SubApproach.php
  src/Entity/ProgrammaticFoundation/Tag.php
  templates/admin/programmatic_foundation/measure/link.html.twig
  templates/programmatic_foundation/_children.html.twig
  templates/programmatic_foundation/view_measure.html.twig
Labels: Bug, Ready for code review

#4079 Fix measure open click
  front/components/ProgrammaticFoundation/Measure.js
Labels: Bug, Ready for code review

#4077 Update wording on error page
  translations/messages.fr.yml
Labels: Ready for code review

#4081 Remove measure slug from admin
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/style/pages/_programmatic_foundation.scss
  src/Admin/ProgrammaticFoundation/MeasureAdmin.php
  templates/programmatic_foundation/view_measure.html.twig
Labels: Bug, Ready for code review

#4082 Allow to use image for mooc element
  app/config/services/admin.xml
  app/config/services/twig.xml
  composer.json
  composer.lock
  migrations/Version20191119002650.php
  src/Admin/MoocElementAdmin.php
  src/DataFixtures/ORM/LoadMoocQuizData.php
  src/DataFixtures/ORM/LoadMoocVideoData.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/MoocElementTypeEnum.php
  src/Entity/Mooc/MoocImageElement.php
  src/Entity/Mooc/MoocQuizElement.php
  src/Entity/Mooc/MoocVideoElement.php
  src/Normalizer/MoocNormalizer.php
  src/Twig/MoocElementExtension.php
  templates/admin/layout.html.twig
  templates/admin/mooc/list_type.html.twig
  templates/form_theme_admin.html.twig
  templates/javascript.js.twig
Labels: Ready for code review

#4083 [Test] Update Event begin date for fixing randomly failed test
  src/DataFixtures/ORM/LoadEventData.php
  src/Repository/EventRepository.php
  templates/programmatic_foundation/view_measure.html.twig
Labels: Ready for code review

#4084 [ProgrammaticFoundation] Override list style
  front/components/ProgrammaticFoundation/Measure.js
  front/services/programmatic-foundation/SearchEngine.js
  front/style/pages/_programmatic_foundation.scss
  package.json
  src/Entity/Mooc/Mooc.php
  yarn.lock
Labels: Bug, Ready for code review

#4080 Fix events timezones
  src/Serializer/CitizenActionICalHandler.php
  src/Serializer/EventICalHandler.php
  templates/committee/timeline/_event.html.twig
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Serializer/EventIcalHandlerTest.php
Labels: Work in progress

#4085 Hotfixes on je-vote page
  templates/adherent/my_vote.html.twig
Labels: Ready for code review

#4088 Remove Canary mode from MyVote page
  src/Controller/EnMarche/MyVoteController.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4087 Reorg socle programme
  front/components/ProgrammaticFoundation/Breadcrumbs.js
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/SubApproach.js
  front/components/ProgrammaticFoundation/ToggleLeadingMeasures.js
  front/style/mixins/_colors.scss
  front/style/pages/_programmatic_foundation.scss
  templates/programmatic_foundation/approaches.html.twig
Labels: Ready for code review

#4089 [Admin] add new Senator role
  features/admin/adherent.feature
  features/api/adherents.feature
  migrations/Version20191121124258.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/ReferentTag.php
  src/Entity/SenatorArea.php
  src/Form/Admin/SenatorAreaType.php
  src/Twig/AdherentRuntime.php
  templates/admin/adherent/list_status.html.twig
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#4092 Import & reset programmatic foundation commands
  app/config/services/services.xml
  src/Command/ImportProgrammaticFoundationCommand.php
Labels: Ready for code review

#4093 [Article] add Media validation
  src/Entity/Article.php
  templates/article/actualites.html.twig
  tests/Admin/ArticleAdminTest.php
Labels: Bug, Ready for code review

#4094 Fix import strategy
  src/Command/ImportProgrammaticFoundationCommand.php
Labels: Ready for code review

#4091 Add reminder links on programme page
  front/style/content/_program.scss
  templates/program/index.html.twig
Labels: Ready for code review

#4095 Hotfixes on search inputs + approaches sizes
  front/components/ProgrammaticFoundation/Breadcrumbs.js
  front/style/pages/_programmatic_foundation.scss
Labels: Ready for code review

#4098 [VoteStatuts] Change intro for the top depart
  app/data/static/infographie-reforme-statuts.jpg
  templates/adherent/my_vote.html.twig
Labels: Ready for code review

#4086 Add command for updating District geo data
  app/config/services/messenger.yml
  app/config/services/services.xml
  src/Adherent/Command/UpdateReferentTagOnDistrictCommand.php
  src/Adherent/Handler/UpdateReferentTagOnDistrictCommandHandler.php
  src/Command/InitializeReferentTagsForDistrictsOnAdherentsCommand.php
  src/Command/UpdateDistrictGeoPolygonCommand.php
  src/Command/UpdateReferentTagsForDistrictsOnAdherentsCommand.php
  src/Deputy/DistrictLoader.php
  src/Entity/District.php
  src/Geo/GeometryFactory.php
  src/Messenger/Message/AsynchronousMessageInterface.php
Labels: Ready for code review

#4101 Update doctrine/orm and increase timeout mailjet api
  app/config/config.yml
  composer.lock
Labels: Bug, Ready for code review

#4102 Update Mun2020 nav
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4103 Fix php warnigs
  composer.lock
  src/Command/MailchimpSegmentUpdateDbSegmentIdsCommand.php
  src/Entity/District.php
  src/Interactive/MyEuropeProcessor.php
  src/TonMacron/InvitationProcessor.php
Labels: Ready for code review

#4104 Update district relation and improve admin district setting field
  migrations/Version20191128155145.php
  src/Admin/AdherentAdmin.php
  src/Admin/DistrictAdmin.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/Entity/Adherent.php
  src/Entity/District.php
  src/Form/Admin/AvailableDistrictAutocompleteType.php
Labels: Ready for code review

#4105 [Event] set timezone data on iCal export
  app/config/services/system.xml
  src/Serializer/CitizenActionICalHandler.php
  src/Serializer/EventICalHandler.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Serializer/EventIcalHandlerTest.php
Labels: Ready for code review

#4106 Remove Measure numbers
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/SubApproach.js
  front/services/programmatic-foundation/SearchEngine.js
  front/style/pages/_programmatic_foundation.scss
  templates/programmatic_foundation/view_measure.html.twig
  web/images/check.svg
Labels: Ready for code review

#4107 [Mooc] Fix admin delete action on mooc element
  src/Admin/Extension/ImageUploadExtension.php
  src/Admin/MoocElementAdmin.php
Labels: Bug, Ready for code review

#4100 Add endpoint for CRM Paris
  app/config/security.yml
  src/Controller/Api/CrmParisController.php
  src/Csv/CsvResponseFactory.php
  src/DataFixtures/ORM/LoadClientData.php
  src/OAuth/Model/Scope.php
  src/Repository/AdherentRepository.php
  tests/Controller/Api/CrmParisControllerTest.php
Labels: Ready for code review
