Repository parti-renaissance/espace-adherent, pull requests merged in 2019-04, with the labels that each got.

#3521 Add search only of referent events
  front/services/api/ReqwestApiClient.js
  front/style/pages/_search.scss
  src/Repository/EventRepository.php
  src/Search/SearchParametersFilter.php
  templates/search/_filters.html.twig
  templates/search/search.html.twig
  tests/Controller/EnMarche/SearchControllerTest.php
Labels: Ready for code review

#3522 Fix tests after changing times
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3523 Add referent tags to CA and synchronize them with API
  app/migrations/Version20190401172021.php
  features/sync_with_api.feature
  src/Admin/CitizenActionAdmin.php
  src/Entity/BaseEvent.php
  src/Entity/CitizenAction.php
  src/Entity/EntityReferentTagTrait.php
  src/Entity/Event.php
  src/Entity/InstitutionalEvent.php
  src/Event/EventFactory.php
Labels: Ready for code review

#3524 Rename 'bannir' to 'exclure'
  src/Controller/Admin/AdminBanAdherentController.php
  templates/admin/adherent/action_button_ban.html.twig
  templates/admin/adherent/ban.html.twig
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#3528 Change wording of sms notification checkbox
  templates/membership/join.html.twig
Labels: Ready for code review

#3525 Date without time for 'registered_at' in the committee members export
  src/Committee/Serializer/AdherentCsvSerializer.php
  tests/Committee/Serializer/AdherentCsvSerializerTest.php
Labels: Ready for code review

#3527 Apply Republican silence for referent message space
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
Labels: Ready for code review

#3530 [Admin] Add canary tester filter
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#3532 Change wording of sms notification checkbox
  templates/membership/join.html.twig
Labels: Ready for code review

#3529 [AdherentMessage] Remove email from Mailchimp on user deletion
  app/config/services/services.xml
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Command/AdherentDeleteCommand.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/AdherentDeleteCommandHandler.php
Labels: Ready for code review

#3533 Change CSV to XLS committee members export
  app/config/services/services.xml
  src/Committee/Serializer/AdherentCsvSerializer.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Entity/Adherent.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Serializer/XlsxEncoder.php
  tests/Committee/Serializer/AdherentCsvSerializerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Serializer/XlsxEncoderTest.php
Labels: Ready for code review

#3531 [AdherentMessage] Mark as unsubscribed member disabled adherent
  src/Admin/AdherentAdmin.php
  src/Command/MailchimpSyncAllAdherentsCommand.php
  src/Entity/Adherent.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#3489 [AdherentMessage] Move supervisor message to mailchimp
  app/config/services/services.xml
  app/migrations/Version20190327135856.php
  composer.json
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/Command/MailchimpSegmentUpdateDbSegmentIdsCommand.php
  src/Command/MailchimpSyncAllCommitteeMembershipsCommand.php
  src/Command/MailchimpSyncAllCommitteesCommand.php
  src/Command/MailchimpUpdateReferentTagExternalIdFromMailchimpCommand.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/CommitteeAdherentMessage.php
  src/Entity/AdherentMessage/Filter/CommitteeFilter.php
  src/Form/AdherentMessage/AdherentMessageType.php
  src/Form/AdherentMessage/CommitteeFilterType.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Form/AdherentMessage/ReferentZoneFilterType.php
  src/Form/MyCommitteeChoiceType.php
  src/Form/MyReferentTagChoiceType.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  templates/components/_nav_desktop.html.twig
  templates/form_theme.html.twig
  templates/message/filter/committee.html.twig
  tests/Controller/EnMarche/AdherentMessage/CommitteeMessageControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3534 [Procuration] Add fields region, state and reachable on procuration proxy and request
  app/migrations/Version20190404112349.php
  features/procuration_proxy.feature
  features/procuration_request.feature
  front/app.js
  front/pages/procuration_proxy.js
  front/pages/procuration_request.js
  front/services/form/changeStateFieldVisibility.js
  src/Admin/ProcurationProxyAdmin.php
  src/Admin/ProcurationRequestAdmin.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Form/Procuration/AbstractProcurationType.php
  src/Form/Procuration/ProcurationProxyType.php
  src/Form/Procuration/ProcurationRequestType.php
  templates/admin/procuration/proxy_list_status.html.twig
  templates/procuration/election_rounds.html.twig
  templates/procuration/profile.html.twig
  templates/procuration/proposal.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3547 [AdherentMessage] Reject message instead requeue on exception
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Mailchimp/Exception/InvalidFilterException.php
Labels: Bug, Ready for code review

#3551 Remove [Référent] from sender name for referent messages
  src/Entity/AdherentMessage/ReferentAdherentMessage.php
  src/Mailer/Message/ReferentMessage.php
Labels: Ready for code review

#3550 Command to import donation coordinates
  app/config/services/services.xml
  src/Command/ImportDonationCoordinatesCommand.php
Labels: Ready for code review

#3548 [AdherentMessage] Create static segment for Citizen project
  app/config/services/services.xml
  app/migrations/Version20190408173240.php
  src/AdherentMessage/Command/CreateCommitteeStaticSegmentCommand.php
  src/AdherentMessage/Command/CreateStaticSegmentCommand.php
  src/AdherentMessage/Handler/CreateCommitteeStaticSegmentCommandHandler.php
  src/AdherentMessage/Handler/CreateStaticSegmentCommandHandler.php
  src/AdherentMessage/Listener/CreateCommitteeStaticSegmentListener.php
  src/AdherentMessage/Listener/CreateStaticSegmentListener.php
  src/AdherentMessage/StaticSegmentInterface.php
  src/CitizenAction/CitizenActionManager.php
  src/CitizenProject/CitizenProjectManagementAuthority.php
  src/CitizenProject/CitizenProjectManager.php
  src/CitizenProject/CitizenProjectMessageNotifier.php
  src/Controller/EnMarche/CitizenProjectController.php
  src/Entity/CitizenProject.php
  src/Entity/Committee.php
  src/Events.php
  tests/Admin/CommitteeAdminTest.php
  tests/CitizenProject/CitizenProjectManagementAuthorityTest.php
  tests/CitizenProject/CitizenProjectManagerTest.php
Labels: Ready for code review

#3557 [AdherentMessage] Add Content sections to Committee message
  app/config/services/services.xml
  src/Mailchimp/Campaign/CampaignContentRequestBuilder.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/ContentSection/CommitteeMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/ContentSectionBuilderInterface.php
  src/Mailchimp/Campaign/ContentSection/DeputyMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/ReferentMessageSectionBuilder.php
  src/Mailchimp/Manager.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#3554 [REFERENT SPACE] Save referent space page access dates
  app/config/services/services.xml
  app/migrations/Version20190409152550.php
  src/Controller/EnMarche/ReferentController.php
  src/Entity/ReferentSpaceAccessInformation.php
  src/EventListener/RecordReferentLastVisitListener.php
  src/Repository/ReferentSpaceAccessInformationRepository.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Entity/ReferentSpaceAccessInformationTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#3559 [Procuration] Fix bug on state validation and add postal code logic
  features/procuration_proxy.feature
  features/procuration_request.feature
  front/app.js
  front/pages/procuration_proxy.js
  front/pages/procuration_request.js
  front/services/form/changeFieldsVisibility.js
  front/services/form/changeStateFieldVisibility.js
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  templates/procuration/profile.html.twig
  templates/procuration/proposal.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3564 [Procuration] Fix widget conflict
  front/pages/procuration_proxy.js
  front/pages/procuration_request.js
  front/services/form/changeFieldsVisibility.js
Labels: Ready for code review

#3539 [Assessor] Add new role and space for assessor management
  app/config/services/admin.xml
  app/migrations/Version20190402144714.php
  app/migrations/Version20190412114157.php
  features/adherent_dashboard.feature
  features/admin/adherent.feature
  features/api/adherents.feature
  front/app.js
  front/pages/assessor_manager_requests.js
  front/pages/assessor_manager_vote_places.js
  front/services/api/ReqwestApiClient.js
  front/style/app.scss
  front/style/pages/_assessor.scss
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/SummaryAdmin.php
  src/Assessor/AssessorManager.php
  src/Assessor/Filter/AssessorFilters.php
  src/Assessor/Filter/AssessorRequestFilters.php
  src/Assessor/Filter/VotePlaceFilters.php
  src/Controller/EnMarche/AssessorManagerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/DataFixtures/ORM/LoadVotePlaceData.php
  src/Entity/ActionEnum.php
  src/Entity/Adherent.php
  src/Entity/AssessorManagedArea.php
  src/Entity/AssessorRequest.php
  src/Entity/ManagedArea.php
  src/Entity/ProcurationManagedArea.php
  src/Entity/VotePlace.php
  src/Exception/AssessorException.php
  src/Repository/AbstractAssessorRepository.php
  src/Repository/AssessorRequestRepository.php
  src/Repository/VotePlaceRepository.php
  src/Security/Voter/ManageAssessorVoter.php
  templates/adherent/dashboard.html.twig
  templates/assessor_manager/_assessor_profile.html.twig
  templates/assessor_manager/_layout.html.twig
  templates/assessor_manager/_requests_list.html.twig
  templates/assessor_manager/_vote_place_profile.html.twig
  templates/assessor_manager/_vote_places_list.html.twig
  templates/assessor_manager/associate.html.twig
  templates/assessor_manager/deassociate.html.twig
  templates/assessor_manager/request.html.twig
  templates/assessor_manager/requests.html.twig
  templates/assessor_manager/vote_places.twig
  templates/components/_nav_desktop.html.twig
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Entity/AssessorRequestTest.php
  tests/Repository/AdherentRepositoryTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#3560 [REFERENT SPACE] Change interests filter to multi select
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Form/AdherentMessage/ReferentFilterType.php
  templates/message/filter.html.twig
  templates/message/filter/_referent_full_filter_form.html.twig
  templates/message/filter/committee.html.twig
  templates/message/filter/deputy.html.twig
  templates/message/filter/referent.html.twig
  templates/referent/users_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3541 [Referent Space] UI update integration
  features/referent-organizational-chart.feature
  front/components/DataGrid.js
  front/style/app.scss
  front/style/layout/_base.scss
  front/style/layout/_buttons.scss
  front/style/layout/_forms.scss
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_filters.scss
  front/style/manager-space/_forms.scss
  front/style/manager-space/_tables.scss
  front/style/manager-space/roles/_referent.scss
  front/style/mixins/_colors.scss
  front/style/mixins/_text.scss
  front/style/pages/_org-chart.scss
  src/Controller/EnMarche/ReferentController.php
  templates/message/_layout.html.twig
  templates/message/create.html.twig
  templates/message/filter/deputy.html.twig
  templates/message/list.html.twig
  templates/referent/_layout.html.twig
  templates/referent/committees_list.html.twig
  templates/referent/edit_referent_person_link.html.twig
  templates/referent/event_create.html.twig
  templates/referent/events_list.html.twig
  templates/referent/institutional_events/create.html.twig
  templates/referent/institutional_events/list.html.twig
  templates/referent/organizational_chart.html.twig
  templates/referent/organizational_chart_macros.html.twig
  templates/referent/surveys/local_surveys_list.html.twig
  templates/referent/users_list.html.twig
  templates/referent/users_message.html.twig
  tests/Controller/EnMarche/DeputyControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  yarn.lock
Labels: Ready for code review

#3562 [REFERENT SPACE] Show email subscription status in the adherents list and add its filter
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadReferentManagedUserData.php
  src/Referent/ManagedUsersFilter.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Repository/Projection/ReferentManagedUserRepositoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3569 [REFERENT SPACE] Show previous connection date in the referent space
  app/config/services/twig.xml
  src/Repository/ReferentSpaceAccessInformationRepository.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/referent/_layout.html.twig
Labels: Ready for code review

#3573 Update Symfony to 3.4.25
  composer.lock
Labels: Ready for code review

#3574 [Assessor] Added new checkboxes
  app/migrations/Version20190416145936.php
  front/style/pages/_assessor.scss
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestFactory.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/AssessorRequest.php
  src/Entity/VotePlace.php
  src/Form/AssessorRequestType.php
  templates/assessor/_fill_assessor_info.html.twig
  templates/assessor/_fill_personal_info.html.twig
  templates/assessor/_valid_summary.html.twig
  tests/Controller/EnMarche/AssessorControllerTest.php
Labels: Ready for code review

#3576 [Assessor] Fix bug on matching foreign country
  src/Command/ImportVotePlacesCommand.php
  src/Repository/AbstractAssessorRepository.php
  src/Repository/AssessorRequestRepository.php
  src/Repository/VotePlaceRepository.php
  templates/assessor_manager/_requests_list.html.twig
Labels: Ready for code review

#3568 [AdherentMessage] Add committee dashboard and apply new layout
  docker-compose.override.yml.dist
  features/republican_silence.feature
  front/style/app.scss
  front/style/mixins/_colors.scss
  front/style/mixins/_text.scss
  front/style/pages/_adherent-space.scss
  front/utils/dom.js
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Controller/EnMarche/CommitteeSpaceController.php
  src/Entity/AdherentMessage/CommitteeAdherentMessage.php
  src/Entity/AdherentMessage/Filter/CommitteeFilter.php
  src/Form/MyCommitteeChoiceType.php
  src/Repository/AdherentMessageRepository.php
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  templates/citizen_project/_sidebar.html.twig
  templates/citizen_project/show_base.html.twig
  templates/committee/_host_header.html.twig
  templates/committee/demote_host.html.twig
  templates/committee/promote_host.html.twig
  templates/committee/show.html.twig
  templates/committee/timeline/_feed.html.twig
  templates/committee/timeline/edit.html.twig
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/_layout_committee.html.twig
  templates/committee_manager/add_event.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/committee_manager/demote_host.html.twig
  templates/committee_manager/edit.html.twig
  templates/committee_manager/list_members.html.twig
  templates/committee_manager/promote_host.html.twig
  templates/components/_nav_desktop.html.twig
  templates/message/_base_committee.html.twig
  templates/message/_layout.html.twig
  templates/message/create.html.twig
  templates/message/filter.html.twig
  templates/message/filter/committee.html.twig
  templates/message/list.html.twig
  templates/message/preview.html.twig
  tests/Controller/EnMarche/AdherentMessage/CommitteeMessageControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3575 [Referent Space] UI update integration 2
  front/components/DataGrid.js
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_forms.scss
  front/style/manager-space/_tables.scss
  front/style/mixins/_colors.scss
  templates/javascript.js.twig
  templates/referent/_layout.html.twig
  templates/referent/users_list.html.twig
  web/images/icons/icn-form-select.svg
  web/images/icons/pager/icn-pager-next.svg
  web/images/icons/pager/icn-pager-prec.svg
Labels: Ready for code review

#3583 [Assessor] Added email confirmation
  app/config/services/services.xml
  app/config/services/workflows.yml
  src/Assessor/AssessorRequestEnum.php
  src/Assessor/AssessorRequestNotifier.php
  src/Mailer/Message/AssessorRequestConfirmationMessage.php
  tests/Controller/EnMarche/AssessorControllerTest.php
Labels: Ready for code review

#3586 [REFERENT SPACE] Re-add multiselect
  templates/referent/users_list.html.twig
Labels: Ready for code review

#3589 [Assessor] Fixed nullable var for confirmation message
  src/Mailer/Message/AssessorRequestConfirmationMessage.php
Labels: Bug, Ready for code review

#3581 [ADMIN] Remove Committee delete action
  src/Admin/CitizenActionAdmin.php
  src/Admin/CitizenProjectAdmin.php
  src/Admin/CommitteeAdmin.php
  src/Admin/EventAdmin.php
Labels: Ready for code review

#3580 [Procuration] Update procuration request legal mention
  templates/procuration/election_rounds.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
Labels: Ready for code review

#3579 [Procuration] Update procuration proxy legal mention
  templates/procuration/proposal.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
Labels: Ready for code review

#3590 [REFERENT SPACE] Fix JS
  templates/referent/users_list.html.twig
Labels: Ready for code review

#3588 Add CP space
  features/adherent_dashboard.feature
  features/republican_silence.feature
  front/style/layout/_layout.scss
  src/Controller/EnMarche/CitizenProjectController.php
  src/Controller/EnMarche/CitizenProjectManagerController.php
  src/Controller/EnMarche/CitizenProjectMediaGeneratorController.php
  src/Controller/EnMarche/CitizenProjectSpaceController.php
  templates/adherent/dashboard.html.twig
  templates/citizen_project/_layout.html.twig
  templates/citizen_project/_sidebar.html.twig
  templates/citizen_project/_space_layout.html.twig
  templates/citizen_project/dashboard.html.twig
  templates/citizen_project/edit.html.twig
  templates/citizen_project/list_actors.html.twig
  templates/citizen_project/media_generator.html.twig
  templates/citizen_project/show_base.html.twig
  templates/committee_manager/_space_layout.html.twig
  templates/committee_manager/add_event.html.twig
  templates/committee_manager/edit.html.twig
  templates/committee_manager/list_members.html.twig
  templates/committee_manager/promote_host.html.twig
  templates/components/_nav_desktop.html.twig
  templates/message/_base_committee.html.twig
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Controller/EnMarche/CitizenProjectMediaGeneratorControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3543 [REFERENT SPACE] Add citizen projects to referent space
  app/config/services/services.xml
  features/citizen_project.feature
  features/referent_space.feature
  src/Controller/EnMarche/ReferentController.php
  src/Referent/ManagedCitizenProjectsExporter.php
  src/Repository/CitizenProjectRepository.php
  templates/referent/_layout.html.twig
  templates/referent/base_group_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3537 Geocode donations
  src/Donation/DonationWasCreatedEvent.php
  src/Geocoder/Subscriber/EntityAddressGeocodingSubscriber.php
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review

#3600 [REFERENT SPACE] Fix select on the messaging page
  templates/message/filter/referent.html.twig
Labels: Ready for code review

#3601 [Lib Phone Number] Update liphonenumber-for-php
  composer.lock
Labels: Ready for code review

#3596 [Procuration] Add state in procuration manager area
  app/config/config.yml
  src/Mailer/Message/ProcurationProxyCancelledMessage.php
  src/Procuration/ProcurationProxyMessageFactory.php
  templates/procuration_manager/_requests_list.html.twig
  templates/procuration_manager/associate.html.twig
  templates/procuration_manager/deassociate.html.twig
  templates/procuration_manager/request.html.twig
  tests/Procuration/ProcurationProxyMessageFactoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3602 Update symfony/symfony & symfony/phpunit-bridge
  composer.lock
Labels: Ready for code review

#3594 [ADHERENT SPACE] Various CSS fixes
  app/migrations/Version20190423130626.php
  front/components/DataGrid.js
  front/components/MessageStatusLoader.js
  front/style/app.scss
  front/style/layout/_banners.scss
  front/style/layout/_base.scss
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_filters.scss
  front/style/manager-space/_tables.scss
  front/style/mixins/_colors.scss
  front/style/pages/_adherent-messages.scss
  front/style/pages/_committee.scss
  src/Admin/CommitteeAdmin.php
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeFactory.php
  src/Committee/CommitteeUpdateCommandHandler.php
  src/Entity/Committee.php
  src/Form/CommitteeCommandType.php
  templates/committee/_form.html.twig
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/_space_layout.html.twig
  templates/committee_manager/add_event.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/committee_manager/list_members.html.twig
  templates/components/alert_european_elections.html.twig
  templates/deputy/_layout.html.twig
  templates/message/create.html.twig
  templates/message/filter.html.twig
  templates/message/list.html.twig
  templates/message/preview.html.twig
  templates/referent/_layout.html.twig
  templates/referent/base_group_list.html.twig
  templates/referent/event_create.html.twig
  templates/referent/events_list.html.twig
  templates/referent/institutional_events/create.html.twig
  templates/referent/institutional_events/list.html.twig
  templates/referent/surveys/create.html.twig
  templates/referent/users_list.html.twig
  tests/Committee/CommitteeCommandTest.php
  tests/Committee/CommitteeFactoryTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Entity/CommitteeTest.php
Labels: Ready for code review

#3604 [REFERENT SPACE][ADMIN] Add co-referent tag and filter to adherents page
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  templates/admin/adherent/list_status.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3603 [CommitteeMessage] Send message in timeline
  app/migrations/Version20190424105726.php
  src/AdherentMessage/AdherentMessageDataObject.php
  src/AdherentMessage/CommitteeAdherentMessageDataObject.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/CommitteeAdherentMessage.php
  src/Form/AdherentMessage/CommitteeAdherentMessageType.php
  templates/committee_manager/dashboard.html.twig
  templates/message/committee_create.html.twig
  templates/message/committee_update.html.twig
  templates/message/create.html.twig
  tests/Controller/EnMarche/AdherentMessage/CommitteeMessageControllerTest.php
Labels: Ready for code review

#3595 [CP/Committee member] Add adhesion date to member tables
  src/Event/EventCommand.php
  templates/citizen_project/list_actors.html.twig
  templates/committee_manager/list_members.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#3558 Split symfony monolit package
  app/AppKernel.php
  app/config/services/system.xml
  composer.json
  composer.lock
  src/Entity/AbstractTranslatableEntity.php
  src/Entity/Timeline/Measure.php
  src/Entity/Timeline/Profile.php
  src/Entity/Timeline/Theme.php
  src/Form/EventListener/EmptyTranslationRemoverListener.php
  src/Redirection/Dynamic/RedirectionManager.php
  tests/Entity/TranslatableEntityTest.php
Labels: Ready for code review

#3606 [REFERENT SPACE] Add co-referent space
  features/referent-organizational-chart.feature
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadOrganizationalChartItemData.php
  src/Form/ReferentPersonLinkForCoReferentType.php
  src/Twig/AdherentRuntime.php
  templates/adherent/dashboard.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/referent/_layout.html.twig
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3608 Fixed committees search
  templates/search/search.html.twig
Labels: Bug, Ready for code review

#3567 [Dev] Add Doctrine stats bundle
  app/AppKernel.php
  app/config/config_dev.yml
  composer.json
  composer.lock
Labels: Ready for code review

#3611 [Fix] Add missing symfony packages
  composer.json
  composer.lock
Labels: Bug, Ready for code review

#3617 [Test] Fix date format
  tests/Validator/DateRangeValidatorTest.php
Labels: Ready for code review

#3615 [Referent Space] Add adhesion date filter
  app/migrations/Version20190426172030.php
  src/Entity/ReferentManagedUsersMessage.php
  src/Referent/ManagedUsersFilter.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  templates/referent/users_list.html.twig
Labels: Ready for code review

#3613 [REFERENT SPACE] Add sending test mail
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/DataFixtures/ORM/LoadAdherentMessageData.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  templates/message/preview.html.twig
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3621 [REFERENT SPACE] Show organizer full name on events page
  src/Referent/ManagedEventsExporter.php
  tests/Referent/ManagedEventsExporterTest.php
Labels: Ready for code review

#3614 [Assessor] Added VotePlace factory
  src/Command/ImportVotePlacesCommand.php
  src/DataFixtures/ORM/LoadVotePlaceData.php
  src/Entity/AssessorRequest.php
  src/Entity/VotePlace.php
  src/VotePlace/VotePlaceFactory.php
Labels: Ready for code review

#3610 [Assessor] Automatically filled the assessor city field by postal code
  app/migrations/Version20190426110248.php
  src/Assessor/AssessorRequestCommand.php
  src/Entity/AssessorRequest.php
  src/Form/AssessorRequestType.php
  templates/assessor/_fill_assessor_info.html.twig
  templates/assessor/request.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#3620 [ReferentSpace] fix subscription count
  src/Controller/EnMarche/ReferentController.php
  templates/citizen_project/dashboard.html.twig
  templates/form_theme.html.twig
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3618 [ADHERENT SPACE] Various CSS fixes #3
  front/components/DataGrid.js
  front/components/MessageStatusLoader.js
  front/style/layout/_loader.scss
  front/style/manager-space/_forms.scss
  front/style/manager-space/_tables.scss
  templates/message/create.html.twig
  templates/message/filter/citizen_project.html.twig
  templates/message/filter/committee.html.twig
  templates/message/preview.html.twig
  templates/referent/users_list.html.twig
  templates/referent/users_message.html.twig
Labels: Ready for code review

#3591 [Assessor] Add filters on assessor request and vote places for the manager area
  src/Assessor/Filter/AssessorFilters.php
  src/Assessor/Filter/AssessorRequestFilters.php
  src/Assessor/Filter/VotePlaceFilters.php
  src/Controller/EnMarche/AssessorManagerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  templates/assessor_manager/_filters.html.twig
  templates/assessor_manager/_filters_assessor_requests.html.twig
  templates/assessor_manager/requests.html.twig
  templates/assessor_manager/vote_places.twig
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Work in progress

#3619 [Assessor] Update wording
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestFactory.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/AssessorRequest.php
  src/Form/AssessorRequestType.php
  templates/assessor/_fill_assessor_info.html.twig
  templates/assessor/_fill_personal_info.html.twig
  tests/Controller/EnMarche/AssessorControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3625 [REFERENT SPACE] Add managed zone filter
  app/migrations/Version20190430130242.php
  src/Controller/EnMarche/ReferentController.php
  src/Entity/ReferentManagedUsersMessage.php
  src/Referent/ManagedUsersFilter.php
  src/Repository/Projection/ReferentManagedUserRepository.php
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Referent/ManagedUsersFilterTest.php
  translations/messages.fr.yml
Labels: Ready for code review
