Repository parti-renaissance/espace-adherent, pull requests merged in 2019-02, with the labels that each got.

#3264 Add nickname to user info endpoints
  features/api/adherents.feature
  src/Entity/Adherent.php
  tests/Controller/Api/OAuthServerControllerTest.php
Labels: Ready for code review

#3266 [ADI] Handle user nickname
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/Comment.stories.js
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/index.jsx
  web/apps/atelier-des-idees/src/components/Header/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCard/IdeaCard.stories.js
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/components/Input/Input.stories.js
  web/apps/atelier-des-idees/src/components/Input/_style.scss
  web/apps/atelier-des-idees/src/components/Input/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/ErrorModal/ErrorModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/ErrorModal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/ErrorModal/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/FailSignal/FailSignal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/FailSignal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/FailSignal/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/FlagModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/SuccessSignal/SuccessSignal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/SuccessSignal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/SuccessSignal/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/FlagModal/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyNicknameModal/MyNicknameModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/MyNicknameModal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/MyNicknameModal/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/SuccessModal/SuccessModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/SuccessModal/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/SuccessModal/index.jsx
  web/apps/atelier-des-idees/src/components/Switch/Switch.stories.js
  web/apps/atelier-des-idees/src/components/Switch/_style.scss
  web/apps/atelier-des-idees/src/components/Switch/index.jsx
  web/apps/atelier-des-idees/src/constants/modalTypes.js
  web/apps/atelier-des-idees/src/containers/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/ModalRoot/_style.scss
  web/apps/atelier-des-idees/src/containers/ModalRoot/index.jsx
  web/apps/atelier-des-idees/src/containers/MyNicknameModal/index.jsx
  web/apps/atelier-des-idees/src/helpers/entities.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/redux/actions/loading.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/loading.js
  web/apps/atelier-des-idees/src/redux/thunk/auth.js
Labels: Ready for code review

#3270 Do not search thread & comment reports by name
  src/Admin/ReportAdmin.php
  src/Report/ReportType.php
  src/Repository/ReportRepository.php
Labels: Ready for code review

#3272 [ADI] fix issue with draft publish
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review

#3273 [ADI] Add idea link to approval comment mail
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/IdeasWorkshop/Handler/SendMailForApprovedThreadCommentHandler.php
  src/Mailer/Message/ApprovedIdeaCommentMessage.php
Labels: Ready for code review

#3275 [ADI] Update min position to 1
  app/migrations/Version20190204103132.php
  src/Entity/IdeasWorkshop/Question.php
Labels: Ready for code review

#3279 [ADI] Add 'Elected' idea author category
  features/api/adherents.feature
  features/api/ideas_workshop_ideas.feature
  src/Adherent/AdherentRoleEnum.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/Adherent.php
  src/Entity/IdeasWorkshop/AuthorCategoryEnum.php
  src/Normalizer/IdeaDenormalizer.php
  src/Security/Voter/ElectedAdherentVoter.php
  src/Security/Voter/IdeaQGVoter.php
  src/Security/Voter/LaREMAdherentVoter.php
  tests/Controller/Api/OAuthServerControllerTest.php
Labels: Ready for code review

#3281 [ADI] Various style improvements
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyContributions/MyContributions.stories.js
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyContributions/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyContributions/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/MyIdeas.stories.js
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
Labels: Ready for code review

#3283 [ADI] Nickname errors improvements
  web/apps/atelier-des-idees/src/components/Input/_style.scss
  web/apps/atelier-des-idees/src/components/Input/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyNicknameModal/index.jsx
  web/apps/atelier-des-idees/src/containers/MyNicknameModal/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/loading.js
  web/apps/atelier-des-idees/src/redux/reducers/loading.js
  web/apps/atelier-des-idees/src/redux/thunk/auth.js
Labels: Ready for code review

#3271 [ADI] Add comments cgu boolean
  app/config/services/services.xml
  app/migrations/Version20190201110931.php
  features/api/adherents.feature
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Entity/Adherent.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/EventSubscriber/CommentsCguSubscriber.php
  tests/Controller/Api/OAuthServerControllerTest.php
Labels: Work in progress

#3280 [ADI] CGU for first comment
  web/apps/atelier-des-idees/src/components/CommentsList/CommentsList.stories.js
  web/apps/atelier-des-idees/src/components/CommentsList/_style.scss
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/SecondForm/_style.scss
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
  web/apps/atelier-des-idees/src/redux/actions/auth.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/auth.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
  web/apps/atelier-des-idees/src/style/_variables.scss
Labels: Ready for code review

#3286 Test new config circle
  .circleci/config.yml
Labels: Ready for code review

#3298 Allow spaces for nickname + error wording
  features/api/adherents.feature
  src/Entity/Adherent.php
  translations/validators.fr.yml
Labels: Ready for code review

#3304 [Test] Store Token date into variable
  tests/OAuth/PersistentTokenFactoryTest.php
Labels: Ready for code review

#3252 [jecoute]dev download file stat question
  src/Controller/EnMarche/ReferentController.php
  src/Jecoute/StatisticsExporter.php
  src/Jecoute/StatisticsProvider.php
  templates/referent/surveys/stats.html.twig
  tests/Jecoute/StatisticsExporterTest.php
Labels: Ready for code review

#3306 [Security] Stop saving target path for API request
  app/config/routing.yml
  app/config/services/services.xml
  src/AppBundle.php
  src/DependencyInjection/Compiler/SecurityPass.php
  src/Security/Firewall/ExceptionListener.php
  src/Security/LoginFormAuthenticator.php
Labels: Bug, Ready for code review

#3309 edit download file stat question
  src/Controller/EnMarche/ReferentController.php
  src/Jecoute/StatisticsExporter.php
Labels: Ready for code review

#3285 [ADI] Stock last date used by NotifyIdeaAuthor job
  app/migrations/Version20190204155307.php
  src/Command/NotifyIdeaAuthorCommand.php
  src/DataFixtures/ORM/LoadIdeaData.php
Labels: Ready for code review

#3289 Redirect to the last visited page after login
  app/config/services/services.xml
  features/redirect.feature
  src/Security/EventListener/LastVisitedPageOnGetListener.php
Labels: Ready for code review

#3310 [ADI] Add fixture with deleted thread and fix count contributors
  features/api/ideas_workshop_ideas.feature
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3314 [ADI] Fix position
  app/migrations/Version20190205173350.php
Labels: Ready for code review

#3282 refacto adherent admin
  app/migrations/Version20190204134057.php
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  src/Form/Admin/ReferentManagedAreaType.php
  tests/Admin/AdherentAdminTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3315 [ADI] Update report admin
  src/Admin/ReportAdmin.php
  templates/admin/ideas_workshop/list_action_moderate.html.twig
  templates/admin/report/list_actions.html.twig
  templates/admin/report/list_enabled.html.twig
Labels: Ready for code review

#3325 [ADI] Remove canary for link in header
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#3323 Admin fix soft deleted view
  src/Admin/Extension/DoctrineEnabledFilterConfigurationAdminExtension.php
  src/Admin/Extension/DoctrineSoftdeleteableFilterConfigurationAdminExtension.php
  src/Admin/IdeasWorkshopThreadAdmin.php
  src/Admin/ReportAdmin.php
  src/Entity/Article.php
  src/Entity/Clarification.php
  src/Entity/EntitySoftDeletedInterface.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/NewsletterSubscription.php
  src/Entity/OAuth/Client.php
  src/Entity/OrderArticle.php
  src/Entity/Page.php
  src/Entity/Proposal.php
  src/Twig/InstanceOfExtension.php
  templates/admin/ideas_workshop/details_column.html.twig
  templates/admin/ideas_workshop/list_action_moderate.html.twig
  templates/admin/partial/_details.html.twig
  templates/admin/report/details_column.html.twig
Labels: Ready for code review

#3328 Revert "[ADI] Remove canary for link in header"
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#3330 [Logger] Do not log BadRequest exception
  app/config/services/system.xml
  src/Controller/Api/IdeasWorkshop/IdeaPublishController.php
  src/Entity/IdeasWorkshop/Idea.php
  tests/Controller/Api/IdeasWorkshop/IdeaPublishControllerTest.php
Labels: Ready for code review

#3317 [ADI] Update ideas' author category if adherent tags or mandates have been changed in admin
  src/Admin/AdherentAdmin.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3322 [ADI] Update idea admin
  features/admin/ideas_workshop_ideas.feature
  src/Admin/IdeasWorkshopIdeaAdmin.php
  templates/admin/ideas_workshop/idea/_status.html.twig
  templates/admin/ideas_workshop/idea/list_author_category.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3333 Fix old password migration
  src/Security/LegacyMigrationListener.php
Labels: Bug, Ready for code review

#3336 Revert "Revert "[ADI] Remove canary for link in header""
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#3337 adherent change email is send on new email
  src/Mailer/Message/AdherentChangeEmailMessage.php
  src/Membership/AdherentChangeEmailHandler.php
Labels: Ready for code review

#3341 [ADI] Add 'contributed_by_me' to the idea list endpoint
  features/api/ideas_workshop_ideas.feature
  src/Admin/IdeaDatagrid.php
  src/Normalizer/IdeaNormalizer.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3344 Admin Create Archives field and put useless field
  app/config/services/admin.xml
Labels: Ready for code review

#3353 [ADI] Fix idea comment number sorting
  features/api/ideas_workshop_ideas.feature
  src/Filter/CommentsCountFilter.php
Labels: Bug, Ready for code review

#3343 refacto design admin referent organigramme
  templates/admin/organizational_chart/admin_list.html.twig
  templates/admin/organizational_chart/chart_macros.html.twig
  templates/admin/referent/organization_chart.html.twig
Labels: Ready for code review

#3329 dev display limit amount while 'abonnement'
  app/config/services/services.xml
  front/components/AmountChooser.js
  front/components/DonationAmountChooser.js
  src/Donation/DonationRequest.php
  src/Validator/MaxMonthDonation.php
  src/Validator/MaxMonthDonationValidator.php
  tests/Validator/MaxMonthDonationValidatorTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3352 [Circle] More containers for behat & do not build example app
  .circleci/config.yml
  bin/build-react-apps.js
  features/popup_chart.feature
  features/registration.feature
  features/republican_silence.feature
  features/surveys.feature
Labels: Ready for code review

#3348 [ADI] Add 'hours_before_deadline' to the idea endpoints
  features/api/ideas_workshop_ideas.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#3358 Revert css deletion on elected checkbox
  front/style/pages/_register.scss
Labels: Bug, Ready for code review

#3349 [AdherentMessage] Add Message action buttons if it was synchronized
  front/app.js
  front/components/MessageStatusLoader.js
  front/pages/message_filters.js
  front/services/api/ReqwestApiClient.js
  front/style/app.scss
  front/style/pages/_adherent-messages.scss
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/Command/MailchimpCreateTagFromReferentTagCommand.php
  src/Command/MailchimpSyncAllAdherentsCommand.php
  src/Command/MailchimpUpdateReferentTagExternalIdFromMailchimpCommand.php
  src/Controller/EnMarche/MessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  templates/message/filter.html.twig
  templates/message/filter/referent.html.twig
  templates/message/preview.html.twig
Labels: Ready for code review

#3357 [ADI] Design improvements
  web/apps/atelier-des-idees/src/components/Dropdown/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCard/ContributingFooter/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaCard/ContributingFooter/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCard/IdeaCard.stories.js
  web/apps/atelier-des-idees/src/components/IdeaCard/VotingFooter/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaCard/VotingFooter/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCard/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/components/IdeaCardList/IdeaCardList.stories.js
  web/apps/atelier-des-idees/src/components/IdeaCardList/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/_style.scss
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/img/icn_card-display-condensed.svg
  web/apps/atelier-des-idees/src/img/icn_card-display-default.svg
  web/apps/atelier-des-idees/src/pages/Consult/_style.scss
  web/apps/atelier-des-idees/src/pages/Contribute/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageHeader/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageHeader/index.jsx
Labels: Ready for code review

#3355 [ADI] Add order by on threads for idea get
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Entity/IdeasWorkshop/Answer.php
Labels: Bug, Ready for code review

#3360 [ADI] Add idea.comments_count column
  app/config/config.yml
  app/config/services/services.xml
  app/migrations/Version20190211164100.php
  features/api/ideas_workshop_ideas.feature
  src/Controller/Admin/AdminThreadCommentController.php
  src/Controller/Admin/AdminThreadController.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/EntityListener/IdeaThreadCommentListener.php
  src/EntityListener/IdeaThreadListener.php
  src/EntityListener/VoteListener.php
  src/IdeasWorkshop/Events.php
  src/IdeasWorkshop/Listener/EnableThreadListener.php
Labels: Ready for code review

#3364 Set collection instance to Adherent tags property
  src/Entity/Adherent.php
Labels: Bug, Ready for code review

#3366 [ADI] Use comment_count column for sorting ideas
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
  src/Filter/CommentsCountFilter.php
  src/Normalizer/IdeaNormalizer.php
  src/Repository/IdeaRepository.php
  web/apps/atelier-des-idees/src/components/IdeaFilters/index.jsx
Labels: Ready for code review

#3367 [ADI] Refacto tests
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  features/bootstrap/JsonContext.php
Labels: Ready for code review

#3372 [ADI] Send contribution notification mail to idea author every 4 days after publication of an idea
  app/config/services/services.xml
  app/migrations/Version20190213141335.php
  src/Command/NotifyIdeaAuthorAboutContributionsCommand.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Mailer/Message/IdeaContributionsMessage.php
  tests/Command/NotifyIdeaAuthorAboutContributionsCommandTest.php
Labels: Ready for code review

#3378 Adi fix admin ux
  src/Entity/Committee.php
  src/Normalizer/IdeaNormalizer.php
Labels: Bug, Ready for code review

#3379 [AdherentMessage] Disable other message types
  src/Form/AdherentMessageTypeType.php
  templates/message/create.html.twig
Labels: Bug, Ready for code review

#3382 [ADI] Add redirection to report list and update report admin
  src/Admin/ReportAdmin.php
  src/Controller/Admin/AdminIdeaController.php
  src/Controller/Admin/AdminThreadCommentController.php
  src/Controller/Admin/AdminThreadController.php
  src/Controller/Admin/RedirectToTargetTrait.php
  templates/admin/ideas_workshop/list_action_moderate.html.twig
  templates/admin/report/list_actions.html.twig
Labels: Ready for code review

#3385 display every-time captcha on register form
  front/pages/registration.js
  templates/membership/register.html.twig
Labels: Ready for code review

#3383 fix datetime notificationMessage
  src/Mailer/Message/CitizenActionNotificationMessage.php
  src/Mailer/Message/EventNotificationMessage.php
  tests/Mailer/Message/AbstractEventMessageTest.php
  tests/Mailer/Message/CitizenActionNotificationMessageTest.php
  tests/Mailer/Message/EventNotificationMessageTest.php
Labels: Ready for code review

#3396 [AdherentMessage] Add RefTag filter to sync adherent command
  src/Command/MailchimpSyncAllAdherentsCommand.php
Labels: Ready for code review

#3397 [Makefile] Added formatted option for doctrine:migration:diff
  Makefile
Labels: Ready for code review

#3345 remove action comment
  src/Admin/CitizenProjectAdmin.php
  src/Form/CoordinatorAreaType.php
  templates/coordinator/_citizen_project_list.html.twig
  templates/coordinator/_committee_list.html.twig
  templates/coordinator/committees.html.twig
  tests/Controller/EnMarche/CoordinatorControllerTest.php
Labels: Ready for code review

#3398 dev display captcha on join view
  front/pages/join.js
  templates/membership/join.html.twig
Labels: Ready for code review

#3394 [ADI] Add validation on mandatory questions
  app/config/services/services.xml
  src/Admin/AdherentAdmin.php
  src/Admin/IdeaDatagrid.php
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Command/NotifyIdeaAuthorAboutContributionsCommand.php
  src/Command/NotifyIdeaAuthorCommand.php
  src/Controller/Admin/AdminIdeaController.php
  src/DataFixtures/ORM/LoadIdeaQuestionData.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Filter/IdeaStatusFilter.php
  src/Normalizer/IdeaNormalizer.php
  src/Repository/IdeasWorkshop/IdeaRepository.php
  src/Repository/IdeasWorkshop/QuestionRepository.php
  src/Validator/MandatoryQuestion.php
  src/Validator/MandatoryQuestionValidator.php
  tests/Controller/Admin/AdminIdeaControllerTest.php
  tests/TestHelperTrait.php
  translations/validators.fr.yml
Labels: Ready for code review

#3402 Fix undefined class in SyncAdherentCommand
  src/Command/MailchimpSyncAllAdherentsCommand.php
Labels: Bug, Ready for code review

#3400 [Fixtures] Updated republican silence tags
  features/republican_silence.feature
  src/DataFixtures/ORM/LoadRepublicanSilenceData.php
  tests/Controller/EnMarche/DeputyControllerTest.php
Labels: Ready for code review

#3406 add btn rss
  templates/components/_footer.html.twig
  templates/home/index.html.twig
Labels: Ready for code review

#3408 [SVG] encode # char in SVG URL data
  front/style/mixins/_icons.scss
Labels: Bug, Ready for code review

#3388 add nationality on adherent entity
  app/migrations/Version20190214153731.php
  features/mandate.feature
  features/oauth.feature
  features/registration.feature
  src/Address/Address.php
  src/Address/NullableAddress.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Donation/DonationRequest.php
  src/Entity/Adherent.php
  src/Entity/Invite.php
  src/Entity/JeMarcheReport.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Event/EventInvitation.php
  src/Form/AdherentRegistrationType.php
  src/Form/AdherentType.php
  src/Form/UserRegistrationType.php
  src/Membership/AdherentFactory.php
  src/Membership/MembershipRequest.php
  src/Newsletter/Invitation.php
  templates/adherent/profile.html.twig
  templates/membership/join.html.twig
  templates/membership/register.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Controller/EnMarche/RegistrationTrait.php
  translations/validators.fr.yml
Labels: Ready for code review

#3404 remove column comment
  app/config/services/services.xml
  app/migrations/Version20190219112556.php
  features/republican_silence.feature
  src/CitizenProject/CitizenProjectCommentCommand.php
  src/CitizenProject/CitizenProjectCommentCreationCommandHandler.php
  src/CitizenProject/CitizenProjectCommentEvent.php
  src/CitizenProject/CitizenProjectMessageNotifier.php
  src/Controller/EnMarche/CitizenProjectController.php
  src/DataFixtures/ORM/LoadCitizenProjectCommentData.php
  src/Entity/CitizenProjectComment.php
  src/Entity/Committee.php
  src/Entity/CoordinatorAreaInterface.php
  src/Entity/CoordinatorAreaTrait.php
  src/Form/CitizenProjectCommentCommandType.php
  src/Mailer/Message/CitizenProjectCommentMessage.php
  src/Membership/AdherentRegistry.php
  src/Repository/CitizenProjectCommentRepository.php
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  templates/citizen_project/show_base.html.twig
  templates/citizen_project/show_comments.html.twig
  tests/CitizenProject/CitizenProjectMessageNotifierTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/CitizenProjectControllerTest.php
  tests/Entity/CitizenProjectCommentTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#3403 [AdherentMessage] Migrate Deputy message to Mailchimp
  app/config/parameters.yml.dist
  app/config/services/services.xml
  app/migrations/Version20190218152507.php
  src/AdherentMessage/AdherentMessageDataObject.php
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/Command/AdherentMessageChangeCommand.php
  src/AdherentMessage/Command/AdherentMessageDeleteCommand.php
  src/AdherentMessage/Command/CreateDefaultMessageFilterCommand.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/Handler/AdherentMessageChangeCommandHandler.php
  src/AdherentMessage/Handler/AdherentMessageDeleteCommandHandler.php
  src/AdherentMessage/Handler/CreateDefaultMessageFilterHandler.php
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/AdherentMessage/Utils.php
  src/Controller/EnMarche/MessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Entity/AdherentMessage/DeputyAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AdherentZoneFilter.php
  src/Form/AdherentMessageReferentZoneFilterType.php
  src/Form/AdherentMessageType.php
  src/Form/AdherentMessageTypeType.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Repository/AdherentMessageRepository.php
  templates/components/_nav_desktop.html.twig
  templates/message/_base_deputy.html.twig
  templates/message/_layout.html.twig
  templates/message/create.html.twig
  templates/message/filter/deputy.html.twig
Labels: Ready for code review

#3411 Add formation role
  app/config/security.yml
  src/Admin/AdministratorAdmin.php
Labels: Ready for code review

#3410 [AdherentMessage] Add default value for url prefix parameter
  src/AdherentMessage/Utils.php
  src/Controller/EnMarche/MessageController.php
Labels: Bug, Ready for code review

#3412 Use adherent role in showMe action
  src/Controller/Api/UserController.php
Labels: Bug, Ready for code review

#3405 Remove duplicate key
  .php_cs.dist
Labels: Ready for code review

#3359 Dev/ch6941/updater la question du sexe sur le formulaire
  app/migrations/Version20190219123557.php
  features/registration.feature
  front/pages/join.js
  front/style/layout/_forms.scss
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  src/Form/AdherentType.php
  src/Membership/AdherentFactory.php
  src/Membership/MembershipRequest.php
  src/Validator/CustomGender.php
  src/Validator/CustomGenderValidator.php
  src/ValueObject/Genders.php
  templates/adherent/profile.html.twig
  templates/board_member/_search_form.html.twig
  templates/board_member/home.html.twig
  templates/membership/_profile_script.html.twig
  templates/membership/join.html.twig
  templates/message/filter/_referent_full_filter_form.html.twig
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Validator/CustomGenderValidatorTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#3392 Manage mandates in the admin and 'elected' idea author category when user changes mandates itself
  .gitignore
  app/config/services/services.xml
  front/style/pages/_join.scss
  front/style/pages/_register.scss
  package.json
  src/Admin/AdherentAdmin.php
  src/EventSubscriber/ChangeIdeaAuthorCategoryListener.php
  src/Form/AdherentType.php
  src/Repository/IdeasWorkshop/IdeaRepository.php
  templates/adherent/profile.html.twig
  templates/javascript.js.twig
  templates/membership/_mandates_script.html.twig
  templates/membership/join.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  translations/messages.fr.yml
  webpack.config.dev.js
  webpack.config.prod.js
  yarn.lock
Labels: Ready for code review

#3415 Add radio button to the proxy form
  app/migrations/Version20190222115015.php
  front/style/pages/_procuration.scss
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  templates/procuration/proposal.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#3417 Remove landscape constraint from biography photo
  src/Entity/Biography/AbstractBiography.php
Labels: Ready for code review

#3413 [Institutional events] Added invitations
  app/config/services/services.xml
  app/migrations/Version20190221144312.php
  src/Admin/InstitutionalEventAdmin.php
  src/Controller/EnMarche/ReferentController.php
  src/Entity/InstitutionalEvent.php
  src/Event/EventFactory.php
  src/Form/DataTransformer/StringToArrayTransformer.php
  src/Form/InstitutionalEventCommandType.php
  src/InstitutionalEvent/InstitutionalEventCommand.php
  src/InstitutionalEvent/InstitutionalEventCommandHandler.php
  src/InstitutionalEvent/InstitutionalEventEvent.php
  src/InstitutionalEvent/InstitutionalEventMessageNotifier.php
  src/Mailer/EmailTemplate.php
  src/Mailer/Message/InstitutionalEventInvitationMessage.php
  src/Mailer/Message/Message.php
  src/Mailjet/EmailTemplate.php
  src/Referent/ManagedInstitutionalEventsExporter.php
  templates/referent/institutional_events/create.html.twig
  templates/referent/institutional_events/list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3419 Add faq link under header in procuration area
  features/republican_silence.feature
  templates/procuration/_faq.html.twig
  templates/procuration/_layout.html.twig
  templates/procuration/choose_election.html.twig
  templates/procuration/landing.html.twig
  templates/procuration/proposal.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
Labels: Ready for code review

#3421 [Mailchimp] fix sync of changed email
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Bug, Ready for code review

#3422 Fixed BCC Emails options
  src/InstitutionalEvent/InstitutionalEventCommand.php
  src/Mailjet/EmailTemplate.php
  templates/referent/institutional_events/create.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3420 fix wording input gender
  src/Admin/AdherentAdmin.php
  src/ValueObject/Genders.php
  templates/adherent/profile.html.twig
  templates/membership/join.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3423 Update information link
  app/migrations/Version20190225135532.php
  src/DataFixtures/ORM/LoadElectionData.php
Labels: Ready for code review

#3428 Fix sensiolabs/security-checker
  composer.json
  composer.lock
  var/SymfonyRequirements.php
Labels: Ready for code review

#3430 Remove !important from visibility-hidden
  front/style/layout/_utilities.scss
Labels: Bug, Ready for code review

#3429 [ADI] Add sharing files in the idea's responses
  app/config/services/system.xml
  app/migrations/Version20190226172524.php
  src/DataFixtures/ORM/LoadIdeaAnswerData.php
  src/DataFixtures/ORM/LoadUserDocumentData.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/Listener/ContainingUserDocumentListener.php
  src/Entity/Report/IdeasWorkshop/IdeaReport.php
  src/Entity/Report/IdeasWorkshop/ThreadCommentReport.php
  src/Entity/Report/IdeasWorkshop/ThreadReport.php
  src/Entity/UserDocument.php
  src/Repository/UserDocumentRepository.php
  tests/Controller/Api/IdeasWorkshop/IdeaEndpointsTest.php
Labels: Ready for code review

#3433 Removed unused PayboxPaymentSubscriptionType class
  src/Form/PayboxPaymentSubscriptionType.php
Labels: Ready for code review

#3439 Change text on the events and committees list pages
  templates/search/search_committees.html.twig
  templates/search/search_events.html.twig
Labels: Ready for code review

#3441 Increase message length (referent, deputy, committee host)
  src/Form/AdherentMessageType.php
  src/Form/CommitteeFeedMessageType.php
  src/Form/DeputyMessageType.php
  src/Form/ReferentMessageType.php
Labels: Ready for code review

#3438 [ADMIN] Change report admin (status and actions)
  app/config/services/services.xml
  src/Admin/ReportAdmin.php
  src/Controller/Admin/AdminIdeaController.php
  src/IdeasWorkshop/Events.php
  src/Report/Listener/EnableSubjectForResolvingReportsListener.php
  src/Repository/ReportRepository.php
  templates/admin/partial/_details.html.twig
  templates/admin/report/_status.html.twig
  templates/admin/report/show_details.html.twig
  translations/reports.fr.yml
Labels: Work in progress

#3442 Change constraint for message length to AssertWysiwygLength (referent, deputy, committee host messages)
  src/AdherentMessage/AdherentMessageDataObject.php
  src/Committee/Feed/CommitteeMessage.php
  src/Deputy/DeputyMessage.php
  src/Referent/ReferentMessage.php
Labels: Ready for code review
