Repository parti-renaissance/espace-adherent, pull requests merged in 2019-01, with the labels that each got.

#3016 Fix test fails related to the new year
  features/donation.feature
  src/DataFixtures/ORM/LoadDonationData.php
  src/Entity/Donation.php
  tests/Repository/TransactionRepositoryTest.php
Labels: Ready for code review

#2987 fix selector MOOC/chapiter [ch5943]
  src/Admin/MoocChapterAdmin.php
  src/Admin/MoocElementAdmin.php
Labels: Bug, Ready for code review

#3017 [ADI] fix reducer init issue in production config
  web/apps/atelier-des-idees/src/redux/store/configStore.prod.js
Labels: Ready for code review

#3020 [ADI] #57 close modal on idea delete success
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review

#3018 [ADI] Add /ideas endpoint to get ideas answers
  app/migrations/Version20181228150617.php
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_votes.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Question.php
  src/Normalizer/IdeasWorkshopNormalizer.php
Labels: Ready for code review

#3021 Remove useless service declaration in admin
  app/config/services/admin.xml
Labels: Ready for code review

#3014 [ADI] #37 save idea
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/loading.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review

#3003 Improve PUT idea endpoints
  app/config/config_dev.yml
  app/config/config_test.yml
  app/config/services/services.xml
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  src/Controller/Api/IdeaPublishController.php
  src/Controller/Api/ThreadCommentController.php
  src/Controller/Api/ThreadController.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/IdeasWorkshop/IdeaPermissions.php
  src/Normalizer/AuthorDenormalizer.php
  src/Normalizer/IdeaDenormalizer.php
  src/Normalizer/ItemNormalizerDecorator.php
  src/Security/Voter/IdeaPublishVoter.php
Labels: Ready for code review

#3013 [ADI] #49 IdeaPage (edit/contribute/consult)
  src/React/App/IdeasWorkshopApp.php
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/components/TextEditor/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/CreateIdeaActions.stories.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/auth.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review

#3023 [ADI] #63 Dynamic tool using guidelines
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/currentIdea.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/currentIdea.js
  web/apps/atelier-des-idees/src/redux/selectors/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review

#3024 [ADI] Expose id on Answer, Category, Need and Theme
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Category.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#2993 [ADI] Add swagger support
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/routing.yml
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/IdeasWorkshop/AuthorCategoryEnum.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/IdeaStatusEnum.php
  src/Entity/IdeasWorkshop/Theme.php
  src/Swagger/PaginatorSwagger.php
  src/Swagger/SwaggerDecorator.php
Labels: Ready for code review

#3026 [ADI] #48 Idea publication
  web/apps/atelier-des-idees/src/components/Button/Button.stories.js
  web/apps/atelier-des-idees/src/components/Button/_style.scss
  web/apps/atelier-des-idees/src/components/Button/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/PublishIdeaForm/PublishIdeaForm.stories.js
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/PublishIdeaForm/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/SecondForm/SecondForm.stories.js
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/SecondForm/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/StateForm/SuccessForm/SuccessForm.stories.js
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/StateForm/SuccessForm/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/containers/LatestIdeas/index.js
  web/apps/atelier-des-idees/src/containers/ModalRoot/index.jsx
  web/apps/atelier-des-idees/src/containers/PublishIdeaFormModal/index.js
  web/apps/atelier-des-idees/src/hocs/withAuth.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/static.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/currentIdea.js
  web/apps/atelier-des-idees/src/redux/reducers/index.js
  web/apps/atelier-des-idees/src/redux/reducers/loading.js
  web/apps/atelier-des-idees/src/redux/reducers/static.js
  web/apps/atelier-des-idees/src/redux/selectors/loading.js
  web/apps/atelier-des-idees/src/redux/selectors/static.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/src/redux/thunk/static.js
  web/apps/atelier-des-idees/src/style/_button.scss
Labels: Work in progress

#3029 [ADI] #65 Remove auth mock
  web/apps/atelier-des-idees/src/redux/reducers/auth.js
  web/apps/atelier-des-idees/src/redux/thunk/auth.js
Labels: Ready for code review

#3032 [ADI] #68 Delete idea from my ideas drawer
  web/apps/atelier-des-idees/src/components/Header/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/MyIdeas.stories.js
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/_style.scss
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/index.jsx
  web/apps/atelier-des-idees/src/containers/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/ideas.js
  web/apps/atelier-des-idees/src/redux/actions/myIdeas.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/ideas.js
  web/apps/atelier-des-idees/src/redux/reducers/myIdeas.js
  web/apps/atelier-des-idees/src/redux/selectors/myContributions.js
  web/apps/atelier-des-idees/src/redux/selectors/myIdeas.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review

#3030 add condition bind district by adherent country
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
  src/Repository/DistrictRepository.php
  tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
Labels: Bug, Ready for code review

#3035 [ADI] #61 IdeaPage: edit answer
  web/apps/atelier-des-idees/src/components/IdeaReader/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review

#3039 [ADI] #74 Improve app initial loading
  web/apps/atelier-des-idees/src/components/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/containers/PublishIdeaFormModal/index.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/src/redux/thunk/static.js
Labels: Ready for code review

#3027 [ADI] Improve swagger
  src/Entity/IdeasWorkshop/EntityThreadCommentStatusTrait.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/ThreadCommentStatusEnum.php
  src/Swagger/SwaggerDecorator.php
Labels: Ready for code review

#2904 Sync adherent data with Mailchimp
  Dockerfile
  Makefile
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/services/messenger.yml
  app/config/services/platform.xml
  app/config/services/services.xml
  composer.json
  composer.lock
  docker/dev/Dockerfile
  docker/dev/my.cnf
  src/Admin/AdherentAdmin.php
  src/AppBundle.php
  src/CitizenProject/CitizenProjectAuthority.php
  src/CitizenProject/CitizenProjectMessageNotifier.php
  src/Collection/CommitteeMembershipCollection.php
  src/Committee/CommitteeManagementAuthority.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/BoardMemberController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/DonationController.php
  src/Controller/EnMarche/MembershipController.php
  src/Entity/Adherent.php
  src/Entity/CommitteeMembership.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Projection/ReferentManagedUser.php
  src/Entity/ReferentTag.php
  src/Mailchimp/Exception/AdherentNotFoundException.php
  src/Mailchimp/Synchronisation/Driver.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/AdherentMessageHandler.php
  src/Mailchimp/Synchronisation/Manager.php
  src/Mailchimp/Synchronisation/Message/AdherentChangeMessage.php
  src/Mailchimp/Synchronisation/Message/AdherentMessageInterface.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/Request/MemberRequestInterface.php
  src/Mailchimp/Synchronisation/Request/MemberTagsRequest.php
  src/Mailchimp/Synchronisation/Request/RequestInterface.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Membership/AdherentAccountActivationHandler.php
  src/Membership/AdherentChangeEmailHandler.php
  src/Membership/AdherentEvents.php
  src/Membership/MembershipRequestHandler.php
  src/Membership/UserCollectionEvent.php
  src/Membership/UserEvent.php
  src/Membership/UserEventInterface.php
  src/Membership/UserEvents.php
  src/Messenger/Message/AsyncMessageInterface.php
  src/Normalizer/UuidNormalizer.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Utils/ArrayUtils.php
  tests/CitizenProject/CitizenProjectMessageNotifierTest.php
  tests/Committee/CommitteeManagementAuthorityTest.php
  tests/Entity/CommitteeMembershipTest.php
Labels: Ready for code review

#3041 [ADI] #73 /ideas paging parameters
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
Labels: Ready for code review

#3042 [ADI] #56 remove connected-react-router
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/history.js
  web/apps/atelier-des-idees/src/index.js
  web/apps/atelier-des-idees/src/redux/reducers/index.js
  web/apps/atelier-des-idees/src/redux/store/configStore.dev.js
  web/apps/atelier-des-idees/src/redux/store/configStore.prod.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#3025 [ADMIN][ADI] Add idea template admin
  app/config/config.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/services.xml
  app/migrations/Version20190103103438.php
  features/api/ideas_workshop_guidelines.feature
  src/Admin/Extension/DoctrineFilterConfigurationAdminExtension.php
  src/Admin/IdeasWorkshopGuidelineAdmin.php
  src/Admin/IdeasWorkshopQuestionAdmin.php
  src/DataFixtures/ORM/LoadIdeaQuestionData.php
  src/Doctrine/EnabledExtension.php
  src/Doctrine/Filter/EnabledFilter.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Guideline.php
  src/Entity/IdeasWorkshop/Question.php
  src/Form/IdeasWorkshop/QuestionType.php
Labels: Ready for code review

#3038 [ADI] add unique constraint on consultation enabled
  app/migrations/Version20190104103759.php
  src/DataFixtures/ORM/LoadIdeaConsultationData.php
  src/Entity/IdeasWorkshop/Consultation.php
Labels: Ready for code review

#3043 [ADI] Add data to idea item endpoint
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#3047 [ADI] Fix thread filtering by idea uuid
  features/api/ideas_workshop_threads.feature
  src/Entity/IdeasWorkshop/Thread.php
Labels: Ready for code review

#3049 [ADI] Expose author uuid on /ideas/{uuid} endpoint
  features/api/ideas_workshop_ideas.feature
  src/Entity/EntityIdentityTrait.php
Labels: Ready for code review

#3048 [ADI] #75 Add comments
  web/apps/atelier-des-idees/src/App.js
  web/apps/atelier-des-idees/src/components/CommentsList/CommentsList.stories.js
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/actions/currentIdea.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/currentIdea.js
  web/apps/atelier-des-idees/src/redux/selectors/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
Labels: Ready for code review

#3050 [ADI] Remove report route from thread and comment
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/ThreadCommentController.php
  src/Controller/Api/ThreadController.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#3051 [ADI] #67 Publish from "My ideas" drawer
  web/apps/atelier-des-idees/src/components/Button/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeasModal.stories.js
  web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/index.jsx
  web/apps/atelier-des-idees/src/containers/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/MyIdeas/index.jsx
  web/apps/atelier-des-idees/src/containers/PublishIdeaFormModal/index.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
Labels: Ready for code review

#3054 Fix adherent message type on single choice
  src/Form/AdherentMessageTypeType.php
Labels: Bug, Ready for code review

#3052 [ADI] Add 'created_at' date to comment endpoints + change pagination
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#3055 [ADI] #86 Redirect to login page on authorized only actions
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/CommentsList/_style.scss
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaThread/_style.scss
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
  web/apps/atelier-des-idees/src/hocs/withAuth.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
Labels: Ready for code review

#3058 [ADI] Add first page of comments in /threads endpoint
  app/config/services/services.xml
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Normalizer/ThreadNormalizer.php
Labels: Ready for code review

#3065 Fixed Blackfire GPG key
  Dockerfile
  docker/dev/Dockerfile
Labels: Bug, Ready for code review

#3066 dev query find committee by privilege [ch6198]
  features/adherent_dashboard.feature
  front/style/layout/_nav.scss
  src/Controller/EnMarche/AdherentController.php
  src/Repository/CommitteeMembershipRepository.php
  templates/adherent/list_my_committees_al.html.twig
Labels: Bug, Ready for code review

#3069 [ADMIN][ADI] Add Idea admin
  app/config/security.yml
  app/config/services/admin.xml
  features/api/ideas_workshop_ideas.feature
  src/Admin/IdeaDatagrid.php
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Controller/Admin/AdminIdeaController.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Repository/IdeaRepository.php
  templates/admin/citizen_project/edit.html.twig
  templates/admin/citizen_project/show.html.twig
  templates/admin/committee/edit.html.twig
  templates/admin/committee/show.html.twig
  templates/admin/event/list_organizer.html.twig
  templates/admin/ideas_workshop/idea_contributors.html.twig
  templates/admin/ideas_workshop/list_deadline.html.twig
  templates/admin/ideas_workshop/list_show_contributors.html.twig
  templates/admin/ideas_workshop/list_show_page.html.twig
  templates/admin/list/list_author.html.twig
Labels: Ready for code review

#3068 [ADI] Expose approved on threads and comments
  app/migrations/Version20190108152424.php
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/ThreadCommentController.php
  src/Controller/Api/ThreadController.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/EntityThreadCommentStatusTrait.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/ThreadCommentStatusEnum.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3075 [ADI] Add vote id to endpoints
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_votes.feature
  src/Entity/IdeasWorkshop/Vote.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3077 [ADI] Fix idea theme creation
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#3073 [ADI] Add filters on Idea
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
  src/Filter/CommentsCountFilter.php
  src/Normalizer/IdeaNormalizer.php
Labels: Ready for code review

#3074 Handle svg
  src/Controller/AssetsController.php
Labels: Ready for code review

#3080 [ADI] Idea: no need for needs
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
  translations/validators.fr.yml
Labels: Ready for code review

#3062 [ADI] #53 Ideas filters
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/IdeaFilters/IdeaFilters.stories.js
  web/apps/atelier-des-idees/src/components/IdeaFilters/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaFilters/index.jsx
  web/apps/atelier-des-idees/src/components/Select/_style.scss
  web/apps/atelier-des-idees/src/components/Select/index.jsx
  web/apps/atelier-des-idees/src/constants/api.js
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/containers/LatestIdeas/index.js
  web/apps/atelier-des-idees/src/pages/Consult/_style.scss
  web/apps/atelier-des-idees/src/pages/Contribute/_style.scss
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/src/style/_variables.scss
Labels: Work in progress

#3086 [ADI] add order on number of votes
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#3089 [ADI] Manage ADI while unregistration + filter threads by answer id
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_themes.feature
  features/api/ideas_workshop_threads.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/DataFixtures/ORM/LoadIdeaThemeData.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/DataFixtures/ORM/LoadIdeaVoteData.php
  src/Entity/AuthorInterface.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
  src/Membership/AdherentRegistry.php
  src/Repository/AuthorTrait.php
  src/Repository/CommitteeFeedItemRepository.php
  src/Repository/IdeaRepository.php
  src/Repository/ThreadCommentRepository.php
  src/Repository/ThreadRepository.php
  src/Repository/VoteRepository.php
  tests/Controller/EnMarche/AdherentControllerTest.php
Labels: Ready for code review

#3093 Fix images exceptions
  src/Controller/AssetsController.php
Labels: Ready for code review

#3094 Clear EntityManager after each message
  app/config/services/services.xml
  src/AdherentMessage/Handler/AdherentMessageChangeCommandHandler.php
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/Admin/AdherentAdmin.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Command/AdherentChangeChangeCommand.php
  src/Mailchimp/Synchronisation/Command/AdherentChangeCommandInterface.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/AdherentChangeCommandHandler.php
Labels: Bug, Ready for code review

#3045 Laurentnegre/ch6009/rajouter la possibilité de changer de fuseau
  app/migrations/Version20190109100241.php
  features/sync_with_api.feature
  src/Address/GeoCoder.php
  src/Admin/EventAdmin.php
  src/Controller/EnMarche/CitizenActionManagerController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadCitizenActionData.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Doctrine/Hydrators/EventHydrator.php
  src/Entity/BaseEvent.php
  src/Entity/CitizenAction.php
  src/Entity/Event.php
  src/Event/BaseEventCommand.php
  src/Event/EventCommand.php
  src/Event/EventFactory.php
  src/Form/BaseEventCommandType.php
  src/Repository/EventRepository.php
  src/Twig/EventExtension.php
  src/Twig/EventRuntime.php
  templates/citizen_action_manager/_layout.html.twig
  templates/committee_manager/add_event.html.twig
  templates/events/edit.html.twig
  templates/events/show.html.twig
  templates/referent/event_create.html.twig
  templates/search/_events.html.twig
  tests/Address/GeoCoderTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Entity/EventTest.php
Labels: Ready for code review

#3098 [AdherentMessage] Sync Referent message filters
  app/config/parameters.yml.dist
  app/config/services/services.xml
  src/AdherentMessage/Filter/FilterDataObjectInterface.php
  src/AdherentMessage/Filter/ReferentFilterDataObject.php
  src/Controller/EnMarche/MessageController.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/Request/EditCampaignRequest.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Referent/ManagedUsersFilter.php
Labels: Ready for code review

#3088 [ADI] #53 Name, need and categories filters
  web/apps/atelier-des-idees/src/components/IdeaFilters/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaFilters/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/img/icn_input_search.svg
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Ready for code review

#3096 [ADI] - add illustrations homepage
  web/apps/atelier-des-idees/.gitignore
  web/apps/atelier-des-idees/src/components/MovementIdeas/_style.scss
  web/apps/atelier-des-idees/src/components/MovementIdeas/index.jsx
  web/apps/atelier-des-idees/src/components/Reports/_style.scss
  web/apps/atelier-des-idees/src/components/Reports/index.jsx
  web/apps/atelier-des-idees/src/img/hp-illustration-rapports.svg
  web/apps/atelier-des-idees/src/img/hp-main-illustration-bkg.svg
  web/apps/atelier-des-idees/src/img/hp-main-illustration.svg
Labels: Ready for code review

#3101 [ADI] css fixes on "proposer" page
  web/apps/atelier-des-idees/src/pages/Propose/PreProposal/_style.scss
  web/apps/atelier-des-idees/src/pages/Propose/PreProposal/index.jsx
  web/apps/atelier-des-idees/src/pages/Propose/ProposalCriteria/_style.scss
  web/apps/atelier-des-idees/src/pages/Propose/ProposalCriteria/index.jsx
  web/apps/atelier-des-idees/src/pages/Propose/ProposalSteps/_style.scss
  web/apps/atelier-des-idees/src/pages/Propose/index.jsx
  web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
Labels: Ready for code review

#3097 [ADI] add sticky header
  web/apps/atelier-des-idees/src/components/Header/_style.scss
  web/apps/atelier-des-idees/src/components/IdeaFilters/_style.scss
  web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
Labels: Ready for code review

#3091 [ADI] #81 Thread comments
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/index.jsx
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
  web/apps/atelier-des-idees/src/helpers/entities.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/redux/actions/threads.js
  web/apps/atelier-des-idees/src/redux/constants/actionTypes.js
  web/apps/atelier-des-idees/src/redux/reducers/threads.js
  web/apps/atelier-des-idees/src/redux/selectors/threads.js
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
Labels: Ready for code review

#3113 [ADI] css fixes
  web/apps/atelier-des-idees/src/components/IdeaCard/_style.scss
  web/apps/atelier-des-idees/src/containers/ModalRoot/_style.scss
Labels: Ready for code review

#3082 [ADI] Update ideas workshop route prefix
  features/api/ideas_workshop_categories.feature
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_consultation_reports.feature
  features/api/ideas_workshop_consultations.feature
  features/api/ideas_workshop_guidelines.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_needs.feature
  features/api/ideas_workshop_themes.feature
  features/api/ideas_workshop_threads.feature
  features/api/ideas_workshop_votes.feature
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Category.php
  src/Entity/IdeasWorkshop/Consultation.php
  src/Entity/IdeasWorkshop/ConsultationReport.php
  src/Entity/IdeasWorkshop/Guideline.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Question.php
  src/Entity/IdeasWorkshop/Theme.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
Labels: Ready for code review

#3114 [ADI] #99 rename /api into /api/ideas-workshop
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/pinned.js
  web/apps/atelier-des-idees/src/redux/thunk/reports.js
  web/apps/atelier-des-idees/src/redux/thunk/static.js
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
Labels: Ready for code review

#3111 [ADI] Set theme image required
  app/migrations/Version20190114153653.php
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_themes.feature
  src/Admin/IdeasWorkshopThemeAdmin.php
  src/DataFixtures/ORM/LoadIdeaThemeData.php
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#3116 [ADI] #6405 fix votes count update
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/redux/reducers/ideas.js
Labels: Ready for code review

#3120 [ADI] #101 fix thread comment delete
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
Labels: Ready for code review

#3119 [ADI] #98 Fix questions numerotation
  web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
Labels: Ready for code review

#3117 [ADI] #97 Idea page skeleton
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageSkeleton/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageSkeleton/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
Labels: Ready for code review

#3139 Upgrade api-platform/core 2.2.10
  composer.json
  composer.lock
Labels: Ready for code review

#3106 [ADI] Add thread admin
  app/config/security.yml
  app/config/services/admin.xml
  src/Admin/IdeasWorkshopThreadAdmin.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Thread.php
  templates/admin/ideas_workshop/thread/list_thread_comments_contributors.html.twig
  templates/admin/ideas_workshop/thread/list_thread_last_comment.html.twig
  templates/admin/ideas_workshop/thread/show_thread_comments.html.twig
Labels: Ready for code review

#3135 dev transformer datetime
  src/Form/BaseEventCommandType.php
  src/Form/DataTransformer/EventDateTimeZoneTransformer.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Form/DataTransformer/EventDateTimeZoneTransformerTest.php
Labels: Bug, Ready for code review

#3134 [ADI] fix typo with rebase
  features/api/ideas_workshop_ideas.feature
Labels: Ready for code review

#3133 [ADI] #107 Fix comments load more button
  web/apps/atelier-des-idees/src/components/CommentsList/_style.scss
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
Labels: Ready for code review

#3129 [ADI] #88 Improve Idea Page errors
  web/apps/atelier-des-idees/src/components/TextEditor/TextEditor.stories.js
  web/apps/atelier-des-idees/src/components/TextEditor/_style.scss
  web/apps/atelier-des-idees/src/components/TextEditor/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
Labels: Ready for code review

#3118 [ADI] Update getIdeaContributors method
  features/api/ideas_workshop_ideas.feature
  src/Admin/IdeaDatagrid.php
  src/Controller/Admin/AdminIdeaController.php
  src/Normalizer/IdeaNormalizer.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3144 [ADI] Allow empty answers
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Answer.php
  translations/validators.fr.yml
Labels: Ready for code review

#3151 [ADI] Add actions on Idea admin
  app/config/services/admin.xml
  features/admin/ideas_workshop_ideas.feature
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Controller/Admin/AdminIdeaController.php
  templates/admin/ideas_workshop/idea/idea_contributors.html.twig
  templates/admin/ideas_workshop/idea/list_action_contribute.html.twig
  templates/admin/ideas_workshop/idea/list_action_disabled.html.twig
  templates/admin/ideas_workshop/idea/list_action_enabled.html.twig
  templates/admin/ideas_workshop/idea/list_action_finalize.html.twig
  templates/admin/ideas_workshop/idea/list_deadline.html.twig
  templates/admin/ideas_workshop/idea/list_show_contributors.html.twig
  templates/admin/ideas_workshop/idea/list_show_page.html.twig
Labels: Ready for code review

#3160 [ADI] Change publish delay
  features/api/ideas_workshop_ideas.feature
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#3140 [ADI] #111 Send comment for an empty answer
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
Labels: Ready for code review

#3165 'add choices during time "don"'
  front/components/AmountChooser.js
  front/style/layout/_forms.scss
  front/style/pages/_donation.scss
  src/Controller/EnMarche/DonationController.php
Labels: Ready for code review

#3164 [AdherentMessage] Keep only zone filter for referent message
  app/config/services/services.xml
  app/migrations/Version20190118131528.php
  src/AdherentMessage/Filter/FilterDataObjectInterface.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/Filter/ReferentFilterDataObject.php
  src/Command/MailchimpCreateTagFromReferentTagCommand.php
  src/Command/MailchimpSyncAllAdherentsCommand.php
  src/Controller/EnMarche/MessageController.php
  src/Entity/ReferentTag.php
  src/Exception/InvalidAdherentMessageType.php
  src/Form/AdherentMessageReferentFilterType.php
  src/Form/ReferentTagChoiceType.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/Request/EditCampaignRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Referent/ManagedUsersFilter.php
  templates/message/filter/referent.html.twig
  templates/message/list.html.twig
Labels: Ready for code review

#3167 [ADI] Expose description on idea
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
Labels: Ready for code review

#3143 add field nationality on donation entity
  app/migrations/Version20190116162854.php
  src/Donation/DonationRequest.php
  src/Entity/Donation.php
  src/Form/DonationRequestType.php
  templates/donation/informations.html.twig
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#3168 [ADI] #117 Update idea infos
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/FirstForm/index.jsx
  web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/PublishIdeaForm/index.jsx
  web/apps/atelier-des-idees/src/components/Select/_style.scss
  web/apps/atelier-des-idees/src/components/Select/index.jsx
  web/apps/atelier-des-idees/src/containers/PublishIdeaFormModal/index.js
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaActions/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/redux/thunk/ideas.js
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
Labels: Work in progress

#3170 [ADI] Expose approved on GET idea endpoint
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/BaseComment.php
Labels: Ready for code review

#3171 [ADI] Add extension to hide ended consultation
  app/config/services/services.xml
  src/DataFixtures/ORM/LoadIdeaConsultationData.php
  src/Doctrine/ConsultationExtension.php
  src/Entity/IdeasWorkshop/Consultation.php
Labels: Ready for code review

#3183 Redirect user after connexion to add note page
  src/Controller/ReactController.php
  web/apps/atelier-des-idees/src/components/Header/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
Labels: Ready for code review

#3185 [ADI] Expose answers on POST /idea
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Question.php
Labels: Ready for code review

#3181 [ADI] update getContributors query
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/DataFixtures/ORM/LoadIdeaAnswerData.php
  src/DataFixtures/ORM/LoadIdeaThreadCommentData.php
  src/DataFixtures/ORM/LoadIdeaThreadData.php
  src/Doctrine/MyIdeaContributionExtension.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3180 [AdherentMessage] Show full referent filter for user with single ref tag
  app/config/services/services.xml
  app/migrations/Version20190122015855.php
  src/AdherentMessage/AdherentMessageSynchronizedObjectInterface.php
  src/AdherentMessage/Filter/AdherentMessageFilterInterface.php
  src/AdherentMessage/Filter/FilterDataObjectInterface.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/Filter/ReferentFilterDataObject.php
  src/AdherentMessage/Handler/AdherentMessageChangeCommandHandler.php
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/Command/MailchimpUpdateReferentTagExternalIdFromMailchimpCommand.php
  src/Controller/EnMarche/MessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Entity/AdherentMessage/Filter/AbstractAdherentMessageFilter.php
  src/Entity/AdherentMessage/Filter/ReferentUserFilter.php
  src/Entity/AdherentMessage/Filter/ReferentZoneFilter.php
  src/Entity/ReferentManagedArea.php
  src/Form/AdherentMessageReferentFilterType.php
  src/Form/AdherentMessageReferentZoneFilterType.php
  src/Form/ReferentTagChoiceType.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/Request/EditCampaignRequest.php
  templates/form_theme.html.twig
  templates/message/filter/_referent_full_filter_form.html.twig
  templates/message/filter/_referent_zone_filter_form.html.twig
  templates/message/filter/referent.html.twig
Labels: Ready for code review

#3189 [ADI][ADMIN] Wording: replace 'idée' by 'proposition'
  app/config/services/admin.xml
  src/Admin/IdeasWorkshopThreadAdmin.php
Labels: Ready for code review

#3191 [ADI] Idea committee validation
  app/config/services/services.xml
  features/api/ideas_workshop_ideas.feature
  src/Entity/IdeasWorkshop/Idea.php
  src/Repository/CommitteeMembershipRepository.php
  src/Validator/CommitteeMember.php
  src/Validator/CommitteeMemberValidator.php
Labels: Ready for code review

#3198 [ADI] tostring methods
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#3190 modifie integration field nationality
  features/donation.feature
  src/DataFixtures/ORM/LoadDonationData.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Entity/Donation.php
  src/Form/DonationRequestType.php
  templates/donation/informations.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review

#3205 [ADI] Do not redirect already authenticated users
  web/apps/atelier-des-idees/src/components/Header/index.jsx
  web/apps/atelier-des-idees/src/pages/Propose/ProposalCriteria/index.jsx
Labels: Ready for code review

#3200 [ADI] Enable in production
  src/React/App/IdeasWorkshopApp.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#3208 [ADI] Fix error on theme creation
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#3150 [ADI] #114 Update url with filter query params
  web/apps/atelier-des-idees/package-lock.json
  web/apps/atelier-des-idees/package.json
  web/apps/atelier-des-idees/src/components/IdeaFilters/IdeaFilters.stories.js
  web/apps/atelier-des-idees/src/components/IdeaFilters/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaCardList/index.jsx
  web/apps/atelier-des-idees/src/pages/Consult/index.jsx
  web/apps/atelier-des-idees/src/pages/Contribute/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPage/index.js
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/thunk/navigation.js
  web/apps/atelier-des-idees/yarn.lock
Labels: Ready for code review

#3209 [ADI] Add LaREM tag for ideas-workshop
  app/migrations/Version20190118142342.php
  features/admin/adherent_tags.feature
  src/DataFixtures/ORM/LoadAdherentTagData.php
  src/Entity/AdherentTagEnum.php
  src/Security/Voter/IdeaQGVoter.php
Labels: Ready for code review

#3211 [ADI] Add thread in count on total comments
  features/api/ideas_workshop_ideas.feature
  src/Normalizer/IdeaNormalizer.php
  src/Repository/IdeaRepository.php
Labels: Ready for code review

#3212 Use new DB dump
  Makefile
  dump/dump-2017.sql
  dump/dump-2018.sql
Labels: Ready for code review

#3221 [ADI][ADMIN] Wording
  features/admin/ideas_workshop_ideas.feature
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Entity/IdeasWorkshop/Idea.php
  templates/admin/ideas_workshop/idea/list_status.html.twig
  translations/reports.fr.yml
Labels: Ready for code review

#3178 hide participants if not logged
  features/search/events.feature
  templates/citizen_action/show.html.twig
  templates/events/_header.html.twig
  templates/search/_events.html.twig
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
Labels: Ready for code review

#3213 add region into address adhesion
  app/migrations/Version20190123111436.php
  front/app.js
  front/pages/donation_informations.js
  front/pages/join.js
  front/services/address/AddressForm.js
  front/services/address/AddressFormFactory.js
  front/services/address/AddressObject.js
  front/services/address/AutocompletedAddressForm.js
  front/services/address/GooglePlaceAutocomplete.js
  src/Address/Address.php
  src/Address/AddressInterface.php
  src/Address/NullableAddress.php
  src/Address/PostAddressFactory.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCitizenActionData.php
  src/DataFixtures/ORM/LoadCitizenProjectData.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Entity/NullablePostAddress.php
  src/Entity/PostAddress.php
  src/Form/AddressType.php
  src/Form/AdherentRegistrationType.php
  src/Form/BecomeAdherentType.php
  templates/javascript.js.twig
  templates/membership/join.html.twig
  tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
  tests/Entity/PostAddressTest.php
  tests/Membership/EventListener/UserSubscriberTest.php
Labels: Ready for code review

#3217 set field nationality to null
  app/migrations/Version20190124141525.php
  src/Entity/Donation.php
Labels: Ready for code review

#3222 [Jecoute] Added migration to generate SurveyQuestion uuids
  app/migrations/Version20190125100000.php
Labels: Ready for code review

#3225 [Jecoute] Updated form and stats
  src/Form/Jecoute/ChoiceFormType.php
  src/Form/Jecoute/SurveyQuestionFormType.php
  src/Repository/Jecoute/SurveyRepository.php
  templates/referent/_form_theme.html.twig
  templates/referent/surveys/create.html.twig
  templates/referent/surveys/stats.html.twig
Labels: Ready for code review

#3223 [ADI] fix migration
  app/migrations/Version20190118142342.php
Labels: Ready for code review

#3214 [ADI] Remove emojis from text fields
  app/config/services/services.xml
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/Entity/IdeasWorkshop/Idea.php
  src/EventListener/RemoveEmojisListener.php
Labels: Ready for code review

#3232 [ADI][ADMIN] Make image theme required only while creation
  src/Admin/IdeasWorkshopThemeAdmin.php
Labels: Ready for code review

#3229 bug la page de don a l adhesion ne s affiche
  front/style/pages/_donation.scss
  templates/membership/donation.html.twig
Labels: Ready for code review

#3233 [ADI] Disable pagination on themes, needs and categories endpoints
  features/api/ideas_workshop_categories.feature
  features/api/ideas_workshop_needs.feature
  features/api/ideas_workshop_themes.feature
  src/Entity/IdeasWorkshop/Category.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Theme.php
Labels: Ready for code review

#3231 [ADI] Change sender name for Idea mail
  features/api/ideas_workshop_ideas.feature
  src/Mailer/Message/IdeaPublishMessage.php
Labels: Ready for code review

#3219 [ADI] Update admin reports and idea
  features/api/report.feature
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Admin/ReportAdmin.php
  src/Controller/Api/ReportController.php
  src/DataFixtures/ORM/LoadReportData.php
  src/Entity/Report/Report.php
  src/Entity/Report/ReportReasonEnum.php
  src/Entity/Report/ReportStatusEnum.php
  src/Form/ReportCommandType.php
  src/Report/ReportCommand.php
  templates/admin/ideas_workshop/idea/list_deadline.html.twig
  templates/admin/ideas_workshop/idea/list_show_page.html.twig
  templates/admin/ideas_workshop/list_action_moderate.html.twig
  tests/Controller/EnMarche/ReportControllerTest.php
  tests/Entity/ReportTest.php
  translations/reports.fr.yml
Labels: Ready for code review

#3239 [ADI] Add image url metadata
  src/React/App/CitizenProjectApp.php
  src/React/App/IdeasWorkshopApp.php
  src/React/PageMetaData.php
  src/React/PageMetaDataInterface.php
  templates/react.html.twig
Labels: Ready for code review

#3242 [jecoute]refacto query findDataBySurveyQuestion
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/DataAnswer.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Jecoute/StatisticsProvider.php
  src/Repository/Jecoute/DataAnswerRepository.php
  src/Repository/Jecoute/QuestionRepository.php
Labels: Ready for code review

#3237 Fix/display event nofrench
  src/Entity/BaseEvent.php
  templates/events/_header.html.twig
  templates/events/show.html.twig
  templates/search/_events.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#3246 [ADI] Split approve endpoint in 2 differents endpoints
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/IdeasWorkshop/ApproveThreadCommentController.php
  src/Controller/Api/IdeasWorkshop/ApproveThreadController.php
  src/Controller/Api/IdeasWorkshop/DisapproveThreadCommentController.php
  src/Controller/Api/IdeasWorkshop/DisapproveThreadController.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#3243 Add adherent nickname
  app/migrations/Version20190128175553.php
  features/api/adherents.feature
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  features/api/ideas_workshop_votes.feature
  src/Controller/Api/AdherentController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Membership/AdherentFactory.php
  src/Normalizer/AuthorNormalizer.php
  translations/validators.fr.yml
Labels: Ready for code review

#3248 Fix tests on ADI
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_threads.feature
Labels: Ready for code review

#3247 [ADI] Switch name to title and update css
  src/Admin/IdeasWorkshopIdeaAdmin.php
Labels: Ready for code review

#3230 [ADI] Send mail notification when a note is finished
  app/config/services/services.xml
  src/Command/NotifyIdeaAuthorCommand.php
  src/DataFixtures/ORM/LoadIdeaData.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Mailer/Message/IdeaFinalizeMessage.php
  tests/Command/NotifyIdeaAuthorCommandTest.php
Labels: Ready for code review

#3245 [ADI] IdeaPage design improvement
  web/apps/atelier-des-idees/src/App.scss
  web/apps/atelier-des-idees/src/components/Collapse/_style.scss
  web/apps/atelier-des-idees/src/components/Collapse/index.jsx
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/Comment.stories.js
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/_style.scss
  web/apps/atelier-des-idees/src/components/CommentsList/Comment/index.jsx
  web/apps/atelier-des-idees/src/components/CommentsList/CommentsList.stories.js
  web/apps/atelier-des-idees/src/components/CommentsList/_style.scss
  web/apps/atelier-des-idees/src/components/CommentsList/index.jsx
  web/apps/atelier-des-idees/src/components/TextArea/index.jsx
  web/apps/atelier-des-idees/src/containers/IdeaThread/_style.scss
  web/apps/atelier-des-idees/src/containers/IdeaThread/index.js
  web/apps/atelier-des-idees/src/img/icn_48px_tool_reveal_white.svg
  web/apps/atelier-des-idees/src/img/icn_toggle_content_big.svg
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/CreateIdeaTool/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaContent/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaContent/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/QuestionBlock/index.jsx
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/VotingFooterIdeaPage/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/_style.scss
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/index.jsx
  web/apps/atelier-des-idees/src/redux/thunk/currentIdea.js
  web/apps/atelier-des-idees/src/style/_variables.scss
Labels: Ready for code review

#3251 [ADI] update threads and comments approval endpoint call
  web/apps/atelier-des-idees/src/redux/thunk/threads.js
Labels: Ready for code review

#3253 [ADI] fix error when displaying answer in draft mode
  web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaContent/index.jsx
Labels: Ready for code review

#3255 [TEST] fix donation test click on button
  features/donation.feature
Labels: Ready for code review

#3256 [Docker] Use gosu changing user and group ids
  Makefile
  docker/dev/Dockerfile
  docker/dev/entrypoint.sh
Labels: Ready for code review

#3262 change filter to ModelAutocomplete
  src/Admin/JecouteSurveyAdmin.php
Labels: Ready for code review

#3254 [Jecoute] Added surveys duplication
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadJecouteDataSurveyData.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Referent/SurveyExporter.php
  templates/referent/surveys/list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3263 Use or not use adherent nickname
  app/migrations/Version20190131133924.php
  features/api/adherents.feature
  features/api/ideas_workshop_comments.feature
  features/api/ideas_workshop_ideas.feature
  features/api/ideas_workshop_threads.feature
  src/Controller/Api/AdherentController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Membership/AdherentFactory.php
  src/Normalizer/AuthorNormalizer.php
Labels: Ready for code review
