Repository parti-renaissance/espace-adherent, pull requests merged in 2019-08, with the labels that each got.

#3910 Use CSV lib with storage service in unregisterAdherent command
  app/config/services/services.xml
  src/Command/UnregisterAdherentsCommand.php
Labels: Ready for code review

#3911 Remove adherent message on unregistration
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/Unregistration.php
  src/Membership/AdherentRegistry.php
  src/Repository/AdherentMessageRepository.php
Labels: Ready for code review

#3909 [ADH Space] Refacto J'écoute section's styles
  features/surveys.feature
  front/style/layout/_forms-em.scss
  front/style/manager-space/_tables.scss
  front/style/manager-space/roles/_referent.scss
  src/Jecoute/SurveyExporter.php
  templates/application_request/space/my_team.html.twig
  templates/committee_manager/list_members.html.twig
  templates/event_manager/events_list.html.twig
  templates/jecoute/_form.html.twig
  templates/jecoute/_form_theme.html.twig
  templates/jecoute/create.html.twig
  templates/jecoute/local_surveys_list.html.twig
  templates/jecoute/national_surveys_list.html.twig
  templates/jecoute/show.html.twig
  templates/jecoute/stats.html.twig
  templates/message/list.html.twig
  templates/municipal_chief/home.html.twig
  templates/referent/institutional_events/list.html.twig
Labels: Ready for code review

#3912 [ReferentSpace] open volunteers list for referent from Paris
  src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
  src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
  src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
  templates/application_request/space/list.html.twig
  templates/referent/_layout.html.twig
Labels: Ready for code review

#3854 [MunicipalSpace] Add chart dialog
  src/DataFixtures/ORM/LoadAdherentData.php
  templates/chart_dialog.html.twig
  templates/municipal_chief/_layout.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3913 Add tool's chart link on municipales overview
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#3914 [ReferentMessage] hide runningMate checkbox
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/Form/AdherentMessage/ReferentFilterType.php
  templates/message/filter/referent.html.twig
Labels: Ready for code review

#3915 [API] detail municipal chief role on API
  features/api/adherents.feature
  src/Entity/Adherent.php
  tests/Controller/Api/OAuthServerControllerTest.php
Labels: Ready for code review

#3916 [MunicipalEvent] Add url property to API response
  app/config/services/services.xml
  src/Normalizer/MunicipalEventNormalizer.php
  src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
  templates/application_request/space/list.html.twig
Labels: Ready for code review

#3918 Move Send Mail test button to filter page
  templates/message/filter.html.twig
  templates/message/preview.html.twig
  tests/Controller/EnMarche/AdherentMessage/ReferentMessageControllerTest.php
Labels: Ready for code review

#3919 Dimitri/ch9034/etq ref et porteur de projet et chef muni
  features/referent_space.feature
  front/components/DataGrid.js
  front/style/layout/_nav.scss
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/application_request/space/_application_request_row.js.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/event_manager/_event_row.js.twig
  templates/event_manager/events_list.html.twig
  templates/municipal_chief/_application_request_datagrid.html.twig
  templates/referent/_application_request_datagrid.html.twig
Labels: Ready for code review

#3917 [MunicipalSpace] merge last and fist name columns and add menu column
  features/referent_space.feature
  front/style/layout/_nav.scss
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/application_request/space/_application_request_row.js.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/event_manager/_event_row.js.twig
  templates/event_manager/events_list.html.twig
  templates/municipal_chief/_application_request_datagrid.html.twig
  templates/referent/_application_request_datagrid.html.twig
Labels: Ready for code review

#3921 [RepublicanSilence] block municipal space pages
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  src/RepublicanSilence/ReferentTagExtractorFactory.php
  src/RepublicanSilence/TagExtractor/MunicipalChefReferentTagExtractor.php
  src/RepublicanSilence/TagExtractor/ReferentTagExtractorInterface.php
Labels: Ready for code review

#3920 [Donation] Added donators
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/services.xml
  features/donation.feature
  migrations/Version20190823172134.php
  src/Admin/DonatorAdmin.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/DataFixtures/ORM/LoadDonatorIdentifierData.php
  src/Donation/DonationRequestHandler.php
  src/Donation/DonatorFactory.php
  src/Donation/DonatorManager.php
  src/Donation/DonatorSubscriber.php
  src/Entity/Donation.php
  src/Entity/Donator.php
  src/Entity/DonatorIdentifier.php
  src/EntityListener/DonationListener.php
  src/Repository/AdherentRepository.php
  src/Repository/DonatorIdentifierRepository.php
  src/Repository/DonatorRepository.php
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#3927 [Donation] Donator Admin : Added donations list
  src/Admin/DonatorAdmin.php
  templates/admin/donator/show_donations.html.twig
Labels: Ready for code review

#3902 [Jecoute] Removed surveys tags command
  app/config/services/services.xml
  src/Command/UpdateLocalSurveysTagsCommand.php
Labels: Don't merge, Ready for code review

#3928 [Donation] Removed unused parameter
  src/Donation/DonationRequestHandler.php
Labels: Ready for code review

#3924 [Admin] Add gender filter to ApplicationRequest pages
  src/Admin/ApplicationRequest/AbstractApplicationRequestAdmin.php
Labels: Ready for code review

#3929 [Formation] Add position column to Axes, Paths and Modules
  migrations/Version20190827001734.php
  src/Admin/Formation/AxeAdmin.php
  src/Admin/Formation/ModuleAdmin.php
  src/Admin/Formation/PathAdmin.php
  src/Entity/Formation/Axe.php
  src/Entity/Formation/Module.php
  src/Entity/Formation/Path.php
  src/Entity/PositionTrait.php
  src/Entity/SocialShare.php
  src/Entity/SocialShareCategory.php
  src/Form/PositionType.php
  src/Repository/Formation/PathRepository.php
Labels: Ready for code review

#3923 [ApplicationRequest] Fix Paris referent tag matching
  src/Referent/ReferentTagManager.php
Labels: Bug, Ready for code review

#3930 [Jecoute] Admin : Added surveys tags
  src/Admin/JecouteLocalSurveyAdmin.php
Labels: Ready for code review

#3925 Fix responsive on video media
  front/style/content/_inside-common.scss
Labels: Ready for code review

#3931 [Mailchimp] Fix sync of campaign message
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
Labels: Bug, Ready for code review

#3932 [Donation] Donator admin : Fixed format date
  templates/admin/donator/show_donations.html.twig
Labels: Bug, Ready for code review

#3934 Rename Municipal Chief role label
  src/Admin/AdherentAdmin.php
  src/Entity/MunicipalChiefManagedArea.php
  src/Twig/AdherentRuntime.php
  templates/admin/adherent/list_status.html.twig
  templates/event_manager/_event_row.js.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3926 Change gender denomination
  tests/Controller/EnMarche/AssessorControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3922 [MunicipalSpace] add candidate filters
  features/municipal_chief_space.feature
  front/style/manager-space/_tables.scss
  src/Admin/ApplicationRequest/AbstractApplicationRequestAdmin.php
  src/ApplicationRequest/ApplicationRequestRepository.php
  src/ApplicationRequest/Filter/ListFilter.php
  src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
  src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
  src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
  src/Form/ApplicationRequest/ApplicationRequestListFilterType.php
  src/Form/ApplicationRequest/ApplicationRequestTagsType.php
  src/Form/ApplicationRequest/TagType.php
  src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
  templates/application_request/space/list.html.twig
  templates/form_theme.html.twig
  templates/referent/users_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3935 [MunicipalSpace] Remove Adherents tab
  features/municipal_chief_space.feature
  src/Controller/EnMarche/MunicipalChiefController.php
  src/Repository/AdherentRepository.php
  templates/municipal_chief/_layout.html.twig
  templates/municipal_chief/adherent/list.html.twig
Labels: Ready for code review

#3938 [AdherentMessage] Remove computeChangeSet call
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  translations/messages.fr.yml
Labels: Bug, Ready for code review

#3937 [Donation] Added donators synchronization command
  app/config/services/services.xml
  migrations/Version20190829161721.php
  src/Command/DonatorSyncronizeCommand.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/Entity/Donator.php
Labels: Ready for code review

#3939 [Donation] Removed adherent matching for donators command
  src/Command/DonatorSyncronizeCommand.php
Labels: Ready for code review

#3940 Fix Event cancelation
  front/components/DataGrid.js
  src/Event/EventCanceledHandler.php
  src/Repository/MunicipalEventRepository.php
  templates/event_manager/_event_row.js.twig
Labels: Bug, Ready for code review

#3941 [Donation] Donators sync command : clear donations only
  app/config/services/services.xml
  src/Command/DonatorSynchronizeCommand.php
Labels: Ready for code review

#3943 [Mailchimp] display service warning
  front/style/manager-space/_base-layout.scss
  front/style/mixins/_colors.scss
  templates/message/_layout.html.twig
  templates/message/filter.html.twig
  templates/message/list.html.twig
Labels: Ready for code review

#3942 [MunicipalSpace] Change isAdherent field type to select
  src/Form/ApplicationRequest/ApplicationRequestListFilterType.php
  src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
  templates/application_request/space/list.html.twig
Labels: Ready for code review

#3944 [Donation] Donators sync command : fixed accented cache keys
  src/Command/DonatorSynchronizeCommand.php
Labels: Ready for code review

#3946 Fix update Sync message status
  src/AdherentMessage/AdherentMessageManager.php
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  templates/message/_layout.html.twig
  templates/message/list.html.twig
Labels: Bug, Ready for code review
