Repository parti-renaissance/espace-adherent, pull requests merged in 2019-09, with the labels that each got.

#3948 Open donator view for donation role
  app/config/security.yml
Labels: Ready for code review

#3947 Add new subscription type for Municipal e-mail
  migrations/Version20190829171055.php
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  src/Subscription/SubscriptionTypeEnum.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#3949 [MunicipalSpace] Add JEcoute tab
  features/municipal_chief_space.feature
  features/surveys.feature
  migrations/Version20190903161429.php
  src/Admin/AdherentAdmin.php
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  src/Controller/EnMarche/Jecoute/JecouteManagerController.php
  src/Controller/EnMarche/Jecoute/JecouteReferentController.php
  src/Controller/EnMarche/Jecoute/MunicipalChiefJecouteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/ManagedArea.php
  src/Entity/MunicipalChiefManagedArea.php
  src/Form/Admin/MunicipalChiefManagedAreaType.php
  src/Form/Jecoute/SurveyFormType.php
  src/Jecoute/JecouteSpaceEnum.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  templates/jecoute/_base_municipal_chief_space.html.twig
  templates/municipal_chief/_layout.html.twig
  templates/referent/organizational_chart_macros.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#3952 Adding jecoute preview on chef mun overview
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#3950 [MunicipalMessage] Send city name as content section
  src/Mailchimp/Campaign/CampaignContentRequestBuilder.php
  src/Mailchimp/Campaign/ContentSection/CitizenProjectMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/CommitteeMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/ContentSectionBuilderInterface.php
  src/Mailchimp/Campaign/ContentSection/DeputyMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/MunicipalChiefMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/ReferentMessageSectionBuilder.php
  src/Mailchimp/Manager.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#3955 [Mailchimp] Fix empty label value
  src/Mailchimp/Campaign/ContentSection/MunicipalChiefMessageSectionBuilder.php
Labels: Bug, Ready for code review

#3951 [MunicipalSpace] Add MySite tab if municipal site is enabled
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/services/services.xml
  app/config/services/twig.xml
  src/MunicipalSite/ApiDriver.php
  src/Twig/MunicipalSiteExtension.php
  src/Twig/MunicipalSiteRuntime.php
  templates/municipal_chief/_layout.html.twig
Labels: Ready for code review

#3954 [ChezVous] Introduce MeasureType entity
  app/config/config.yml
  app/config/config_test.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/system.xml
  migrations/Version20190906165357.php
  src/Admin/ChezVous/MeasureTypeAdmin.php
  src/Algolia/AlgoliaIndexedEntityManager.php
  src/ChezVous/Measure/AbstractMeasure.php
  src/ChezVous/Measure/BaisseNombreChomeurs.php
  src/ChezVous/Measure/ChequeEnergie.php
  src/ChezVous/Measure/ConversionSurfaceAgricoleBio.php
  src/ChezVous/Measure/CouvertureFibre.php
  src/ChezVous/Measure/CreationEntreprise.php
  src/ChezVous/Measure/DedoublementClasses.php
  src/ChezVous/Measure/MissionBern.php
  src/ChezVous/Measure/PrimeConversionAutomobile.php
  src/ChezVous/Measure/SuppressionTaxeHabitation.php
  src/ChezVous/MeasureChoiceLoader.php
  src/Command/ChezVous/ImportMarkersCommand.php
  src/Command/ChezVous/ImportMeasureTypesCommand.php
  src/Command/ChezVous/ImportMeasuresCommand.php
  src/Consumer/ChezVous/AlgoliaConsumer.php
  src/DataFixtures/ORM/LoadChezVousData.php
  src/DataFixtures/ORM/LoadChezVousMeasureTypeData.php
  src/Entity/ChezVous/Measure.php
  src/Entity/ChezVous/MeasureType.php
  src/Form/Admin/ChezVous/MeasureType.php
  src/Producer/ChezVous/AlgoliaProducer.php
  src/Producer/ChezVous/AlgoliaProducerInterface.php
  src/Repository/ChezVous/CityRepository.php
  src/Repository/ChezVous/MeasureRepository.php
  src/Repository/ChezVous/MeasureTypeRepository.php
  src/Validator/ChezVous/MeasurePayloadValidator.php
  tests/Controller/Admin/AdminChezVousCityControllerTest.php
  tests/Test/Producer/ChezVous/AlgoliaNullProducer.php
Labels: Work in progress

#3959 Add intro for Jecoute section (space)
  templates/jecoute/local_surveys_list.html.twig
  templates/jecoute/national_surveys_list.html.twig
Labels: Ready for code review

#3963 Add new replyTo button
  src/Mailchimp/Campaign/ContentSection/CitizenProjectMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/CommitteeMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/MunicipalChiefMessageSectionBuilder.php
  src/Mailchimp/Campaign/ContentSection/ReferentMessageSectionBuilder.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#3961 [MunicipalChief] Allow contact newsletter
  app/config/parameters.yml.dist
  app/config/services/services.xml
  migrations/Version20190910174932.php
  src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
  src/Form/AdherentMessage/MunicipalChiefFilterType.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToCandidateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToNewsletterConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  templates/message/filter/municipal_chief.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#3966 [Mailchimp] Sync adherent on Subscribe webhook call
  src/Controller/EnMarche/UserController.php
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  src/Mailchimp/Webhook/Handler/AbstractAdherentHandler.php
  src/Mailchimp/Webhook/Handler/AdherentSubscribeHandler.php
  src/Mailchimp/Webhook/Handler/AdherentUnsubscribeHandler.php
Labels: Ready for code review

#3967 [MunicipalSpace] Adds on overview, candidates colors...
  front/style/manager-space/_tables.scss
  templates/application_request/space/list.html.twig
  templates/municipal_chief/home.html.twig
  templates/referent/organizational_chart.html.twig
Labels: Ready for code review

#3969 [MailchimpWebhook] Update interest & notif on subscribe call
  src/Mailchimp/Webhook/Handler/AdherentProfileUpdateHandler.php
  src/Mailchimp/Webhook/Handler/AdherentSubscribeHandler.php
  src/Mailchimp/Webhook/WebhookHandler.php
Labels: Ready for code review

#3971 Fix radio buttons on donation journey
  front/components/DonationAmountChooser.js
  front/style/pages/_donation.scss
  templates/donation/index.html.twig
  templates/donation/layout.html.twig
Labels: Ready for code review

#3972 [Mailchimp] Sync newsletter unsubscribtions
  src/Command/MailchimpSyncAllNewsletterCommand.php
  src/Mailchimp/Synchronisation/MemberRequest/NewsletterMemberRequestBuilder.php
  src/Newsletter/Handler/MailchimpSyncNewsletterSubscriptionEntityCommandHandler.php
  src/Newsletter/NewsletterValueObject.php
  src/Repository/NewsletterSubscriptionRepository.php
Labels: Ready for code review

#3974 Fix label sizes
  front/components/DonationAmountChooser.js
  front/style/pages/_donation.scss
Labels: Ready for code review

#3975 Pad Insee code on the left with 0
  src/Intl/FranceCitiesBundle.php
Labels: Bug, Ready for code review

#3973 Allow referent to create adherent segment
  app/config/services/services.xml
  front/app.js
  front/components/Modal.js
  front/components/UserSegmentWidget.js
  front/pages/manage_user_segment.js
  front/services/api/ReqwestApiClient.js
  front/style/layout/_modal.scss
  front/style/manager-space/_filters.scss
  front/style/manager-space/_tables.scss
  migrations/Version20190926171344.php
  src/AdherentMessage/Command/SynchronizeAdherentSegmentCommand.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/Handler/SynchronizeAdherentSegmentCommandHandler.php
  src/Admin/CommitteeMergeHistoryAdmin.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/DataFixtures/ORM/LoadAdherentSegmentData.php
  src/Entity/AdherentMessage/CitizenProjectAdherentMessage.php
  src/Entity/AdherentMessage/CommitteeAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AdherentSegmentAwareFilterInterface.php
  src/Entity/AdherentMessage/Filter/AdherentSegmentAwareFilterTrait.php
  src/Entity/AdherentMessage/Filter/CitizenProjectFilter.php
  src/Entity/AdherentMessage/Filter/CommitteeFilter.php
  src/Entity/AdherentMessage/Filter/ReferentUserFilter.php
  src/Entity/AdherentSegment.php
  src/EntityListener/AdherentSegmentListener.php
  src/Form/AdherentMessage/AdherentSegmentFilterType.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Form/AdherentSegmentType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentSegmentConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToAdherentConditionBuilder.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Synchronisation/Handler/UpdateStaticSegmentHandler.php
  src/Membership/AdherentRegistry.php
  src/Normalizer/AdherentSegmentDenormalizer.php
  src/Repository/AdherentRepository.php
  src/Repository/AdherentSegmentRepository.php
  src/Repository/EventRepository.php
  templates/citizen_project/list_actors.html.twig
  templates/committee_manager/list_members.html.twig
  templates/message/filter/citizen_project.html.twig
  templates/message/filter/committee.html.twig
  templates/message/filter/referent.html.twig
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/AdherentMessage/CommitteeMessageControllerTest.php
Labels: Ready for code review

#3977 Add `Je me forme` boutton to navbar
  templates/components/_nav_desktop.html.twig
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#3976 [Event] Change wording of acceptTerms case
  src/Form/EventRegistrationType.php
  templates/events/attend.html.twig
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#3978 Add new role for formation space access
  src/Controller/EnMarche/FormationController.php
  src/Entity/Adherent.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Bug, Ready for code review

#3979 Change adherent subscription status when at least one checkbox is che…
  src/Controller/EnMarche/UserController.php
Labels: Ready for code review
