Repository parti-renaissance/espace-adherent, pull requests merged in 2019-10, with the labels that each got.

#3980 Create newsletter from event registration if checked
  app/config/services/services.xml
  migrations/Version20190930215529.php
  src/Controller/EnMarche/CitizenActionController.php
  src/Controller/EnMarche/EventController.php
  src/Entity/NewsletterSubscription.php
  src/Event/EventListener/EventRegistrationNewsletterSubscriber.php
  src/Event/EventRegistrationFactory.php
  src/Mailchimp/Synchronisation/MemberRequest/NewsletterMemberRequestBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Newsletter/NewsletterTypeEnum.php
  src/Newsletter/NewsletterValueObject.php
  templates/events/attend.html.twig
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
Labels: Ready for code review

#3981 Change wording on Event registration page
  templates/events/attend.html.twig
Labels: Ready for code review

#3982 Hotfixes on ChefMun and Ref spaces
  front/components/UserSegmentWidget.js
  templates/message/filter/referent.html.twig
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#3984 [JECOUTE] Allow empty answers on text fields
  features/api/surveys.feature
  src/Validator/DataSurveyAnswerTypeChoice.php
  src/Validator/DataSurveyAnswerTypeChoiceValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#3983 Allow to assign Paris, Marseille and Lyon for municipal chief
  app/config/config.yml
  src/Admin/AdherentAdmin.php
  src/Entity/ApplicationRequest/ApplicationRequest.php
  src/Entity/MunicipalChiefManagedArea.php
  src/Form/AdherentMessage/MunicipalChiefFilterType.php
  src/Form/EventListener/RevokeManagedAreaSubscriber.php
  src/Intl/FranceCitiesBundle.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToAdherentConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToCandidateConditionBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
  src/Security/Voter/MunicipalChiefVoter.php
  templates/message/filter/municipal_chief.html.twig
  templates/municipal_chief/_application_request_datagrid.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#3985 Add SegmentType property to AdherentSegment
  app/config/services/services.xml
  front/app.js
  front/components/UserSegmentWidget.js
  front/pages/manage_user_segment.js
  migrations/Version20191003224241.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentSegment/AdherentSegmentTypeEnum.php
  src/Entity/AdherentSegment.php
  src/Form/AdherentMessage/AdherentSegmentFilterType.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Form/AdherentSegmentType.php
  src/Referent/ManagedUsersFilter.php
  templates/citizen_project/list_actors.html.twig
  templates/committee_manager/list_members.html.twig
  templates/referent/users_list.html.twig
Labels: Ready for code review

#3986 [ApplicationRequest] Update adherent relation on email change
  src/ApplicationRequest/ApplicationRequestRepository.php
  src/ApplicationRequest/Listener/UpdateAdherentRelationSubscriber.php
  src/Membership/AdherentChangeEmailHandler.php
  src/Membership/UserEmailEvent.php
  src/Membership/UserEvents.php
Labels: Ready for code review

#3988 [Ref Space] Various hotfixes
  front/components/UserSegmentWidget.js
  templates/events/attend.html.twig
  templates/message/filter/citizen_project.html.twig
  templates/message/filter/committee.html.twig
  templates/message/filter/referent.html.twig
  templates/message/preview.html.twig
  templates/referent/users_list.html.twig
  tests/Controller/EnMarche/AdherentMessage/CommitteeMessageControllerTest.php
Labels: Ready for code review

#3987 Split chartAcceptation column on many type of chart
  migrations/Version20191004164517.php
  src/AdherentCharter/AdherentCharterFactory.php
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/Collection/AdherentCharterCollection.php
  src/Controller/EnMarche/UserController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/AdherentCharter/AbstractAdherentCharter.php
  src/Entity/AdherentCharter/AdherentCharterInterface.php
  src/Entity/AdherentCharter/DeputyCharter.php
  src/Entity/AdherentCharter/MunicipalChiefCharter.php
  src/Entity/AdherentCharter/ReferentCharter.php
  templates/deputy/_layout.html.twig
  templates/javascript.js.twig
  templates/municipal_chief/_layout.html.twig
  templates/referent/_layout.html.twig
Labels: Bug, Ready for code review

#3989 [Event] fix newsletter creation
  app/config/services/services.xml
  src/Event/EventListener/EventRegistrationNewsletterSubscriber.php
  src/Event/EventRegistrationCommand.php
  src/Repository/AdherentRepository.php
  src/Validator/EventRegistration.php
  src/Validator/EventRegistrationValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#3990 [Event] validate Adherent registration
  src/Controller/EnMarche/CitizenActionController.php
  src/Controller/EnMarche/EventController.php
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/CitizenActionControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
Labels: Bug, Ready for code review

#3991 [Mailchimp] Subscribe adherent when notification is changed
  app/config/config_prod.yml
  app/config/parameters.yml.dist
  app/config/services/http_client.yaml
  app/config/services/mailchimp.yaml
  composer.json
  composer.lock
  src/Controller/EnMarche/UserController.php
  src/Mailchimp/SignUp/SignUpHandler.php
Labels: Ready for code review

#3994 [UserSegment] handle dynamically updated table
  front/components/UserSegmentWidget.js
  front/pages/manage_user_segment.js
Labels: Bug, Ready for code review

#3993 Dimitri/ch9738/lancer la synchro si suppression de candidats
  src/ApplicationRequest/Listener/ApplicationRequestChangeSubscriber.php
  src/Repository/EventRegistrationRepository.php
  src/Security/Voter/AttendEventVoter.php
  src/Twig/EventRuntime.php
  src/Validator/EventRegistrationValidator.php
  tests/Security/Voter/AttendEventVoterTest.php
Labels: Ready for code review

#3996 [ApplicationRequest] fix remove candidate command handler
  src/Mailchimp/Synchronisation/Handler/RemoveApplicationRequestCandidateCommandHandler.php
Labels: Bug, Ready for code review

#3995 Remove "Mes tracts" from MunSpace
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#3997 Revert "[Logger] mute http client error"
  app/config/config_prod.yml
  app/config/services/system.xml
  composer.json
  composer.lock
  src/Logging/ActivationStrategy.php
Labels: Ready for code review

#3999 Update wording on notification's page
  features/api/subscription.feature
  features/registration.feature
  migrations/Version20191011155432.php
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  templates/adherent/_profile_menu.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/user/set_email_notifications.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4000 [Mailchimp] Add command for subscribe contact with signup form
  app/config/services/services.xml
  src/Command/MailchimpSignUpEmailsCommand.php
Labels: Ready for code review

#4001 Remove adherent segment creation part
  app/config/services/services.xml
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/Command/MailchimpDeleteStaticSegmentCommand.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  templates/citizen_project/list_actors.html.twig
  templates/committee_manager/list_members.html.twig
  templates/message/filter/citizen_project.html.twig
  templates/message/filter/committee.html.twig
  templates/message/filter/referent.html.twig
  templates/referent/users_list.html.twig
Labels: Ready for code review

#4002 [JEcoute] limit choice content to 80 chars
  src/Entity/Jecoute/Choice.php
  templates/jecoute/_form_theme.html.twig
  templates/jecoute/create.html.twig
Labels: Ready for code review

#4003 [AdherentMessage] add custom filters for committee members message
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/AbstractMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/CommitteeMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentMailchimpCampaignHandler.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/Filter/AbstractUserFilter.php
  src/Entity/AdherentMessage/Filter/CommitteeFilter.php
  src/Entity/AdherentMessage/Filter/ReferentUserFilter.php
  src/Form/AdherentMessage/CommitteeUserFilterType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentRegistrationDateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactAgeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactCityConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToAdherentConditionBuilder.php
  templates/form_theme.html.twig
  templates/message/filter/committee.html.twig
Labels: Ready for code review

#4005 [ChefMun] Display "maisondesimpressions" bloc on space
  front/style/manager-space/_base-layout.scss
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#4004 [Committee] Add filters to adherent list page
  front/style/manager-space/_tables.scss
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Event/Filter/ListFilterObject.php
  src/Form/AdherentMessage/CommitteeFilterType.php
  src/Form/CommitteeMemberFilterType.php
  src/Repository/CommitteeMembershipRepository.php
  templates/committee_manager/_member_rows.html.twig
  templates/committee_manager/list_members.html.twig
  templates/components/_modern_pagination.html.twig
  templates/form_theme.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#4006 [Committee] Add status filter to adherent list page
  app/config/config.yml
  src/AdherentMessage/MailchimpCampaign/Handler/CommitteeMailchimpCampaignHandler.php
  src/Event/Filter/ListFilterObject.php
  src/Form/AdherentMessage/CommitteeFilterType.php
  src/Form/CommitteeMemberFilterType.php
  src/Repository/CommitteeMembershipRepository.php
  templates/citizen_project/list_actors.html.twig
  templates/committee_manager/_member_rows.html.twig
  templates/committee_manager/list_members.html.twig
  templates/form_theme.html.twig
  templates/message/filter/committee.html.twig
  templates/referent/users_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4009 [MunicipalMessage] Add postalCode filter for Paris/Lyon/Marseille cities
  app/config/services/services.xml
  migrations/Version20191017001314.php
  src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
  src/Form/AdherentMessage/MunicipalChiefFilterType.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Intl/FranceCitiesBundle.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToAdherentConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToCandidateConditionBuilder.php
  src/Referent/ReferentTagManager.php
  templates/message/filter/municipal_chief.html.twig
  tests/Referent/ReferentTagManagerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4010 [CommitteMessage] Add default filtre on message creation
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
Labels: Ready for code review

#4011 Minor fix
  app/config/services/services.xml
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/IdeasWorkshop/Answer.php
  src/Entity/IdeasWorkshop/BaseComment.php
  src/Entity/IdeasWorkshop/Consultation.php
  src/Entity/IdeasWorkshop/ConsultationReport.php
  src/Entity/IdeasWorkshop/Guideline.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/IdeasWorkshop/Need.php
  src/Entity/IdeasWorkshop/Question.php
  src/Entity/IdeasWorkshop/Theme.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
  src/Entity/IdeasWorkshop/Vote.php
  src/Normalizer/IdeaAnswerNormalizer.php
  src/Normalizer/IdeaAuthorNicknameNormalizer.php
  src/Normalizer/IdeaThemeNormalizer.php
  src/Normalizer/IdeaThreadNormalizer.php
  translations/validators.fr.yml
Labels: Bug, Ready for code review

#4012 Update charter URLs
  translations/messages.fr.yml
Labels: Ready for code review

#4014 [J'écoute] Reorg questio creation
  front/style/layout/_buttons.scss
  front/style/layout/_layout.scss
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/roles/_referent.scss
  front/style/mixins/_colors.scss
  templates/jecoute/_form.html.twig
  templates/jecoute/_form_theme.html.twig
Labels: Ready for code review

#3998 [Donation] Integration of the reworked journey
  features/donation.feature
  features/registration.feature
  front/app.js
  front/components/AmountChooser.js
  front/components/DonationAmountChooser.js
  front/components/DonationWidget.js
  front/pages/donation.js
  front/services/donation/TaxReturnProvider.js
  front/style/layout/_buttons.scss
  front/style/mixins/_colors.scss
  front/style/mixins/_fonts.scss
  front/style/mixins/_text.scss
  front/style/pages/_donation.scss
  front/utils/css.js
  front/utils/dom.js
  src/Controller/EnMarche/DonationController.php
  templates/donation/_quick_form.html.twig
  templates/donation/index.html.twig
  templates/donation/informations.html.twig
  templates/donation/layout.html.twig
  templates/donation/paybox.html.twig
  templates/donation/result.html.twig
  templates/form_theme.html.twig
  templates/membership/donation.html.twig
  web/fonts/gillsans-semibold.woff
  web/fonts/gillsans-semibold.woff2
  web/images/donation-sharer.jpg
  web/images/icons/donation-journey-chevron.svg
Labels: Ready for code review

#4015 [Don] Fix background image url
  front/style/pages/_donation.scss
  src/Command/MailchimpSignUpEmailsCommand.php
  src/Controller/EnMarche/DonationController.php
Labels: Ready for code review

#4016 [Donation] Update wording and colors of donation module on static pages
  front/style/layout/_buttons.scss
  front/style/mixins/_text.scss
  front/style/pages/_donation.scss
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/desintox/view.html.twig
  templates/donation/_quick_form.html.twig
  templates/donation/index.html.twig
  templates/donation/layout.html.twig
  templates/donation/result.html.twig
  templates/explainer/article.html.twig
  templates/home/index.html.twig
  templates/membership/donation.html.twig
  templates/page/emmanuel-macron/layout.html.twig
  templates/page/le-mouvement/layout.html.twig
  templates/program/index.html.twig
  templates/program/proposal.html.twig
  web/images/donation-sharer.jpg
Labels: Ready for code review

#4017 [Donation] Last hotfixes - Encore
  front/style/pages/_donation.scss
  src/Controller/EnMarche/DonationController.php
  templates/donation/index.html.twig
  templates/donation/informations.html.twig
  templates/donation/result.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#4018 [Don] fix amount chooser on adhesion
  front/services/address/AutocompletedAddressForm.js
  src/Controller/EnMarche/MembershipController.php
  templates/membership/donation.html.twig
Labels: Ready for code review

#4019 [Don] fix CSS amount achooser adhesion
  front/style/pages/_donation.scss
  templates/membership/donation.html.twig
Labels: Ready for code review

#4020 [Jecoute] Add wording and urls
  front/style/layout/_buttons.scss
  front/style/manager-space/_base-layout.scss
  templates/jecoute/_manager_space_layout.html.twig
  templates/jecoute/local_surveys_list.html.twig
  templates/municipal_chief/home.html.twig
Labels: Ready for code review

#4021 [Donation] Fix accent on firefox and transac failed page
  front/style/pages/_donation.scss
  templates/donation/index.html.twig
  templates/donation/result.html.twig
Labels: Ready for code review

#4022 Fix some JS errors
  .gitignore
  Makefile
  front/kernel.js
  front/pages/grande_marche_europe.js
  front/pages/manage_participants.js
  package.json
Labels: Bug, Ready for code review

#4028 Remove unused CP notif checkbox
  src/Controller/EnMarche/UserController.php
  src/Entity/Adherent.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Subscription/SubscriptionTypeEnum.php
  templates/user/set_email_notifications.html.twig
  tests/CitizenProject/CitizenProjectManagerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#4023 Dimitri/ch10086/quick fixes sur l espace j écoute ref respo
  app/config/services/services.xml
  features/referent_space.feature
  features/surveys.feature
  migrations/Version20191023005244.php
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  src/Controller/EnMarche/Jecoute/JecouteManagerController.php
  src/Controller/EnMarche/Jecoute/JecouteReferentController.php
  src/Controller/EnMarche/Jecoute/MunicipalChiefJecouteController.php
  src/DataFixtures/ORM/LoadJecouteSurveyData.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Form/Admin/JecouteAdminSurveyQuestionFormType.php
  src/Form/DataTransformer/ReferentAreaTransformer.php
  src/Form/Jecoute/SurveyFormType.php
  src/Form/Jecoute/SurveyQuestionFormType.php
  src/Jecoute/StatisticsExporter.php
  src/Jecoute/StatisticsProvider.php
  src/Jecoute/SurveyExporter.php
  src/Repository/Jecoute/DataAnswerRepository.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  src/Repository/Jecoute/NationalSurveyRepository.php
  src/Repository/Jecoute/QuestionRepository.php
  src/Repository/Jecoute/SuggestedQuestionRepository.php
  templates/base.html.twig
  templates/jecoute/_form_theme.html.twig
  templates/jecoute/create.html.twig
  templates/jecoute/local_surveys_list.html.twig
  templates/jecoute/national_surveys_list.html.twig
  templates/jecoute/stats.html.twig
  templates/jecoute/suggested_questions_dialog.html.twig
  templates/jecoute/surveys_list.html.twig
  tests/Jecoute/StatisticsExporterTest.php
Labels: Ready for code review

#4030 [Jecoute] Change form wording
  templates/jecoute/_form.html.twig
  templates/jecoute/create.html.twig
Labels: Ready for code review

#4032 Dimitri/ch9843/4 petits fixes
  app/config/config.yml
  app/config/services/system.xml
  features/bootstrap/RabbitMqContext.php
  front/pages/join.js
  front/validator/formValidator.js
  migrations/Version20191011155432.php
  migrations/Version20191024111152.php
  src/CitizenProject/CitizenProjectManager.php
  src/CitizenProject/CitizenProjectMessageNotifier.php
  src/Consumer/ProjectCitizenCreationNotificationConsumer.php
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Entity/Adherent.php
  src/Form/AdherentType.php
  src/Membership/CitizenProjectNotificationDistance.php
  src/Repository/AdherentRepository.php
  templates/form_theme.html.twig
  templates/membership/join.html.twig
  tests/CitizenProject/CitizenProjectManagerTest.php
  tests/Consumer/ProjectCitizenCreationNotificationConsumerTest.php
  tests/Entity/AdherentTest.php
Labels: Ready for code review

#4033 [Message] change replyTo field for all message
  src/Mailchimp/Campaign/ContentSection/DeputyMessageSectionBuilder.php
  src/Mailchimp/Campaign/Listener/SetCampaignReplyToSubscriber.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#4034 [Jecoute] fix Choice join by checking question type
  src/Repository/Jecoute/QuestionRepository.php
Labels: Bug, Ready for code review

#4035 Add "salariés" to organization page
  features/sitemap.feature
  src/DataFixtures/ORM/LoadPageData.php
  templates/page/le-mouvement/notre-organisation.html.twig
Labels: Ready for code review

#4036 [MunicipalEvent] filter event category by event postalCode
  src/Controller/Api/MunicipalEventController.php
  src/Repository/MunicipalEventRepository.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
Labels: Ready for code review

#4037 [MunicipalEvent] enable search by categorie name
  app/config/services/services.xml
  src/Doctrine/MunicipalEventExtension.php
  src/Entity/MunicipalEvent.php
Labels: Ready for code review

#4038 Wording, links update, sharer update
  features/api/ideas_workshop_consultation_reports.feature
  src/DataFixtures/ORM/LoadIdeaConsultationReportData.php
  templates/components/_footer.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/membership/join.html.twig
  web/apps/atelier-des-idees/public/index.html
  web/apps/example/public/index.html
  web/images/membership-sharer.png
Labels: Ready for code review

#4029 Crm dons
  app/config/config.yml
  app/config/security.yml
  app/config/services/admin.xml
  app/config/services/services.xml
  migrations/Version20190919134908.php
  migrations/Version20191008121508.php
  migrations/Version20191008141228.php
  migrations/Version20191008162525.php
  migrations/Version20191024150239.php
  migrations/Version20191024151423.php
  migrations/Version20191029115419.php
  src/Admin/DonationAdmin.php
  src/Admin/DonationTagAdmin.php
  src/Admin/DonatorAdmin.php
  src/Admin/DonatorTagAdmin.php
  src/Command/ImportDonationsCommand.php
  src/Controller/Admin/AdminDonationController.php
  src/Controller/Admin/AdminDonatorController.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/DataFixtures/ORM/LoadDonationTagData.php
  src/DataFixtures/ORM/LoadDonatorTagData.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Donation/DonatorManager.php
  src/Donation/DonatorMergeCommand.php
  src/Donation/DonatorMergeCommandHandler.php
  src/Entity/ApplicationRequest/test.txt
  src/Entity/Donation.php
  src/Entity/DonationTag.php
  src/Entity/Donator.php
  src/Entity/DonatorTag.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Transaction.php
  src/EntityListener/DonationListener.php
  src/Form/Admin/DonatorIdentifierType.php
  src/Form/Admin/DonatorMergeType.php
  src/Form/DataTransformer/DonatorToIdentifierTransformer.php
  src/Repository/DonationRepository.php
  templates/admin/donation/list_tags.html.twig
  templates/admin/donator/list_is_adherent.html.twig
  templates/admin/donator/list_last_donation.html.twig
  templates/admin/donator/list_tags.html.twig
  templates/admin/donator/merge/_donator_summary.html.twig
  templates/admin/donator/merge/confirm.html.twig
  templates/admin/donator/merge/merge_button.html.twig
  templates/admin/donator/merge/request.html.twig
  templates/admin/list/list_color.html.twig
  templates/form_theme_admin.html.twig
  templates/user/my_donation.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Entity/DonationTest.php
  translations/messages.fr.yml
Labels: Ready for code review, Work in progress

#4042 Add additional adherent filters
  features/admin/adherent.feature
  src/Admin/AdherentAdmin.php
  templates/admin/adherent/list_status.html.twig
Labels: Ready for code review

#4044 [Jecoute] remove choices for simple fields
  src/Entity/Jecoute/Question.php
  src/Form/Jecoute/QuestionType.php
Labels: Bug, Ready for code review

#4045 [ReferentMessage] create default filter after message creation
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
Labels: Ready for code review

#4049 [AdherentMessage] add message preview link for mailchimp preview page
  app/config/parameters.yml.dist
  app/config/services/mailchimp.yaml
  app/config/services/services.xml
  src/Controller/EnMarche/AdherentMessage/CommonMessageController.php
  src/Mailchimp/SignUp/SignUpHandler.php
  templates/message/list.html.twig
Labels: Ready for code review

#4048 [Committee] Change page metadata description
  templates/committee/_layout.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4050 Fix committee metadata
  templates/committee/_layout.html.twig
Labels: Ready for code review

#3677 Add new CKEditor5 for adherent message form
  front/app.js
  front/services/form/CKEditor.js
  front/style/app.scss
  front/style/manager-space/_forms.scss
  package.json
  src/Controller/UploadDocumentController.php
  src/Form/AdherentMessage/AdherentMessageType.php
  templates/message/create.html.twig
  yarn.lock
Labels: Ready for code review
