Repository parti-renaissance/espace-adherent, pull requests merged in 2020-12, with the labels that each got.

#5137 Replace Router by UrlGenerator service
  src/Admin/DonationAdmin.php
  src/CitizenProject/CitizenProjectMessageNotifier.php
  src/Controller/Api/AdherentController.php
  src/Controller/Api/ReportController.php
  src/Controller/EnMarche/UserController.php
  src/Donation/DonationRequestUtils.php
  src/Donation/PayboxFormFactory.php
  src/EntityListener/ArticleListener.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  src/Normalizer/MoocNormalizer.php
  src/Security/UserChecker.php
  src/Serializer/MoocSerializerSubscriber.php
  src/Sitemap/SitemapFactory.php
  src/Timeline/TimelineFactory.php
  src/Twig/AssetRuntime.php
  src/Vision/IdentityDocumentParser.php
Labels: Ready for code review

#5141 Fix user count
  src/Repository/Projection/ManagedUserRepository.php
Labels: Bug, Ready for code review

#5134 User role normalization
  config/packages/framework.yaml
  config/services.yaml
  features/api/adherents.feature
  features/api/jecoute_departments.feature
  features/api/user.feature
  features/bootstrap/RestContext.php
  migrations/Version20201201114334.php
  src/Controller/Api/Jecoute/SurveyController.php
  src/Controller/Api/UserController.php
  src/Entity/Adherent.php
  src/Entity/Device.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Entity/OAuth/AbstractGrantToken.php
  src/Mailchimp/Synchronisation/EventListener/ElectedRepresentativeEventSubscriber.php
  src/Normalizer/AdherentNormalizer.php
  src/Normalizer/DeviceNormalizer.php
  src/Normalizer/JecouteAdherentNormalizer.php
  src/Normalizer/JecouteDeviceNormalizer.php
  src/Normalizer/JecouteSurveyNormalizer.php
  src/OAuth/AuthorizationValidators/JsonWebTokenValidator.php
  src/OAuth/Model/AbstractApiUser.php
  src/OAuth/Model/ClientApiUser.php
  src/OAuth/Model/DeviceApiUser.php
  src/OAuth/OAuthAuthenticator.php
  src/OAuth/PersistentTokenFactory.php
  src/Repository/IdeasWorkshop/IdeaRepository.php
  src/Repository/Jecoute/DataSurveyRepository.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  src/Security/Voter/LaREMAdherentVoter.php
  tests/Controller/Api/OAuthServerControllerTest.php
Labels: Ready for code review

#5146 [Admin] Fix algolia pagination on candidature admin
  config/settings/algolia_search/designation_candidate-settings.json
  src/Admin/Designation/CandidateAdmin.php
  src/Algolia/Sonata/Pager/Pager.php
Labels: Bug, Ready for code review

#5147 [CommitteeMerge] fix Aloglia sync by loading adherent names
  src/Repository/CommitteeMembershipRepository.php
  templates/admin/instances/candidate_list_entity_column.html.twig
Labels: Bug, Ready for code review

#5151 Update index.html.twig
  templates/donation/index.html.twig
Labels: Ready for code review

#5135 Update league/oauth2-server (from v6 to v8)
  composer.json
  composer.lock
  config/services/oauth.xml
  features/bootstrap/RestContext.php
  features/oauth.feature
  migrations/Version20201111020858.php
  src/DataFixtures/ORM/LoadClientData.php
  src/DataFixtures/ORM/LoadOAuthTokenData.php
  src/Entity/OAuth/AbstractGrantToken.php
  src/Entity/OAuth/AbstractToken.php
  src/Entity/OAuth/AuthorizationCode.php
  src/Entity/OAuth/RefreshToken.php
  src/OAuth/AuthorizationValidators/JsonWebTokenValidator.php
  src/OAuth/Grant/DeviceGrantTrait.php
  src/OAuth/Model/Client.php
  src/OAuth/OAuthAuthenticator.php
  src/OAuth/Store/AccessTokenStore.php
  src/OAuth/Store/ClientStore.php
  tests/Controller/Api/OAuthServerControllerTest.php
  tests/Entity/OAuth/AccessTokenTest.php
  tests/Entity/OAuth/AuthorizationCodeTest.php
  tests/Entity/OAuth/ClientTest.php
  tests/Entity/OAuth/UserAuthorizationTest.php
  tests/OAuth/PersistentTokenFactoryTest.php
Labels: Ready for code review, dependencies

#5153 [Form] replace string type notations
  src/Admin/AdherentAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/ElectedRepresentative/MandateAdmin.php
  src/Admin/ElectedRepresentative/PoliticalFunctionAdmin.php
  src/Admin/IdeasWorkshopIdeaAdmin.php
  src/Admin/JecouteSuggestedQuestionAdmin.php
  src/Admin/ProcurationProxyAdmin.php
  src/Admin/ProcurationRequestAdmin.php
  src/Admin/SummaryAdmin.php
Labels: Ready for code review

#5155 [Fixtures] improve zone fixtures
  dump/all-geo-zone.sql
  src/DataFixtures/ORM/AbstractFixtures.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadGeoData.php
  src/DataFixtures/ORM/LoadGeoZoneData.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/DataFixtures/ORM/LoadReferentTagsZonesLinksData.php
  src/DataFixtures/geo/geo-zones.csv
  src/Entity/ElectedRepresentative/Mandate.php
Labels: Ready for code review

#5148 [VotePlatform] Integrate majority vote
  front/listeners/em-modal.js
  front/style/mixins/_colors.scss
  front/style/voting-platform/_layout.scss
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/Form/VotingPlatform/VotePoolCollectionType.php
  src/Twig/VotingPlatformExtension.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/confirmation/_majority_vote_confirmation_block.html.twig
  templates/voting_platform/vote.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5156 [Jecoute] Add geo zone to survey
  features/api/surveys.feature
  features/referent_space.feature
  features/surveys.feature
  migrations/Version20201127155445.php
  src/Admin/AdherentAdmin.php
  src/Admin/JecouteLocalSurveyAdmin.php
  src/Command/ImportJecouteSurveysCommand.php
  src/Controller/Api/Jecoute/SurveyController.php
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  src/Controller/EnMarche/Jecoute/JecouteManagerController.php
  src/Controller/EnMarche/Jecoute/JecouteReferentController.php
  src/Controller/EnMarche/Jecoute/MunicipalChiefJecouteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadJecouteSurveyData.php
  src/Entity/Adherent.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/JecouteManagedArea.php
  src/Entity/ZoneManagedArea.php
  src/EventListener/ManageReferentTeamMembersListener.php
  src/Form/Admin/JecouteManagedAreaType.php
  src/Form/EventListener/RevokeManagedAreaSubscriber.php
  src/Form/Jecoute/SurveyFormType.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  src/Security/Voter/SurveyManagedAreaVoter.php
  templates/admin/jecoute/list_zone.html.twig
  templates/admin/jecoute/survey_edit.html.twig
  templates/jecoute/_form.html.twig
  templates/jecoute/_manager_space_layout.html.twig
  templates/jecoute/create.html.twig
  templates/jecoute/surveys_list.html.twig
  templates/referent/territorial_council/official_report_list.html.twig
Labels: Ready for code review

#5152 Link geo entities to geo_data
  dump/all-geo-zone.sql
  migrations/Version20201202105306.php
  src/Entity/Geo/GeoInterface.php
  src/Entity/Geo/GeoTrait.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5145 Permissive Zone name matching
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5140 Do not expand city group zone level filter
  src/Entity/Geo/Zone.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#5163 [VotingPlatform] fix display candidacy box on vote step
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/vote.html.twig
Labels: Bug, Ready for code review

#5165 [Jecoute] Fix getting surveys by postal code via API
  src/Controller/Api/Jecoute/SurveyController.php
  src/Form/Jecoute/DataSurveyFormType.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  tests/Filesystem/FileManagerTest.php
Labels: Ready for code review

#5167 [Test] Fix file permissions
  app/data/files/certification_requests/document/CNI.jpg
  src/Repository/CitizenProjectCategorySkillRepository.php
  tests/Filesystem/FileManagerTest.php
Labels: Ready for code review

#5174 Fix Sf4.4 migrations
  composer.json
  composer.lock
  config/packages/messenger.yaml
  config/services.yaml
  front/components/MessageStatusLoader.js
  public/apps/projets-citoyens/yarn.lock
  src/Controller/EnMarche/ProcurationManagerController.php
  src/Mailchimp/Exception/InvalidFilterException.php
  src/Mailchimp/Exception/StaticSegmentIdMissingException.php
  templates/adherent/pin_interests.html.twig
Labels: Bug, Ready for code review

#5175 [Adherent] fix committee list modal widget
  front/components/AdherentCommitteeList.js
  templates/base.html.twig
Labels: Bug, Ready for code review

#5177 [Config] Update Messenger configuration
  config/packages/messenger.yaml
Labels: Bug, Ready for code review

#5168 Zone features
  dump/all-geo-zone.sql
  migrations/Version20201202105306.php
  migrations/Version20201202140626.php
  src/Command/Geo/UpdateCityReplacementsCommand.php
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
  src/Deputy/Subscriber/BindAdherentZoneSubscriber.php
  src/Entity/EntityReferentTagTrait.php
  src/Entity/Geo/City.php
  src/Entity/Geo/GeoInterface.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Projection/ManagedUserRepository.php
  tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
  tests/Deputy/Subscriber/BindAdherentZoneSubscriberTest.php
Labels: Ready for code review

#5180 [VotingPlatform] update designation/election wording
  migrations/Version20201210112852.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Entity/VotingPlatform/Designation/Designation.php
  templates/committee/election_box/_committee_supervisor.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_committee_supervisor.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_stats_block.html.twig
Labels: Ready for code review

#5179 [Mailchimp] Synchronize zone team codes
  config/services/mailchimp.yaml
  dump/all-geo-zone.sql
  migrations/Version20201209165048.php
  src/Command/UpdateZoneTeamCodesFromCSVCommand.php
  src/Entity/Adherent.php
  src/Entity/EntityZoneTrait.php
  src/Entity/Geo/Zone.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#5183 Do not suggest inactive zone
  src/Controller/Api/ZoneController.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5188 [Mailchimp] Fix multiple department problem
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/EntityZoneTrait.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Security/Voter/CanEditSurveyVoter.php
Labels: Ready for code review

#5192 Dimitri/ch12948/la modale d invitation à se certifier a un
  front/style/layout/_modal.scss
  templates/voting_platform/vote.html.twig
Labels: Ready for code review

#5193 [Messenger] improve messenger libs/config
  composer.lock
  config/packages/messenger.yaml
  src/Adherent/Unregistration/Handlers/UnfollowCommitteeHandler.php
  symfony.lock
Labels: Ready for code review

#5197 Use custom type for survey field
  features/api/surveys.feature
  src/Form/DataTransformer/SurveyToIdTransformer.php
  src/Form/Jecoute/DataSurveyFormType.php
  src/Form/Jecoute/SurveyIdType.php
  translations/validators.fr.yml
Labels: Ready for code review

#5196 Add certified_at to managed users + change filters
  front/components/AdherentCommitteeList.js
  migrations/Version20201211111152.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Form/ManagedUsers/AbstractManagedUsersFilterType.php
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/Form/ManagedUsers/ReferentManagedUsersFilterType.php
  src/Form/TerritorialCouncil/MemberFilterType.php
  src/Form/ThematicCommunityMembershipFilterType.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/candidate/filter_form.html.twig
  templates/form_theme.html.twig
  templates/managed_users/_table.html.twig
  templates/managed_users/filter_form.html.twig
  templates/referent/territorial_council/members.html.twig
  templates/thematic_community/filter_form.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#5200 [CommitteeCandidacy] sync project fields on modification
  src/Committee/Election/CandidacyManager.php
Labels: Bug, Ready for code review

#5199 Link committees to zones
  migrations/Version20201214180957.php
  src/CitizenAction/CitizenActionEvent.php
  src/CitizenProject/CitizenProjectEvent.php
  src/Committee/CommitteeEvent.php
  src/Donation/DonationWasCreatedEvent.php
  src/Donation/DonationWasUpdatedEvent.php
  src/Entity/Committee.php
  src/Event/EventEvent.php
  src/Geo/Subscriber/ZoneAssignerSubscriber.php
  src/Geocoder/GeoHashChangeAwareTrait.php
  src/Geocoder/GeocodableEntityEventInterface.php
  src/Geocoder/Subscriber/EntityAddressGeocodingSubscriber.php
  src/InstitutionalEvent/InstitutionalEventEvent.php
  src/Membership/AdherentEvent.php
Labels: Ready for code review

#5205 Remove cookies consent and add Cookiebot
  .env
  .eslintrc
  config/packages/twig.yaml
  features/adherent_candidate.feature
  features/committee_vote.feature
  features/donation.feature
  features/municipal_chief_space.feature
  features/procuration_request.feature
  features/referent_space.feature
  features/surveys.feature
  front/app.js
  front/listeners/cookies-consent.js
  public/js/cookieconsent.min.js
  templates/base.html.twig
  templates/oauth/base.html.twig
Labels: Ready for code review

#5204 Link committees to zones
  src/Committee/CommitteeFactory.php
  src/Committee/Filter/ListFilter.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Form/Committee/CommitteeFilterType.php
  src/Geo/Subscriber/ZoneAssignerSubscriber.php
  src/Geo/ZoneMatcher.php
  src/Repository/CommitteeRepository.php
  src/Repository/Geo/ZoneRepository.php
  templates/referent/committees_list.html.twig
  tests/Committee/CommitteeFactoryTest.php
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Geo/ZoneMatcherTest.php
Labels: Ready for code review

#5210 Add link eurodéputés renaissance dans Nav Bar
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: front-end

#5211 Set Cookiebot on the top of the page
  templates/base.html.twig
  templates/oauth/base.html.twig
Labels: Ready for code review

#5212 [VotingPlatform] update wording on index page
  src/DataFixtures/ORM/LoadDesignationData.php
  templates/voting_platform/index.html.twig
Labels: Ready for code review

#5219 [VotingPlatform] fix vote on many committees
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/VotingPlatform/Voter.php
  src/Entity/VotingPlatform/VotersList.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Listener/AddNewVoterAfterCertificationListener.php
Labels: Bug, Ready for code review

#5221 [Committee] Change wording of the vote committee
  features/committee_vote.feature
  front/components/VoteCommitteeWidget.js
  templates/adherent/my_activity_committees.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee_manager/list_members.html.twig
  templates/managed_users/filter_form.html.twig
  templates/voting_platform/_designation_banner.html.twig
  templates/voting_platform/index.html.twig
Labels: Ready for code review

#5209 Link events to zones
  migrations/Version20201217161643.php
  src/Controller/EnMarche/EventManager/CandidateEventManagerController.php
  src/Controller/EnMarche/EventManager/DeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/ReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/SenatorEventManagerController.php
  src/DataFixtures/ORM/LoadEventData.php
  src/Entity/BaseEvent.php
  src/Entity/CitizenAction.php
  src/Entity/Event.php
  src/Entity/InstitutionalEvent.php
  src/Event/EventFactory.php
  src/Geo/Subscriber/ZoneAssignerSubscriber.php
  src/Repository/EventRepository.php
  templates/event_manager/events_list.html.twig
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
Labels: Ready for code review

#5222 Add zone filters in admin
  src/Admin/AdherentAdmin.php
  src/Admin/CommitteeAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/EventAdmin.php
  src/Admin/Filter/ZoneAutocompleteFilter.php
  src/Admin/JecouteLocalSurveyAdmin.php
Labels: Ready for code review

#5226 [Dev] refresh fixtures of home page
  app/data/dist/bandeau-PR-Ensemble-nous-reussirons.jpeg
  app/data/dist/logo-france-relance.jpeg
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadHomeBlockData.php
  templates/search/search.html.twig
Labels: Ready for code review

#5227 Introduce app:geo:zone-matcher command
  src/Command/Geo/ZoneMatcherCommand.php
  src/Entity/AddressHolderInterface.php
  src/Entity/BaseEvent.php
  src/Entity/Committee.php
  src/Geo/ZoneMatcher.php
Labels: Ready for code review

#5225 [VotingPlatform] many wording fixes
  features/api/adherents.feature
  features/sitemap.feature
  src/Command/VotingPlatform/CloseElectionCommand.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Controller/Api/CommitteesController.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Election.php
  src/Repository/CommitteeCandidacyRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  src/Security/Voter/Committee/CommitteeElectionVoter.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Security/ElectionAuthorisationChecker.php
  templates/adherent_profile/activity/_committees.html.twig
  templates/committee/_sidebar.html.twig
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee/election_box/_committee_supervisor.html.twig
  templates/committee_designation/list.html.twig
  templates/committee_designation/show_layout.html.twig
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/SearchControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/Repository/CommitteeRepositoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5223 Enable edit & delete routes for jecoute/notifications
  src/Admin/Jecoute/NewsAdmin.php
Labels: Je Marche !

#5235 Reduce the scope when matching by coordinates
  src/Command/Geo/ZoneMatcherCommand.php
  src/Geo/ZoneMatcher.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review
