Repository parti-renaissance/espace-adherent, pull requests merged in 2020-11, with the labels that each got.

#4971 Detect birthdate in multiple retrieved dates
  src/Vision/IdentityDocumentParser.php
  tests/Vision/IdentityDocumentParserTest.php
Labels: Ready for code review

#4978 Dimitri/ch12673/programmer les emails transacs
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Entity/VotingPlatform/Designation/ElectionEntityInterface.php
  src/Mailer/Message/AbstractVotingPlatformCandidacyInvitationMessage.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationRemovedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationAcceptedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationCreatedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationDeclinedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationRemovedMessage.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  src/TerritorialCouncil/Listeners/SendCandidacyEmailListener.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee/election_box/_committee_supervisor.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4981 [Committee] Fix candidacy security check
  src/Controller/Api/CommitteesController.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Entity/CommitteeCandidacy.php
  src/Repository/CommitteeMembershipRepository.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  templates/committee/election_box/_committee_supervisor.html.twig
Labels: Bug, Ready for code review

#4974 Add link to thematic communities (canary)
  src/Controller/EnMarche/ThematicCommunity/ThematicCommunityController.php
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#4983 [Committee] Update candidacy wording
  front/style/content/_em-tooltip.scss
  front/style/pages/_territorial-council.scss
  front/style/voting-platform/_candidacy.scss
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
  templates/adherent_profile/_layout.html.twig
  templates/committee/_sidebar.html.twig
  templates/committee/candidacy/candidacy_invitation.html.twig
  templates/committee/candidacy/candidacy_list.html.twig
  templates/committee/candidacy/form_committee_supervisor.html.twig
  templates/committee/election_box/_committee_supervisor.html.twig
Labels: Ready for code review

#4979 [EspaceCandidate] Add managed users list
  config/packages/security.yaml
  migrations/Version20201103112318.php
  src/Controller/EnMarche/InvitationController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/Entity/Adherent.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Exporter/ManagedUsersExporter.php
  src/Form/ManagedUsers/AbstractManagedUsersFilterType.php
  src/Form/ManagedUsers/CandidateManagedUsersFilterType.php
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/adherent/_list_my_sections.html.twig
  templates/adherent_space/_layout.html.twig
  templates/candidate/_layout.html.twig
  templates/candidate/_sidebar.html.twig
  templates/candidate/_table.html.twig
  templates/candidate/filter_form.html.twig
  templates/components/_nav_desktop.html.twig
  templates/invitation/adherent_space/_base_candidate_space.html.twig
  templates/managed_users/_base_candidate_space.html.twig
  templates/managed_users/_table.html.twig
  templates/managed_users/list.html.twig
  templates/referent/_sidebar.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#4986 [ADMIN] Fix adherents filters
  config/packages/security.yaml
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#4985 Update Actualites menu item
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#4989 Fix getting zone with ManagedAreaUtils
  src/Referent/ReferentZoneManager.php
  src/Utils/AreaUtils.php
  tests/Referent/ReferentZoneManagerTest.php
  tests/Utils/AreaUtilsTest.php
Labels: Ready for code review

#4990 [MyCommittee] display election details on my committees page
  front/style/layout/_cards.scss
  templates/adherent_profile/activity/_adi.html.twig
  templates/adherent_profile/activity/_citizen_projects.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/adherent_profile/activity/_events.html.twig
  templates/adherent_profile/activity/_instances.html.twig
  templates/territorial_council/political_committee/official_reports.html.twig
Labels: Ready for code review

#4992 [PoliticalCommittee] fix name of downloaded files
  src/Entity/TerritorialCouncil/OfficialReportDocument.php
Labels: Bug, Ready for code review

#4980 Filter elected via geo zone in "espace référent" and LRE
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  src/Controller/Api/ZoneController.php
  src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/Geo/ZoneRepository.php
  symfony.lock
  templates/elected_representative/list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4995 Update InfoCovid link
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#4984 Candidate space add event page
  migrations/Version20201103161100.php
  src/Admin/EventGroupCategoryAdmin.php
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/CandidateEventManagerController.php
  src/DataFixtures/ORM/LoadEventCategoryData.php
  src/DataFixtures/ORM/LoadEventGroupCategoryData.php
  src/Entity/EventGroupCategory.php
  src/Event/EventManagerSpaceEnum.php
  src/Form/EventCommandType.php
  src/Form/EventGroupCategoryType.php
  src/Repository/BaseEventCategoryRepository.php
  src/Repository/CitizenActionCategoryRepository.php
  src/Repository/EventCategoryRepository.php
  src/Repository/EventGroupCategoryRepository.php
  src/Repository/EventRepository.php
  src/Repository/ReferentTagRepository.php
  templates/candidate/_sidebar.html.twig
  templates/event_manager/_base_candidate_space.html.twig
  templates/event_manager/_event_row.js.twig
  templates/event_manager/event_create.html.twig
  templates/event_manager/events_list.html.twig
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Test/Geocoder/DummyGeocoder.php
Labels: Ready for code review

#4991 [Adherent] validate email address on update
  src/AdherentProfile/AdherentProfile.php
  src/Admin/AdherentAdmin.php
  src/Controller/EnMarche/UserController.php
  src/Entity/Adherent.php
  src/Form/EventListener/BoardMemberListener.php
  src/Repository/AdherentRepository.php
  src/Validator/UniqueMembershipValidator.php
Labels: Bug, Ready for code review

#4996 Update committee election box display
  public/images/icons/icn_close-rose.svg
  public/images/icons/icn_vote-rose.svg
  src/Entity/Adherent.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  templates/adherent_profile/activity/_committees.html.twig
  templates/voting_platform/_designation_banner.html.twig
Labels: Ready for code review

#5000 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: Security

#5003 [CommitteeElection] update committee voting switch on candidate
  src/Committee/CommitteeManager.php
  src/Committee/EventListener/UpdateVotingCommitteeOnCandidateListener.php
Labels: Ready for code review

#5002 [CommitteeElection] Do not allow to candidate for parliamentary elect…
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/adherent_profile/activity/_committees.html.twig
Labels: Ready for code review

#5005 [CommitteeMerge] move committee candidacies on merge
  features/admin/committee_merge.feature
  src/Committee/CommitteeMergeCommandHandler.php
Labels: Ready for code review

#5006 Review and fix new zones usage
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/Form/Geo/ZoneType.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#5007 [ManagedUsers] hide phone numbers for delegated access until 24/12
  src/Adherent/AdherentExtractCommandHandler.php
  src/Admin/CertificationRequestAdmin.php
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
  src/Assessor/AssessorRequestExporter.php
  src/Assessor/AssessorRequestFactory.php
  src/CitizenProject/CitizenProjectFactory.php
  src/Committee/CommitteeFactory.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/DataFixtures/ORM/LoadCitizenProjectData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadElectionCityCardData.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/DataFixtures/ORM/LoadThematicCommunityContactData.php
  src/Donation/DonatorExtractCommandHandler.php
  src/Mailer/Message/ProcurationProxyFoundMessage.php
  src/Mailer/Message/ProcurationProxyReminderMessage.php
  src/Membership/AdherentFactory.php
  src/Utils/PhoneNumberUtils.php
  templates/managed_users/_table.html.twig
  templates/referent/_sidebar.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Membership/AdherentFactoryTest.php
Labels: Ready for code review

#5009 Fix zone filter
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5011 [Committee] add tooltip for disabled candidadate/vote buttons
  front/style/content/_em-tooltip.scss
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee/election_box/_committee_supervisor.html.twig
Labels: Ready for code review

#5012 Update limit date of CoTerr meeting
  config/services.yaml
Labels: Ready for code review

#5014 Allow to remove a relation parent/child in app:geo:sync-zones command
  src/Command/Geo/SyncZonesCommand.php
Labels: Ready for code review

#5010 [Admin] Add files admin
  config/packages/security.yaml
  config/services.yaml
  config/services/admin.xml
  migrations/Version20201112154218.php
  src/Admin/AdministratorAdmin.php
  src/Admin/Filesystem/FileAdmin.php
  src/Controller/Admin/AdminFileController.php
  src/Controller/EnMarche/Filesystem/FileController.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadFileData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Filesystem/File.php
  src/Entity/Filesystem/FilePermission.php
  src/Entity/Filesystem/FilePermissionEnum.php
  src/Entity/Filesystem/FileTypeEnum.php
  src/Filesystem/FileManager.php
  src/Form/Admin/Filesystem/FileParentType.php
  src/Form/Admin/Filesystem/FilePermissionType.php
  src/Repository/Filesystem/FileRepository.php
  src/Security/Voter/Filesystem/DownloadFileVoter.php
  symfony.lock
  templates/admin/filesystem/list_actions.html.twig
  templates/admin/filesystem/list_permissions.html.twig
  templates/form_theme_admin.html.twig
  tests/Controller/EnMarche/Filesystem/FileControllerTest.php
  tests/Filesystem/FileManagerTest.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#5015 Synchronize Adherent zones with mailchimp
  src/Entity/Geo/GeoTrait.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Work in progress

#5016 [EspaceCandidate] Add documents
  front/style/manager-space/_tables.scss
  src/Controller/Admin/AdminFileController.php
  src/Controller/EnMarche/Filesystem/AbstractFilesController.php
  src/Controller/EnMarche/Filesystem/CandidateFilesController.php
  src/Controller/EnMarche/Filesystem/FileController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadFileData.php
  src/Entity/Adherent.php
  src/Entity/Filesystem/File.php
  src/Repository/Filesystem/FileRepository.php
  src/Security/Voter/Filesystem/DownloadFileVoter.php
  templates/admin/filesystem/list_actions.html.twig
  templates/candidate/_sidebar.html.twig
  templates/filesystem/_base_candidate_space.html.twig
  templates/filesystem/_layout.html.twig
  templates/filesystem/list.html.twig
  templates/form_theme_admin.html.twig
  tests/Controller/Admin/AdminFileControllerTest.php
  tests/Controller/EnMarche/Filesystem/CandidateFilesControllerTest.php
  tests/Controller/EnMarche/Filesystem/FilesControllerTest.php
Labels: Ready for code review

#5018 Dimitri/ch12765/modale de connexion invitant à se certifier
  config/services.yaml
  front/components/Modal.js
  front/listeners/em-modal.js
  front/style/layout/_modal.scss
  front/style/manager-space/_base-layout.scss
  front/style/pages/_committee.scss
  front/style/pages/_territorial-council.scss
  front/style/voting-platform/_layout.scss
  src/Adherent/SessionModal/SessionModalActivatorListener.php
  src/DataFixtures/ORM/LoadCertificationData.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/adherent/my_activity_committees.html.twig
  templates/adherent_profile/activity.html.twig
  templates/base.html.twig
  templates/certification_request/_layout.html.twig
  templates/committee/candidacy/candidacy_list.html.twig
  templates/committee/candidacy/invitation_list.html.twig
  templates/committee/edit_candidacy.html.twig
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee/election_box/_committee_supervisor.html.twig
  templates/committee/show.html.twig
  templates/components/_adherent_session_modal.html.twig
  templates/managed_users/list.html.twig
  templates/message/list.html.twig
  templates/referent/committees_list.html.twig
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/invitation_list.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/thematic_community/members.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
Labels: Ready for code review

#5019 [Committee] Close adherent mandat on committee merge
  migrations/Version20201117122118.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
Labels: Ready for code review

#5021 [EspaceCandidate] Change documents table display
  src/Controller/EnMarche/Filesystem/AbstractFilesController.php
  src/Entity/Filesystem/File.php
  templates/filesystem/list.html.twig
  tests/Controller/EnMarche/Filesystem/CandidateFilesControllerTest.php
Labels: Ready for code review

#5023 Fix session modal title
  src/Adherent/SessionModal/SessionModalActivatorListener.php
  templates/adherent_profile/activity/_committees.html.twig
  templates/components/_adherent_session_modal.html.twig
Labels: Bug, Ready for code review

#5024 Fix zone filter in candidate space
  features/adherent_candidate.feature
  templates/candidate/filter_form.html.twig
Labels: Ready for code review

#5027 Fix candidate message
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  templates/message/filter/candidate.html.twig
Labels: Ready for code review

#5028 [EspaceCandidate] Add a chart
  src/AdherentCharter/AdherentCharterFactory.php
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/Collection/AdherentCharterCollection.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/AdherentCharter/CandidateCharter.php
  templates/candidate/_layout.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5030 [EspaceCandidate] Fix documents display depending on role
  src/Controller/EnMarche/Filesystem/AbstractFilesController.php
  templates/candidate/_sidebar.html.twig
Labels: Ready for code review

#5031 Show adherents with delegated access for specific space
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#5032 Fix filtering by zone
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#5034 Fix cities' INSEE code building in update districts command
  src/Command/Geo/UpdateDistrictsCommand.php
Labels: Ready for code review

#5033 Refactor zone filtering in mandate form
  src/Controller/Admin/AdminZoneController.php
  src/Entity/ElectedRepresentative/MandateTypeEnum.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5029 Add Region entity+endpoint
  config/packages/security.yaml
  config/services.yaml
  config/services/admin.xml
  config/services/cms.xml
  features/api/jecoute_regions.feature
  migrations/Version20201120165911.php
  src/Admin/Jecoute/RegionAdmin.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/Jecoute/Region.php
  src/Exception/InvalidUrlAdapterException.php
  src/Normalizer/RegionNormalizer.php
  src/Storage/FilesystemAdapterFactory.php
  src/Storage/GoogleStorageAdapter.php
  src/Storage/UrlAdapterInterface.php
  src/Storage/WebLocalAdapter.php
  tests/Storage/FilesystemAdapterFactoryTest.php
Labels: Ready for code review

#5071 Add pagination to events page in spaces
  features/deputy.feature
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/CandidateEventManagerController.php
  src/Controller/EnMarche/EventManager/DeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/MunicipalChiefEventManagerController.php
  src/Controller/EnMarche/EventManager/ReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/SenatorEventManagerController.php
  src/Repository/EventRepository.php
  templates/event_manager/_event_row.js.twig
  templates/event_manager/events_list.html.twig
Labels: Ready for code review

#5076 Append zone filter in pagination widget
  src/ElectedRepresentative/Filter/ListFilter.php
  src/ManagedUsers/ManagedUsersFilter.php
Labels: Bug, Ready for code review

#5082 [TerritorialCouncil] Update memberships of ElectedRepresentatives
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/Geo/Zone.php
  src/Repository/ElectedRepresentative/MandateRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilConsularCouncilorHandler.php
Labels: Ready for code review

#5086 [ADI] improve check of Adherent session
  src/Normalizer/IdeaNormalizer.php
Labels: Ready for code review

#5091 [CommitteeCandidacy] prevent enter key and validate empty invitation
  front/components/CommitteeCandidacyWidget.js
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Form/Committee/CandidacyBinomeType.php
Labels: Bug, Ready for code review

#5093 [Jecoute] set public image access permission
  src/Admin/Jecoute/RegionAdmin.php
Labels: Ready for code review

#5094 Validate zone before filtering users
  src/Controller/Api/ZoneController.php
  src/Controller/EnMarche/ElectedRepresentative/DeputyElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/SenatorElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/SenatorialCandidateElectedRepresentativeController.php
  src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/Form/AdherentMessage/AdherentGeoZoneFilterType.php
  src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Form/ManagedUsers/AbstractManagedUsersFilterType.php
  src/Geo/ManagedZoneProvider.php
  src/Validator/ManagedZone.php
  src/Validator/ManagedZoneValidator.php
  templates/message/filter/candidate.html.twig
Labels: Ready for code review

#5095 Better zone grouping in zone filter widget
  src/Controller/Api/ZoneController.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5103 Make Region color a choice
  features/api/jecoute_regions.feature
  src/Admin/Jecoute/RegionAdmin.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/Jecoute/Region.php
  src/Jecoute/RegionColorEnum.php
  translations/messages.fr.yml
Labels: Ready for code review

#5104 Some js fixes
  templates/adherent_space/_layout.html.twig
  templates/bot/_javascript.html.twig
  templates/bot/_stylesheet.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/desintox/view.html.twig
  templates/page/emmanuel-macron/layout.html.twig
  templates/page/le-mouvement/layout.html.twig
  templates/program/proposal.html.twig
Labels: Bug, Ready for code review

#5101 Create dependabot.yml
  .github/dependabot.yml
Labels: Security

#5102 [TerritorialCouncil] Add geo zones + change memberships update command
  migrations/Version20201125105646.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/Geo/Zone.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
Labels: Ready for code review

#5105 Rebuild link between adherent and district on updating adherent
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
Labels: Ready for code review

#5117 Add corsica assembly member
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilCorsicaAssemblyMemberHandler.php
  src/Validator/TerritorialCouncil/ValidSearchAvailableMembershipFilterValidator.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5121 [Certification] Add id processing GDPR
  src/Form/CertificationRequestType.php
  templates/certification_request/form.html.twig
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
Labels: Ready for code review

#5118 Take in account both managed and zones on filtering
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#5124 [Certification] Add id processing GDPR info
  src/Form/CertificationRequestType.php
  templates/certification_request/form.html.twig
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
Labels: Ready for code review

#5119 Add News entity, admin & endpoints (+region fixes)
  config/packages/security.yaml
  config/services/admin.xml
  features/api/jecoute_news.feature
  features/api/jecoute_regions.feature
  migrations/Version20201126141427.php
  src/Admin/Jecoute/NewsAdmin.php
  src/Admin/Jecoute/RegionAdmin.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Jecoute/News.php
  src/Entity/Jecoute/Region.php
Labels: Ready for code review

#5120 Make logo not required at edition, allow nullable logos (for bulk inserts)
  migrations/Version20201126133559.php
  src/Admin/Jecoute/RegionAdmin.php
  src/Entity/Jecoute/Region.php
Labels: Ready for code review

#5125 [TerritorialCouncil] Update only elected representative while memberships update command
  src/Command/UpdateTerritorialCouncilMembershipsCommand.php
Labels: Ready for code review

#5122 Add Department endpoint - Remove Region endpoint
  config/services.yaml
  features/api/jecoute_departments.feature
  features/api/jecoute_regions.feature
  migrations/Version20201126191138.php
  src/Admin/Jecoute/RegionAdmin.php
  src/Controller/Api/Jecoute/DepartmentController.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Jecoute/Region.php
  src/Normalizer/JecouteDepartmentNormalizer.php
  src/Normalizer/JecouteRegionNormalizer.php
  src/Repository/Geo/DepartmentRepository.php
  src/Repository/Jecoute/RegionRepository.php
Labels: Ready for code review

#5123 Fix committee share button
  src/Controller/EnMarche/AdherentProfile/Informations/ElectionsController.php
  templates/adherent_profile/informations/elections.html.twig
  templates/committee/_layout.html.twig
  templates/committee/show.html.twig
Labels: Bug, Ready for code review

#5126 [DelegatedAccess] fix zone filter
  src/Form/ZoneAutoCompleteType.php
  src/Validator/ManagedZoneValidator.php
Labels: Bug, Ready for code review

#5130 Fix zone filter validation in LRE space
  src/Validator/ManagedZoneValidator.php
Labels: Ready for code review

#5131 Search for boroughs in zone autocompletion endpoint
  src/Controller/Api/ZoneController.php
Labels: Ready for code review

#5133 Update to sf 3.4.47
  composer.lock
Labels: Ready for code review, dependencies

#5081 [VotingPlatform] allow to configure majority vote
  features/api/adherents.feature
  features/sitemap.feature
  front/style/voting-platform/_layout.scss
  migrations/Version20201123122651.php
  src/Command/VotingPlatformConfigureCommand.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
  src/Entity/VotingPlatform/VoteChoice.php
  src/Form/VotingPlatform/MajorityVoteChoiceType.php
  src/Form/VotingPlatform/VotePoolCollectionType.php
  src/Repository/CommitteeCandidacyRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/VotingPlatform/Designation/MajorityVoteMentionEnum.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Election/VoteCommand/VoteCommand.php
  templates/voting_platform/_layout_committee_adherent.html.twig
  templates/voting_platform/_layout_committee_base.html.twig
  templates/voting_platform/_layout_committee_supervisor.html.twig
  templates/voting_platform/_layout_copol.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/confirmation/_confirmation_block.html.twig
  templates/voting_platform/confirmation/_majority_vote_confirmation_block.html.twig
  templates/voting_platform/vote.html.twig
  templates/voting_platform/vote_step/_candiates_list.html.twig
  templates/voting_platform/vote_step/_majority_vote_candidate_box.html.twig
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Controller/Api/CommitteesControllerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/SearchControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/Repository/CommitteeRepositoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5129 Store extra parameters on oauth requests
  features/oauth.feature
  migrations/Version20201130131955.php
  src/DataFixtures/ORM/LoadClientData.php
  src/Entity/Device.php
  src/Entity/OAuth/AbstractGrantToken.php
  src/OAuth/AuthorizationServerFactory.php
  src/OAuth/AuthorizationValidators/JsonWebTokenValidator.php
  src/OAuth/Grant/ClientCredentialsGrant.php
  src/OAuth/Grant/DeviceGrantTrait.php
  src/OAuth/Grant/PasswordGrant.php
  src/OAuth/Model/AccessToken.php
  src/OAuth/Model/DeviceAccessTokenInterface.php
  src/OAuth/Model/DeviceApiUser.php
  src/OAuth/OAuthAuthenticator.php
  src/OAuth/PersistentTokenFactory.php
  src/OAuth/Store/AccessTokenStore.php
  src/Repository/DeviceRepository.php
  tests/Controller/Api/OAuthServerControllerTest.php
  tests/OAuth/PersistentTokenFactoryTest.php
Labels: Ready for code review

#5132 Link managed user to multiple zones
  migrations/Version20201130121116.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/Entity/EntityZoneTrait.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/managed_users/_table.html.twig
Labels: Ready for code review
