Repository parti-renaissance/espace-adherent, pull requests merged in 2020-04, with the labels that each got.

#4374 [AdherentMessage] add basic filters for Deputy and Senator
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/AdherentZoneMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/Entity/AdherentMessage/DeputyAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AdherentZoneFilter.php
  src/Entity/AdherentMessage/Filter/BasicUserFiltersTrait.php
  src/Entity/AdherentMessage/Filter/ReferentUserFilter.php
  src/Entity/AdherentMessage/MailchimpCampaign.php
  src/Entity/AdherentMessage/SenatorAdherentMessage.php
  src/Form/AdherentMessage/AdherentZoneFilterType.php
  src/Form/AdherentMessage/ReferentFilterType.php
  src/Form/CommitteeChoiceType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AbstractStaticSegmentConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentInterestConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentRegistrationDateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentSegmentConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentZoneConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/CitizenProjectConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/CommitteeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactAgeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactCityConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToAdherentConditionBuilder.php
  src/Repository/CommitteeRepository.php
  templates/form_theme.html.twig
  templates/message/filter/_adherent_zone_filter.html.twig
  templates/message/filter/deputy.html.twig
  templates/message/filter/senator.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
  tests/Controller/EnMarche/DeputyControllerTest.php
Labels: Ready for code review

#4376 Add message_redactor role to Senator
  src/Entity/Adherent.php
Labels: Bug, Ready for code review

#4375 [ApiSync] sync approved date for citizen projet
  features/admin/citizen_project.feature
  features/sync_with_api.feature
  src/Entity/BaseGroup.php
  web/apps/projets-citoyens/src/js/actions/citizen-projects.js
Labels: Ready for code review

#4371 [ADMIN] ElectedRepresentative : change the design
  app/config/services/admin.xml
  src/Admin/ElectedRepresentative/SocialNetworkLinkAdmin.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/Entity/ElectedRepresentative/Sponsorship.php
  src/Form/SocialNetworkLinkType.php
  templates/admin/elected_representative/edit.html.twig
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4373 [ADMIN] ElectedRepresentative : change the design
  app/config/services/admin.xml
  app/config/services/services.xml
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeLabelAdmin.php
  src/Admin/ElectedRepresentative/MandateAdmin.php
  src/Admin/ElectedRepresentative/PoliticalFunctionAdmin.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Form/ElectedRepresentative/PoliticalFunctionType.php
  src/Repository/ElectedRepresentative/MandateRepository.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4380 [Adhesion] Use France as prefered choice
  src/Form/AdherentRegistrationType.php
  src/Form/AdherentType.php
Labels: Ready for code review

#4379 [AdherentMessage] improve UX by adding test & preview button on filte…
  front/components/MessageStatusLoader.js
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  templates/message/filter.html.twig
Labels: Ready for code review

#4382 Add Google autocomplete on adherent update page
  front/app.js
  front/pages/profile_update.js
  front/services/address/AutocompletedAddressForm.js
  templates/adherent/profile.html.twig
Labels: Ready for code review

#4381 Update unregistration wording on my_account page
  src/Entity/Adherent.php
  templates/user/my_account.html.twig
  tests/Controller/EnMarche/UnregistrationControllerTest.php
Labels: Ready for code review

#4383 Update adresse autocomplete on my-account page
  front/pages/profile_update.js
  front/services/address/AutocompletedAddressForm.js
  front/services/address/GooglePlaceAutocomplete.js
Labels: Ready for code review

#4385 Fix city card export by increasing memory&time limit
  front/pages/profile_update.js
  src/Admin/Election/CityCardAdmin.php
  src/Controller/Admin/AdminExportCityCardController.php
  src/Utils/PhpConfigurator.php
Labels: Ready for code review

#4384 [ADMIN] ElectedRepresentative : change some design
  src/Admin/ElectedRepresentative/MandateAdmin.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4386 [Election] Add Command for importing votePlace results
  app/config/services/services.xml
  src/Command/ImportElectionVotePlaceResultsCommand.php
  src/Election/ElectionManager.php
  src/Entity/Election/VoteResultListCollection.php
Labels: Ready for code review

#4387 Clean figure for article img
  front/style/layout/_base.scss
Labels: Ready for code review

#4388 Rollback message buttons position
  front/components/MessageStatusLoader.js
  templates/message/filter.html.twig
Labels: Ready for code review

#4389 Add small size class for article img
  docs/content-styleguide.md
  front/style/content/_inside-common.scss
Labels: Ready for code review

#4393 Fix red button on citizen project page menu
  web/apps/projets-citoyens/src/style/layout/_buttons.scss
  web/apps/projets-citoyens/src/style/mixins/_colors.scss
Labels: Ready for code review

#4392 Add filters & improve Donations admin
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
  src/Entity/Donator.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4396 Improve donation admins
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
  src/Form/Admin/DonatorExtractType.php
Labels: Ready for code review

#4395 Match adherents to donator even if not enabled yet
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
  src/Form/Admin/DonatorExtractType.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#4401 Update wording on assessor request
  templates/assessor_request/_fill_personal_info.html.twig
  templates/assessor_request/_layout.html.twig
Labels: Ready for code review

#4403 Improve extract of data & admins
  app/config/services/admin.xml
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
  src/Controller/Admin/AdminDonationController.php
  src/Donation/DonatorExtractCommand.php
  src/Donation/DonatorExtractCommandHandler.php
  src/Entity/Donation.php
  src/Entity/Donator.php
  src/Form/Admin/DonatorExtractType.php
  templates/admin/donation/action_button_refund.html.twig
  templates/admin/donator/edit.html.twig
  templates/admin/donator/list_is_adherent.html.twig
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4402 [CityCard] improve export and change priority filter
  migrations/Version20200410155343.php
  src/Admin/Election/AbstractCityCardAdmin.php
  src/Admin/Election/CityCardAdmin.php
  src/Controller/Admin/AdminExportCityCardController.php
  src/Controller/Api/CrmParisController.php
  src/DataFixtures/ORM/LoadElectionData.php
  src/DataFixtures/ORM/LoadMinistryVoteResultData.php
  src/DataFixtures/ORM/LoadVotePlaceResultData.php
  src/DataFixtures/ORM/LoadVoteResultListCollectionData.php
  src/Entity/Election/BaseWithListCollectionResult.php
  src/Entity/Election/MinistryVoteResult.php
  src/Repository/Election/CityVoteResultRepository.php
  src/Repository/Election/MinistryVoteResultRepository.php
  src/Repository/Election/VotePlaceResultRepository.php
  templates/admin/city_card/list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4404 [CityCard] display outgoing mayor statut
  migrations/Version20200410161254.php
  src/Election/CityResults.php
  src/Entity/Election/ListFieldTrait.php
  templates/admin/election/city_card/edit.html.twig
Labels: Ready for code review

#4405 [CityCard] display municipal election result history
  src/DataFixtures/ORM/LoadElectionData.php
  src/DataFixtures/ORM/LoadMinistryVoteResultData.php
  src/Election/ElectionManager.php
  src/Entity/Election.php
  src/Entity/ElectionRound.php
  src/Repository/Election/MinistryVoteResultRepository.php
  src/Repository/ElectionRepository.php
  src/Twig/ElectionVoteResultExtension.php
  src/Twig/ElectionVoteResultRuntime.php
  templates/admin/election/city_card/edit.html.twig
Labels: Ready for code review

#4406 [VoteResult] fix import command
  src/Command/ImportElectionVotePlaceResultsCommand.php
  src/Election/ElectionManager.php
  src/Repository/ElectionRepository.php
  src/Twig/ElectionVoteResultRuntime.php
Labels: Bug, Ready for code review

#4407 [CityCard] improve result aggregation
  src/Controller/Admin/AdminExportCityCardController.php
  src/Election/CityResultAggregator.php
  src/Twig/ElectionVoteResultRuntime.php
Labels: Ready for code review

#4378 Update en-marche nav
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Don't merge, Ready for code review

#4411 Add dropdown on "Nos idées" item
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4412 Add item "publications" on nav
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4410 [ReferentSpace] display committee candidacy count on committee list
  config/packages/doctrine.yaml
  src/Controller/EnMarche/ReferentController.php
  src/Repository/CommitteeRepository.php
  templates/committee_manager/list_members.html.twig
  templates/referent/committees_list.html.twig
Labels: Ready for code review

#4413 Export address on multiple columns
  src/Admin/DonationAdmin.php
  src/Admin/DonatorAdmin.php
Labels: Ready for code review

#4415 [CommitteeCandidacy] send confirmations emails
  config/services/voting_platform.yaml
  features/bootstrap/EmailContext.php
  features/committee_vote.feature
  src/Committee/CommitteeManager.php
  src/Entity/CommitteeElection.php
  src/Mailer/Message/CommitteeCandidacyCreatedConfirmationMessage.php
  src/Mailer/Message/CommitteeCandidacyRemovedConfirmationMessage.php
  src/Mailer/Message/CommitteeNewCandidacyNotificationMessage.php
  src/Mailer/Message/CommitteeRemovedCandidacyNotificationMessage.php
  src/VotingPlatform/Event/CommitteeCandidacyEvent.php
  src/VotingPlatform/Events.php
  src/VotingPlatform/Listener/SendCandidacyEmailsListener.php
  templates/committee/show.html.twig
Labels: Ready for code review

#4349 [Committee] Global lifting
  Makefile
  features/committee_vote.feature
  front/style/app.scss
  front/style/layout/_avatar.scss
  front/style/layout/_buttons.scss
  front/style/manager-space/_base-layout.scss
  front/style/mixins/_colors.scss
  front/style/pages/_committee.scss
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_host_header.html.twig
  templates/committee/_layout.html.twig
  templates/committee/_sidebar.html.twig
  templates/committee/show.html.twig
  templates/committee/timeline/_event.html.twig
  templates/committee/timeline/_feed.html.twig
  templates/committee/timeline/_message.html.twig
  templates/components/_annimated_sub_menu.html.twig
  templates/components/location.html.twig
  templates/components/share.html.twig
  templates/components/users.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Work in progress

#4425 [Certification] Integration ajustments
  front/style/layout/_forms-em.scss
  front/style/layout/_layout.scss
  front/style/pages/_profile.scss
  src/Adherent/CertificationPermissions.php
  src/Security/Voter/CertificationRequestVoter.php
  src/Security/Voter/CertificationVoter.php
  templates/certification_request/_layout.html.twig
  templates/certification_request/form.html.twig
  templates/certification_request/home.html.twig
  templates/components/_header.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
  tests/Security/Voter/CertificationRequestVoterTest.php
  tests/Security/Voter/CertificationVoterTest.php
  web/images/icons/certification/blocked.svg
  web/images/icons/certification/certification_confettis.svg
  web/images/icons/certification/certified-lg.svg
  web/images/icons/certification/certified-sm.svg
  web/images/icons/certification/not-certified.svg
  web/images/icons/certification/on-waiting.svg
Labels: Ready for code review

#4424 [ESPACE REFERENT] Add a limited co-referent
  features/referent-organizational-chart.feature
  front/style/layout/_forms.scss
  migrations/Version20200423124633.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/DataFixtures/ORM/LoadOrganizationalChartItemData.php
  src/Entity/Adherent.php
  src/Entity/ReferentOrganizationalChart/ReferentPersonLink.php
  src/Entity/ReferentTeamMember.php
  src/EntityListener/RevokeReferentTeamMemberRolesListener.php
  src/EventListener/ManageReferentTeamMembersListener.php
  src/Form/ReferentPersonLinkType.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/referent/edit_referent_person_link.html.twig
  templates/referent/organizational_chart_macros.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4427 Add "Nos sénateurs" to EM nav
  templates/components/_footer.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#3907 [New-Sf-Structure] step 3: add dotEnv
  .env
  .env.dev
  .env.test
  .gitignore
  .php_cs.dist
  Dockerfile
  Makefile
  app/config/config_prod.yml
  app/config/parameters.yml.dist
  app/config/services/services.yml
  behat.yml.dist
  bin/console
  composer.json
  composer.lock
  config/bootstrap.php
  config/bundles.php
  config/routes.yaml
  config/services.yaml
  config/services/admin.xml
  config/services/cms.xml
  config/services/community.xml
  config/services/external_services.xml
  config/services/http_client.yaml
  config/services/oauth.xml
  config/services/platform.xml
  config/services/services.xml
  config/services/system.xml
  config/services/twig.xml
  config/services_dev.yaml
  config/services_dev_front.yaml
  config/services_test.yaml
  config/trusted_proxies.php
  docker-compose.ci.yml
  docker/dev/Dockerfile
  docker/dev/symfony.conf
  docker/prod/nginx.conf
  features/bootstrap/bootstrap.php
  phpunit.xml.dist
  src/Controller/AssetsController.php
  src/Kernel.php
  tests/Controller/Admin/AdminChezVousCityControllerTest.php
  tests/Controller/Admin/AdminTimelineMeasureControllerTest.php
  tests/Controller/Api/OAuthServerControllerTest.php
  tests/Donation/TransactionSubscriberTest.php
  web/index.php
Labels: Ready for code review

#4418 [Committee] Hotfixes
  .gitignore
  config/services/admin.xml
  config/services/services.xml
  features/committee_vote.feature
  front/app.js
  front/components/CandidaciesListWidget.js
  front/components/VoteCommitteeWidget.js
  front/listeners/confirm-modal.js
  front/services/utils/imageCropper.js
  front/style/manager-space/_base-layout.scss
  front/style/pages/_committee.scss
  migrations/Version20200427193951.php
  package.json
  src/Admin/ExecutiveOfficeMemberAdmin.php
  src/Admin/IdeasWorkshopThemeAdmin.php
  src/Biography/BiographyManager.php
  src/Committee/CommitteeManager.php
  src/Controller/EnMarche/CommitteeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/Entity/Biography/AbstractBiography.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/IdeasWorkshop/Theme.php
  src/Entity/ImageOwnerInterface.php
  src/Entity/ImageTrait.php
  src/Form/VotingPlatform/CandidateProfileType.php
  src/IdeasWorkshop/ThemeManager.php
  src/Image/ImageManager.php
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/committee/_layout.html.twig
  templates/committee/_sidebar.html.twig
  templates/committee/edit_candidacy.html.twig
  templates/committee/show.html.twig
  templates/committee/timeline/_event.html.twig
  templates/components/_annimated_sub_menu.html.twig
  webpack.common.js
  yarn.lock
Labels: Ready for code review

#4431 Sf update to 3.4.40
  composer.lock
Labels: Ready for code review

#4332 Add SQL to migrate data from 'elected_representatives_register' to multiple tables
  config/services/services.xml
  elected_representative_migration.sql
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Command/RestructureElectedRepresentativesRegisterCommand.php
  src/Entity/ElectedRepresentative/PoliticalFunctionNameEnum.php
Labels: Ready for code review
