Repository parti-renaissance/espace-adherent, pull requests merged in 2020-06, with the labels that each got.

#4513 Add descriptif note on my committees page
  templates/adherent/my_activity_committees.html.twig
Labels: Ready for code review

#4514 [Committee] change missing candidate warning
  templates/committee/_election_box.html.twig
Labels: Ready for code review

#4515 Update SF from 3.4.40 to 3.4.41
  composer.lock
Labels: Ready for code review

#4516 [Committee] Remove Voting column for host of committee
  templates/committee_manager/list_members.html.twig
Labels: Ready for code review

#4510 Dimitri/ch11545/vote espace affichage des désignations dans
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_tables.scss
  front/style/voting-platform/_layout.scss
  src/Controller/EnMarche/Designation/AbstractDesignationController.php
  src/Controller/EnMarche/Designation/ReferentDesignationController.php
  src/Controller/EnMarche/Designation/SupervisorDesignationController.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Voter.php
  src/Entity/VotingPlatform/VotersList.php
  src/Repository/CommitteeRepository.php
  src/Repository/VotingPlatform/CandidateGroupRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Repository/VotingPlatform/VoterRepository.php
  templates/committee_manager/_space_layout.html.twig
  templates/designation/_base_referent.html.twig
  templates/designation/_base_supervisor.html.twig
  templates/designation/_candidate.html.twig
  templates/designation/_layout.html.twig
  templates/designation/list.html.twig
  templates/designation/results.html.twig
  templates/designation/show_layout.html.twig
  templates/designation/voters_list.html.twig
  templates/designation/votes_list.html.twig
  templates/referent/_layout.html.twig
  templates/referent/committees_list.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4519 Hide designation tab for committee hosts
  templates/adherent/my_activity_committees.html.twig
  templates/committee_manager/_space_layout.html.twig
Labels: Ready for code review

#4503 [Designation] remove canary mode
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Form/CommitteeMemberFilterType.php
  templates/adherent/my_activity_layout.html.twig
  templates/committee/show.html.twig
  templates/committee_manager/list_members.html.twig
  templates/referent/committees_list.html.twig
  templates/voting_platform/_designation_banner.html.twig
Labels: Ready for code review

#4511 [ReferentSpace] CSS fixes Elu page
  front/style/manager-space/_tables.scss
  templates/elected_representative/list.html.twig
  templates/elected_representative/show.html.twig
Labels: Ready for code review

#4508 Add Block & Refusal justifications
  migrations/Version20200528124038.php
  src/Adherent/Certification/AbstractCertificationRequestModerationCommand.php
  src/Adherent/Certification/CertificationAuthorityManager.php
  src/Adherent/Certification/CertificationManager.php
  src/Adherent/Certification/CertificationPermissions.php
  src/Adherent/Certification/CertificationRequestBlockCommand.php
  src/Adherent/Certification/CertificationRequestRefuseCommand.php
  src/Collection/CertificationRequestCollection.php
  src/Controller/Admin/AdminAdherentCRUDController.php
  src/Controller/Admin/AdminCertificationRequestController.php
  src/Controller/EnMarche/CertificationRequestController.php
  src/DataFixtures/ORM/LoadCertificationData.php
  src/Entity/CertificationRequest.php
  src/Form/Admin/CertificationRequestBlockCommandType.php
  src/Form/Admin/CertificationRequestRefuseCommandType.php
  src/Security/Voter/Admin/AdherentCertifyVoter.php
  src/Security/Voter/Admin/AdherentUncertifyVoter.php
  src/Security/Voter/Admin/CertificationRequestProcessVoter.php
  src/Security/Voter/CertificationVoter.php
  templates/admin/adherent/action_button_certify.html.twig
  templates/admin/adherent/action_button_uncertify.html.twig
  templates/admin/certification_request/action_button_approve.html.twig
  templates/admin/certification_request/action_button_block.html.twig
  templates/admin/certification_request/action_button_refuse.html.twig
  templates/admin/certification_request/block.html.twig
  templates/admin/certification_request/refuse.html.twig
  templates/admin/certification_request/show.html.twig
  templates/certification_request/home.html.twig
  templates/components/_header.html.twig
  tests/Adherent/Certification/CertificationAuthorityManagerTest.php
  tests/Adherent/Certification/CertificationManagerTest.php
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
  tests/Security/Voter/CertificationVoterTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4528 [Referent] allow to display candidates list modal
  Makefile
  front/app.js
  front/components/CandidaciesListWidget.js
  front/pages/committee_candidacies.js
  front/style/layout/_avatar.scss
  front/style/pages/_committee.scss
  front/style/voting-platform/_layout.scss
  src/Controller/Api/CommitteesController.php
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/committee/show.html.twig
  templates/designation/_candidate.html.twig
  templates/referent/committees_list.html.twig
Labels: Ready for code review

#4529 [CityCard] fix result history tab
  src/Twig/ElectionVoteResultRuntime.php
  templates/adherent/my_activity_committees.html.twig
  templates/admin/election/city_card/edit.html.twig
Labels: Ready for code review

#4522 [Deputy] Team access style
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_filters.scss
  templates/my_team/delegate_access.html.twig
  templates/my_team/list.html.twig
  templates/my_team/search_results.html.twig
Labels: Ready for code review

#4534 [CityCard] update results history tab to display all results
  src/Election/ElectionManager.php
  src/Twig/ElectionVoteResultRuntime.php
  templates/admin/election/city_card/edit.html.twig
Labels: Ready for code review

#4488 Feature/senator team
  config/services/services.xml
  features/access_delegation.feature
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_filters.scss
  migrations/Version20200608101418.php
  src/Controller/AccessDelegatorTrait.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedDeputyMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedReferentMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedSenatorMessageController.php
  src/Controller/EnMarche/DelegatedDeputyController.php
  src/Controller/EnMarche/DeputyController.php
  src/Controller/EnMarche/EventManager/DelegatedDeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedSenatorEventManagerController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedDeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedSenatorManagedUsersController.php
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/Controller/EnMarche/MyTeam/DeputyMyTeamController.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/Adherent.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Entity/ReferentTag.php
  src/EntityListener/RevokeDelegatedAccessListener.php
  src/EventSubscriber/DelegatedAccessSubscriber.php
  src/Form/DataTransformer/AdherentToEmailTransformer.php
  src/Form/MyTeam/DelegateAccessType.php
  src/Form/MyTeam/MyTeamSearchAdherentType.php
  src/Intl/FranceCitiesBundle.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/GeoFilterTrait.php
  src/Repository/MyTeam/DelegatedAccessRepository.php
  src/RepublicanSilence/TagExtractor/DistrictReferentTagExtractor.php
  src/Security/Voter/AuthorVoter.php
  src/Security/Voter/DelegatedAccessesVoter.php
  src/Security/Voter/DelegatedTypeVoter.php
  src/Twig/AdherentDelegatedAccessesExtension.php
  templates/adherent/_list_my_sections.html.twig
  templates/components/_nav_desktop.html.twig
  templates/deputy/_layout.html.twig
  templates/event_manager/event_create.html.twig
  templates/event_manager/events_list.html.twig
  templates/message/create.html.twig
  templates/message/filter.html.twig
  templates/message/list.html.twig
  templates/my_team/_base_deputy_space.html.twig
  templates/my_team/delegate_access.html.twig
  templates/my_team/list.html.twig
  templates/my_team/search_results.html.twig
  templates/referent/_form_theme.html.twig
  templates/referent/_layout.html.twig
  templates/senator/_layout.html.twig
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4509 [ElectedRepresentative] Add UserListDefinition managing system
  front/app.js
  front/components/UserListDefinitionWidget.js
  front/listeners/check-with-shift.js
  front/pages/user_list_definition.js
  front/services/api/ReqwestApiClient.js
  front/style/manager-space/_tables.scss
  front/style/mixins/_icons.scss
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Controller/Api/UserListDefinition/AbstractUserListDefinitionController.php
  src/Controller/Api/UserListDefinition/ElectedRepresentativeUserListDefinitionController.php
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/EntityUserListDefinitionTrait.php
  src/Entity/UserListDefinition.php
  src/Exception/UserListDefinitionException.php
  src/Exception/UserListDefinitionMemberException.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/UserListDefinitionRepository.php
  src/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoter.php
  src/Security/Voter/ManageUserListDefinitionsForTypeVoter.php
  src/UserListDefinition/UserListDefinitionManager.php
  src/UserListDefinition/UserListDefinitionPermissions.php
  templates/elected_representative/_datagrid_table.html.twig
  templates/elected_representative/list.html.twig
  templates/managed_users/list.html.twig
  tests/Controller/Api/UserListDefinition/ElectedRepresentativeUserListDefinitionControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoterTest.php
  tests/Security/Voter/ManageUserListDefinitionsForTypeVoterTest.php
  tests/TestHelperTrait.php
  tests/UserListDefinition/UserListDefinitionManagerTest.php
Labels: Ready for code review

#4538 Fix/delegated access feedback
  src/Controller/AccessDelegatorTrait.php
  src/Controller/EnMarche/ManagedUsers/DelegatedDeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedSenatorManagedUsersController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/EventSubscriber/DelegatedAccessSubscriber.php
  src/Security/Voter/AuthorVoter.php
  src/Security/Voter/DelegatedAccessesVoter.php
  src/Security/Voter/DelegatedTypeVoter.php
  templates/adherent/_list_my_sections.html.twig
  templates/deputy/_layout.html.twig
  templates/event_manager/events_list.html.twig
  templates/referent/_layout.html.twig
  templates/senator/_layout.html.twig
Labels: Ready for code review

#4540 Refactor required checkboxes
  src/Form/ApplicationRequest/ApplicationRequestType.php
  src/Form/CertificationRequestType.php
  src/Form/CitizenProjectCommandType.php
  src/Form/EventRegistrationType.php
  src/Form/RequiredCheckboxType.php
Labels: Ready for code review

#4537 Add checkbox to accept certification requests cgu
  src/Form/ApplicationRequest/ApplicationRequestType.php
  src/Form/CertificationRequestType.php
  src/Form/CitizenProjectCommandType.php
  src/Form/EventRegistrationType.php
  src/Form/RequiredCheckboxType.php
  templates/certification_request/form.html.twig
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
Labels: Ready for code review

#4539 Add validation for required non-mapped checkboxes
  src/Form/ApplicationRequest/ApplicationRequestType.php
  src/Form/CertificationRequestType.php
  src/Form/CitizenProjectCommandType.php
  src/Form/DonationRequestType.php
  src/Form/EventRegistrationType.php
  src/Form/RequiredCheckboxType.php
  templates/adherent/create_citizen_project.html.twig
  templates/certification_request/form.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#4543 Change UserListDefinition managing system display
  front/components/UserListDefinitionWidget.js
Labels: Ready for code review

#4544 Add session TTL
  .env
  config/packages/dev/snc_redis.yaml
  config/packages/snc_redis.yaml
Labels: Ready for code review

#4549 Update wording "Idées" menu
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4546 [ElectedRepresentative] CSS ajustements
  features/municipal_chief_space.feature
  front/components/UserListDefinitionWidget.js
  front/style/manager-space/_tables.scss
  templates/elected_representative/list.html.twig
  templates/municipal_chief/_application_request_datagrid.html.twig
  templates/referent/_layout.html.twig
Labels: Ready for code review

#4541 [My Team] Allow senator to delegate their access
  src/Controller/AccessDelegatorTrait.php
  src/Controller/EnMarche/DelegatedInvitationController.php
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/Controller/EnMarche/MyTeam/SenatorMyTeamController.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Form/MyTeam/DelegateAccessType.php
  src/Repository/CommitteeRepository.php
  src/Repository/GeoFilterTrait.php
  templates/components/_nav_desktop.html.twig
  templates/invitation/adherent_space/_layout.html.twig
  templates/managed_users/list.html.twig
  templates/my_team/_base_senator_space.html.twig
  templates/my_team/delegate_access.html.twig
  templates/senator/_layout.html.twig
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
Labels: Ready for code review

#4554 Persist adherent modif before event dispatch call
  front/pages/profile_update.js
  front/services/address/AutocompletedAddressForm.js
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
  src/Membership/MembershipRequestHandler.php
  src/Referent/ReferentTagManager.php
  tests/Referent/ReferentTagManagerTest.php
Labels: Bug, Ready for code review

#4556 [Procu] Add assistance text
  templates/procuration/_faq.html.twig
  templates/procuration/_layout.html.twig
  templates/procuration/landing.html.twig
  templates/procuration/proxy/proposal.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
Labels: Ready for code review

#4555 [My Team] Change predefined roles
  features/access_delegation.feature
  src/Entity/MyTeam/DelegatedAccess.php
Labels: Ready for code review

#4517 Replace a2lix/i18n-doctrine-bundle by knplabs/doctrine-behaviors
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/services/admin.xml
  config/services/services.xml
  migrations/Version20200602175713.php
  src/Admin/Extension/EmptyTranslationRemoverAdminExtension.php
  src/Command/AlgoliaSynchronizeCommand.php
  src/Controller/Admin/AdminTimelineManifestoController.php
  src/Controller/Admin/AdminTimelineMeasureController.php
  src/Controller/Admin/AdminTimelineProfileController.php
  src/Controller/Admin/AdminTimelineThemeController.php
  src/DataFixtures/ORM/LoadTimelineData.php
  src/Entity/AbstractTranslatableEntity.php
  src/Entity/EntityTranslationInterface.php
  src/Entity/Timeline/Manifesto.php
  src/Entity/Timeline/ManifestoTranslation.php
  src/Entity/Timeline/Measure.php
  src/Entity/Timeline/MeasureTranslation.php
  src/Entity/Timeline/Profile.php
  src/Entity/Timeline/ProfileTranslation.php
  src/Entity/Timeline/Theme.php
  src/Entity/Timeline/ThemeTranslation.php
  src/EventListener/ControllerListener.php
  src/Form/EventListener/EmptyTranslationRemoverListener.php
  symfony.lock
  tests/Controller/Admin/AdminChezVousCityControllerTest.php
  tests/Controller/Admin/AdminTimelineMeasureControllerTest.php
  tests/Entity/Timeline/MeasureTest.php
  tests/Entity/TranslatableEntityTest.php
Labels: Ready for code review

#4552 Improve php config
  docker/prod/pool.conf
Labels: Ready for code review

#4551 Remove oneshot scripts
  add_referent_tags_to_elected_representative.sql
  src/Command/CreateReferentTagsForDistrictsCommand.php
  src/Command/CreateUuidsForElectedRepresentativeCommand.php
Labels: Don't merge

#4545 Certification emails
  config/services.yaml
  src/Adherent/Certification/CertificationAuthorityManager.php
  src/Adherent/Certification/CertificationManager.php
  src/Adherent/Certification/CertificationRequestNotifier.php
  src/Form/DonationRequestType.php
  src/Mailer/Message/CertificationRequestApprovedMessage.php
  src/Mailer/Message/CertificationRequestBlockedMessage.php
  src/Mailer/Message/CertificationRequestPendingMessage.php
  src/Mailer/Message/CertificationRequestRefusedMessage.php
  tests/Adherent/Certification/CertificationAuthorityManagerTest.php
  tests/Controller/EnMarche/CertificationRequestControllerTest.php
Labels: Ready for code review

#4550 [ADMIN] Add UserListDefinition admin
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20200610185809.php
  src/Admin/AdministratorAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/UserListDefinitionAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadUserListDefinitionData.php
  src/Entity/UserListDefinition.php
  src/Entity/UserListDefinitionEnum.php
  templates/admin/elected_representative/list_type.html.twig
  templates/admin/user_list_definition/list_type.html.twig
  tests/Controller/Api/UserListDefinition/ElectedRepresentativeUserListDefinitionControllerTest.php
  tests/Security/Voter/ManageUserListDefinitionsForTypeVoterTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4558 [Newsletter] Mise à jour des styles
  front/style/layout/_layout.scss
  front/style/mixins/_vars.scss
  templates/newsletter/subscribed.html.twig
  templates/newsletter/subscription.html.twig
  templates/newsletter/subscription_mail_sent.html.twig
Labels: Ready for code review

#4559 [Certification] translate reason in email
  src/Adherent/Certification/CertificationRequestNotifier.php
  src/Entity/CertificationRequest.php
  templates/admin/certification_request/show.html.twig
  templates/certification_request/home.html.twig
Labels: Ready for code review

#4553 [My Team] Allow to have 2 delegated accesses of same type (eg. deputy)
  config/services/services.xml
  features/admin/adherent.feature
  features/api/adherents.feature
  features/deputy.feature
  migrations/Version20200615093024.php
  src/Controller/AccessDelegatorTrait.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedDeputyMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedReferentMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedSenatorMessageController.php
  src/Controller/EnMarche/DelegatedDeputyController.php
  src/Controller/EnMarche/DelegatedInvitationController.php
  src/Controller/EnMarche/DeputyController.php
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedDeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedSenatorEventManagerController.php
  src/Controller/EnMarche/EventManager/DeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/MunicipalChiefEventManagerController.php
  src/Controller/EnMarche/EventManager/ReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/SenatorEventManagerController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedDeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedSenatorManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/EventSubscriber/DelegatedAccessSubscriber.php
  src/Repository/AdherentRepository.php
  src/Security/Voter/AuthorVoter.php
  src/Security/Voter/DelegatedAccessesVoter.php
  src/Security/Voter/DelegatedTypeVoter.php
  src/Twig/AdherentDelegatedAccessesExtension.php
  templates/adherent/_list_my_sections.html.twig
  templates/components/_nav_desktop.html.twig
  templates/deputy/_layout.html.twig
  templates/event_manager/event_create.html.twig
  templates/event_manager/events_list.html.twig
  templates/managed_users/list.html.twig
  templates/message/create.html.twig
  templates/message/filter.html.twig
  templates/message/list.html.twig
  templates/my_team/list.html.twig
  templates/referent/_layout.html.twig
  templates/senator/_layout.html.twig
  tests/BoardMember/BoardMemberManagerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#4557 [VotingPlatform] add round and candidate pool entities
  .php_cs.dist
  features/admin/adherent.feature
  features/api/adherents.feature
  features/api/committees.feature
  front/style/voting-platform/_layout.scss
  migrations/Version20200612142737.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Command/VotingPlatformConfigureCommand.php
  src/Controller/EnMarche/Designation/AbstractDesignationController.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/CandidateGroup.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionPool.php
  src/Entity/VotingPlatform/ElectionRound.php
  src/Entity/VotingPlatform/Vote.php
  src/Entity/VotingPlatform/VoteChoice.php
  src/Entity/VotingPlatform/VoteResult.php
  src/Form/VotingPlatform/CommitteeAdherentCandidatesType.php
  src/Form/VotingPlatform/VoteCandidateType.php
  src/Form/VotingPlatform/VoteChoiceType.php
  src/Form/VotingPlatform/VotePoolCollectionType.php
  src/Repository/VotingPlatform/CandidateGroupRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Repository/VotingPlatform/VoteResultRepository.php
  src/Security/Voter/VotingPlatformAccessVoter.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Election/ElectionStatusEnum.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Election/VoteCommand/CommitteeAdherentVoteCommand.php
  src/VotingPlatform/Election/VoteCommand/VoteCommand.php
  src/VotingPlatform/Election/VoteCommandStorage.php
  src/VotingPlatform/VoteResult/VoteResultAggregator.php
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
  templates/voting_platform/vote.html.twig
  templates/voting_platform/vote_step.html.twig
  templates/voting_platform/vote_step/committee_adherent.html.twig
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#4562 [Event] validate event name length
  src/Entity/BaseEvent.php
  src/Form/BaseEventCommandType.php
Labels: Bug, Ready for code review

#4560 [My Team] Front changes and access deletion
  features/access_delegation.feature
  front/style/layout/_select2.scss
  front/style/manager-space/_base-layout.scss
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/Entity/Adherent.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Form/MyTeam/DelegateAccessType.php
  src/Twig/AdherentRuntime.php
  templates/my_team/delegate_access.html.twig
  templates/my_team/list.html.twig
  templates/my_team/search_results.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4564 ElectedRepresentative admin
  migrations/Version20200619181519.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeLabelAdmin.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/ElectedRepresentativeLabel.php
  src/Entity/ElectedRepresentative/LabelNameEnum.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  templates/admin/elected_representative/edit.html.twig
  templates/admin/elected_representative/list_zones.html.twig
  templates/admin/elected_representative/show_is_adherent.html.twig
Labels: Ready for code review

#4566 [ElectedList] Remove canary mode
  src/Controller/EnMarche/ReferentController.php
  templates/referent/_layout.html.twig
Labels: Ready for code review

#4565 Remove certification canary
  src/Controller/EnMarche/CertificationRequestController.php
  templates/adherent/_profile_menu.html.twig
Labels: Ready for code review

#4518 Voting platform finish command
  migrations/Version20200617113000.php
  src/Command/VotingPlatformCloseElectionCommand.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionRound.php
  src/Repository/VotingPlatform/ElectionRepository.php
  templates/adherent/overview.html.twig
  templates/voting_platform/vote.html.twig
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
Labels: Ready for code review

#4563 Delegated/small fixes
  migrations/Version20200618163910.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Controller/EnMarche/AdherentMessage/DelegatedCommonMessageController.php
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/Adherent.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Form/MyTeam/DelegateAccessType.php
  src/Repository/AdherentRepository.php
  src/Twig/AdherentDelegatedAccessesExtension.php
  src/Twig/AdherentRuntime.php
  templates/adherent/_list_my_sections.html.twig
  templates/admin/adherent/list_status.html.twig
  templates/deputy/_layout.html.twig
  templates/managed_users/list.html.twig
  templates/message/filter/_adherent_zone_filter.html.twig
  templates/message/list.html.twig
  templates/message/preview.html.twig
  templates/my_team/delegate_access.html.twig
  templates/my_team/search_results.html.twig
  templates/senator/_layout.html.twig
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4567 [ElectedCRM] add code column to Zone entity
  Makefile
  migrations/Version20200623103937.php
  src/Entity/ElectedRepresentative/Zone.php
Labels: Ready for code review

#4570 Fix user can be a string
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#4572 Improve command services config
  config/services.yaml
  config/services/command.yaml
  config/services/http_client.yaml
  src/Command/NotifyIdeaAuthorAboutContributionsCommand.php
  src/Command/NotifyIdeaAuthorCommand.php
  src/Command/SendAdhesionReportCommand.php
  src/Repository/CommitteeRepository.php
  src/Repository/GeoFilterTrait.php
  templates/elected_representative/list.html.twig
Labels: Ready for code review

#4573 [Certification] prevent certification without birthdate
  src/Security/Voter/CertificationVoter.php
  templates/certification_request/home.html.twig
  tests/Security/Voter/CertificationVoterTest.php
Labels: Bug, Ready for code review

#4568 ElectedRepresentative list
  migrations/Version20200623204535.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/ValueObject/Genders.php
  templates/admin/elected_representative/list_type.html.twig
  templates/elected_representative/list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
  translations/messages.fr.yml
Labels: Work in progress

#4571 [VotingPlatform] implement adherent lock period after vote
  config/packages/framework.yaml
  config/services.yaml
  config/services/voting_platform.yaml
  migrations/Version20200623224423.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Security/Voter/Committee/ChangeCommitteeVoteVoter.php
  src/VotingPlatform/Election/Listener/LockPeriodClearCacheListener.php
  src/VotingPlatform/Listener/SendCandidacyEmailsListener.php
  src/VotingPlatform/Security/LockPeriodManager.php
Labels: Ready for code review

#4576 Make ElectedRepresentative gender nullable in admin
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
Labels: Ready for code review

#4574 Keep track of UserListDefinitions movements
  migrations/Version20200624175233.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/ElectedRepresentative/UserListDefinitionHistoryManager.php
  src/Entity/ElectedRepresentative/Reporting/UserListDefinitionHistory.php
  src/UserListDefinition/UserListDefinitionManager.php
  templates/admin/elected_representative/list_type.html.twig
  tests/UserListDefinition/UserListDefinitionManagerTest.php
Labels: Ready for code review

#4579 Update wording on "Mes activités"
  templates/adherent/my_activity_committees.html.twig
  templates/elected_representative/list.html.twig
Labels: Ready for code review

#4580 [Referent] Fix lazy loaded entities
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/AdherentRepository.php
  src/Repository/EventRepository.php
  src/Repository/ReferentRepository.php
  src/Security/Voter/ReferentPersonLinkVoter.php
Labels: Ready for code review

#4582 [ElectionBox] add countdown clocks
  front/app.js
  front/services/utils/countdownClock.js
  front/style/app.scss
  front/style/layout/_countdown_clock.scss
  src/Entity/EntityDesignationTrait.php
  templates/committee/_election_box.html.twig
  templates/committee/show.html.twig
Labels: Ready for code review

#4577 Dimitri/ch11530 committee part
  front/style/pages/_adherent-activities.scss
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionRound.php
  src/Entity/VotingPlatform/Vote.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Security/Voter/Committee/ChangeCommitteeVoteVoter.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Security/LockPeriodManager.php
  templates/adherent/my_activity_committees.html.twig
Labels: Ready for code review

#4583 Change url from "espace-delegue" to "espace-partage"
  src/Controller/EnMarche/AdherentMessage/DelegatedDeputyMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedReferentMessageController.php
  src/Controller/EnMarche/AdherentMessage/DelegatedSenatorMessageController.php
  src/Controller/EnMarche/CitizenProjects/DelegatedReferentCitizenProjectsController.php
  src/Controller/EnMarche/Committee/DelegatedReferentCommitteeController.php
  src/Controller/EnMarche/DelegatedDeputyController.php
  src/Controller/EnMarche/DelegatedInvitationController.php
  src/Controller/EnMarche/Designation/DelegatedReferentDesignationController.php
  src/Controller/EnMarche/ElectedRepresentative/DelegatedReferentElectedRepresentativeController.php
  src/Controller/EnMarche/EventManager/DelegatedDeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/DelegatedSenatorEventManagerController.php
  src/Controller/EnMarche/Jecoute/DelegatedJecouteReferentController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedDeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DelegatedSenatorManagedUsersController.php
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
Labels: Ready for code review

#4587 Update SF from 3.4.41 to 3.4.42
  composer.lock
Labels: Ready for code review
