Repository parti-renaissance/espace-adherent, pull requests merged in 2020-05, with the labels that each got.

#4439 Add ondelete cascad for application requests
  migrations/Version20200502224418.php
  src/Entity/ApplicationRequest/ApplicationRequest.php
Labels: Bug, Ready for code review

#4442 [Committee] Wording and CSS fixes
  front/style/layout/_avatar.scss
  front/style/pages/_committee.scss
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/CommitteeElection.php
  src/VotingPlatform/Designation/ElectionStaticDate.php
  templates/committee/_election_box.html.twig
  templates/committee/edit_candidacy.html.twig
Labels: Ready for code review

#4443 Fix Candidacy upload image behavior
  front/components/CandidaciesListWidget.js
  front/components/Modal.js
  front/services/utils/imageCropper.js
  front/style/pages/_committee.scss
  src/Controller/Api/CommitteesController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/CommitteeCandidacy.php
  src/Form/VotingPlatform/CandidateProfileType.php
  src/Image/ImageManager.php
  templates/committee/edit_candidacy.html.twig
Labels: Ready for code review

#4397 [CP-App] remove duplicated styles
  front/style/app.scss
  front/style/pages/_citizen-project-app-react.scss
  web/apps/projets-citoyens/src/App.js
  web/apps/projets-citoyens/src/App.scss
  web/apps/projets-citoyens/src/style/base/_general.scss
  web/apps/projets-citoyens/src/style/components/_cookie-banner.scss
  web/apps/projets-citoyens/src/style/components/_footer.scss
  web/apps/projets-citoyens/src/style/components/_header.scss
  web/apps/projets-citoyens/src/style/components/_nav.scss
  web/apps/projets-citoyens/src/style/components/_pagination.scss
  web/apps/projets-citoyens/src/style/components/_select.scss
  web/apps/projets-citoyens/src/style/components/_summary.scss
  web/apps/projets-citoyens/src/style/containers/citizen-project/_citizen-project-search.scss
  web/apps/projets-citoyens/src/style/content/_header.scss
  web/apps/projets-citoyens/src/style/content/_inside-common.scss
  web/apps/projets-citoyens/src/style/content/_inside-html.scss
  web/apps/projets-citoyens/src/style/content/_movement.scss
  web/apps/projets-citoyens/src/style/content/_program.scss
  web/apps/projets-citoyens/src/style/content/_read-more.scss
  web/apps/projets-citoyens/src/style/layout/_banners.scss
  web/apps/projets-citoyens/src/style/layout/_base.scss
  web/apps/projets-citoyens/src/style/layout/_buttons.scss
  web/apps/projets-citoyens/src/style/layout/_cards.scss
  web/apps/projets-citoyens/src/style/layout/_carousel.scss
  web/apps/projets-citoyens/src/style/layout/_datagrid.scss
  web/apps/projets-citoyens/src/style/layout/_footer.scss
  web/apps/projets-citoyens/src/style/layout/_forms.scss
  web/apps/projets-citoyens/src/style/layout/_hero.scss
  web/apps/projets-citoyens/src/style/layout/_layout.scss
  web/apps/projets-citoyens/src/style/layout/_loader.scss
  web/apps/projets-citoyens/src/style/layout/_nav.scss
  web/apps/projets-citoyens/src/style/layout/_search.scss
  web/apps/projets-citoyens/src/style/layout/_spaces.scss
  web/apps/projets-citoyens/src/style/layout/_utilities.scss
  web/apps/projets-citoyens/src/style/layout/_vendors.scss
  web/apps/projets-citoyens/src/style/mixins/_colors.scss
  web/apps/projets-citoyens/src/style/mixins/_font-awesome.scss
  web/apps/projets-citoyens/src/style/mixins/_fonts.scss
  web/apps/projets-citoyens/src/style/mixins/_icons.scss
  web/apps/projets-citoyens/src/style/mixins/_positioning.scss
  web/apps/projets-citoyens/src/style/mixins/_spinner.scss
  web/apps/projets-citoyens/src/style/mixins/_text.scss
  web/apps/projets-citoyens/src/style/mixins/_vars.scss
  web/apps/projets-citoyens/src/style/vars/_colors.scss
Labels: Ready for code review

#4432 [NEWSLETTER] Email confirmation for newsletter
  config/services/services.xml
  migrations/Version20200429105408.php
  src/Controller/EnMarche/NewsletterController.php
  src/DataFixtures/ORM/LoadNewsletterSubscriptionData.php
  src/Entity/NewsletterSubscription.php
  src/Event/EventListener/EventRegistrationNewsletterSubscriber.php
  src/Form/NewsletterSubscriptionType.php
  src/Mailer/Message/NewsletterAdherentSubscriptionMessage.php
  src/Mailer/Message/NewsletterSubscriptionConfirmationMessage.php
  src/Mailer/Message/NewsletterSubscriptionMessage.php
  src/Newsletter/Events.php
  src/Newsletter/Listener/MailchimpSyncSubscriber.php
  src/Newsletter/Listener/SendWelcomeMailSubscriber.php
  src/Newsletter/NewsletterEvent.php
  src/Newsletter/NewsletterSubscriptionHandler.php
  src/Repository/AdherentRepository.php
  src/Repository/NewsletterSubscriptionRepository.php
  templates/home/index.html.twig
  templates/jemarche/index.html.twig
  templates/newsletter/subscribed.html.twig
  templates/newsletter/subscription_mail_sent.html.twig
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Controller/EnMarche/NewsletterControllerTest.php
Labels: Ready for code review

#4447 [Committee] Update wording on Election box
  features/committee_vote.feature
  front/style/pages/_committee.scss
  src/Controller/EnMarche/CommitteeController.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  src/VotingPlatform/Designation/ElectionStaticDate.php
  templates/committee/_election_box.html.twig
Labels: Ready for code review

#4446 Dimitri/ch11442/ajouter un petit à côté de conseil territorial
  front/components/Modal.js
  front/services/utils/imageCropper.js
  front/style/app.scss
  front/style/content/_em-tooltip.scss
  templates/committee/_election_box.html.twig
Labels: Ready for code review

#4445 [ELECTED REPRESENTATIVE] Add referent tag to elected representative zone
  add_referent_tags_to_elected_representative.sql
  migrations/Version20200504123507.php
  src/Entity/ElectedRepresentative/Zone.php
Labels: Ready for code review

#4449 Remove candidate button for AL
  templates/committee/_election_box.html.twig
Labels: Bug, Ready for code review

#4444 [VotePlatform] Integration
  front/style/layout/_avatar.scss
  front/style/layout/_layout.scss
  front/style/voting-platform/_layout.scss
  templates/voting_platform/_helper.html.twig
  templates/voting_platform/_layout.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/vote_step/_candidate_row.html.twig
  templates/voting_platform/vote_step/committee_adherent.html.twig
Labels: Work in progress

#4454 Remove unused macaddress JS package
  package.json
  yarn.lock
Labels: Ready for code review

#4455 Improve geocodable listener by checking address hash
  migrations/Version20200508235826.php
  src/Entity/EntityNullablePostAddressTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/NullablePostAddress.php
  src/Entity/PostAddress.php
  src/Geocoder/GeoPointInterface.php
  src/Geocoder/Subscriber/EntityAddressGeocodingSubscriber.php
Labels: Ready for code review

#4456 [Designation] Update wording
  features/committee_vote.feature
  front/components/VoteCommitteeWidget.js
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/committee/edit_candidacy.html.twig
Labels: Ready for code review

#4430 Voting platform
  config/packages/workflows.yaml
  config/services/controller.yaml
  config/services/services.xml
  config/services/voting_platform.yaml
  front/style/app.scss
  front/style/layout/_avatar.scss
  front/style/layout/_buttons.scss
  front/style/layout/_layout.scss
  front/style/voting-platform/_layout.scss
  front/style/voting-platform/index.scss
  migrations/Version20200504113033.php
  migrations/Version20200507151000.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/VotingPlatform/VotingPlatformController.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/VotingPlatform/Candidate.php
  src/Entity/VotingPlatform/CandidateGroup.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionEntity.php
  src/Entity/VotingPlatform/Vote.php
  src/Entity/VotingPlatform/VoteChoice.php
  src/Entity/VotingPlatform/VoteResult.php
  src/Entity/VotingPlatform/Voter.php
  src/Entity/VotingPlatform/VotersList.php
  src/Form/VotingPlatform/CandidacyBiographyType.php
  src/Form/VotingPlatform/CommitteeAdherentCandidatesType.php
  src/Form/VotingPlatform/VoteCandidateType.php
  src/Form/VotingPlatform/VoteChoiceType.php
  src/Repository/VotingPlatform/CandidateGroupRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Repository/VotingPlatform/VoterRepository.php
  src/Repository/VotingPlatform/VotersListRepository.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Election/Listener/GuardListener.php
  src/VotingPlatform/Election/Listener/ManageVoteCommandStoreListener.php
  src/VotingPlatform/Election/RedirectManager.php
  src/VotingPlatform/Election/VoteCommand/CommitteeAdherentVoteCommand.php
  src/VotingPlatform/Election/VoteCommand/VoteCommand.php
  src/VotingPlatform/Election/VoteCommandProcessor.php
  src/VotingPlatform/Election/VoteCommandStateEnum.php
  src/VotingPlatform/Election/VoteCommandStorage.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_committee_adherent.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/vote_step.html.twig
  templates/voting_platform/vote_step/_candiates_list.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  templates/voting_platform/vote_step/committee_adherent.html.twig
  web/images/vote-platform-ornaments/ornament-1.png
  web/images/vote-platform-ornaments/ornament-2.png
  web/images/vote-platform-ornaments/ornament-3.png
Labels: Ready for code review

#4459 [VotePlatform] Integration 3
  front/style/voting-platform/_layout.scss
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
Labels: Ready for code review

#4463 [Wording] Our organization's page
  templates/page/le-mouvement/notre-organisation.html.twig
Labels: Ready for code review

#4464 [Wording] Certification page
  templates/certification_request/home.html.twig
Labels: Ready for code review

#4465 [Committee] Hotfixes wording & style
  features/committee_vote.feature
  front/components/VoteCommitteeWidget.js
  front/style/content/_em-tooltip.scss
  src/Controller/EnMarche/CommitteeController.php
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
Labels: Ready for code review

#4466 [CommitteeCandidacy] fix image cropper field name
  front/services/utils/imageCropper.js
Labels: Bug, Ready for code review

#4461 [VotingPlatform] add configuring scripts
  Makefile
  config/services/services.xml
  features/api/committees.feature
  migrations/Version20200511124432.php
  src/Command/VotingPlatformConfigureCommand.php
  src/Command/VotingPlatformInitializeCommitteeElectionCommand.php
  src/Committee/CommitteeFactory.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/Committee.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/CommitteeElection.php
  src/Entity/CommitteeMembership.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionEntity.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeElectionRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Api/CommitteesControllerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
Labels: Ready for code review

#4448 role filter new style on adherent form
  config/services/services.xml
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/managed_users/filter_form.html.twig
  templates/managed_users/list.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4468 [ElectedRepresentative] Gender-neutral names for mandates and political functions + remove `no_name` political function
  migrations/Version20200512123804.php
  src/Entity/ElectedRepresentative/MandateTypeEnum.php
  src/Entity/ElectedRepresentative/PoliticalFunctionNameEnum.php
Labels: Ready for code review

#4469 [ADMIN] Add ElectedRepresentative role
  config/packages/security.yaml
  src/Admin/AdministratorAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
Labels: Ready for code review

#4462 Add null results for non subscribed filter
  src/Repository/CommitteeMembershipRepository.php
Labels: Ready for code review

#4472 [Config] Improve twig service config
  config/services/twig.xml
  config/services/twig.yaml
  src/Twig/AdminReportRuntime.php
  src/Twig/AssetRuntime.php
  src/Twig/CitizenActionRuntime.php
  src/Twig/CitizenProjectRuntime.php
  src/Twig/CommitteeRuntime.php
  src/Twig/EventRuntime.php
  src/Twig/FormRuntime.php
  src/Twig/IdeasWorkshopRuntime.php
  src/Twig/MarkdownRuntime.php
  src/Twig/MunicipalSiteRuntime.php
  src/Twig/ReportRuntime.php
Labels: Ready for code review

#4473 [Referent] Stylise edit member form
  config/services/services.xml
  front/style/manager-space/_forms.scss
  src/Form/CommitteeUuidType.php
  src/Form/ReferentPersonLinkType.php
  templates/javascript.js.twig
  templates/referent/_form_theme.html.twig
  templates/referent/edit_referent_person_link.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4475 [Referent] Add subsection to form
  front/style/manager-space/_forms.scss
  templates/referent/edit_referent_person_link.html.twig
Labels: Ready for code review

#4474 Access to voting platform
  features/committee_vote.feature
  front/components/CandidaciesListWidget.js
  front/style/voting-platform/_layout.scss
  src/Command/VotingPlatformInitializeCommitteeElectionCommand.php
  src/Controller/EnMarche/CommitteeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/Committee.php
  src/Entity/CommitteeElection.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Election.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Security/Voter/VotingPlatformAccessVoter.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Designation/ElectionStaticDate.php
  src/VotingPlatform/Election/Listener/GuardListener.php
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/committee/edit_candidacy.html.twig
  templates/committee/show.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/finish.html.twig
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
Labels: Ready for code review

#4477 [Admin] fix donator page and check phone number
  templates/admin/donator/edit.html.twig
Labels: Bug, Ready for code review

#4460 [REFERENT] Add ElectedRepresentative list
  add_referent_tags_to_elected_representative.sql
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadElectedRepresentativesRegisterData.php
  src/DataFixtures/ORM/LoadElectionCityCardData.php
  src/DataFixtures/ORM/LoadZoneCategoryData.php
  src/DataFixtures/ORM/LoadZoneData.php
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/ElectedRepresentativeLabel.php
  src/Entity/ElectedRepresentative/SocialNetworkLink.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  templates/elected_representative/list.html.twig
  templates/referent/_layout.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4481 [VotingPlatform] add results page
  config/packages/security.yaml
  config/routes.yaml
  front/style/voting-platform/_results.scss
  front/style/voting-platform/index.scss
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/EnMarche/VotingPlatform/AbstractController.php
  src/Controller/EnMarche/VotingPlatform/ConfirmController.php
  src/Controller/EnMarche/VotingPlatform/FinishController.php
  src/Controller/EnMarche/VotingPlatform/IndexController.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/Controller/EnMarche/VotingPlatform/VotingPlatformController.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/Vote.php
  src/Entity/VotingPlatform/VoteResult.php
  src/Repository/VotingPlatform/CandidateGroupRepository.php
  src/Repository/VotingPlatform/VoteRepository.php
  src/Repository/VotingPlatform/VoteResultRepository.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Collection/CandidateGroupsCollection.php
  src/VotingPlatform/Election/RedirectManager.php
  templates/committee/_election_box.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_macros.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candiates_list.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/results/_stats_block.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
  templates/voting_platform/vote_step.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
Labels: Ready for code review

#4483 [Candidacy] fix update photo
  .circleci/config.yml
  front/components/CandidaciesListWidget.js
  migrations/Version20200515153555.php
  src/Committee/CommitteeManager.php
  src/Controller/EnMarche/CommitteeController.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/ImageTrait.php
  src/Form/VotingPlatform/CandidacyBiographyType.php
  src/Storage/ImageStorage.php
  src/VotingPlatform/Event/UpdateCommitteeCandidacyEvent.php
  src/VotingPlatform/Events.php
  src/VotingPlatform/Listener/UpdateCandidacyProfilePhotoListener.php
  tests/Controller/Api/CommitteesControllerTest.php
Labels: Bug, Ready for code review

#4479 [REFERENT] Get all ElectedRepresentatives for Paris tag
  features/api/adherents.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadReferentTagData.php
  src/DataFixtures/ORM/LoadZoneData.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4470 Remove ElectedRepresentativesRegister related classes, but not entity
  config/packages/security.yaml
  config/services/admin.xml
  elected_representative_migration.sql
  src/Admin/AdministratorAdmin.php
  src/Admin/ElectedRepresentativesRegisterAdmin.php
  src/Command/ImportElectedRepresentativesRegisterCommand.php
  src/Command/RestructureElectedRepresentativesRegisterCommand.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadElectedRepresentativesRegisterData.php
  src/Entity/ElectedRepresentativesRegister.php
  src/Repository/ElectedRepresentativesRegisterRepository.php
  templates/admin/elected_representatives_register/field_adherent.html.twig
Labels: Ready for code review

#4480 [REFERENT] Add ElectedRepresentative show page
  front/style/manager-space/_tables.scss
  migrations/Version20200512163952.php
  src/Controller/EnMarche/ReferentController.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  templates/elected_representative/list.html.twig
  templates/elected_representative/show.html.twig
  templates/referent/_layout.html.twig
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4487 [ElectedRepresentative] Add a command to create ElectedRepresentative uuid
  migrations/Version20200512163952.php
  src/Command/CreateUuidsForElectedRepresentativeCommand.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#4489 [hotfix] Avoid to have negatif member count on basegroup
  src/Entity/BaseGroup.php
Labels: Bug, Ready for code review

#4484 [VotingPlatform] Integration results part. 1
  front/style/app.scss
  front/style/layout/_tabs.scss
  front/style/mixins/_text.scss
  front/style/voting-platform/_layout.scss
  front/style/voting-platform/_results.scss
  templates/voting_platform/_macros.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candiates_list.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/results/_stats_block.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
  templates/voting_platform/vote_step.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
Labels: Ready for code review

#4492 [ReferentTeam] fix team member creation
  src/Entity/ReferentOrganizationalChart/ReferentPersonLink.php
  src/Entity/ReferentTeamMember.php
  src/EventListener/ManageReferentTeamMembersListener.php
Labels: Bug, Ready for code review

#4485 [VotingPlatform] Update stats on results page
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/VoteChoice.php
  src/Entity/VotingPlatform/VoteResult.php
  src/Form/ReferentPersonLinkType.php
  src/Form/VotingPlatform/CandidacyBiographyType.php
  src/Repository/VotingPlatform/VoteResultRepository.php
  src/Repository/VotingPlatform/VoterRepository.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/VoteResult/VoteResultAggregator.php
  templates/voting_platform/results/_candiates_list.html.twig
  templates/voting_platform/results/_stats_block.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
Labels: Ready for code review

#4493 Fix RestrictedCommittees setter by checking null value
  src/Entity/ReferentOrganizationalChart/ReferentPersonLink.php
Labels: Bug, Ready for code review

#4490 [VotingPlatform] Integration part. 3
  front/style/voting-platform/_layout.scss
  front/style/voting-platform/_results.scss
  migrations/Version20200522171542.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/CandidateGroup.php
  templates/voting_platform/_layout_committee_adherent.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/results/committee_adherent.html.twig
Labels: Ready for code review

#4482 [ElectedRepresentative][ADMIN] Add UserListDefinition and its filter
  config/services/admin.xml
  migrations/Version20200518173215.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/UserListDefinitionAdmin.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadUserListDefinitionData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/EntityUserListDefinitionTrait.php
  src/Entity/UserListDefinition.php
  src/Entity/UserListDefinitionEnum.php
  templates/admin/elected_representative/edit.html.twig
  templates/admin/elected_representative/list_is_adherent.html.twig
  templates/admin/elected_representative/list_type.html.twig
Labels: Ready for code review

#4496 [CI] clear oldest docker images
  scripts/build.sh
Labels: Ready for code review

#4502 Crm dons v1.7
  src/Adherent/AdherentExtractCommand.php
  src/Adherent/AdherentExtractCommandHandler.php
  src/Admin/DonationAdmin.php
  src/Controller/EnMarche/UserController.php
  src/Donation/DonationManager.php
  src/Donation/DonationValueObject.php
  src/Donation/DonatorExtractCommand.php
  src/Donation/DonatorExtractCommandHandler.php
  src/Entity/Donation.php
  src/Extract/AbstractEmailExtractCommandHandler.php
  src/Repository/DonationRepository.php
  templates/admin/donator/extract/extract_button.html.twig
  templates/user/my_donation.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4491 [ElectedRepresentative][ADMIN] Add a zone filter
  config/services/admin.xml
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Admin/ElectedRepresentative/ZoneAdmin.php
Labels: Ready for code review

#4507 [ElectedRepresentative][ADMIN] Show all in UserListDefinition filter
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
Labels: Ready for code review
