Repository parti-renaissance/espace-adherent, pull requests merged in 2020-09, with the labels that each got.

#4751 [Adherent Space] Hotfixes (documents, avatar,..)
  front/style/layout/_cards.scss
  front/style/pages/_adherent-profile.scss
  front/style/pages/_documents.scss
  src/Twig/AdherentRuntime.php
  templates/adherent_profile/_funnel_layout.html.twig
  templates/adherent_profile/_layout.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/documents/directory.html.twig
  templates/documents/index.html.twig
Labels: Ready for code review

#4752 Add plural names of Terrirotial council membership qualities
  templates/territorial_council/candidacy_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4755 [REFERENT] Add TerritorialCouncil members filter list
  src/Controller/EnMarche/TerritorialCouncil/ReferentTerritorialCouncilController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Form/TerritorialCouncil/MemberFilterType.php
  src/Repository/CommitteeRepository.php
  src/Repository/ElectedRepresentative/ZoneRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/TerritorialCouncil/Filter/MembersListFilter.php
  templates/referent/territorial_council/members.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/ReferentTerritorialCouncilControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4747 [TerritorialCouncil][CoPol][Admin] Add mayor and leader membership
  src/Controller/Admin/AdminTerritorialCouncilController.php
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/PoliticalCommitteeMembership.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Repository/ElectedRepresentative/MandateRepository.php
  src/Repository/TerritorialCouncil/PoliticalCommitteeMembershipRepository.php
  src/TerritorialCouncil/Exception/PoliticalCommitteeMembershipException.php
  src/TerritorialCouncil/PoliticalCommitteeManager.php
  templates/admin/territorial_council/list_actions.html.twig
  tests/Controller/Admin/AdminTerritorialCouncilControllerTest.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
Labels: Ready for code review

#4759 [REFERENT] Add TerritorialCouncil members export
  src/Controller/EnMarche/TerritorialCouncil/ReferentTerritorialCouncilController.php
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Exporter/TerritorialCouncilMembersExporter.php
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
  templates/referent/territorial_council/members.html.twig
Labels: Ready for code review

#4763 [Committee] Add designed adherents on committee page
  front/style/pages/_committee.scss
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/Entity/Committee.php
  templates/committee/_sidebar.html.twig
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Ready for code review

#4760 [Admin] Add role to change adherent mandates in committee
  config/packages/security.yaml
  src/Admin/AdministratorAdmin.php
  src/Controller/Admin/AdminCommitteeController.php
  src/DataFixtures/ORM/LoadAdminData.php
  templates/admin/committee/members.html.twig
Labels: Ready for code review

#4765 [Admin][Committee] Add designed adherents on committee list page
  src/Entity/Committee.php
  templates/admin/committee/list_hosts.html.twig
Labels: Ready for code review

#4764 Fix review of new profil design
  front/style/layout/_utilities.scss
  front/style/pages/_listing.scss
  src/Entity/AdherentCommitmentEnum.php
  src/Form/AdherentCommitmentType.php
  src/Form/AdherentProfileType.php
  templates/adherent/profile.html.twig
  templates/adherent_profile/activity/_citizen_projects.html.twig
  templates/adherent_profile/activity/_pagination.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4622 [Election] add result entities
  config/services_dev.yaml
  features/api/adherents.feature
  front/style/mixins/_colors.scss
  migrations/Version20200714020357.php
  src/Command/VotingPlatformCloseElectionCommand.php
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  src/Controller/EnMarche/VotingPlatform/AbstractController.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilElectionData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionResult/CandidateGroupResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionRoundResult.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Repository/VotingPlatform/VoteResultRepository.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Election/ResultCalculator.php
  src/VotingPlatform/VoteResult/VoteResultAggregator.php
  templates/committee/_election_box.html.twig
  templates/committee_designation/results.html.twig
  templates/committee_designation/voters_list.html.twig
  templates/committee_designation/votes_list.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_copol.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candiates_list.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/results/_stats_block.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4768 [Admin] Change ElectedRepresentative info on Adherent edit page
  src/Admin/AdherentAdmin.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4766 Add district role list to adherents
  config/packages/security.yaml
Labels: Ready for code review

#4770 [VotingPlatform] fix return back button
  src/Controller/EnMarche/VotingPlatform/ConfirmController.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  src/VotingPlatform/Election/VoteCommand/VoteCommand.php
  templates/voting_platform/confirmation.html.twig
Labels: Ready for code review

#4769 Voting platform fix styles
  front/style/voting-platform/_candidacy.scss
  front/style/voting-platform/_layout.scss
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  templates/territorial_council/candidacy_list.html.twig
  templates/voting_platform/_layout_copol.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/vote.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
Labels: Ready for code review

#4778 Voting platform fix styles #2
  front/style/voting-platform/_layout.scss
  front/style/voting-platform/_results.scss
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
Labels: Ready for code review

#4777 [Admin] TerritorialCouncilMembershipLog add resolve action button
  config/packages/security.yaml
  src/Admin/AdministratorAdmin.php
  src/Controller/Admin/AdminTerritorialCouncilController.php
  src/Controller/Admin/AdminTerritorialCouncilMembershipLogController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipLogData.php
  templates/admin/territorial_council/membership_log_list_actions.html.twig
  tests/Controller/Admin/AdminTerritorialCouncilMembershipLogControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4781 [Committee] Add order of designed adherents on committee page
  src/Entity/Committee.php
Labels: Ready for code review

#4714 Send membership email reminder
  migrations/Version20200819100824.php
  src/Command/RemindActivatedMembershipCommand.php
  src/Entity/Adherent.php
  src/Mailer/Message/AdherentMembershipReminderMessage.php
  src/Membership/MembershipRequestHandler.php
Labels: Ready for code review

#4785 [VotingPlatform] fix aggregation process and take all rounds
  src/Entity/VotingPlatform/Election.php
  src/VotingPlatform/Election/ResultCalculator.php
Labels: Ready for code review

#4787 [Admin][TerritorialCouncil] Add Political committee members on Territorial council admin pages
  config/services/admin.xml
  src/Admin/TerritorialCouncil/TerritorialCouncilAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipAdmin.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  templates/admin/territorial_council/list_membership_political_committee_qualities.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4791 [AdherentProfile] Fix documents accordion height
  front/style/pages/_documents.scss
Labels: Ready for code review

#4792 [TerritorialCouncil] Add election poll result on Territorial council page
  front/style/pages/_territorial-council.scss
  public/images/icons/icn-choosen.svg
  src/DataFixtures/ORM/LoadTerritorialCouncilElectionData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilElectionPollData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/TerritorialCouncil/ElectionPoll/Poll.php
  src/Entity/TerritorialCouncil/ElectionPoll/PollChoice.php
  src/Entity/TerritorialCouncil/ElectionPoll/Vote.php
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/partials/_election_poll.html.twig
Labels: Needs design

#4793 Dimitri/ch12213/gérer le statut désignés supplémentaires
  front/style/pages/_territorial-council.scss
  migrations/Version20200908154509.php
  public/images/icons/icn-chosen.svg
  src/Command/VotingPlatformConfigureCommand.php
  src/Controller/Api/CommitteesController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/TerritorialCouncil/ElectionPoll/Poll.php
  src/Entity/TerritorialCouncil/ElectionPoll/PollChoice.php
  src/Entity/VotingPlatform/Candidate.php
  src/Entity/VotingPlatform/CandidateGroup.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionPool.php
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionRoundResult.php
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
  src/Repository/VotingPlatform/CandidateGroupRepository.php
  src/Twig/CommitteeRuntime.php
  src/VotingPlatform/Collection/CandidateGroupsCollection.php
  src/VotingPlatform/Listener/AttributeAdditionalElectedPlacesListener.php
  templates/referent/territorial_council/members.html.twig
  templates/territorial_council/partials/_election_poll.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
Labels: Ready for code review

#4800 [TerritorialCouncil] Change election poll result
  templates/territorial_council/partials/_election_poll.html.twig
Labels: Ready for code review

#4801 Update donations import command
  migrations/Version20200909153859.php
  src/Command/ImportDonationsCommand.php
  src/Entity/Donation.php
Labels: Ready for code review

#4805 [FrontChat] remove inactive chat (FrontApp) and catch JS errors
  templates/bot/_javascript.html.twig
Labels: Ready for code review

#4806 [Donator] fix typo
  src/Admin/DonatorAdmin.php
  src/Command/DonatorSynchronizeCommand.php
  src/Donation/DonationRequestHandler.php
  src/Donation/DonatorManager.php
Labels: Ready for code review

#4808 [Spaces] Fix designation table scroll (container)
  templates/committee_designation/list.html.twig
  templates/territorial_council_designation/list.html.twig
Labels: Ready for code review

#4811 [Designation] fix clone clone methode
  src/Entity/VotingPlatform/Designation/Designation.php
  src/TerritorialCouncil/Designation/UpdateDesignationHandler.php
  templates/form_theme_admin.html.twig
Labels: Bug, Ready for code review

#4813 [Referent] message instances - filter by territorial council
  migrations/Version20200911103327.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Sender/TransactionalSender.php
  src/AdherentMessage/TransactionalMessage/MessageModifier/ReferentTerritorialCouncilModifier.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/ReferentTerritorialCouncilMessageController.php
  src/Entity/AdherentMessage/Filter/ReferentTerritorialCouncilFilter.php
  src/Form/AbstractConnectedUserFormType.php
  src/Form/AdherentMessage/ReferentTerritorialCouncilFilterType.php
  src/Form/ManagedTerritorialCouncilChoiceType.php
  src/Form/MyReferentTagChoiceType.php
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/TerritorialCouncil/Filter/MembersListFilter.php
  templates/message/filter/referent_territorial_council.html.twig
Labels: Ready for code review

#4810 [Committee] Display designed adherents in election box
  front/style/voting-platform/_candidacy.scss
  front/style/voting-platform/_results.scss
  src/DataFixtures/ORM/LoadElectionData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/ElectionPool.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Twig/VotingPlatformRuntime.php
  templates/committee/_election_box.html.twig
Labels: Needs design, Ready for code review

#4803 [TerritorialCouncil][CoPol] Change Political committee memberships management
  src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Repository/AdherentMandate/TerritorialCouncilAdherentMandateRepository.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilElectedCandidateAdherentHandler.php
  src/TerritorialCouncil/PoliticalCommitteeManager.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
Labels: Ready for code review

#4815 [TerritorialCouncil] Add qualities management for borough council
  src/Repository/ElectedRepresentative/MandateRepository.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilCityCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDepartmentCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDepartmentalCouncilPresidentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDeputyHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilEuropeanDeputyHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilMayorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilRegionalCouncilPresidentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilRegionalCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilSenatorHandler.php
Labels: Ready for code review

#4814 [AdherentMessage] cast to array recipients var
  src/AdherentMessage/Sender/CampaignSender.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
Labels: Bug, Ready for code review

#4802 Add thematic community entities
  migrations/Version20200911155434.php
  src/Entity/EntityNullablePostAddressTrait.php
  src/Entity/ThematicCommunity/AdherentMembership.php
  src/Entity/ThematicCommunity/Contact.php
  src/Entity/ThematicCommunity/ContactMembership.php
  src/Entity/ThematicCommunity/ElectedRepresentativeMembership.php
  src/Entity/ThematicCommunity/ThematicCommunity.php
  src/Entity/ThematicCommunity/ThematicCommunityMembership.php
Labels: Ready for code review

#4816 [VotingPlatform] add cascade deletion for election result
  migrations/Version20200914095246.php
  src/Entity/VotingPlatform/ElectionResult/ElectionResult.php
Labels: Ready for code review

#4667 Activity/instances
  templates/adherent_profile/activity.html.twig
  templates/adherent_profile/activity/_instances.html.twig
  templates/components/_nav_desktop.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#4817 [TerritorialCouncil] Change display conditions of the election info and election poll
  src/Entity/EntityDesignationTrait.php
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/partials/_election_poll.html.twig
Labels: Ready for code review

#4818 [VotingPlatform] remove title field from ElectionPool and use code in…
  migrations/Version20200914170156.php
  src/Command/VotingPlatformConfigureCommand.php
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/ElectionPool.php
  src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
  src/Entity/VotingPlatform/ElectionPoolTitleEnum.php
  src/Twig/VotingPlatformExtension.php
  templates/committee_designation/votes_list.html.twig
  templates/voting_platform/_layout_committee_adherent.html.twig
  templates/voting_platform/_layout_copol.html.twig
  templates/voting_platform/confirmation.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4820 [Donation] Fix flip on firefox
  front/style/pages/_donation.scss
Labels: Ready for code review

#4819 Dimitri/ch12226/créer des mandats après les élections
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
  src/Entity/VotingPlatform/Candidate.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Repository/AdherentMandate/TerritorialCouncilAdherentMandateRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/VotingPlatform/Command/UpdateMandateForElectedAdherentCommand.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Election/Listener/GuardListener.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
  src/VotingPlatform/Listener/NotifierListener.php
  src/VotingPlatform/Listener/UpdateAdherentMandateListener.php
  src/VotingPlatform/Notifier/Event/CommitteeElectionSecondRoundNotificationEvent.php
  src/VotingPlatform/Notifier/Event/CommitteeElectionVoteIsOpenEvent.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
Labels: Ready for code review

#4822 [CoPol] Rename leader quality
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  translations/messages.fr.yml
Labels: Ready for code review

#4730 [Space] Rework navigation
  front/style/app.scss
  front/style/layout/_em-dropdown.scss
  front/style/layout/_layout.scss
  front/style/layout/_nav.scss
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_tables.scss
  public/images/icons/icn-form-switch.svg
  public/images/icons/icons.svg
  templates/adherent_space/_layout.html.twig
  templates/assessor_attribution/index.html.twig
  templates/base.html.twig
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/_space_layout.html.twig
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/managed_users/list.html.twig
  templates/message/_base_referent.html.twig
  templates/referent/_layout.html.twig
  templates/referent/_sidebar.html.twig
  templates/referent/territorial_council/members.html.twig
  tests/Controller/EnMarche/AdherentMessage/ReferentMessageControllerTest.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
Labels: Ready for code review

#4827 [AdherentSpace] Various hotfixes
  front/style/layout/_cards.scss
  templates/adherent/profile.html.twig
  templates/adherent_profile/activity/_citizen_projects.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/adherent_profile/activity/_events.html.twig
  templates/adherent_profile/activity/_instances.html.twig
  templates/adherent_profile/funnel/general.html.twig
Labels: Ready for code review

#4829 Fix length constraint on event name
  src/Entity/BaseEvent.php
Labels: Ready for code review

#4830 [TerritorialCouncil][CoPol] Rename adding to Political committee membership action + fix
  templates/admin/territorial_council/list_membership_actions.html.twig
Labels: Ready for code review

#4824 [Admin] use app admin layout instead of Sonata
  templates/admin/adherent/extract/request.html.twig
  templates/admin/adherent/unregistration_export.html.twig
  templates/admin/citizen_project/members.html.twig
  templates/admin/committee/members.html.twig
  templates/admin/donator/extract/request.html.twig
  templates/admin/donator/merge/confirm.html.twig
  templates/admin/donator/merge/request.html.twig
  templates/admin/elected_representative/adherent_similar_profiles.html.twig
  templates/admin/ideas_workshop/idea/idea_contributors.html.twig
  templates/admin/interactive/invitation_export.html.twig
Labels: Ready for code review

#4828 Changes candidacy and convocation text display
  src/Form/DataTransformer/DoubleNewlineTextTransformer.php
  src/Form/DoubleNewlineTextareaType.php
  src/Form/TerritorialCouncil/EditDesignationType.php
  src/Form/VotingPlatform/Candidacy/BaseCandidacyBiographyType.php
  src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council_designation/convocation.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
Labels: Ready for code review

#4833 [Deps] update lullabot/amp (sabberworm/php-css-parser [CVE-2020-13756])
  composer.lock
  symfony.lock
Labels: Ready for code review

#4826 Dimitri/ch12224/afficher les détails des désignations dans
  front/style/pages/_territorial-council.scss
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Entity/EntityDesignationTrait.php
  src/Repository/TerritorialCouncil/CandidacyRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Twig/TerritorialCouncilExtension.php
  src/Twig/TerritorialCouncilRuntime.php
  src/VotingPlatform/Designation/DesignationStatusEnum.php
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/faq.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/territorial_council/partials/_election_poll.html.twig
  templates/territorial_council/partials/_nav.html.twig
  templates/territorial_council/partials/_sidebar.html.twig
  templates/territorial_council_designation/list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4834 [TerritorialCouncil] improve adherent selection on membership cron co…
  src/Command/UpdateTerritorialCouncilMembershipsCommand.php
Labels: Ready for code review

#4836 Change adherent mandates
  src/Entity/Committee.php
  templates/committee/_sidebar.html.twig
  templates/committee_manager/list_members.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4835 New page layout with header image
  features/sitemap.feature
  front/style/app.scss
  front/style/pages/static/_default-with-header.scss
  migrations/Version20200918121201.php
  src/Admin/PageAdmin.php
  src/Content/PageFactory.php
  src/DataFixtures/ORM/LoadPageData.php
  src/Entity/Page.php
  templates/page/layout/default_with_header_image.html.twig
  translations/messages.fr.yml
Labels: Work in progress

#4837 Page subdomain
  .env
  config/routes.yaml
  config/services.yaml
  docker-compose.override.yml.dist
  features/sitemap.feature
  src/DataFixtures/ORM/LoadPageData.php
Labels: Ready for code review

#4838 Add micro ckeditor to apply on convocation page
  config/packages/exercise_html_purifier.yaml
  config/services.yaml
  config/services/services.xml
  src/Form/TerritorialCouncil/EditDesignationType.php
  templates/javascript.js.twig
  templates/territorial_council_designation/convocation.html.twig
Labels: Ready for code review

#4832 [Spaces] Apply new nav
  front/style/manager-space/_base-layout.scss
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/_sidebar.html.twig
  templates/committee_manager/_space_layout.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/deputy/_layout.html.twig
  templates/deputy/_sidebar.html.twig
  templates/jecoute/_manager_space_layout.html.twig
  templates/jecoute/_sidebar.html.twig
  templates/jecoute/surveys_list.html.twig
  templates/legislative_candidate/_layout.html.twig
  templates/legislative_candidate/_sidebar.html.twig
  templates/lre/_layout.html.twig
  templates/lre/_sidebar.html.twig
  templates/referent/_sidebar.html.twig
  templates/senator/_layout.html.twig
  templates/senator/_sidebar.html.twig
  tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
  tests/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeControllerTest.php
Labels: Ready for code review

#4841 [Referent] fix convoc page styles
  front/style/pages/_referent_space.scss
  templates/territorial_council/partials/_election_poll.html.twig
Labels: Ready for code review

#4842 [CoTerr] fix - add security check for territorial council page
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Repository/VotingPlatform/ElectionRepository.php
  templates/referent/_sidebar.html.twig
  templates/referent/territorial_council/_instances_nav.html.twig
  templates/referent/territorial_council/members.html.twig
  templates/territorial_council_designation/_layout.html.twig
  templates/territorial_council_designation/list.html.twig
Labels: Bug, Ready for code review

#4823 [Thematic community] Handle thematic community in admin
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20200918105807.php
  src/Admin/AdministratorAdmin.php
  src/Admin/ThematicCommunity/ThematicCommunityAdmin.php
  src/Admin/ThematicCommunity/ThematicCommunityMembershipAdmin.php
  src/DataFixtures/ORM/LoadThematicCommunityContactData.php
  src/DataFixtures/ORM/LoadThematicCommunityData.php
  src/DataFixtures/ORM/LoadThematicCommunityMembershipData.php
  src/Entity/ThematicCommunity/AdherentMembership.php
  src/Entity/ThematicCommunity/Contact.php
  src/Entity/ThematicCommunity/ContactMembership.php
  src/Entity/ThematicCommunity/ElectedRepresentativeMembership.php
  src/Entity/ThematicCommunity/ThematicCommunity.php
  src/Entity/ThematicCommunity/ThematicCommunityMembership.php
  src/Entity/ThematicCommunity/ThematicCommunityToUserListDefinitionEnum.php
  src/Entity/UserListDefinitionEnum.php
  templates/admin/thematic_community/member/categories.html.twig
  templates/admin/thematic_community/member/community.html.twig
  templates/admin/thematic_community/member/edit.html.twig
  templates/admin/thematic_community/member/qualifications.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4840 Add 'Membre des instances' and 'Adhérent désigné' roles to profile info
  src/Entity/Adherent.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Twig/AdherentRuntime.php
Labels: Ready for code review

#4845 [Thematic Communities] Set chief from adherent admin
  migrations/Version20200917163301.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  templates/admin/adherent/statuses.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4844 [Spaces] Update REC and Coord.
  templates/coordinator/_citizen_project_list.html.twig
  templates/coordinator/_layout.html.twig
  templates/coordinator/citizen_project.html.twig
  templates/coordinator/committees.html.twig
  tests/Controller/EnMarche/CoordinatorControllerTest.php
Labels: Ready for code review

#4846 [TerritorialCouncil] minor fixes and wording
  src/Entity/EntityDesignationTrait.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  templates/territorial_council/partials/_election_poll.html.twig
  templates/territorial_council/partials/_nav.html.twig
  templates/territorial_council_designation/list.html.twig
  templates/voting_platform/results/_candidate_box.html.twig
Labels: Ready for code review

#4849 Update sf/http-client to 4.4 (CVE-2020-15094)
  composer.json
  composer.lock
Labels: Ready for code review

#4854 Index Election candidacy
  config/packages/algolia_search.yaml
  config/services.yaml
  migrations/Version20200924112904.php
  src/Entity/Algolia/AlgoliaCandidature.php
  src/Entity/AuthoredTrait.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/Event.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/EntityListener/AlgoliaIndexListener.php
  src/EntityListener/EventIndexedListener.php
  src/Normalizer/Indexer/AbstractDesignationCandidatureNormalizer.php
  src/Normalizer/Indexer/CommitteeCandidatureNormalizer.php
  src/Normalizer/Indexer/TerritorialCouncilCandidatureNormalizer.php
  tests/Committee/CommitteeManagerTest.php
Labels: Ready for code review

#4847 [TerritorialCouncil][CoPol] Add referent messages page
  front/services/api/ReqwestApiClient.js
  front/style/pages/_territorial-council.scss
  migrations/Version20200921110741.php
  src/Adherent/Unregistration/Handlers/RemovePoliticalCommitteeItemHandler.php
  src/Adherent/Unregistration/Handlers/RemoveTerritorialCouncilItemHandler.php
  src/Collection/TerritorialCouncilMembershipCollection.php
  src/Committee/CommitteeContactMembersCommand.php
  src/Committee/Feed/CommitteeMessage.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/FeedItemControllerTrait.php
  src/Controller/EnMarche/TerritorialCouncil/PoliticalCommitteeController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/DataFixtures/ORM/LoadPoliticalCommitteeFeedItemData.php
  src/DataFixtures/ORM/LoadPoliticalCommitteeMembershipData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilFeedItemData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/AbstractFeedItem.php
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/PoliticalCommitteeFeedItem.php
  src/Entity/TerritorialCouncil/TerritorialCouncilFeedItem.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/UserDocument.php
  src/FeedItem/FeedItemPermissions.php
  src/FeedItem/FeedItemTypeEnum.php
  src/Form/FeedItemType.php
  src/Repository/TerritorialCouncil/PoliticalCommitteeFeedItemRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilFeedItemRepository.php
  src/Security/Voter/FileUploadVoter.php
  src/Security/Voter/TerritorialCouncil/ManagePoliticalCommitteeFeedItemVoter.php
  src/Security/Voter/TerritorialCouncil/ManageTerritorialCouncilFeedItemVoter.php
  templates/adherent/contact.html.twig
  templates/adherent_profile/activity/_instances.html.twig
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/edit_feed_item.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/members.html.twig
  templates/territorial_council/messages.html.twig
  templates/territorial_council/partials/_feed.html.twig
  templates/territorial_council/partials/_feed_items.html.twig
  templates/territorial_council/partials/_nav.html.twig
  templates/territorial_council/political_committee/_layout.html.twig
  templates/territorial_council/political_committee/index.html.twig
  templates/territorial_council/political_committee/messages.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/PoliticalCommitteeControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
  tests/Security/Voter/FileUploadVoterTest.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#4855 Update flysysteme service
  composer.json
  composer.lock
  config/services/admin.xml
  config/services/cms.xml
  config/services/community.xml
  config/services/platform.xml
  config/services/services.xml
  config/services/system.xml
  config/services_dev.yaml
  src/Adherent/Certification/CertificationRequestDocumentManager.php
  src/Admin/ApplicationRequest/RunningMateRequestAdmin.php
  src/Admin/DonationAdmin.php
  src/Admin/Extension/ImageUploadExtension.php
  src/Admin/MediaAdmin.php
  src/Admin/MediaSynchronisedAdminTrait.php
  src/ApplicationRequest/ApplicationRequestHandler.php
  src/CitizenProject/CitizenProjectManager.php
  src/Command/ChezVous/AbstractImportCommand.php
  src/Command/ChezVous/ImportMarkersCommand.php
  src/Command/ChezVous/ImportMeasuresCommand.php
  src/Command/ChezVous/ImportZipCodesCommand.php
  src/Command/ImportReferentBioPictureCommand.php
  src/Command/ImportReferentNominationCommand.php
  src/Command/ImportTerritorialCouncilFromCSVCommand.php
  src/Command/MailchimpDeleteContactsFromCsvCommand.php
  src/Command/MailchimpSignUpEmailsCommand.php
  src/Command/TimelineImportCommand.php
  src/Committee/PhotoManager.php
  src/Controller/Admin/AdminCertificationRequestController.php
  src/Controller/Admin/AdminDonationController.php
  src/Controller/AssetsController.php
  src/Controller/EnMarche/FacebookController.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadCitizenProjectData.php
  src/DataFixtures/ORM/LoadClarificationData.php
  src/DataFixtures/ORM/LoadCustomSearchData.php
  src/DataFixtures/ORM/LoadFormationData.php
  src/DataFixtures/ORM/LoadHomeBlockData.php
  src/DataFixtures/ORM/LoadOrderArticleData.php
  src/DataFixtures/ORM/LoadPageData.php
  src/DataFixtures/ORM/LoadProposalData.php
  src/DataFixtures/ORM/LoadSocialShareData.php
  src/Documents/DocumentRepository.php
  src/EntityListener/FileListener.php
  src/Facebook/PictureUploader.php
  src/Form/SummaryType.php
  src/Storage/ImageStorage.php
  src/Summary/SummaryManager.php
  src/Timeline/TimelineFactory.php
  src/TurnkeyProject/TurnkeyProjectManager.php
  src/UserDocument/UserDocumentManager.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#4852 [Thematic communities] Add space in front
  src/AdherentCharter/AdherentCharterFactory.php
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/Admin/AdherentAdmin.php
  src/Collection/AdherentCharterCollection.php
  src/Collection/UserListDefinitionCollection.php
  src/Controller/EnMarche/ThematicCommunity/ThematicCommunitiesChiefMembersController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/AdherentCharter/ThematicCommunityChiefCharter.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Entity/ThematicCommunity/AdherentMembership.php
  src/Entity/ThematicCommunity/ContactMembership.php
  src/Entity/ThematicCommunity/ThematicCommunityMembership.php
  src/Entity/UserListDefinitionEnum.php
  src/Form/ThematicCommunityMembershipFilterType.php
  src/Repository/ThematicCommunity/ThematicCommunityMembershipRepository.php
  src/Subscription/SubscriptionTypeEnum.php
  src/ThematicCommunity/ThematicCommunityMembershipFilter.php
  src/Twig/DateExtension.php
  src/Twig/DateRuntime.php
  symfony.lock
  templates/adherent/_list_my_sections.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/components/_email_icon.svg.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_sms_icon.svg.twig
  templates/thematic_community/_layout.html.twig
  templates/thematic_community/_sidebar.html.twig
  templates/thematic_community/filter_form.html.twig
  templates/thematic_community/members.html.twig
  tests/Controller/EnMarche/ThematicCommunity/ThematicCommunitiesChiefMembersControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4857 [CoPol] Fix adding qualities
  src/DataFixtures/ORM/LoadTerritorialCouncilAdherentMandateData.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/PoliticalCommitteeManager.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4860 [CoPol][TerritorialCouncil] Add additionally elected
  migrations/Version20200928143320.php
  src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
  src/Entity/TerritorialCouncil/PoliticalCommitteeMembership.php
  src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
  src/TerritorialCouncil/PoliticalCommitteeManager.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
Labels: Ready for code review

#4862 [Unregistration] Add roles that cannot unregister
  src/Entity/Adherent.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Repository/AdherentMandate/AdherentMandateRepository.php
  src/Security/Voter/MembershipVoter.php
  templates/user/my_account.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Entity/AdherentTest.php
  tests/Security/Voter/MembershipVoterTest.php
Labels: Ready for code review

#4859 [Admin] Display candidacy dashboard
  config/packages/sonata_admin.yaml
  config/packages/sonata_doctrine_orm_admin.yaml
  config/services.yaml
  config/services/admin.xml
  config/settings/algolia_search/designation_candidate-settings.json
  config/settings/algolia_search/event-settings.json
  src/Admin/AbstractAlgoliaAdmin.php
  src/Admin/Designation/CandidateAdmin.php
  src/Admin/DonatorAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilAdmin.php
  src/Algolia/AlgoliaIndexedEntityManager.php
  src/Algolia/Query/Expr/AbstractExpr.php
  src/Algolia/Query/Expr/Add.php
  src/Algolia/Query/Expr/AndWhere.php
  src/Algolia/Query/Expr/Eq.php
  src/Algolia/Query/Expr/Expr.php
  src/Algolia/Query/Expr/ExprInterface.php
  src/Algolia/Query/Expr/In.php
  src/Algolia/Query/Expr/Like.php
  src/Algolia/Query/Expr/OrX.php
  src/Algolia/Query/QueryBuilder.php
  src/Algolia/Query/Result.php
  src/Algolia/SearchService.php
  src/Algolia/Sonata/Builder/DatagridBuilder.php
  src/Algolia/Sonata/Model/FieldDescription.php
  src/Algolia/Sonata/Model/ModelManager.php
  src/Algolia/Sonata/Pager/Pager.php
  src/Algolia/Sonata/ProxyQuery/ProxyQuery.php
  src/Entity/Algolia/AlgoliaCandidature.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Form/Admin/DonatorKinshipType.php
  src/Normalizer/Indexer/AbstractDesignationCandidatureNormalizer.php
  src/Normalizer/Indexer/CommitteeCandidatureNormalizer.php
  src/Normalizer/Indexer/TerritorialCouncilCandidatureNormalizer.php
  src/Procuration/ProcurationProxyMessageFactory.php
  templates/admin/CRUD/list_trans.html.twig
  templates/admin/instances/candidate_list_binomes_column.html.twig
  templates/admin/instances/candidate_list_entity_column.html.twig
  templates/admin/instances/candidate_list_identity_column.html.twig
  templates/admin/instances/candidate_list_presentation_column.html.twig
  templates/admin/instances/candidate_list_votes_column.html.twig
  templates/admin/layout.html.twig
  tests/Test/Algolia/DummySearchService.php
  translations/messages.fr.yml
Labels: Ready for code review

#4863 Change Territorial council limite date
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignationValidator.php
Labels: Ready for code review

#4861 Export national survey data
  features/api/surveys.feature
  features/referent_space.feature
  features/surveys.feature
  src/Admin/JecouteLocalSurveyAdmin.php
  src/Admin/JecouteNationalSurveyAdmin.php
  src/Controller/Admin/AdminJecouteController.php
  src/DataFixtures/ORM/LoadJecouteDataAnswerData.php
  src/DataFixtures/ORM/LoadJecouteDataSurveyData.php
  src/DataFixtures/ORM/LoadJecouteQuestionData.php
  src/DataFixtures/ORM/LoadJecouteSurveyData.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Exporter/SurveyExporter.php
  src/Repository/Jecoute/DataSurveyRepository.php
  templates/admin/jecoute/_exports.html.twig
Labels: Ready for code review

#4865 Export survey data in front
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  templates/jecoute/stats.html.twig
Labels: Ready for code review

#4867 Fix html counter validator on designation form
  src/TerritorialCouncil/Designation/UpdateDesignationRequest.php
Labels: Ready for code review
