Repository parti-renaissance/espace-adherent, pull requests merged in 2020-08, with the labels that each got.

#4646 Allow to filter by lre labels on LRE space + change social network column to phone
  src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  templates/elected_representative/list.html.twig
  templates/lre/_layout.html.twig
Labels: Ready for code review

#4647 Remove my team tab to senatorial candidates and better filter in BO
  src/Controller/EnMarche/MyTeam/SenatorialCandidateMyTeamController.php
  src/Entity/Adherent.php
  src/Form/Admin/SenatorialCandidateManagedAreaType.php
  templates/admin/adherent/list_status.html.twig
  templates/my_team/_base_senatorial_candidate_space.html.twig
  templates/senatorial_candidate/_layout.html.twig
Labels: Ready for code review

#4651 [VotingPlatform] Add adherent relation to candidate
  migrations/Version20200803141312.php
  src/Command/VotingPlatformConfigureCommand.php
  src/Entity/VotingPlatform/Candidate.php
  templates/admin/elected_representative/edit.html.twig
Labels: Ready for code review

#4609 Create ElectedRepresentative message for Referents
  config/services.yaml
  config/services/services.xml
  migrations/Version20200803182201.php
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/AbstractMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentElectedRepresentativeMailchimpCampaignHandler.php
  src/Command/MailchimpInitElectedRepresentativeSegmentsCommand.php
  src/Command/MailchimpSyncAllElectedRepresentativesCommand.php
  src/Command/MailchimpUpdateSegmentsFromListCommand.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/ReferentElectedRepresentativeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AbstractElectedRepresentativeFilter.php
  src/Entity/AdherentMessage/Filter/ReferentElectedRepresentativeFilter.php
  src/Entity/AdherentMessage/MailchimpCampaign.php
  src/Entity/AdherentMessage/ReferentElectedRepresentativeMessage.php
  src/Entity/MailchimpSegment.php
  src/Entity/UserListDefinitionEnum.php
  src/Form/AdherentMessage/ElectedRepresentativeFilterType.php
  src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
  src/Mailchimp/Campaign/ContentSection/ElectedRepresentativeMessageSectionBuilder.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToElectedRepresentativeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Mailchimp/Synchronisation/ElectedRepresentativeTagsBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/MailchimpSegmentRepository.php
  templates/form_theme.html.twig
  templates/message/_base_referent.html.twig
  templates/message/_base_referent_elected_representative.html.twig
  templates/message/filter/referent_elected_representative.html.twig
  templates/referent/_layout.html.twig
Labels: Ready for code review

#4612 Store & synchronize mailchimp segments
  config/services.yaml
  config/services/services.xml
  migrations/Version20200710134404.php
  migrations/Version20200803182201.php
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/AbstractMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentElectedRepresentativeMailchimpCampaignHandler.php
  src/Command/MailchimpInitElectedRepresentativeSegmentsCommand.php
  src/Command/MailchimpSyncAllElectedRepresentativesCommand.php
  src/Command/MailchimpUpdateSegmentsFromListCommand.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/ReferentElectedRepresentativeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AbstractElectedRepresentativeFilter.php
  src/Entity/AdherentMessage/Filter/ReferentElectedRepresentativeFilter.php
  src/Entity/AdherentMessage/MailchimpCampaign.php
  src/Entity/AdherentMessage/ReferentElectedRepresentativeMessage.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/MailchimpSegment.php
  src/Entity/UserListDefinitionEnum.php
  src/Form/AdherentMessage/ElectedRepresentativeFilterType.php
  src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
  src/Mailchimp/Campaign/ContentSection/ElectedRepresentativeMessageSectionBuilder.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToElectedRepresentativeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Mailchimp/Synchronisation/ElectedRepresentativeTagsBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/MailchimpSegmentRepository.php
  templates/form_theme.html.twig
  templates/message/_base_referent.html.twig
  templates/message/_base_referent_elected_representative.html.twig
  templates/message/filter/referent_elected_representative.html.twig
  templates/referent/_layout.html.twig
Labels: Ready for code review

#4653 [Referent] improve elected representative filter page
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentElectedRepresentativeMailchimpCampaignHandler.php
  src/Controller/EnMarche/AccessDelegatorTrait.php
  src/Entity/AdherentMessage/Filter/ReferentElectedRepresentativeFilter.php
  src/Entity/AdherentMessage/MailchimpCampaign.php
  src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoter.php
  templates/message/filter/referent_elected_representative.html.twig
Labels: Ready for code review

#4657 Fix display lre labels only in LRE space
  src/Collection/UserListDefinitionCollection.php
  src/Entity/EntityUserListDefinitionTrait.php
  templates/elected_representative/list.html.twig
Labels: Ready for code review

#4655 [TerritorialCouncil] Add COPOL designation type and council election
  migrations/Version20200805111724.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Command/VotingPlatformInitializeElectionsCommand.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/Committee.php
  src/Entity/CommitteeElection.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/TerritorialCouncil/Election.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/VotingPlatform/Designation/AbstractElectionEntity.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Designation/ElectionEntityInterface.php
  src/Entity/VotingPlatform/Designation/EntityElectionHelperTrait.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/admin/designation/list_zone.html.twig
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4652 Add TerritorialCouncilMembership management in admin + command
  config/services/services.xml
  migrations/Version20200804182635.php
  src/Admin/AdherentAdmin.php
  src/Command/AddTerritorialCouncilMembershipCommand.php
  src/Command/ImportTerritorialCouncilFromCSVCommand.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQuality.php
  src/Form/EventListener/TerritorialCouncilMembershipListener.php
  src/Repository/AdherentRepository.php
  src/Repository/TerritorialCouncilRepository.php
  src/Validator/TerritorialCouncil/UniqueTerritorialCouncilMember.php
  src/Validator/TerritorialCouncil/UniqueTerritorialCouncilMemberValidator.php
  templates/form_theme_admin.html.twig
  tests/Validator/TerritorialCouncil/UniqueTerritorialCouncilMemberValidatorTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#4656 Territorial council page
  front/style/app.scss
  front/style/layout/_avatar.scss
  front/style/mixins/_colors.scss
  front/style/pages/_territorial-council.scss
  src/Collection/TerritorialCouncilMembershipCollection.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQuality.php
  templates/adherent/contact.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_nav.html.twig
  templates/territorial_council/_sidebar.html.twig
  templates/territorial_council/index.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
  translations/messages.fr.yml
Labels: Needs design, Ready for code review

#4662 Fix add membership (referent + LRE) command
  src/Command/AddTerritorialCouncilMembershipCommand.php
Labels: Ready for code review

#4663 [LRE] Allow to disable zone restriction and see all elected represent…
  migrations/Version20200806155443.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/LreArea.php
  src/Form/Admin/LreAreaType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  templates/lre/_layout.html.twig
  tests/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#4668 [LRE] fix elected list for LRE with all zones
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoter.php
Labels: Bug, Ready for code review

#4671 [PHP] increase memory limit
  docker/dev/php.ini
Labels: Ready for code review

#4661 [TerritorialCouncil] improve admin membership assignation
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Form/Admin/AdherentTerritorialCouncilMembershipType.php
  src/Form/Admin/TerritorialCouncilChoiceType.php
  src/Form/DataTransformer/AdminTerritorialCouncilAdherentMembershipDataTransformer.php
  src/Form/EventListener/TerritorialCouncilMembershipListener.php
  src/Validator/TerritorialCouncil/UniqueTerritorialCouncilMemberValidator.php
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#4665 [TerritorialCouncil] Add TerritorialCouncil membership management command
  config/services.yaml
  src/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandler.php
  src/Command/UpdateTerritorialCouncilMembershipsCommand.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Repository/ElectedRepresentative/MandateRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/TerritorialCouncil/Command/AdherentUpdateTerritorialCouncilMembershipsCommand.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilCityCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilCommitteeSupervisorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilConsularCounselorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDepartmentCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDepartmentalCouncilPresidentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilDeputyHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilElectedCandidateAdherentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilEmptyMembershipHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilEuropeanDeputyHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilMayorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilMembershipHandlerInterface.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilRegionalCouncilPresidentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilRegionalCouncilorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilSenatorHandler.php
Labels: Work in progress

#4673 Fix title of confirm modal
  front/listeners/confirm-modal.js
  templates/adherent/my_activity_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/territorial_council/_election_box.html.twig
Labels: Ready for code review

#4672 [TerritorialCouncil] Candidacy: validate invited membership
  front/style/pages/_territorial-council.scss
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/TerritorialCouncil/CandidacyInvitation.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitation.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitationValidator.php
  templates/territorial_council/candidacy_step2_invitation.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#4675 [TerritorialCouncil] Add membership for elected candidate adherents
  config/services.yaml
  src/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandler.php
  src/Repository/CommitteeRepository.php
  src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilCommitteeSupervisorHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilElectedCandidateAdherentHandler.php
Labels: Ready for code review

#4676 [TerritorialCouncil] Candidacy: add invitation list page with accept/…
  front/style/pages/_committee.scss
  front/style/voting-platform/_candidacy.scss
  migrations/Version20200810225900.php
  src/Admin/AdherentAdmin.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilData.php
  src/Entity/ImageTrait.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/TerritorialCouncil/CandidacyInvitation.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Repository/TerritorialCouncil/CandidacyInvitationRepository.php
  src/TerritorialCouncil/CandidacyManager.php
  templates/form_theme.html.twig
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_member_identity_box.html.twig
  templates/territorial_council/_sidebar.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/candidacy_step3_confirmation.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/invitation_list.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4678 [TerritorialCouncil] Hide foreign co terr
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4680 [TerritorialCouncil] Candidacy: make photo required
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
Labels: Ready for code review

#4679 Messages subnav style
  templates/message/_base_referent.html.twig
  templates/message/list.html.twig
Labels: Ready for code review

#4681 [TerritorialCouncil] Fix update membership command : change membership + if has candidacy
  src/Command/UpdateTerritorialCouncilMembershipsCommand.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
Labels: Ready for code review

#4685 [TerritorialCouncil] Candidacy: fix photo validation
  src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
  templates/territorial_council/_election_box.html.twig
Labels: Bug, Ready for code review

#4688 [TerritorialCouncil] Add some tests
  config/services.yaml
  config/services_test.yaml
  src/Admin/ExecutiveOfficeMemberAdmin.php
  src/Admin/IdeasWorkshopThemeAdmin.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
  src/Image/ImageManager.php
  src/Image/ImageManagerInterface.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitation.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitationValidator.php
  src/VotingPlatform/Listener/UpdateCandidacyProfilePhotoListener.php
  templates/territorial_council/candidacy_step1_edit.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
  tests/Image/DummyImageManager.php
  translations/validators.fr.yml
Labels: Ready for code review

#4691 [TerritorialCouncil] Candidacy: improve candidacy voter
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/TerritorialCouncil/CandidacyInvitation.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/Form/TerritorialCouncil/CandidacyQualityType.php
  src/Security/Voter/TerritorialCouncil/AccessVoter.php
  src/Security/Voter/TerritorialCouncil/CandidatureVoter.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitationValidator.php
  templates/form_theme.html.twig
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/_sidebar.html.twig
  templates/territorial_council/index.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#4687 [TerritorialCouncil] Styles ajustments
  front/style/layout/_avatar.scss
  front/style/pages/_territorial-council.scss
  front/style/voting-platform/_candidacy.scss
  public/images/icons/election-box/icn_confirmed.svg
  public/images/icons/election-box/icn_on-waiting.svg
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/_member_identity_box.html.twig
  templates/territorial_council/_sidebar.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/candidacy_step2_invitation.html.twig
  templates/territorial_council/candidacy_step3_confirmation.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/invitation_list.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4692 [TerritorialCouncil] Add candidacy list tab
  composer.json
  composer.lock
  front/style/pages/_territorial-council.scss
  front/style/voting-platform/_candidacy.scss
  front/style/voting-platform/_layout.scss
  migrations/Version20200812144550.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Repository/TerritorialCouncil/CandidacyRepository.php
  templates/admin/committee/merge/_layout.html.twig
  templates/admin/committee/merge/confirm.html.twig
  templates/admin/committee/merge/request.html.twig
  templates/admin/committee/merge/revert.html.twig
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/_macros.html.twig
  templates/territorial_council/_nav.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/invitation_list.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#4694 [TerritorialCouncil] many fixes
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Security/Voter/TerritorialCouncil/CandidatureVoter.php
  src/TerritorialCouncil/CandidacyManager.php
  templates/form_theme.html.twig
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_sidebar.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/index.html.twig
Labels: Ready for code review

#4683 Disable/enable assessor & municipal space with env var
  .env
  config/packages/twig.yaml
  config/services/controller.yaml
  src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
  src/Controller/EnMarche/AssessorSpace/AbstractAssessorSpaceController.php
  templates/municipal_chief/_layout.html.twig
  templates/municipal_chief/home.html.twig
  templates/municipal_manager/_layout.html.twig
  templates/referent/_layout.html.twig
Labels: Ready for code review

#4682 Elected representative filters
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentativeTypeEnum.php
  src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  templates/elected_representative/list.html.twig
  templates/form_theme.html.twig
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4674 Add confirmation before sending emails & restrict emails to adherents only
  front/components/MessageStatusLoader.js
  front/listeners/confirm-modal.js
  migrations/Version20200813102442.php
  src/Entity/AdherentMessage/Filter/AbstractElectedRepresentativeFilter.php
  src/Form/AdherentMessage/ElectedRepresentativeFilterType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToElectedRepresentativeConditionBuilder.php
  templates/message/filter/referent_elected_representative.html.twig
  templates/message/preview.html.twig
Labels: Ready for code review

#4686 [TerritorialCouncil] Add update membership log
  config/services.yaml
  config/services/admin.xml
  migrations/Version20200811181456.php
  src/Admin/TerritorialCouncil/TerritorialCouncilAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipLogAdmin.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembershipLog.php
  src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  templates/admin/territorial_council/list_adherent.html.twig
  templates/admin/territorial_council/list_qualities.html.twig
  templates/admin/territorial_council/list_quality_name.html.twig
  templates/admin/territorial_council/list_territorial_councils.html.twig
  templates/admin/territorial_council/list_type.html.twig
Labels: Ready for code review

#4696 [TerritorialCouncil] Styles ajustement #2
  front/style/pages/_territorial-council.scss
  templates/territorial_council/candidacy_list.html.twig
Labels: Ready for code review

#4697 [TerritorialCouncil] fill candidacy quality from invited candidate
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Form/TerritorialCouncil/CandidacyQualityType.php
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/candidacy_step2_invitation.html.twig
  templates/territorial_council/candidacy_step3_confirmation.html.twig
Labels: Bug, Ready for code review

#4698 Assign circo & dpt to Euro Deputies
  src/Entity/ElectedRepresentative/ZoneCategory.php
Labels: Ready for code review

#4699 [TerritorialCouncil] send email with invitation to candidate
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Mailer/Message/CommitteeCandidacyCreatedConfirmationMessage.php
  src/Mailer/Message/CommitteeCandidacyRemovedConfirmationMessage.php
  src/Mailer/Message/CommitteeNewCandidacyNotificationMessage.php
  src/Mailer/Message/CommitteeRemovedCandidacyNotificationMessage.php
  src/Mailer/Message/Message.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationCreatedMessage.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationDeclinedMessage.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationRemovedMessage.php
  src/TerritorialCouncil/CandidacyManager.php
  src/TerritorialCouncil/Event/CandidacyInvitationEvent.php
  src/TerritorialCouncil/Events.php
  src/TerritorialCouncil/Listeners/SendCandidacyEmailListener.php
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4693 [TerritorialCouncil] Remove canary mode
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4701 [TerritorialCouncil] send email on invitation acceptation
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationAcceptedMessage.php
  src/Mailer/Message/TerritorialCouncilCandidacyInvitationDeclinedMessage.php
  src/TerritorialCouncil/CandidacyManager.php
  src/TerritorialCouncil/Events.php
  src/TerritorialCouncil/Listeners/SendCandidacyEmailListener.php
  templates/territorial_council/_election_box.html.twig
  templates/territorial_council/candidacy_step2_invitation.html.twig
  templates/territorial_council/invitation_list.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4684 [TerritorialCouncil] Complete admin page
  config/services/admin.xml
  src/Admin/TerritorialCouncil/TerritorialCouncilAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipAdmin.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  templates/admin/territorial_council/list_action_members.html.twig
  templates/admin/territorial_council/list_actions.html.twig
  templates/admin/territorial_council/list_membership_member.html.twig
  templates/admin/territorial_council/list_membership_qualities.html.twig
  templates/admin/territorial_council/list_president.html.twig
Labels: Ready for code review

#4700 [ElectedRepresentative] Add zones to senator mandates
  src/Entity/ElectedRepresentative/ZoneCategory.php
  src/Repository/ElectedRepresentative/ZoneRepository.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4702 Regional councils are elected in a department
  src/Entity/ElectedRepresentative/ZoneCategory.php
Labels: Ready for code review

#4706 Remove canary on elected representative messages
  src/Controller/EnMarche/AdherentMessage/ReferentElectedRepresentativeMessageController.php
Labels: Ready for code review

#4703 [Mailchimp] Sync territorial council membership
  migrations/Version20200814161402.php
  src/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandler.php
  src/Command/MailchimpSyncAllEventsCommand.php
  src/Controller/EnMarche/UserController.php
  src/Entity/Adherent.php
  src/Entity/AdherentSegment.php
  src/Entity/CitizenProject.php
  src/Entity/Committee.php
  src/Entity/StaticSegmentTrait.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/TerritorialCouncil/Event/MembershipEvent.php
  src/TerritorialCouncil/Events.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilElectedRepresentativeHandler.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilElectedCandidateAdherentHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilEmptyMembershipHandler.php
Labels: Ready for code review

#4707 Remove canary check for elected representative messages
  templates/message/_base_referent.html.twig
Labels: Ready for code review

#4710 [TerritorialCouncil] hide members
  templates/territorial_council/_nav.html.twig
  templates/territorial_council/index.html.twig
Labels: Ready for code review

#4709 Create handler to synchronize tags on mailchimp
  config/services/services.xml
  src/Mailchimp/Campaign/Listener/SynchroniseCampaignSegmentsSubscriber.php
  src/Mailchimp/CampaignEvent.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Events.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/MailchimpSegmentHandler.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#4711 [Test] fix Jecoute test by waiting table load in JS
  features/surveys.feature
Labels: Ready for code review

#4716 [JS] Fix typo in propTypes statement
  front/components/AdherentCommitteeList.js
  front/components/FacebookPictureChooser.js
  front/components/Loader.js
  front/components/MessageStatisticsWidget.js
  front/components/MessageStatusLoader.js
  front/components/Modal.js
  front/components/ProgrammaticFoundation/Approach.js
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/Project.js
  front/components/ProgrammaticFoundation/SearchBar.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/SubApproach.js
  front/components/ProgrammaticFoundation/ToggleLeadingMeasures.js
  front/components/UserListDefinitionWidget.js
  front/components/UserSegmentWidget.js
Labels: Ready for code review

#4717 [TerritorialCouncil] sync all memberships with MC
  src/Command/MailchimpSyncAllMembershipsCommand.php
Labels: Ready for code review

#4719 [TerritorialCouncil] improve candidacy search by using first_name too
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
Labels: Ready for code review

#4720 Revoke delegated access when delegator loose his role
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/Adherent.php
  src/EntityListener/RevokeDelegatedAccessListener.php
  tests/EntityListener/RevokeDelegatedAccessListenerTest.php
Labels: Ready for code review

#4722 [TerritorialCouncil] hide Accept checkbox for some qualities in candi…
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
  templates/territorial_council/candidacy_step1_edit.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#4718 Update rgpd mentions on forms
  templates/components/_gdpr_mentions.html.twig
  templates/events/attend.html.twig
  templates/membership/join.html.twig
Labels: Ready for code review

#4723 Remove canary on referent message for coTerr members
  src/Controller/EnMarche/AdherentMessage/ReferentTerritorialCouncilMessageController.php
  templates/message/_base_referent.html.twig
Labels: Ready for code review

#4724 [TerritorialCouncil][Admin] Add link to Territorial council list on memberships page
  config/services/admin.xml
  src/Admin/TerritorialCouncil/TerritorialCouncilAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipAdmin.php
  templates/admin/territorial_council/list.html.twig
  templates/admin/territorial_council/list_action_members.html.twig
Labels: Ready for code review

#4727 [TerritorialCouncil][Admin] Add Elected representative edit link on membership log page
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipLogAdmin.php
  templates/admin/territorial_council/membership_log_list_actions.html.twig
Labels: Ready for code review

#4726 add lre labels to elected representative in admin
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
Labels: Ready for code review

#4728 [TerritorialCouncil] Add home and FAQ wording
  front/style/pages/_territorial-council.scss
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  templates/components/_nav_desktop.html.twig
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/_slim_header_layout.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/candidacy_step2_invitation.html.twig
  templates/territorial_council/candidacy_step3_confirmation.html.twig
  templates/territorial_council/faq.html.twig
  templates/territorial_council/index.html.twig
  templates/territorial_council/invitation_list.html.twig
  templates/territorial_council/members.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/territorial_council/partials/_header.html.twig
  templates/territorial_council/partials/_member_identity_box.html.twig
  templates/territorial_council/partials/_nav.html.twig
  templates/territorial_council/partials/_sidebar.html.twig
  templates/territorial_council/partials/_slim_header.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#4731 [Admin] Add ElectedRepresentative info on Adherent edit page
  src/Admin/AdherentAdmin.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4733 [TerritorialCouncil] allow Referent to send election convocation
  features/api/adherents.feature
  features/municipal_chief_space.feature
  features/surveys.feature
  front/app.js
  front/style/app.scss
  front/style/layout/_forms-em.scss
  front/style/pages/_referent_space.scss
  migrations/Version20200821124210.php
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  src/Controller/EnMarche/CommitteeDesignation/ReferentDesignationController.php
  src/Controller/EnMarche/CommitteeDesignation/SupervisorDesignationController.php
  src/Controller/EnMarche/TerritorialCouncil/Designation/ReferentDesignationController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/BaseEvent.php
  src/Entity/CommitteeElection.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/TerritorialCouncil/Election.php
  src/Entity/VotingPlatform/Designation/AbstractElectionEntity.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Form/TerritorialCouncil/EditDesignationType.php
  src/Mailer/Message/TerritorialCouncilElectionConvocationMessage.php
  src/Repository/TerritorialCouncil/ElectionRepository.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/Security/Voter/TerritorialCouncil/AccessVoter.php
  src/Security/Voter/TerritorialCouncil/ManageTerritorialCouncilVoter.php
  src/TerritorialCouncil/Designation/DesignationVoteModeEnum.php
  src/TerritorialCouncil/Designation/UpdateDesignationHandler.php
  src/TerritorialCouncil/Designation/UpdateDesignationRequest.php
  src/TerritorialCouncil/Event/TerritorialCouncilEvent.php
  src/TerritorialCouncil/Events.php
  src/TerritorialCouncil/Listeners/SendConvocationEmailListener.php
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignation.php
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignationValidator.php
  templates/committee_designation/_base_referent.html.twig
  templates/committee_designation/_base_supervisor.html.twig
  templates/committee_designation/_layout.html.twig
  templates/committee_designation/dashboard.html.twig
  templates/committee_designation/list.html.twig
  templates/committee_designation/results.html.twig
  templates/committee_designation/show_layout.html.twig
  templates/committee_designation/voters_list.html.twig
  templates/committee_designation/votes_list.html.twig
  templates/donation/informations.html.twig
  templates/form_theme.html.twig
  templates/javascript.js.twig
  templates/referent/_layout.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/territorial_council_designation/_layout.html.twig
  templates/territorial_council_designation/convocation.html.twig
  templates/territorial_council_designation/list.html.twig
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4732 List adherent profiles similar to elected representative
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  src/Controller/Admin/ElectedRepresentativeSimilarAdherentProfilesController.php
  src/Repository/AdherentRepository.php
  templates/admin/adherent/list_status.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/admin/elected_representative/adherent_similar_profiles.html.twig
  templates/admin/elected_representative/edit.html.twig
  templates/admin/elected_representative/list_actions.html.twig
Labels: Ready for code review

#4744 [Admin][TerritorialCouncil] Fix access to members page
  config/packages/security.yaml
Labels: Ready for code review

#4736 Add legislative candidate space
  config/services/services.xml
  migrations/Version20200827233545.php
  src/Adherent/AdherentRoleEnum.php
  src/AdherentCharter/AdherentCharterFactory.php
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/AdherentZoneMailchimpCampaignHandler.php
  src/Admin/AdherentAdmin.php
  src/Admin/DistrictAdmin.php
  src/Collection/AdherentCharterCollection.php
  src/Controller/EnMarche/AdherentMessage/LegislativeCandidateMessageController.php
  src/Controller/EnMarche/InvitationController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/Entity/Adherent.php
  src/Entity/AdherentCharter/LegislativeCandidateCharter.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/LegislativeCandidateAdherentMessage.php
  src/Mailchimp/Campaign/ContentSection/LegislativeCandidateMessageSectionBuilder.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  templates/adherent/_list_my_sections.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/components/_nav_desktop.html.twig
  templates/invitation/adherent_space/_base_legislative_candidate_space.html.twig
  templates/legislative_candidate/_layout.html.twig
  templates/managed_users/_base_legislative_candidate_space.html.twig
  templates/message/_base_legislative_candidate.html.twig
  templates/message/filter/legislative_candidate.html.twig
  tests/Controller/EnMarche/LegislativesControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4746 Fix committee voting switcher
  templates/adherent_profile/_funnel_layout.html.twig
  templates/adherent_profile/_layout.html.twig
  templates/adherent_profile/activity.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4729 Add adherent readonly role on admin
  config/packages/security.yaml
  src/Admin/AdministratorAdmin.php
  templates/admin/adherent/_summary.html.twig
  templates/admin/adherent/list_actions.html.twig
  templates/admin/donator/list_is_adherent.html.twig
  templates/admin/elected_representative/edit.html.twig
  templates/admin/ideas_workshop/thread/list_thread_comments_contributors.html.twig
  templates/admin/territorial_council/list_actions.html.twig
Labels: Ready for code review

#4590 Commands to update and harmonize french administrative divisions tables
  config/services.yaml
  config/services/http_client.yaml
  migrations/Version20200825164048.php
  src/Command/Geo/Helper/Persister.php
  src/Command/Geo/Helper/Summary.php
  src/Command/Geo/SyncZoneCommand.php
  src/Command/Geo/UpdateCantonCommand.php
  src/Command/Geo/UpdateFranceCommand.php
  src/Entity/ElectedRepresentative/Zone.php
  tests/Command/Geo/UpdateFranceCommandTest.php
Labels: Ready for code review

#4749 [REFERENT] Add TerritorialCouncil members list
  src/Controller/EnMarche/TerritorialCouncil/Designation/ReferentDesignationController.php
  src/Controller/EnMarche/TerritorialCouncil/ReferentTerritorialCouncilController.php
  src/Form/TerritorialCouncil/MemberFilterType.php
  src/Repository/TerritorialCouncil/TerritorialCouncilMembershipRepository.php
  src/TerritorialCouncil/Filter/MembersListFilter.php
  templates/referent/_layout.html.twig
  templates/referent/territorial_council/_instances_nav.html.twig
  templates/referent/territorial_council/members.html.twig
  templates/territorial_council_designation/_layout.html.twig
  templates/territorial_council_designation/list.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/ReferentTerritorialCouncilControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#4750 [TerritorialCouncil] allow single candidacy
  front/components/TerritorialCouncilCandidacyWidget.js
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Form/TerritorialCouncil/CandidacyQualityType.php
  src/Repository/TerritorialCouncil/CandidacyRepository.php
  src/TerritorialCouncil/CandidacyManager.php
  src/TerritorialCouncil/Event/CandidacyInvitationEvent.php
  src/TerritorialCouncil/Listeners/SendCandidacyEmailListener.php
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/candidacy_step2_invitation.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review
