Repository parti-renaissance/espace-adherent, pull requests merged in 2020-03, with the labels that each got.

#4254 Feature ETQM je peux indiquer où je vote
  migrations/Version20200224124920.php
  src/Committee/CommitteeManager.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/CommitteeMembership.php
  src/Repository/CommitteeMembershipRepository.php
  templates/adherent/activities.html.twig
  templates/adherent/committees.html.twig
  templates/adherent/events.html.twig
Labels: Work in progress

#4269 [VoteResultList] add Vote List crud
  app/config/services/services.xml
  migrations/Version20200302100656.php
  src/Controller/EnMarche/Election/VoteResultList/AbstractVoteResultListController.php
  src/Controller/EnMarche/Election/VoteResultList/MunicipalChiefVoteResultListController.php
  src/Controller/EnMarche/Election/VoteResultList/MunicipalManagerVoteResultListController.php
  src/Controller/EnMarche/Election/VoteResultList/ReferentVoteResultListController.php
  src/Controller/EnMarche/Election/VoteResults/AbstractVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/AssessorVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/DefaultVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/MunicipalChiefVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/MunicipalManagerVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/ReferentVoteResultController.php
  src/DataFixtures/ORM/LoadVoteResultData.php
  src/DataFixtures/ORM/LoadVoteResultListCollectionData.php
  src/Election/ElectionManager.php
  src/Election/VoteListNuanceEnum.php
  src/Entity/Election/ListTotalResult.php
  src/Entity/Election/VoteResultList.php
  src/Entity/Election/VoteResultListCollection.php
  src/Entity/Election/VoteResultListCollectionCityProxy.php
  src/Entity/VoteResult.php
  src/Form/ListTotalResultType.php
  src/Form/VoteResultListCollectionType.php
  src/Form/VoteResultListType.php
  src/Form/VoteResultType.php
  src/Repository/CityRepository.php
  src/Repository/Election/VoteResultListCollectionRepository.php
  templates/assessor_attribution/index.html.twig
  templates/election_result_list/_base_municipal_chief_space.html.twig
  templates/election_result_list/_base_municipal_manager_space.html.twig
  templates/election_result_list/_base_referent_space.html.twig
  templates/election_result_list/_layout.html.twig
  templates/election_result_list/edit.html.twig
  templates/election_vote_results/index.html.twig
  templates/form_theme.html.twig
  templates/municipal_chief/_layout.html.twig
  templates/municipal_manager/_layout.html.twig
  templates/referent/_layout.html.twig
  templates/referent/municipal_manager/attribution_form.html.twig
Labels: Ready for code review

#4271 [VoteResult] enable blameable listener
  app/config/config.yml
  app/config/services/services.xml
  migrations/Version20200302213404.php
  src/Election/ElectionManager.php
  src/Election/Listener/VoteResultBlameableListener.php
  src/Entity/Election/ListTotalResult.php
  src/Entity/VotePlace.php
  src/Entity/VoteResult.php
  src/Form/ListTotalResultType.php
  templates/assessor_attribution/index.html.twig
  templates/election_vote_results/index.html.twig
Labels: Ready for code review

#4273 [Admin] Add new ElectionResultsReporter role
  migrations/Version20200302213404.php
  migrations/Version20200303120914.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  templates/admin/adherent/list_status.html.twig
  templates/components/_nav_desktop.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4275 [Election] Allow report City vote result
  migrations/Version20200303180519.php
  src/Controller/EnMarche/Election/VoteResults/CityVoteResultController.php
  src/Controller/EnMarche/ElectionResultsReporterController.php
  src/Election/ElectionManager.php
  src/Entity/CityVoteResult.php
  src/Exporter/VoteResultsExporter.php
  src/Form/BasicVoteListResultType.php
  src/Form/CityFilterType.php
  src/Form/CityVoteResultType.php
  src/Repository/CityVoteResultRepository.php
  templates/adherent/_list_my_sections.html.twig
  templates/election_results_reporter/_layout.html.twig
  templates/election_results_reporter/cities_list.html.twig
  templates/election_results_reporter/form.html.twig
  templates/election_vote_results/index.html.twig
  templates/form_theme.html.twig
Labels: Ready for code review

#4268 Add ElectedRepresentative admin (list, show, modification page)
  app/config/services/admin.xml
  app/config/services/services.xml
  migrations/Version20200228112636.php
  src/Admin/CityAdmin.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/SocialLinkTypeEnum.php
  src/Entity/ElectedRepresentative/SocialNetworkLink.php
  src/Exception/BadSocialLinkTypeException.php
  src/Form/AdherentEmailType.php
  src/Form/AssessorRoleAssociationType.php
  src/Form/MunicipalManagerCityAssociationType.php
  src/Form/SocialNetworkLinkType.php
  templates/admin/elected_representative/list_is_adherent.html.twig
  templates/admin/elected_representative/show_contact_phone.html.twig
  templates/admin/elected_representative/show_email.html.twig
  templates/admin/elected_representative/show_is_adherent.html.twig
  templates/admin/elected_representative/show_phone.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#4274 [AdherentBinome] Fix style on "Mes activités"
  front/style/app.scss
  front/style/layout/_forms-em.scss
  front/style/layout/_layout.scss
  front/style/layout/_modal.scss
  front/style/pages/_adherent-activities.scss
  templates/adherent/activities.html.twig
  templates/adherent/committees.html.twig
  templates/adherent/events.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
Labels: Ready for code review

#4282 Remove canary mode for vote results pages
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/Election/VoteResults/AbstractVoteResultController.php
  src/Controller/EnMarche/Election/VoteResults/CityVoteResultController.php
  src/Repository/VoteResultRepository.php
  templates/adherent/_list_my_sections.html.twig
  templates/assessor_attribution/index.html.twig
Labels: Ready for code review

#4281 [AdherentBinome] Fix style on "Mes activités" part2
  templates/adherent/activities.html.twig
  templates/adherent/committees.html.twig
  templates/adherent/events.html.twig
Labels: Ready for code review

#4277 Add Mandates to ElectedRepresentative
  migrations/Version20200303163802.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/LaREMSupportEnum.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/MandateTypeEnum.php
  src/Exception/BadMandateTypeException.php
  src/Form/MandateType.php
  templates/form_theme_admin.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#4286 Enable canary for my-committees page
  templates/adherent/activities.html.twig
Labels: Ready for code review

#4287 Remove canary for municipal manager attribution features
  src/Controller/EnMarche/MunicipalManagerAttribution/AbstractMunicipalManagerAttributionController.php
  templates/adherent/_list_my_sections.html.twig
  templates/assessor_attribution/_sub_menu.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4290 [Assessor] some fixes
  src/Controller/EnMarche/AssessorSpace/AbstractAssessorSpaceController.php
  src/Controller/EnMarche/Election/VoteResultList/ReferentVoteResultListController.php
  src/Entity/VotePlace.php
  templates/admin/adherent/list_status.html.twig
  templates/admin/elected_representative/show_contact_phone.html.twig
  templates/municipal_chief/_layout.html.twig
  templates/municipal_manager_attribution/index.html.twig
  templates/referent/_layout.html.twig
  templates/referent/municipal_manager/attribution_form.html.twig
Labels: Bug, Ready for code review

#4296 [Referent] Revoke referent team member roles if referent loses his role
  src/Entity/Adherent.php
  src/EntityListener/RevokeReferentTeamMemberRolesListener.php
  src/Repository/ReferentOrganizationalChart/ReferentPersonLinkRepository.php
Labels: Ready for code review

#4301 [Chatbot] add Botmind script
  templates/bot/_javascript.html.twig
Labels: Ready for code review

#4278 Update Sf patch version
  composer.lock
Labels: Ready for code review

#4309 Fix Assessors filter handleRequest method
  migrations/Version20200311141459.php
  src/Controller/EnMarche/AssessorSpace/AbstractAssessorSpaceController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/AbstractMunicipalManagerAttributionController.php
  src/DataFixtures/ORM/LoadVoteResultData.php
  src/Entity/Election/BaseVoteResult.php
  src/Exporter/VoteResultsExporter.php
  src/Form/Election/BaseVoteResultType.php
  templates/election_results_reporter/form.html.twig
  templates/election_vote_results/_form_layout.html.twig
  templates/form_theme.html.twig
Labels: Bug, Ready for code review

#4306 [RepublicanSilence] lock IdeaWorkshop creation page
  src/Controller/Api/RepublicanSilenceController.php
  src/DataFixtures/ORM/LoadMinistryVoteResultData.php
  src/DataFixtures/ORM/LoadVotePlaceResultData.php
  src/DataFixtures/ORM/LoadVoteResultListCollectionData.php
  src/Entity/ReferentManagedArea.php
  src/Entity/ReferentTag.php
  src/Entity/RepublicanSilence.php
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  src/RepublicanSilence/RepublicanSilenceManager.php
  src/RepublicanSilence/TagExtractor/CommitteeReferentTagExtractor.php
  src/RepublicanSilence/TagExtractor/MunicipalChefReferentTagExtractor.php
  src/RepublicanSilence/TagExtractor/ReferentTagExtractor.php
  src/RepublicanSilence/TagExtractor/ReferentTagExtractorInterface.php
  src/RepublicanSilence/TagExtractor/SenatorReferentTagExtractor.php
  tests/Controller/Api/IdeasWorkshop/IdeaPublishControllerTest.php
  web/apps/atelier-des-idees/src/components/RepublicanSilence/index.jsx
  web/apps/atelier-des-idees/src/pages/CreateIdeaPage/index.js
  web/apps/atelier-des-idees/src/redux/selectors/republicanSilence.js
  web/apps/atelier-des-idees/src/redux/thunk/static.js
Labels: Ready for code review

#4311 Update wording for co-referent space
  templates/adherent/_list_my_sections.html.twig
  templates/components/_nav_mobile.html.twig
  templates/managed_users/_base_referent_space.html.twig
Labels: Ready for code review

#4313 Remove Assessor assignation validator
  app/config/services/services.xml
  src/Assessor/AssessorRoleAssociationValueObject.php
  src/Validator/ValidAdherentForVotePlace.php
  src/Validator/ValidAdherentForVotePlaceValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#4314 Enable canary for my europe page
  src/Controller/EnMarche/InteractiveController.php
Labels: Ready for code review

#4312 Change "Formation" redirection to MOOC
  templates/components/_footer.html.twig
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4283 [ADMIN] ElectedRepresentative list with filters and export
  src/Admin/ElectedRepresentativeAdmin.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  templates/admin/elected_representative/list_mandates.html.twig
  templates/admin/elected_representative/list_political_functions.html.twig
Labels: Ready for code review

#4303 [ADMIN] Add Labels to ElectedRepresentative
  app/config/services/admin.xml
  app/config/services/services.xml
  migrations/Version20200313112431.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/Controller/Admin/AdminElectedRepresentativeController.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/ElectedRepresentativeLabel.php
  src/Entity/PoliticalLabel.php
  src/Form/ElectedRepresentative/ElectedRepresentativeLabelType.php
  src/Repository/PoliticalLabelRepository.php
  templates/admin/elected_representative/label_name_type_model_autocomplete.html.twig
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4295 Introduce city cards
  app/config/security.yml
  app/config/services/admin.xml
  migrations/Version20200313133408.php
  src/Admin/AdministratorAdmin.php
  src/Admin/Election/AbstractCityCardAdmin.php
  src/Admin/Election/CityCardAdmin.php
  src/Admin/Election/CityCardContactAdmin.php
  src/Admin/Election/CityCardManagersAdmin.php
  src/Admin/Election/CityCardPartnerAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadCityData.php
  src/DataFixtures/ORM/LoadElectionCityCardData.php
  src/Election/CityResultAggregator.php
  src/Election/CityResults.php
  src/Election/ListTotalResult.php
  src/Election/VotePlacesResult.php
  src/Entity/City.php
  src/Entity/Department.php
  src/Entity/Election/CityCandidate.php
  src/Entity/Election/CityCard.php
  src/Entity/Election/CityContact.php
  src/Entity/Election/CityManager.php
  src/Entity/Election/CityPartner.php
  src/Entity/Election/CityPrevision.php
  src/Entity/Region.php
  src/Form/Admin/Election/CityCandidateType.php
  src/Form/Admin/Election/CityManagerType.php
  src/Form/Admin/Election/CityPrevisionType.php
  src/Form/EventListener/CityCardListener.php
  src/Repository/AssessorRequestRepository.php
  src/Repository/CityRepository.php
  src/Repository/Election/MinistryVoteResultRepository.php
  src/Repository/Election/VotePlaceResultRepository.php
  src/Repository/GeoFilterTrait.php
  src/Repository/VotePlaceRepository.php
  src/Twig/ElectionVoteResultExtension.php
  src/Twig/ElectionVoteResultRuntime.php
  templates/admin/election/city_card/_form_theme_admin.html.twig
  templates/admin/election/city_card/_list_manager.html.twig
  templates/admin/election/city_card/_list_postal_codes.html.twig
  templates/admin/election/city_card/edit.html.twig
  templates/admin/election/city_card/edit_managers.html.twig
  templates/form_theme_admin.html.twig
  templates/municipal_manager/cities.html.twig
  templates/municipal_manager_attribution/index.html.twig
  translations/messages.fr.yml
Labels: Work in progress

#4315 City cards export
  src/Admin/Election/CityCardAdmin.php
  src/Controller/Admin/AdminExportCityCardController.php
  src/Election/CityResults.php
  templates/admin/city_card/list.html.twig
Labels: Ready for code review

#4319 [Admin] add pagination for citycard admin
  src/Controller/Admin/AdminExportCityCardController.php
  src/Election/VoteListNuanceEnum.php
  templates/admin/city_card/list.html.twig
Labels: Ready for code review

#4320 Fix blameableListener for MinistryVoteResult
  src/Election/Listener/VoteResultBlameableListener.php
  src/Entity/Election/MinistryListTotalResult.php
Labels: Bug, Ready for code review

#4326 [VoteList] add position and candidate fields
  migrations/Version20200315102252.php
  src/DataFixtures/ORM/LoadMinistryVoteResultData.php
  src/DataFixtures/ORM/LoadVoteResultListCollectionData.php
  src/Entity/Election/ListFieldTrait.php
  src/Entity/Election/MinistryListTotalResult.php
  src/Entity/Election/VoteResultList.php
  src/Form/VoteResultListType.php
  templates/form_theme.html.twig
Labels: Ready for code review

#4330 Disable front chatbot on dev
  templates/base.html.twig
  templates/bot/_javascript.html.twig
Labels: Ready for code review

#4331 [MinistryResult] add import result command
  app/config/services/services.xml
  src/Command/ImportElectionMinistryResultCommand.php
  src/Entity/Election/MinistryVoteResult.php
  src/Repository/CityRepository.php
Labels: Ready for code review

#4338 Increase message limits
  app/config/config.yml
Labels: Ready for code review

#4339 [MinistryResult] fix import command by handle timeout exception
  src/Command/ImportElectionMinistryResultCommand.php
Labels: Ready for code review

#4308 [ADMIN] Add Sponsorships to ElectedRepresentative
  migrations/Version20200310163906.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Sponsorship.php
  src/Form/ElectedRepresentative/MandateType.php
  src/Form/ElectedRepresentative/PoliticalFunctionType.php
  src/Form/ElectedRepresentative/SponsorshipType.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4340 Fixe horizontal scroll on datagrid tables
  front/components/DataGrid.js
  front/style/manager-space/_tables.scss
  templates/assessor_attribution/index.html.twig
  templates/assessor_manager/requests.html.twig
  templates/assessor_manager/vote_places.twig
  templates/election_results_reporter/cities_list.html.twig
  templates/managed_users/list.html.twig
  templates/message/list.html.twig
  templates/procuration_manager/proposals.html.twig
  templates/procuration_manager/requests.html.twig
Labels: Ready for code review

#4341 [ADMIN] Link ElectedRepresentative functions with mandates
  migrations/Version20200318114627.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/ElectedRepresentative/ElectedRepresentativeMandatesOrderer.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Form/ElectedRepresentative/MandateType.php
  src/Form/ElectedRepresentative/PoliticalFunctionType.php
  src/Repository/ElectedRepresentative/MandateRepository.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4344 Remove "appel à candidatures" link in menu
  templates/components/_nav_desktop.html.twig
  templates/components/_nav_mobile.html.twig
Labels: Ready for code review

#4285 Fix candidacy
  features/committee_vote.feature
  front/app.js
  front/components/Modal.js
  front/components/VoteCommitteeWidget.js
  front/pages/my_activity_committees.js
  front/services/api/ReqwestApiClient.js
  front/style/layout/_forms-em.scss
  front/style/manager-space/_base-layout.scss
  front/style/pages/_adherent-activities.scss
  front/style/pages/_committee.scss
  src/Collection/CommitteeMembershipCollection.php
  src/Committee/CommitteeManager.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/CommitteeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAdherentTagData.php
  src/DataFixtures/ORM/LoadApplicationRequestTagData.php
  src/DataFixtures/ORM/LoadBoardMemberRoleData.php
  src/DataFixtures/ORM/LoadCitizenActionCategoryData.php
  src/DataFixtures/ORM/LoadCitizenActionData.php
  src/DataFixtures/ORM/LoadCitizenProjectCategoryData.php
  src/DataFixtures/ORM/LoadCitizenProjectData.php
  src/DataFixtures/ORM/LoadCitizenProjectSkillData.php
  src/DataFixtures/ORM/LoadClientData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/DataFixtures/ORM/LoadExecutiveOfficeMemberData.php
  src/DataFixtures/ORM/LoadInstitutionalEventData.php
  src/DataFixtures/ORM/LoadNewsletterSubscriptionData.php
  src/DataFixtures/ORM/LoadOrderSectionData.php
  src/DataFixtures/ORM/LoadTurnkeyProjectData.php
  src/Exception/CommitteeMembershipException.php
  src/Security/Voter/Committee/VoteCommitteeVoter.php
  src/Twig/CommitteeElectionExtension.php
  src/Twig/CommitteeRuntime.php
  templates/adherent/committees.html.twig
  templates/adherent/my_activity_committees.html.twig
  templates/adherent/my_activity_events.html.twig
  templates/adherent/my_activity_layout.html.twig
  templates/committee/show.html.twig
Labels: Pending

#4345 [CommitteeVote] add candidacies list modal
  features/committee_vote.feature
  front/app.js
  front/components/CandidaciesListWidget.js
  front/components/Modal.js
  front/pages/committee_candidacies.js
  front/pages/manage_user_segment.js
  front/services/address/GooglePlaceAutocomplete.js
  front/services/api/ReqwestApiClient.js
  package.json
  src/Controller/Api/CommitteesController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Entity/CommitteeElection.php
  src/Repository/CommitteeCandidacyRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Security/Voter/Committee/MemberOfCommitteeVoter.php
  templates/committee/show.html.twig
  tests/Controller/Api/CommitteesControllerTest.php
  yarn.lock
Labels: Ready for code review

#4347 Remove unnecessary php polyfills
  composer.json
  composer.lock
Labels: Ready for code review

#4352 Enable canary mode for candidacy block
  templates/committee/show.html.twig
Labels: Ready for code review

#4354 Disable canary on Deputy and Senator spaces
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/DeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/SenatorEventManagerController.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/Controller/EnMarche/PageController.php
  templates/deputy/_layout.html.twig
  templates/senator/_layout.html.twig
Labels: Ready for code review

#4355 Update candidacies list modal
  front/components/CandidaciesListWidget.js
  front/components/VoteCommitteeWidget.js
  src/Controller/Api/CommitteesController.php
  templates/adherent/my_activity_committees.html.twig
Labels: Ready for code review

#4356 Remove canary for deputy committees page
  src/Controller/EnMarche/DeputyController.php
  templates/deputy/_layout.html.twig
Labels: Ready for code review

#4351 [Unregistration] handle the request on async mode
  app/config/config_test.yml
  app/config/services/platform.xml
  app/config/services/services.xml
  app/config/services/services.yml
  src/Adherent/BanManager.php
  src/Adherent/Command/RemoveAdherentAndRelatedDataCommand.php
  src/Adherent/Handler/RemoveAdherentAndRelatedDataCommandHandler.php
  src/Adherent/Unregistration/Handlers/RemoveAdherentMessageHandler.php
  src/Adherent/Unregistration/Handlers/RemoveAdherentSegmentHandler.php
  src/Adherent/Unregistration/Handlers/RemoveAdherentSummaryHandler.php
  src/Adherent/Unregistration/Handlers/RemoveAdherentTokensHandler.php
  src/Adherent/Unregistration/Handlers/RemoveCommitteeItemHandler.php
  src/Adherent/Unregistration/Handlers/UnfollowCitizenProjectHandler.php
  src/Adherent/Unregistration/Handlers/UnfollowCommitteeHandler.php
  src/Adherent/Unregistration/Handlers/UnregistrationAdherentHandlerInterface.php
  src/Adherent/Unregistration/Handlers/UpdateApplicationRequestHandler.php
  src/Adherent/Unregistration/Handlers/UpdateEmailSubscriptionHistoryHandler.php
  src/Adherent/Unregistration/Handlers/UpdateEventHandler.php
  src/Adherent/Unregistration/Handlers/UpdateEventRegistrationHandler.php
  src/Adherent/Unregistration/Handlers/UpdateIdeaWorkshopHandler.php
  src/Adherent/Unregistration/Handlers/UpdateReportHandler.php
  src/Adherent/Unregistration/UnregistrationCommand.php
  src/Adherent/Unregistration/UnregistrationFactory.php
  src/Adherent/UnregistrationHandler.php
  src/Command/UnregisterAdherentsCommand.php
  src/Controller/EnMarche/UserController.php
  src/Entity/Adherent.php
  src/Form/UnregistrationType.php
  src/Membership/AdherentRegistry.php
  src/Membership/MembershipPermissions.php
  src/Membership/MembershipRequestHandler.php
  src/Repository/CitizenProjectRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/EventRepository.php
  src/Security/UserChecker.php
  src/Security/Voter/MembershipVoter.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Security/Voter/MembershipVoterTest.php
Labels: Ready for code review

#4350 [ADMIN] ElectedRepresentative : change label's field
  app/config/services/admin.xml
  migrations/Version20200324140944.php
  src/Admin/ElectedRepresentativeAdmin.php
  src/Controller/Admin/AdminElectedRepresentativeController.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/ElectedRepresentativeLabel.php
  src/Entity/ElectedRepresentative/LabelNameEnum.php
  src/Entity/PoliticalLabel.php
  src/Form/ElectedRepresentative/ElectedRepresentativeLabelType.php
  src/Repository/PoliticalLabelRepository.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4353 [ADMIN] ElectedRepresentative : change sponsorship candidate's field
  src/Entity/ElectedRepresentative/CandidateNameEnum.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#4357 [CommitteeCandidacy] improve candidacy button behaviour
  features/api/committees.feature
  features/committee_vote.feature
  front/components/VoteCommitteeWidget.js
  src/Controller/EnMarche/CommitteeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Security/Voter/Committee/CommitteeCandidacyVoter.php
  src/Security/Voter/Committee/FollowerCommitteeVoter.php
  templates/committee/show.html.twig
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Api/CommitteesControllerTest.php
Labels: Ready for code review

#4346 [ADMIN] Add ElectedRepresentative zones
  app/config/services/services.xml
  migrations/Version20200319171717.php
  src/Controller/Admin/AdminElectedRepresentativeController.php
  src/DataFixtures/ORM/LoadZoneCategoryData.php
  src/DataFixtures/ORM/LoadZoneData.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/ElectedRepresentative/Zone.php
  src/Entity/ElectedRepresentative/ZoneCategory.php
  src/Entity/Epci.php
  src/Form/ElectedRepresentative/MandateType.php
  src/Form/ElectedRepresentative/PoliticalFunctionType.php
  src/Form/ElectedRepresentative/ZoneType.php
  src/Repository/ElectedRepresentative/ZoneRepository.php
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#3669 [New-Sf-Structure] step 1: move AppKernel, add bundles.php, move some…
  app/AppKernel.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_dev_front.yml
  app/config/config_prod.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  app/config/routing_dev.yml
  app/config/services/services.xml
  app/var/sessions/118c64daac57ad6a08e0911e2c0f3c7b83749ae092c07cc82af328c77c45b965.mocksess
  behat.yml.dist
  bin/console
  composer.json
  config/bundles.php
  config/packages/dev/routing.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/dev_front/web_profiler.yaml
  config/packages/messenger.yaml
  config/packages/prod/doctrine.yaml
  config/packages/routing.yaml
  config/packages/test/framework.yaml
  config/packages/test/messenger.yaml
  config/packages/test/routing.yaml
  config/packages/test/web_profiler.yaml
  config/routes.yml
  config/routes/dev/twig.yaml
  config/routes/dev/web_profiler.yaml
  phpunit.xml.dist
  src/AppBundle.php
  src/Command/ImportReferentNominationCommand.php
  src/Kernel.php
  tests/Command/ImportReferentBioPictureCommandTest.php
  web/index.php
Labels: Ready for code review

#4360 Change HP medium's article CTA label
  templates/home/articles.html.twig
Labels: Ready for code review

#4363 Add EM confirmation modal widget
  features/committee_vote.feature
  front/app.js
  front/listeners/confirm-modal.js
  templates/adherent/my_activity_committees.html.twig
  templates/committee/show.html.twig
Labels: Ready for code review

#4364 [CommitteeVote] prohibit changing committee vote for supervisor
  src/Controller/EnMarche/CommitteeController.php
  src/Security/Voter/Committee/ChangeCommitteeVoteVoter.php
  templates/adherent/my_activity_committees.html.twig
Labels: Ready for code review

#4366 Change VoteListNuanceEnum
  migrations/Version20200330100733.php
  src/Election/VoteListNuanceEnum.php
Labels: Ready for code review

#3906 [New-Sf-Structure] step2: move config files
  .gitignore
  Makefile
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  config/packages/a2lix_translation_form.yaml
  config/packages/adherent.yaml
  config/packages/api_platform.yaml
  config/packages/app_version.yaml
  config/packages/bazinga_geocoder.yaml
  config/packages/csa_guzzle.yaml
  config/packages/dev/api_platform.yaml
  config/packages/dev/doctrine.yaml
  config/packages/dev/monolog.yaml
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/endroid_qr_code.yaml
  config/packages/exercise_html_purifier.yaml
  config/packages/framework.yaml
  config/packages/knp_snappy.yaml
  config/packages/lexik_jwt_authentication.yaml
  config/packages/lexik_paybox.yaml
  config/packages/nelmio_cors.yaml
  config/packages/old_sound_rabbit_mq.yaml
  config/packages/prod/algolia.yaml
  config/packages/prod/lexik_paybox.yaml
  config/packages/prod/monolog.yaml
  config/packages/scheb_two_factor.yaml
  config/packages/security.yaml
  config/packages/snc_redis.yaml
  config/packages/sonata_admin.yaml
  config/packages/sonata_block.yaml
  config/packages/sonata_doctrine_orm_admin.yaml
  config/packages/stof_doctrine_extensions.yaml
  config/packages/test/api_platform.yaml
  config/packages/test/doctrine.yaml
  config/packages/test/lexik_paybox.yaml
  config/packages/test/old_sound_rabbit_mq.yaml
  config/packages/test/security.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/workflows.yaml
  config/services/mailchimp.yaml
  scripts/build.sh
  src/Kernel.php
  webpack.production.js
Labels: Ready for code review

#4367 [CandidacyBlock] add woman/man parity warning
  app/config/services/twig.xml
  src/Twig/CommitteeElectionExtension.php
  src/Twig/CommitteeRuntime.php
  templates/adherent/my_activity_committees.html.twig
  templates/committee/show.html.twig
Labels: Ready for code review

#4370 Update vote status when merge two committees
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeCreationCommand.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Exception/CommitteeMembershipException.php
  src/Repository/CommitteeMembershipRepository.php
  tests/Committee/CommitteeCommandTest.php
Labels: Ready for code review
