Repository parti-renaissance/espace-adherent, pull requests merged in 2021-11, with the labels that each got.

#6486 [PHP] Update Symfony to 4.4.33
  composer.lock
Labels: dependencies, composer

#6505 [PHP] Update Symfony to 4.4.33
  composer.json
  composer.lock
Labels: dependencies, composer

#6472 New master
  .circleci/config.yml
  .dockerignore
  .env
  Dockerfile
  config/packages/doctrine.yaml
  config/packages/firebase.yaml
  config/services.yaml
  docker-compose.yml
  features/api/coalition_events.feature
  scripts/build.sh
  src/Storage/FilesystemAdapterFactory.php
  src/Vision/ImageAnnotatorClient.php
  tests/Storage/FilesystemAdapterFactoryTest.php
Labels: Work in progress

#6459 Change phone SubscriptionType label
  features/api/profile.feature
  features/registration.feature
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  templates/candidate/_table.html.twig
  templates/managed_users/_table.html.twig
  templates/membership/join.html.twig
  templates/municipal_chief/adherent/list.html.twig
  templates/referent/territorial_council/members.html.twig
Labels: Ready for code review

#6466 [API][News] Add get news endpoint
  features/api/jecoute_news.feature
  src/Api/Doctrine/JecouteNewsExtension.php
  src/Api/Filter/JecouteNewsScopeFilter.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Jecoute/News.php
  src/Normalizer/JecouteNewsNormalizer.php
Labels: Ready for code review

#6479 [API][News] Add POST and PUT news endpoints
  config/services.yaml
  features/api/jecoute_news.feature
  src/Api/Serializer/JecouteNewsGroupsContextBuilder.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Jecoute/News.php
  src/Jecoute/Api/Listener/PostWriteNewsListener.php
  src/Jecoute/Api/Listener/PreWriteNewsListener.php
  src/Normalizer/JecouteNewsNormalizer.php
  src/Repository/Geo/ZoneRepository.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
Labels: Ready for code review

#6522 [PHP] Sync composer deps
  composer.json
  composer.lock
Labels: dependencies, composer

#6515 [EM-1192] add crud endpoints for phoning campaign
  config/services/admin.xml
  features/api/phoning_campaigns.feature
  features/api/surveys.feature
  features/api/teams.feature
  migrations/Version20211028141452.php
  src/Entity/Audience/AudienceFieldsTrait.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/EntityZoneTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Entity/Team/Team.php
  src/Normalizer/AdherentBlameableDenormalizer.php
  src/Normalizer/CampaignNormalizer.php
  src/Normalizer/JecouteSurveyNormalizer.php
  src/Normalizer/TeamFromUuidDenormalizer.php
Labels: Ready for code review

#6523 [EM-1246] add a get endpoint for campaign histories list with some fi…
  features/api/phoning_campaigns.feature
  src/Api/Filter/AdherentIdentityFilter.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
Labels: Work in progress

#6530 [News][API] add creator for DC endpoints
  features/api/jecoute_news.feature
  src/Normalizer/JecouteNewsNormalizer.php
Labels: Ready for code review

#6531 [Audience] add adherent role field for supervisors
  migrations/Version20211116130705.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Entity/Audience/AudienceFieldsTrait.php
  src/Entity/Audience/AudienceInterface.php
  src/Form/Audience/AudienceSnapshotType.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6539 [API] update zone autocomplete endpoint for adding zone types param
  features/api/zones.feature
  src/AdherentFilter/FilterBuilder/ZoneAutocompleteFilterBuilder.php
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Filter/Types/DefinedTypes/ZoneAutocomplete.php
Labels: Ready for code review

#6528 [PAP][API] Get address building structure
  features/api/pap_address.feature
  migrations/Version20211117151217.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/Floor.php
  src/Pap/BuildingStatusEnum.php
Labels: Ready for code review

#6540 [Audience] fix committeeMember filter
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentInterestConditionBuilder.php
Labels: Ready for code review

#6547 [SMS] Handle STOP sms webhook call
  migrations/Version20211118110102.php
  src/Admin/SmsCampaignAdmin.php
  src/Controller/Admin/AdminSmsCampaignCRUDController.php
  src/Controller/EnMarche/OvhSmsWebhookController.php
  src/DataFixtures/ORM/LoadSmsCampaignData.php
  src/Entity/SmsCampaign/SmsCampaign.php
  src/Entity/SmsCampaign/SmsStopHistory.php
  src/OvhCloud/Notifier.php
  src/Repository/AdherentRepository.php
  src/Repository/SmsCampaignRepository.php
  src/SmsCampaign/Command/CatchOvhSmsWebhookCallCommand.php
  src/SmsCampaign/Handler/CatchOvhSmsWebhookCallCommandHandler.php
  src/SmsCampaign/Handler/SendSmsCampaignCommandHandler.php
  src/Utils/PhoneNumberUtils.php
Labels: Ready for code review

#6546 [PAP] Add Building to CampaignHistory
  features/api/pap_campaigns.feature
  migrations/Version20211117174035.php
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/CampaignHistory.php
Labels: Ready for code review

#6548 [Candidacy] Fix check for existing binome candidacies
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
Labels: Bug, Ready for code review

#6550 [Admin] Fix setting current admin on Campaign creation
  src/Admin/Phoning/CampaignAdmin.php
Labels: Bug, Ready for code review

#6549 Remove renovate
  renovate.json
Labels: Ready for code review

#6553 [ZoneAutocomplete] avoid perimeter check for national scope
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Scope/ScopeEnum.php
Labels: Ready for code review

#6552 [Admin] Add participants count for phoning campaign
  Makefile
  features/api/phoning_campaigns.feature
  migrations/Version20211118172844.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6558 [PAP] Add building statistics tables
  features/api/pap_address.feature
  migrations/Version20211118144647.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/BuildingBlockStatistics.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignStatisticsInterface.php
  src/Entity/Pap/CampaignStatisticsTrait.php
  src/Entity/Pap/Floor.php
  src/Entity/Pap/FloorStatistics.php
  src/Normalizer/BuildingStatusNormalizer.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6566 [EM-1253] add phoning campaign callers with their stats
  features/api/phoning_campaigns.feature
  src/Controller/Api/AdherentFilter/GetFilterCollectionController.php
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/Api/Jecoute/AbstractReplyController.php
  src/Controller/Api/Phoning/GetPhoningCampaignCallersStatsController.php
  src/Entity/Phoning/Campaign.php
  src/Normalizer/CampaignScoreNormalizer.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6563 [PHP] update a2lix/translation-form-bundle
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20211119194504.php
  src/Entity/AbstractTranslatableEntity.php
  src/Entity/Timeline/Manifesto.php
  src/Entity/Timeline/ManifestoTranslation.php
  src/Entity/Timeline/Measure.php
  src/Entity/Timeline/MeasureTranslation.php
  src/Entity/Timeline/Profile.php
  src/Entity/Timeline/ProfileTranslation.php
  src/Entity/Timeline/Theme.php
  src/Entity/Timeline/ThemeTranslation.php
  templates/admin/form_translations.html.twig
Labels: Ready for code review, dependencies, composer

#6568 [API] Fix news update
  migrations/Version20211122174400.php
  src/Entity/Jecoute/News.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
Labels: Ready for code review

#6574 [Config] Remove unused front-dev env
  app/data/circonscriptions.csv
  app/data/geolite2-countries.mmdb
  bin/mac-docker-install.sh
  config/bundles.php
  config/packages/dev_front/web_profiler.yaml
  config/services_dev_front.yaml
  docker/dev/nginx.conf
  src/Twig/AssetRuntime.php
Labels: Ready for code review

#6567 [Admin] Display sms campaign stats on view action
  src/Admin/SmsCampaignAdmin.php
  src/Controller/Admin/AdminSmsCampaignCRUDController.php
  src/Entity/SmsCampaign/SmsCampaign.php
  src/OvhCloud/Driver.php
  src/SmsCampaign/Statistics.php
  templates/admin/sms_campaign/CRUD/show__stats.html.twig
Labels: Ready for code review

#6569 [EM-1662] add satisfaction data on campaign history endpoint
  features/api/phoning_campaigns.feature
  src/Entity/Phoning/CampaignHistory.php
Labels: Ready for code review

#6572 Expand address payload
  config/packages/doctrine.yaml
  features/api/pap_address.feature
  src/Doctrine/Hydrators/PapAddressHydrator.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/Floor.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6571 Add timestamp for administrator export history
  migrations/Version20211122235636.php
  src/Entity/Reporting/AdministratorExportHistory.php
  src/EventListener/AdministratorExportHistoryListener.php
Labels: Ready for code review

#6577 [Config] add missing var env for maintenance mode
  .env
Labels: Ready for code review

#6559 [EM-1247] phoning campaign survey answers
  features/api/phoning_campaigns.feature
  features/api/surveys.feature
  src/Controller/Api/Phoning/GetPhoningCampaignSurveyRepliesController.php
  src/DataFixtures/ORM/LoadJecouteDataAnswerData.php
  src/DataFixtures/ORM/LoadJecouteQuestionData.php
  src/DataFixtures/ORM/LoadJecouteSurveyData.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Ready for code review

#6578 [API] Fix news
  features/api/jecoute_news.feature
  src/Api/Serializer/JecouteNewsGroupsContextBuilder.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
Labels: Ready for code review

#6581 [PHP] Update Symfony to 4.4.34
  composer.lock
Labels: Ready for code review, dependencies, composer

#6580 Rename app DataCorner to Je mengage
  public/images/data-corner/sidebar-data-corner.png
  templates/candidate/_data-corner-modal.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#6579 [EM-1249] add global kpi endpoint on phoning campaign
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/GetPhoningCampaignsKpiController.php
  src/Entity/Phoning/Campaign.php
  src/Repository/Phoning/CampaignRepository.php
Labels: Ready for code review

#6582 Fix edit news without 'global' information
  features/api/jecoute_news.feature
  src/Admin/AbstractAdmin.php
  src/Admin/Jecoute/NewsAdmin.php
  src/Entity/Jecoute/News.php
  src/Validator/Jecoute/NewsTargetValidator.php
Labels: Ready for code review

#6575 [Dev] Fix behat tests on dev
  behat.yml.dist
Labels: Ready for code review

#6585 [PAP] expose Building stats on Address endpoint
  Makefile
  features/api/pap_address.feature
  migrations/Version20211125000708.php
  src/Controller/Api/Pap/AddressNearController.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/BuildingBlockStatistics.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/CampaignStatisticsTrait.php
  src/Entity/Pap/Floor.php
  src/Form/DeleteEntityType.php
  src/Normalizer/BuildingStatusNormalizer.php
  src/Repository/Pap/AddressRepository.php
  src/Twig/FormExtension.php
  src/Twig/FormRuntime.php
  templates/candidate/_data-corner-modal.html.twig
Labels: Ready for code review

#6587 [EM-1706] Optimize survey reply export
  src/Exporter/SurveyExporter.php
  src/Repository/Jecoute/JemarcheDataSurveyRepository.php
  src/Repository/Jecoute/SurveyQuestionRepository.php
Labels: Ready for code review

#6584 [EM-1675] add phoning campaign answers export endpoint
  src/Controller/Api/Phoning/GetPhoningCampaignSurveyRepliesController.php
  src/Entity/Phoning/Campaign.php
  src/Exporter/PhoningCampaignSurveyRepliesExporter.php
  src/Repository/Jecoute/DataSurveyRepository.php
  tests/Controller/Api/ExportPhoningCampaignSurveyAnswersControllerTest.php
Labels: Ready for code review

#6589 [Phoning] Check allowed action before sending summary email
  src/Phoning/Handler/SendAdherentActionSummaryCommandHandler.php
Labels: Bug, Ready for code review

#6590 [Address] add postalCode and votersCount fields
  features/api/pap_address.feature
  migrations/Version20211126151434.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/BuildingStatistics.php
  src/Pap/BuildingStatusEnum.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6592 [EM-1671] add author postal code on data survey entity
  migrations/Version20211126172212.php
  src/Controller/Api/Jecoute/JemarcheDataSurveyReplyController.php
  src/Controller/Api/Phoning/CampaignHistoryReplyController.php
  src/DataFixtures/ORM/LoadJemarcheDataSurveyData.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/Jecoute/DataSurvey.php
Labels: Ready for code review

#6591 [SmsAdmin] improve stats block
  src/SmsCampaign/Statistics.php
  templates/admin/sms_campaign/CRUD/show__stats.html.twig
Labels: Ready for code review

#6576 [API][PAP] Add close-open building endpoints
  features/api/pap_address.feature
  migrations/Version20211126130535.php
  src/Controller/Api/Pap/BuildingEventController.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/BuildingBlockStatistics.php
  src/Entity/Pap/BuildingEvent.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/CampaignStatisticsInterface.php
  src/Entity/Pap/CampaignStatisticsOwnerInterface.php
  src/Entity/Pap/CampaignStatisticsTrait.php
  src/Entity/Pap/Floor.php
  src/Entity/Pap/FloorStatistics.php
  src/Entity/Pap/StatusTrait.php
  src/Normalizer/PapCampaignFromUuidDenormalizer.php
  src/Pap/BuildingEventActionEnum.php
  src/Pap/BuildingEventTypeEnum.php
  src/Pap/Command/BuildingEventCommand.php
  src/Pap/Handler/BuildingEventCommandHandler.php
  src/Repository/Pap/BuildingEventRepository.php
  src/Repository/Pap/BuildingRepository.php
  tests/Controller/Api/Pap/BuildingEventControllerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#6593 [API] Add info to adherent messages list
  features/api/adherent_messages.feature
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
Labels: Ready for code review

#6583 [PAP][API] Create a building block and floor while creating/updating a campaign history
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Pap/CampaignStatisticsInterface.php
  src/Entity/Pap/StatusTrait.php
  src/Pap/Api/Listener/PostWritePapCampaignHistoryListener.php
  src/Pap/CampaignHistoryManager.php
  src/Pap/Command/CreateBuildingPartsCommand.php
  src/Pap/Handler/CreateBuildingPartsCommandHandler.php
  src/Repository/Pap/CampaignHistoryRepository.php
  tests/Pap/CampaignHistoryManagerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#6597 [Admin] Fix edit zones of Phoning campaign
  config/packages/security.yaml
Labels: Ready for code review

#6596 [Admin] Filter events by inactive event category
  src/Admin/EventAdmin.php
Labels: Ready for code review

#6595 [EM-1689] add calling average time on get one phoning campaign endpoint
  config/packages/doctrine.yaml
  features/api/phoning_campaigns.feature
  migrations/Version20211130023420.php
  src/Entity/Phoning/Campaign.php
  src/Normalizer/CampaignNormalizer.php
  src/Repository/Phoning/CampaignHistoryRepository.php
Labels: Ready for code review

#6600 [PAP] add Vote place API endpoint
  features/api/pap_address.feature
  features/api/pap_vote_places.feature
  migrations/Version20211126020536.php
  migrations/Version20211130010431.php
  src/Controller/Api/Pap/AddressNearController.php
  src/Controller/Api/Pap/GetNearPointsController.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/VotePlaceRepository.php
Labels: Ready for code review

#6601 [Admin] Fix creation of Phoning campaign
  src/Admin/Jecoute/NewsAdmin.php
  src/Admin/Phoning/CampaignAdmin.php
  tests/Admin/Phoning/CampaignAdminTest.php
Labels: Bug, Ready for code review

#6604 Add phone verified at column to Adherent
  migrations/Version20211130163308.php
  src/Entity/Adherent.php
Labels: Ready for code review

#6605 Remove prefix from title on update
  features/api/jecoute_news.feature
  src/Jecoute/NewsTitlePrefix.php
  src/Normalizer/JecouteNewsNormalizer.php
Labels: Ready for code review
