Repository parti-renaissance/espace-adherent, pull requests merged in 2021-04, with the labels that each got.

#5508 [Cause] Add status field and use it on API
  config/services/services.xml
  features/api/causes.feature
  migrations/Version20210401105220.php
  src/Api/Doctrine/CauseExtension.php
  src/Api/Doctrine/CoalitionEventExtension.php
  src/Api/Doctrine/CoalitionExtension.php
  src/Api/Doctrine/ConsultationExtension.php
  src/Api/Doctrine/GeoZoneExtension.php
  src/Api/Doctrine/IdeaExtension.php
  src/Api/Doctrine/JecouteNewsExtension.php
  src/Api/Doctrine/MunicipalEventExtension.php
  src/Api/Doctrine/MyIdeaContributionExtension.php
  src/Api/Doctrine/VisibleStatusesExtension.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
  symfony.lock
Labels: Ready for code review

#5505 [API] Create a password
  features/api/user.feature
  src/AdherentProfile/Password.php
  src/Controller/Api/UserController.php
  src/DataFixtures/ORM/LoadUserData.php
  src/Entity/AdherentToken.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5512 [Cause] attach creator of cause as the first cause follower
  features/api/causes.feature
  src/Coalition/Api/Listener/PostCauseCreationListener.php
Labels: Ready for code review

#5514 [PHP] Remove unused Doctrine cache bundle
  composer.json
  composer.lock
  symfony.lock
Labels: Ready for code review, dependencies

#5484 Add an endpoint returning a national or a local poll
  features/api/polls.feature
  src/Controller/Api/PollController.php
  src/DataFixtures/ORM/LoadPollData.php
  src/Entity/Poll/LocalPoll.php
  src/Entity/Poll/NationalPoll.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Poll/LocalPollRepository.php
  src/Repository/Poll/NationalPollRepository.php
Labels: Ready for code review

#5516 [Cause] allow update cause image
  src/Api/DTO/ImageContent.php
  src/Controller/Api/Coalition/CauseController.php
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5518 [Config] remove controller yaml config
  config/services.yaml
  config/services/controller.yaml
  symfony.lock
Labels: Ready for code review

#5499 [Coalition] Send account creation confirmation message
  .env
  config/services.yaml
  config/services/platform.xml
  src/Mailer/Message/Coalition/CoalitionUserAccountConfirmationMessage.php
  src/Membership/EventListener/CoalitionUserCreateSubscriber.php
  src/Membership/MembershipSourceEnum.php
Labels: Work in progress

#5521 [Coalition] Add coalition oauth login page
  .env
  config/packages/twig.yaml
  config/routes.yaml
  config/services.yaml
  config/services/services.xml
  features/redirect.feature
  src/Controller/EnMarche/Security/SecurityController.php
  src/Security/EventListener/LastVisitedPageOnGetListener.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/base_print.html.twig
  templates/citizen_project/cover_image.html.twig
  templates/citizen_project/tract_pdf.html.twig
  templates/legislative_candidate/platform.html.twig
  templates/oauth/base.html.twig
  templates/security/coalition_user_login.html.twig
Labels: Ready for code review

#5523 Store coalition & cause subscriptions
  features/api/membership.feature
  features/api/profile.feature
  migrations/Version20210406102412.php
  src/Entity/Adherent.php
  src/Membership/AdherentFactory.php
  src/Membership/LightMembershipRequest.php
Labels: Ready for code review

#5524 [Coalition] update sender email info
  .env
  features/api/membership.feature
  src/Mailer/Message/Coalition/AbstractCoalitionMessage.php
  src/Mailer/Message/Coalition/CoalitionUserAccountConfirmationMessage.php
Labels: Ready for code review

#5525 [Coalition] Activate user after password validation
  config/services/services.xml
  src/Controller/Api/UserController.php
  src/Exception/AccountNotValidatedException.php
  src/Membership/AdherentResetPasswordHandler.php
  src/Security/LoginFormAuthenticator.php
  src/Security/UserChecker.php
  translations/messages.fr.yml
Labels: Bug, Ready for code review

#5526 [Coalition] fix inscription url
  src/Controller/EnMarche/Security/SecurityController.php
  templates/security/coalition_user_login.html.twig
Labels: Bug, Ready for code review

#5528 [Coalition] Add transactional emails
  features/api/causes.feature
  src/Coalition/Api/Listener/PostCauseCreationListener.php
  src/Coalition/Api/Listener/PostCauseFollowerCreationListener.php
  src/Coalition/CoalitionUrlGenerator.php
  src/Coalition/MessageNotifier.php
  src/Controller/Api/Coalition/CauseAnonymousFollowerController.php
  src/Entity/AbstractFollower.php
  src/Mailer/Message/Coalition/CauseCreationConfirmationMessage.php
  src/Mailer/Message/Coalition/CauseFollowerAnonymousConfirmationMessage.php
  src/Mailer/Message/Coalition/CauseFollowerConfirmationMessage.php
Labels: Ready for code review

#5529 [Coalition][Admin] Add coalition moderator role + Coalition space
  front/style/layout/_avatar.scss
  migrations/Version20210402115202.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Coalition/Filter/CauseFilter.php
  src/Controller/EnMarche/Coalition/CausesController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/Coalition.php
  src/Entity/Coalition/CoalitionModeratorRoleAssociation.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Form/Coalition/CauseFilterType.php
  src/Form/EventListener/CoalitionModeratorRoleListener.php
  src/Repository/Coalition/CauseRepository.php
  templates/adherent/_list_my_sections.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/coalition/_layout.html.twig
  templates/coalition/_sidebar.html.twig
  templates/coalition/causes_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5530 Send email after Cause approval
  src/Coalition/MessageNotifier.php
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Mailer/Message/Coalition/CauseApprovalMessage.php
Labels: Ready for code review

#5531 Fix space bar display if adherent has only coalition moderator role
  templates/adherent_space/_layout.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#5534 [Algolia] use new indexes for events/articles on front
  front/components/AlgoliaSearch.js
  src/Normalizer/Indexer/ArticleNormalizer.php
Labels: Ready for code review

#5535 [Event] add mode column with 2 values: online/meeting
  features/api/coalition_events.feature
  migrations/Version20210407184126.php
  src/Entity/Event/BaseEvent.php
  tests/Controller/Api/Event/CoalitionEventControllerTest.php
Labels: Ready for code review

#5536 [Event/API] expose more details of each event
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/BaseEventCategory.php
  src/Entity/Event/CitizenAction.php
  src/Entity/Event/CoalitionEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Event/EventCategory.php
  src/Entity/Event/InstitutionalEvent.php
  src/Normalizer/EventUserRegistrationNormalizer.php
Labels: Ready for code review

#5537 Allow PUT on causes
  features/api/causes.feature
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5540 [VotingPlatform] fix cronjob for starting new election type - nationa…
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/VotingPlatform/ElectionEntity.php
  src/VotingPlatform/Election/RedirectManager.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  templates/admin/designation/list_zone.html.twig
Labels: Ready for code review

#5539 [Coalition space] Batch actions
  front/app.js
  front/components/BatchActionsWidget.js
  front/pages/batch_actions.js
  src/Coalition/Filter/CauseFilter.php
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Entity/Coalition/Cause.php
  src/Repository/Coalition/CauseRepository.php
  templates/coalition/causes_list.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#5541 [EM-584][EM-588][VotingPlatform] update CSS theme of national council
  front/listeners/em-modal.js
  front/style/voting-platform/_layout.scss
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/VotingPlatform/Designation/Designation.php
  templates/filesystem/list.html.twig
  templates/voting_platform/_layout_national_council.html.twig
  templates/voting_platform/index.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5542 [Coalition] Add statistics endpoint
  features/api/causes.feature
  src/Controller/Api/Coalition/CauseController.php
  src/Repository/Coalition/CauseRepository.php
Labels: Ready for code review

#5543 Add geo informations to survey answers
  features/api/surveys.feature
  migrations/Version20210409110544.php
  src/Entity/Jecoute/DataSurvey.php
  src/Form/Jecoute/DataSurveyFormType.php
Labels: Ready for code review

#5549 [Coalition space] Revert and fix filter
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Form/Coalition/CauseFilterType.php
  templates/coalition/causes_list.html.twig
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5550 [Coalitions][API] Add last name to causes
  features/api/causes.feature
  src/Entity/EntityPersonNameTrait.php
Labels: Ready for code review

#5552 Change endpoint returning a national or a local poll
  features/api/polls.feature
  src/Controller/Api/PollController.php
  src/Entity/Poll/NationalPoll.php
Labels: Ready for code review

#5554 [PHP] Update `php-amqplib/rabbitmq-bundle` to 1.15
  composer.lock
Labels: Ready for code review

#5553 [Admin] Fix national poll creation
  src/Admin/Poll/NationalPollAdmin.php
  src/Entity/Poll/NationalPoll.php
Labels: Ready for code review

#5544 [API] add a proxy endpoint for internal API application
  config/services.yaml
  config/services/http_client.yaml
  migrations/Version20210408015453.php
  src/Controller/Api/InternalApiProxyController.php
  src/DataFixtures/ORM/LoadInternalApiApplicationData.php
  src/DataFixtures/ORM/LoadOAuthTokenData.php
  src/Entity/InternalApiApplication.php
  src/Repository/InternalApiApplicationRepository.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
  tests/Controller/ApiControllerTestTrait.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5547 [Event/API] enable some filters
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5555 Fix survey answer creation
  src/Jecoute/DataSurveyAnswerHandler.php
Labels: Bug, Ready for code review

#5557 [CodeQuality] replace Intl usage by Countries
  src/Assessor/AssessorRequestExporter.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/EntityNullablePostAddressTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/MemberSummary/Language.php
  src/Entity/NewsletterSubscription.php
  src/Entity/NullablePostAddress.php
  src/Entity/PostAddress.php
  src/Intl/UnitedNationsBundle.php
  src/Mailer/Message/AssessorRequestAssociateMessage.php
  src/Mailer/Message/AssessorRequestConfirmationMessage.php
  src/Twig/CountryExtension.php
Labels: Ready for code review

#5559 [Coalitions][API] Order causes by followers count
  features/api/causes.feature
  migrations/Version20210412143031.php
  src/Coalition/Api/Listener/AddCauseFollowerListener.php
  src/Coalition/Api/Listener/PostCauseCreationListener.php
  src/Coalition/CauseFollowerChangeEvent.php
  src/Controller/Api/Coalition/CauseAnonymousFollowerController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5560 Add endpoint to list countries
  features/api/intl.feature
  src/Controller/Api/IntlController.php
Labels: Ready for code review

#5556 [Event/API] expose organizer and committee data
  features/api/coalition_events.feature
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Entity/EntityExposedObjectTrait.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/ExposedObjectInterface.php
  src/Entity/PostAddress.php
  src/Normalizer/ExposedObjectNormalizer.php
Labels: Ready for code review

#5561 [PHP] Add google storage lib as direct dependence
  composer.json
  composer.lock
Labels: Ready for code review

#5558 Add adherent boolean to profile
  features/api/profile.feature
  src/Entity/Adherent.php
Labels: Ready for code review

#5563 [Cause] check image before delete it
  src/Image/ImageManager.php
  src/Storage/ImageStorage.php
Labels: Bug, Ready for code review

#5568 Check country code before call `Countries::getName`
  src/Entity/EntityNullablePostAddressTrait.php
  src/Entity/NullablePostAddress.php
  src/Entity/PostAddress.php
Labels: Bug, Ready for code review

#5569 Add command to resend CoTerr convocation
  src/Command/VotingPlatform/SendElectionConvocationCommand.php
Labels: Ready for code review

#5564 [Event/API] add event subscribe endpoint
  config/services.yaml
  src/Controller/Api/EventSubscribeController.php
  src/Controller/EnMarche/AdherentMessage/CommonMessageController.php
  src/Entity/Event/BaseEvent.php
  tests/Controller/Api/Event/EventSubscribeControllerTest.php
  tests/Controller/ApiControllerTestTrait.php
Labels: Ready for code review

#5573 [Event/API] Add finishAt filter for GET collection
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5571 Add logout route to calitions host
  config/routes.yaml
  src/Controller/EnMarche/Security/SecurityController.php
Labels: Ready for code review

#5572 [Event/API] Add subscribedOnly filter for GET collection
  config/services/services.xml
  src/Api/Filter/ContributorsCountFilter.php
  src/Api/Filter/IdeaStatusFilter.php
  src/Api/Filter/JecouteNewsZipCodeFilter.php
  src/Api/Filter/MySubscribedEventsFilter.php
  src/Api/Filter/OrTextSearchFilter.php
  src/Entity/Event/BaseEvent.php
  src/Entity/IdeasWorkshop/Idea.php
  src/Entity/Jecoute/News.php
  tests/Controller/Api/Event/EventsControllerTest.php
Labels: Ready for code review

#5570 Add coalitionsCguAccepted bool
  features/api/profile.feature
  migrations/Version20210415123607.php
  src/AdherentProfile/AdherentProfile.php
  src/Entity/Adherent.php
Labels: Ready for code review

#5574 [API][Coalitions] Add quick actions
  features/api/quick_actions.feature
  features/bootstrap/RestContext.php
  migrations/Version20210414133657.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/DataFixtures/ORM/LoadQuickActionData.php
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/QuickAction.php
Labels: Ready for code review

#5562 [CRM/API] add CRUD endpoints for Email Templates
  config/services/services.xml
  features/api/email_templates.feature
  migrations/Version20210414110430.php
  src/Api/Doctrine/EmailTemplateExtension.php
  src/DataFixtures/ORM/LoadEmailTemplateData.php
  src/Entity/EmailTemplate/EmailTemplate.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityTimestampableTrait.php
Labels: Ready for code review

#5575 [Event/API] Add order filter for GET collection
  src/Api/Filter/OrderEventsBySubscriptionsFilter.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5565 [CodeQuality] Update ESLint packages
  .eslintrc.js
  front/components/AdherentCommitteeList.js
  front/components/AlgoliaSearch.js
  front/components/AmountChooser.js
  front/components/BatchActionsWidget.js
  front/components/CandidaciesListWidget.js
  front/components/CommitteeCandidacyWidget.js
  front/components/DataGrid.js
  front/components/DonationAmountChooser.js
  front/components/FacebookPictureChooser.js
  front/components/MessageStatusLoader.js
  front/components/Modal.js
  front/components/NationalCouncilCandidacyWidget.js
  front/components/TerritorialCouncilCandidacyWidget.js
  front/components/UserListDefinitionWidget.js
  front/components/UserSegmentWidget.js
  front/components/VoteCommitteeWidget.js
  front/listeners/amount-chooser.js
  front/listeners/confirm-modal.js
  front/listeners/em-datetime-picker.js
  front/listeners/em-modal.js
  front/pages/application_request.js
  front/pages/board_member_list.js
  front/pages/citizen_project_image_generator.js
  front/pages/committees_map.js
  front/pages/jemarche.js
  front/pages/profile_update.js
  front/utils/dom.js
  front/utils/text.js
  front/validator/formValidator.js
  package.json
  templates/jemarche/action.html.twig
  webpack.development.js
  yarn.lock
Labels: Ready for code review

#5580 [API] add user uuid in the proxy forward request headers
  src/Controller/Api/InternalApiProxyController.php
Labels: Ready for code review

#5581 [EM-646][EM-656][Event/API] Enrich Event data payload
  features/api/coalition_events.feature
  src/Api/Filter/MySubscribedEventsFilter.php
  src/Api/Filter/OrderEventsBySubscriptionsFilter.php
  src/Controller/Api/EventSubscribeController.php
  src/Entity/Committee.php
  src/Entity/EntityExposedObjectTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/BaseEventCategory.php
  src/Entity/Event/CitizenAction.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Event/EventCategory.php
  src/Entity/ExposedObjectInterface.php
  src/Normalizer/ExposedObjectNormalizer.php
Labels: Ready for code review

#5582 [Coalitions][API] Follow a coalition when follow a cause
  features/api/causes.feature
  src/Coalition/Api/Listener/CoalitionFollowerPostCauseFollowerCreationListener.php
  src/Coalition/Api/Listener/NotificationPostCauseFollowerCreationListener.php
  src/Coalition/Api/Listener/PostCauseCreationListener.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/EntityFollowersTrait.php
Labels: Ready for code review

#5583 [Event/API] Fix finishAt filter
  src/Entity/Event/BaseEvent.php
Labels: Bug, Ready for code review

#5585 [Coalitions][API] Get followed coalitions
  features/api/coalitions.feature
  src/Controller/Api/Coalition/CoalitionController.php
  src/Entity/Coalition/Coalition.php
  src/Entity/FollowedInterface.php
  src/Repository/Coalition/CoalitionRepository.php
Labels: Ready for code review

#5584 [OAuth] Add RoleBased check to AuthGrant flow
  config/packages/security.yaml
  migrations/Version20210409110544.php
  migrations/Version20210416154229.php
  src/Admin/OAuth/ClientAdmin.php
  src/Controller/OAuth/OAuthServerController.php
  src/DataFixtures/ORM/LoadClientData.php
  src/Entity/OAuth/Client.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
Labels: Ready for code review

#5587 [Event/API] replace {id} by {uuid} for fixing subscribe route
  src/Entity/Event/BaseEvent.php
Labels: Bug, Ready for code review

#5586 [EM-553][Coalition/API] retrieve cause by uuid or slug
  features/api/causes.feature
  src/Controller/Api/Coalition/RetrieveCauseController.php
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5590 [VotingPlatform] Fix designation type check on close mandate command
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
Labels: Bug, Ready for code review

#5588 [Coalitions][API] Add causes followers + youtubeId field
  features/api/coalitions.feature
  migrations/Version20210419144627.php
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/Entity/Coalition/CauseFollower.php
  src/Entity/Coalition/Coalition.php
  src/Entity/Coalition/CoalitionFollower.php
  src/Normalizer/CoalitionNormalizer.php
  src/Repository/Coalition/CauseFollowerRepository.php
  translations/validators.fr.yml
Labels: Ready for code review

#5591 [Coalitions] Add cause edit page
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Form/Coalition/CauseType.php
  templates/coalition/_sidebar.html.twig
  templates/coalition/causes_list.html.twig
  templates/coalition/edit_cause.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5592 [Coalitions] Change causes order
  src/Coalition/Filter/CauseFilter.php
  src/Controller/EnMarche/Coalition/CausesController.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5596 [Message/API] allow create AdherentMessage on API
  config/services/services.xml
  migrations/Version20210420154030.php
  src/AdherentMessage/AdherentMessageFactory.php
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/Api/Doctrine/AuthoredItemsCollectionExtension.php
  src/Controller/Api/GetAdherentMessageStatusController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Entity/AuthoredItemsCollectionInterface.php
  src/Entity/EmailTemplate/EmailTemplate.php
  src/Entity/EntityIdentityTrait.php
  src/Normalizer/AdherentMessageDenormalizer.php
  src/Security/Voter/AdherentMessageTypeVoter.php
  src/Validator/ValidAuthorRoleMessageType.php
  src/Validator/ValidAuthorRoleMessageTypeValidator.php
Labels: Ready for code review

#5598 [Message/API] attach default filter for Candidate message
  src/AdherentMessage/Api/Listener/PreCreateAdherentMessageListener.php
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
Labels: Ready for code review

#5600 [EM-590][PROFILE/API] generate access token when resetting user password with…
  features/api/user.feature
  src/Controller/Api/UserController.php
  src/DataFixtures/ORM/LoadUserData.php
  src/OAuth/OAuthTokenGenerator.php
Labels: Ready for code review

#5601 [PROXY/API] fix internal app proxy when sub-request throw an client e…
  src/Controller/Api/InternalApiProxyController.php
Labels: Ready for code review

#5602 [API] fix email template author persist
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AuthoredItemsCollectionInterface.php
Labels: Ready for code review

#5603 [Message/API] add send action
  src/AdherentMessage/AdherentMessageManager.php
  src/Controller/Api/AdherentMessage/GetAdherentMessageStatusController.php
  src/Controller/Api/AdherentMessage/SendAdherentMessageController.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#5605 Fix creation DataSurvey without email + access to events via API
  src/Entity/Event/BaseEvent.php
  src/Jecoute/DataSurveyAnswerHandler.php
Labels: Bug, Ready for code review

#5606 Attach MessageRedactor role to candidate
  src/Entity/Adherent.php
  src/Security/Voter/FileUploadVoter.php
  tests/Security/Voter/FileUploadVoterTest.php
  tests/Security/Voter/MembershipRegistrationVoterTest.php
Labels: Bug, Ready for code review

#5608 [CommitteeElection] update vote rule and ignore vote in refused commi…
  src/Repository/CommitteeRepository.php
Labels: Ready for code review

#5604 [Coalitions][API] Create and edit cause/coalition events
  features/api/coalition_events.feature
  features/api/events.feature
  features/bootstrap/SyncWithAPIContext.php
  src/Admin/EventAdmin.php
  src/Coalition/Api/Listener/PostEventEditListener.php
  src/Command/ApiScheduleEventCreationCommand.php
  src/DataFixtures/ORM/LoadEventCategoryData.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CauseEvent.php
  src/Entity/Event/CoalitionEvent.php
  src/Entity/Event/EventCategory.php
  src/Entity/PostAddress.php
  src/Event/CommitteeEventEvent.php
  src/Event/EventCanceledHandler.php
  src/Event/EventCommandHandler.php
  src/Event/EventEvent.php
  src/Event/EventListener/EventSubscriber.php
  src/Event/EventMessageNotifier.php
  src/Event/EventRegistrationCommandHandler.php
  src/EventListener/SendEventUpdateNotificationListener.php
  src/Normalizer/AddressDenormalizer.php
  src/Normalizer/EventDenormalizer.php
  tests/Controller/Api/Event/CoalitionEventControllerTest.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5609 [Profil/API] fix empty postal code on address
  src/Entity/NullablePostAddress.php
  src/Entity/PostAddress.php
Labels: Bug, Ready for code review

#5607 [API] Add event categories list
  features/api/coalition_events.feature
  features/api/event_categories.feature
  src/Api/Doctrine/BaseEventCategoryExtension.php
  src/Coalition/Api/Listener/PostEventEditListener.php
  src/Entity/Event/BaseEventCategory.php
  src/Entity/Event/EventCategory.php
Labels: Ready for code review

#5612 Enable CORS config for deconnexion route
  config/packages/nelmio_cors.yaml
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#5610 [ZONE/API] add postal code serialization on zone read endpoint
  dump/all-geo-zone.sql
  features/api/zones.feature
  migrations/Version20210422112919.php
  src/Entity/Geo/Zone.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5613 [PROXY/API] add a blacklist of unnecessary headers
  src/Controller/Api/InternalApiProxyController.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
Labels: Ready for code review

#5614 [API][Coalitions] Get events of a coalition or a cause
  config/services/services.xml
  features/api/coalition_events.feature
  src/Api/Doctrine/BaseEventExtension.php
Labels: Ready for code review

#5615 Fix events test
  features/api/coalition_events.feature
Labels: Ready for code review

#5616 [Security] Replace IS_AUTHENTICATED_FULLY by IS_AUTHENTICATED_REMEMBERED
  config/packages/security.yaml
  src/Controller/Api/Coalition/CauseController.php
  src/Controller/Api/InternalApiProxyController.php
  src/Controller/Api/MembershipController.php
  src/Controller/Api/ZoneController.php
  src/Controller/EnMarche/CitizenActionController.php
  src/Controller/EnMarche/CitizenProjectController.php
  src/Controller/EnMarche/MembershipController.php
  src/Controller/OAuth/OAuthServerController.php
  src/Entity/Coalition/Cause.php
  src/Form/EventRegistrationType.php
  src/Security/Voter/ReportVoter.php
  src/Validator/UniqueDonationSubscriptionValidator.php
  tests/Security/Voter/ReportVoterTest.php
Labels: Ready for code review

#5617 Change wording for procurations
  features/procuration_proxy.feature
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/election_rounds.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5619 [API][Coalitions] Add cause name filter
  features/api/causes.feature
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5618 [EVENTS/API] update event participant count
  src/Controller/Api/EventSubscribeController.php
Labels: Work in progress

#5621 [API] Return only scheduled and published events
  features/api/events.feature
  src/Api/Doctrine/BaseEventExtension.php
  tests/Controller/Api/Event/EventsControllerTest.php
Labels: Ready for code review

#5620 [API][Coalitions] Add sort to events list
  features/api/causes.feature
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5624 [VotingPlatform] Skip National council election on mandate creation
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
Labels: Ready for code review

#5625 Remove cache for events list
  src/Repository/EventRepository.php
Labels: Ready for code review

#5626 [API] add api endpoint for document upload
  src/Controller/UploadDocumentController.php
Labels: Ready for code review

#5623 [EVENTS/API] add an event image
  src/Controller/Api/Coalition/CauseController.php
  src/Controller/Api/EventImageController.php
  src/Entity/Event/BaseEvent.php
  src/Image/ImageUploadHelper.php
Labels: Ready for code review

#5627 [Coalitions] Add causes export
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Entity/Coalition/Cause.php
  src/Entity/Geo/City.php
  src/Exporter/CausesExporter.php
  src/Repository/Coalition/CauseRepository.php
  templates/coalition/causes_list.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5635 Update cause follower while creating an account
  src/Controller/Api/UserController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Membership/EventListener/NewUserUpdateCoalitionCauseFollowerSubscriber.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#5639 Make some changes in causes export
  src/Entity/Geo/City.php
  src/Exporter/CausesExporter.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5640 Redirect after logout from Coalitions
  config/packages/security.yaml
  config/services/services.xml
  src/Coalition/CoalitionUrlGenerator.php
  src/Security/AuthenticationHandler.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
Labels: Ready for code review

#5642 [EM-711] Revert "Enable CORS config for deconnexion route"
  config/packages/nelmio_cors.yaml
Labels: Ready for code review

#5643 [OAuth] Throw OAuth Exception if refresh token has been revoked
  src/Controller/Api/InternalApiProxyController.php
  src/OAuth/Store/RefreshTokenStore.php
Labels: Bug, Ready for code review

#5644 [Document] Add extension to uploaded filename
  src/Controller/UploadDocumentController.php
  src/Entity/UserDocument.php
Labels: Bug, Ready for code review

#5641 add lint job to github actions
  .circleci/config.yml
  .github/workflows/lint.yml
  config/packages/assets_version.yaml
Labels: Ready for code review

#5645 Create command to add coalition followers
  src/Command/CreateCoalitionFollowerFromCauseFollowerCommand.php
Labels: Ready for code review

#5647 [Hotfix] Replace `class_implements` by `is_a` in AddressDenormalizer
  src/Entity/Adherent.php
  src/Normalizer/AddressDenormalizer.php
Labels: Bug, Ready for code review

#5648 Add events image repository
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5650 [OAuth] Throw OAuth Exception if access token has been revoked
  src/Entity/OAuth/AbstractToken.php
  src/Entity/OAuth/TokenInterface.php
  src/OAuth/Store/AccessTokenStore.php
  src/OAuth/Store/RefreshTokenStore.php
  src/OAuth/Store/TokenStoreTrait.php
Labels: Ready for code review

#5657 add a copy of the assets version file to packages prod folder
  .github/workflows/lint.yml
  .gitignore
  webpack.production.js
Labels: Ready for code review

#5660 Rename reserved `token` route parameter
  src/Controller/EnMarche/NewsletterController.php
  src/Controller/EnMarche/ProcurationController.php
  src/Controller/EnMarche/ProcurationManagerController.php
  src/Newsletter/Listener/SendWelcomeMailSubscriber.php
  src/Procuration/ProcurationProxyMessageFactory.php
  src/Procuration/ProcurationRequestSerializer.php
  templates/procuration_manager/request.html.twig
Labels: Bug, Ready for code review

#5659 Add new role ROLE_CAUSE_AUTHOR
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  src/Entity/AuthoredTrait.php
  src/Entity/Coalition/Cause.php
  src/Repository/AdherentRepository.php
  templates/admin/adherent/statuses.html.twig
  tests/Admin/AdherentAdminTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5662 [AdherentMessage] Add new message type - CoalitionsMessage
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/CoalitionAdherentMessageInterface.php
  src/Entity/AdherentMessage/CoalitionsMessage.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/Listener/SetCampaignReplyToSubscriber.php
Labels: Ready for code review

#5661 add visio url field to events form
  src/CitizenAction/CitizenActionCommand.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CitizenAction.php
  src/Event/BaseEventCommand.php
  src/Event/EventCommand.php
  src/Event/EventFactory.php
  src/Form/BaseEventCommandType.php
  src/InstitutionalEvent/InstitutionalEventCommand.php
  templates/citizen_action/_sidebar.html.twig
  templates/citizen_action_manager/_layout.html.twig
  templates/committee_manager/add_event.html.twig
  templates/event_manager/event_form_layout.html.twig
  templates/events/edit.html.twig
  templates/events/show.html.twig
  templates/institutional_events/create.html.twig
Labels: Ready for code review

#5673 [Coalitions][Mailchimp] Initialize syncro with Mailchimp
  .env
  config/services/mailchimp.yaml
  config/services/services.xml
  src/Coalition/CoalitionContactValueObject.php
  src/Coalition/ContactSourceEnum.php
  src/Command/MailchimpSyncCoalitionsContactsCommand.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Command/CoalitionContactChangeCommand.php
  src/Mailchimp/Synchronisation/Handler/CoalitionContactChangeCommandHandler.php
  src/Mailchimp/Synchronisation/MemberRequest/CoalitionMemberRequestBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Repository/AdherentRepository.php
  src/Repository/Coalition/CauseFollowerRepository.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#5663 [Test] Fix phantom failed OAuth test
  config/services_test.yaml
  features/access_delegation.feature
  features/popup_chart.feature
  features/referent_space.feature
  src/DataFixtures/ORM/LoadClientData.php
  src/OAuth/AuthorizationServerFactory.php
  src/Repository/Jecoute/LocalSurveyRepository.php
Labels: Ready for code review
