Repository parti-renaissance/espace-adherent, pull requests merged in 2021-12, with the labels that each got.

#6603 [OVH] resubscribe number on subscription update
  config/services.yaml
  features/bootstrap/SyncWithAPIContext.php
  src/Admin/AdherentAdmin.php
  src/Controller/EnMarche/UserController.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Mailchimp/Webhook/Handler/AdherentProfileUpdateHandler.php
  src/Mailchimp/Webhook/Handler/AdherentUnsubscribeHandler.php
  src/Membership/MembershipRequestHandler.php
  src/Membership/UserEvent.php
  src/OvhCloud/Driver.php
  src/OvhCloud/Exception/ContactNotFoundException.php
  src/SmsCampaign/Listener/AdherentChangeSmsNotificationListener.php
  src/Subscription/SubscriptionHandler.php
Labels: Ready for code review

#6609 [API] remove cause event from events endpoint
  features/api/events.feature
  src/Api/Doctrine/BaseEventExtension.php
Labels: Ready for code review

#6611 [EM-1663][EM-1739] fix some bugs on teams and surveys
  features/api/teams.feature
  src/Entity/Team/Team.php
  src/Jecoute/JemarcheDataSurveyAnswerHandler.php
  src/Normalizer/SurveyFromUuidDenormalizer.php
  src/Normalizer/TeamFromUuidDenormalizer.php
Labels: Ready for code review

#6610 Remove unused ChangeEmail route
  src/Controller/EnMarche/UserController.php
  src/Form/AdherentChangeEmailType.php
  templates/adherent/_profile_menu.html.twig
  templates/adherent/layout.twig
  templates/adherent/profile-email.html.twig
  templates/certification_request/_layout.html.twig
Labels: Ready for code review

#6613 [PAP] add code to VotePlace entity
  migrations/Version20211202125517.php
  src/Entity/Pap/VotePlace.php
Labels: Ready for code review

#6607 [API][PAP] Change get campaign endpoint for DC
  features/api/pap_campaigns.feature
  src/Entity/Pap/Campaign.php
Labels: Ready for code review

#6614 CD for staging
  .github/workflows/ci-cd.yml
Labels: Ready for code review

#6608 [EM-1677] Update firebase topics on profile update
  src/Adherent/Command/UpdateFirebaseTopicsCommand.php
  src/Adherent/Handler/UpdateFirebaseTopicsCommandHandler.php
  src/AdherentProfile/AdherentProfileHandler.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Firebase/AbstractMessaging.php
  src/JeMarche/NotificationTopicBuilder.php
  src/JeMarche/Subscriber/FirebaseTopicSubscriber.php
  src/Repository/PushTokenRepository.php
  tests/JeMarche/NotificationTopicBuilderTest.php
  tests/Test/Firebase/DummyMessaging.php
Labels: Ready for code review

#6619 [CI] use GH action concurrency config
  .github/workflows/ci-cd.yml
Labels: Ready for code review, github_actions

#6617 [EM-1735] fix referent news creation
  features/api/jecoute_news.feature
  src/Entity/Jecoute/News.php
  src/Jecoute/Api/Listener/PreWriteNewsListener.php
  src/Normalizer/JecouteNewsNormalizer.php
  src/Validator/Jecoute/ReferentNews.php
  src/Validator/Jecoute/ReferentNewsValidator.php
Labels: Ready for code review

#6606 [EM-1725] add jecoute resource entity
  config/packages/security.yaml
  config/services/admin.xml
  features/api/jecoute_resource_links.feature
  migrations/Version20211202191607.php
  src/Admin/Jecoute/ResourceLinkAdmin.php
  src/DataFixtures/ORM/LoadJecouteResourceLinkData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Jecoute/ResourceLink.php
  src/Repository/Jecoute/ResourceLinkRepository.php
Labels: Ready for code review

#6616 [Admin] Add Phoning campaign responses to survey export + optimize survey reply export
  src/Exporter/SurveyExporter.php
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Ready for code review

#6622 [Admin] use text type for redirection urls
  migrations/Version20211203111253.php
  src/Admin/RedirectionAdmin.php
  src/Entity/QrCode.php
  src/Entity/Redirection.php
Labels: Ready for code review

#6620 Add EntityFromUuid denormalizer
  src/Normalizer/AudienceSegmentFromUuidDenormalizer.php
  src/Normalizer/CauseFromUuidDenormalizer.php
  src/Normalizer/EntityFromUuidDenormalizer.php
  src/Normalizer/PapCampaignFromUuidDenormalizer.php
  src/Normalizer/SurveyFromUuidDenormalizer.php
  src/Normalizer/TeamFromUuidDenormalizer.php
  src/Normalizer/ZoneFromUuidDenormalizer.php
Labels: Ready for code review

#6615 Add new adherent role - national communication
  features/api/scopes.feature
  migrations/Version20211202151633.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/Adherent.php
  src/Scope/Generator/NationalCommunicationScopeGenerator.php
  src/Scope/ScopeEnum.php
  templates/admin/adherent/statuses.html.twig
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#6602 [API][PAP] Change survey config endpoint
  features/api/pap_campaigns.feature
  migrations/Version20211203112333.php
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/Entity/Jecoute/DataSurveyAwareTrait.php
  src/Entity/Jecoute/JemarcheDataSurvey.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Phoning/CampaignHistory.php
  src/Pap/CampaignHistoryVoterStatusEnum.php
Labels: Ready for code review

#6612 [API][PAP] Create/edit campaign
  features/api/pap_campaigns.feature
  src/Entity/EntityIdentityTrait.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/Campaign.php
Labels: Work in progress

#6625 [API] validate Team addMember payload
  features/api/teams.feature
  src/Api/DTO/AdherentUuid.php
  src/Controller/Api/Team/AddTeamMembersController.php
  src/Team/TeamMemberManagementHandler.php
Labels: Ready for code review

#6626 [EM-1756] delete message endpoint
  features/api/adherent_messages.feature
  src/DataFixtures/ORM/LoadAdherentMessageData.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#6627 [EM-1755] add source in payload
  features/api/adherent_messages.feature
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#6628 [Algolia] Initialize new index for JeMengage timeline feeds
  config/packages/algolia_search.yaml
  config/settings/algolia_search/jemengage_timeline_feed-settings.json
  migrations/Version20211206115819.php
  src/Entity/Algolia/AlgoliaJeMengageTimelineFeed.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/Campaign.php
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  src/Normalizer/Indexer/PapCampaignNormalizer.php
  src/Normalizer/Indexer/SurveyNormalizer.php
Labels: Ready for code review

#6632 Fix floor creation and change status + change naming
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/Pap/CampaignHistoryManager.php
  src/Pap/Handler/BuildingEventCommandHandler.php
Labels: Ready for code review

#6630 Update CI/CD badge
  README.md
Labels: Ready for code review

#6635 Add new measures on ChezVous
  src/ChezVous/Measure/Apprentissage.php
  src/ChezVous/Measure/DevoirsFaits.php
  src/ChezVous/Measure/EntreprisesAideesCovid.php
  src/ChezVous/Measure/FranceRelance.php
  src/ChezVous/Measure/MaPrimeRenov.php
  src/ChezVous/Measure/MaisonDeSante.php
  src/ChezVous/MeasureChoiceLoader.php
  src/Command/ChezVous/ImportMeasuresCommand.php
  src/DataFixtures/ORM/LoadChezVousData.php
  src/DataFixtures/ORM/LoadChezVousMeasureTypeData.php
  translations/forms.fr.yml
Labels: Ready for code review

#6637 [EM-1783] add campaign uuid filter on phoning campaign history and ad…
  features/api/phoning_campaigns.feature
  src/Entity/Adherent.php
  src/Entity/Phoning/CampaignHistory.php
Labels: Ready for code review

#6631 [API][PAP] Add doors and survey number to floor info
  features/api/pap_address.feature
  migrations/Version20211206110133.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Pap/CampaignStatisticsOwnerInterface.php
  src/Entity/Pap/Floor.php
  src/Entity/Pap/FloorStatistics.php
  src/Normalizer/Pap/BuildingBlockNormalizer.php
  src/Normalizer/Pap/BuildingFloorNormalizer.php
  src/Normalizer/Pap/PapAddressNormalizer.php
  src/Pap/BuildingStatisticsManager.php
  src/Pap/CampaignHistoryManager.php
  src/Pap/Command/UpdateStatsCommand.php
  src/Pap/Handler/BuildingEventCommandHandler.php
  src/Pap/Handler/CreateBuildingPartsCommandHandler.php
  src/Pap/Handler/UpdateStatsCommandHandler.php
  src/Repository/Jecoute/DataSurveyRepository.php
  src/Repository/Pap/CampaignHistoryRepository.php
  src/Repository/Pap/FloorRepository.php
  tests/Pap/CampaignHistoryManagerTest.php
Labels: Ready for code review

#6640 Add Github to social links
  templates/components/_footer.html.twig
Labels: Ready for code review

#6648 [RegistrationFlow] flush after each committee following
  src/Committee/CommitteeManager.php
Labels: Bug, Ready for code review

#6647 [EM-1791] change on delete action on phoning campaign history when ad…
  features/api/phoning_campaigns.feature
  migrations/Version20211209142923.php
  src/DataFixtures/ORM/LoadJecouteDataAnswerData.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/Phoning/CampaignHistory.php
  src/Exporter/PhoningCampaignSurveyRepliesExporter.php
Labels: Ready for code review

#6646 [API][PAP][Admin] Add PAP user option to access PAP functionalities
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  migrations/Version20211209114932.php
  src/Adherent/AdherentRoleEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/Controller/Api/Pap/BuildingEventController.php
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/Controller/Api/Pap/GetPapCampaignTutorialController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/BuildingBlock.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignHistory.php
  translations/messages.fr.yml
Labels: Ready for code review

#6652 [API][PAP] Add building history endpoint
  features/api/pap_address.feature
  src/Controller/Api/Pap/BuildingHistoryController.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/CampaignHistory.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6655 [Quality] Remove Faker deprecations
  config/routes.yaml
  src/Api/DTO/ImageContent.php
  src/Controller/HealthController.php
  src/DataFixtures/ORM/LoadApplicationRequestRunningMateRequestData.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadFacebookVideoData.php
  src/DataFixtures/ORM/LoadJecouteResourceLinkData.php
  src/DataFixtures/ORM/LoadNationalCouncilElectionData.php
  src/DataFixtures/ORM/LoadOrderArticleData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Form/CroppedImageType.php
  tests/Controller/EnMarche/HomeControllerTest.php
Labels: Ready for code review

#6653 Enable OAuth connexion for JeMengage user and disable loginForm
  config/packages/security.yaml
  config/services/services.xml
  features/api/adherents.feature
  features/firewall.feature
  features/oauth.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Membership/AdherentManager.php
  src/Repository/AdherentRepository.php
  src/Security/LoginFormGuardAuthenticator.php
  src/Security/UserChecker.php
  src/Security/UserProvider.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#6654 [API][PAP] Return global KPI
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignsKpiController.php
  src/Entity/Pap/Campaign.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6661 [API][PAP] Add campaign KPI
  features/api/pap_campaigns.feature
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/Campaign.php
  src/Normalizer/Pap/CampaignNormalizer.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6662 [API][PAP] Change survey config endpoint
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
Labels: Ready for code review

#6663 [JeMengage] Improve new membership type creation
  config/packages/security.yaml
  config/services.yaml
  config/services/oauth.xml
  config/services/services.xml
  features/api/membership_jemengage.feature
  src/Coalition/CoalitionUrlGenerator.php
  src/Controller/EnMarche/Security/SecurityController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/JeMengage/App/AppUrlGenerator.php
  src/JeMengage/Timeline/TimelineFeedTypeEnum.php
  src/JeMengageTimelineFeed/JeMengageTimelineFeedEnum.php
  src/Mailer/Message/JeMengage/AbstractJeMengageMessage.php
  src/Mailer/Message/JeMengage/JeMengageResetPasswordMessage.php
  src/Membership/EventListener/UserResetPasswordSubscriber.php
  src/Membership/MembershipRequest/JeMengageMembershipRequest.php
  src/Membership/MembershipRequestHandler.php
  src/Membership/MembershipSourceEnum.php
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  src/Normalizer/Indexer/NewsNormalizer.php
  src/Normalizer/Indexer/PapCampaignNormalizer.php
  src/Normalizer/Indexer/PhoningCampaignNormalizer.php
  src/Normalizer/Indexer/RiposteNormalizer.php
  src/Normalizer/Indexer/SurveyNormalizer.php
  src/OAuth/App/AbstractAppUrlGenerator.php
  src/OAuth/App/AuthAppUrlGeneratorInterface.php
  src/OAuth/App/AuthAppUrlManager.php
  src/OAuth/App/PlatformAuthUrlGenerator.php
  src/Security/AuthenticationHandler.php
  src/Security/LoginFormGuardAuthenticator.php
  src/Security/LogoutSuccessHandler.php
  templates/security/coalitions_forgot_password.html.twig
  templates/security/jemengage_forgot_password.html.twig
Labels: Ready for code review

#6664 [Serializer] Append campaign stats only for GET request
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
  src/Normalizer/Phoning/AppendCampaignStatsNormalizer.php
  src/Normalizer/Phoning/CampaignScoreNormalizer.php
Labels: Ready for code review

#6666 [EM-1763] add endpoint to retrieve timeline feed on algolia
  config/settings/algolia_search/jemengage_timeline_feed-settings.json
  src/Controller/Api/JeMengage/GetTimelineFeedsController.php
  src/Entity/Algolia/AlgoliaJeMengageTimelineFeed.php
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  src/Normalizer/Indexer/NewsNormalizer.php
  src/Normalizer/Indexer/PapCampaignNormalizer.php
  src/Normalizer/Indexer/PhoningCampaignNormalizer.php
  src/Normalizer/Indexer/RiposteNormalizer.php
  src/Normalizer/Indexer/SurveyNormalizer.php
Labels: Work in progress

#6667 [API][PAP] Add questioners scores endpoint
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignQuestionersStatsController.php
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/Repository/AdherentRepository.php
  src/Repository/PaginatorTrait.php
Labels: Ready for code review

#6668 [JME] send validation email on user creation
  features/api/membership_jemengage.feature
  src/Controller/OAuth/OAuthServerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Mailer/Message/JeMengage/JeMengageUserAccountConfirmationMessage.php
  src/Membership/EventListener/SendEmailValidationSubscriber.php
  src/Security/LoginFormGuardAuthenticator.php
  tests/Controller/EnMarche/Security/CoalitionsSecurityControllerTest.php
  tests/Controller/EnMarche/Security/JeMengageSecurityControllerTest.php
Labels: Ready for code review

#6670 [EM-1809] remove info covid
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Work in progress

#6448 [API][PAP] improve survey config payload structure
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/Pap/CampaignHistoryStatusEnum.php
Labels: Ready for code review

#6672 Update Sentry integration with new PHP/JS libs
  .env
  .eslintrc.js
  .github/workflows/ci-cd.yml
  composer.json
  composer.lock
  config/bundles.php
  config/packages/prod/monolog.yaml
  config/packages/prod/sentry.yaml
  config/packages/twig.yaml
  config/services.yaml
  config/services/services.xml
  config/services/system.xml
  config/services_prod.yaml
  front/components/ResubscribeEmail.js
  front/kernel.js
  front/vendor.js
  package.json
  src/Logging/ActivationStrategy.php
  src/Logging/CurrentUserProcessor.php
  src/Logging/SentryHandler.php
  src/Monolog/SentryHandler.php
  templates/base.html.twig
  templates/oauth/base.html.twig
  yarn.lock
Labels: Ready for code review

#6680 [API][PAP] Add closed building block/floor info to building structure
  features/api/pap_address.feature
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Normalizer/Pap/BuildingBlockNormalizer.php
  src/Normalizer/Pap/BuildingFloorNormalizer.php
Labels: Ready for code review

#6684 [EM-1853] add question type to campaign survey replies endpoint
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
Labels: Ready for code review

#6686 [EM-1854] update campaign replies normalizer
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
Labels: Ready for code review

#6685 [JeMengage] add user validation
  config/routes.yaml
  features/api/membership_jemengage.feature
  src/Coalition/CoalitionUrlGenerator.php
  src/Controller/Api/UserController.php
  src/Controller/EnMarche/Security/SecurityController.php
  src/Controller/JeMengage/CreationConfirmationController.php
  src/JeMengage/App/AppUrlGenerator.php
  src/Membership/AdherentResetPasswordHandler.php
  src/Membership/EventListener/SendEmailValidationSubscriber.php
  src/OAuth/App/AuthAppUrlGeneratorInterface.php
  src/OAuth/App/PlatformAuthUrlGenerator.php
  templates/jemengage/user/creation_confirmation.html.twig
  templates/security/jemengage_reset_password.html.twig
  templates/security/platform_reset_password.html.twig
Labels: Ready for code review
