Repository parti-renaissance/espace-adherent, pull requests merged in 2021-06, with the labels that each got.

#5783 [API][Events] Get events where user has a registration
  features/api/events.feature
  src/Controller/Api/EventsController.php
  src/Repository/Event/BaseEventRepository.php
Labels: Ready for code review

#5780 [API][Events] Get event categories with group
  features/api/event_categories.feature
  src/Entity/Event/EventCategory.php
Labels: Ready for code review

#5789 [PHP] Update Symfony to 4.4.25
  composer.lock
Labels: Ready for code review, dependencies

#5792 fix referent sidebar menu
  templates/referent/_sidebar.html.twig
Labels: Ready for code review

#5793 [API][Events] Add public GET events routes
  features/api/events.feature
  front/services/api/ReqwestApiClient.js
  src/Controller/Api/EventsController.php
  src/Entity/Event/BaseEvent.php
  tests/Controller/Api/Event/EventsControllerTest.php
Labels: Ready for code review

#5794 EM-966 Update menu items
  symfony.lock
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#5797 Modify footer
  templates/components/_footer.html.twig
Labels: Ready for code review

#5798 [API][Events] Add group source filter
  features/api/events.feature
  src/Api/Filter/EventsGroupSourceFilter.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5795 fix region migration
  migrations/Version20210526121013.php
Labels: Ready for code review

#5802 [Test] fix failed survey test
  src/Repository/Jecoute/NationalSurveyRepository.php
Labels: Bug, Ready for code review

#5801 [Event/API] add event anonymous subscribe endpoint
  src/Controller/Api/Event/SubscribeAsAdherentController.php
  src/Controller/Api/Event/SubscribeAsAnonymousController.php
  src/Entity/Event/BaseEvent.php
  src/Event/EventRegistrationCommand.php
  src/Validator/EventRegistrationValidator.php
  tests/Controller/Api/Event/SubscribeAsAdherentControllerTest.php
  tests/Controller/Api/Event/SubscribeAsAnonymousControllerTest.php
Labels: Ready for code review

#5791 fix admin campaign zone field
  config/packages/security.yaml
  config/services/admin.xml
  src/Admin/Jecoute/AbstractRegionAdmin.php
  src/Admin/Jecoute/CandidateRegionAdmin.php
  src/Admin/Jecoute/ReferentRegionAdmin.php
Labels: Work in progress

#5796 [EM-959][Events] add specific serialization for coalitions
  features/api/coalition_events.feature
  migrations/Version20210602113034.php
  migrations/Version20210602124821.php
  src/DataFixtures/ORM/LoadCauseEventData.php
  src/DataFixtures/ORM/LoadCoalitionEventData.php
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/Coalition.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CauseEvent.php
  src/Entity/Event/CoalitionEvent.php
  src/Entity/PostAddress.php
  tests/Controller/Api/Event/CoalitionEventControllerTest.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
Labels: Ready for code review

#5805 Add noopener rel property
  front/components/AdherentCommitteeList.js
  front/components/ProgrammaticFoundation/Measure.js
Labels: Ready for code review

#5804 Remove AMP pages
  .circleci/config.yml
  .env
  .gitignore
  Makefile
  composer.json
  composer.lock
  config/routes.yaml
  config/services.yaml
  config/services/admin.xml
  config/services_test.yaml
  docs/1-Installer-le-projet-en-local.md
  features/sitemap.feature
  front/style/amp.scss
  migrations/Version20210603175336.php
  package.json
  src/Admin/Extension/AmpSynchronisedAdminExtension.php
  src/Command/BuildAmpContentCommand.php
  src/Content/ArticleFactory.php
  src/Content/OrderArticleFactory.php
  src/Content/ProposalFactory.php
  src/Controller/Amp/AmpController.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/DataFixtures/ORM/LoadOrderArticleData.php
  src/DataFixtures/ORM/LoadProposalData.php
  src/DataFixtures/content_amp.html
  src/Entity/EntityContentInterface.php
  src/Entity/EntityContentTrait.php
  src/Form/EventListener/AmpSynchronisedListener.php
  src/Sitemap/SitemapFactory.php
  symfony.lock
  templates/amp/_layout.html.twig
  templates/amp/article.html.twig
  templates/amp/order_article.html.twig
  templates/amp/proposal.html.twig
  templates/article/article.html.twig
  templates/base.html.twig
  templates/explainer/article.html.twig
  tests/Admin/ArticleAdminTest.php
  tests/Controller/Amp/AmpControllerTest.php
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Ready for code review

#5809 [API][Events] Add organizer to events list
  features/api/events.feature
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5807 [EM-975] remove canary
  templates/referent/_sidebar.html.twig
Labels: Ready for code review

#5810 [API][Events] Allow user create an event
  features/api/coalition_events.feature
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5808 [EM-960][Events] retrieve a cancelled event
  features/api/events.feature
  src/Api/Doctrine/BaseEventExtension.php
Labels: Ready for code review

#5814 Simplify Event route generation
  src/Twig/EventExtension.php
  src/Twig/EventRuntime.php
  templates/adherent/home.html.twig
  templates/adherent/my_activity_events.html.twig
  templates/adherent_profile/activity/_events.html.twig
  templates/events/_header.html.twig
  templates/events/_layout.html.twig
  templates/events/attend.html.twig
  templates/events/attend_confirmation.html.twig
  templates/events/cancel.html.twig
  templates/events/contact_members.html.twig
  templates/events/contact_old.html.twig
  templates/events/edit.html.twig
  templates/events/members.html.twig
  templates/events/show.html.twig
  templates/search/_events.html.twig
Labels: Ready for code review

#5813 [PHP] Update PHPUnit lib
  composer.json
  composer.lock
  features/bootstrap/JsonContext.php
  front/tests/ContainerTest.js
  front/tests/donation/TaxReturnProviderTest.js
  front/tests/sharer/ShareDialogFactoryTest.js
  package.json
  phpunit.xml.dist
  symfony.lock
  tests/Controller/Api/CommitteesControllerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/Api/UserListDefinition/ElectedRepresentativeUserListDefinitionControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
  tests/Test/Helper/PHPUnitHelper.php
  yarn.lock
Labels: Ready for code review, dependencies

#5830 [API][Events] Allow user to subscribe/unsubscribe to an event
  src/Entity/Event/BaseEvent.php
  tests/Controller/Api/Event/SubscribeAsAdherentControllerTest.php
Labels: Bug, Ready for code review

#5815 [EM-987][Events] add cancellation api endpoint on events
  features/api/events.feature
  src/Controller/Api/Event/CancelEventController.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5834 Link Device to Geo\Zone
  migrations/Version20210608090625.php
  src/DataFixtures/ORM/LoadDeviceData.php
  src/DataFixtures/ORM/LoadPushTokenData.php
  src/Device/DeviceManager.php
  src/Device/DeviceSubscriber.php
  src/Entity/Device.php
  src/Entity/PushToken.php
  src/Geo/ZoneMatcher.php
  src/PushToken/PushTokenSourceEnum.php
  src/Repository/Geo/ZoneRepository.php
  tests/Device/DeviceManagerTest.php
Labels: Ready for code review

#5811 [EM-887][News] give access for news edition
  src/Controller/EnMarche/Jecoute/News/AbstractNewsController.php
  src/Security/Voter/CanEditCandidateNewsVoter.php
  src/Security/Voter/CanEditReferentNewsVoter.php
Labels: Ready for code review

#5812 [EM-963] Add endpoints to track push token with adherents & devices
  features/api/device.feature
  features/api/push_token.feature
  features/api/user.feature
  migrations/Version20210608090625.php
  src/DataFixtures/ORM/LoadDeviceData.php
  src/DataFixtures/ORM/LoadPushTokenData.php
  src/Device/DeviceManager.php
  src/Device/DeviceSubscriber.php
  src/Entity/Device.php
  src/Entity/PushToken.php
  src/Geo/ZoneMatcher.php
  src/Normalizer/PushTokenDenormalizer.php
  src/PushToken/PushTokenSourceEnum.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/PushTokenRepository.php
  src/Security/Voter/PushTokenAuthorVoter.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
  tests/Device/DeviceManagerTest.php
Labels: Ready for code review

#5838 Remove Botmind
  templates/base.html.twig
  templates/bot/_javascript.html.twig
Labels: Ready for code review

#5840 [API][Causes] Not return refused cause
  features/api/causes.feature
  phpunit.xml.dist
  src/Controller/Api/Coalition/RetrieveCauseController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5843 [Cookiebot] Add cookies consent modification
  templates/components/_footer_cgu.html.twig
  templates/page/politique-cookies.html.twig
Labels: Ready for code review

#5844 Remove an inappropriate export from Procuration manager space
  templates/procuration_manager/_layout.html.twig
Labels: Bug

#5858 [API][Causes] Get created and followed causes by a user
  features/api/causes.feature
  src/Api/Filter/MyCausesFilter.php
  src/Entity/Coalition/Cause.php
Labels: Ready for code review

#5859 [Coalitions][Events] Add events pages to Coalitions moderator space
  features/api/causes.feature
  src/Controller/EnMarche/CommitteeEventManagerController.php
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/CandidateEventManagerController.php
  src/Controller/EnMarche/EventManager/CoalitionEventManagerController.php
  src/Entity/Event/CoalitionEvent.php
  src/Event/EventCommand.php
  src/Event/EventFactory.php
  src/Event/EventManagerSpaceEnum.php
  src/Form/Coalition/CoalitionEventType.php
  src/Form/Coalition/EnabledCoalitionEntityType.php
  src/Repository/Coalition/CoalitionRepository.php
  src/Repository/CoalitionEventRepository.php
  templates/coalition/_sidebar.html.twig
  templates/event_manager/_base_coalition_moderator_space.html.twig
  templates/event_manager/_form_layout.html.twig
  templates/event_manager/event_create_success.html.twig
  templates/event_manager/events_list.html.twig
  templates/events/members.html.twig
  tests/Controller/EnMarche/EventManager/CoalitionEventManagerControllerTest.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Form/DataTransformer/EventDateTimeZoneTransformerTest.php
  tests/TestHelperTrait.php
Labels: Ready for code review

#5882 [API][Events] Not return institutional events and citizen actions
  src/Api/Doctrine/BaseEventExtension.php
Labels: Ready for code review

#5880 [Coalitions] Change cause edit page in the coalition moderator space
  features/api/causes.feature
  features/api/quick_actions.feature
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Controller/EnMarche/Coalition/CoalitionAuthorAucompleteController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Adherent.php
  src/Entity/Coalition/Cause.php
  src/Form/AdherentUuidType.php
  src/Form/Coalition/CauseType.php
  src/Repository/AdherentRepository.php
  src/Validator/Coalition/EnabledCoalitionUser.php
  src/Validator/Coalition/EnabledCoalitionUserValidator.php
  templates/coalition/edit_cause.html.twig
  templates/form_theme.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5885 [Command] Add command to unpublish local polls with passed finish date
  src/Command/UnpublishLocalPollCommand.php
Labels: Ready for code review

#5908 [EM-943] Events reminder notification
  migrations/Version20210615134639.php
  src/Command/RemindEventCommand.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Notification.php
  src/Event/EventReminderHandler.php
  src/Firebase/AbstractMessaging.php
  src/JeMarche/Command/EventReminderNotificationCommand.php
  src/JeMarche/Handler/CommitteeEventCreationNotificationCommandHandler.php
  src/JeMarche/Handler/EventReminderNotificationCommandHandler.php
  src/JeMarche/JeMarcheDeviceNotifier.php
  src/JeMarche/Notification/EventReminderNotification.php
  src/PushToken/PushTokenManager.php
  src/Repository/EventRegistrationRepository.php
  src/Repository/EventRepository.php
Labels: Ready for code review

#5877 [VotingPlatform] Add NationalCouncil mandate after election
  config/services.yaml
  config/services/mailchimp.yaml
  src/Committee/CommitteeAdherentMandateCommand.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Controller/Admin/AdminCommitteeController.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/DataFixtures/ORM/LoadNationalCouncilAdherentMandateData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilAdherentMandateData.php
  src/Entity/Adherent.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/AdherentMandate/AdherentMandateInterface.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Entity/AdherentMandate/NationalCouncilAdherentMandate.php
  src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Repository/AdherentMandate/NationalCouncilAdherentMandateRepository.php
  src/Repository/AdherentMandate/TerritorialCouncilAdherentMandateRepository.php
  src/VotingPlatform/AdherentMandate/AdherentMandateFactory.php
  src/VotingPlatform/AdherentMandate/Factory/AdherentMandateFactoryInterface.php
  src/VotingPlatform/AdherentMandate/Factory/CommitteeAdherentMandateFactory.php
  src/VotingPlatform/AdherentMandate/Factory/NationalCouncilAdherentMandateFactory.php
  src/VotingPlatform/AdherentMandate/Factory/TerritorialCouncilAdherentMandateFactory.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
  templates/admin/adherent/list_mandates.html.twig
  tests/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandlerTest.php
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
Labels: Ready for code review

#5912 [Coalition] Add cause author as follower if been changed + add cause link + css
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Twig/CoalitionUrlExtension.php
  src/Twig/CoalitionUrlRuntime.php
  templates/coalition/causes_list.html.twig
  templates/coalition/edit_cause.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5911 [Coalitions][Events] Change events pages to see cause and coalition events
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/EventManager/CoalitionEventManagerController.php
  src/Repository/CoalitionEventRepository.php
  src/Repository/EventRepository.php
  src/Security/Voter/HostEventVoter.php
  templates/coalition/_sidebar.html.twig
  templates/event_manager/events_list.html.twig
  tests/Controller/EnMarche/EventManager/CoalitionEventManagerControllerTest.php
  tests/Security/Voter/HostEventVoterTest.php
Labels: Ready for code review

#5913 Update donations import command
  src/Command/ImportDonationsCommand.php
Labels: Ready for code review

#5915 [Events] Add even mode to coalition event mails
  features/api/coalition_events.feature
  src/Entity/Event/BaseEvent.php
  src/Mailer/Message/Coalition/CauseEventCreationMessage.php
  src/Mailer/Message/Coalition/CoalitionsEventUpdateMessage.php
Labels: Ready for code review

#5910 Add new structure for Instance qualities
  config/services.yaml
  migrations/Version20210616114059.php
  src/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandler.php
  src/DataFixtures/ORM/LoadInstanceQualityData.php
  src/Entity/Adherent.php
  src/Entity/Instance/AdherentInstanceQuality.php
  src/Entity/Instance/InstanceQuality.php
  src/Instance/Command/UpdateInstanceQualitiesCommand.php
  src/Instance/Handler/UpdateInstanceQualitiesCommandHandler.php
  src/Instance/InstanceQualityEnum.php
  src/Instance/InstanceQualityScopeEnum.php
  src/Instance/InstanceQualityUpdater/AbstractQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/AbstractElectedRepresentativeBasedUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/AbstractFunctionTypeBasedQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/AbstractMandateTypeBasedQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/DepartmentCouncilPresidentQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/DeputyQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/EuroDeputyQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/RegionalCouncilPresidentQualityUpdater.php
  src/Instance/InstanceQualityUpdater/ElectedRepresentative/SenatorQualityUpdater.php
  src/Instance/InstanceQualityUpdater/GovernmentMemberQualityUpdater.php
  src/Instance/InstanceQualityUpdater/QualityUpdaterInterface.php
  src/Instance/InstanceQualityUpdater/TerritorialCouncilPresidentQualityUpdater.php
  src/Repository/Instance/InstanceQualityRepository.php
  tests/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandlerTest.php
Labels: Ready for code review

#5916 [NationalCouncil] Add homepage
  front/style/app.scss
  front/style/layout/_base.scss
  front/style/layout/_tabs.scss
  front/style/pages/_instances.scss
  src/Controller/EnMarche/NationalCouncil/IndexController.php
  src/DataFixtures/ORM/LoadAdherentInstanceQualityData.php
  src/DataFixtures/ORM/LoadInstanceQualityData.php
  src/Entity/Adherent.php
  src/Entity/Instance/AdherentInstanceQuality.php
  src/Entity/Instance/InstanceQuality.php
  templates/adherent_profile/activity/_instances.html.twig
  templates/national_council/_layout.html.twig
  templates/national_council/index.html.twig
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/candidacy_invitation/_copol_layout.html.twig
  templates/territorial_council/candidacy_invitation/_national_council_layout.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  templates/territorial_council/candidacy_step3_confirmation.html.twig
  templates/territorial_council/edit_feed_item.html.twig
  templates/territorial_council/faq.html.twig
  templates/territorial_council/homepage.html.twig
  templates/territorial_council/invitation_list.html.twig
  templates/territorial_council/members.html.twig
  templates/territorial_council/messages.html.twig
  templates/territorial_council/partials/_feed_items.html.twig
  templates/territorial_council/partials/_header.html.twig
  templates/territorial_council/partials/_sidebar.html.twig
  templates/territorial_council/partials/_slim_header.html.twig
  templates/territorial_council/political_committee/_layout.html.twig
  templates/territorial_council/political_committee/partials/_header.html.twig
  templates/territorial_council/political_committee/partials/_sidebar.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/PoliticalCommitteeControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#5924 [Dependabot] Ignore Major version of Symfony
  .github/dependabot.yml
Labels: Ready for code review

#5914 [EM-940] Poll notifications
  src/Admin/Poll/NationalPollAdmin.php
  src/Controller/Api/PollController.php
  src/Controller/EnMarche/Poll/AbstractPollController.php
  src/Entity/Poll/Poll.php
  src/JeMarche/Command/PollCreatedNotificationCommand.php
  src/JeMarche/Handler/DefaultEventCreationNotificationCommandHandler.php
  src/JeMarche/Handler/PollCreatedNotificationCommandHandler.php
  src/JeMarche/Notification/CommitteeEventCreatedNotification.php
  src/JeMarche/Notification/PollCreatedNotification.php
  src/JeMarche/NotificationTopicBuilder.php
  src/Poll/PollManager.php
  src/Repository/Poll/LocalPollRepository.php
  src/Repository/Poll/NationalPollRepository.php
  src/Repository/Poll/PollRepository.php
  src/Repository/Poll/UnpublishPollTrait.php
Labels: Ready for code review

#5917 Fix DefaultEventCreationNotificationHandler, add tests
  config/packages/test/messenger.yaml
  config/services_test.yaml
  src/Entity/Notification.php
  src/JeMarche/Handler/DefaultEventCreationNotificationCommandHandler.php
  src/Repository/EventRegistrationRepository.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/Test/Firebase/DummyMessaging.php
Labels: Ready for code review

#5926 [Events] Fix event description in CauseEventCreationMessage
  features/api/coalition_events.feature
  src/Mailer/Message/Coalition/CauseEventCreationMessage.php
Labels: Bug, Ready for code review

#5929 Fix events page
  src/Controller/EnMarche/EventManager/CoalitionEventManagerController.php
  templates/event_manager/events_list.html.twig
Labels: Bug

#5930 [NationalCouncil] Add members file
  app/data/static/instances/conseil-national/membres.pdf
  front/style/layout/_buttons.scss
  templates/national_council/_layout.html.twig
Labels: Ready for code review

#5928 [RepublicanSilence] Lock Candidate,LRE and Procurations spaces
  src/RepublicanSilence/CheckRepublicanSilenceListener.php
  tests/Controller/EnMarche/Filesystem/CandidateFilesControllerTest.php
  tests/Controller/EnMarche/Filesystem/FilesControllerTest.php
  tests/Controller/EnMarche/Jecoute/JecouteRegionControllerTest.php
  tests/Controller/EnMarche/ManagedUsers/ManagedUserControllerTest.php
  tests/Controller/EnMarche/Poll/PollCandidateControllerTest.php
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
Labels: Ready for code review

#5931 [Coalitions] Fix cause author autocomplete
  src/Controller/EnMarche/Coalition/CoalitionAuthorAutocompleteController.php
  src/Mailer/Message/Coalition/CauseFollowerConfirmationMessage.php
  src/Repository/AdherentRepository.php
  tests/Controller/EnMarche/Coalition/CoalitionAuthorAutocompleteControllerTest.php
Labels: Ready for code review

#5932 Remove unique adherent relation for instance quality
  migrations/Version20210618173936.php
  src/Entity/Instance/AdherentInstanceQuality.php
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
Labels: Bug, Ready for code review

#5938 [RepublicanSilence] Remove unused code for citizen action deletion
  src/Command/RepublicanSilenceCloseEventCommand.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
Labels: Bug, Ready for code review

#5927 [API][Events] Coalition events route returns Coalition and Cause events
  features/api/coalition_events.feature
  src/Controller/Api/Coalition/CoalitionEventsController.php
  src/Entity/Coalition/Coalition.php
  src/Repository/Event/BaseEventRepository.php
Labels: Ready for code review

#5940 [API][Events] Send an event visio url without protocol
  features/api/coalition_events.feature
  src/Normalizer/EventDenormalizer.php
Labels: Bug, Ready for code review

#5941 Make RefreshToken TTL an env var
  .env
  config/services/oauth.xml
  config/services_test.yaml
  src/OAuth/AuthorizationServerFactory.php
Labels: Ready for code review

#5942 [Dependabot 🤖] Maintain dependencies for GitHub Action
  .github/dependabot.yml
Labels: dependencies

#5944 Make AccessTokenTtl an env var
  .env
  config/services/oauth.xml
  config/services_test.yaml
  src/OAuth/AuthorizationServerFactory.php
Labels: Ready for code review

#5945 [EM-812] Change lastName validation
  src/AdherentProfile/AdherentProfile.php
  src/Assessor/AssessorRequestCommand.php
  src/Donation/DonationRequest.php
  src/Entity/ApplicationRequest/ApplicationRequest.php
  src/Entity/AssessorRequest.php
  src/Entity/Donator.php
  src/Entity/Invite.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Event/EventRegistrationCommand.php
  src/Legislative/LegislativeCampaignContactMessage.php
  src/Membership/MembershipRequest.php
  src/Newsletter/Invitation.php
  tests/Controller/Api/FormControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#5947 Do not check if tokens are expired when revoking them
  src/OAuth/Store/AccessTokenStore.php
  src/OAuth/Store/RefreshTokenStore.php
  src/OAuth/Store/TokenStoreTrait.php
Labels: Ready for code review

#5950 Fix followers count when cause author has been changed + Fix empty event visio url
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Normalizer/EventDenormalizer.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Bug, Ready for code review

#5835 [Event] Add Event creator as a first participant
  config/services/services.xml
  features/api/coalition_events.feature
  features/api/surveys.feature
  features/bootstrap/SyncWithAPIContext.php
  features/sync_with_api.feature
  src/Command/ApiScheduleEventCreationCommand.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Event/EventListener/AddFirstEventRegistrationSubscriber.php
  src/Event/EventListener/ApiSyncEventSubscriber.php
  src/Repository/Jecoute/NationalSurveyRepository.php
  templates/adherent_profile/activity/_events.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
Labels: Ready for code review

#5952 [NationalCouncil] Add Quatuor instance quality
  src/Entity/Adherent.php
  src/Instance/InstanceQualityEnum.php
  src/Instance/InstanceQualityUpdater/QuatuorMemberQualityUpdater.php
  src/Twig/AdherentRuntime.php
  templates/adherent_profile/_layout.html.twig
  templates/adherent_profile/activity.html.twig
  templates/adherent_profile/activity/_instances.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
Labels: Ready for code review

#5949 [EM-582] Change adherent interests
  config/packages/adherent.yaml
  features/api/profile.feature
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/SummaryManagerControllerTest.php
Labels: Ready for code review

#5951 [EM-582] Adherents interests migration
  src/Adherent/AdherentInterestsMigrationHandler.php
  src/Adherent/Command/AdherentMigrateInterestsCommand.php
  src/Adherent/Handler/AdherentMigrateInterestsCommandHandler.php
  src/Command/MigrateAdherentInterestsCommand.php
  src/Controller/EnMarche/AdherentController.php
  src/Form/AdherentMessage/AdherentZoneFilterType.php
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/Form/SummaryType.php
  templates/adherent/_profile_menu.html.twig
  templates/adherent_profile/_layout.html.twig
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/managed_users/filter_form.html.twig
  templates/message/filter/_adherent_zone_filter.html.twig
  templates/message/filter/referent.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/SummaryManagerControllerTest.php
Labels: Ready for code review

#5960 Revert adherents interests migration
  src/Adherent/AdherentInterestsMigrationHandler.php
  src/Adherent/Command/AdherentMigrateInterestsCommand.php
  src/Adherent/Handler/AdherentMigrateInterestsCommandHandler.php
  src/Command/MigrateAdherentInterestsCommand.php
  src/Controller/EnMarche/AdherentController.php
  src/Form/AdherentMessage/AdherentZoneFilterType.php
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/Form/SummaryType.php
  templates/adherent/_profile_menu.html.twig
  templates/adherent_profile/_layout.html.twig
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/managed_users/filter_form.html.twig
  templates/message/filter/_adherent_zone_filter.html.twig
  templates/message/filter/referent.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/SummaryManagerControllerTest.php
Labels: Ready for code review

#5962 [Admin] allow updating instance custom quality for adherent
  config/packages/security.yaml
  migrations/Version20210624021627.php
  src/Admin/AdherentAdmin.php
  src/Admin/AdministratorAdmin.php
  src/DataFixtures/ORM/LoadInstanceQualityData.php
  src/Entity/Adherent.php
  src/Entity/Instance/AdherentInstanceQuality.php
  src/Entity/Instance/InstanceQuality.php
  src/Form/Admin/AdherentInstanceQualityType.php
  src/Repository/Instance/InstanceQualityRepository.php
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#5963 [Admin] add national council filter on adherent list
  src/Admin/AdherentAdmin.php
  src/DataFixtures/ORM/LoadAdherentInstanceQualityData.php
  src/Entity/Adherent.php
  src/Entity/Instance/InstanceQuality.php
  src/Repository/Instance/InstanceQualityRepository.php
  symfony.lock
  templates/admin/adherent/list_vote_instances.html.twig
Labels: Ready for code review

#5964 [Referent] disable labels widget on elected representatives list
  templates/elected_representative/list.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
Labels: Ready for code review

#5965 [Admin] Add new role for elected representative labels field
  config/packages/security.yaml
  phpunit.xml.dist
  src/Admin/AdministratorAdmin.php
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  templates/admin/elected_representative/edit.html.twig
  tests/bootstrap.php
Labels: Ready for code review

#5966 [API] Get scopes of the adherent
  config/services.yaml
  features/api/scopes.feature
  src/Controller/Api/ScopeController.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Scope/AppEnum.php
  src/Scope/GeneralScopeGenerator.php
  src/Scope/Generator/CandidateScopeGenerator.php
  src/Scope/Generator/DeputyScopeGenerator.php
  src/Scope/Generator/ReferentScopeGenerator.php
  src/Scope/Generator/ScopeGeneratorInterface.php
  src/Scope/Generator/SenatorScopeGenerator.php
  src/Scope/Scope.php
  src/Scope/ScopeEnum.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#5957 [API][Causes] Send a quick action url without protocol
  features/api/quick_actions.feature
  src/Normalizer/EventDenormalizer.php
  src/Normalizer/UrlDenormalizer.php
Labels: Work in progress

#5976 [BurexElection] add Burex election entities
  Makefile
  migrations/Version20210628162452.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Command/VotingPlatform/InitializeElectionsCommand.php
  src/Controller/EnMarche/CommitteeDesignation/ReferentDesignationController.php
  src/DataFixtures/ORM/LoadAdherentInstanceQualityData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadNationalCouncilElectionData.php
  src/Entity/Instance/NationalCouncil/CandidaciesGroup.php
  src/Entity/Instance/NationalCouncil/Candidacy.php
  src/Entity/Instance/NationalCouncil/Election.php
  src/Entity/TerritorialCouncil/Election.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Form/Admin/VotingPlatform/DesignationNotificationType.php
  src/Mailer/Message/VotingPlatformElectionSecondRoundNotificationMessage.php
  src/Repository/Instance/NationalCouncil/ElectionRepository.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  templates/committee/_election_box.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5980 [NationalCouncil] Display election box
  src/Controller/EnMarche/NationalCouncil/IndexController.php
  src/Repository/Instance/NationalCouncil/ElectionRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/national_council/_layout.html.twig
  templates/national_council/partials/_election_box.html.twig
  templates/territorial_council/partials/_election_box.html.twig
Labels: Ready for code review

#5982 [PHP] Update Symfony to 4.4.26
  composer.lock
Labels: composer, dependencies

#5977 [API] Send scope to internal API application
  migrations/Version20210629122424.php
  src/Controller/Admin/AdminZoneController.php
  src/Controller/Api/InternalApiProxyController.php
  src/DataFixtures/ORM/LoadInternalApiApplicationData.php
  src/DataFixtures/ORM/LoadOAuthTokenData.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/InternalApiApplication.php
  src/Scope/Exception/NotFoundScopeGeneratorException.php
  src/Scope/GeneralScopeGenerator.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Generator/CandidateScopeGenerator.php
  src/Scope/Generator/DeputyScopeGenerator.php
  src/Scope/Generator/ReferentScopeGenerator.php
  src/Scope/Generator/ScopeGeneratorInterface.php
  src/Scope/Generator/SenatorScopeGenerator.php
  src/Scope/Scope.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
Labels: Ready for code review

#5984 [NationalCouncil] Display election candidacies
  front/style/pages/_instances.scss
  src/Controller/EnMarche/NationalCouncil/CandidacyListController.php
  src/Entity/Instance/NationalCouncil/CandidaciesGroup.php
  src/Entity/Instance/NationalCouncil/Candidacy.php
  src/Entity/VotingPlatform/Designation/BaseCandidaciesGroup.php
  src/Repository/Instance/NationalCouncil/CandidaciesGroupRepository.php
  src/Repository/Instance/NationalCouncil/CandidacyRepository.php
  templates/national_council/_layout.html.twig
  templates/national_council/candidacy_list.html.twig
  templates/national_council/index.html.twig
  templates/national_council/partials/_election_box.html.twig
  templates/national_council/partials/_nav.html.twig
  templates/territorial_council/_macros.html.twig
Labels: Ready for code review
