Repository parti-renaissance/espace-adherent, pull requests merged in 2021-09, with the labels that each got.

#6172 [API] Add tests to start phoning campaign endpoint
  features/api/phoning_campaigns.feature
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#6154 Change DataSurvey table
  migrations/Version20210824172202.php
  src/Entity/Jecoute/DataSurvey.php
Labels: Ready for code review

#6174 [Jecoute] use EXTRA_LAZY fetch strategy for answer collection
  src/Entity/Jecoute/Choice.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  src/Repository/Jecoute/NationalSurveyRepository.php
Labels: Bug, Ready for code review

#6173 [API][Phoning] Get phoning campaign survey
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/Phoning/CampaignHistory.php
  src/Phoning/CampaignHistoryStatusEnum.php
Labels: Ready for code review

#6179 [API][Phoning] Change status of the phoning campaign history
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Phoning/CampaignHistory.php
  src/Phoning/CampaignHistoryStatusEnum.php
  src/Security/Voter/CampaignHistoryCallerVoter.php
  translations/validators.fr.yml
Labels: Ready for code review

#6181 [Admin][Phoning] Add survey to phoning campaign
  migrations/Version20210902172856.php
  src/Admin/Phoning/CampaignAdmin.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/Entity/Phoning/Campaign.php
Labels: Ready for code review

#6186 [Phoning] Add brief to campaign
  features/api/phoning_campaigns.feature
  migrations/Version20210903162936.php
  src/Admin/Phoning/CampaignAdmin.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/Entity/Phoning/Campaign.php
Labels: Ready for code review

#6187 [API][Phoning] Get phoning campaign survey
  features/api/phoning_campaigns.feature
  features/api/surveys.feature
  src/Entity/Jecoute/Survey.php
  src/Entity/Phoning/Campaign.php
Labels: Ready for code review

#6190 Add adherent index on projection table
  migrations/Version20210906151345.php
  src/Entity/Projection/ManagedUser.php
Labels: Ready for code review

#5382 [Test] unskip donation tests
  features/donation.feature
  templates/adherent_profile/_layout.html.twig
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review

#6198 [JS] update js-base64 lib
  .eslintrc.js
  front/kernel.js
  front/vendor.js
  package.json
  yarn.lock
Labels: Ready for code review, dependencies, javascript, npm

#6199 [API][Phoning] Update phoning campaign history
  features/api/phoning_campaigns.feature
  src/Admin/Phoning/CampaignAdmin.php
  src/Entity/Adherent.php
  src/Entity/Phoning/CampaignHistory.php
  src/Phoning/Api/Listener/PostPhoningCampaignHistoryEditListener.php
  src/Phoning/CampaignHistoryStatusEnum.php
  translations/validators.fr.yml
Labels: Ready for code review

#6194 [API][Phoning] Add stats and scores
  features/api/phoning_campaigns.feature
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Normalizer/CampaignScoreNormalizer.php
  src/Repository/AdherentRepository.php
  src/Repository/Phoning/CampaignRepository.php
Labels: Ready for code review

#6195 Remove unused role ROLE_ADMIN_IDEAS_WORKSHOP
  src/Admin/AdministratorAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  templates/admin/report/list_actions.html.twig
Labels: Ready for code review

#6200 Update php7.4
  .github/workflows/lint.yml
  Dockerfile
  composer.json
  config/services.yaml
  docker/dev/Dockerfile
  docker/dev/entrypoint.sh
  docker/dev/supervisord.conf
  docker/prod/supervisord.conf
  src/Api/ApiPlatform/Core/Operation/Factory/SubresourceOperationFactory.php
  src/Doctrine/Filter/EnabledFilter.php
  src/Exception/AccountNotValidatedException.php
  src/Intl/UnitedNationsBundle.php
Labels: Ready for code review

#6201 [API][Phoning] Add endpoint to get one phoning campaign
  features/api/phoning_campaigns.feature
  src/Entity/Phoning/Campaign.php
  src/Normalizer/CampaignScoreNormalizer.php
  src/Security/Voter/PhoningCampaignVoter.php
Labels: Ready for code review

#6197 [API] Add get and accept chart endpoints
  features/api/charter.feature
  src/AdherentCharter/AdherentCharterFactory.php
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/Collection/AdherentCharterCollection.php
  src/Controller/Api/CharterController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/AdherentCharter/PhoningCampaignCharter.php
  src/Security/Voter/CharterVoter.php
Labels: Ready for code review

#6206 [Symfony] Enable inline Dumper factories
  src/Kernel.php
Labels: Ready for code review

#6208 [API][Phoning] Add phoning campaign tutorial
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/Controller/Api/Phoning/GetPhoningCampaignTutorialController.php
Labels: Ready for code review

#6207 [API][Phoning] Change sent info about adherent + some small changes
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/StartCampaignController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Entity/Adherent.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Phoning/CampaignHistory.php
  src/Form/Audience/AudienceSnapshotType.php
  src/Normalizer/AdherentNormalizer.php
  src/Phoning/CampaignHistoryStatusEnum.php
  src/Repository/AdherentRepository.php
  src/Repository/Phoning/CampaignHistoryRepository.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#6211 [Firebase] Fix service declaration
  config/packages/firebase.yaml
Labels: Ready for code review

#6210 Add SMS campaign admin role
  config/packages/security.yaml
  src/Admin/AdministratorAdmin.php
Labels: Ready for code review

#6193 Send sms campaign
  .env
  config/packages/old_sound_rabbit_mq.yaml
  config/packages/test/old_sound_rabbit_mq.yaml
  config/services.yaml
  config/services/http_client.yaml
  config/services_test.yaml
  features/admin/adherent.feature
  features/admin/committee_merge.feature
  features/bootstrap/RabbitMqContext.php
  features/registration.feature
  features/sync_with_api.feature
  migrations/Version20210906214006.php
  src/Admin/SmsCampaignAdmin.php
  src/Controller/Admin/AdminSmsCampaignCRUDController.php
  src/DataFixtures/ORM/LoadSmsCampaignData.php
  src/Entity/SmsCampaign.php
  src/OvhCloud/Driver.php
  src/OvhCloud/Notifier.php
  src/Repository/AdherentRepository.php
  src/Repository/SmsCampaignRepository.php
  src/SmsCampaign/Handler/SendSmsCampaignCommandHandler.php
  src/SmsCampaign/SmsCampaignStatusEnum.php
  templates/admin/sms_campaign/confirm.html.twig
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Controller/EnMarche/EventManager/CoalitionEventManagerControllerTest.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Controller/EnMarche/UserControllerTest.php
  tests/Test/Consumer/DummyConsumer.php
  tests/Test/OldSoundRabbitMq/Connection/DummyChannel.php
  tests/Test/OldSoundRabbitMq/Connection/DummyConnection.php
  translations/messages.fr.yml
Labels: Ready for code review

#6215 [CI] avoid load fixtures for behat tests
  .circleci/config.yml
  Makefile
Labels: Ready for code review

#6209 [EM-1225] Amélioration du BO campagne Phoning
  src/Admin/Phoning/CampaignAdmin.php
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Entity/Team/Team.php
  templates/admin/phoning/campaign/list_campaign_histories_count.html.twig
  templates/admin/phoning/campaign/list_campaign_histories_unjoin_unsubscribe_count.html.twig
  templates/admin/phoning/campaign/list_campaign_histories_with_data_survey_count.html.twig
  templates/admin/phoning/campaign/list_goal.html.twig
  templates/admin/phoning/campaign/list_team.html.twig
Labels: Ready for code review

#6212 [EM-1226] Amélioration du BO Equipes
  src/Entity/Team/Member.php
  src/Entity/Team/Team.php
  src/Validator/UniqueInCollection.php
  src/Validator/UniqueInCollectionValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#6220 [Admin][Phoning] Add simplified Markdown field to the campaign brief
  src/Admin/Phoning/CampaignAdmin.php
  templates/admin/layout.html.twig
Labels: Ready for code review

#6219 [API][Phoning] Modify scoreboard + add all callers
  features/api/phoning_campaigns.feature
  src/Normalizer/CampaignScoreNormalizer.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6216 [API][Phoning] Change replay survey endpoint
  features/api/surveys-replys.feature
  src/Controller/Api/Jecoute/AbstractReplyController.php
  src/Controller/Api/Jecoute/JemarcheDataSurveyReplyController.php
  src/Controller/Api/Jecoute/ReplyController.php
  src/Controller/Api/Phoning/CampaignHistoryReplyController.php
  src/DataFixtures/ORM/LoadJemarcheDataSurveyData.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/DataAnswer.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Jecoute/DataSurveyAwareTrait.php
  src/Entity/Jecoute/JemarcheDataSurvey.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Entity/Phoning/CampaignHistory.php
  src/Jecoute/Exception/DataSurveyException.php
  src/Normalizer/ChoiceFromIdDenormalizer.php
  src/Normalizer/SurveyFromUuidDenormalizer.php
  src/Normalizer/SurveyQuestionFromIdDenormalizer.php
  src/Repository/Jecoute/ChoiceRepository.php
  src/Repository/Jecoute/SurveyQuestionRepository.php
Labels: Ready for code review

#6222 Initialize Filter brick
  config/services.yaml
  src/AdherentFilter/AdherentFiltersGenerator.php
  src/AdherentFilter/FilterBuilder/AdherentBasicFieldsFilterBuilder.php
  src/AdherentFilter/FilterBuilder/AdherentFilterBuilderInterface.php
  src/AdherentFilter/FilterBuilder/CertifiedStatusFilterBuilder.php
  src/AdherentFilter/FilterBuilder/SmsAndEmailSubscriptionStatusFilterBuilder.php
  src/Controller/Api/AdherentFilter/GetFilterCollectionController.php
  src/Filter/FilterCollectionBuilder.php
  src/Filter/FilterInterface.php
  src/Filter/FilterTypeEnum.php
  src/Filter/Types/AbstractFilter.php
  src/Filter/Types/Autocomplete.php
  src/Filter/Types/DateInterval.php
  src/Filter/Types/DefinedTypes/AgeRange.php
  src/Filter/Types/DefinedTypes/BooleanSelect.php
  src/Filter/Types/DefinedTypes/GenderSelect.php
  src/Filter/Types/DefinedTypes/ZoneAutocomplete.php
  src/Filter/Types/IntegerInterval.php
  src/Filter/Types/Select.php
  src/Filter/Types/Text.php
  src/Scope/FeatureEnum.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#6223 [API][Riposte] Add stats fields
  features/api/jecoute_ripostes.feature
  migrations/Version20210916141855.php
  src/Admin/Jecoute/RiposteAdmin.php
  src/Controller/Api/Jecoute/IncrementRiposteStatsCounterController.php
  src/Entity/Jecoute/Riposte.php
  src/Jecoute/Api/Listener/PostGetRipostesListener.php
Labels: Ready for code review

#6227 [EM-1335] QR Codes
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20210920011827.php
  src/Admin/AdministratorAdmin.php
  src/Admin/QrCodeAdmin.php
  src/Controller/Admin/AdminQrCodeGeneratorController.php
  src/Controller/EnMarche/QrCodeController.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadQrCodeData.php
  src/Entity/QrCode.php
  src/QrCode/QrCodeEntityHandler.php
  src/QrCode/QrCodeResponseFactory.php
  src/Repository/QrCodeRepository.php
  src/Security/QrCodeResponseFactory.php
  templates/admin/qr_code/list_qrcode.html.twig
  tests/Controller/EnMarche/QrCodeControllerTest.php
Labels: Ready for code review

#6230 [API][Riposte] Change access + add some tests
  features/api/jecoute_ripostes.feature
  src/Api/Doctrine/JecouteRiposteExtension.php
  src/Controller/Api/Jecoute/IncrementRiposteStatsCounterController.php
  src/Entity/Jecoute/Riposte.php
  src/Jecoute/Api/Listener/PostGetRipostesListener.php
  tests/Controller/Api/Jecoute/GetRipostesControllerTest.php
  tests/Controller/Api/Jecoute/IncrementRiposteStatsCounterControllerTest.php
Labels: Ready for code review

#6221 Add Panther component
  Dockerfile
  composer.json
  composer.lock
  config/services.yaml
  config/services_dev.yaml
  docker/dev/Dockerfile
  features/api/jecoute_ripostes.feature
  migrations/Version20210916155001.php
  src/Admin/Jecoute/RiposteAdmin.php
  src/Controller/Api/CharterController.php
  src/DataFixtures/ORM/LoadJecouteRiposteData.php
  src/Entity/Jecoute/Riposte.php
  src/Normalizer/JecouteRiposteDenormalizer.php
  src/OpenGraph/OpenGraphFetcher.php
  src/Riposte/RiposteOpenGraphHandler.php
  src/Utils/PhpConfigurator.php
  src/Validator/RiposteOpenGraph.php
  src/Validator/RiposteOpenGraphValidator.php
  src/Validator/UniqueDonationSubscriptionValidator.php
  symfony.lock
  templates/form_theme_admin.html.twig
  tests/Controller/Api/Jecoute/GetRipostesControllerTest.php
  tests/Test/OpenGraph/DummyOpenGraphFetcher.php
  translations/validators.fr.yml
Labels: Ready for code review

#6233 [API][Phoning] Change phoning campaign survey config
  features/api/phoning_campaigns.feature
  migrations/Version20210920171534.php
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/DataFixtures/ORM/LoadPhoningCampaignHistoryData.php
  src/Entity/Adherent.php
  src/Entity/Phoning/CampaignHistory.php
  src/Phoning/Api/Listener/PostPhoningCampaignHistoryEditListener.php
  src/Phoning/CampaignHistoryEngagementEnum.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6235 [Admin][Phoning] Add phoning campaign calls stats
  features/api/phoning_campaigns.feature
  src/Admin/Phoning/CampaignAdmin.php
  src/Controller/Admin/AdminPhoningCampaignStatsController.php
  src/Repository/AdherentRepository.php
  templates/admin/phoning/campaign/list_action_stats.html.twig
  templates/admin/phoning/campaign/stats.html.twig
Labels: Ready for code review

#6236 [API][Phoning] Add 'profession' field to the phoning campaign history
  features/api/phoning_campaigns.feature
  migrations/Version20210922120136.php
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
  src/Entity/Phoning/CampaignHistory.php
Labels: Ready for code review

#6237 Enable API filters on adherents endpoint
  src/AdherentFilter/FilterBuilder/AdherentBasicFieldsFilterBuilder.php
  src/AdherentFilter/FilterBuilder/SmsAndEmailSubscriptionStatusFilterBuilder.php
  src/Filter/Types/DefinedTypes/BooleanSelect.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Normalizer/ZoneDenormalizer.php
  src/Repository/Projection/ManagedUserRepository.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
  tests/Controller/Api/AdherentList/AdherentListControllerTest.php
Labels: Ready for code review

#6238 Use distant selenium client
  .env
  Dockerfile
  config/services.yaml
  docker/dev/Dockerfile
  src/OpenGraph/OpenGraphFetcher.php
  src/Panther/ClientFactory.php
Labels: Ready for code review

#6241 Use default email template on API
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
Labels: Bug, Ready for code review

#6242 Change OpenGraphFetcher timeout
  src/OpenGraph/OpenGraphFetcher.php
Labels: Ready for code review

#6243 [Admin][Phoning] Add phoning campaign histories admin
  config/services/admin.xml
  src/Admin/Phoning/CampaignHistoryAdmin.php
  src/Phoning/CampaignHistoryStatusEnum.php
  src/Phoning/CampaignHistoryTypeEnum.php
  templates/admin/phoning/campaign/stats.html.twig
  templates/admin/phoning/campaign_history/list_call_info.html.twig
  templates/admin/phoning/campaign_history/list_satisfaction_questions.html.twig
  templates/admin/phoning/campaign_history/list_status.html.twig
  templates/admin/phoning/campaign_history/list_survey.html.twig
  templates/admin/phoning/campaign_history/list_type.html.twig
Labels: Ready for code review

#6245 Fix events display in spaces
  src/Repository/Event/BaseEventRepository.php
Labels: Ready for code review

#6246 [AudienceSegment] enable additional filters
  src/AdherentFilter/FilterBuilder/AdherentBasicFieldsFilterBuilder.php
  src/AdherentFilter/FilterBuilder/ZoneAutocompleteFilterBuilder.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
  src/Entity/AdherentMessage/Segment/AudienceSegment.php
  src/Filter/FilterCollectionBuilder.php
  src/Filter/Types/Autocomplete.php
  src/Filter/Types/DefinedTypes/GenderSelect.php
  src/Filter/Types/DefinedTypes/ZoneAutocomplete.php
  src/Filter/Types/Select.php
  src/Normalizer/AudienceFilterDenormalizer.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#6256 Add Zone autocomplete endpoint
  features/api/zones.feature
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Controller/Api/Zone/ZoneAutocompleteSelect2Controller.php
  src/Entity/Geo/Zone.php
  src/Filter/Types/DefinedTypes/ZoneAutocomplete.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#6255 [Tests] remove useless header Accept step on Behat
  features/api/adherents.feature
  features/api/committees.feature
  features/api/event_categories.feature
  features/api/events.feature
  features/api/referent.feature
  features/api/statistics.feature
  features/api/zones.feature
  features/oauth.feature
Labels: Ready for code review

#6250 Add Jecoute national campaigns
  config/services/admin.xml
  migrations/Version20210926023127.php
  src/Admin/Jecoute/AbstractRegionAdmin.php
  src/Admin/Jecoute/NationalRegionAdmin.php
  src/Controller/EnMarche/Jecoute/Personalization/AbstractPersonalizationController.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/Jecoute/Region.php
  src/Form/Jecoute/RegionType.php
  src/Repository/Jecoute/RegionRepository.php
  templates/jecoute/edit_region.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#6248 Handle scopes for delegated accesses
  features/api/scopes.feature
  src/Repository/MyTeam/DelegatedAccessRepository.php
  src/Scope/FeatureEnum.php
  src/Scope/GeneralScopeGenerator.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Generator/ScopeGeneratorInterface.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#6257 Use BinaryFileResponse instead of file_get_contents on AssetsController
  composer.json
  composer.lock
  src/Controller/AssetsController.php
Labels: Ready for code review

#6258 [EM-1356] Remove 'responsables thematiques' block
  templates/page/le-mouvement/notre-organisation.html.twig
Labels: Ready for code review

#6249 Datacorner delegated accesses
  src/Security/Voter/DataCornerVoter.php
  templates/candidate/_layout.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
  tests/Security/Voter/DataCornerVoterTest.php
Labels: Ready for code review

#6265 Update lcobucci/jwt
  composer.lock
Labels: Ready for code review

#6261 Use Fusonic/OpenGraph instead of Panther for scrapping
  .env
  composer.json
  composer.lock
  config/services.yaml
  src/OpenGraph/OpenGraphFetcher.php
  src/Panther/ClientFactory.php
  symfony.lock
  templates/form_theme_admin.html.twig
Labels: Ready for code review

#6269 [AudienceSegment] add flush for update action too
  src/AdherentMessage/Handler/SynchronizeDynamicSegmentCommandHandler.php
Labels: Bug, Ready for code review

#6267 [SmsCampaign] improve Admin
  migrations/Version20210929151100.php
  src/Admin/SmsCampaignAdmin.php
  src/Controller/Admin/AdminSmsCampaignCRUDController.php
  src/DataFixtures/ORM/LoadSmsCampaignData.php
  src/Entity/SmsCampaign.php
  src/Repository/AdherentRepository.php
  src/SmsCampaign/Handler/SendSmsCampaignCommandHandler.php
  templates/admin/sms_campaign/CRUD/_recipient_count.html.twig
  templates/admin/sms_campaign/CRUD/list__action_confirm.html.twig
  templates/admin/sms_campaign/CRUD/list__action_delete.html.twig
  templates/admin/sms_campaign/CRUD/list__recipient_count.html.twig
  templates/admin/sms_campaign/CRUD/show__recipient_count.html.twig
  templates/admin/sms_campaign/confirm.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#6266 [ManagedUser] add city filter for FDE referents
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Entity/ReferentManagedArea.php
  src/Form/ManagedUsers/ReferentManagedUsersFilterType.php
  templates/managed_users/filter_form.html.twig
Labels: Ready for code review

#6274 Send notification on Riposte postPersist
  src/Admin/Jecoute/RiposteAdmin.php
  src/JeMarche/Command/RiposteCreatedNotificationCommand.php
  src/JeMarche/Handler/RiposteCreatedNotificationCommandHandler.php
  src/JeMarche/JeMarcheDeviceNotifier.php
  src/JeMarche/Notification/RiposteCreatedNotification.php
  src/JeMarche/NotificationTopicBuilder.php
  src/Jecoute/RiposteHandler.php
  src/Repository/Jecoute/RiposteRepository.php
Labels: Ready for code review
