Repository parti-renaissance/espace-adherent, pull requests merged in 2021-02, with the labels that each got.

#5314 [Admin][Committee] Close a committee while merge
  migrations/Version20210201114929.php
  src/Admin/CommitteeAdmin.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Entity/Committee.php
  templates/admin/committee/list_actions.html.twig
  templates/admin/committee/mandates/list.html.twig
  templates/admin/committee/members.html.twig
  templates/committee/status.html.twig
  tests/Entity/CommitteeTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5325 [Admin] Remove useless SwitchUser exit controller
  config/packages/security.yaml
  src/Controller/Admin/AdminAdherentController.php
  src/Controller/AssetsController.php
  src/Controller/HealthController.php
  src/Controller/UploadDocumentController.php
  src/Security/AuthenticationUtils.php
  templates/components/_dropdown_user_desktop.html.twig
  templates/components/_dropdown_user_mobile.html.twig
Labels: Ready for code review

#5320 [Security] Improve cookie settings
  config/packages/prod/framework.yaml
Labels: Ready for code review

#5323 [Committee] Not show promote to host button if committee has 2 hosts
  src/Committee/CommitteePermissions.php
  src/Controller/Admin/AdminCommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Security/Voter/Committee/PromoteToHostInCommitteeVoter.php
  templates/admin/committee/members.html.twig
  templates/committee_manager/list_members.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#5326 [Committee] Fix committee creation
  features/api/committees.feature
  front/services/address/AutocompletedAddressForm.js
  front/services/address/GooglePlaceAutocomplete.js
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeCreationCommand.php
  src/Committee/CommitteeManager.php
  src/Committee/Filter/ListFilterObject.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Form/AddressType.php
  src/Form/BooleanChoiceType.php
  src/Form/CommitteeCommandType.php
  src/Form/CommitteeMemberFilterType.php
  src/Form/ManagedUsers/ManagedUsersFilterType.php
  src/Form/ManagedUsers/ReferentManagedUsersFilterType.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/CommitteeRepository.php
  src/Security/Voter/Committee/HostCommitteeVoter.php
  src/Security/Voter/Committee/SuperviseCommitteeVoter.php
  src/Validator/AbstractInManagedZoneValidator.php
  src/Validator/AddressInManagedZones.php
  src/Validator/AddressInManagedZonesValidator.php
  src/Validator/ApprovedCommitteeAddress.php
  src/Validator/ApprovedCommitteeAddressValidator.php
  src/Validator/CommitteeAddressValidator.php
  src/Validator/ManagedZoneValidator.php
  src/Validator/UniqueCommittee.php
  src/Validator/UniqueCommitteeValidator.php
  templates/committee/_form.html.twig
  templates/committee_manager/list_members.html.twig
  templates/form_theme.html.twig
  templates/form_theme_admin.html.twig
  templates/referent/committee/requests_list.html.twig
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Security/Voter/Committee/HostCommitteeVoterTest.php
  tests/Security/Voter/Committee/SuperviseCommitteeVoterTest.php
  tests/Test/Geocoder/DummyGeocoder.php
  translations/validators.fr.yml
Labels: Ready for code review

#5327 [Mailchimp] Fix resub from my-space
  config/services/http_client.yaml
  src/Mailchimp/SignUp/SignUpHandler.php
Labels: Bug, Ready for code review

#5322 [Event] Enable API for coalition event type
  composer.json
  composer.lock
  config/packages/security.yaml
  config/services.yaml
  config/services/mailchimp.yaml
  config/services/twig.yaml
  migrations/Version20210127181420.php
  src/DataFixtures/ORM/LoadClientData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CoalitionEvent.php
  src/Event/EventTypeEnum.php
  src/Form/MemberInterestsChoiceType.php
  src/Mailchimp/Webhook/Handler/AdherentProfileUpdateHandler.php
  src/Normalizer/EventDenormalizer.php
  src/OAuth/Model/Scope.php
  src/Twig/AdherentRuntime.php
  src/Validator/AddressValidator.php
  src/Validator/AdherentInterests.php
  src/Validator/AdherentInterestsValidator.php
  src/Validator/CommitteeMemberValidator.php
  src/Validator/MergeableCommitteesValidator.php
  src/Validator/UnitedNationsCountryValidator.php
  src/Validator/WasNotInvitedRecentlyValidator.php
  symfony.lock
  tests/Controller/Api/Event/CoalitionEventControllerTest.php
Labels: Ready for code review

#5331 [Committee] Some changes in admin and committees list
  features/admin/committee_merge.feature
  src/Admin/CommitteeAdmin.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteeMergeCommandHandler.php
  src/Committee/CommitteePermissions.php
  src/Controller/Admin/AdminCommitteeController.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/Security/Voter/Committee/ManageCommitteeMandatesVoter.php
  src/Security/Voter/Committee/PromoteToHostInCommitteeVoter.php
  templates/admin/committee/mandates/add.html.twig
  templates/admin/committee/mandates/list.html.twig
  templates/admin/committee/mandates/replace.html.twig
  templates/admin/committee/members.html.twig
  templates/admin/committee/refuse.html.twig
  templates/admin/list_address.html.twig
  templates/committee_manager/_layout.html.twig
  templates/referent/committee/list.html.twig
  templates/referent/committee/requests_list.html.twig
  tests/Admin/CommitteeAdminTest.php
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
Labels: Ready for code review

#5332 [Committee] Fix committee address autocomplete with no postal code
  front/services/address/GooglePlaceAutocomplete.js
Labels: Ready for code review

#5335 [Committee] Fix merge and demote host
  features/admin/committee_merge.feature
  src/Committee/CommitteeMergeCommandHandler.php
  src/Controller/Admin/AdminCommitteeController.php
Labels: Ready for code review

#5336 Change menu and footer
  front/style/layout/_footer.scss
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_footer.html.twig
  templates/components/_nav_desktop.html.twig
Labels: Ready for code review

#5339 Fix convocation creation
  src/Form/AddressType.php
Labels: Ready for code review

#5337 [ApplicationRequest] Remove a creation page
  src/ApplicationRequest/ApplicationRequestHandler.php
  src/ApplicationRequest/ApplicationRequestRepository.php
  src/ApplicationRequest/Events.php
  src/ApplicationRequest/Listener/HideDuplicateRequestsSubscriber.php
  src/ApplicationRequest/Listener/SendConfirmationRequestSubscriber.php
  src/Controller/EnMarche/ApplicationRequestController.php
  src/Form/ApplicationRequest/ApplicationRequestType.php
  src/Form/ApplicationRequest/RunningMateRequestType.php
  src/Form/ApplicationRequest/VolunteerRequestType.php
  src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
  templates/application_request/_layout.html.twig
  templates/application_request/confirmation.html.twig
  templates/application_request/request.html.twig
  tests/Controller/EnMarche/ApplicationRequestControllerTest.php
Labels: Ready for code review

#5338 Add new zone (a department 'Nouveau Rhône')
  dump/all-geo-zone.sql
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/DataFixtures/ORM/LoadReferentTagData.php
  src/DataFixtures/geo/geo-zones.csv
  src/Repository/GeoFilterTrait.php
  src/Utils/AreaUtils.php
Labels: Ready for code review

#5341 Add Facebook Pixel to base layout
  templates/base.html.twig
  templates/components/_facebook_pixel.html.twig
Labels: Ready for code review

#5345 [Coalition] Create entity
  migrations/Version20210211183646.php
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/Entity/Coalition/Coalition.php
  src/Entity/Event/CoalitionEvent.php
  src/Entity/Projection/ManagedUser.php
Labels: Ready for code review

#5340 [CitizenProject] Fix adding committee support
  src/Controller/EnMarche/AdherentController.php
  src/Entity/CitizenProject.php
  templates/admin/citizen_action/edit.html.twig
  templates/admin/citizen_action/list_actions.html.twig
  templates/admin/citizen_action/show.html.twig
  templates/admin/citizen_project/list_next_citizen_action.html.twig
  templates/admin/event_category/list_status.html.twig
  templates/citizen_project/_sidebar.html.twig
Labels: Ready for code review

#5330 [PHP] Replace abandoned PhoneNumber bundle by its fork
  composer.json
  composer.lock
  symfony.lock
Labels: Ready for code review

#5346 [Admin] remove second "=" from adherent host query
  src/Admin/AdherentAdmin.php
Labels: Bug, Ready for code review

#5348 [Coalition][API] Add get list and item routes
  config/services/services.xml
  features/api/coalitions.feature
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/DataFixtures/coalitions/default.png
  src/Doctrine/CoalitionExtension.php
  src/Entity/Coalition/Coalition.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Event/CoalitionEvent.php
  src/Normalizer/CoalitionNormalizer.php
Labels: Ready for code review

#5352 Fix donation tests
  features/donation.feature
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review

#5351 Allow to create Committee without postal code if outside France
  features/registration.feature
  src/Address/Address.php
Labels: Ready for code review

#5353 [Partial election] Add creation form
  config/packages/exercise_html_purifier.yaml
  config/services/controller.yaml
  migrations/Version20210217141844.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  src/Controller/EnMarche/CommitteeDesignation/ReferentDesignationController.php
  src/Entity/Committee.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/ZoneableEntity.php
  src/Form/PartialDesignationType.php
  src/Geo/ManagedZoneProvider.php
  src/Mailer/Message/VotingPlatformPartialElectionIsOpenMessage.php
  src/Repository/CommitteeElectionRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/EventRepository.php
  src/Repository/GeoZoneTrait.php
  src/Repository/Projection/ManagedUserRepository.php
  src/Security/Voter/ManageZoneableItemVoter.php
  src/Validator/AbstractInManagedZoneValidator.php
  src/Validator/CommitteePartialDesignation.php
  src/Validator/CommitteePartialDesignationValidator.php
  src/VotingPlatform/Command/NotifyPartialElectionVoterCommand.php
  src/VotingPlatform/Designation/CreatePartialDesignationCommand.php
  templates/committee/_base_referent.html.twig
  templates/committee_designation/create_partial.html.twig
  templates/committee_manager/_layout.html.twig
  templates/referent/_sidebar.html.twig
  templates/referent/committee/available_committees_for_partials.html.twig
  templates/referent/committee/list.html.twig
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
Labels: Ready for code review

#5349 Add env var to enable Facebook pixel
  .env
  config/packages/twig.yaml
  templates/base.html.twig
Labels: Ready for code review

#5354 [Test] add sleep for donation tests
  features/donation.feature
Labels: Ready for code review

#5356 [PartialElection] Send email with partial election dates
  migrations/Version20210218153831.php
  src/Controller/EnMarche/CommitteeDesignation/ReferentDesignationController.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Mailer/Message/VotingPlatformPartialElectionIsOpenMessage.php
  src/VotingPlatform/Handler/NotifyPartialElectionVoterCommandHandler.php
Labels: Ready for code review

#5357 [Test] behat - skip donation tests
  behat.yml.dist
  composer.json
  composer.lock
  features/donation.feature
  symfony.lock
Labels: Ready for code review

#5355 [Coalition][API] Add coalition events route
  config/services/services.xml
  features/api/coalition_events.feature
  migrations/Version20210217165724.php
  src/Adherent/Unregistration/Handlers/UpdateEventHandler.php
  src/DataFixtures/ORM/LoadCoalitionEventData.php
  src/Doctrine/CoalitionEventExtension.php
  src/Entity/Coalition/Coalition.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/BaseEventCategory.php
  src/Entity/Event/CoalitionEvent.php
  src/Repository/CoalitionEventRepository.php
Labels: Ready for code review

#5358 Fix api tests
  src/DataFixtures/ORM/LoadCoalitionEventData.php
Labels: Ready for code review

#5361 [Coalition][API] Add coalition causes route
  features/api/causes.feature
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/Coalition.php
Labels: Ready for code review

#5362 Add if necessary a 69D referent tag when address has been changed
  src/Referent/ManagedAreaUtils.php
  src/Utils/AreaUtils.php
  tests/Referent/ManagedAreaUtilsTest.php
  tests/Utils/AreaUtilsTest.php
Labels: Ready for code review

#5363 [PartialElection] update wording on form and election box
  src/Repository/CommitteeCandidacyRepository.php
  src/Repository/CommitteeRepository.php
  src/Utils/AreaUtils.php
  templates/committee/_election_box.html.twig
  templates/committee/election_box/_committee_adherent.html.twig
  templates/committee/show.html.twig
  templates/committee_designation/create_partial.html.twig
  templates/referent/committee/available_committees_for_partials.html.twig
Labels: Ready for code review

#5364 Partial election fix email
  .circleci/config.yml
  config/services.yaml
  src/VotingPlatform/Handler/NotifyPartialElectionVoterCommandHandler.php
Labels: Ready for code review

#5369 [CI] Fix tests related to Partial election
  .circleci/config.yml
  features/committee_vote.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  templates/committee/_election_box.html.twig
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
Labels: Bug, Ready for code review

#5373 [PartialElection] fix committee list with partial election actions
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Repository/CommitteeElectionRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/EventRepository.php
  src/Repository/GeoZoneTrait.php
  src/Repository/Projection/ManagedUserRepository.php
  src/Validator/CommitteePartialDesignation.php
  src/Validator/CommitteePartialDesignationValidator.php
  templates/committee/candidacy/candidacy_list.html.twig
  templates/committee_designation/create_partial.html.twig
  templates/referent/committee/list.html.twig
Labels: Bug, Ready for code review

#5376 Prevent to remove a quality/membership from TerritorialCouncil if adherent has a corresponding mandate in CoPol
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
Labels: Work in progress

#5375 Composer v2
  .blackfire.yml
  .circleci/config.yml
  .sensiolabs.yml
  Dockerfile
  Makefile
  composer.json
  composer.lock
  docker/dev/Dockerfile
  src/Algolia/Query/QueryBuilder.php
  src/Command/ImportReferentBioPictureCommand.php
  src/Consumer/AbstractConsumer.php
  src/Controller/Api/UserController.php
  src/Controller/Api/ZoneController.php
  src/Controller/OAuth/OAuthServerController.php
  src/Entity/Adherent.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/ApplicationRequest/test.txt
  src/Entity/BaseGroup.php
  src/Entity/CitizenProjectMembership.php
  src/Entity/CommitteeFeedItem.php
  src/Entity/CommitteeMembership.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Page.php
  src/Entity/ProcurationProxy.php
  src/Entity/SocialShare.php
  src/Entity/ThematicCommunity/ThematicCommunity.php
  src/Entity/ThematicCommunity/ThematicCommunityMembership.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentGeoZoneConditionBuilder.php
  src/OAuth/Store/RefreshTokenStore.php
  src/Repository/EventRepository.php
  src/Repository/VotePlaceRepository.php
  symfony.lock
  test.html
  tests/Adherent/Certification/CertificationAuthorityManagerTest.php
  tests/Adherent/Certification/CertificationManagerTest.php
  tests/Admin/AdherentAdminTest.php
  tests/Admin/ElectedRepresentative/ElectedRepresentativeAdminTest.php
  tests/Admin/FormationAdminTest.php
  tests/BoardMember/BoardMemberManagerTest.php
  tests/Controller/Admin/AdminIdeaControllerTest.php
  tests/Controller/Admin/AdminThreadCommentControllerTest.php
  tests/Controller/Admin/AdminThreadControllerTest.php
  tests/EventListener/AdministratorExportHistoryListenerTest.php
  tests/Repository/AdherentRepositoryTest.php
  tests/Repository/CommitteeMembershipRepositoryTest.php
  tests/Repository/CommitteeRepositoryTest.php
  tests/Repository/EventRepositoryTest.php
  tests/Repository/MyEuropeChoiceRepositoryTest.php
  tests/Repository/NewsletterSubscriptionRepositoryTest.php
  tests/Repository/TonMacronChoiceRepositoryTest.php
  var/SymfonyRequirements.php
  var/sessions/.gitkeep
Labels: Ready for code review

#5379 [PartialElection] fix vote start date in email
  src/Mailer/Message/VotingPlatformPartialElectionIsOpenMessage.php
Labels: Bug, Ready for code review

#5381 [PHP] add nyholm/psr7 package
  composer.json
  composer.lock
  src/Controller/Api/UserController.php
  src/Controller/OAuth/OAuthServerController.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/VotingPlatform/Security/ElectionAuthorisationChecker.php
  symfony.lock
  templates/referent/committee/available_committees_for_partials.html.twig
Labels: Bug, Ready for code review

#5386 [Committee] Remove canary mode for phone number in committee for AL + show phone of all members
  templates/committee_manager/list_members.html.twig
Labels: Ready for code review

#5366 News front
  config/packages/security.yaml
  migrations/Version20210226133019.php
  src/Admin/Jecoute/NewsAdmin.php
  src/Controller/EnMarche/Jecoute/News/AbstractNewsController.php
  src/Controller/EnMarche/Jecoute/News/NewsCandidateController.php
  src/Entity/Jecoute/News.php
  src/Form/Jecoute/NewsFormType.php
  src/Jecoute/NewsHandler.php
  templates/candidate/_sidebar.html.twig
  templates/jecoute/news/_form.html.twig
  templates/jecoute/news/create.html.twig
  templates/jecoute/news/news_list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review
