Repository parti-renaissance/espace-adherent, pull requests merged in 2021-03, with the labels that each got.

#5393 [CommitteeElection] update vote/candidate Voter and wording
  features/admin/committee_merge.feature
  src/Collection/CommitteeMembershipCollection.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/Adherent.php
  src/Entity/CommitteeMembership.php
  src/Repository/CommitteeRepository.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Security/ElectionAuthorisationChecker.php
  templates/adherent_profile/activity/_committees.html.twig
  templates/committee/_election_box.html.twig
Labels: Ready for code review

#5396 [Committee] Prevent adherent leaving committee during an election
  features/committee_vote.feature
  src/Security/Voter/Committee/FollowerCommitteeVoter.php
Labels: Ready for code review

#5397 [Committee] Update vote status on candidacy/vote
  src/Committee/EventListener/UpdateVotingCommitteeOnCandidateListener.php
  src/Entity/Adherent.php
  src/VotingPlatform/Election/Event/NewVote.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  templates/referent/committee/available_committees_for_partials.html.twig
Labels: Ready for code review

#5401 [Admin] Fix ban adherent
  config/packages/security.yaml
Labels: Ready for code review

#5403 [Coalition] disable coalition pagination
  features/api/causes.feature
  features/api/coalitions.feature
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/Coalition.php
Labels: Ready for code review

#5405 [CommitteeElection] fix wording on election box
  features/committee_vote.feature
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/adherent/my_activity_committees.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/committee/_election_box.html.twig
  templates/committee_designation/list.html.twig
  templates/committee_designation/show_layout.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/territorial_council_designation/election_results/show_layout.html.twig
  templates/territorial_council_designation/list.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5404 [Committee] Fix committee address validator
  src/Repository/CommitteeRepository.php
  src/Validator/UniqueCommitteeValidator.php
Labels: Ready for code review

#5406 [CommitteeElection] add button for updating a candidacy
  templates/committee/_election_box.html.twig
Labels: Bug, Ready for code review

#5388 [TerritorialCouncil] Add tests for update memberships command
  src/Entity/Adherent.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  src/TerritorialCouncil/Handlers/TerritorialCouncilActiveMandateHandler.php
  src/TerritorialCouncil/PoliticalCommitteeManager.php
  templates/referent/territorial_council/members.html.twig
  tests/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandlerTest.php
  tests/TerritorialCouncil/PoliticalCommitteeManagerTest.php
Labels: Ready for code review

#5402 [CommitteeElection] prevent candidate unregistration
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Security/Voter/AdherentUnregistrationVoter.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Security/Voter/AdherentUnregistrationVoterTest.php
Labels: Ready for code review

#5407 [EM-405][MunicipalEvent] fix event show page
  src/DataFixtures/ORM/LoadMunicipalEventData.php
  src/Entity/Event/MunicipalEvent.php
  tests/Command/ApiScheduleEventCreationCommandTest.php
  tests/Controller/Api/Event/EventsControllerTest.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/ApiControllerTestTrait.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Repository/EventRepositoryTest.php
Labels: Bug, Ready for code review

#5409 [Admin] Fix designation edit form
  src/Admin/Designation/VotingPlatformElectionAdmin.php
  src/Form/Admin/DesignationTypeType.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  tests/Controller/Api/Event/EventsControllerTest.php
Labels: Bug, Ready for code review

#5372 [Coalition][API] Add follow/unfollow a coalition or a cause
  features/api/causes.feature
  features/api/coalitions.feature
  features/api/events.feature
  migrations/Version20210303175731.php
  src/Controller/Api/FollowController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/Entity/AbstractFollower.php
  src/Entity/Coalition/Cause.php
  src/Entity/Coalition/CauseFollower.php
  src/Entity/Coalition/Coalition.php
  src/Entity/Coalition/CoalitionFollower.php
  src/Entity/EntityFollowersTrait.php
  src/Entity/FollowedInterface.php
  src/Entity/FollowerInterface.php
  src/Entity/IdeasWorkshop/Thread.php
  src/Entity/IdeasWorkshop/ThreadComment.php
Labels: Ready for code review

#5418 [Mailchimp] Fix update committee tags
  src/Committee/EventListener/UpdateMembersWithMailchimpListener.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#5413 [VotingPlatform] close/create supervisor mandates
  src/Admin/Committee/CommitteeAdherentMandateTypeEnum.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
  src/Entity/VotingPlatform/Election.php
  src/Entity/VotingPlatform/ElectionResult/ElectionResult.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
Labels: Ready for code review

#5424 [CommitteeElection] improve committee designation list pages
  src/Committee/Filter/CommitteeDesignationsListFilter.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Repository/CommitteeElectionRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
  templates/committee/_election_box.html.twig
  templates/committee_designation/list.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/referent/committee/list.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
Labels: Ready for code review

#5416 Création du réseau avant le make
  docs/1-Installer-le-projet-en-local.md
Labels: Documentation

#5436 [CommitteeMerge] add Mailchimp sync trigger
  src/Committee/CommitteeMergeCommandHandler.php
  src/Committee/Event/CommitteeMergeEvent.php
  src/Mailchimp/Synchronisation/Command/SyncAllMembersOfCommitteeCommand.php
  src/Mailchimp/Synchronisation/EventListener/SyncCommitteeAfterMergeListener.php
  src/Mailchimp/Synchronisation/Handler/SyncAllMembersOfCommitteeCommandHandler.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/CommitteeMembershipRepository.php
Labels: Ready for code review

#5433 Update React, React-dom, mocha-webpack and eslint packages
  .eslintrc.js
  front/app.js
  front/components/AdherentCommitteeList.js
  front/components/AlgoliaSearch.js
  front/components/AmountChooser.js
  front/components/CandidaciesListWidget.js
  front/components/CommitteeCandidacyWidget.js
  front/components/DataGrid.js
  front/components/DonationAmountChooser.js
  front/components/FacebookPictureChooser.js
  front/components/Loader.js
  front/components/MessageStatisticsWidget.js
  front/components/MessageStatusLoader.js
  front/components/Modal.js
  front/components/ProgrammaticFoundation/Approach.js
  front/components/ProgrammaticFoundation/Breadcrumbs.js
  front/components/ProgrammaticFoundation/Content.js
  front/components/ProgrammaticFoundation/Measure.js
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/components/ProgrammaticFoundation/Project.js
  front/components/ProgrammaticFoundation/SearchBar.js
  front/components/ProgrammaticFoundation/SearchResults.js
  front/components/ProgrammaticFoundation/SubApproach.js
  front/components/ProgrammaticFoundation/ToggleLeadingMeasures.js
  front/components/TerritorialCouncilCandidacyWidget.js
  front/components/UserListDefinitionWidget.js
  front/components/UserSegmentWidget.js
  front/components/VoteCommitteeWidget.js
  front/kernel.js
  front/listeners/amount-chooser.js
  front/listeners/confirm-modal.js
  front/pages/board_member_list.js
  front/services.js
  front/services/address/AddressForm.js
  front/services/address/AddressObject.js
  front/services/address/AutocompletedAddressForm.js
  front/services/address/GooglePlaceAutocomplete.js
  front/services/api/ReqwestApiClient.js
  front/services/datagrid/DataGridFactory.js
  front/services/datagrid/SearchEngine.js
  front/services/donation/TaxReturnProvider.js
  front/services/form/CKEditor.js
  front/services/form/DateFieldsSynchronizer.js
  front/services/map/MapFactory.js
  front/services/programmatic-foundation/SearchEngine.js
  front/services/slugifier/Slugifier.js
  front/services/utils/countdownClock.js
  front/services/utils/imageCropper.js
  front/services/vote/VoteLocationForm.js
  front/services/vote/VoteLocationFormFactory.js
  front/tests/donation/TaxReturnProviderTest.js
  front/tests/sharer/ShareDialogFactoryTest.js
  package.json
  yarn.lock
Labels: Ready for code review

#5440 Eslint update to latest version
  front/components/ProgrammaticFoundation/Content.js
  front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
  front/kernel.js
  front/pages/citizen_project_image_generator.js
  front/pages/manage_participants.js
  front/pages/message_filters.js
  front/pages/report.js
  front/services/slugifier/Slugifier.js
  front/services/utils/imageCropper.js
  package.json
  yarn.lock
Labels: Ready for code review

#5447 [CoTerr] fix command for adherent with many committee mandates
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  tests/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandlerTest.php
Labels: Bug, Ready for code review

#5448 Update node-sass to 5.0.0
  package.json
  yarn.lock
Labels: Ready for code review

#5445 Create endpoint to filter zones by name & type
  config/services/services.xml
  features/api/zones.feature
  migrations/Version20210312122341.php
  src/DataFixtures/ORM/LoadGeoZoneData.php
  src/Doctrine/GeoZoneExtension.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
Labels: Ready for code review

#5456 [NationalCouncil] some wording updates
  front/components/NationalCouncilCandidacyWidget.js
  front/style/pages/_territorial-council.scss
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Security/Voter/TerritorialCouncil/CandidatureVoter.php
  src/Twig/TerritorialCouncilExtension.php
  src/Twig/TerritorialCouncilRuntime.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
  templates/territorial_council/_layout.html.twig
  templates/territorial_council/_main_layout.html.twig
  templates/territorial_council/candidacy_invitation/_national_council_layout.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/territorial_council/partials/_my_candidate_invitations.html.twig
  templates/territorial_council/partials/_nav.html.twig
  templates/territorial_council/partials/_sidebar.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#5454 [Mailchimp][Jecoute][Candidate] Sync contacts with Mailchimp + Send messages to Jecoute contacts
  .env
  config/services/mailchimp.yaml
  config/services/services.xml
  front/style/manager-space/_base-layout.scss
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Filter/FilterFormFactory.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/Command/MailchimpSyncJecouteCommand.php
  src/Controller/Api/ZoneController.php
  src/Controller/EnMarche/AdherentMessage/CandidateJecouteMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/CandidateJecouteMessage.php
  src/Entity/AdherentMessage/Filter/JecouteFilter.php
  src/Entity/Geo/Zone.php
  src/Form/AdherentMessage/JecouteFilterType.php
  src/Geo/ManagedZoneProvider.php
  src/Geo/ZoneMatcher.php
  src/Jecoute/DataSurveyAnswerHandler.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/JecouteConditionBuilder.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Command/DataSurveyCommandInterface.php
  src/Mailchimp/Synchronisation/Command/DataSurveyCreateCommand.php
  src/Mailchimp/Synchronisation/Handler/DataSurveyCreateCommandHandler.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/Jecoute/DataSurveyRepository.php
  templates/candidate/_sidebar.html.twig
  templates/message/_base_candidate_jecoute.html.twig
  templates/message/filter/candidate_jecoute.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#5461 [Mailchimp][Jecoute][Candidate] Add canary mode
  src/Controller/EnMarche/AdherentMessage/CandidateJecouteMessageController.php
  templates/candidate/_sidebar.html.twig
Labels: Ready for code review

#5459 [Cookiebot] Replace document.write by document.createElement
  templates/base.html.twig
Labels: Ready for code review

#5460 [NationalCouncil] Referent can update vote dates
  config/services.yaml
  src/Form/TerritorialCouncil/EditDesignationType.php
  src/TerritorialCouncil/Designation/UpdateDesignationHandler.php
  src/TerritorialCouncil/Designation/UpdateDesignationRequest.php
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignation.php
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignationValidator.php
  templates/territorial_council_designation/convocation.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#5457 Create endpoint to check if causes are followed
  features/api/causes.feature
  src/Controller/Api/Coalition/CauseController.php
  src/Repository/Coalition/CauseRepository.php
Labels: Ready for code review

#5321 Profile API
  features/api/profile.feature
  features/bootstrap/JsonContext.php
  features/bootstrap/RestContext.php
  src/Address/Address.php
  src/AdherentProfile/AdherentProfile.php
  src/AdherentProfile/AdherentProfileConfiguration.php
  src/AdherentProfile/AdherentProfileHandler.php
  src/Controller/Api/ProfileController.php
  src/Controller/EnMarche/UserController.php
  src/DataFixtures/ORM/LoadClientData.php
  src/Entity/Adherent.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/PostAddress.php
  src/Entity/SubscriptionType.php
  src/Form/AddressType.php
  src/Intl/FranceCitiesBundle.php
  src/Normalizer/AddressDenormalizer.php
  src/Normalizer/AdherentNormalizer.php
  src/Normalizer/PhoneNumberNormalizer.php
  src/OAuth/Model/Scope.php
  src/Subscription/SubscriptionHandler.php
  translations/validators.fr.yml
Labels: Ready for code review

#5462 [VotingPlatform] fix candidates list template name
  templates/voting_platform/results/_candidates_list.html.twig
Labels: Bug, Ready for code review

#5465 Add certified information on profile API
  features/api/adherents.feature
  features/api/profile.feature
  features/api/user.feature
  src/Entity/Adherent.php
Labels: Ready for code review

#5466 [Candidate] Add delegated access to news
  src/Controller/EnMarche/Jecoute/News/NewsCandidateController.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Security/Voter/DelegatedAccessesVoter.php
  templates/candidate/_sidebar.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5343 Polls
  config/services/admin.xml
  features/api/polls.feature
  migrations/Version20210318134314.php
  src/Admin/Poll/PollAdmin.php
  src/Controller/Api/PollController.php
  src/DataFixtures/ORM/LoadPollData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Poll/Choice.php
  src/Entity/Poll/Poll.php
  src/Entity/Poll/Vote.php
  src/Form/Admin/PollChoiceType.php
  src/Repository/Poll/ChoiceRepository.php
  src/Repository/Poll/PollRepository.php
  src/Repository/Poll/VoteRepository.php
  templates/admin/poll/list_created_by.html.twig
  templates/admin/poll/show.html.twig
Labels: Je Marche !, Ready for code review

#5468 [Candidate] Add region edit page + delegated access
  config/packages/security.yaml
  config/services/admin.xml
  src/Admin/Jecoute/RegionAdmin.php
  src/Controller/EnMarche/Jecoute/JecouteRegionController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/Geo/Zone.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Form/Jecoute/RegionType.php
  src/Jecoute/RegionManager.php
  src/Repository/Geo/RegionRepository.php
  src/Security/Voter/DelegatedAccessesVoter.php
  templates/candidate/_sidebar.html.twig
  templates/jecoute/edit_region.html.twig
  tests/Controller/EnMarche/Jecoute/JecouteRegionControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5470 [CommitteeCandidacy] fix invitation form
  front/app.js
  front/components/CommitteeCandidacyWidget.js
  front/pages/committee_candidacy.js
  src/Committee/Election/CandidacyManager.php
  src/Entity/CommitteeCandidacy.php
  src/Form/Committee/CandidacyBinomeType.php
  templates/committee/candidacy/candidacy_invitation.html.twig
  tests/Controller/EnMarche/CommitteeDesignation/CandidatureControllerTest.php
  translations/messages.fr.yml
Labels: Bug, Ready for code review

#5474 [VotingPlatform] Add CandidaciesGroup entity for keeping all candidacies together
  migrations/Version20210319175244.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Committee/Election/CandidacyManager.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/CommitteeCandidaciesGroup.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/TerritorialCouncil/CandidaciesGroup.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/VotingPlatform/Designation/BaseCandidaciesGroup.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Entity/VotingPlatform/ElectionResult/ElectionResult.php
  src/Form/TerritorialCouncil/CandidacyQualityType.php
  src/Normalizer/Indexer/CommitteeCandidatureNormalizer.php
  src/Normalizer/Indexer/TerritorialCouncilCandidatureNormalizer.php
  src/Repository/CommitteeCandidacyRepository.php
  src/Repository/TerritorialCouncil/CandidacyRepository.php
  src/TerritorialCouncil/Candidacy/SearchAvailableMembershipFilter.php
  src/TerritorialCouncil/CandidacyManager.php
  src/Validator/TerritorialCouncil/ValidSearchAvailableMembershipFilter.php
  src/Validator/TerritorialCouncil/ValidSearchAvailableMembershipFilterValidator.php
  templates/committee/_election_box.html.twig
  templates/committee/candidacy/candidacy_list.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Work in progress

#5479 [Referent] Remove questions field from designation form
  migrations/Version20210324150101.php
  src/Entity/TerritorialCouncil/Election.php
  src/Form/TerritorialCouncil/EditDesignationType.php
  src/Mailer/Message/TerritorialCouncilElectionConvocationMessage.php
  src/TerritorialCouncil/Designation/UpdateDesignationHandler.php
  src/TerritorialCouncil/Designation/UpdateDesignationRequest.php
  templates/territorial_council_designation/convocation.html.twig
Labels: Ready for code review

#4471 Remove ElectedRepresentativesRegister entity
  migrations/Version20200512154124.php
  src/Entity/ElectedRepresentativesRegister.php
Labels: Don't merge, Ready for code review

#2297 Add Session TTL with Remember me feature
  config/packages/doctrine.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20210324151041.php
  src/Security/AdherentLoginTimestampRecorder.php
  templates/security/adherent_login.html.twig
Labels: Ready for code review

#5483 [CodeQuality] use Sf contract Translator interface
  src/Adherent/AdherentExtractCommandHandler.php
  src/Adherent/Certification/CertificationRequestNotifier.php
  src/AdherentMessage/MailchimpCampaign/Handler/ElectedRepresentativeMailchimpCampaignHandler.php
  src/Admin/JecouteLocalSurveyAdmin.php
  src/Assessor/AssessorRequestNotifier.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Controller/Admin/AdminTerritorialCouncilMembershipLogController.php
  src/Controller/Api/ReportController.php
  src/Controller/EnMarche/SearchController.php
  src/Donation/DonatorExtractCommandHandler.php
  src/Exporter/AssessorsExporter.php
  src/Exporter/SurveyExporter.php
  src/Exporter/TerritorialCouncilMembersExporter.php
  src/Extract/AbstractEmailExtractCommandHandler.php
  src/Form/AdherentMessage/ElectedRepresentativeFilterType.php
  src/Mailchimp/Synchronisation/ElectedRepresentativeTagsBuilder.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  src/OAuth/Form/ScopesType.php
  src/Timeline/TimelineImageFactory.php
  src/Validator/ChezVous/MeasurePayloadValidator.php
  src/Validator/TerritorialCouncil/UniqueTerritorialCouncilMemberValidator.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
Labels: Ready for code review

#5485 [Test] Fix translator interface in tests
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Validator/TerritorialCouncil/UniqueTerritorialCouncilMemberValidatorTest.php
Labels: Bug, Ready for code review

#5482 [Candidacy] Remove my invitations if I accept one
  src/Committee/Election/CandidacyManager.php
  src/Committee/EventListener/DeclinePendingCandidacyInvitationsListener.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Entity/VotingPlatform/Designation/CandidacyInvitationInterface.php
  src/TerritorialCouncil/CandidacyManager.php
  src/TerritorialCouncil/Events.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Events.php
  src/VotingPlatform/Listener/DeclinePendingCandidacyInvitationsListener.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5486 Update FAQ
  templates/territorial_council/faq.html.twig
Labels: Work in progress

#5477 [Mailchimp][Jecoute][Candidate] Remove canary mode
  src/Controller/EnMarche/AdherentMessage/CandidateJecouteMessageController.php
  templates/candidate/_sidebar.html.twig
Labels: Needs product go/no go, Ready for code review

#5487 [VotingPlatform] update invitation emails
  src/Committee/Election/CandidacyManager.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Mailer/Message/AbstractVotingPlatformCandidacyInvitationMessage.php
  src/Mailer/Message/AbstractVotingPlatformMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationAcceptedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationCreatedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationDeclinedMessage.php
  src/Mailer/Message/VotingPlatformCandidacyInvitationRemovedMessage.php
  src/TerritorialCouncil/CandidacyManager.php
  src/VotingPlatform/Event/CandidacyInvitationEvent.php
  src/VotingPlatform/Listener/DeclinePendingCandidacyInvitationsListener.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
Labels: Ready for code review

#5491 Display Homepage modal for supervisor election only
  src/Adherent/SessionModal/SessionModalActivatorListener.php
Labels: Ready for code review

#5492 [VotingPlatform] improve email by extending abstract template
  src/Mailer/Message/VotingPlatformElectionSecondRoundNotificationMessage.php
  src/Mailer/Message/VotingPlatformElectionVoteConfirmationMessage.php
  src/Mailer/Message/VotingPlatformElectionVoteIsOpenMessage.php
  src/Mailer/Message/VotingPlatformElectionVoteIsOverMessage.php
  src/Mailer/Message/VotingPlatformPartialElectionIsOpenMessage.php
Labels: Ready for code review

#5493 [CANDIDATE] Fix delegated access to files in space
  src/Security/Voter/Filesystem/DownloadFileVoter.php
  tests/Controller/ControllerTestTrait.php
  tests/Controller/EnMarche/Filesystem/CandidateFilesControllerTest.php
Labels: Ready for code review

#5494 [Docker] remove empty lines
  Dockerfile
  docker/dev/Dockerfile
Labels: Ready for code review

#5496 [Committee] Fix committee candidacy acceptation step
  src/Committee/Election/CandidacyManager.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/CommitteeMembership.php
  templates/committee/candidacy/candidacy_list.html.twig
Labels: Bug, Ready for code review

#5495 [CoTerr] rename candidaciesGroup table
  .circleci/config.yml
  migrations/Version20210329151215.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/TerritorialCouncil/CandidaciesGroup.php
  src/Entity/TerritorialCouncil/Candidacy.php
Labels: Ready for code review

#5489 [Coalition][API] Follow/unfollow a cause as not connected user
  dump/all-geo-zone.sql
  features/api/causes.feature
  migrations/Version20210326120302.php
  src/Controller/Api/Coalition/CauseAnonymousFollowerController.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/DataFixtures/ORM/LoadGeoZoneData.php
  src/Entity/Coalition/CauseFollower.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Repository/Coalition/CauseFollowerRepository.php
  src/Validator/Coalition/CauseFollowerEmail.php
  src/Validator/Coalition/CauseFollowerEmailValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#5503 [Config] Fix Doctrine cache config
  config/packages/prod/doctrine.yaml
Labels: Bug, Ready for code review

#5498 [PHP] Update Symfony 4.4.21
  composer.json
  composer.lock
  symfony.lock
  translations/validators.fr.yml
Labels: Ready for code review, dependencies

#5463 [EM-479] Activate POST endpoint for Causes
  features/api/causes.feature
  migrations/Version20210331134337.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/Entity/Coalition/Cause.php
  src/Entity/EntityNameSlugTrait.php
Labels: Ready for code review
