Repository parti-renaissance/espace-adherent, pull requests merged in 2021-08, with the labels that each got.

#6092 [PHP] Update Symfony
  composer.lock
Labels: Ready for code review, composer, dependencies

#6095 [Admin] Add Ripostes
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20210803141208.php
  src/Admin/Jecoute/RiposteAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadJecouteRiposteData.php
  src/Entity/Jecoute/Riposte.php
  templates/admin/jecoute/riposte/list_creator.html.twig
Labels: Ready for code review

#6097 [API] Get Ripostes
  config/services/services.xml
  features/api/jecoute_ripostes.feature
  src/Api/Doctrine/JecouteRiposteExtension.php
  src/DataFixtures/ORM/LoadJecouteRiposteData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Jecoute/Riposte.php
Labels: Ready for code review

#6099 [API] Create and delete ripostes
  features/api/jecoute_ripostes.feature
  src/DataFixtures/ORM/LoadJecouteRiposteData.php
  src/Entity/AuthoredTrait.php
  src/Entity/Jecoute/Riposte.php
  src/Normalizer/UrlDenormalizer.php
Labels: Ready for code review

#6107 [Mailchimp] Sync certified as merge field
  src/Entity/Adherent.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#6104 [API] Endpoints for a AudienceSegment
  features/api/audience_segments.feature
  migrations/Version20210805173606.php
  src/DataFixtures/ORM/LoadAudienceSegmentData.php
  src/Entity/AdherentMessage/Filter/AbstractAdherentFilter.php
  src/Entity/AdherentMessage/Filter/AbstractAdherentMessageFilter.php
  src/Entity/AdherentMessage/Filter/AbstractUserFilter.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
  src/Entity/AdherentMessage/Filter/GeneralFilterTrait.php
  src/Entity/AdherentMessage/Segment/AudienceSegment.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Normalizer/AudienceFilterDenormalizer.php
  src/Normalizer/AudienceSegmentDenormalizer.php
Labels: Ready for code review

#6112 [Contacts] add column config endpoint
  src/Controller/Api/AdherentList/ColumnsConfigurationController.php
  src/Controller/Api/Audience/RetrieveAudiencesController.php
  src/Controller/Api/ScopeTrait.php
  src/ManagedUsers/ColumnsConfigurator.php
  src/Scope/AuthorizationChecker.php
  src/Scope/Exception/InvalidFeatureCodeException.php
  src/Scope/Exception/InvalidScopeException.php
  src/Scope/Exception/NotFoundScopeGeneratorException.php
  src/Scope/Exception/ScopeExceptionInterface.php
  src/Scope/Exception/ScopeQueryParamMissingException.php
  src/Scope/GeneralScopeGenerator.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Generator/CandidateScopeGenerator.php
  src/Scope/Generator/DeputyScopeGenerator.php
  src/Scope/Generator/NationalScopeGenerator.php
  src/Scope/Generator/ReferentScopeGenerator.php
  src/Scope/Generator/ScopeGeneratorInterface.php
  src/Scope/Generator/SenatorScopeGenerator.php
  src/Scope/Scope.php
  src/ValueObject/Genders.php
Labels: Ready for code review

#6113 Add ManagedUsersFilter factory
  config/services.yaml
  src/AdherentSpace/AdherentSpaceEnum.php
  src/Audience/AudienceHelper.php
  src/Committee/CommitteeSpaceEnum.php
  src/Controller/Api/ZoneController.php
  src/Controller/EnMarche/AccessDelegatorTrait.php
  src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
  src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
  src/Controller/EnMarche/AssessorSpace/MunicipalChiefAssessorSpaceController.php
  src/Controller/EnMarche/AssessorSpace/MunicipalManagerAssessorSpaceController.php
  src/Controller/EnMarche/AssessorSpace/MunicipalManagerSupervisorAssessorSpaceController.php
  src/Controller/EnMarche/AssessorSpace/ReferentAssessorSpaceController.php
  src/Controller/EnMarche/Committee/ReferentCommitteeController.php
  src/Controller/EnMarche/ElectedRepresentative/DeputyElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/SenatorElectedRepresentativeController.php
  src/Controller/EnMarche/ElectedRepresentative/SenatorialCandidateElectedRepresentativeController.php
  src/Controller/EnMarche/Election/VotePlaceResults/AssessorVoteResultController.php
  src/Controller/EnMarche/Election/VotePlaceResults/MunicipalChiefVoteResultController.php
  src/Controller/EnMarche/Election/VotePlaceResults/MunicipalManagerVoteResultController.php
  src/Controller/EnMarche/Election/VotePlaceResults/ReferentVoteResultController.php
  src/Controller/EnMarche/EventManager/CandidateEventManagerController.php
  src/Controller/EnMarche/EventManager/DeputyEventManagerController.php
  src/Controller/EnMarche/EventManager/ReferentEventManagerController.php
  src/Controller/EnMarche/EventManager/SenatorEventManagerController.php
  src/Controller/EnMarche/Filesystem/CandidateFilesController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/MunicipalChiefMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/MunicipalManagerSupervisorMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/ReferentMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MyTeam/DeputyMyTeamController.php
  src/Controller/EnMarche/MyTeam/SenatorMyTeamController.php
  src/Controller/EnMarche/Poll/PollCandidateController.php
  src/Controller/EnMarche/Poll/PollReferentController.php
  src/Entity/Audience/CandidateAudience.php
  src/Entity/Audience/DeputyAudience.php
  src/Entity/Audience/ReferentAudience.php
  src/Entity/Audience/SenatorAudience.php
  src/Exporter/ManagedUsersExporter.php
  src/Geo/ManagedZoneProvider.php
  src/ManagedUsers/Filter/AbstractFilterFactory.php
  src/ManagedUsers/Filter/CandidateFilterFactory.php
  src/ManagedUsers/Filter/DeputyFilterFactory.php
  src/ManagedUsers/Filter/ManagedUsersFilterFactoryInterface.php
  src/ManagedUsers/Filter/ReferentFilterFactory.php
  src/ManagedUsers/Filter/SenatorFilterFactory.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/ManagedUsers/ManagedUsersFilterFactory.php
  src/Poll/PollSpaceEnum.php
  src/Security/Voter/Audience/ManageAudienceVoter.php
Labels: Ready for code review

#6118 [JS] Replace Node-sass by Sass
  package.json
  yarn.lock
Labels: dependencies, Security, javascript, npm

#6117 [ManagedUsers] add API collection endpoint
  src/AdherentSpace/AdherentSpaceEnum.php
  src/Controller/Api/AdherentList/AdherentListController.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/Entity/EntityZoneTrait.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Event/EventMessageNotifier.php
  src/ManagedUsers/ColumnsConfigurator.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/ManagedUsers/ManagedUsersFilterFactory.php
  src/Normalizer/ManagedUserNormalizer.php
  src/Repository/Projection/ManagedUserRepository.php
  src/Scope/AuthorizationChecker.php
  tests/Controller/Api/AdherentList/AdherentListControllerTest.php
Labels: Ready for code review

#6122 Remove amp route in redirection listener
  src/ManagedUsers/ColumnsConfigurator.php
  src/Redirection/Dynamic/RedirectionsProvider.php
Labels: Ready for code review

#6119 [Scope] improve scope adherent check
  src/Scope/AuthorizationChecker.php
  src/Validator/ValidScopeValidator.php
Labels: Ready for code review

#6120 [Mailchimp] Send mail for an AudienceSegment
  features/api/adherent_messages.feature
  migrations/Version20210812102957.php
  src/AdherentMessage/Filter/AdherentMessageFilterInterface.php
  src/DataFixtures/ORM/LoadAdherentMessageData.php
  src/DataFixtures/ORM/LoadMunicipalEventData.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Entity/AdherentMessage/CandidateAdherentMessage.php
  src/Entity/AdherentMessage/DeputyAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AbstractAdherentMessageFilter.php
  src/Entity/AdherentMessage/ReferentAdherentMessage.php
  src/Entity/AdherentMessage/Segment/AudienceSegment.php
  src/Entity/AdherentMessage/SenatorAdherentMessage.php
  src/Entity/EntityIdentityTrait.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Normalizer/AudienceSegmentFromUuidDenormalizer.php
  src/Repository/AdherentMessage/Segment/AudienceSegmentRepository.php
  src/Validator/ValidMessageFilterSegment.php
  src/Validator/ValidMessageFilterSegmentValidator.php
  tests/Controller/EnMarche/AdherentMessage/ReferentMessageControllerTest.php
Labels: Ready for code review

#6124 Send update email when visioUrl of the event has been changed
  features/api/coalition_events.feature
  src/EventListener/SendEventUpdateNotificationListener.php
Labels: Ready for code review

#6126 Fix test with a specific date
  features/api/coalition_events.feature
Labels: Ready for code review

#6130 [API][Coalitions] Get event subscriptions
  features/api/coalition_events.feature
  features/api/events.feature
  src/Controller/Api/EventsController.php
  src/DataFixtures/ORM/LoadCauseEventData.php
  src/Exporter/EventRegistrationExporter.php
  tests/Controller/Api/EventsControllerTest.php
Labels: Ready for code review

#6133 [API][Events] Impossible to subscribe to a cancelled event
  features/api/coalition_events.feature
  src/Controller/Api/Event/SubscribeAsAdherentController.php
  src/Controller/Api/Event/SubscribeAsAnonymousController.php
  tests/Controller/Api/Event/SubscribeAsAdherentControllerTest.php
  tests/Controller/Api/Event/SubscribeAsAnonymousControllerTest.php
Labels: Ready for code review

#6129 Keep only one entity for Audience
  features/api/audiences.feature
  migrations/Version20210818093317.php
  src/Audience/AudienceHelper.php
  src/Audience/AudienceTypeEnum.php
  src/Controller/Api/Audience/RetrieveAudiencesController.php
  src/DataFixtures/ORM/LoadAudienceData.php
  src/Entity/Audience/Audience.php
  src/Entity/Audience/AudienceTypeEnum.php
  src/Entity/Audience/CandidateAudience.php
  src/Entity/Audience/DeputyAudience.php
  src/Entity/Audience/ReferentAudience.php
  src/Entity/Audience/SenatorAudience.php
  src/Entity/EntityZoneTrait.php
  src/Entity/ZoneableEntity.php
  src/Normalizer/AudienceDenormalizer.php
  src/Repository/Audience/AbstractAudienceRepository.php
  src/Repository/Audience/AudienceRepository.php
  src/Repository/Audience/CandidateAudienceRepository.php
  src/Repository/Audience/DeputyAudienceRepository.php
  src/Repository/Audience/ReferentAudienceRepository.php
  src/Repository/Audience/SenatorAudienceRepository.php
  src/Scope/AuthorizationChecker.php
  src/Security/Voter/Audience/CreateAudienceVoter.php
  src/Security/Voter/Audience/ManageAudienceVoter.php
  src/Security/Voter/ManageZoneableItemVoter.php
  src/Security/Voter/RequestScopeVoter.php
  src/Validator/AbstractInManagedZoneValidator.php
  src/Validator/ManagedZone.php
  src/Validator/ManagedZoneValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#6131 [API] Add PUT riposte endpoint + some other changes
  config/services/services.xml
  features/api/jecoute_ripostes.feature
  src/Api/Doctrine/JecouteRiposteExtension.php
  src/Api/Filter/ActiveRipostesFilter.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Jecoute/Riposte.php
Labels: Ready for code review

#6132 Add teams administration
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20210820093550.php
  src/Admin/AdherentAdmin.php
  src/Admin/Reporting/TeamMemberHistoryAdmin.php
  src/Admin/Team/MemberAdmin.php
  src/Admin/Team/TeamAdmin.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/Adherent.php
  src/Entity/EntityAdministratorTrait.php
  src/Entity/Reporting/TeamMemberHistory.php
  src/Entity/Team/Member.php
  src/Entity/Team/Team.php
  src/Form/Admin/Team/MemberAdherentAutocompleteType.php
  src/Form/Admin/Team/MemberType.php
  src/Form/Admin/Team/TeamType.php
  src/Repository/Team/MemberRepository.php
  src/Repository/Team/TeamRepository.php
  src/Team/TeamMemberHistoryManager.php
  src/Team/TypeEnum.php
  templates/admin/reporting/team_member_history/list_action.html.twig
  templates/admin/reporting/team_member_history/list_adherent.html.twig
  templates/admin/team/_list_members.html.twig
  templates/admin/team/_list_type.html.twig
  templates/admin/team/member_type_model_autocomplete.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#6136 Add phoning scope
  features/api/scopes.feature
  src/DataFixtures/ORM/LoadScopeData.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/Adherent.php
  src/Entity/Team/Team.php
  src/Scope/AppEnum.php
  src/Scope/Generator/PhoningScopeGenerator.php
  src/Scope/ScopeEnum.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#5848 Update Ubuntu to v20.04
  Dockerfile
  composer.json
  composer.lock
  docker/dev/Dockerfile
  symfony.lock
  tests/Controller/EnMarche/AbstractEventControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  tests/Controller/EnMarche/EventControllerTest.php
  tests/Controller/EnMarche/EventManager/CoalitionEventManagerControllerTest.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Controller/EnMarche/UserControllerTest.php
Labels: Ready for code review

#6135 Add SMS campaign admin
  config/services/admin.xml
  migrations/Version20210820173926.php
  src/Admin/AbstractAdmin.php
  src/Admin/Audience/AudienceAdmin.php
  src/Admin/SmsCampaignAdmin.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/Admin/AdminSmsCampaignCRUDController.php
  src/Entity/Audience/AbstractAudience.php
  src/Entity/Audience/Audience.php
  src/Entity/Audience/AudienceFieldsTrait.php
  src/Entity/Audience/AudienceInterface.php
  src/Entity/Audience/AudienceSnapshot.php
  src/Entity/EntityReferentTagTrait.php
  src/Entity/EntityZoneTrait.php
  src/Entity/ReferentOrganizationalChart/PersonOrganizationalChartItem.php
  src/Entity/SmsCampaign.php
  src/Entity/ZoneableEntity.php
  src/Entity/ZoneableWithScopeEntity.php
  src/Form/Admin/AdminZoneAutocompleteType.php
  src/Form/Admin/DonatorKinshipType.php
  src/Form/Admin/Team/MemberAdherentAutocompleteType.php
  src/Form/Audience/AudienceSnapshotType.php
  src/Repository/AdherentRepository.php
  src/Security/Voter/ManageZoneableItemVoter.php
  src/SmsCampaign/Command/SendSmsCampaignCommand.php
  src/SmsCampaign/SmsCampaignStatusEnum.php
  templates/admin/elected_representative/label_name_type_model_autocomplete.html.twig
  templates/admin/form/sonata_type_model_autocomplete.html.twig
  templates/admin/sms_campaign/CRUD/list__action_confirm.html.twig
  templates/admin/sms_campaign/CRUD/list__action_edit.html.twig
  templates/admin/sms_campaign/confirm.html.twig
  templates/admin/sms_campaign/edit.html.twig
  templates/admin/team/member_type_model_autocomplete.html.twig
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#6137 Add phoning campaigns
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20210824151807.php
  src/Admin/AdministratorAdmin.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Admin/Team/TeamAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/Phoning/Campaign.php
  src/Form/Admin/Team/TeamTypeType.php
Labels: Ready for code review

#6147 [AdherentMessage] Fix denormalization of cause for adherent message f…
  src/Entity/AdherentMessage/Filter/AbstractAdherentMessageFilter.php
  src/Entity/AdherentMessage/Filter/CoalitionsFilter.php
  src/Normalizer/CauseFromUuidDenormalizer.php
  tests/Controller/Api/AdherentMessage/AdherentMessageControllerTest.php
Labels: Bug, Ready for code review

#6146 Update Nodejs to v14
  docker/dev/Dockerfile
Labels: Work in progress

#6145 [API] Get my phoning campaigns
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/MyPhoningCampaignsController.php
  src/Entity/Phoning/Campaign.php
  src/Repository/Phoning/CampaignRepository.php
Labels: Ready for code review

#6152 [Newsletter] disable temporarily newsletter form
  src/Controller/EnMarche/NewsletterController.php
  templates/home/index.html.twig
Labels: Ready for code review

#6165 [PHP] Update Symfony to 4.4.30
  composer.lock
Labels: dependencies, composer

#6169 [PhoningCampaign] update start response payload
  features/api/phoning_campaigns.feature
  src/Controller/Api/Phoning/StartCampaignController.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/Entity/Adherent.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/Phoning/CampaignHistory.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6170 [Jecoute] Set nullable Question type argument
  src/Entity/Jecoute/Question.php
Labels: Bug, Ready for code review
