Repository parti-renaissance/espace-adherent, pull requests merged in 2021-01, with the labels that each got.

#5239 Change committee creation page
  front/app.js
  front/services/address/AddressObject.js
  front/services/address/AutocompletedAddressForm.js
  front/services/address/GooglePlaceAutocomplete.js
  front/style/pages/_committee.scss
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeCreationCommandHandler.php
  src/Committee/CommitteeUpdateCommandHandler.php
  src/Controller/EnMarche/AdherentController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Form/CommitteeCommandType.php
  src/Form/CreateCommitteeCommandType.php
  src/Security/Voter/Committee/CreateCommitteeVoter.php
  templates/adherent/create_committee.html.twig
  templates/adherent/profile.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/citizen_project/edit.html.twig
  templates/committee/_form.html.twig
  templates/committee/show.html.twig
  templates/committee_manager/_sidebar.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/committee_manager/edit.html.twig
  templates/javascript.js.twig
  templates/thematic_community/join.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
  tests/Security/Voter/Committee/CreateCommitteeVoterTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5247 [Election] update committee election reminder message
  migrations/Version20210105162229.php
  src/Command/VotingPlatform/SendVoteReminderCommand.php
  src/Entity/Adherent.php
  src/Mailer/Message/CommitteeElectionVoteReminderMessage.php
  src/Mailer/Message/VotingPlatformVoteReminderMessage.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/VotingPlatform/VoterRepository.php
  src/VotingPlatform/Listener/NotifierListener.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  src/VotingPlatform/Notifier/Event/AbstractEvent.php
  src/VotingPlatform/Notifier/Event/AbstractVotingPlatformElectionEvent.php
  src/VotingPlatform/Notifier/Event/CommitteeElectionVoteReminderEvent.php
  src/VotingPlatform/Notifier/Event/VotingPlatformVoteReminderEvent.php
Labels: Ready for code review

#5252 [VotingPlatform] add election type to reminder message
  src/Mailer/Message/VotingPlatformVoteReminderMessage.php
Labels: Bug, Ready for code review

#5250 Update sf 4.4.18
  composer.lock
Labels: Ready for code review

#5257 [VotingPlatform] sort candidates groups on result page
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  templates/voting_platform/results/_majority_vote_bulletins_list.html.twig
Labels: Ready for code review

#5258 [VotingPlatform] minors fixes of majority vote result page
  front/style/voting-platform/_results.scss
  src/Command/VotingPlatform/SendVoteReminderCommand.php
  src/Repository/CommitteeMembershipRepository.php
  templates/voting_platform/results/_majority_vote_candiates_list.html.twig
  templates/voting_platform/results/_stats_block.html.twig
Labels: Bug, Ready for code review

#5262 [VotingPlatform] hotfix: handle election without votes
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/MajorityJudgment/Election.php
  src/MajorityJudgment/Processor.php
Labels: Bug

#5263 [VotingPlatform] use EnMarche external lib MajorityJudgment
  composer.json
  composer.lock
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/MajorityJudgment/Candidate.php
  src/MajorityJudgment/Election.php
  src/MajorityJudgment/Mention.php
  src/MajorityJudgment/Merit.php
  src/MajorityJudgment/Processor.php
  src/MajorityJudgment/Vote.php
  src/MajorityJudgment/VotingProfile.php
  symfony.lock
  tests/MajorityJudgment/ProcessorTest.php
Labels: Ready for code review

#5265 Disallow index documents endpoint
  public/robots.txt
Labels: Ready for code review

#5266 Pad insee code to 5 digits on zone matching
  src/Geo/ZoneMatcher.php
Labels: Ready for code review

#5267 [VotingPlatform] fix majority mention badge if 0 vote
  templates/voting_platform/results/_majority_vote_bulletins_list.html.twig
  templates/voting_platform/results/_majority_vote_candiates_list.html.twig
Labels: Ready for code review

#5241 [Referent space] Add committee creation and committees lists
  front/style/layout/_buttons.scss
  front/style/manager-space/_tables.scss
  front/style/mixins/_colors.scss
  front/style/pages/_committee.scss
  migrations/Version20210113120839.php
  src/Address/Address.php
  src/Address/NullableAddress.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeCreationCommand.php
  src/Committee/CommitteeCreationCommandHandler.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteeSpaceEnum.php
  src/Committee/Exception/CommitteeProvisionalSupervisorException.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/Committee/ReferentCommitteeController.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/Adherent.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Entity/AdherentMandate/CommitteeMandateQualityEnum.php
  src/Entity/Committee.php
  src/Entity/ProvisionalSupervisor.php
  src/Form/Committee/ProvisionalSupervisorType.php
  src/Form/CommitteeCommandType.php
  src/Intl/FranceCitiesBundle.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/Geo/ZoneRepository.php
  src/Security/Voter/Committee/CreateCommitteeVoter.php
  src/Twig/AdherentExtension.php
  src/Twig/AdherentRuntime.php
  src/Validator/CommitteeAddress.php
  src/Validator/CommitteeAddressValidator.php
  src/Validator/CommitteeProvisionalSupervisor.php
  src/Validator/CommitteeProvisionalSupervisorValidator.php
  templates/adherent/create_committee.html.twig
  templates/adherent_profile/activity/_committees.html.twig
  templates/committee/_form.html.twig
  templates/committee_manager/edit.html.twig
  templates/form_theme.html.twig
  templates/referent/_sidebar.html.twig
  templates/referent/committees_list.html.twig
  templates/referent/committees_requests_list.html.twig
  templates/referent/create_committee.html.twig
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  tests/Security/Voter/Committee/CreateCommitteeVoterTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#5273 [CI] fix paybox related test by adding amount arg to callback URL
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Bug, Ready for code review

#5272 Hide adherent modal session content from page
  templates/components/_adherent_session_modal.html.twig
Labels: Bug, Ready for code review

#5271 Add footer links for all spaces
  templates/adherent_space/_layout.html.twig
  templates/candidate/_layout.html.twig
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/_space_layout.html.twig
  templates/committee_manager/dashboard.html.twig
  templates/components/_footer.html.twig
  templates/components/_footer_cgu.html.twig
  templates/coordinator/_layout.html.twig
  templates/deputy/_layout.html.twig
  templates/jecoute/_manager_space_layout.html.twig
  templates/legislative_candidate/_layout.html.twig
  templates/lre/_layout.html.twig
  templates/referent/_layout.html.twig
  templates/senator/_layout.html.twig
  templates/thematic_community/_layout_thematic_community_chief.html.twig
Labels: Ready for code review

#5254 [Referent] Add committee pre-accept and pre-refuse actions
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeCreationCommandHandler.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteePermissions.php
  src/Committee/CommitteeUpdateCommandHandler.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Entity/Committee.php
  src/Form/Committee/ProvisionalSupervisorType.php
  src/Form/CommitteeCommandType.php
  src/Repository/Geo/ZoneRepository.php
  src/Security/Voter/Committee/PreApprovePreRefuseCommitteeVoter.php
  templates/committee/_form.html.twig
  templates/committee_manager/edit.html.twig
  templates/coordinator/_committee_list.html.twig
  templates/form_theme.html.twig
  templates/referent/committee/create.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/referent/committee/list.html.twig
  templates/referent/committee/pre_approve.html.twig
  templates/referent/committee/requests_list.html.twig
  templates/referent/committees_requests_list.html.twig
  templates/territorial_council/political_committee/official_reports.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5276 [EM-201] Fix address autocomplete by checking if removal link exists
  .eslintrc
  front/services/address/AutocompletedAddressForm.js
Labels: Bug, Ready for code review

#5277 [ReferentSpace] show majority vote election details
  front/style/voting-platform/_results.scss
  src/Controller/EnMarche/CommitteeDesignation/AbstractDesignationController.php
  templates/committee_designation/results.html.twig
  templates/committee_designation/show_layout.html.twig
  templates/committee_designation/votes_list.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
Labels: Ready for code review

#5279 [PHP] replace PHP Faker lib
  composer.json
  composer.lock
  symfony.lock
Labels: Ready for code review

#5280 [ReferentSpace] display all candidates on result page
  src/Admin/AdherentAdmin.php
  templates/committee_designation/results.html.twig
  templates/committee_designation/votes_list.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/referent/territorial_council/convocation_list.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_majority_vote_candidates_list.html.twig
Labels: Bug, Ready for code review

#5278 [PHP] Update UUID lib
  composer.json
  composer.lock
  src/Form/DataTransformer/UuidToObjectTransformer.php
  symfony.lock
  tests/Entity/CommitteeTest.php
Labels: Ready for code review

#5281 [CodeQuality] remove unused MyCommittee/PC actions
  src/Collection/CommitteeCollection.php
  src/Committee/CommitteeManager.php
  src/Controller/EnMarche/AdherentController.php
  src/Repository/CommitteeRepository.php
  src/Twig/CommitteeExtension.php
  src/Twig/CommitteeRuntime.php
  templates/adherent/list_my_administrated_citizen_projects.html.twig
  templates/adherent/list_my_citizen_projects.html.twig
  templates/adherent/list_my_committees.html.twig
  templates/adherent/list_my_committees_al.html.twig
  templates/adherent_space/_layout.html.twig
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/components/_nav_desktop.html.twig
  tests/Committee/CommitteeManagerTest.php
Labels: Ready for code review

#5285 [PHP] update Algolia bundle
  composer.lock
Labels: Ready for code review

#5284 [MyActivity] fix displaying committee election block for committee wi…
  templates/adherent_profile/activity/_committees.html.twig
Labels: Bug, Ready for code review

#5264 [Admin] Change committee actions + remove no more needed fields
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20210107173700.php
  src/Address/Address.php
  src/Admin/CommitteeAdmin.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeCommand.php
  src/Committee/CommitteeManagementAuthority.php
  src/Committee/CommitteeManager.php
  src/Committee/EventListener/InitializeSupervisorMandatesListener.php
  src/Committee/Exception/CommitteeSupervisorException.php
  src/Committee/PhotoManager.php
  src/Controller/Admin/AdminCommitteeCRUDController.php
  src/Controller/Admin/AdminCommitteeController.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Entity/Committee.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembershipLog.php
  src/Events.php
  src/Form/AdherentIdType.php
  src/Form/Admin/ApproveCommitteeCommandType.php
  src/Form/CommitteeCommandType.php
  src/Form/DataTransformer/AdherentToIdTransformer.php
  src/Mailer/Message/CommitteeApprovalConfirmationMessage.php
  src/Repository/AdherentRepository.php
  src/Validator/CommitteeProvisionalSupervisor.php
  templates/admin/committee/approve/_layout.html.twig
  templates/admin/committee/approve/_provisional_supervisors.html.twig
  templates/admin/committee/approve/confirm.html.twig
  templates/admin/committee/approve/edit.html.twig
  templates/admin/committee/list_actions.html.twig
  templates/admin/committee/photo.html.twig
  templates/admin/committee/refuse.html.twig
  templates/admin/layout.html.twig
  tests/Admin/CommitteeAdminTest.php
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Committee/CommitteeManagementAuthorityTest.php
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Admin/AdminCommitteeCRUDControllerTest.php
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  tests/Test/Geocoder/DummyGeocoder.php
  translations/validators.fr.yml
Labels: Ready for code review

#4585 Add institutional events tab accesses
  src/Controller/EnMarche/InstitutionalEvents/AbstractInstitutionalEventsController.php
  src/Controller/EnMarche/InstitutionalEvents/ReferentInstitutionalEventsController.php
  src/Controller/EnMarche/ReferentController.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Referent/ManagedInstitutionalEventsExporter.php
  src/Security/Voter/DelegatedAccessesVoter.php
  templates/institutional_events/_base_referent.html.twig
  templates/institutional_events/create.html.twig
  templates/institutional_events/list.html.twig
  templates/referent/_sidebar.html.twig
  templates/referent/institutional_events/list.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#5287 [CoTerr] check election status for candidacy check
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
  templates/candidate/_table.html.twig
  templates/managed_users/_table.html.twig
Labels: Ready for code review

#5288 [Geo] update parents links between Paris and its districts
  src/Command/Geo/SyncZonesCommand.php
  src/Command/Geo/UpdateBoroughsCommand.php
  src/Command/Geo/UpdateCantonsCommand.php
  src/Command/Geo/UpdateCityReplacementsCommand.php
  src/Command/Geo/UpdateCommunitiesCommand.php
  src/Command/Geo/UpdateDistrictsCommand.php
  src/Command/Geo/UpdateFranceCommand.php
  src/Command/Geo/ZoneMatcherCommand.php
  src/Entity/Geo/City.php
  src/Entity/Geo/District.php
  src/Entity/Geo/GeoInterface.php
Labels: Ready for code review

#5291 [Committee] Provisional supervisor can not access designations page
  src/Committee/CommitteePermissions.php
  src/Controller/EnMarche/CommitteeDesignation/SupervisorDesignationController.php
  src/Repository/CommitteeRepository.php
  src/Security/Voter/Committee/CompletelySuperviseCommitteeVoter.php
  templates/committee_manager/_sidebar.html.twig
  tests/Controller/EnMarche/Designation/SupervisorDesignationControllerTest.php
Labels: Ready for code review

#5290 Add a committee charter
  features/admin/committee_merge.feature
  features/api/committees.feature
  features/committee_vote.feature
  features/popup_chart.feature
  features/republican_silence.feature
  src/AdherentCharter/AdherentCharterTypeEnum.php
  src/Collection/AdherentCharterCollection.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/Entity/AdherentCharter/CommitteeHostCharter.php
  src/Repository/CommitteeMembershipRepository.php
  templates/committee_manager/_layout.html.twig
  templates/committee_manager/dashboard.html.twig
  tests/Repository/AdherentRepositoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5294 [Committee] Fix members display for provisional supervisor + some other fixes
  features/popup_chart.feature
  src/AdherentCharter/AdherentCharterFactory.php
  src/Admin/AdherentAdmin.php
  src/Entity/CommitteeMembership.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  templates/admin/committee/members.html.twig
  templates/committee_manager/list_members.html.twig
  templates/components/_vote_icon.svg.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#5295 [Mailchimp] fix sync with Mailchimp of newly approved committee
  src/Committee/CommitteeManager.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
Labels: Bug, Ready for code review

#5296 [Committee] Fix JS on committee creation page
  src/Controller/Admin/AdminCommitteeCRUDController.php
  templates/adherent/create_committee.html.twig
  templates/committee_manager/edit.html.twig
  templates/javascript.js.twig
  templates/referent/committee/create.html.twig
  templates/referent/committee/pre_approve.html.twig
  templates/referent/territorial_council/convocation_create.html.twig
  templates/territorial_council_designation/convocation.html.twig
  templates/thematic_community/join.html.twig
Labels: Ready for code review

#5297 [Mailchimp] Sync provisional status with Mailchimp
  .env
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#5298 [Committee] Fix not show supervisors with finished mandates + some other fixes
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Entity/Adherent.php
  templates/admin/committee/list_hosts.html.twig
  templates/committee/_sidebar.html.twig
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Ready for code review

#5300 Fix elected adherents in Territorial council
  src/Repository/CommitteeRepository.php
Labels: Ready for code review

#5301 [Committee] Remove canary mode for committee creation
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  templates/adherent_profile/activity/_committees.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/referent/committee/list.html.twig
Labels: Ready for code review

#5299 [Admin][Committee] Add info to membership list
  templates/admin/committee/members.html.twig
Labels: Ready for code review

#5304 [Admin][Committee] Add mandates page
  src/Controller/Admin/AdminCommitteeController.php
  src/Entity/CommitteeMembership.php
  templates/admin/committee/_mandate_type.html.twig
  templates/admin/committee/list_actions.html.twig
  templates/admin/committee/mandates.html.twig
  templates/admin/layout.html.twig
Labels: Ready for code review

#5305 [Front] Add Mailchimp check JS code
  templates/base.html.twig
Labels: Ready for code review

#5306 [Dev] Re activate Redis as Profiler storage
  config/packages/dev/profiler.yaml
  config/packages/dev/snc_redis.yaml
  src/Profiler/Storage/RedisProfilerStorage.php
Labels: Ready for code review

#5307 [TerritorialCouncil] check committee mandate type for adherent_candid…
  src/TerritorialCouncil/Handlers/AbstractTerritorialCouncilHandler.php
Labels: Bug, Ready for code review

#5308 [Admin][Committee] Replace a mandate
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeMandateCommand.php
  src/Controller/Admin/AdminCommitteeController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Form/Admin/CommitteeMandateCommandType.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Validator/AdherentForCommitteeMandateReplacement.php
  src/Validator/AdherentForCommitteeMandateReplacementValidator.php
  templates/admin/committee/mandates/_layout_mandate_action.html.twig
  templates/admin/committee/mandates/_mandate_as_table.html.twig
  templates/admin/committee/mandates/_type.html.twig
  templates/admin/committee/mandates/list.html.twig
  templates/admin/committee/mandates/replace.html.twig
  templates/admin/committee/mandates/replace_confirm.html.twig
  templates/admin/committee/members.html.twig
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  tests/TestHelperTrait.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#5310 [Admin][Committee] Add a mandate
  src/Admin/Committee/CommitteeAdherentMandateTypeEnum.php
  src/Committee/CommitteeAdherentMandateCommand.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeManager.php
  src/Controller/Admin/AdminCommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/DataFixtures/ORM/LoadCommitteeAdherentMandateData.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Form/Admin/CommitteeMandateCommandType.php
  src/Repository/AdherentMandate/CommitteeAdherentMandateRepository.php
  src/Validator/AdherentForCommitteeMandateReplacementValidator.php
  templates/admin/committee/mandates/_layout_mandate_action.html.twig
  templates/admin/committee/mandates/add.html.twig
  templates/admin/committee/mandates/add_confirm.html.twig
  templates/admin/committee/mandates/list.html.twig
  templates/admin/committee/mandates/replace_confirm.html.twig
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Committee/CommitteeManagerTest.php
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
  tests/Repository/AdherentRepositoryTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5312 [ElectedList] Fix zone filter
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
Labels: Bug, Ready for code review

#5311 [Admin][Committee] Remove a mandate + some display changes and test fixes
  src/Committee/CommitteeAdherentMandateManager.php
  src/Controller/Admin/AdminCommitteeController.php
  templates/admin/committee/_actions_menu_li.html.twig
  templates/admin/committee/_actions_menu_right.html.twig
  templates/admin/committee/edit.html.twig
  templates/admin/committee/mandates/_layout_mandate_action.html.twig
  templates/admin/committee/mandates/close_confirm.html.twig
  templates/admin/committee/mandates/list.html.twig
  templates/admin/committee/show.html.twig
  tests/Controller/Admin/AdminCommitteeControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review
