Repository parti-renaissance/espace-adherent, pull requests merged in 2021-05, with the labels that each got.

#5674 [EM-736] Add endpoint to terminate membership
  src/Adherent/BanManager.php
  src/Controller/Api/ProfileController.php
  src/Controller/EnMarche/UserController.php
  src/Membership/MembershipRequestHandler.php
  src/OAuth/TokenRevocationAuthority.php
  src/Repository/OAuth/AccessTokenRepository.php
  src/Repository/OAuth/RefreshTokenRepository.php
Labels: Ready for code review

#5687 Fix uprocess action of procuration request
  src/Controller/Admin/AdminProcurationController.php
Labels: Bug, Ready for code review

#5688 [Mailchimp] Skip message if zone is not synchronized
  src/AdherentMessage/Handler/AdherentMessageChangeCommandHandler.php
  src/Mailchimp/Exception/SkippableMessageExceptionInterface.php
  src/Mailchimp/Exception/ZoneNotSynchronizedException.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
Labels: Ready for code review

#5689 [Candidate] Hide messages for departmental candidate
  src/Controller/EnMarche/InvitationController.php
  templates/candidate/_sidebar.html.twig
Labels: Ready for code review

#5686 [Coalitions][Mailchimp] Sync contacts with Mailchimp
  .env
  config/services.yaml
  config/services/services.xml
  src/Coalition/CoalitionContactValueObject.php
  src/Coalition/CoalitionMemberValueObject.php
  src/Coalition/Listener/FollowerChangeSubscriber.php
  src/Command/MailchimpSyncCoalitionsMembersCommand.php
  src/Controller/EnMarche/Coalition/CausesController.php
  src/Entity/AbstractFollower.php
  src/Entity/Adherent.php
  src/Entity/Coalition/CoalitionFollower.php
  src/Entity/FollowerInterface.php
  src/Entity/Geo/Zone.php
  src/Entity/PostAddress.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Command/CoalitionMemberChangeCommand.php
  src/Mailchimp/Synchronisation/Command/RemoveCoalitionMemberCommand.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/CoalitionMemberChangeCommandHandler.php
  src/Mailchimp/Synchronisation/Handler/RemoveCoalitionMemberCommandHandler.php
  src/Mailchimp/Synchronisation/MemberRequest/AbstractMemberRequestBuilder.php
  src/Mailchimp/Synchronisation/MemberRequest/CoalitionMemberRequestBuilder.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Repository/AdherentRepository.php
  src/Repository/Coalition/CauseFollowerRepository.php
  src/Repository/Coalition/CauseRepository.php
  src/Repository/Coalition/CoalitionRepository.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#5692 [Coalition] Add cause author phone number
  templates/coalition/causes_list.html.twig
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5693 [CoalitionsMessage] allow update message filter via API
  migrations/Version20210504210739.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Controller/Api/AdherentMessage/UpdateAdherentMessageFilterController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AdherentSegmentAwareFilterTrait.php
  src/Entity/AdherentMessage/Filter/CoalitionsFilter.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/CoalitionsConditionBuilder.php
  src/Validator/ValidMessageCoalitionsFilter.php
  src/Validator/ValidMessageCoalitionsFilterValidator.php
Labels: Ready for code review

#5696 [EVENTS] add zipcode filter
  src/Api/Filter/EventsZipCodeFilter.php
  src/Command/Geo/ZoneMatcherCommand.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#5694 [PHP] Update symfony 4.4.22
  composer.lock
Labels: Ready for code review, dependencies

#5695 [Test] update oauth token ttl
  features/bootstrap/RestContext.php
  features/deputy.feature
  src/DataFixtures/ORM/LoadOAuthTokenData.php
Labels: Ready for code review

#5697 [Coalition][Mailchimp] Change conditions
  src/Entity/Adherent.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/CoalitionMemberChangeCommandHandler.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#5702 [CoalitionsMessage] add default filter
  src/Entity/AdherentMessage/Filter/CoalitionsFilter.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
Labels: Ready for code review

#5705 [Events] display default event on search page
  src/Repository/EventRepository.php
  templates/search/_events.html.twig
Labels: Ready for code review

#5690 [EM-781] Add label for procuration proxy reliability
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationProxy.php
  templates/procuration_manager/request.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
  tests/Procuration/ProcurationManagerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5691 [EM-783] Allow only one election for procuration proxy & request
  src/Form/Procuration/ElectionContextType.php
  src/Procuration/ElectionContext.php
  templates/procuration/choose_election.html.twig
  tests/Controller/EnMarche/ProcurationControllerTest.php
Labels: Ready for code review

#5703 [Coalition][Mailchimp] Fix information updates
  features/api/causes.feature
  features/api/coalitions.feature
  src/Coalition/CoalitionMemberValueObject.php
  src/DataFixtures/ORM/LoadCauseData.php
  src/DataFixtures/ORM/LoadCoalitionData.php
  src/DataFixtures/ORM/LoadCoalitionEventData.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Handler/CoalitionMemberChangeCommandHandler.php
  src/Repository/Coalition/CauseFollowerRepository.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
Labels: Ready for code review

#5704 Fix display defaultEvent
  src/Command/VotingPlatform/CloseElectionCommand.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Controller/EnMarche/EventController.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Report/CommunityEventReport.php
  src/Event/EventInvitationHandler.php
  src/Mailer/Message/EventInvitationMessage.php
  src/Repository/Event/BaseEventRepository.php
  src/Twig/EventRuntime.php
  templates/events/_header.html.twig
  templates/events/_layout.html.twig
  templates/events/attend_confirmation.html.twig
  tests/Controller/EnMarche/CitizenActionControllerTest.php
Labels: Bug, Ready for code review

#5707 [Coalition][Mailchimp] Avoid Mailchimp sync for coalitions user with global audience
  src/Mailchimp/Synchronisation/Handler/AdherentChangeCommandHandler.php
Labels: Ready for code review

#5685 [EM-763][EVENTS] add image field to event creation and update
  front/app.js
  front/services/utils/imageCropper.js
  front/style/layout/_forms-em.scss
  front/style/voting-platform/_candidacy.scss
  src/Controller/EnMarche/CitizenActionManagerController.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Controller/EnMarche/CommitteeEventManagerController.php
  src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
  src/Controller/EnMarche/InstitutionalEvents/AbstractInstitutionalEventsController.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Entity/ImageOwnerInterface.php
  src/Entity/ImageTrait.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Event/BaseEventCommand.php
  src/Event/EventFactory.php
  src/Form/BaseEventCommandType.php
  src/Form/CroppedImageType.php
  src/Form/DataTransformer/CroppedImageDataTransformer.php
  src/Form/VotingPlatform/Candidacy/BaseCandidacyBiographyType.php
  src/InstitutionalEvent/InstitutionalEventCommand.php
  templates/citizen_action_manager/_layout.html.twig
  templates/committee/candidacy/form_committee_adherent.html.twig
  templates/committee/candidacy/form_committee_supervisor.html.twig
  templates/committee/edit_candidacy.html.twig
  templates/committee_manager/add_event.html.twig
  templates/event_manager/event_form_layout.html.twig
  templates/events/edit.html.twig
  templates/form_theme.html.twig
  templates/institutional_events/create.html.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
  tests/Controller/EnMarche/CommitteeDesignation/CandidatureControllerTest.php
  tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
Labels: Ready for code review

#5715 Show candidate messages & do not synchronize inactive zones
  src/Mailchimp/Synchronisation/RequestBuilder.php
  templates/candidate/_sidebar.html.twig
Labels: Ready for code review

#5721 Unregistration adherents email
  src/Controller/EnMarche/UserController.php
Labels: Ready for code review

#5722 Fix events urls
  src/Controller/EnMarche/CommitteeEventManagerController.php
  src/Twig/EventExtension.php
  src/Twig/EventRuntime.php
  templates/adherent/contact.html.twig
  templates/adherent/home.html.twig
  templates/adherent/my_activity_events.html.twig
  templates/adherent_profile/activity/_events.html.twig
  templates/events/_header.html.twig
  templates/events/_layout.html.twig
  templates/events/attend.html.twig
  templates/events/attend_confirmation.html.twig
  templates/events/cancel.html.twig
  templates/events/contact_members.html.twig
  templates/events/contact_old.html.twig
  templates/events/edit.html.twig
  templates/events/members.html.twig
  templates/events/show.html.twig
  templates/search/_events.html.twig
Labels: Bug, Ready for code review

#5716 Add twig macro for init cropperjs widget
  front/app.js
  front/services/utils/imageCropper.js
  src/Form/CroppedImageType.php
  src/Form/DataTransformer/CroppedImageDataTransformer.php
  templates/citizen_action_manager/_form_layout.html.twig
  templates/citizen_action_manager/_layout.html.twig
  templates/citizen_action_manager/create.html.twig
  templates/citizen_action_manager/edit.html.twig
  templates/committee/edit_candidacy.html.twig
  templates/committee_manager/add_event.html.twig
  templates/event_manager/_form_layout.html.twig
  templates/event_manager/event_create.html.twig
  templates/event_manager/event_edit.html.twig
  templates/events/edit.html.twig
  templates/institutional_events/create.html.twig
  templates/javascript.js.twig
  templates/territorial_council/candidacy_step1_edit.html.twig
Labels: Ready for code review

#5731 Send content to Coalition campaign email
  src/Mailchimp/Campaign/ContentSection/CoalitionMessageSectionBuilder.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#5738 [PHP] Update Symfony to 4.4.23
  composer.lock
Labels: Ready for code review

#5734 [API] add send message test endpoint
  src/Controller/Api/AdherentMessage/SendTestAdherentMessageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#5727 [EM-820][News] add News to referent space
  config/packages/security.yaml
  src/Controller/EnMarche/Jecoute/News/AbstractNewsController.php
  src/Controller/EnMarche/Jecoute/News/NewsCandidateController.php
  src/Controller/EnMarche/Jecoute/News/NewsReferentController.php
  src/Form/Jecoute/NewsFormType.php
  src/Security/Voter/ReferentNewsPublicationVoter.php
  templates/jecoute/news/_form.html.twig
  templates/referent/_sidebar.html.twig
Labels: Ready for code review

#5739 Add geo point to region & dpt
  migrations/Version20210517124456.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/GeoPointTrait.php
Labels: Ready for code review

#5745 Fix sync adherent geo-zone with Mailchimp
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Bug, Ready for code review

#5746 [EM-820][News] fix zone repository method findForJecouteByReferentTags
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#5741 [EM-821][Polls] add polls to referent space
  src/Controller/EnMarche/Poll/AbstractPollController.php
  src/Controller/EnMarche/Poll/PollReferentController.php
  src/Poll/PollSpaceEnum.php
  src/Repository/Poll/AbstractPollRepository.php
  src/Repository/Poll/LocalPollRepository.php
  src/Security/Voter/Poll/EditCandidateLocalPollVoter.php
  src/Security/Voter/Poll/EditReferentLocalPollVoter.php
  templates/poll/_base_referent_space.html.twig
  templates/referent/_sidebar.html.twig
Labels: Ready for code review

#5748 [EM-841][News] retrieve only news created 60 days before
  src/Api/Doctrine/JecouteNewsExtension.php
Labels: Ready for code review

#5751 [PHP] Update Symfony to 4.4.24
  composer.lock
Labels: Ready for code review, Security

#5753 [EM-850][Polls] update polls api endpoint
  src/Controller/Api/PollController.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Poll/LocalPollRepository.php
Labels: Ready for code review

#5744 Add modal + button to Data Corner
  .env
  config/packages/security.yaml
  config/packages/twig.yaml
  front/style/app.scss
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_data-corner.scss
  front/style/mixins/_colors.scss
  public/images/data-corner/modal-animation.gif
  public/images/data-corner/sidebar-data-corner.png
  src/Entity/Adherent.php
  templates/candidate/_data-corner-modal.html.twig
  templates/candidate/_layout.html.twig
  templates/candidate/_sidebar.html.twig
  tests/Controller/OAuth/OAuthServerControllerTest.php
Labels: Ready for code review

#5747 [Events] expose image url for coalition/cause events
  features/api/coalition_events.feature
  src/Entity/Event/CauseEvent.php
  src/Entity/Event/CoalitionEvent.php
Labels: Ready for code review

#5765 Update modal
  front/style/manager-space/_base-layout.scss
  front/style/manager-space/_data-corner.scss
Labels: Work in progress

#5771 [EM-925] Add Source field for AdherentMessage and use it to choose good template
  migrations/Version20210527002020.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/AdherentMessageInterface.php
  src/Mailchimp/Campaign/CampaignContentRequestBuilder.php
  src/Mailchimp/Campaign/CampaignRequestBuilder.php
  src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
  src/Mailchimp/Manager.php
  src/Normalizer/AdherentMessageDenormalizer.php
Labels: Ready for code review

#5772 [EM-930] [Admin] Fix survey export
  src/Exporter/SurveyExporter.php
Labels: Bug, Ready for code review

#5773 Fix find coalition followers method
  src/Repository/Coalition/CoalitionRepository.php
Labels: Bug, Ready for code review

#5779 [EM-945] change candidate prefix on news title
  features/api/jecoute_news.feature
  src/Jecoute/NewsTitlePrefix.php
Labels: Ready for code review

#5774 [EM-842][Campaign] add personalization to referent space
  config/packages/security.yaml
  front/app.js
  front/listeners/confirm-modal.js
  front/services/utils/imageCropper.js
  front/style/layout/_buttons.scss
  migrations/Version20210526121013.php
  src/Admin/Jecoute/RegionAdmin.php
  src/Controller/Api/Jecoute/DepartmentController.php
  src/Controller/EnMarche/Jecoute/JecouteRegionController.php
  src/Controller/EnMarche/Jecoute/Personalization/AbstractPersonalizationController.php
  src/Controller/EnMarche/Jecoute/Personalization/JecouteCandidateRegionController.php
  src/Controller/EnMarche/Jecoute/Personalization/JecouteReferentRegionController.php
  src/DataFixtures/ORM/AbstractFixtures.php
  src/DataFixtures/ORM/LoadJecouteRegionData.php
  src/Entity/Jecoute/Region.php
  src/Form/CroppedImageType.php
  src/Form/Jecoute/RegionType.php
  src/Jecoute/RegionManager.php
  src/Normalizer/RegionNormalizer.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Jecoute/RegionRepository.php
  templates/candidate/_sidebar.html.twig
  templates/form_theme.html.twig
  templates/javascript.js.twig
  templates/jecoute/edit_region.html.twig
  templates/referent/_sidebar.html.twig
  tests/Controller/EnMarche/Jecoute/JecouteRegionControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#5781 [EM-923] display news notification checkbox in referent space
  src/Controller/EnMarche/Jecoute/News/AbstractNewsController.php
  src/Controller/EnMarche/Jecoute/News/NewsCandidateController.php
  src/Controller/EnMarche/Jecoute/News/NewsReferentController.php
  src/Form/Jecoute/NewsFormType.php
  templates/jecoute/news/_form.html.twig
Labels: Ready for code review

#5782 fix campaign migration
  migrations/Version20210526121013.php
Labels: Ready for code review

#5784 fix cropper image input
  templates/form_theme.html.twig
Labels: Ready for code review
