Repository parti-renaissance/espace-adherent, pull requests merged in 2022-04, with the labels that each got.

#7132 [PHP] Update Symfony
  composer.lock
Labels: dependencies, composer

#7130 [API][PAP] Add vote places list endpoint
  features/api/pap_campaigns.feature
  migrations/Version20220401171433.php
  src/Api/Filter/PapVotePlaceScopeFilter.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Pap/VotePlace.php
Labels: Ready for code review

#7133 [PAP] Fix PAP campaign list endpoint
  features/api/pap_campaigns.feature
  src/Entity/Pap/Campaign.php
Labels: Bug, Ready for code review

#7131 [Procuration] update reminder email
  src/Command/ProcurationSendReminderCommand.php
  src/Mailer/Message/Procuration/ProcurationProxyReminderMessage.php
  src/Procuration/ProcurationProxyMessageFactory.php
  src/Procuration/ProcurationReminderHandler.php
  src/Repository/ProcurationRequestRepository.php
  tests/Command/ProcurationSendReminderCommandTest.php
Labels: Ready for code review

#7135 [PAP] Fix campaign admin
  config/services/admin.xml
  src/Admin/Pap/CampaignAdmin.php
  templates/admin/scope/list_zones.html.twig
Labels: Bug, Ready for code review

#7141 [Procuration] disable procuration object with invalid email
  .env
  config/packages/test/messenger.yaml
  config/services.yaml
  migrations/Version20220406110135.php
  src/DataFixtures/ORM/LoadInvalidEmailAddressData.php
  src/Entity/InvalidEmailAddress.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/InvalidEmailAddress/HashGenerator.php
  src/Procuration/Command/NewProcurationObjectCommand.php
  src/Procuration/Command/ProcurationCommandInterface.php
  src/Procuration/Handler/CheckProcurationAuthorHandler.php
  src/Procuration/Listener/ProcurationListener.php
  src/Repository/InvalidEmailAddressRepository.php
  src/Validator/InvalidEmailAddress.php
  src/Validator/InvalidEmailAddressValidator.php
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#7124 [PAP] Improve the command associating campaigns with buildings to take into account local campaigns
  src/Command/PapAssociateActiveCampaignsToBuildingsCommand.php
  src/Pap/Exception/LocalCampaignException.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#7142 [PAP] Set TZ on begin_at of PAP campaign history
  src/Normalizer/Pap/CampaignHistoryDenormalizer.php
Labels: Ready for code review

#7144 [Procuration] improve email validation
  src/Procuration/Handler/CheckProcurationAuthorHandler.php
  src/Validator/StrictEmail.php
  src/Validator/StrictEmailValidator.php
Labels: Ready for code review

#7148 [Procuration] hide disabled procuration requests
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#7145 [Articles][LPN-596] add article api resource
  config/services/services.xml
  features/api/article.feature
  features/sitemap.feature
  src/Api/Doctrine/ArticleCategoryExtension.php
  src/Api/Doctrine/ArticleExtension.php
  src/DataFixtures/ORM/LoadArticleData.php
  src/Entity/Article.php
  src/Entity/ArticleCategory.php
  src/Entity/EntityContentTrait.php
  src/Normalizer/ArticleNormalizer.php
  tests/Command/AlgoliaSynchronizeCommandTest.php
Labels: Ready for code review

#7150 Fix zone autocomplete query mode
  src/Form/Procuration/ProcurationProxyType.php
Labels: Ready for code review

#7154 [Procuration] improve match method for borough zone
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
  tests/Entity/ProcurationProxyTest.php
Labels: Bug, Ready for code review

#7155 [Procuration] add reminder email for proxies
  migrations/Version20220408144824.php
  src/Command/ProcurationSendReminderCommand.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Mailer/Message/Procuration/ProcurationProxyReminderMessage.php
  src/Mailer/Message/Procuration/ProcurationRequestReminderMessage.php
  src/Procuration/ProcurationProxyMessageFactory.php
  src/Procuration/ProcurationReminderHandler.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
  tests/AbstractCommandCaseTest.php
  tests/Command/ProcurationSendReminderCommandTest.php
Labels: Ready for code review

#7122 Synchronize adherents on SendInBlue
  .env
  .env.test
  config/services.yaml
  config/services_test.yaml
  src/Command/SendInBlueSyncAllAdherentsCommand.php
  src/Membership/Contact/ContactSynchronisationCommandHandler.php
  src/SendInBlue/AdherentManager.php
  src/SendInBlue/Client.php
  src/SendInBlue/ClientInterface.php
  src/SendInBlue/Command/AdherentDeleteCommand.php
  src/SendInBlue/Command/AdherentSynchronisationCommand.php
  src/SendInBlue/ContactManager.php
  src/SendInBlue/EventListener/AdherentEventSubscriber.php
  src/SendInBlue/Handler/AdherentDeleteCommandHandler.php
  src/SendInBlue/Handler/AdherentSynchronisationCommandHandler.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Test/SendInBlue/DummyClient.php
Labels: Ready for code review

#7160 [Procuration] Update replyTo email
  config/services.yaml
  config/services/community.xml
  src/Mailer/Message/Procuration/AbstractProcurationMessage.php
Labels: Ready for code review

#7159 [Admin] Improve Election list queryBuilder
  src/Admin/Designation/VotingPlatformElectionAdmin.php
Labels: Ready for code review

#7162 [PAP] expose campaign vote places on API
  features/api/pap_campaigns.feature
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
Labels: Ready for code review

#7164 [PAP] improve vote place list endpoint
  src/Api/Filter/PapVotePlaceScopeFilter.php
  src/Repository/Pap/VotePlaceRepository.php
Labels: Ready for code review

#7163 [Newsletters][LPN-632] add legislative newsletter subscription entity
  features/api/legislative_newsletter_subscriptions.feature
  migrations/Version20220412120724.php
  src/DataFixtures/ORM/LoadLegislativeNewsletterSubscriptionData.php
  src/Entity/LegislativeNewsletterSubscription.php
  src/Normalizer/LegislativeNewsletterSubscriptionSourceDenormalizer.php
  src/Repository/LegislativeNewsletterSubscriptionRepository.php
  translations/validators.fr.yml
Labels: Ready for code review

#7168 [Admin] Add Legislative candidate role
  migrations/Version20220412172359.php
  src/Adherent/AdherentRoleEnum.php
  src/Adherent/Authorization/ZoneBasedRoleTypeEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/DistrictAdmin.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/Entity/Adherent.php
  src/Entity/AdherentZoneBasedRole.php
  src/Geo/ManagedZoneProvider.php
  src/Repository/Pap/AddressRepository.php
  src/Scope/ScopeEnum.php
  src/Validator/ZoneBasedRoles.php
  src/Validator/ZoneBasedRolesValidator.php
  templates/admin/adherent/statuses.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7170 [Newsletters][LPN-673] add friendly captcha fields
  features/api/legislative_newsletter_subscriptions.feature
  src/Entity/LegislativeNewsletterSubscription.php
  src/Recaptcha/RecaptchaChallengeTrait.php
Labels: Ready for code review

#7169 Add Scope for legislative candidate
  src/DataFixtures/ORM/LoadScopeData.php
  src/Scope/Generator/LegislativeCandidateScopeGenerator.php
  src/Security/Voter/DataCornerVoter.php
Labels: Ready for code review

#7171 [Scope] use forbidden features list for delegated access
  features/api/my_teams.feature
  features/api/scopes.feature
  src/Controller/Api/AdherentAutocompleteController.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Entity/MyTeam/Member.php
  src/OAuth/OAuthAuthenticator.php
  src/Repository/AdherentRepository.php
  src/Scope/FeatureEnum.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#7172 [PAP] expose Survey uuid on campaign get endpoint
  features/api/pap_campaigns.feature
  src/Entity/EntityIdentityTrait.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/Campaign.php
  src/Normalizer/JecouteSurveyNormalizer.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
Labels: Ready for code review

#7175 [PAP] add building statistics endpoint
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/Campaign.php
Labels: Ready for code review

#7177 [PAP] Create BuildingStatistics for new assigned campaign
  migrations/Version20220414170047.php
  src/Command/PapAssociateActiveCampaignsToBuildingsCommand.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/BuildingStatistics.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#7180 [PAP] fix PAP Campaign Algolia index with any zone
  src/Normalizer/Indexer/PapCampaignNormalizer.php
Labels: Bug, Ready for code review

#7179 [ManagedUser] improve status index
  migrations/Version20220414211940.php
  src/Entity/Projection/ManagedUser.php
Labels: Ready for code review

#7182 Fix typo
  features/api/pap_campaigns.feature
  src/Validator/PapCampaignVotePlaces.php
  templates/assessor_attribution/_sub_menu.html.twig
  templates/assessor_request/_fill_assessor_info.html.twig
  templates/assessor_request/index.html.twig
  templates/municipal_manager/_layout.html.twig
Labels: Ready for code review

#7176 [PAP] Add data to campaign replies
  features/api/pap_campaigns.feature
  features/api/surveys.feature
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Entity/Pap/CampaignHistory.php
Labels: Ready for code review

#7183 Add filter to surveys type
  features/api/surveys.feature
  src/Api/Filter/SurveyTypeFilter.php
  src/Entity/Jecoute/Survey.php
Labels: Ready for code review

#7185 [PAP] Fix votePlace validation on PAP campaign creation
  src/Admin/AdherentZoneBasedRoleAdmin.php
  src/Admin/Geo/ZoneAdmin.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Pap/CampaignRepository.php
  src/Validator/PapCampaignVotePlaces.php
  src/Validator/PapCampaignVotePlacesValidator.php
Labels: Bug, Ready for code review

#7186 [Assessors][LPN-610] remove old cities
  src/Intl/FranceCitiesBundle.php
Labels: Ready for code review

#7178 [Newsletters][LPN-676] add confirmation email on legislatives newsletter subscription
  .env
  .env.test
  app/data/static/majorite.jpg
  config/routes.yaml
  config/services.yaml
  features/api/legislative_newsletter_subscriptions.feature
  front/style/app.scss
  front/style/pages/_legislatives-newsletter.scss
  migrations/Version20220413192745.php
  src/Api/Listener/PostLegislativeNewsletterCreateListener.php
  src/Controller/Legislatives/Newsletter/NewsletterController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/Entity/LegislativeNewsletterSubscription.php
  src/Legislative/Newsletter/Events.php
  src/Legislative/Newsletter/LegislativeNewsletterEvent.php
  src/Legislative/Newsletter/LegislativeNewsletterSubscriptionHandler.php
  src/Legislative/Newsletter/Listener/SendValidationMailSubscriber.php
  src/Mailer/Message/Legislatives/AbstractLegislativeNewsletterMessage.php
  src/Mailer/Message/Legislatives/LegislativeNewsletterSubscriptionConfirmationMessage.php
  src/Repository/LegislativeNewsletterSubscriptionRepository.php
  templates/legislatives/newsletter/_layout.html.twig
  templates/legislatives/newsletter/thanks.html.twig
Labels: Ready for code review

#7188 Minimum age filter should be 1
  features/api/adherents.feature
  src/Entity/AdherentMessage/Filter/GeneralFilterTrait.php
  src/Filter/Types/DefinedTypes/AgeRange.php
  src/Filter/Types/IntegerInterval.php
  src/Form/AdherentMessage/AdherentGeoZoneFilterType.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#7191 [AdherentMessage] Skip sync check for test message
  features/api/adherent_messages.feature
  src/Controller/Api/AdherentMessage/SendTestAdherentMessageController.php
Labels: Ready for code review

#7192 [PHP] Update phpstan libs
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Admin/Filter/AdherentRoleFilter.php
  src/Admin/Filter/ReferentTagAutocompleteFilter.php
  src/Admin/Filter/ZoneAutocompleteFilter.php
  src/Command/ReferentTagImportCommand.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Entity/AdherentMessage/Segment/AudienceSegment.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Entity/VotingPlatform/Designation/CandidacyInvitationInterface.php
  src/Form/Admin/AvailableDistrictAutocompleteType.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
  src/TerritorialCouncil/Candidacy/NationalCouncilCandidacyConfigurator.php
  src/Timeline/TimelineImageFactory.php
  src/Twig/AdherentDelegatedAccessesExtension.php
  src/Utils/AreaUtils.php
  src/Validator/AbstractInManagedZoneValidator.php
  src/Validator/FrenchZipCodeValidator.php
  src/Validator/MaxFiscalYearDonationValidator.php
  src/Validator/MergeableCommitteesValidator.php
  src/Validator/PayboxSubscriptionValidator.php
  src/Validator/RepeatedValidator.php
  src/Validator/UnitedNationsCountryValidator.php
  src/VotingPlatform/Listener/CommitteeCandidacySendEmailsListener.php
  src/VotingPlatform/Listener/DeclinePendingCandidacyInvitationsListener.php
  symfony.lock
Labels: Ready for code review, dependencies, composer

#7190 [PAP] Add endpoint for available for campaign vote places
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetAvailableVotePlaceForCampaignController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/VotePlaceRepository.php
Labels: Ready for code review

#7196 Fix typo
  features/api/events.feature
  features/api/pap_campaigns.feature
  translations/validators.fr.yml
Labels: Ready for code review

#7199 Bandeau procuration fix
  templates/banner/call.html.twig
Labels: Ready for code review

#7189 [PAP] Campaign end date should always be after start date
  features/api/pap_campaigns.feature
  src/Entity/Pap/Campaign.php
  translations/validators.fr.yml
Labels: Ready for code review

#7193 [PAP][LPN-678] change pap campaign list query rules
  src/Api/Filter/ScopeVisibilityFilter.php
Labels: Ready for code review

#7201 Add max value to age range inputs
  features/api/adherents.feature
  src/Entity/AdherentMessage/Filter/GeneralFilterTrait.php
  src/Filter/Types/DefinedTypes/AgeRange.php
  src/Filter/Types/IntegerInterval.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#7202 [PAP] Fix address & voters nb calcul process
  src/Pap/Api/Listener/PostWritePapCampaignListener.php
  src/Pap/Handler/UpdateCampaignAddressInfoCommandHandler.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#7203 [Articles] fix retrieve an article endpoint
  src/Entity/Article.php
Labels: Ready for code review

#7208 [PAP] Fix Active campaign extension for app mobile
  config/services/services.xml
  features/api/charter.feature
  features/api/email_templates.feature
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  features/api/push_token.feature
  src/Api/Doctrine/LoadActivePapCampaignExtension.php
  src/Repository/Pap/VotePlaceRepository.php
  templates/amp/style.css.twig
Labels: Bug, Ready for code review

#7211 [Config] improve php fpm config
  docker/dev/pool.conf
  docker/prod/pool.conf
Labels: Ready for code review

#7207 Fix insee codes with leading zeros
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
Labels: Ready for code review

#7209 [PAP][API] Change campaign modification endpoint
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  features/api/pap_vote_places.feature
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/EntityListener/PapCampaignListener.php
  src/Repository/Pap/AddressRepository.php
  src/Repository/Pap/VotePlaceRepository.php
  src/Validator/PapCampaignBeginAtValidator.php
  src/Validator/PapCampaignStarted.php
  src/Validator/PapCampaignStartedValidator.php
  templates/assessor_request/_valid_summary.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#7204 [Newsletters][LPN-712] update from zones collection on duplicate email address
  features/api/legislative_newsletter_subscriptions.feature
  migrations/Version20220419193718.php
  src/Api/Listener/PostLegislativeNewsletterCreateListener.php
  src/DataFixtures/ORM/LoadLegislativeNewsletterSubscriptionData.php
  src/Entity/LegislativeNewsletterSubscription.php
  src/Normalizer/LegislativeNewsletterSubscriptionSourceDenormalizer.php
  translations/validators.fr.yml
Labels: Ready for code review

#7212 [Legislatives][LPN-715] add avec vous error pages
  src/ErrorRenderer/TwigErrorRenderer.php
  templates/TwigBundle/Exception/avecvous/error.html.twig
  templates/TwigBundle/Exception/avecvous/error403.html.twig
  templates/TwigBundle/Exception/avecvous/error404.html.twig
  templates/TwigBundle/Exception/avecvous/error500.html.twig
Labels: Ready for code review

#7213 [PAP] return all questioners for my campaign
  features/api/pap_campaigns.feature
  src/Controller/Api/AdherentAutocompleteController.php
  src/Controller/Api/AdherentFilter/GetFilterCollectionController.php
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/Api/AdherentList/ColumnsConfigurationController.php
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/Controller/Api/Pap/GetPapCampaignQuestionersStatsController.php
  src/Controller/Api/Pap/GetPapCampaignSurveyRepliesController.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Pap/VotePlace.php
  src/Normalizer/AudienceDenormalizer.php
  src/Normalizer/JecouteNewsNormalizer.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
  src/Repository/AdherentRepository.php
  src/Scope/AuthorizationChecker.php
  src/Scope/Scope.php
  src/Scope/ScopeGeneratorResolver.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
  src/Security/Voter/FeatureVoter.php
  src/Security/Voter/RequestScopeVoter.php
  src/Security/Voter/ScopeVisibilityVoter.php
  src/Security/Voter/Survey/CanReadSurveyVoter.php
  src/Validator/Jecoute/SurveyScopeTargetValidator.php
Labels: Ready for code review

#7215 [Survey] simplify security check for Survey endpoints
  .php-cs-fixer.dist.php
  migrations/Version20220421132926.php
  src/Api/Filter/ScopeVisibilityFilter.php
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/News.php
  src/Entity/Jecoute/Survey.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Repository/Jecoute/DataSurveyRepository.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
  src/Security/Voter/Survey/CanReadSurveyVoter.php
  src/Validator/Jecoute/SurveyScopeTargetValidator.php
Labels: Ready for code review

#7216 [Surveys][LPN-679] update surveys collection endpoint query
  src/Api/Filter/JeMengageSurveyScopeFilter.php
Labels: Ready for code review

#7222 [PAP] Replace subresoure route for buildingStats by custom controller
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetCampaignBuildingStatisticsController.php
  src/Entity/Pap/BuildingStatistics.php
  src/Entity/Pap/Campaign.php
  src/Repository/Pap/BuildingStatisticsRepository.php
Labels: Bug, Ready for code review

#7225 [Surveys][LPN-679] fix survey collection endpoint
  src/Api/Filter/JeMengageSurveyScopeFilter.php
  src/Entity/Jecoute/Survey.php
Labels: Bug, Ready for code review

#7223 [LegislativeCandidate][Scope][API] Add all access to events and fix event creation in the district
  features/api/coalition_events.feature
  features/api/events.feature
  src/DataFixtures/ORM/LoadDefaultEventData.php
  src/DataFixtures/ORM/LoadDistrictData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Deputy/LightFileDistrictLoader.php
  src/Normalizer/PostAddressDenormalizer.php
  tests/Test/Geocoder/DummyGeocoder.php
Labels: Ready for code review

#7230 [Surveys] KPI endpoints
  features/api/surveys.feature
  src/Controller/Api/Jecoute/GetSurveysKpiController.php
  src/Entity/Jecoute/Survey.php
  src/Repository/Jecoute/LocalSurveyRepository.php
Labels: Ready for code review

#7221 [Surveys][LPN-614] update survey data answer to accept partial answers
  features/api/surveys-replys.feature
  features/api/surveys.feature
  src/Entity/Jecoute/DataAnswer.php
  src/Validator/DataSurveyAnswerTypeChoice.php
  src/Validator/DataSurveyAnswerTypeChoiceValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#7226 [Procurations][LPN-648] fix other cities matching search
  src/Intl/FranceCitiesBundle.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
Labels: Ready for code review

#7234 [LegislativeNewsletter] remove country field
  features/api/legislative_newsletter_subscriptions.feature
  migrations/Version20220426163649.php
  src/DataFixtures/ORM/LoadLegislativeNewsletterSubscriptionData.php
  src/Entity/LegislativeNewsletterSubscription.php
Labels: Ready for code review

#7237 [Surveys][LPN-748] add type on survey retrieve endpoint
  features/api/surveys.feature
  src/Entity/Jecoute/Survey.php
Labels: Ready for code review

#7244 [PAP] enable sortBy for building stats endpoint
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetCampaignBuildingStatisticsController.php
  src/Repository/Pap/BuildingStatisticsRepository.php
Labels: Ready for code review

#7243 [PHP] Update phpstan libs
  composer.json
  composer.lock
  src/Entity/ArticleCategory.php
  templates/events/_header.html.twig
Labels: Ready for code review, dependencies, composer

#7242 [Survey] Add national published only count
  features/api/surveys.feature
  src/Controller/Api/Jecoute/GetSurveysKpiController.php
Labels: Ready for code review

#7248 [PHP] Update Symfony 4.4.41
  composer.lock
Labels: dependencies, composer

#7245 Fix get news endpoint
  dump/all-geo-zone.sql
  features/api/jecoute_news.feature
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#7241 [LegislativeCandidate][Scope][API] Add access to adherents endpoints
  features/api/adherents.feature
  features/api/events.feature
  features/api/jecoute_news.feature
  features/api/pap_campaigns.feature
  features/api/pap_vote_places.feature
  features/api/scopes.feature
  features/api/surveys.feature
  features/deputy.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDefaultEventData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/DataFixtures/ORM/LoadLegislativeNewsletterSubscriptionData.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/ManagedUsers/Filter/LegislativeCandidateFilterFactory.php
  tests/Controller/EnMarche/ManagedUsers/ManagedUserControllerTest.php
  tests/Test/Geocoder/DummyGeocoder.php
Labels: Ready for code review

#7249 [Procuration] Add a voter number field to the procuration request
  migrations/Version20220428150916.php
  src/Entity/ProcurationRequest.php
  src/Form/Procuration/ProcurationRequestType.php
  templates/procuration/request/profile.html.twig
  tests/Controller/Procuration/ProcurationControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#7246 Fix legislatives newsletter subscription
  features/api/legislative_newsletter_subscriptions.feature
  src/Entity/LegislativeNewsletterSubscription.php
Labels: Ready for code review

#7250 [Events][LPN-652] add denormalization context on event update
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#7254 remove debug
  features/api/coalition_events.feature
Labels: Ready for code review
