Repository parti-renaissance/espace-adherent, pull requests merged in 2022-11, with the labels that each got.

#7713 Enable carousel to slide 1 item
  assets/listeners/carousel.js
  templates/article/partial/article-item.html.twig
Labels: Ready for code review

#7714 Update Tailwind config, layout font color and style
  assets/style/main.scss
  tailwind.config.js
  tailwind.config.site.js
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/partials/summary_row.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/double_columns_layout.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/site-header.html.twig
  templates/renaissance/partials/small-footer.html.twig
Labels: Ready for code review

#7699 [Adhesion] add new form pre-payment step
  assets/bootstrap.js
  assets/style/components/_form.scss
  assets/style/pages/_adhesion.scss
  assets/utils/css.js
  src/Controller/Renaissance/Adhesion/CompleteProfileController.php
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Controller/Renaissance/Adhesion/ValidateController.php
  src/Entity/Adherent.php
  src/Form/CivilityType.php
  src/Form/DonationRequestType.php
  src/Form/Renaissance/Adhesion/AdditionalInfoType.php
  src/Form/Renaissance/Adhesion/CompleteProfileType.php
  src/Form/Renaissance/Donation/DonationRequestDonatorType.php
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/complete_profile.html.twig
  templates/renaissance/adhesion/validate.html.twig
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#7717 Update wording funnel
  tailwind.config.site.js
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/partials/left-side-content.html.twig
Labels: Ready for code review

#7718 Update wording on funnel cotisation
  assets/style/components/_form.scss
  assets/style/mixins/_colors.scss
  assets/style/pages/_adhesion.scss
  src/Form/Renaissance/Adhesion/AdhesionAmountType.php
  templates/base_renaissance.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/form_theme.html.twig
Labels: Ready for code review

#7720 [Phoning] fix table alias in query
  src/Repository/AdherentRepository.php
Labels: Bug, Ready for code review

#7721 Update Symfony httpkernel events
  src/EventListener/AdministratorExportHistoryListener.php
  src/EventListener/RecordReferentLastVisitListener.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  src/Redirection/Dynamic/RedirectToAdminPanelHandler.php
  src/Redirection/Dynamic/RedirectToInterface.php
  src/Redirection/Dynamic/RedirectToPathHandler.php
  src/Redirection/Dynamic/RedirectToRemoveUuidHandler.php
  src/Redirection/Dynamic/RedirectToRouteHandler.php
  src/Redirection/Dynamic/RedirectionsSubscriber.php
  src/Redirection/LegacyRedirectionsSubscriber.php
Labels: Ready for code review, PHP 8 & Symfony 5 🚀

#7722 [Config] Fix Bazinga geocoder cache config
  config/packages/bazinga_geocoder.yaml
  config/packages/framework.yaml
Labels: Ready for code review, PHP 8 & Symfony 5 🚀

#7725 [Adhesion] update confirmation wording
  templates/renaissance/adhesion/end_adhesion.html.twig
Labels: Ready for code review

#7728 [Config] remove FB keys
  .env
  src/Adherent/AdherentRoleEnum.php
Labels: Ready for code review

#7727 [Admin] Remove unused Pixsort lib
  public/js/pixsort_ini.js
  templates/admin/layout.html.twig
Labels: Ready for code review

#7731 Fix login button style
  templates/security/renaissance_user_login.html.twig
Labels: Ready for code review

#7730 Add carousel to office members picture
  assets/components/Carousel/Carousel.js
  assets/listeners/carousel.js
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7666 [LPN-1207] switch to friendly recaptcha
  config/packages/twig.yaml
  config/services.yaml
  config/services/http_client.yaml
  public/js/friendly-challenge.widget.module.min.js
  src/Controller/Renaissance/Adhesion/AdhesionController.php
  src/Controller/Renaissance/Donation/MentionsController.php
  src/Controller/Renaissance/Newsletter/SaveNewsletterController.php
  src/Donation/DonationRequest.php
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  src/Renaissance/Newsletter/SubscriptionRequest.php
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/friendly-captcha.html.twig
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
  tests/Controller/Renaissance/NewsletterControllerTest.php
Labels: Ready for code review

#7739 add layout to password view
  templates/renaissance/adherent/change_password/form.html.twig
Labels: Ready for code review

#7732 [Adhesion] Generate for adherent UUID v4
  src/Membership/AdherentFactory.php
  src/Validator/UniqueMembershipValidator.php
Labels: Ready for code review

#7734 [Admin] allow add Media from article page
  composer.json
  composer.lock
  docker/dev/supervisord.conf
  src/Admin/Article/AbstractArticleAdmin.php
  src/Entity/Media.php
Labels: Ready for code review

#7751 [Config] fix php-cs-fixer cache path
  .github/workflows/ci-cd.yml
Labels: Ready for code review

#7755 update adherent terminate membership view
  tailwind.config.site.js
  templates/renaissance/adherent/_layout.html.twig
  templates/renaissance/adherent/profile/form.html.twig
  templates/renaissance/adherent/terminate_membership/form.html.twig
  templates/renaissance/adherent/terminate_membership/success.html.twig
  tests/Controller/Renaissance/AdherentControllerTest.php
Labels: Ready for code review

#7760 Fix responsive
  assets/style/main.scss
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/complete_profile.html.twig
  templates/renaissance/adhesion/confirmation.html.twig
  templates/renaissance/adhesion/end_adhesion.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/adhesion/partials/summary_row.html.twig
  templates/renaissance/adhesion/payment.html.twig
  templates/renaissance/adhesion/pre-payment.html.twig
  templates/renaissance/adhesion/result.html.twig
  templates/renaissance/adhesion/summary.html.twig
  templates/renaissance/donation/_layout.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/choose_donation_amount.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/left-side-content.html.twig
  templates/renaissance/partials/logo-icon.svg.twig
  templates/renaissance/partials/logo-text.svg.twig
  templates/renaissance/partials/previous-next-buttons.html.twig
  templates/security/renaissance_forgot_password.html.twig
  templates/security/renaissance_reset_password.html.twig
  tests/Controller/Renaissance/Security/SecurityControllerTest.php
Labels: Ready for code review

#7764 Update adherent wording
  templates/renaissance/adherent/_layout.html.twig
  templates/renaissance/adherent/certification_request/form.html.twig
  templates/renaissance/adherent/certification_request/home.html.twig
  templates/renaissance/adherent/profile/form.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
Labels: Ready for code review

#7761 Remove privacy card
  templates/renaissance/adherent/profile/form.html.twig
  tests/Controller/Renaissance/AdherentControllerTest.php
Labels: Ready for code review

#7759 [Config] remove QueryString paramConverter
  config/services/services.xml
  src/Controller/Api/CommitteesController.php
  src/Controller/Api/EventsController.php
  src/Controller/Api/Statistics/AbstractStatisticsController.php
  src/Controller/Api/Statistics/AdherentsController.php
  src/Controller/Api/Statistics/CommitteesController.php
  src/Controller/Api/Statistics/EventsController.php
  src/Controller/Api/Statistics/ReferentAutocompleteController.php
  src/Controller/Api/StatsController.php
  src/ParamConverter/DoctrineQueryStringParamConverter.php
  tests/Controller/Api/StatsControllerTest.php
Labels: Ready for code review

#7757 [PHP] remove Goutte client
  composer.json
  composer.lock
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review, PHP 8 & Symfony 5 🚀

#7763 [Profile] remove captcha and fix JS
  templates/base_renaissance.html.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/adherent/certification_request/form.html.twig
  templates/renaissance/adherent/profile/form.html.twig
  templates/renaissance/partials/friendly-captcha.html.twig
Labels: Ready for code review

#7766 [Admin] generate uuid from adherent email for ban action
  migrations/Version20221115082558.php
  src/Adherent/Unregistration/UnregistrationFactory.php
  src/Entity/BannedAdherent.php
  src/Entity/Unregistration.php
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#7779 Fix checkbox and blur header
  assets/components/Carousel/Carousel.js
  assets/listeners/glider.js
  assets/main.js
  assets/style/main.scss
  package.json
  templates/renaissance/adherent/profile/form.html.twig
  templates/renaissance/forms/form_theme_profile.html.twig
  templates/renaissance/home.html.twig
  yarn.lock
Labels: Don't merge

#7781 Remove glider-js
  assets/listeners/glider.js
  assets/main.js
  assets/style/main.scss
  package.json
  yarn.lock
Labels: Ready for code review

#7782 [Security] Fix check for anonymous token
  src/Security/Listener/SecurityListener.php
Labels: Bug, Ready for code review

#7784 Fix PR and StS carousel
  assets/components/Carousel/Carousel.js
  assets/style/main.scss
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7729 [Committee] add phone column
  templates/committee_manager/list_members.html.twig
  tests/Controller/EnMarche/CommitteeManagerControllerTest.php
Labels: Ready for code review

#7783 Improve Renaissance member filter
  src/Form/AdherentMessage/SimpleMessageFilterType.php
  src/Form/CommitteeMemberFilterType.php
  templates/committee_manager/list_members.html.twig
  templates/form_theme.html.twig
  templates/message/filter/message_filter.html.twig
Labels: Ready for code review

#7787 Add account delele card
  templates/renaissance/adherent/profile/form.html.twig
Labels: Ready for code review

#7791 Remove red border
  templates/renaissance/adherent/profile/form.html.twig
Labels: Ready for code review

#7792 Update civility radio on adhesion
  assets/style/main.scss
  templates/renaissance/adhesion/complete_profile.html.twig
  templates/renaissance/form_theme.html.twig
Labels: Ready for code review

#7804 Avoid inject user interface
  config/services/compatibility.yaml
  src/Controller/Api/AdherentFilter/GetFilterCollectionController.php
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/Api/AdherentList/ColumnsConfigurationController.php
  src/Controller/Api/AdherentMessage/SendTestAdherentMessageController.php
  src/Controller/Api/AdherentMessage/UpdateAdherentMessageFilterController.php
  src/Controller/Api/Coalition/CauseController.php
  src/Controller/Api/Coalition/CoalitionController.php
  src/Controller/Api/CommitteesController.php
  src/Controller/Api/Event/SubscribeAsAdherentController.php
  src/Controller/Api/EventsController.php
  src/Controller/Api/FollowController.php
  src/Controller/Api/InternalApiProxyController.php
  src/Controller/Api/JeMengage/GetHeaderBlockContentController.php
  src/Controller/Api/JeMengage/GetTimelineFeedsController.php
  src/Controller/Api/Jecoute/JemarcheDataSurveyReplyController.php
  src/Controller/Api/Jecoute/SurveyController.php
  src/Controller/Api/Phoning/CampaignsScoresController.php
  src/Controller/Api/Phoning/StartCampaignController.php
  src/Controller/Api/ProfileController.php
  src/Controller/Api/ResubscribeEmailController.php
  src/Controller/Api/ScopeController.php
  src/Controller/Api/ScopesController.php
  src/Controller/Api/TerritorialCouncilCandidacyController.php
  src/Controller/Api/UserController.php
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
  src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
  src/Controller/EnMarche/AdherentProfile/ActivityController.php
  src/Controller/EnMarche/AdherentProfile/CommitmentController.php
  src/Controller/EnMarche/CommitteeController.php
  src/Controller/EnMarche/CommitteeDesignation/CandidatureController.php
  src/Controller/EnMarche/CommitteeDesignation/ReferentDesignationController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/Controller/EnMarche/CommitteeSpaceController.php
  src/Controller/EnMarche/Election/VotePlaceResults/AssessorVoteResultController.php
  src/Controller/EnMarche/EventController.php
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  src/Controller/EnMarche/Jecoute/News/AbstractNewsController.php
  src/Controller/EnMarche/MunicipalChiefController.php
  src/Controller/EnMarche/Poll/AbstractPollController.php
  src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
  src/Controller/EnMarche/TerritorialCouncil/ConvocationManagerController.php
  src/Controller/EnMarche/TerritorialCouncil/Designation/ReferentDesignationController.php
  src/Controller/EnMarche/TerritorialCouncil/PoliticalCommitteeController.php
  src/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilController.php
  src/Controller/EnMarche/ThematicCommunity/ThematicCommunitiesChiefMembersController.php
  src/Controller/EnMarche/ThematicCommunity/ThematicCommunityController.php
  src/Controller/EnMarche/UserController.php
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Security/Listener/SecurityListener.php
Labels: Ready for code review

#7408 Update Sentry js lib
  .github/actions/setup-yarn/action.yml
  .github/workflows/ci-cd.yml
  behat.yml.dist
  composer.lock
  docker-compose.yml
  docker/dev/Dockerfile
  front/kernel.js
  package.json
  yarn.lock
Labels: dependencies, javascript, front-end, npm

#7805 [LPN-1236][Admin] Add LocalElection admin
  config/services/admin.xml
  migrations/Version20221122094902.php
  src/Admin/LocalElection/CandidaciesGroupAdmin.php
  src/Admin/LocalElection/CandidacyAdmin.php
  src/Admin/LocalElection/LocalElectionAdmin.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/AssetsController.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/Instance/NationalCouncil/Candidacy.php
  src/Entity/LocalElection/CandidaciesGroup.php
  src/Entity/LocalElection/Candidacy.php
  src/Entity/LocalElection/LocalElection.php
  src/Entity/TerritorialCouncil/Candidacy.php
  src/Entity/VotingPlatform/Designation/BaseCandidaciesGroup.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Entity/VotingPlatform/Designation/CandidacyInterface.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Designation/ElectionEntityInterface.php
  src/Entity/VotingPlatform/Election.php
  src/Form/Admin/AdminType.php
  src/Form/Admin/DesignationGlobalZoneType.php
  src/Repository/CommitteeRepository.php
  src/VotingPlatform/Designation/DesignationGlobalZoneEnum.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/admin/designation/list_zone.html.twig
  templates/admin/layout.html.twig
  templates/admin/local_election/list_candidacies_count.html.twig
  templates/form_theme_admin.html.twig
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#7807 undo communication wording
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  templates/renaissance/adherent/email_notifications/form.html.twig
Labels: Ready for code review

#7793 [Admin] Add form to create RE adherents
  config/packages/security.yaml
  src/Address/Address.php
  src/Admin/AdherentAdmin.php
  src/Controller/Admin/AdminAdherentCRUDController.php
  src/Donation/DonationRequest.php
  src/Entity/Adherent.php
  src/Form/AddressType.php
  src/Form/Admin/Adherent/CreateRenaissanceType.php
  src/Form/CivilityType.php
  src/Membership/AdherentFactory.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  src/Renaissance/Membership/Admin/CotisationAmountChoiceEnum.php
  src/Renaissance/Membership/Admin/MembershipTypeEnum.php
  templates/admin/adherent/renaissance/create.html.twig
  templates/admin/adherent/renaissance/create_button.html.twig
  tests/Admin/AdherentAdminTest.php
  translations/messages+intl-icu.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7822 [LPN-1295] move vote platform on RE domain
  front/style/voting-platform/_layout.scss
  src/Controller/EnMarche/VotingPlatform/AbstractController.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_committee_supervisor.html.twig
  templates/voting_platform/_layout_poll.html.twig
Labels: Ready for code review

#7820 Fix UniqueMembership with custom paths
  src/Entity/Donation.php
  src/Membership/AdherentFactory.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  src/Validator/UniqueMembership.php
  src/Validator/UniqueMembershipValidator.php
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#7823 [Validation] remove allowEmptyString option for Length constraint
  features/api/quick_actions.feature
  features/registration.feature
  src/Entity/Contact.php
  src/Membership/MembershipRequest/AbstractMembershipRequest.php
  src/Membership/MembershipRequest/JeMengageMembershipRequest.php
  src/Membership/MembershipRequest/PlatformMembershipRequest.php
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#7833 Add account validation funnel after RE adherent creation
  src/Controller/Renaissance/Adherent/CreationConfirmationController.php
  src/Entity/Adherent.php
  src/Mailer/Message/Renaissance/RenaissanceAdherentAccountCreatedMessage.php
  src/Renaissance/App/UrlGenerator.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  src/Renaissance/Membership/Notifier.php
  templates/renaissance/adherent/creation_confirmation.html.twig
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#7851 Improve validation annotations
  features/api/quick_actions.feature
  src/AdherentMessage/AdherentMessageDataObject.php
  src/AdherentProfile/Password.php
  src/Coalition/Filter/CauseFilter.php
  src/Committee/CommitteeCommand.php
  src/Controller/Api/Pap/GetCampaignBuildingStatisticsController.php
  src/Entity/Adherent.php
  src/Entity/AdherentMandate/AbstractAdherentMandate.php
  src/Entity/AdherentMessage/Filter/JecouteFilter.php
  src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
  src/Entity/Coalition/QuickAction.php
  src/Entity/Contact.php
  src/Entity/CustomSearchResult.php
  src/Entity/Device.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/EntityContentTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Formation/Axe.php
  src/Entity/Formation/Module.php
  src/Entity/Formation/Path.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Entity/LegislativeDistrictZone.php
  src/Entity/Mooc/BaseMoocElement.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Mooc/MoocVideoElement.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Phoning/CampaignHistory.php
  src/Entity/ReferentArea.php
  src/Entity/RepublicanSilence.php
  src/Entity/ThematicCommunity/Contact.php
  src/Entity/Unregistration.php
  src/Entity/UserDocument.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Event/BaseEventCommand.php
  src/Event/EventRegistrationCommand.php
  src/Filesystem/FileManager.php
  src/Form/ThematicCommunity/ThematicCommunityMembershipType.php
  src/Interactive/MyEuropeProcessor.php
  src/Membership/EventListener/ChangeEmailFlashMessageSubscriber.php
  src/Membership/MembershipRequest/PlatformMembershipRequest.php
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  src/Repository/AdherentChangeEmailTokenRepository.php
  src/TerritorialCouncil/Convocation/ConvocationObject.php
  src/TerritorialCouncil/Designation/UpdateDesignationRequest.php
  src/Validator/ImageObjectValidator.php
  src/VotingPlatform/Designation/CreatePartialDesignationCommand.php
Labels: Ready for code review

#7852 [Adhesion] update UTM params for existing account
  src/Membership/MembershipRequestHandler.php
Labels: Bug, Ready for code review

#7853 Extends renaissance layout
  assets/style/components/_button.scss
  assets/style/main.scss
  assets/style/mixins/_colors.scss
  assets/style/pages/index.scss
  assets/style/pages/voting-platform/_candidacy.scss
  assets/style/pages/voting-platform/_layout.scss
  assets/style/pages/voting-platform/_results.scss
  assets/style/pages/voting-platform/index.scss
  src/Controller/EnMarche/VotingPlatform/AbstractController.php
  src/Controller/EnMarche/VotingPlatform/ConfirmController.php
  src/Controller/EnMarche/VotingPlatform/FinishController.php
  src/Controller/EnMarche/VotingPlatform/IndexController.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
  src/Controller/EnMarche/VotingPlatform/VoteController.php
  templates/base_renaissance.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_poll.html.twig
  templates/voting_platform/finish.html.twig
Labels: Ready for code review
