Repository parti-renaissance/espace-adherent, pull requests merged in 2022-01, with the labels that each got.

#6691 [API][Events] Get events created by me
  features/api/events.feature
  src/Api/Filter/MyCreatedEventsFilter.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#6692 [API][Events] Get one event with all info
  features/api/events.feature
  src/Api/Serializer/EventGroupsContextBuilder.php
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#6695 [API][Events] Create a default event + add some validation constraints
  features/api/events.feature
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/DefaultEvent.php
  src/Normalizer/EventDenormalizer.php
  tests/Controller/Api/Event/CoalitionEventControllerTest.php
  tests/Controller/Api/InternalApiProxyControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#6696 [API][Events] Send email after modification or cancellation of a default event
  features/api/events.feature
  src/Entity/Event/DefaultEvent.php
  src/Event/CommitteeEventEvent.php
  src/Event/EventEvent.php
  src/Event/EventMessageNotifier.php
  src/EventListener/SendEventUpdateNotificationListener.php
  src/Mailer/Message/EventUpdateMessage.php
Labels: Ready for code review

#6697 [API][Events] Can delete events only without participants
  features/api/events.feature
  src/Entity/Event/BaseEvent.php
  src/Repository/EventRegistrationRepository.php
  src/Security/Voter/CanDeleteEventVoter.php
Labels: Ready for code review

#6701 [PHP] Update Symfony to 4.4.36
  composer.lock
Labels: dependencies, composer

#6700 [EM-1858] fix the order of survey questions on phoning campaign replies endpoint
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
  src/Repository/Jecoute/SurveyQuestionRepository.php
Labels: Ready for code review

#6709 [API][Events] Get and export event participants
  features/api/events.feature
  src/Controller/Api/Event/GetEventParticipantsController.php
  src/DataFixtures/ORM/LoadDefaultEventData.php
  src/DataFixtures/ORM/LoadUserData.php
  src/Exporter/EventParticipantsExporter.php
  src/Repository/EventRegistrationRepository.php
  tests/Controller/Api/Event/GetEventParticipantsControllerTest.php
Labels: Ready for code review

#6710 Fix survey responses download
  src/Exporter/SurveyExporter.php
Labels: Bug, Ready for code review

#6706 [Admin] Add Zone Based roles form to Adherent admin
  config/services/admin.xml
  migrations/Version20220104015613.php
  src/Adherent/Authorization/ZoneBasedRoleTypeEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/AdherentZoneBasedRoleAdmin.php
  src/Admin/Jecoute/JecouteManagedAreaAdmin.php
  src/Entity/Adherent.php
  src/Entity/AdherentZoneBasedRole.php
  src/Form/Admin/AdherentZoneBasedRoleType.php
  src/Form/Admin/JecouteManagedAreaType.php
  src/Form/Geo/ZoneType.php
  src/Profiler/Storage/RedisProfilerStorage.php
  src/Scope/ScopeEnum.php
  src/Validator/WysiwygLengthValidator.php
  src/Validator/ZoneBasedRoles.php
  src/Validator/ZoneBasedRolesValidator.php
  templates/admin/adherent/partial/zone_based_role_autocomplete.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
  webpack.development.js
Labels: Ready for code review

#6712 [API][PAP] Change response status order
  features/api/pap_campaigns.feature
  src/Pap/CampaignHistoryStatusEnum.php
Labels: Ready for code review

#6711 Improve API Scope filters
  src/Api/Filter/AbstractScopeFilter.php
  src/Api/Filter/AdherentMessageScopeFilter.php
  src/Api/Filter/EventScopeFilter.php
  src/Api/Filter/JecouteNewsScopeFilter.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Generator/CandidateScopeGenerator.php
  src/Scope/Generator/DeputyScopeGenerator.php
  src/Scope/Generator/NationalCommunicationScopeGenerator.php
  src/Scope/Generator/NationalScopeGenerator.php
  src/Scope/Generator/PapNationalManagerScopeGenerator.php
  src/Scope/Generator/PhoningManagerScopeGenerator.php
  src/Scope/Generator/PhoningScopeGenerator.php
  src/Scope/Generator/ReferentScopeGenerator.php
  src/Scope/Generator/ScopeGeneratorInterface.php
  src/Scope/Generator/SenatorScopeGenerator.php
Labels: Ready for code review

#6693 [EM-1823] retrieve surveys endpoints
  features/api/scopes.feature
  features/api/surveys.feature
  src/Api/Filter/JeMengageSurveyScopeFilter.php
  src/Api/Serializer/EventGroupsContextBuilder.php
  src/Api/Serializer/JecouteNewsGroupsContextBuilder.php
  src/Controller/Api/Jecoute/SurveyController.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Geo/ManagedZoneProvider.php
  src/Normalizer/JeMengageWebSurveyNormalizer.php
  src/Normalizer/JecouteSurveyNormalizer.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
  src/Repository/Jecoute/DataSurveyRepository.php
  src/Scope/AuthorizationChecker.php
  src/Scope/FeatureEnum.php
  src/Security/Voter/Survey/ReadSurveyVoter.php
  translations/messages.fr.yml
Labels: Ready for code review

#6717 [API] add notifs OptIn keys
  features/api/membership_jemengage.feature
  src/Membership/MembershipRequest/AbstractMembershipRequest.php
  src/Membership/MembershipRequest/JeMengageMembershipRequest.php
Labels: Ready for code review

#6718 [Membership] add reset password endpoint
  features/api/membership_jemengage.feature
  src/Controller/Api/MembershipController.php
  src/Controller/EnMarche/Security/SecurityController.php
  src/Membership/AdherentResetPasswordHandler.php
  src/Membership/Event/UserResetPasswordEvent.php
  src/Membership/EventListener/UserResetPasswordSubscriber.php
Labels: Ready for code review

#6720 [API][PAP] Add info to endpoints
  features/api/pap_campaigns.feature
  src/Entity/Adherent.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Pap/CampaignHistory.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
Labels: Ready for code review

#6721 [API][Events] Add a sorting to events endpoint + return cancelled events
  features/api/event_stats.feature
  features/api/events.feature
  src/Api/Doctrine/BaseEventExtension.php
  src/DataFixtures/ORM/LoadCommitteeEventData.php
  src/DataFixtures/ORM/LoadDefaultEventData.php
  src/Entity/Event/BaseEvent.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
Labels: Ready for code review

#6722 [API][PAP] Close/open a building
  features/api/pap_address.feature
  migrations/Version20220106143719.php
  src/Entity/Pap/BuildingEvent.php
  tests/Controller/Api/Pap/BuildingEventControllerTest.php
Labels: Ready for code review

#6723 [API][PAP] Add an endpoint to change building type
  features/api/pap_address.feature
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Pap/Building.php
  src/Pap/BuildingTypeEnum.php
  translations/validators.fr.yml
Labels: Ready for code review

#6724 Add JeMengage Admin scope
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/Adherent.php
  src/Entity/AdherentZoneBasedRole.php
  src/Scope/Generator/JeMengageAdminScopeGenerator.php
  src/Scope/ScopeEnum.php
  src/Security/LoginFormGuardAuthenticator.php
  src/Security/Voter/DataCornerVoter.php
  translations/messages.fr.yml
Labels: Ready for code review

#6715 [EM-1824] add post endpoint on survey
  config/services/admin.xml
  features/api/surveys.feature
  migrations/Version20220103181110.php
  src/Admin/Extension/EntityAdministratorBlameableAdminExtension.php
  src/Admin/JecouteLocalSurveyAdmin.php
  src/Admin/JecouteNationalSurveyAdmin.php
  src/Admin/ReorderableAdminInterface.php
  src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
  src/DataFixtures/ORM/LoadJecouteSurveyData.php
  src/Entity/Jecoute/Choice.php
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/NationalSurvey.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Jecoute/SurveyQuestion.php
  src/Normalizer/SurveyDenormalizer.php
  src/Repository/Jecoute/LocalSurveyRepository.php
  src/Security/Voter/CanEditSurveyVoter.php
  src/Validator/Jecoute/SurveyScopeTarget.php
  src/Validator/Jecoute/SurveyScopeTargetValidator.php
  templates/jecoute/surveys_list.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#6726 [API][PAP] Add missing data
  features/api/pap_campaigns.feature
  src/Entity/Adherent.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/CampaignHistory.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
Labels: Ready for code review

#6727 [API][PAP] Set finish_at for CampaignHistory in finished status
  src/Pap/Api/Listener/PreWritePapCampaignHistoryListener.php
  src/Pap/CampaignHistoryStatusEnum.php
Labels: Bug, Ready for code review

#6731 Fix BoardMember tests
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#6735 fix survey creation
  src/Normalizer/Indexer/SurveyNormalizer.php
Labels: Ready for code review

#6734 [API][PAP] Add begin_at to CampaignHistory
  features/api/pap_campaigns.feature
  migrations/Version20220110135715.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/CampaignHistory.php
  src/Normalizer/Pap/CampaignHistoryDenormalizer.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6733 [API][PAP] Add address stats
  features/api/pap_campaigns.feature
  migrations/Version20220110165351.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/Entity/Pap/Campaign.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
  src/Pap/Api/Listener/PostWritePapCampaignListener.php
  src/Pap/Command/UpdateCampaignAddressInfoCommand.php
  src/Pap/Handler/UpdateCampaignAddressInfoCommandHandler.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6736 [EM-1862] Je m'engage - Login + forgot password pages
  front/style/app.scss
  front/style/mixins/_fonts.scss
  front/style/pages/_jemengage_user_login.scss
  public/fonts/Maax - Medium Italic-205TF.woff
  public/fonts/maax-medium-italic.eot
  public/fonts/maax-medium-italic.ttf
  public/fonts/maax-medium-italic.woff2
  templates/amp/style.css.twig
  templates/oauth/base.html.twig
  templates/oauth/base_jemengage.html.twig
  templates/security/jemengage_forgot_password.html.twig
  templates/security/jemengage_user_login.html.twig
Labels: Ready for code review

#6742 [JS] remove unused react-csv lib
  package.json
  yarn.lock
Labels: Ready for code review, dependencies, npm

#6743 [API][PAP] Change survey config
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
Labels: Ready for code review

#6641 [EM-1767] Distinguish local & national teams
  config/services/admin.xml
  features/api/teams.feature
  migrations/Version20211207152117.php
  src/Admin/Extension/EntityScopeVisibilityAdminExtension.php
  src/Admin/Team/TeamAdmin.php
  src/Api/DTO/AdherentUuid.php
  src/Api/Filter/ScopeVisibilityFilter.php
  src/Controller/Api/Team/AddTeamMembersController.php
  src/Controller/Api/Team/RemoveTeamMemberController.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/EntityScopeVisibilityInterface.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Team/Team.php
  src/Scope/Generator/PapScopeGenerator.php
  src/Scope/ScopeGeneratorResolver.php
  src/Scope/ScopeVisibilityEnum.php
  src/Security/Voter/ScopeVisibilityVoter.php
  src/Validator/AdherentUuid.php
  src/Validator/AdherentUuidValidator.php
  src/Validator/Scope/ScopeVisibility.php
  src/Validator/Scope/ScopeVisibilityValidator.php
  templates/admin/scope/list_visibility.html.twig
  templates/admin/scope/list_zone.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#6732 [EM-1919] national/local pap campaigns
  config/services/admin.xml
  features/api/pap_campaigns.feature
  migrations/Version20220110122036.php
  src/Admin/Pap/CampaignAdmin.php
  src/Admin/Team/TeamAdmin.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/Pap/Campaign.php
Labels: Ready for code review

#6725 [EM-1825] update survey endpoint
  features/api/surveys.feature
  src/Entity/Jecoute/LocalSurvey.php
  src/Entity/Jecoute/Question.php
  src/Entity/Jecoute/Survey.php
  src/Jecoute/SurveyQuestionTypeEnum.php
  src/Normalizer/JecouteSurveyNormalizer.php
  src/Normalizer/SurveyDenormalizer.php
  src/Normalizer/UpdateSurveyDenormalizer.php
  src/Security/Voter/Survey/CanReadSurveyVoter.php
Labels: Ready for code review

#6737 [EM-1918] national/local phoning campaigns
  config/services/admin.xml
  features/api/phoning_campaigns.feature
  migrations/Version20220110185032.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/Phoning/Campaign.php
Labels: Ready for code review

#6741 [JME] Allow EM user to request resetPassword token
  src/Controller/EnMarche/Security/SecurityController.php
Labels: Ready for code review

#6750 [API] Add Jemengage RGPD endpoint
  features/api/jemengage.feature
  src/Controller/Api/JeMengage/GetRgpdController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
Labels: Ready for code review

#6745 [Login] Je m'engage - fix returns + maquette updates
  front/style/pages/_jemengage_user_login.scss
  public/fonts/maax-medium-italic.woff
  templates/security/jemengage_forgot_password.html.twig
  templates/security/jemengage_user_login.html.twig
Labels: Ready for code review

#6751 [OAuth] Add OAuth client code field
  features/api/adherent_messages.feature
  features/api/audience_segments.feature
  features/api/audiences.feature
  features/api/charter.feature
  features/api/device.feature
  features/api/email_templates.feature
  features/api/events.feature
  features/api/jecoute_news.feature
  features/api/jecoute_ripostes.feature
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  features/api/pap_vote_places.feature
  features/api/phoning_campaigns.feature
  features/api/polls.feature
  features/api/push_token.feature
  features/api/scopes.feature
  features/api/surveys-replys.feature
  features/api/surveys.feature
  features/api/teams.feature
  features/api/user.feature
  features/api/zones.feature
  migrations/Version20220112153457.php
  src/Admin/OAuth/ClientAdmin.php
  src/AppCodeEnum.php
  src/DataFixtures/ORM/LoadClientData.php
  src/Entity/Adherent.php
  src/Entity/OAuth/Client.php
  src/OAuth/AuthorizationValidators/JsonWebTokenValidator.php
  src/OAuth/OAuthAuthenticator.php
Labels: Ready for code review

#6753 Fix addresses and voter number setting to a PAP campaign
  src/Admin/Pap/CampaignAdmin.php
  src/Pap/Handler/UpdateCampaignAddressInfoCommandHandler.php
Labels: Ready for code review

#6748 Fix local stats & add tests
  features/api/pap_campaigns.feature
  features/api/teams.feature
  src/Controller/Api/Pap/GetPapCampaignsKpiController.php
  src/Controller/Api/Team/AddTeamMembersController.php
  src/Controller/Api/Team/RemoveTeamMemberController.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadTeamData.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Team/Team.php
  src/Repository/Pap/CampaignRepository.php
  src/Scope/ScopeGeneratorResolver.php
  src/Security/Voter/ScopeVisibilityVoter.php
Labels: Ready for code review

#6754 Change error message for disabled user
  features/api/jemengage.feature
  src/Security/UserChecker.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#6744 [EM-1945][EM-1946] survey replies endpoint
  features/api/phoning_campaigns.feature
  features/api/surveys.feature
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/Entity/Adherent.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Jecoute/DataSurvey.php
  src/Entity/Pap/CampaignHistory.php
  src/Entity/Phoning/CampaignHistory.php
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
  src/Repository/Jecoute/DataSurveyRepository.php
  tests/Controller/Api/ExportSurveyAnswersControllerTest.php
Labels: Ready for code review

#6757 [EM-1971] get only national survey replies of my zone as a referent user
  features/api/surveys.feature
  migrations/Version20220114151651.php
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/Entity/Jecoute/DataSurvey.php
  src/Exporter/SurveyExporter.php
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Ready for code review

#6759 Change relation between PapAddress and GeoZone to ManyToMany
  features/api/pap_campaigns.feature
  migrations/Version20220114104853.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/Entity/Pap/Address.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6761 [PAP] Change addresses and voters number calculation for a campaign
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6762 [API][PAP] Change survey config
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
Labels: Ready for code review

#6764 [PHP] update htmlpurifier-bundle
  composer.json
  composer.lock
  config/packages/exercise_html_purifier.yaml
  config/services.yaml
  config/services/services.xml
  features/search/events.feature
  src/Admin/ElectionAdmin.php
  src/Admin/ExecutiveOfficeMemberAdmin.php
  src/Admin/MoocAdmin.php
  src/Admin/MoocElementAdmin.php
  src/Admin/ProgrammaticFoundation/ApproachAdmin.php
  src/Admin/ProgrammaticFoundation/MeasureAdmin.php
  src/Admin/ProgrammaticFoundation/ProjectAdmin.php
  src/Admin/ProgrammaticFoundation/SubApproachAdmin.php
  src/Entity/Coalition/Cause.php
  src/EventListener/ControllerListener.php
  src/Form/AdherentMessage/AdherentMessageType.php
  src/Form/BaseEventCommandType.php
  src/Form/CommitteeFeedMessageType.php
  src/Form/ContactMembersType.php
  src/Form/DeputyMessageType.php
  src/Form/FeedItemType.php
  src/Form/InstitutionalEventCommandType.php
  src/Form/PartialDesignationType.php
  src/Form/PurifiedTextareaType.php
  src/Form/TerritorialCouncil/ConvocationType.php
  src/Form/TerritorialCouncil/EditDesignationType.php
  src/Form/TypeExtension/FormTypeExtension.php
  src/Form/TypeExtension/PhoneNumberTypeExtension.php
  src/Form/TypeExtension/TextTypeExtension.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6769 [Algolia] Use AppEnvironment var env for Algolia index name
  config/packages/twig.yaml
  front/kernel.js
  front/listeners/algolia-search.js
  templates/base.html.twig
  templates/oauth/base.html.twig
Labels: Bug, Ready for code review

#6768 [EM-1995] add some address information
  features/api/pap_address.feature
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Pap/Address.php
  src/Entity/Pap/Building.php
  src/Entity/Pap/BuildingStatistics.php
Labels: Ready for code review

#6770 [PAP] Fix zone check on query
  src/Repository/Pap/CampaignRepository.php
Labels: Bug, Ready for code review

#6772 [Correspondent] Fix adherents list endpoint
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
  src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
  src/ManagedUsers/Filter/AbstractFilterFactory.php
  src/ManagedUsers/Filter/CandidateFilterFactory.php
  src/ManagedUsers/Filter/DeputyFilterFactory.php
  src/ManagedUsers/Filter/ManagedUsersFilterFactoryInterface.php
  src/ManagedUsers/Filter/ReferentFilterFactory.php
  src/ManagedUsers/Filter/SenatorFilterFactory.php
  src/ManagedUsers/ManagedUsersFilterFactory.php
Labels: Bug, Ready for code review

#6773 Use UUID v4 for all adherent tokens
  src/Entity/AdherentToken.php
Labels: Ready for code review

#6774 fix admin role based role for simple admin
  config/packages/security.yaml
Labels: Ready for code review

#6771 [EM-1986] add enabled field on procuration request
  migrations/Version20220117173646.php
  src/Admin/ProcurationRequestAdmin.php
  src/Controller/EnMarche/ProcurationController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationRequest.php
Labels: Ready for code review

#6775 Fix Adherent membership reminder command
  src/Command/RemindActivatedMembershipCommand.php
Labels: Bug, Ready for code review

#6776 [EM-2010] add endpoint to retrieve cgu and data policy static page
  features/api/pages.feature
  features/sitemap.feature
  src/DataFixtures/ORM/LoadPageData.php
  src/DataFixtures/data_policy.md
  src/Entity/EntityContentTrait.php
  src/Entity/Page.php
Labels: Ready for code review

#6779 [PAP] Increase size of Campaign stats columns
  migrations/Version20220119094725.php
  src/Entity/Pap/Campaign.php
Labels: Bug, Ready for code review

#6763 [PHP] Remove jms/serializer-bundle lib
  composer.json
  composer.lock
  config/bundles.php
  config/packages/test/web_profiler.yaml
  config/services/services.xml
  config/services/system.xml
  src/Committee/EventListener/CommitteeSubscriber.php
  src/Controller/Api/FormController.php
  src/Controller/Api/MoocController.php
  src/Controller/EnMarche/EventController.php
  src/Entity/Adherent.php
  src/Entity/BaseGroup.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/EntityReferentTagTrait.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Mooc/Mooc.php
  src/Entity/Redirection.php
  src/Entity/ReferentTag.php
  src/Entity/TerritorialCouncil/TerritorialCouncil.php
  src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
  src/Event/EventListener/ApiSyncEventSubscriber.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Normalizer/ApiSyncCommitteeEventNormalizer.php
  src/Normalizer/ApiSyncCommitteeNormalizer.php
  src/Normalizer/FormErrorNormalizer.php
  src/Normalizer/ICal/EventNormalizer.php
  src/Normalizer/MoocImageNormalizer.php
  src/Normalizer/MoocNormalizer.php
  src/Redirection/Dynamic/RedirectionManager.php
  src/Serializer/Encoder/ICalEncoder.php
  src/Serializer/EventICalHandler.php
  src/Serializer/IcalSerializationVisitor.php
  src/Serializer/MoocSerializerSubscriber.php
  tests/Controller/Api/FormControllerTest.php
  tests/Serializer/EventIcalHandlerTest.php
  tests/Serializer/IcalSerializationVisitorTest.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6780 [API] Count surveys of all types when return user information
  features/api/user.feature
  src/Normalizer/JecouteAdherentNormalizer.php
  src/Repository/Jecoute/DataSurveyRepository.php
  src/Repository/Jecoute/JemarcheDataSurveyRepository.php
Labels: Ready for code review

#6783 [API] Fix 500 when phone number is not correct
  features/api/membership_jemengage.feature
  src/Normalizer/PhoneNumberNormalizer.php
Labels: Ready for code review

#6786 [Scopes] Add 'my_team' scope
  features/api/scopes.feature
  src/DataFixtures/ORM/LoadScopeData.php
  src/Scope/FeatureEnum.php
  translations/messages.fr.yml
Labels: Ready for code review

#6758 Fix KPI endpoints & add more tests
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  features/api/scopes.feature
  src/Controller/Api/Pap/GetPapCampaignsKpiController.php
  src/Controller/Api/Phoning/GetPhoningCampaignsKpiController.php
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/Repository/Pap/CampaignRepository.php
  src/Repository/Phoning/CampaignRepository.php
  src/Repository/ScopeVisibilityEntityRepositoryTrait.php
  src/Scope/Generator/PapNationalManagerScopeGenerator.php
  src/Scope/Scope.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#6782 [PAP] Fix payload structure of survey config
  src/Controller/Api/Phoning/GetPhoningCampaignHistoriesSurveyConfigController.php
Labels: Bug, Ready for code review

#6777 [API][PAP] Local user can get national campaign and its information
  features/api/pap_campaigns.feature
  src/Api/Filter/PapCampaignHistoryScopeFilter.php
  src/Api/Filter/ScopeVisibilityFilter.php
  src/Controller/Api/Pap/GetPapCampaignQuestionersStatsController.php
  src/Controller/Api/Pap/GetPapCampaignSurveyRepliesController.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
  src/Entity/Pap/CampaignHistory.php
  src/Exporter/PapCampaignSurveyRepliesExporter.php
  src/Repository/AdherentRepository.php
  src/Repository/GeoZoneTrait.php
  src/Repository/Jecoute/DataSurveyRepository.php
  tests/Controller/Api/ExportPapCampaignSurveyAnswersControllerTest.php
Labels: Ready for code review

#6788 Handle AdherentMessage for Correspondent role
  features/api/adherent_messages.feature
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/CorrespondentAdherentMessage.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/Normalizer/AdherentMessageNormalizer.php
  src/Scope/Generator/CorrespondentScopeGenerator.php
  src/Security/Voter/DataCornerVoter.php
Labels: Ready for code review

#6793 fix legal content endpoint
  features/api/jemengage.feature
  features/api/pages.feature
  features/sitemap.feature
  src/Controller/Api/JeMengage/GetJeMengageContentBlockController.php
  src/Controller/Api/JeMengage/GetRgpdController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/DataFixtures/ORM/LoadPageData.php
  src/Entity/EntityContentTrait.php
  src/Entity/Page.php
Labels: Ready for code review

#6792 [API][MyTeam] Initialize MyTeam
  features/api/my_teams.feature
  migrations/Version20220120173302.php
  src/Controller/Api/MyTeam/InitializeMyTeamController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/MyTeam/Member.php
  src/Entity/MyTeam/MyTeam.php
  src/MyTeam/RoleEnum.php
  src/Repository/MyTeam/MyTeamRepository.php
  translations/validators.fr.yml
Labels: Ready for code review

#6796 [API][MyTeam] Add and modify my team member
  features/api/my_teams.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Entity/Adherent.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/MyTeam/Member.php
  src/Scope/FeatureEnum.php
  src/Validator/MyTeamMember.php
  src/Validator/MyTeamMemberValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#6798 [API][MyTeam] Get and delete a MyTeam member
  features/api/my_teams.feature
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Entity/MyTeam/Member.php
  translations/validators.fr.yml
Labels: Ready for code review

#6801 [API][MyTeam] Get my team with members
  features/api/my_teams.feature
  src/Api/Filter/MyTeamScopeFilter.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/MyTeam/Member.php
  src/Entity/MyTeam/MyTeam.php
Labels: Ready for code review

#6800 add new columns on vote place and link pap campaign to vote place
  migrations/Version20220124162602.php
  src/Controller/Api/Pap/GetNearPointsController.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/AddressRepository.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6806 [API] Improve adherent autocomplete
  features/api/teams.feature
  src/Controller/Api/AdherentAutocompleteController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#6799 [EM-2021] Password create branding
  features/api/membership_jemengage.feature
  front/style/app.scss
  front/style/pages/_jemengage_password_success.scss
  front/style/pages/_jemengage_reset_password.scss
  templates/jemengage/form_theme.html.twig
  templates/jemengage/user/creation_confirmation.html.twig
  templates/security/jemengage_reset_password.html.twig
Labels: Ready for code review

#6809 [API] Allow simple user access ripostes and surveys in App mobile
  features/api/jecoute_ripostes.feature
  features/api/surveys.feature
  src/Controller/Api/Jecoute/SurveyController.php
  src/Entity/Jecoute/Riposte.php
Labels: Bug, Ready for code review

#6811 [API][PAP] Fix survey number count for floor 0
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Bug, Ready for code review

#6812 Add scheme to fix redirection after password reset
  src/JeMengage/App/AppUrlGenerator.php
Labels: Ready for code review

#6813 Feat/pap campaign bdv filters
  features/api/pap_address.feature
  features/javascript/donation.feature
  migrations/Version20220126182307.php
  src/Admin/Pap/CampaignAdmin.php
  src/Controller/Api/Pap/GetNearPointsController.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/AddressRepository.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6816 Remove temporary is_granted('ROLE_OAUTH_SCOPE_JEMENGAGE_ADMIN') from MyTeam endpoints
  src/Entity/MyTeam/Member.php
  src/Entity/MyTeam/MyTeam.php
Labels: Ready for code review

#6817 Enable visibility filters for EntityScopeVisibilityInterface
  features/api/pap_campaigns.feature
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Team/Team.php
Labels: Ready for code review

#6818 Create new correspondent_email subscription type
  .env
  features/api/profile.feature
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  src/Subscription/SubscriptionTypeEnum.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MailchimpWebhookControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#6819 [API][Scopes] Return delegated access info in the get scope endpoint
  features/api/scopes.feature
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Scope/DelegatedAccess.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Scope.php
Labels: Ready for code review

#6822 Add a fix value of zoom on address endpoint only for the Jan 29 2022 …
  src/Controller/Api/Pap/GetNearPointsController.php
Labels: Ready for code review

#6832 [API][MyTeam] Add scope features validation allowing only delegator's features
  features/api/events.feature
  features/api/my_teams.feature
  src/Entity/MyTeam/Member.php
  src/Validator/MyTeamMemberScopeFeatures.php
  src/Validator/MyTeamMemberScopeFeaturesValidator.php
Labels: Ready for code review

#6834 [JS] remove unused react-data-grid lib
  package.json
  yarn.lock
Labels: Ready for code review, dependencies, npm

#6833 [PHP] Update Symfony to 4.4.37
  composer.lock
Labels: Ready for code review, dependencies, composer

#6840 Fix correspondent message
  .env
  features/api/profile.feature
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  src/Subscription/SubscriptionTypeEnum.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MailchimpWebhookControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#6831 Remove delegated accesses from delegated users when delegator has no longer a delegator role
  src/Admin/AdherentAdmin.php
  src/Committee/EventListener/InitializeSupervisorMandatesListener.php
  src/EntityListener/RevokeDelegatedAccessListener.php
  src/Membership/UserEvents.php
  src/MyTeam/Listener/AdherentChangeListener.php
  src/Repository/MyTeam/DelegatedAccessRepository.php
  tests/Admin/AdherentAdminTest.php
  tests/EntityListener/RevokeDelegatedAccessListenerTest.php
Labels: Ready for code review
