Repository parti-renaissance/espace-adherent, pull requests merged in 2022-09, with the labels that each got.

#7479 Revert FontAwesome fonts
  public/fonts/fontawesome-webfont.eot
  public/fonts/fontawesome-webfont.svg
  public/fonts/fontawesome-webfont.ttf
  public/fonts/fontawesome-webfont.woff
  public/fonts/fontawesome-webfont.woff2
Labels: Bug

#7480 [Admin] add getter for QueryBuilder to Algolia query proxy
  src/Algolia/Sonata/ProxyQuery/ProxyQuery.php
Labels: Bug

#7485 [Certification] Redirect anonymous user to login page
  config/packages/security.yaml
Labels: Bug

#7486 [Profile] fix permission check
  config/packages/security.yaml
  src/Controller/EnMarche/AdherentProfile/FunnelController.php
Labels: Bug, Ready for code review

#7491 remove text on procuration platform
  templates/procuration/proxy/proposal.html.twig
Labels: Ready for code review

#7490 [ManagedUser] use array of zone instead of collection instance
  src/Security/Voter/ManagedUserVoter.php
Labels: Bug, Ready for code review

#7501 [VoteStatuses] update results page
  front/style/voting-platform/_layout.scss
  src/Entity/LegislativeNewsletterSubscription.php
  src/Entity/NewsletterSubscription.php
  src/VotingPlatform/Election/VoteCommand/VoteCommand.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_poll.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candidates_list.html.twig
  templates/voting_platform/results/_poll_bulletins_list.html.twig
  templates/voting_platform/results/_poll_candidate_box.html.twig
  tests/Controller/EnMarche/VotingPlatform/CommitteeAdherentVotingPlatformControllerTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7502 [VoteStatuses] enable label clicks for vote step
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/certification_request/home.html.twig
  templates/vote_statuses/_election_box.html.twig
  templates/voting_platform/_layout_poll.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/vote.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  templates/voting_platform/vote_step/_poll_candidate_box.html.twig
  templates/voting_platform/vote_step/candidate_box/poll_content.html.twig
Labels: Ready for code review

#7514 [LPN-1103] fix donation widget css
  assets/components/Donation/DonationAmountChooser.js
  assets/components/Donation/DonationWidget.js
  assets/style/components/_donation.scss
  assets/style/main.scss
  config/packages/workflows.yaml
  features/donation.feature
  src/Admin/DonationAdmin.php
  src/Controller/Renaissance/Donation/DonationController.php
  src/Controller/Renaissance/HomeController.php
  src/Donation/DonationRequest.php
  src/Form/Renaissance/Donation/DonationRequestAmountType.php
  src/Mailer/Message/DonationThanksMessage.php
  templates/admin/donation/list_source.html.twig
  templates/renaissance/adhesion/result.html.twig
  templates/renaissance/donation/choose_donation_amount.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/partials/_quick_form.html.twig
  templates/renaissance/home.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7521 [VoteStatuses] create voters for election
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#7524 [VoteStatuses] fix check vote permission
  src/Entity/Adherent.php
  templates/components/_nav_desktop.html.twig
Labels: Bug, Ready for code review

#7527 Add renaissance page layer
  assets/style/components/_static-page.scss
  assets/style/components/index.scss
  assets/style/mixins/_colors.scss
  config/routes.yaml
  src/Entity/Page.php
  templates/base.html.twig
  templates/base_renaissance.html.twig
  templates/page/layout/renaissance.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/site-header.html.twig
  templates/renaissance/partials/small-footer.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#7532 Allow to connect renaissance user
  features/api/adherents.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Repository/AdherentRepository.php
  src/Security/AuthenticationUtils.php
  src/Security/LoginFormGuardAuthenticator.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
Labels: Ready for code review

#7529 [LPN-1119] change some content on forms
  config/routes.yaml
  features/api/membership_jemengage.feature
  features/registration.feature
  src/Form/Renaissance/Adhesion/MembershipRequestMentionsType.php
  src/Membership/MembershipRequest/AbstractMembershipRequest.php
  templates/renaissance/adhesion/mentions.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/small-footer.html.twig
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#7544 Avoid removing adherent when user is connected
  src/Controller/Renaissance/Adhesion/PaymentController.php
Labels: Bug, Ready for code review

#7543 Add amount help message on adhesion page
  src/Form/Renaissance/Adhesion/MembershipRequestAmountType.php
  templates/renaissance/adhesion/choose_amount.html.twig
Labels: Ready for code review

#7545 [Admin] add adhesion filter for donation admin
  src/Admin/DonationAdmin.php
Labels: Ready for code review

#7547 [LPN-1131] add conditions checkbox and some modification on donation funnel
  config/packages/workflows.yaml
  src/Form/Renaissance/NewsletterSubscriptionType.php
  src/Renaissance/Newsletter/SubscriptionRequest.php
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7549 [Designation] allow to disable result page
  config/packages/sonata_exporter.yaml
  config/services.yaml
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/EnMarche/VotingPlatform/ResultsController.php
Labels: Ready for code review

#7550 [LPN-1096] add new menu in the BO
  config/services/admin.xml
Labels: Ready for code review

#7551 [NL] fix background image position
  public/images/renaissance/newsletter.jpg
  templates/renaissance/adhesion/mentions.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/small-footer.html.twig
Labels: Ready for code review

#7554 [Adhesion] add google place autocomplete
  .eslintrc.js
  assets/components/Address/AddressForm.js
  assets/components/Address/GooglePlaceAutocomplete.js
  assets/components/AmountChooser.js
  assets/listeners/address-autocomplete.js
  assets/main.js
  assets/style/main.scss
  assets/utils/sharer.js
  features/api/membership_jemengage.feature
  package.json
  src/Address/Address.php
  src/Form/AddressType.php
  src/Form/AutocompleteAddressType.php
  src/Form/Renaissance/Adhesion/MembershipRequestPersonalInfoType.php
  src/Form/Renaissance/Donation/DonationRequestDonatorType.php
  src/Membership/MembershipRequest/AbstractMembershipRequest.php
  src/Membership/MembershipRequest/MembershipInterface.php
  src/Membership/MembershipRequest/PlatformMembershipRequest.php
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  templates/renaissance/adhesion/_layout.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
Labels: Ready for code review

#7555 [Donation] add google place autocomplete
  features/donation.feature
  src/Address/PostAddressFactory.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Donation/DonationRequestUtils.php
  src/Donation/DonatorFactory.php
  src/Form/DonationRequestType.php
  src/Validator/FrenchAddressOrNationalityDonationValidator.php
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Donation/DonationFactoryTest.php
  tests/Donation/DonationRequestTest.php
  tests/Validator/FrenchAddressOrNationalityDonationValidatorTest.php
Labels: Ready for code review

#7570 [Renaissance] add labels for adhesion and donation forms
  assets/style/components/_form.scss
  assets/style/main.scss
  postcss.config.js
  src/Form/AutocompleteAddressType.php
  src/Form/AutocompleteInputType.php
  src/Form/Renaissance/Adhesion/MembershipRequestAdditionalInformationsType.php
  src/Form/Renaissance/Adhesion/MembershipRequestPersonalInfoType.php
  src/Form/Renaissance/Donation/DonationRequestDonatorType.php
  templates/renaissance/adhesion/additional_informations.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  templates/security/renaissance_forgot_password.html.twig
  templates/security/renaissance_reset_password.html.twig
  templates/security/renaissance_user_login.html.twig
Labels: Ready for code review

#7571 [Admin] Adherents RE
  features/admin/adherent.feature
  src/Admin/AdherentAdmin.php
  src/DataFixtures/ORM/LoadAdherentData.php
  templates/admin/adherent/statuses.html.twig
Labels: Ready for code review

#7573 [NL] add autocomplete for postalCode field
  assets/components/Address/AddressForm.js
  assets/components/Address/GooglePlaceAutocomplete.js
  assets/listeners/address-autocomplete.js
  assets/style/components/_autocomplete.scss
  assets/style/components/index.scss
  migrations/Version20220922172929.php
  src/Entity/Renaissance/NewsletterSubscription.php
  src/Form/AutocompleteAddressType.php
  src/Form/Renaissance/NewsletterSubscriptionType.php
  src/Form/Renaissance/NewsletterZoneType.php
  src/Renaissance/Newsletter/SubscriptionRequest.php
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  tests/Controller/Renaissance/NewsletterControllerTest.php
Labels: Ready for code review

#7581 [LPN-1151] add abla on new site
  templates/base_renaissance.html.twig
Labels: Ready for code review

#7583 [PHP] Update Twig lib
  composer.lock
Labels: dependencies, Security, composer

#7584 [CampaignMessage] update sender info
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Mailchimp/Campaign/Listener/SetCampaignReplyToSubscriber.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#7582 [LPN-1082] add axeptio cookies management
  .env
  config/packages/twig.yaml
  templates/base_renaissance.html.twig
Labels: Ready for code review

#7568 Sync last membership donation with MC
  src/Entity/Adherent.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#7592 [Adhesion] remove double * on amount choices
  src/Form/Renaissance/Adhesion/MembershipRequestAmountType.php
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/form_theme.html.twig
Labels: Bug, Ready for code review

#7593 [Donation] update amount validation message
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  translations/validators.fr.yml
Labels: Ready for code review
