Repository parti-renaissance/espace-adherent, pull requests merged in 2022-03, with the labels that each got.

#6984 [Assessor][LPN-342] update form
  config/routes.yaml
  config/services.yaml
  config/services_test.yaml
  migrations/Version20220228120338.php
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestFactory.php
  src/Controller/Assessor/AssessorController.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/AssessorRequest.php
  src/Form/AssessorRequestType.php
  templates/assessor_request/_fill_assessor_info.html.twig
  templates/assessor_request/_fill_personal_info.html.twig
  templates/assessor_request/_valid_summary.html.twig
  tests/Controller/Assessor/AssessorControllerTest.php
Labels: Ready for code review

#6983 [API][News] Fix order for app mobile
  features/api/jecoute_news.feature
  src/Api/Doctrine/JecouteNewsExtension.php
Labels: Ready for code review

#6985 [Mailchimp] Skip unsync zone exceptions
  src/AdherentMessage/Handler/AdherentMessageChangeCommandHandler.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Exception/SkippableMessageExceptionInterface.php
  src/Mailchimp/Exception/ZoneNotSynchronizedException.php
  src/Mailchimp/Manager.php
Labels: Ready for code review

#6986 [API] Fix empty date denormalization error
  config/services.yaml
  src/Normalizer/DateTimeNormalizer.php
Labels: Bug, Ready for code review

#6987 [API] Fix invalid phone number denormalization
  src/Normalizer/PhoneNumberNormalizer.php
Labels: Bug, Ready for code review

#6991 Contacts api
  features/api/membership_avecvous.feature
  migrations/Version20220301133517.php
  src/DataFixtures/ORM/LoadContactData.php
  src/Entity/Contact.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/PostAddress.php
  src/Membership/Contact/InterestEnum.php
  src/Membership/Contact/SourceEnum.php
  tests/Test/Recaptcha/DummyRecaptchaApiClient.php
  translations/validators.fr.yml
Labels: Ready for code review

#6990 [PushToken] improve voter by checking adherent relation
  src/Security/Voter/PushTokenAuthorVoter.php
Labels: Bug, Ready for code review

#6992 [Messenger] Adjust retry/fail strategy
  config/packages/doctrine.yaml
  config/packages/messenger.yaml
  src/Mailchimp/Synchronisation/Handler/AdherentChangeCommandHandler.php
  src/Messenger/AlwaysRetryStrategy.php
  templates/certification_request/form.html.twig
Labels: Ready for code review

#6993 [Messenger] Check StatusCode of response before transform it to array
  src/AdherentMessage/Handler/SynchronizeDynamicSegmentCommandHandler.php
  src/Mailchimp/Manager.php
Labels: Bug, Ready for code review

#6994 [AdherentMessage] Sync Message with MC on update (PUT)
  features/api/adherent_messages.feature
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Normalizer/AdherentMessageDenormalizer.php
Labels: Bug, Ready for code review

#7001 [Procuration] remove department check for matching proxy
  src/Repository/ProcurationProxyRepository.php
Labels: Bug, Ready for code review

#6998 [Assessor][LPN-342] update form
  migrations/Version20220301190248.php
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestElectionRoundsEnum.php
  src/Assessor/AssessorRequestFactory.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/AssessorRequest.php
  src/Form/AssessorRequestType.php
  templates/assessor_manager/_assessor_profile.html.twig
  templates/assessor_request/_fill_assessor_info.html.twig
  templates/assessor_request/_layout.html.twig
  templates/assessor_request/_valid_summary.html.twig
  tests/Controller/Assessor/AssessorControllerTest.php
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7000 [Scope] Expose Zone type on API
  features/api/scopes.feature
  src/Entity/Geo/Zone.php
Labels: Ready for code review

#7002 [Timeline Feed][LPN-401][LPN-420] add new sync key and remove markdow…
  config/settings/algolia_search/jemengage_timeline_feed-settings.json
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  src/Normalizer/Indexer/NewsNormalizer.php
  src/Normalizer/Indexer/RiposteNormalizer.php
Labels: Ready for code review

#7006 [Event][LPN-322] update event export columns
  src/Admin/EventAdmin.php
Labels: Ready for code review

#7008 [API] Allow delete event image
  features/api/events.feature
  src/Controller/Api/EventImageController.php
  src/Entity/Event/BaseEvent.php
  tests/Behat/Context/JsonContext.php
Labels: Ready for code review

#7010 [Phoning] fix wording
  features/api/phoning_campaigns.feature
  src/Phoning/CampaignHistoryStatusEnum.php
Labels: Bug, Ready for code review

#7009 [PAP] improve pap address-campaign associating command
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#7011 Contacts registration
  features/api/membership_avecvous.feature
  migrations/Version20220304164524.php
  src/Api/Listener/PostContactEditListener.php
  src/Command/ContactProcessCommand.php
  src/Contact/ContactHandler.php
  src/DataFixtures/ORM/LoadContactData.php
  src/Entity/Contact.php
  src/Mailer/Message/AvecVous/AbstractAvecVousMessage.php
  src/Mailer/Message/AvecVous/AvecVousUserAccountConfirmationMessage.php
  src/Membership/AdherentFactory.php
  src/Membership/Contact/ContactRegistrationCommand.php
  src/Membership/Contact/ContactRegistrationCommandHandler.php
  src/Membership/EventListener/SendEmailValidationSubscriber.php
  src/Membership/MembershipRequest/AvecVousMembershipRequest.php
  src/Membership/MembershipSourceEnum.php
  src/Normalizer/AddressDenormalizer.php
  src/Repository/ContactRepository.php
Labels: Ready for code review

#6981 [PHP] Update Symfony to 4.4.38
  composer.lock
Labels: dependencies, composer

#7015 Remove relation on adherent unregistration
  migrations/Version20220307111506.php
  src/Entity/Contact.php
Labels: Ready for code review

#7014 [MC] Sync only adherent type users
  src/Mailchimp/Synchronisation/Handler/AdherentChangeCommandHandler.php
Labels: Bug, Ready for code review

#6996 Remove team code field
  src/Form/DonationRequestType.php
  templates/donation/informations.html.twig
Labels: Ready for code review

#7012 [Assesseurs][LPN-353] add new tab for vote place assigned cities on assessor manager space
  src/Assessor/AssessorManager.php
  src/Assessor/Filter/CitiesFilters.php
  src/Controller/EnMarche/AssessorManagerController.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/VotePlace.php
  src/Exporter/CityAssessorExporter.php
  src/Repository/VotePlaceRepository.php
  templates/assessor_manager/_cities_list.html.twig
  templates/assessor_manager/_filters_cities.html.twig
  templates/assessor_manager/_layout.html.twig
  templates/assessor_manager/cities.html.twig
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#7018 [Assesseurs][LPN-462] fix vote place associated rule
  src/Assessor/Filter/VotePlaceFilters.php
Labels: Ready for code review

#7021 [Assesseurs][LPN-474] change some labels and remove birth-name field
  migrations/Version20220309113539.php
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestExporter.php
  src/Assessor/AssessorRequestFactory.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/Entity/AssessorRequest.php
  src/Exporter/AssessorsExporter.php
  src/Exporter/CityAssessorExporter.php
  src/Form/AssessorRequestType.php
  templates/assessor_manager/requests.html.twig
  templates/assessor_request/_fill_personal_info.html.twig
  templates/assessor_request/_valid_summary.html.twig
  tests/Controller/Assessor/AssessorControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#7023 [Timeline][LPN-464] change algolia news object indexing visibility
  src/Normalizer/Indexer/NewsNormalizer.php
Labels: Ready for code review

#7026 [Timeline][LPN-466] change event image url
  src/Normalizer/Indexer/EventNormalizer.php
Labels: Ready for code review

#7025 [Correspondent] use two audiences MC for campaign message
  features/api/adherents.feature
  migrations/Version20220309113232.php
  src/AdherentFilter/FilterBuilder/AdherentBasicFieldsFilterBuilder.php
  src/AdherentFilter/FilterBuilder/CommitteeMemberFilterBuilder.php
  src/AdherentMessage/MailchimpCampaign/Handler/AbstractMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/AdherentZoneMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/CommitteeMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/CorrespondentMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ElectedRepresentativeMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/MunicipalChiefMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentMailchimpCampaignHandler.php
  src/Command/MailchimpSyncAllAdherentsCommand.php
  src/Controller/Api/EventImageController.php
  src/Entity/AdherentMessage/MailchimpCampaign.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentRegistrationDateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Normalizer/AddressDenormalizer.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#7024 Change procuration slot count
  src/Entity/ProcurationProxy.php
  tests/Entity/ProcurationRequestTest.php
Labels: Ready for code review

#7027 [Assessor][LPN-484] add service public url in voter number field help text
  templates/assessor_request/_fill_personal_info.html.twig
Labels: Ready for code review

#7028 [Event] quick fix on event export
  src/Admin/EventAdmin.php
Labels: Ready for code review

#7030 Command to synchronise all contacts
  src/Command/SendInBlueSyncAllContactsCommand.php
Labels: Ready for code review

#7032 [Event] disable auto-subscribe for newsletter
  src/Event/EventRegistrationCommand.php
  src/Form/EventRegistrationType.php
Labels: Ready for code review

#7029 Count other cities when matching proxies
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
Labels: Ready for code review

#7037 Fix matching proxies count
  src/Repository/ProcurationProxyRepository.php
Labels: Ready for code review

#7034 Create new template for procuration_proxy_found
  src/Mailer/Message/Procuration/ProcurationProxyMatchedMessage.php
  src/Procuration/ProcurationProxyMessageFactory.php
  tests/Procuration/ProcurationProxyMessageFactoryTest.php
Labels: Ready for code review

#7038 [Procuration] update metadata
  templates/assessor_request/_layout.html.twig
  templates/procuration/_layout.html.twig
Labels: Ready for code review

#7039 [Assessor][LPN-486][LPN-493] add new rule on assessor postal code and add address autocomplete
  front/app.js
  front/pages/assessor_request.js
  migrations/Version20220311152121.php
  src/Assessor/AssessorRequestCommand.php
  src/Assessor/AssessorRequestFactory.php
  src/Entity/AssessorRequest.php
  src/Exporter/CityAssessorExporter.php
  src/Form/AssessorRequestType.php
  src/Validator/Assessor/AssessorDepartment.php
  src/Validator/Assessor/AssessorDepartmentValidator.php
  templates/assessor_request/_fill_personal_info.html.twig
  templates/assessor_request/_valid_summary.html.twig
  templates/assessor_request/index.html.twig
  tests/Controller/Assessor/AssessorControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Ready for code review

#7040 [Assessor][LPN-492][LPN-493] add new column in cities assessors export
  src/Exporter/CityAssessorExporter.php
  templates/assessor_request/_fill_assessor_info.html.twig
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Ready for code review

#7041 [Assessor] update sender name of emails
  src/Assessor/AssessorRequestNotifier.php
  src/Mailer/Message/Assessor/AbstractAssessorMessage.php
  src/Mailer/Message/Assessor/AssessorRequestAssociateMessage.php
  src/Mailer/Message/Assessor/AssessorRequestConfirmationMessage.php
  tests/Controller/Assessor/AssessorControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Ready for code review

#7047 [PAP] log errors bad request on reply endpoint
  src/Controller/Api/Jecoute/AbstractReplyController.php
  src/Controller/Api/Pap/CampaignHistoryReplyController.php
  templates/events/show.html.twig
Labels: Ready for code review

#7049 [Timeline][LPN-463] update sync policy
  migrations/Version20220314141817.php
  src/Entity/Algolia/AlgoliaJeMengageTimelineFeed.php
Labels: Ready for code review

#7054 Add DynamicLinks generator
  .env
  config/packages/firebase.yaml
  config/services.yaml
  config/services_dev.yaml
  config/services_test.yaml
  migrations/Version20220315005750.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Jecoute/News.php
  src/Entity/Jecoute/Riposte.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/EntityListener/DynamicLinkListener.php
  src/Firebase/AbstractMessaging.php
  src/Firebase/DynamicLinks/DynamicLinkFactory.php
  src/Firebase/DynamicLinks/DynamicLinkObjectInterface.php
  src/Firebase/DynamicLinks/DynamicLinkObjectTrait.php
  src/Firebase/DynamicLinks/Manager.php
  tests/Test/Firebase/DummyDynamicLinks.php
Labels: Ready for code review

#7051 District sync
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#7057 [Timeline] update event sync
  src/Entity/Event/BaseEvent.php
Labels: Ready for code review

#7055 [Admin] add deeplink page
  config/services/admin.xml
  migrations/Version20220315170237.php
  src/Admin/JeMengage/DeepLinkAdmin.php
  src/Entity/JeMengage/DeepLink.php
  src/Firebase/DynamicLinks/DynamicLinkFactory.php
Labels: Ready for code review

#7058 Remove unused contact template
  templates/contact/contact.html.twig
Labels: Ready for code review

#7062 Use recaptcha enterprise api
  .env
  composer.json
  composer.lock
  config/services.yaml
  src/Recaptcha/RecaptchaApiClient.php
  symfony.lock
  templates/adherent/contact.html.twig
  templates/assessor_request/index.html.twig
  templates/events/invitation.html.twig
  templates/interactive/my_europe.html.twig
  templates/invitation/form.html.twig
  templates/jemarche/action.html.twig
  templates/membership/join.html.twig
  templates/membership/register.html.twig
  templates/newsletter/subscription.html.twig
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/election_rounds.html.twig
Labels: Ready for code review

#7063 [Admin] display deeplink on resources
  config/services/admin.xml
  config/settings/algolia_search/jemengage_timeline_feed-settings.json
  src/Admin/Extension/DeepLinkExtension.php
  src/Admin/JeMengage/DeepLinkAdmin.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Jecoute/News.php
  src/Entity/Jecoute/Riposte.php
  src/Entity/Jecoute/Survey.php
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/Firebase/DynamicLinks/DynamicLinkObjectInterface.php
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  templates/admin/CRUD/list_dynamic_link.html.twig
Labels: Ready for code review

#7061 [Procurations] add a new tag on procuration manager zone
  src/Admin/AdherentAdmin.php
  src/Entity/Adherent.php
  src/Entity/ManagedArea.php
  src/Repository/AssessorRequestRepository.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
  src/Repository/VotePlaceRepository.php
  src/Validator/TagAllInManagedAreaCodes.php
  src/Validator/TagAllInManagedAreaCodesValidator.php
  templates/assessor_manager/_layout.html.twig
  templates/procuration_manager/_layout.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7067 Refactor recaptcha
  config/services.yaml
  features/api/membership_avecvous.feature
  src/Assessor/AssessorRequestCommand.php
  src/Contact/ContactMessage.php
  src/Controller/Procuration/ProcurationController.php
  src/Entity/AssessorRequest.php
  src/Entity/Contact.php
  src/Entity/Invite.php
  src/Entity/JeMarcheReport.php
  src/Entity/NewsletterSubscription.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Event/EventInvitation.php
  src/Interactive/MyEuropeProcessor.php
  src/Membership/MembershipRequest/PlatformMembershipRequest.php
  src/Recaptcha/RecaptchaApiClient.php
  src/Recaptcha/RecaptchaApiClientInterface.php
  src/Recaptcha/RecaptchaChallengeInterface.php
  src/Recaptcha/RecaptchaChallengeTrait.php
  src/Validator/Recaptcha.php
  src/Validator/RecaptchaValidator.php
  tests/Test/Recaptcha/DummyRecaptchaApiClient.php
  translations/validators.fr.yml
Labels: Ready for code review

#7068 [PAP][LPN-519] optimize api sub queries perf
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Ready for code review

#7069 [PAP][LPN-520] display email address in survey export
  src/Exporter/SurveyExporter.php
  tests/Controller/Api/ExportSurveyAnswersControllerTest.php
Labels: Ready for code review

#7078 [PHP] Update guzzlehttp/psr7 lib
  composer.lock
Labels: dependencies, composer

#7079 Remove unused Mailchimp script
  templates/base.html.twig
Labels: Ready for code review

#7081 [Assessors] fix vote place wishes list on city change
  src/Controller/Assessor/AssessorController.php
  src/Form/AssessorRequestType.php
  src/Repository/VotePlaceRepository.php
  src/VotePlace/VotePlaceManager.php
  templates/assessor_request/index.html.twig
Labels: Ready for code review

#7083 [SMS] disable async mode for sending
  src/Repository/AdherentRepository.php
  src/SmsCampaign/Command/SendSmsCampaignCommand.php
Labels: Ready for code review

#7084 [Procurations] Fix near marching proxies
  src/Repository/ProcurationProxyRepository.php
Labels: Bug, Ready for code review

#7086 [Push] add deeplink to push notification
  migrations/Version20220323165400.php
  src/Entity/Notification.php
  src/Firebase/AbstractMessaging.php
  src/Firebase/Notification/AbstractNotification.php
  src/Firebase/Notification/NotificationInterface.php
  src/JeMarche/Notification/CommitteeEventCreatedNotification.php
  src/JeMarche/Notification/DefaultEventCreatedNotification.php
  src/JeMarche/Notification/EventReminderNotification.php
  src/JeMarche/Notification/NewsCreatedNotification.php
  src/JeMarche/Notification/RiposteCreatedNotification.php
Labels: Ready for code review

#7087 [Assessors][LPN-555] add vote place code on association page
  templates/assessor_manager/request.html.twig
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
Labels: Ready for code review

#7091 Improve GET PAP replies endpoint
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Ready for code review

#7093 Disable contact captcha
  features/api/membership_avecvous.feature
  src/Entity/Contact.php
Labels: Ready for code review

#7094 Validate contact address
  features/api/membership_avecvous.feature
  src/Entity/Contact.php
  src/Entity/EntityPostAddressTrait.php
  src/Entity/PostAddress.php
Labels: Ready for code review

#7097 Fix survey replies endpoint
  src/Repository/Jecoute/DataSurveyRepository.php
Labels: Bug, Ready for code review

#7096 [Procurations] Fix near marching proxies count
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
Labels: Bug, Ready for code review

#7098 [Procurations][LPN-508] increase the max limit result on other cities autocomplete
  src/Form/Procuration/ProcurationProxyType.php
Labels: Ready for code review

#7099 [Admin] Fix zones autocomplete
  config/packages/security.yaml
Labels: Bug, Ready for code review

#7103 Update participant count on prod
  src/Admin/Phoning/CampaignAdmin.php
  src/Api/Listener/PhoningCampaignParticipantsCountUpdateListener.php
  src/Command/PhoningCampaignUpdateParticipantsCountCommand.php
Labels: Ready for code review

#7104 fix wording
  src/Command/PhoningCampaignUpdateParticipantsCountCommand.php
Labels: Ready for code review

#7108 [Surveys][LPN-575] retrieve national surveys with national phoning and pap manager
  features/api/surveys.feature
  src/Api/Filter/JeMengageSurveyScopeFilter.php
Labels: Ready for code review

#7107 [Assessors][LPN-580][LPN-581] fix 403 on assessor requests
  src/Security/Voter/ManageAssessorVoter.php
Labels: Ready for code review

#7080 [AdherentMessage] Improve API filter endpoint
  features/api/adherents.feature
  features/api/scopes.feature
  front/kernel.js
  src/AdherentFilter/FilterBuilder/AdherentBasicFieldsFilterBuilder.php
  src/AdherentFilter/FilterBuilder/CommitteeMemberFilterBuilder.php
  src/AdherentMessage/Filter/AdherentMessageFilterInterface.php
  src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
  src/AdherentMessage/Listener/InitialiseMailchimpCampaignEntitySubscriber.php
  src/AdherentMessage/MailchimpCampaign/Handler/AbstractMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/AdherentZoneMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/CommitteeMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/CorrespondentMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ElectedRepresentativeMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/GenericMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/MailchimpCampaignHandlerInterface.php
  src/AdherentMessage/MailchimpCampaign/Handler/MunicipalChiefMailchimpCampaignHandler.php
  src/AdherentMessage/MailchimpCampaign/Handler/ReferentMailchimpCampaignHandler.php
  src/Command/MailchimpSyncAllAdherentsCommand.php
  src/Controller/Api/AdherentMessage/UpdateAdherentMessageFilterController.php
  src/Controller/Api/EventImageController.php
  src/DataFixtures/ORM/LoadReferentTagData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/Filter/AbstractAdherentMessageFilter.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
  src/Entity/AdherentMessage/Filter/GeneralFilterTrait.php
  src/Entity/EntityZoneTrait.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentInterestConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentRegistrationDateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionsBuilder.php
  src/Mailchimp/Driver.php
  src/Normalizer/AddressDenormalizer.php
  src/Validator/ValidMessageFilterSegmentValidator.php
  tests/Controller/Api/AdherentFilter/GetFilterCollectionControllerTest.php
Labels: Ready for code review

#7116 [PHP] update sentry lib
  composer.lock
Labels: dependencies, composer

#7117 [AdherentMessage] Enable orderBy filter
  front/kernel.js
  src/Controller/Api/EventImageController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Mailchimp/Driver.php
  src/Normalizer/AddressDenormalizer.php
Labels: Ready for code review

#7119 [Scope][PAP] Add PAP V2 feature
  features/api/scopes.feature
  src/Scope/FeatureEnum.php
  translations/messages.fr.yml
Labels: Ready for code review

#7095 [API] Improve document upload
  behat.yml.dist
  config/services/system.xml
  features/api/upload_documents.feature
  migrations/Version20220324112855.php
  src/Controller/UploadDocumentController.php
  src/Entity/CommitteeFeedItem.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Jecoute/News.php
  src/Entity/Listener/ContainingUserDocumentListener.php
  src/Entity/UserDocument.php
  src/Entity/UserDocumentInterface.php
  src/Entity/UserDocumentTrait.php
  src/Security/Voter/FileUploadVoter.php
  tests/Security/Voter/FileUploadVoterTest.php
Labels: Ready for code review

#7118 [API][PAP] Add local PAP campaign
  features/api/pap_campaigns.feature
  migrations/Version20220325172441.php
  src/Api/Filter/ScopeVisibilityFilter.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/EntityScopeVisibilityInterface.php
  src/Entity/EntityScopeVisibilityWithZoneInterface.php
  src/Entity/EntityScopeVisibilityWithZonesInterface.php
  src/Entity/Jecoute/News.php
  src/Entity/Pap/Campaign.php
  src/Entity/Phoning/Campaign.php
  src/Entity/Team/Team.php
  src/Normalizer/Pap/CampaignDenormalizer.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Pap/CampaignRepository.php
  src/Security/Voter/ScopeVisibilityVoter.php
  src/Validator/PapCampaignBeginAt.php
  src/Validator/PapCampaignBeginAtValidator.php
  src/Validator/PapCampaignVotePlaces.php
  src/Validator/PapCampaignVotePlacesValidator.php
  src/Validator/Scope/ScopeVisibilityValidator.php
  translations/validators.fr.yml
Labels: Ready for code review
