Repository parti-renaissance/espace-adherent, pull requests merged in 2022-10, with the labels that each got.

#7603 [PHP] Update Symfony 4.4.46
  composer.lock
  features/api/pap_campaigns.feature
Labels: dependencies, composer

#7609 [Don] find all donator and use the first one
  migrations/Version20221003152108.php
  src/Admin/DonatorAdmin.php
  src/Entity/Donator.php
  src/Repository/DonatorRepository.php
Labels: Ready for code review

#7605 Add RE filter on adherents list
  features/api/adherents.feature
  src/Entity/Projection/ManagedUser.php
  src/ManagedUsers/ColumnsConfigurator.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#7615 [Adhesion-v2] add entity for adherent request
  migrations/Version20221004155004.php
  src/Entity/Renaissance/Adhesion/AdherentRequest.php
Labels: Ready for code review

#7613 [JME] remove unused filter key from columns endpoint
  features/api/adherents.feature
  src/ManagedUsers/ColumnsConfigurator.php
Labels: Ready for code review

#7617 [Don] generate a new uuid for donation
  src/Controller/EnMarche/DonationController.php
  src/Controller/Renaissance/Adhesion/SummaryController.php
  src/Controller/Renaissance/Donation/MentionsController.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Donation/DonationRequestUtils.php
  src/Entity/Adherent.php
  tests/Donation/DonationFactoryTest.php
  tests/Donation/DonationRequestTest.php
  tests/Validator/FrenchAddressOrNationalityDonationValidatorTest.php
  tests/Validator/MaxFiscalYearDonationValidatorTest.php
  tests/Validator/MaxMonthDonationValidatorTest.php
Labels: Bug, Ready for code review

#7628 [Adhesion-v2] update form
  config/packages/workflows.yaml
  migrations/Version20221007154603.php
  src/Controller/Renaissance/Adhesion/ActivateController.php
  src/Controller/Renaissance/Adhesion/AdditionalInformationController.php
  src/Controller/Renaissance/Adhesion/FinishController.php
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Controller/Renaissance/Adhesion/ValidateController.php
  src/DataFixtures/ORM/LoadAdherentRequestData.php
  src/Donation/TransactionSubscriber.php
  src/Entity/Adherent.php
  src/Entity/Renaissance/Adhesion/AdherentRequest.php
  src/Form/Renaissance/Adhesion/AdditionalInfoType.php
  src/Membership/AdherentFactory.php
  src/Membership/EventListener/SendEmailValidationSubscriber.php
  src/Membership/MembershipNotifier.php
  src/Membership/MembershipRequestHandler.php
  src/Membership/UserEvents.php
  src/Repository/Renaissance/AdherentRequestRepository.php
  src/Subscription/SubscriptionListener.php
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/end_adhesion.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/adhesion/result.html.twig
  templates/renaissance/adhesion/validate.html.twig
Labels: Ready for code review

#7631 [Adhesion-v2] fix phpunit test
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#7632 [Adhesion-v2] allow resuming the contribution payment
  src/Controller/Renaissance/Adhesion/AmountController.php
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Entity/Renaissance/Adhesion/AdherentRequest.php
  src/Form/Renaissance/Adhesion/AdhesionAmountType.php
  src/Form/Renaissance/Adhesion/AdhesionMentionStep2Type.php
  src/Form/Renaissance/Adhesion/PrePaymentType.php
  src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
  templates/renaissance/adhesion/confirmation.html.twig
  templates/renaissance/adhesion/pre-payment.html.twig
  templates/renaissance/adhesion/summary.html.twig
  templates/renaissance/adhesion/validate.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#7633 [Admin] fix reports list page
  src/Twig/AdminReportRuntime.php
Labels: Bug, Ready for code review

#7635 Update post-login redirect url
  src/Renaissance/App/UrlGenerator.php
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7636 Update adhesion button wording
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7646 [Adhesion] Link Donator with Adherent
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Donation/DonationRequestHandler.php
Labels: Bug, Ready for code review

#7649 [Home] fix header button text center
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7647 [Adhesion-v2] update display of adhesion and donation flow
  assets/components/Adhesion/AdhesionTaxReturn.js
  assets/components/Donation/DonationAmountChooser.js
  assets/components/Donation/DonationWidget.js
  assets/style/components/_button.scss
  assets/style/components/_logo.scss
  assets/style/components/_separators.scss
  assets/style/components/index.scss
  assets/style/main.scss
  assets/style/mixins/_colors.scss
  assets/style/pages/_adhesion.scss
  public/images/renaissance/bain-foule-macron.jpg
  public/images/renaissance/logo-circle.svg
  tailwind.config.js
  templates/renaissance/adhesion/_layout.html.twig
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/confirmation.html.twig
  templates/renaissance/adhesion/end_adhesion.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/adhesion/partials/summary_row.html.twig
  templates/renaissance/adhesion/payment.html.twig
  templates/renaissance/adhesion/pre-payment.html.twig
  templates/renaissance/adhesion/result.html.twig
  templates/renaissance/adhesion/summary.html.twig
  templates/renaissance/adhesion/validate.html.twig
  templates/renaissance/donation/_layout.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/choose_donation_amount.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/donation/result.html.twig
  templates/renaissance/double_columns_layout.html.twig
  templates/renaissance/form_theme.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/left-side-content.html.twig
  templates/renaissance/partials/previous-next-buttons.html.twig
  tests/Controller/EnMarche/Security/RenaissanceSecurityControllerTest.php
Labels: Nice PR 🥳

#7650 [donation-v2] fix the donation flow display
  assets/components/AmountChooser.js
  assets/style/components/_button.scss
  assets/style/components/_donation.scss
  assets/style/mixins/_colors.scss
  templates/renaissance/donation/_layout.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/choose_donation_amount.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/donation/result.html.twig
Labels: Ready for code review

#7652 [LPN-1216] update donation request workflow state
  config/packages/workflows.yaml
Labels: Ready for code review

#7654 [Adhesion] Add back button
  config/packages/workflows.yaml
  templates/renaissance/adhesion/choose_amount.html.twig
  templates/renaissance/adhesion/confirmation.html.twig
  templates/renaissance/adhesion/end_adhesion.html.twig
  templates/renaissance/adhesion/pre-payment.html.twig
  templates/renaissance/adhesion/summary.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
  templates/renaissance/double_columns_layout.html.twig
  templates/renaissance/partials/left-side-content.html.twig
Labels: Ready for code review

#7653 [LPN-1217] rename session name
  config/packages/framework.yaml
Labels: Ready for code review

#7657 [Admin] allow Commitment sorting with drag & drop
  config/services/admin.xml
  src/Admin/CommitmentAdmin.php
Labels: Ready for code review

#7658 [Admin] preset position of commitment
  config/packages/sonata_admin.yaml
  src/Admin/CommitmentAdmin.php
  src/Entity/Commitment.php
Labels: Ready for code review

#7659 [Adhesion] dispatch validate event
  src/Membership/MembershipRequestHandler.php
Labels: Ready for code review

#7660 [Burex] add role field
  migrations/Version20221017232936.php
  src/Admin/ExecutiveOfficeMember/AbstractExecutiveOfficeMemberAdmin.php
  src/Collection/ExecutiveOfficeMemberCollection.php
  src/Command/ImportExecutiveOfficeMembersCommand.php
  src/DataFixtures/ORM/LoadExecutiveOfficeMemberData.php
  src/Entity/Biography/ExecutiveOfficeMember.php
  src/Entity/Biography/ExecutiveOfficeRoleEnum.php
  src/Repository/Biography/ExecutiveOfficeMemberRepository.php
  src/Validator/UniqueExecutiveOfficeMemberRole.php
  src/Validator/UniqueExecutiveOfficeMemberRoleValidator.php
  templates/renaissance/home.html.twig
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#7661 [Adhesion] sync adherent after payment
  src/Membership/MembershipRequestHandler.php
  translations/messages.fr.yml
Labels: Ready for code review

#7662 [Burex] fix member image height
  templates/renaissance/home.html.twig
Labels: Bug, Ready for code review

#7665 [LPN-1224] update social media list
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7669 [Clean] remove unused url generator
  config/services/cms.xml
  config/services/community.xml
  config/services/platform.xml
  src/Event/EventInvitationHandler.php
  src/Procuration/ProcurationProxyMessageFactory.php
  src/Routing/RemoteUrlGenerator.php
  tests/Procuration/ProcurationProxyMessageFactoryTest.php
Labels: Ready for code review

#7667 [Clean] remove unused CGU column related to Idea workshop
  features/api/adherents.feature
  features/api/user.feature
  migrations/Version20221020113016.php
  src/Entity/Adherent.php
  src/EventSubscriber/CommentsCguSubscriber.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
Labels: Ready for code review

#7670 [LPN-1228] Add new filter on AL space
  src/Committee/Filter/Enum/RenaissanceMembershipFilterEnum.php
  src/Committee/Filter/ListFilterObject.php
  src/Form/CommitteeMemberFilterType.php
  src/Repository/CommitteeMembershipRepository.php
  templates/committee_manager/list_members.html.twig
  templates/form_theme.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#7671 [LPN-1229] update RE filter
  migrations/Version20221021140835.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Repository/AdherentRepository.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#7674 [LPN-1232] add facebook pixel
  .env
  config/packages/twig.yaml
  templates/base_renaissance.html.twig
Labels: Ready for code review

#7675 [Mailchimp] fix synchro for RE adherents
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Bug, Ready for code review

#7683 [LPN-1239] add contact link in the footer
  templates/renaissance/home.html.twig
  templates/renaissance/partials/small-footer.html.twig
Labels: Ready for code review

#7686 Update node to v16
  .github/workflows/ci-cd.yml
  docker/dev/Dockerfile
Labels: Ready for code review, front-end

#7687 Improve Renaissance filters
  features/api/adherents.feature
  features/api/audience_segments.feature
  features/api/audiences.feature
  features/api/phoning_campaigns.feature
  migrations/Version20221026085426.php
  src/AdherentFilter/FilterBuilder/RenaissanceMembershipFilterBuilder.php
  src/Committee/Filter/Enum/RenaissanceMembershipFilterEnum.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
  src/Entity/AdherentMessage/Filter/GeneralFilterTrait.php
  src/Entity/Audience/AudienceFieldsTrait.php
  src/Entity/Audience/AudienceInterface.php
  src/Entity/Projection/ManagedUser.php
  src/Form/AdherentMessage/SimpleMessageFilterType.php
  src/Form/Audience/AudienceSnapshotType.php
  src/Form/CommitteeMemberFilterType.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/RenaissanceMembershipConditionBuilder.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/ManagedUsers/ColumnsConfigurator.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Renaissance/Membership/RenaissanceMembershipFilterEnum.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/Projection/ManagedUserRepository.php
  templates/committee_manager/list_members.html.twig
  templates/form_theme.html.twig
  templates/message/filter/message_filter.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#7689 [MyTeam] allow to add RE adherent as team member
  src/Validator/MyTeamMemberValidator.php
Labels: Bug, Ready for code review

#7691 update pixel snippet
  templates/base_renaissance.html.twig
Labels: Ready for code review

#7684 [LPN-1241] Remove facebook sdk
  app/data/static/pages-sharers/facebook-legislatives.jpg
  composer.json
  composer.lock
  config/services/community.xml
  config/services/external_services.xml
  config/services/http_client.yaml
  front/app.js
  front/components/FacebookPictureChooser.js
  front/pages/facebook_pictures.js
  public/images/facebook-example.jpg
  src/Controller/EnMarche/FacebookController.php
  src/Entity/FacebookProfile.php
  src/Facebook/PictureFilterer.php
  src/Facebook/PictureImporter.php
  src/Facebook/PictureUploader.php
  src/Facebook/ProfileImporter.php
  src/Repository/FacebookProfileRepository.php
  templates/facebook/_layout.html.twig
  templates/facebook/index.html.twig
  templates/facebook/show.html.twig
  tests/Controller/EnMarche/FacebookControllerTest.php
Labels: Ready for code review

#7693 Add .editorconfig
  .editorconfig
Labels: Ready for code review

#7695 [PHP] Remove polyfill for php8.1
  composer.json
  composer.lock
Labels: dependencies, composer

#7688 Add article carousel
  .gitignore
  assets/components/Carousel/Carousel.js
  assets/listeners/carousel.js
  assets/main.js
  assets/style/components/_carousel.scss
  assets/style/components/index.scss
  assets/style/main.scss
  features/sitemap.feature
  src/Controller/Renaissance/HomeController.php
  src/DataFixtures/ORM/LoadArticleData.php
  templates/article/partial/article-item.html.twig
  templates/renaissance/home.html.twig
  tests/Command/AlgoliaSynchronizeCommandTest.php
Labels: Ready for code review

#7696 [PHP8.1] Fix current call on object
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentGeoZoneConditionBuilder.php
Labels: Bug, Ready for code review

#7694 [LPN-1238] add new coordinator role with zone based role
  config/packages/security.yaml
  src/Adherent/AdherentRoleEnum.php
  src/Adherent/Authorization/ZoneBasedRoleTypeEnum.php
  src/AdherentSpace/AdherentSpaceEnum.php
  src/Admin/AdherentAdmin.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/Command/UpdateCoordinatorManagedAreaToZoneBasedRoleCommand.php
  src/Controller/EnMarche/Coordinator/CoordinatorCommitteeController.php
  src/Coordinator/CoordinatorAreaSectors.php
  src/Coordinator/Filter/AbstractCoordinatorAreaFilter.php
  src/Coordinator/Filter/CommitteeFilter.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/Adherent.php
  src/Entity/AdherentZoneBasedRole.php
  src/Form/Admin/CoordinatorManagedAreaType.php
  src/Geo/ManagedZoneProvider.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  src/Repository/CommitteeRepository.php
  src/Scope/Generator/RegionalCoordinatorScopeGenerator.php
  src/Scope/ScopeEnum.php
  templates/adherent/_list_my_sections.html.twig
  templates/adherent_space/_layout.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
  templates/coordinator/committees.html.twig
  tests/Controller/EnMarche/CoordinatorControllerTest.php
  tests/Procuration/ProcurationReliabilityProcessorTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#7698 Update tailwindcss config
  package.json
  tailwind.config.js
  tailwind.config.site.js
  yarn.lock
Labels: Ready for code review

#7700 Update Tailwind config for font size
  assets/style/main.scss
  tailwind.config.js
  tailwind.config.site.js
  templates/base_renaissance.html.twig
  templates/renaissance/adhesion/additional_information.html.twig
  templates/renaissance/adhesion/validate.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/home.html.twig
  templates/renaissance/partials/left-side-content.html.twig
  templates/renaissance/partials/small-footer.html.twig
Labels: Ready for code review

#7701 Fix display article carousel
  assets/components/Carousel/Carousel.js
  templates/article/partial/article-item.html.twig
Labels: Ready for code review
