Repository parti-renaissance/espace-adherent, pull requests merged in 2022-02, with the labels that each got.

#6842 [API][PAP] Change survey config
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
  src/Jecoute/ProfessionEnum.php
  src/Pap/CampaignHistoryStatusEnum.php
Labels: Ready for code review

#6823 PAP Admin - fix labels
  src/Admin/Pap/CampaignAdmin.php
Labels: Ready for code review

#6846 [API][PAP] Fix wording in a survey config
  features/api/pap_campaigns.feature
  src/Pap/CampaignHistoryStatusEnum.php
Labels: Ready for code review

#6847 Enable PAP feature by default for new adherent
  src/Membership/AdherentFactory.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#6845 [LPN-119] add address new request parameters
  features/api/pap_address.feature
  src/Controller/Api/Pap/GetNearPointsController.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6797 New layout for jemengage errors
  config/packages/twig.yaml
  config/routes/dev/twig.yaml
  config/services.yaml
  src/Coalition/CoalitionUrlGenerator.php
  src/ErrorRenderer/TwigErrorRenderer.php
  src/JeMengage/App/AppUrlGenerator.php
  templates/TwigBundle/Exception/error.html.twig
  templates/TwigBundle/Exception/jemengage/error.html.twig
  templates/TwigBundle/Exception/jemengage/error404.html.twig
  templates/TwigBundle/Exception/jemengage/error410.html.twig
  templates/TwigBundle/Exception/jemengage/error503.html.twig
  templates/jemengage/base.html.twig
Labels: Ready for code review

#6849 [PAP] Fix score endpoint
  src/Controller/Api/Pap/GetCampaignRankingController.php
Labels: Bug, Ready for code review

#6852 [Polls] avoid 404 on get endpoint
  features/api/polls.feature
  src/Controller/Api/PollController.php
Labels: Ready for code review

#6835 Local roles can get KPI of all pap campaigns
  features/api/pap_campaigns.feature
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6556 [PHP] update behat libs
  .php-cs-fixer.dist.php
  behat.yml.dist
  composer.json
  composer.lock
  config/bundles.php
  config/services_dev.yaml
  config/services_test.yaml
  features/api/scopes.feature
  features/bootstrap/bootstrap.php
  features/registration.feature
  src/Controller/Api/EventsController.php
  templates/membership/register.html.twig
  tests/Behat/Context/ChronosContext.php
  tests/Behat/Context/DIContext.php
  tests/Behat/Context/DonationContext.php
  tests/Behat/Context/EmailContext.php
  tests/Behat/Context/FeatureContext.php
  tests/Behat/Context/FixtureContext.php
  tests/Behat/Context/JsonContext.php
  tests/Behat/Context/NotificationContext.php
  tests/Behat/Context/RabbitMqContext.php
  tests/Behat/Context/ReferentTagContext.php
  tests/Behat/Context/RestContext.php
  tests/Behat/Context/SecurityContext.php
  tests/Behat/Context/SyncWithAPIContext.php
  tests/Behat/Context/TransactionalDatabaseContext.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6854 [API][MyTeam] Take into account delegated access in spaces (AdherentMessages, News, Events, Teams, Phoning, PAP, Surveys)
  features/api/adherent_messages.feature
  features/api/event_stats.feature
  features/api/events.feature
  features/api/jecoute_news.feature
  features/api/my_teams.feature
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  features/api/scopes.feature
  features/api/surveys.feature
  features/api/teams.feature
  src/Api/Filter/MyCreatedEventsFilter.php
  src/Api/Filter/PapCampaignHistoryScopeFilter.php
  src/Api/Filter/ScopeVisibilityFilter.php
  src/Controller/Api/AdherentMessage/UpdateAdherentMessageFilterController.php
  src/Controller/Api/Event/CancelEventController.php
  src/Controller/Api/EventImageController.php
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/Controller/Api/Pap/GetPapCampaignQuestionersStatsController.php
  src/Controller/Api/Pap/GetPapCampaignSurveyRepliesController.php
  src/DataFixtures/ORM/LoadDefaultEventData.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/DataFixtures/ORM/LoadInstitutionalEventData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Entity/Adherent.php
  src/Entity/Event/BaseEvent.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Geo/ManagedZoneProvider.php
  src/Normalizer/AdherentBlameableDenormalizer.php
  src/Normalizer/AuthorDenormalizer.php
  src/Normalizer/EventUserRegistrationNormalizer.php
  src/Normalizer/JecouteNewsNormalizer.php
  src/Scope/AuthorizationChecker.php
  src/Scope/FeatureEnum.php
  src/Scope/GeneralScopeGenerator.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Scope.php
  src/Security/Voter/CanManageEventVoter.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
  src/Security/Voter/ScopeVisibilityVoter.php
  src/Security/Voter/Survey/CanReadSurveyVoter.php
  src/Validator/Jecoute/SurveyScopeTargetValidator.php
  src/Validator/Scope/ScopeVisibilityValidator.php
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/EntityListener/RevokeDelegatedAccessListenerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#6862 [PAP] Update building stats and status simultaneously after a close/open action
  features/api/pap_address.feature
  src/Pap/Command/BuildingEventCommand.php
Labels: Ready for code review

#6863 [PAP] Improve building parts close/open action
  src/Controller/Api/Pap/BuildingEventController.php
  src/Pap/Command/BuildingEventAsyncCommand.php
  src/Pap/Command/BuildingEventCommand.php
  src/Pap/Command/BuildingEventCommandInterface.php
  src/Pap/Handler/BuildingEventCommandHandler.php
Labels: Ready for code review

#6864 [PAP] Fix visited doors count for building
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Bug, Ready for code review

#6861 [API][MyTeam] Take into account delegated access for Adherents + some tests
  features/api/adherents.feature
  features/api/pap_campaigns.feature
  src/Controller/Api/AdherentFilter/GetFilterCollectionController.php
  tests/Controller/Api/ExportPapCampaignSurveyAnswersControllerTest.php
  tests/Controller/Api/ExportPhoningCampaignSurveyAnswersControllerTest.php
  tests/Controller/Api/ExportSurveyAnswersControllerTest.php
Labels: Ready for code review

#6866 Fix adherents autocomplete
  features/api/adherents.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadUserData.php
  src/Membership/AdherentFactory.php
  src/Repository/AdherentRepository.php
  tests/Controller/Api/StatsControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
Labels: Ready for code review

#6860 [Tests] unskip donation tests
  features/javascript/donation.feature
  features/sync_with_api.feature
Labels: Ready for code review

#6867 [Admin] validate empty zone for zoneBasedRoles
  src/Validator/ZoneBasedRoles.php
  src/Validator/ZoneBasedRolesValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#6853 [LPN-120] add surveys to correspondent scope
  features/api/scopes.feature
  features/api/surveys.feature
  src/Api/Filter/JeMengageSurveyScopeFilter.php
  src/Controller/Api/Jecoute/GetSurveyRepliesController.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Security/Voter/Survey/CanReadSurveyVoter.php
  src/Validator/Jecoute/SurveyScopeTargetValidator.php
Labels: Ready for code review

#6869 [PAP] Fix department scoring
  dump/all-geo-zone.sql
  features/api/pap_campaigns.feature
  migrations/Version20220204164624.php
  src/Controller/Api/Pap/GetCampaignRankingController.php
  src/DataFixtures/ORM/LoadElectedRepresentativeZoneCategoryData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeZoneData.php
  src/DataFixtures/ORM/LoadGeoZoneData.php
  src/Entity/EntityZoneTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/Geo/ZoneTagEnum.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6870 [PHP] Update Scheb 2FA bundle
  composer.json
  composer.lock
  config/packages/scheb_2fa.yaml
  config/routes.yaml
  config/routes/scheb_2fa.yaml
  symfony.lock
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6868 [Admin] Display all types of event
  config/services/admin.xml
  src/Admin/EventAdmin.php
  src/Api/Listener/PreEventEditListener.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/BaseEventCategory.php
  src/Entity/Event/BaseEventWithCategory.php
  src/Entity/Event/CauseEvent.php
  src/Entity/Event/CoalitionEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/Entity/Event/DefaultCategoryOwnerTrait.php
  src/Entity/Event/DefaultEvent.php
  src/Entity/Event/EventCategoryInterface.php
  src/Entity/Event/InstitutionalEvent.php
  src/Mailer/Message/InstitutionalEventInvitationMessage.php
  templates/admin/event/edit.html.twig
  templates/admin/event/list_actions.html.twig
  templates/admin/event/list_committee.html.twig
  templates/admin/event/show.html.twig
  templates/admin/event/show_committee.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#6872 [PHP] Replace guzzle clients
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/csa_guzzle.yaml
  config/services.yaml
  config/services/community.xml
  config/services/external_services.xml
  config/services/http_client.yaml
  config/services/platform.xml
  config/services/services.xml
  config/services/system.xml
  config/services_dev.yaml
  src/Adherent/Unregistration/UnregistrationCommand.php
  src/Command/MailchimpCreateTagFromReferentTagCommand.php
  src/Command/MailchimpInitElectedRepresentativeSegmentsCommand.php
  src/Command/MailchimpListInterestsCommand.php
  src/Command/MailchimpSegmentUpdateDbSegmentIdsCommand.php
  src/Consumer/AbstractMailerConsumer.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/MembershipController.php
  src/Facebook/PictureImporter.php
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  src/Mandrill/EmailClient.php
  src/Map/GoogleStaticMapProvider.php
  src/MunicipalSite/ApiDriver.php
  src/Recaptcha/RecaptchaApiClient.php
  src/Recaptcha/RecaptchaApiClientInterface.php
  src/Validator/RecaptchaValidator.php
  symfony.lock
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
  tests/Consumer/AbstractMailerConsumerTest.php
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Mailer/Transport/ApiTransportTest.php
  tests/Test/Mailer/DummyEmailClient.php
  tests/Test/Recaptcha/DummyRecaptchaApiClient.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6874 [Admin] remove event category filter
  src/Admin/EventAdmin.php
Labels: Bug, Ready for code review

#6873 [PHP] replace zend-diactoros
  composer.json
  composer.lock
  config/packages/nyholm_psr7.yaml
  config/packages/psr_http_message_bridge.yaml
  config/services.yaml
  symfony.lock
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6875 [MyTeam] Separate EM and MyTeam delegated access
  features/api/scopes.feature
  migrations/Version20220204141925.php
  src/Adherent/Unregistration/Handlers/RemoveDelegatorDelegatedAccessesHandler.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Entity/Adherent.php
  src/Entity/MyTeam/DelegatedAccess.php
  src/Entity/MyTeam/Member.php
  src/MyTeam/Api/Listener/PostWriteMyTeamMemberListener.php
  src/Scope/FeatureEnum.php
  src/Scope/Generator/AbstractScopeGenerator.php
  tests/Controller/Api/MyTeam/MyTeamMemberControllerTest.php
  tests/EntityListener/RevokeDelegatedAccessListenerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
Labels: Ready for code review

#6876 [LPN-153] add custom message for adherent unregistration
  src/Adherent/UnregistrationHandler.php
  src/Controller/Api/ProfileController.php
  src/Entity/Unregistration.php
  src/Membership/MembershipRequestHandler.php
Labels: Ready for code review

#6878 [LNP-164][PAP] Improve address near endpoint
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  migrations/Version20220207135908.php
  src/Command/PapAssociateActiveCampaignsToBuildingsCommand.php
  src/Controller/Api/Pap/GetNearPointsController.php
  src/Entity/Pap/Campaign.php
  src/Repository/Pap/AddressRepository.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#6881 [API][Events] Return only events of user's department or borough
  features/api/events.feature
  src/Api/Doctrine/BaseEventExtension.php
  src/Controller/Api/Pap/GetCampaignRankingController.php
  src/Entity/EntityZoneTrait.php
Labels: Ready for code review

#6883 Allow MyTeam members access to Jemengage Web
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/Repository/MyTeam/DelegatedAccessRepository.php
  src/Security/Voter/DataCornerVoter.php
  tests/Controller/EnMarche/Security/JeMengageSecurityControllerTest.php
  tests/Security/Voter/DataCornerVoterTest.php
Labels: Ready for code review

#6890 Fix multiple use of withGeoZones method
  src/Api/Doctrine/BaseEventExtension.php
  src/Repository/GeoZoneTrait.php
Labels: Bug, Ready for code review

#6882 Remove Correspondent Email case
  .env
  features/api/profile.feature
  src/DataFixtures/ORM/LoadSubscriptionTypeData.php
  src/Form/AdherentEmailSubscriptionType.php
  src/Mailchimp/MailchimpSubscriptionLabelMapping.php
  src/Subscription/SubscriptionTypeEnum.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MailchimpWebhookControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
Labels: Ready for code review

#6885 Remove unused scope feature - phoning
  features/api/scopes.feature
  src/AdherentFilter/FilterBuilder/SmsAndEmailSubscriptionStatusFilterBuilder.php
  src/Scope/FeatureEnum.php
  translations/messages.fr.yml
Labels: Ready for code review

#6898 [AdherentMessage] Fix message endpoints for delegated access
  features/api/audience_segments.feature
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/Segment/AudienceSegment.php
  src/Validator/ValidScopeValidator.php
Labels: Ready for code review

#6900 [AdherentMessage] fix audience segment endpoint
  features/api/scopes.feature
  src/DataFixtures/ORM/LoadDelegatedAccessData.php
  src/Normalizer/AudienceFilterDenormalizer.php
  src/Scope/GeneralScopeGenerator.php
Labels: Ready for code review

#6901 [CI] fix clean registry workflow
  .github/actions/docker-login/action.yml
  .github/workflows/clean-registry.yml
Labels: Bug, Ready for code review

#6896 Use new host for procuration platform
  .env
  .env.test
  config/routes.yaml
  config/services.yaml
  docker-compose.override.yml.dist
  features/javascript/procuration_proxy.feature
  features/javascript/procuration_request.feature
  phpunit.xml.dist
  src/Controller/Procuration/ProcurationController.php
  templates/procuration/proxy/thanks.html.twig
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/DonationControllerTest.php
  tests/Controller/EnMarche/EventManagerControllerTest.php
  tests/Controller/Procuration/ProcurationControllerTest.php
  tests/bootstrap.php
Labels: Ready for code review

#6893 Use cms blocks to display procuration wording
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/Twig/CmsBlockExtension.php
  src/Twig/CmsBlockRuntime.php
  templates/procuration/_faq.html.twig
  templates/procuration/choose_election.html.twig
  templates/procuration/landing.html.twig
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/proxy/thanks.html.twig
  templates/procuration/request/election_rounds.html.twig
  templates/procuration/request/my_request.html.twig
  templates/procuration/request/thanks.html.twig
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#6903 [Procuration] Update proxy form
  config/routes.yaml
  features/javascript/procuration_proxy.feature
  front/style/pages/_procuration.scss
  migrations/Version20220211115509.php
  src/Controller/IntlController.php
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  templates/procuration/proxy/proposal.html.twig
  tests/Controller/Procuration/ProcurationControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#6909 [API][Events] Add event category validation
  features/api/events.feature
  src/Entity/Event/BaseEvent.php
  src/Validator/EventCategory.php
  src/Validator/EventCategoryValidator.php
Labels: Ready for code review

#6904 [API] Revert delegated access when user has back delegated role
  src/MyTeam/Api/Listener/PostWriteMyTeamMemberListener.php
  src/MyTeam/DelegatedAccessManager.php
  src/MyTeam/Listener/AdherentChangeListener.php
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#6902 [API][Events] Allow creation of events only in user's managed zones
  features/api/events.feature
  src/Entity/Event/BaseEvent.php
  src/Validator/AddressInScopeZones.php
  src/Validator/AddressInScopeZonesValidator.php
  translations/validators.fr.yml
Labels: Ready for code review

#6895 [API][PAP] Add a filter and order to CampaignHistory list + fix national campaign KPI for a local role
  features/api/pap_campaigns.feature
  src/Entity/Pap/CampaignHistory.php
  src/Normalizer/Pap/AppendCampaignStatsNormalizer.php
  src/Pap/CampaignHistoryStatusEnum.php
  src/Repository/Pap/CampaignHistoryRepository.php
Labels: Ready for code review

#6915 Fix inseeCode search from address
  src/Geo/Subscriber/ZoneAssignerSubscriber.php
  src/Geo/ZoneMatcher.php
  src/Intl/FranceCitiesBundle.php
Labels: Ready for code review

#6899 Add some geo/address info to surveys export
  src/Entity/Pap/Address.php
  src/Exporter/PapCampaignSurveyRepliesExporter.php
  src/Exporter/PhoningCampaignSurveyRepliesExporter.php
  src/Exporter/SurveyExporter.php
  src/Repository/Jecoute/DataSurveyRepository.php
  tests/Controller/Api/ExportPapCampaignSurveyAnswersControllerTest.php
  tests/Controller/Api/ExportPhoningCampaignSurveyAnswersControllerTest.php
  tests/Controller/Api/ExportSurveyAnswersControllerTest.php
Labels: Ready for code review

#6917 Procuration wording & style
  app/data/static/procuration.jpg
  app/data/static/procuration_2.jpg
  front/style/layout/_buttons.scss
  front/style/mixins/_colors.scss
  front/style/pages/_procuration.scss
  templates/procuration/_layout.html.twig
  templates/procuration/landing.html.twig
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/proxy/thanks.html.twig
Labels: front-end

#6920 [PHP] Update twig lib
  composer.lock
Labels: Ready for code review, dependencies, composer

#6886 [LPN-147] add event sync on algolia
  config/packages/algolia_search.yaml
  config/settings/algolia_search/event-settings.json
  config/settings/algolia_search/jemengage_timeline_feed-settings.json
  src/Controller/Api/JeMengage/GetTimelineFeedsController.php
  src/Entity/Algolia/AlgoliaJeMengageTimelineFeed.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Event/CommitteeEvent.php
  src/JeMengage/Timeline/TimelineFeedTypeEnum.php
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
  src/Normalizer/Indexer/EventNormalizer.php
  src/Normalizer/Indexer/PapCampaignNormalizer.php
  src/Normalizer/Indexer/PhoningCampaignNormalizer.php
  tests/Command/AlgoliaSynchronizeCommandTest.php
Labels: Ready for code review

#6921 [Procuration] Enable procuration request by default
  src/Controller/Procuration/ProcurationController.php
Labels: Ready for code review

#6924 Change email sender pour Jemengage emails
  features/api/membership_jemengage.feature
  src/Mailer/Message/JeMengage/AbstractJeMengageMessage.php
Labels: Ready for code review

#6922 fix deploy
  src/Normalizer/Indexer/EventNormalizer.php
  src/Normalizer/JecouteRegionNormalizer.php
Labels: Ready for code review

#6923 [API] Take into account an order parameter in snake_case
  config/services.yaml
  features/api/causes.feature
  features/api/events.feature
  features/api/pap_campaigns.feature
  src/Api/Filter/OrderFilter.php
  src/Entity/Coalition/Cause.php
  src/Entity/Event/BaseEvent.php
  src/Entity/Pap/CampaignHistory.php
Labels: Ready for code review

#6928 [Procuration] Improve request forms
  front/style/pages/_procuration.scss
  src/Controller/Api/ScopesController.php
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  src/Mailer/Message/Procuration/AbstractProcurationMessage.php
  src/Repository/CommitteeMembershipRepository.php
  templates/components/projets-citoyens.html.twig
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/election_rounds.html.twig
  templates/procuration/request/my_request.html.twig
  templates/procuration/request/profile.html.twig
  templates/procuration/request/vote.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#6929 [PushToken] improve voter by checking device
  src/Security/Voter/PushTokenAuthorVoter.php
Labels: Ready for code review

#6930 [Procuration] update metadata
  templates/base.html.twig
  templates/procuration/_layout.html.twig
  templates/procuration/choose_election.html.twig
  templates/procuration/landing.html.twig
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/my_request.html.twig
Labels: Ready for code review

#6934 fix campaigns indexing
  src/Normalizer/Indexer/PapCampaignNormalizer.php
  src/Normalizer/Indexer/PhoningCampaignNormalizer.php
Labels: Ready for code review

#6937 [PHP] Update sonata libs
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  src/Admin/ArticleAdmin.php
  src/Admin/ClarificationAdmin.php
  src/Admin/EventAdmin.php
  src/Admin/HomeBlockAdmin.php
  src/Admin/InstitutionalEventAdmin.php
  src/Admin/MediaAdmin.php
  src/Admin/MoocChapterAdmin.php
  src/Admin/OrderArticleAdmin.php
  src/Admin/ProcurationProxyAdmin.php
  src/Admin/ProcurationRequestAdmin.php
  src/Admin/ProposalAdmin.php
  src/Admin/ReportAdmin.php
  src/Admin/RepublicanSilenceAdmin.php
  src/Admin/SocialShareAdmin.php
  src/Admin/TerritorialCouncil/TerritorialCouncilMembershipLogAdmin.php
  src/Admin/UnregistrationAdmin.php
  src/Algolia/Sonata/Model/ModelManager.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6942 Allow delegated correspondent to create mails
  features/api/adherent_messages.feature
  src/AdherentMessage/AdherentMessageTypeEnum.php
Labels: Bug, Ready for code review

#6943 fix menu
  config/services/admin.xml
Labels: Ready for code review

#6944 [Procuration] fix foreign address on form
  features/javascript/procuration_proxy.feature
  features/javascript/procuration_request.feature
  front/app.js
  front/pages/procuration_proxy.js
  front/pages/procuration_request.js
  front/services/address/AddressObject.js
  front/services/form/changeFieldsVisibility.js
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/profile.html.twig
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Bug, Ready for code review

#6941 [Procuration] replace otherVoteCities by Zone relation
  features/api/zones.feature
  migrations/Version20220217124001.php
  migrations/Version20220218125939.php
  src/Controller/Api/Zone/ZoneAutocompleteSelect2Controller.php
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  src/Validator/ZoneType.php
  src/Validator/ZoneTypeValidator.php
  templates/procuration/proxy/proposal.html.twig
Labels: Ready for code review

#6947 Fix creation mails and mail filters by a delegated role
  features/api/audience_segments.feature
  features/api/audiences.feature
  src/Normalizer/AudienceDenormalizer.php
  src/Scope/AuthorizationChecker.php
  src/Security/Voter/RequestScopeVoter.php
  src/Validator/ValidScopeValidator.php
Labels: Bug, Ready for code review

#6945 [PHP] Update extra-framework-bundle lib
  composer.json
  composer.lock
  config/services/compatibility.yaml
  src/Admin/DatagridDecorator.php
  src/Security/Listener/SecurityListener.php
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀

#6948 fix header block form fields
  src/Admin/JeMengage/HeaderBlockAdmin.php
Labels: Ready for code review

#6949 [LPN-289] fix questions remove on update endpoint
  features/api/surveys.feature
  src/Entity/Jecoute/Survey.php
  src/Normalizer/UpdateSurveyDenormalizer.php
  translations/validators.fr.yml
Labels: Ready for code review

#6950 [LPN-317] change date format on timeline feed indexing
  src/Normalizer/Indexer/AbstractJeMengageTimelineFeedNormalizer.php
Labels: Ready for code review

#6951 [Procuration] keep otherVoteCities field only for FR proxies
  templates/procuration/proxy/proposal.html.twig
Labels: Ready for code review

#6952 Enable default subs types on resubscribe action
  src/Mailchimp/SignUp/SignUpHandler.php
Labels: Bug, Ready for code review

#6954 Synchronize boroughs to mailchimp
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Ready for code review

#6957 [Admin][News] Add 'pinned' and 'enriched' fields and make some other modifications
  config/services/admin.xml
  features/api/jecoute_news.feature
  migrations/Version20220217113503.php
  src/Admin/Jecoute/NewsAdmin.php
  src/Controller/Admin/AdminJecouteNewsCRUDController.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/Entity/Jecoute/News.php
  src/Jecoute/NewsHandler.php
  src/Repository/Jecoute/NewsRepository.php
  src/Validator/Jecoute/NewsText.php
  src/Validator/Jecoute/NewsTextValidator.php
  templates/admin/jecoute/news/action_pin.html.twig
  templates/admin/jecoute/news/edit.html.twig
  templates/admin/layout.html.twig
  translations/validators.fr.yml
Labels: Ready for code review

#6958 [LPN-136] add category filter
  src/Admin/EventAdmin.php
Labels: Ready for code review

#6961 Send mail with JME template for update/cancel/registration event when JME app/Web
  src/Api/Listener/PostEventEditListener.php
  src/AppCodeEnum.php
  src/Entity/Event/EventRegistration.php
  src/Event/EventMessageNotifier.php
  src/Event/EventRegistrationCommand.php
  src/Event/EventRegistrationFactory.php
  src/Event/EventRegistrationSubscriber.php
  src/EventListener/SendEventUpdateNotificationListener.php
  tests/Controller/Api/Event/EventControllerTest.php
  tests/TestHelperTrait.php
Labels: Bug, Ready for code review

#6962 [Procuration] transform birthday field
  src/Entity/ProcurationRequest.php
  src/Form/Procuration/AbstractProcurationType.php
  src/Form/Procuration/ProcurationProxyType.php
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/election_rounds.html.twig
  templates/procuration/request/profile.html.twig
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#6966 [Phoning] Use DateTime typehint to avoid injecting DateTimeImmutable …
  src/DataFixtures/ORM/LoadPhoningCampaignData.php
  src/Entity/Phoning/Campaign.php
Labels: Bug, Ready for code review

#6965 [PHP] Downgrade Sonata exporter to 2.7.0 for being compatible with do…
  composer.json
  composer.lock
Labels: Bug, Ready for code review, dependencies, composer

#6967 [PAP] Create a new Messenger queue for PAP
  config/packages/messenger.yaml
  src/Pap/Command/AsynchronousMessageInterface.php
  src/Pap/Command/BuildingEventAsyncCommand.php
  src/Pap/Command/CreateBuildingPartsCommand.php
  src/Pap/Command/UpdateCampaignAddressInfoCommand.php
  src/Pap/Command/UpdateStatsCommand.php
Labels: Ready for code review

#6963 rename new ciblage column
  migrations/Version20220223181739.php
  src/Admin/Pap/CampaignAdmin.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#6968 Change reply-To and sender name for Correspondent's emails
  features/api/adherent_messages.feature
  src/Entity/AdherentMessage/CorrespondentAdherentMessage.php
  src/Mailchimp/Campaign/Listener/SetCampaignReplyToSubscriber.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#6975 [API][News] Fix news update access
  features/api/jecoute_news.feature
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/DataFixtures/ORM/LoadMyTeamData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Jecoute/JecouteSpaceEnum.php
  src/Security/Voter/ChangeJecouteNewsVoter.php
Labels: Ready for code review

#6964 [API][News] Modify news list
  features/api/jecoute_news.feature
  src/Api/Doctrine/JecouteNewsExtension.php
  src/DataFixtures/ORM/LoadJecouteNewsData.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/Jecoute/News.php
  src/Jecoute/JecouteSpaceEnum.php
  src/Normalizer/JecouteNewsNormalizer.php
  src/Utils/StringCleaner.php
  templates/admin/layout.html.twig
Labels: Ready for code review

#6974 Donation layout
  templates/donation/index.html.twig
  templates/donation/informations.html.twig
  templates/donation/paybox.html.twig
  templates/donation/result.html.twig
Labels: Ready for code review

#6969 [Assessor][LPN-340] move assessor on avecvous domain
  .env
  .env.test
  config/routes.yaml
  config/services.yaml
  src/Controller/Assessor/AssessorController.php
  tests/Controller/Assessor/AssessorControllerTest.php
Labels: Ready for code review

#6980 [Procuration] Show near matched proxies for manager
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Procuration/ProcurationManager.php
  src/Repository/ProcurationProxyRepository.php
  templates/procuration_manager/_matching_proxy.html.twig
  templates/procuration_manager/request.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
Labels: Ready for code review

#6977 [PHP] Replace abandoned twig/extension
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig_extentions.yaml
  config/services/twig.yaml
  templates/adherent/home.html.twig
  templates/adherent/my_activity_events.html.twig
  templates/adherent_profile/_funnel_layout.html.twig
  templates/adherent_profile/_layout.html.twig
  templates/adherent_profile/activity/_donations.html.twig
  templates/adherent_profile/activity/_events.html.twig
  templates/admin/CRUD/list_datetime.html.twig
  templates/admin/adherent/ban.html.twig
  templates/admin/certification_request/_macros.html.twig
  templates/admin/certification_request/approve.html.twig
  templates/admin/certification_request/block.html.twig
  templates/admin/certification_request/refuse.html.twig
  templates/admin/certification_request/show.html.twig
  templates/admin/consultation/list_period.html.twig
  templates/admin/donation/list_amount.html.twig
  templates/admin/donator/edit.html.twig
  templates/admin/donator/list_last_donation.html.twig
  templates/admin/donator/show_donations.html.twig
  templates/admin/election/city_card/edit.html.twig
  templates/admin/poll/show.html.twig
  templates/article/actualites.html.twig
  templates/article/article.html.twig
  templates/certification_request/form.html.twig
  templates/committee/_election_box.html.twig
  templates/committee/_sidebar.html.twig
  templates/committee/candidacy/form_committee_adherent.html.twig
  templates/committee/timeline/_event.html.twig
  templates/committee_designation/list.html.twig
  templates/committee_designation/show_layout.html.twig
  templates/committee_designation/voters_list.html.twig
  templates/components/_adherent_session_modal.html.twig
  templates/donation/informations.html.twig
  templates/donation/result.html.twig
  templates/elected_representative/show.html.twig
  templates/election_results_reporter/form.html.twig
  templates/election_vote_results/_form_layout.html.twig
  templates/events/_layout.html.twig
  templates/events/show.html.twig
  templates/form_theme.html.twig
  templates/form_theme_admin.html.twig
  templates/helper/vote_result_macro.html.twig
  templates/message/list.html.twig
  templates/message/list_referent_instances.html.twig
  templates/national_council/partials/_election_box.html.twig
  templates/referent/committee/designations_list.html.twig
  templates/referent/territorial_council/_convocation_feed_item.html.twig
  templates/search/_events.html.twig
  templates/territorial_council/partials/_election_box.html.twig
  templates/territorial_council/political_committee/official_reports.html.twig
  templates/territorial_council_designation/election_results/show_layout.html.twig
  templates/territorial_council_designation/election_results/voters_list.html.twig
  templates/territorial_council_designation/list.html.twig
  templates/user/my_donation.html.twig
  templates/voting_platform/results/_stats_block.html.twig
Labels: Ready for code review, dependencies, composer, Symfony 5 🚀
