Repository parti-renaissance/espace-adherent, pull requests merged in 2022-05, with the labels that each got.

#7258 [AdherentMessage] Check filter synchro status
  features/api/pap_campaigns.feature
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#7261 [Procuration] Add some wording to procuration forms
  templates/procuration/proxy/proposal.html.twig
  templates/procuration/request/profile.html.twig
Labels: Ready for code review

#7259 [Procuration] Disable/enable a procuration request and list disabled requests
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationRequest.php
  src/Procuration/Filter/ProcurationRequestFilters.php
  src/Procuration/ProcurationManager.php
  src/Repository/ProcurationRequestRepository.php
  templates/procuration_manager/_layout.html.twig
  templates/procuration_manager/_requests_list.html.twig
  templates/procuration_manager/requests.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#7260 [LegislativeCandidate] remove old space
  .env
  config/packages/twig.yaml
  config/services.yaml
  config/services/platform.xml
  src/Controller/EnMarche/AdherentMessage/LegislativeCandidateMessageController.php
  src/Controller/EnMarche/LegislativeCandidateController.php
  src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
  src/Controller/EnMarche/PageController.php
  src/Form/LegislativeCampaignContactMessageType.php
  src/Legislative/LegislativeCampaignContactMessage.php
  src/Legislative/LegislativeCampaignContactMessageHandler.php
  src/Mailer/Message/LegislativeCampaignContactMessage.php
  src/TerritorialCouncil/Convocation/ConvocationObject.php
  templates/adherent/_list_my_sections.html.twig
  templates/invitation/adherent_space/_base_legislative_candidate_space.html.twig
  templates/legislative_candidate/_layout.html.twig
  templates/legislative_candidate/_sidebar.html.twig
  templates/legislative_candidate/confirm_newsletter.html.twig
  templates/legislative_candidate/contact.html.twig
  templates/legislative_candidate/platform.html.twig
  templates/managed_users/_base_legislative_candidate_space.html.twig
  templates/message/_base_legislative_candidate.html.twig
  tests/Controller/EnMarche/LegislativesControllerTest.php
  tests/Controller/EnMarche/PageControllerTest.php
  translations/messages.fr.yml
Labels: Ready for code review

#7263 [AdherentMessage] fix recipient count
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Ready for code review

#7264 [Procuration] Add page to show procuration proxy information
  front/style/pages/_procuration.scss
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  templates/procuration_manager/_proposals_list.html.twig
  templates/procuration_manager/proposal.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
Labels: Ready for code review

#7265 [Procuration] Show disable mode of procuration request
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationRequest.php
  src/Procuration/Handler/CheckProcurationAuthorHandler.php
  templates/procuration_manager/_requests_list.html.twig
  templates/procuration_manager/requests.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
Labels: Ready for code review

#7269 [AdherentMessage] fix reset message state
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
Labels: Bug, Ready for code review

#7268 Remove useless tel: prefix for phone
  templates/assessor_manager/_assessor_profile.html.twig
  templates/procuration/request/my_request.html.twig
  templates/procuration_manager/_matching_proxy.html.twig
  templates/procuration_manager/associate.html.twig
  templates/procuration_manager/deassociate.html.twig
  templates/procuration_manager/request.html.twig
Labels: Ready for code review

#7267 [Procuration] Make a voter number field of the procuration proxy required
  src/Entity/ProcurationProxy.php
  src/Form/Procuration/ProcurationProxyType.php
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#7270 [Procuration] Remove mention 'non required' from voter number form field
  templates/procuration/proxy/proposal.html.twig
Labels: Ready for code review

#7274 [LegislativeCandidate] Add menu link for JME
  templates/adherent/_list_my_sections.html.twig
Labels: Ready for code review

#7275 [Admin] add national region role to admin jecoute role group
  config/packages/security.yaml
Labels: Ready for code review

#7277 [PAP] replace subResource VotePlace route by classic collection route
  src/Controller/Api/Pap/GetCampaignVotePlacesController.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
Labels: Bug, Ready for code review

#7276 Allow JME user impersonification
  src/Controller/OAuth/OAuthServerController.php
  src/Security/Voter/DataCornerVoter.php
  src/Twig/OAuthClientExtension.php
  src/Twig/OAuthClientRuntime.php
  templates/admin/adherent/list_actions.html.twig
  tests/Security/Voter/AbstractAdherentVoterTest.php
  tests/Security/Voter/DataCornerVoterTest.php
Labels: Ready for code review

#7281 [Admin] Fix Adherent instance quality form type
  config/services.yaml
  src/Entity/Adherent.php
  src/Entity/Instance/AdherentInstanceQuality.php
  src/Form/Admin/AdherentInstanceQualityType.php
Labels: Bug, Ready for code review

#7278 Fix AdherentMessageTypeEnum for legislative candidates
  src/AdherentMessage/AdherentMessageTypeEnum.php
Labels: Ready for code review

#7282 [Scope] expose latitude & longitude of scope zone
  features/api/scopes.feature
  src/Entity/Geo/GeoTrait.php
  src/Entity/GeoPointTrait.php
Labels: Ready for code review

#7279 [Procuration] Apply proxies count for every election round and change calculation of availability
  front/style/layout/_base.scss
  migrations/Version20220504182132.php
  src/Admin/AdherentAdmin.php
  src/Admin/ProcurationProxyAdmin.php
  src/Command/ProcessProcurationProxyElectionRoundAvailabilitiesCommand.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationProxyElectionRound.php
  src/Form/Procuration/ProcurationProxyType.php
  src/Procuration/Filter/ProcurationFilters.php
  src/Procuration/Filter/ProcurationProxyProposalFilters.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/ProcurationRequestRepository.php
  src/Repository/ProcurationTrait.php
  templates/procuration/proxy/_available_rounds.html.twig
  templates/procuration_manager/_matching_proxy.html.twig
  templates/procuration_manager/_proposals_list.html.twig
  templates/procuration_manager/associate.html.twig
  templates/procuration_manager/deassociate.html.twig
  templates/procuration_manager/proposal.html.twig
  templates/procuration_manager/proposals.html.twig
  templates/procuration_manager/request.html.twig
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
  tests/Controller/Procuration/ProcurationControllerTest.php
  tests/Entity/ProcurationProxyTest.php
  tests/Entity/ProcurationRequestTest.php
Labels: Ready for code review

#7285 [AdherentMessage][Mailchimp] Fix filter application when message has not been changed and fix legislative candidate audience synchronization
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentRegistrationDateConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactAgeConditionBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/ContactNameConditionBuilder.php
Labels: Bug, Ready for code review

#7292 [OAuth] set switch_user param on redirection on AuthCodeGrant
  src/Controller/OAuth/OAuthServerController.php
Labels: Ready for code review

#7293 [Mailchimp] Enable sync log
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
Labels: Ready for code review

#7294 [Mailchimp] update adherent mailchimp status on sync
  src/Mailchimp/Driver.php
  src/Mailchimp/Manager.php
  src/Mailchimp/Synchronisation/Handler/AdherentChangeCommandHandler.php
Labels: Ready for code review

#7296 Fix contact email
  templates/procuration/request/my_request.html.twig
Labels: Ready for code review

#7297 Simplify Kernel class
  src/Kernel.php
  var/cache/.gitkeep
  var/logs/.gitkeep
Labels: Ready for code review

#7303 [API] Add filter to return only adherents, JME users or both
  features/api/adherents.feature
  src/AdherentFilter/FilterBuilder/OnlyJeMengageUsersFilterBuilder.php
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/ManagedUsers/Filter/CorrespondentFilterFactory.php
  src/ManagedUsers/Filter/LegislativeCandidateFilterFactory.php
  src/ManagedUsers/ManagedUsersFilter.php
  src/Repository/Projection/ManagedUserRepository.php
  tests/Controller/Api/AdherentList/AdherentListControllerTest.php
Labels: Ready for code review

#7302 Make donation index content editable
  src/DataFixtures/ORM/LoadCmsBlockData.php
  templates/donation/index.html.twig
Labels: Ready for code review

#7304 Remove electoral checkbox in event management
  src/Admin/EventAdmin.php
  src/Form/EventCommandType.php
  templates/committee_manager/add_event.html.twig
  templates/event_manager/_form_layout.html.twig
  templates/events/edit.html.twig
  tests/Controller/EnMarche/EventManager/ReferentEventManagerControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
Labels: Ready for code review

#7306 [API][PAP] Delete a PAP campaign
  features/api/pap_campaigns.feature
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/Entity/Pap/Campaign.php
  src/Security/Voter/CanDeletePapCampaignVoter.php
Labels: Ready for code review

#7310 [API] Enable/disable a PAP campaign
  features/api/pap_campaigns.feature
  migrations/Version20220519181035.php
  src/Api/Doctrine/LoadActivePapCampaignExtension.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/Entity/Pap/Campaign.php
Labels: Ready for code review

#7287 [LPN-765] implement new france cities service version
  features/api/adherents.feature
  features/api/profile.feature
  features/api/user.feature
  features/javascript/registration.feature
  src/AdherentMessage/MailchimpCampaign/Handler/MunicipalChiefMailchimpCampaignHandler.php
  src/Controller/EnMarche/AssessorSpace/MunicipalChiefAssessorSpaceController.php
  src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
  src/Controller/EnMarche/ReferentController.php
  src/Controller/IntlController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/Form/AddressType.php
  src/Form/CreateVotePlaceType.php
  src/FranceCities/CitiesStorage.php
  src/FranceCities/CitiesStorageInterface.php
  src/FranceCities/CityValueObject.php
  src/FranceCities/FranceCities.php
  src/Intl/FranceCitiesBundle.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/MunicipalChiefToAdherentConditionBuilder.php
  src/Normalizer/AddressDenormalizer.php
  src/Repository/Geo/ZoneRepository.php
  src/Repository/Projection/ManagedUserRepository.php
  src/Twig/AppIntlExtension.php
  src/Twig/AppIntlRuntime.php
  src/Validator/AddressValidator.php
  templates/admin/application_request/show_favorite_cities.html.twig
  templates/application_request/_form_theme.html.twig
  templates/referent/_form_theme.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
  tests/Controller/Api/IntlControllerTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/Coalition/CausesControllerTest.php
  tests/Controller/OAuth/OAuthServerControllerTest.php
  tests/FranceCities/FranceCitiesTest.php
  tests/JeMarche/NotificationTopicBuilderTest.php
  tests/Repository/AdherentRepositoryTest.php
Labels: Ready for code review

#7325 [JS] remove unused react-power-select lib
  package.json
  yarn.lock
Labels: dependencies, npm

#7315 [LPN-812] implement cached city storage
  config/packages/framework.yaml
  config/services.yaml
  src/FranceCities/CachedCitiesStorage.php
Labels: Work in progress
