Repository parti-renaissance/espace-adherent, pull requests merged in 2022-06, with the labels that each got.

#7329 [Assessor] update votePlace relation
  migrations/Version20220601181917.php
  src/Address/PostAddressFactory.php
  src/Assessor/AssessorManager.php
  src/Assessor/AssessorRequestExporter.php
  src/Assessor/AssessorRequestFactory.php
  src/Assessor/Filter/CitiesFilters.php
  src/Assessor/Filter/VotePlaceFilters.php
  src/Controller/EnMarche/AssessorManagerController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadAssessorRequestData.php
  src/DataFixtures/ORM/LoadElectionVotePlaceData.php
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadVotePlaceData.php
  src/DataFixtures/ORM/LoadVotePlaceResultData.php
  src/Entity/AssessorRequest.php
  src/Entity/AssessorRoleAssociation.php
  src/Entity/Donation.php
  src/Entity/Election/VotePlace.php
  src/Entity/Election/VotePlaceResult.php
  src/Entity/EntityNullablePostAddressTrait.php
  src/Entity/NullablePostAddress.php
  src/Entity/VotePlace.php
  src/Exporter/CityAssessorExporter.php
  src/Form/AssessorRequestType.php
  src/Mailer/Message/Assessor/AssessorRequestAssociateMessage.php
  src/Procuration/Filter/ProcurationProxyProposalFilters.php
  src/Repository/AssessorLocationTrait.php
  src/Repository/AssessorRequestRepository.php
  src/Repository/Election/VotePlaceRepository.php
  src/Repository/ProcurationProxyRepository.php
  src/Repository/VotePlaceRepository.php
  src/Security/Voter/ManageAssessorVoter.php
  src/VotePlace/VotePlaceManager.php
  templates/assessor_manager/_assessor_profile.html.twig
  templates/assessor_manager/_cities_list.html.twig
  templates/assessor_manager/_vote_place_profile.html.twig
  templates/assessor_manager/_vote_places_list.html.twig
  templates/assessor_manager/request.html.twig
  templates/assessor_manager/requests.html.twig
  templates/assessor_manager/vote_places.twig
  tests/Controller/Assessor/AssessorControllerTest.php
  tests/Controller/EnMarche/AssessorManagerControllerTest.php
  tests/Entity/AssessorRequestTest.php
Labels: Ready for code review

#7332 [LPN-865] create adherent message kpi endpoint
  config/packages/doctrine.yaml
  src/Controller/Api/AdherentMessage/GetAdherentMessageKpiController.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Repository/MailchimpCampaignReportRepository.php
Labels: Ready for code review

#7336 [Adherent] Bind Foreign district zone by country code
  src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
  src/Deputy/Subscriber/BindAdherentZoneSubscriber.php
  src/Repository/DistrictRepository.php
  src/Repository/Geo/ZoneRepository.php
  tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
  tests/Deputy/Subscriber/BindAdherentZoneSubscriberTest.php
Labels: Ready for code review

#7340 [Procuration] show disable reason of proxy
  src/Controller/EnMarche/ProcurationManagerController.php
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Procuration/Handler/CheckProcurationAuthorHandler.php
  src/Procuration/ProcurationDisableReasonEnum.php
  templates/procuration_manager/_proposals_list.html.twig
  templates/procuration_manager/_requests_list.html.twig
  templates/procuration_manager/proposal.html.twig
Labels: Ready for code review

#7339 [PAP] remove useless VotePlace stats fields
  migrations/Version20220608011640.php
  src/Admin/Pap/CampaignAdmin.php
  src/DataFixtures/ORM/LoadElectionVotePlaceData.php
  src/DataFixtures/ORM/LoadPapCampaignData.php
  src/DataFixtures/ORM/LoadPapVotePlaceData.php
  src/Entity/Election/VotePlace.php
  src/Entity/Pap/Campaign.php
  src/Entity/Pap/VotePlace.php
  src/Repository/Pap/AddressRepository.php
Labels: Ready for code review

#7341 [Phoning][LPN-886] add new indicator values on phoning campaigns endpoints
  features/api/phoning_campaigns.feature
  src/Entity/Phoning/Campaign.php
  src/Normalizer/Phoning/AppendCampaignStatsNormalizer.php
  src/Repository/Phoning/CampaignHistoryRepository.php
Labels: Ready for code review

#7344 [LPN-897] migrate procuration cities system
  src/DataFixtures/ORM/LoadProcurationData.php
  src/Entity/ProcurationProxy.php
  src/Entity/ProcurationRequest.php
  src/Form/DataTransformer/CityNameDataTransformer.php
  src/Form/Procuration/ProcurationProxyType.php
  src/Form/Procuration/ProcurationRequestType.php
  tests/Controller/EnMarche/ProcurationManagerControllerTest.php
  tests/Controller/Procuration/ProcurationControllerTest.php
Labels: Ready for code review

#7345 [PAP] Not return addresses for disabled campaign in app mobile
  composer.lock
  features/api/pap_campaigns.feature
  features/api/pap_vote_places.feature
  src/DataFixtures/ORM/LoadPapAddressData.php
  src/DataFixtures/ORM/LoadPapBuildingData.php
  src/Repository/Pap/CampaignRepository.php
Labels: Ready for code review

#7347 Remove old message system classes
  config/packages/old_sound_rabbit_mq.yaml
  config/services/services.xml
  config/services/system.xml
  config/services_test.yaml
  features/deputy.feature
  migrations/Version20220613112116.php
  src/Consumer/DeputyMessageDispatcherConsumer.php
  src/Consumer/ReferentMessageDispatcherConsumer.php
  src/Controller/EnMarche/DeputyController.php
  src/Deputy/DeputyMessage.php
  src/Deputy/DeputyMessageNotifier.php
  src/Entity/DeputyManagedUsersMessage.php
  src/Entity/ManagedUsersMessage.php
  src/Entity/ReferentManagedUsersMessage.php
  src/Form/DeputyMessageType.php
  src/Mailer/Message/DeputyMessage.php
  src/Mailer/Message/ReferentMessage.php
  src/Producer/DeputyMessageDispatcherProducer.php
  src/Producer/DeputyMessageDispatcherProducerInterface.php
  src/Referent/ReferentMessage.php
  src/Repository/AdherentRepository.php
  src/Repository/DeputyManagedUsersMessageRepository.php
  src/Repository/ManagedUsersMessageRepository.php
  src/Repository/ReferentManagedUsersMessageRepository.php
  templates/deputy/users_message.html.twig
  tests/Behat/Context/RabbitMqContext.php
  tests/Consumer/DeputyMessageDispatcherConsumerTest.php
  tests/Controller/EnMarche/DeputyControllerTest.php
  tests/Controller/EnMarche/ReferentControllerTest.php
  tests/Test/Producer/DeputyMessageNullProducer.php
  translations/messages.fr.yml
Labels: Ready for code review

#7349 [Survey] expose survey question id
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  features/api/surveys.feature
  src/Normalizer/CampaignRepliesDataSurveyNormalizer.php
Labels: Ready for code review

#7351 [Admin] update coordinates on Adherent update action
  src/Geocoder/Subscriber/EntityAddressGeocodingSubscriber.php
  tests/Geocoder/Subscriber/EntityAddressGeocodingSubscriberTest.php
Labels: Ready for code review

#7357 [VotingPlatform] Add new poll type
  front/style/voting-platform/_layout.scss
  migrations/Version20220616165915.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Voter.php
  src/Repository/AdherentRepository.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/voting_platform/_layout_poll.html.twig
  templates/voting_platform/confirmation/_confirmation_block.html.twig
  templates/voting_platform/confirmation/candidate_box/poll_content.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  templates/voting_platform/vote_step/candidate_box/poll_content.html.twig
  translations/messages.fr.yml
Labels: Ready for code review

#7358 Add rememberMe token table
  migrations/Version20220616154158.php
Labels: Ready for code review

#7360 [PAP] improve buildingStats KPI query
  features/api/pap_campaigns.feature
  migrations/Version20220617190412.php
  src/Entity/Pap/BuildingStatistics.php
  src/Repository/Pap/BuildingStatisticsRepository.php
Labels: Ready for code review

#7363 [PHP] Update Guzzle lib
  composer.lock
Labels: dependencies, composer

#7362 [VoteStatuses] add command for sending convocation
  migrations/Version20220622122711.php
  src/Command/SendVoteStatusesConvocationCommand.php
  src/Controller/EnMarche/VoteStatusesController.php
  src/Entity/Adherent.php
  src/Mailer/Message/VoteStatusesConvocationMessage.php
  templates/components/_dropdown_user_desktop.html.twig
  templates/vote_statuses/_election_box.html.twig
Labels: Ready for code review

#7364 [VoteStatuses] update style of voting platform
  front/style/mixins/_colors.scss
  front/style/pages/_instances.scss
  front/style/voting-platform/_layout.scss
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/_layout_poll.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/vote_step/candidate_box/poll_content.html.twig
Labels: Ready for code review

#7365 [PHP] Update Symfony 4.4.42
  composer.lock
Labels: dependencies, composer

#7366 [VoteStatuses] add new Vote Open email
  src/Mailer/Message/VotingPlatformVoteStatusesIsOpenMessage.php
  src/Repository/VotingPlatform/VoterRepository.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
Labels: Ready for code review

#7368 [Copol] fix convocation address validation
  src/TerritorialCouncil/Convocation/ConvocationObject.php
Labels: Bug, Ready for code review

#7375 [CHORE] Remove mocha webpack lib
  package.json
  yarn.lock
Labels: Ready for code review

#7377 [CHORE] Upgrade webpack
  yarn.lock
Labels: Ready for code review
