Repository parti-renaissance/espace-adherent, pull requests merged in 2022-12, with the labels that each got.

#7871 [Adhesion] utm params improvement
  src/Membership/AdherentFactory.php
  src/Membership/MembershipRequestHandler.php
Labels: Ready for code review

#7874 [Admin] disable add button from ModelAutocomplete field
  src/Admin/AdherentZoneBasedRoleAdmin.php
  src/Admin/Audience/AudienceAdmin.php
  src/Admin/DonationAdmin.php
  src/Admin/Jecoute/AbstractRegionAdmin.php
  src/Admin/Jecoute/JecouteManagedAreaAdmin.php
  src/Admin/LocalElection/CandidaciesGroupAdmin.php
  src/Admin/Pap/CampaignAdmin.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Admin/Team/TeamAdmin.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Form/Admin/DonatorKinshipType.php
Labels: Ready for code review

#7884 remove din font on heading with image
  templates/renaissance/adhesion/complete_profile.html.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  templates/renaissance/donation/choose_donation_amount.html.twig
  templates/renaissance/donation/confirm_type.html.twig
  templates/renaissance/donation/fill_personal_info.html.twig
  templates/renaissance/donation/mentions.html.twig
Labels: Ready for code review

#7887 Fix don wording
  assets/components/AmountChooser.js
  front/components/DonationAmountChooser.js
  src/DataFixtures/ORM/LoadCmsBlockData.php
  templates/donation/informations.html.twig
  templates/renaissance/home.html.twig
Labels: Ready for code review

#7872 [Adhesion] improve autocomplete address fields
  assets/components/Address/AddressForm.js
  assets/components/Address/GooglePlaceAutocomplete.js
  assets/listeners/address-autocomplete.js
  front/services/address/GooglePlaceAutocomplete.js
  src/Form/AddressType.php
  src/Form/AutocompleteAddressType.php
  src/Form/AutocompleteInputType.php
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/form_theme.html.twig
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#7895 [Admin] fix candidacies update process
  src/Admin/AdherentAdmin.php
  src/Admin/Article/AbstractArticleAdmin.php
  src/Admin/EventCategoryAdmin.php
  src/Admin/JeMengage/DeepLinkAdmin.php
  src/Admin/JeMengage/HeaderBlockAdmin.php
  src/Admin/Jecoute/NewsAdmin.php
  src/Admin/LocalElection/CandidaciesGroupAdmin.php
  src/Admin/OrderArticleAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/ProposalAdmin.php
  src/Entity/LocalElection/CandidaciesGroup.php
  src/Entity/LocalElection/Candidacy.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#7896 [Deprecation] Fix validator constraint getTargets signature
  src/Validator/Address.php
  src/Validator/AddressInManagedZones.php
  src/Validator/AdherentForCommitteeMandateReplacement.php
  src/Validator/ApprovedCommitteeAddress.php
  src/Validator/Assessor/AssessorDepartment.php
  src/Validator/ChezVous/MeasurePayload.php
  src/Validator/Coalition/CauseFollowerEmail.php
  src/Validator/CommitteePartialDesignation.php
  src/Validator/CustomGender.php
  src/Validator/DataSurveyAnswerTypeChoice.php
  src/Validator/DateRange.php
  src/Validator/EventCategory.php
  src/Validator/EventRegistration.php
  src/Validator/FrenchAddressOrNationalityDonation.php
  src/Validator/GeocodableAddress.php
  src/Validator/Jecoute/NewsTarget.php
  src/Validator/Jecoute/NewsText.php
  src/Validator/Jecoute/ReferentNews.php
  src/Validator/Jecoute/SurveyScopeTarget.php
  src/Validator/JemarcheDataSurveyConstraint.php
  src/Validator/ManagedZone.php
  src/Validator/MaxFiscalYearDonation.php
  src/Validator/MaxMonthDonation.php
  src/Validator/MergeableCommittees.php
  src/Validator/PapCampaignStarted.php
  src/Validator/PapCampaignVotePlaces.php
  src/Validator/Recaptcha.php
  src/Validator/RiposteOpenGraph.php
  src/Validator/Scope/ScopeVisibility.php
  src/Validator/SurveyQuestionTypeChoice.php
  src/Validator/TerritorialCouncil/TerritorialCouncilDesignation.php
  src/Validator/TerritorialCouncil/UniqueTerritorialCouncilMember.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyForCopolInvitation.php
  src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitation.php
  src/Validator/UniqueCommittee.php
  src/Validator/UniqueDonationSubscription.php
  src/Validator/UniqueExecutiveOfficeMemberRole.php
  src/Validator/UniqueMembership.php
  src/Validator/UniqueRenaissanceNewsletter.php
  src/Validator/UniqueVotePlaceAssessor.php
  src/Validator/ValidAdherentCoReferent.php
  src/Validator/ValidAuthorRoleMessageType.php
  src/Validator/ValidMessageCoalitionsFilter.php
  src/Validator/ValidMessageFilterSegment.php
  src/Validator/WasNotInvitedRecently.php
  src/Validator/ZoneBasedRoles.php
  src/Validator/ZoneType.php
Labels: Ready for code review

#7897 update article post ui
  package.json
  tailwind.config.site.js
  templates/article/partial/article-item.html.twig
  templates/article/renaissance_article.html.twig
  templates/renaissance/partials/site-header.html.twig
  yarn.lock
Labels: Ready for code review

#7898 [Admin] fix JME impersonnification
  src/Controller/OAuth/OAuthServerController.php
  src/Security/Voter/DataCornerVoter.php
  tests/Security/Voter/DataCornerVoterTest.php
Labels: Bug, Ready for code review

#7894 Remove unused print Event member page
  Dockerfile
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_snappy.yaml
  docker/dev/Dockerfile
  front/pages/manage_participants.js
  public/css/print.css
  src/Controller/Admin/AdminMyEuropeController.php
  src/Controller/Admin/AdminTonMacronController.php
  src/Controller/EnMarche/CommitteeEventManagerController.php
  src/Controller/PrintControllerTrait.php
  src/Controller/UploadDocumentController.php
  symfony.lock
  templates/admin/interactive/choice_list.html.twig
  templates/base_print.html.twig
  templates/events/members.html.twig
  templates/events/print_members.html.twig
  tests/Controller/EnMarche/EventManagerControllerTest.php
Labels: Ready for code review

#7899 [Profile] fix address block
  templates/renaissance/adherent/_layout.html.twig
  templates/renaissance/adherent/profile/form.html.twig
Labels: Bug, Ready for code review

#7860 Use different credentials for membership donations
  .env
  .env.dev
  .env.test
  config/services.yaml
  src/Donation/PayboxFormFactory.php
Labels: Ready for code review

#7903 [Admin] fix administrator edition form
  src/Admin/AdministratorAdmin.php
Labels: Bug, Ready for code review

#7900 update sas design page
  assets/style/main.scss
  assets/style/pages/voting-platform/_layout.scss
  templates/renaissance/local_election/_election_box.html.twig
  templates/renaissance/local_election/_nav.html.twig
  templates/renaissance/local_election/lists.html.twig
  templates/voting_platform/confirmation/candidate_box/local_election_content.html.twig
  templates/voting_platform/vote_step/candidate_box/local_election_content.html.twig
Labels: Ready for code review

#7917 update formations ui design
  templates/icons/academic.svg.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/formation/list.html.twig
Labels: Ready for code review

#7902 [RE] Adherent formations
  config/packages/security.yaml
  config/services/admin.xml
  migrations/Version20221207092223.php
  src/Admin/FormationAdmin.php
  src/Controller/Renaissance/Formation/DownloadController.php
  src/Controller/Renaissance/Formation/ListController.php
  src/DataFixtures/ORM/LoadAdherentFormationData.php
  src/DataFixtures/adherent_formations/formation.pdf
  src/Entity/AdherentFormation/File.php
  src/Entity/AdherentFormation/Formation.php
  src/Form/Admin/BaseFileType.php
  src/Repository/AdherentFormation/FormationRepository.php
  src/Security/Voter/RenaissanceAdherentVoter.php
  templates/icons/academic.svg.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/formation/list.html.twig
  tests/Controller/Renaissance/Formation/ListControllerTest.php
Labels: Ready for code review

#7920 [Admin] improve zone autocomplete template
  templates/admin/adherent/partial/zone_based_role_autocomplete.html.twig
Labels: Ready for code review

#7922 [LPN-1326] add local election voting platform emails templates
  src/Mailer/Message/Renaissance/VotingPlatform/AbstractRenaissanceVotingPlatformMessages.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteConfirmationMessage.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteIsOpenMessage.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteIsOverMessage.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
Labels: Ready for code review

#7919 [LocalElection] Replace dropdown list with modale
  templates/renaissance/local_election/lists.html.twig
Labels: Ready for code review

#7924 Update file validation
  src/Entity/Formation/File.php
Labels: Ready for code review

#7932 remove end date in the vote confirmation message
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteConfirmationMessage.php
Labels: Ready for code review

#7905 [LPN-1287] update article preview
  .env
  config/packages/twig.yaml
  config/services.yaml
  src/Controller/EnMarche/ArticleController.php
  src/Repository/ArticleRepository.php
  templates/admin/article/list_preview.html.twig
  templates/article/article.html.twig
  templates/article/renaissance_article.html.twig
Labels: Ready for code review

#7940 [Admin] add new election type - local poll
  config/packages/sonata_admin.yaml
  config/services/admin.xml
  features/admin/adherent.feature
  migrations/Version20221209122913.php
  src/Admin/AbstractAdmin.php
  src/Admin/VotingPlatform/Designation/DesignationPollAdmin.php
  src/Admin/VotingPlatform/Designation/PollQuestionAdmin.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Designation/Poll/Poll.php
  src/Entity/VotingPlatform/Designation/Poll/PollQuestion.php
  src/Entity/VotingPlatform/Designation/Poll/QuestionChoice.php
  src/Form/Admin/VotingPlatform/Poll/QuestionChoiceType.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  templates/admin/designation/list_zone.html.twig
  templates/admin/instances/election_list_details_column.html.twig
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#7944 Add RI on local election voting platform sas
  src/Controller/Renaissance/LocalElection/RulesController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  templates/renaissance/local_election/_layout.html.twig
  templates/renaissance/local_election/_nav.html.twig
  templates/renaissance/local_election/rules.html.twig
Labels: Ready for code review

#7952 change paybox redirection loader message
  templates/donation/paybox.html.twig
  templates/renaissance/adhesion/payment.html.twig
  templates/renaissance/donation/payment.html.twig
Labels: Ready for code review

#7950 Update vote responsive mobile
  assets/style/main.scss
  templates/renaissance/local_election/lists.html.twig
  templates/voting_platform/_layout_base.html.twig
  templates/voting_platform/finish.html.twig
  templates/voting_platform/vote_step/candidate_box/local_election_content.html.twig
Labels: Ready for code review

#7959 Try matching only when datas are available
  src/Donation/DonatorSubscriber.php
Labels: Ready for code review

#7960 Local poll election improvements
  assets/style/main.scss
  migrations/Version20221122094902.php
  migrations/Version20221209162545.php
  migrations/Version20221213112859.php
  src/Admin/CmsBlockAdmin.php
  src/Admin/CommitmentAdmin.php
  src/Admin/JeMengage/HeaderBlockAdmin.php
  src/Admin/Pap/CampaignAdmin.php
  src/Admin/Phoning/CampaignAdmin.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Controller/Renaissance/LocalElection/LocalPollElectionController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadDesignationPollData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Form/Admin/SimpleMDEContent.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/Security/Voter/VotingPlatform/AbleToVoteVoter.php
  src/Twig/VotingPlatformExtension.php
  src/Twig/VotingPlatformRuntime.php
  templates/admin/layout.html.twig
  templates/form_theme_admin.html.twig
  templates/icons/user.svg.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/local_election/_election_box.html.twig
  templates/voting_platform/_layout_local_poll.html.twig
  templates/voting_platform/index.html.twig
  templates/voting_platform/vote_step/_candidate_box.html.twig
  templates/voting_platform/vote_step/candidate_box/local_election_content.html.twig
Labels: Ready for code review

#7962 [VotingPlatform] send open-vote mail when it is really vote time
  migrations/Version20221214111850.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/VotingPlatform/Election.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteConfirmationMessage.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteIsOpenMessage.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformLocalElectionVoteIsOverMessage.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  templates/voting_platform/finish.html.twig
Labels: Ready for code review

#7964 [VotingPlatform] fix send open-vote email
  src/Command/VotingPlatform/ConfigureCommand.php
Labels: Bug, Ready for code review

#7963 Allow empty addresses from foreign places
  assets/components/Address/AddressForm.js
  src/Address/Address.php
  src/Form/AutocompleteAddressType.php
  tests/Test/Geocoder/DummyGeocoder.php
Labels: Ready for code review

#7972 [Admin] fix designation vote blank switcher
  src/Admin/VotingPlatform/DesignationAdmin.php
Labels: Bug, Ready for code review

#7974 [LocalPoll] fix selection by adherent zones
  src/Repository/VotingPlatform/DesignationRepository.php
Labels: Bug, Ready for code review

#7973 Disable adherents formation only in production
  config/services.yaml
  src/Controller/Renaissance/Formation/AdherentFormationControllerTrait.php
  src/Controller/Renaissance/Formation/DownloadController.php
  src/Controller/Renaissance/Formation/ListController.php
  templates/renaissance/adherent/_menu.html.twig
Labels: Ready for code review

#7980 Remove SendInBlue integration
  .env
  .env.test
  composer.json
  composer.lock
  config/packages/messenger.yaml
  config/packages/test/messenger.yaml
  config/services.yaml
  config/services_dev.yaml
  config/services_test.yaml
  src/Api/Listener/PostContactEditListener.php
  src/Command/SendInBlueSyncAllAdherentsCommand.php
  src/Command/SendInBlueSyncAllContactsCommand.php
  src/Contact/ContactHandler.php
  src/Membership/Contact/ContactSynchronisationCommand.php
  src/Membership/Contact/ContactSynchronisationCommandHandler.php
  src/SendInBlue/AdherentManager.php
  src/SendInBlue/Client.php
  src/SendInBlue/ClientInterface.php
  src/SendInBlue/Command/AdherentDeleteCommand.php
  src/SendInBlue/Command/AdherentSynchronisationCommand.php
  src/SendInBlue/ContactManager.php
  src/SendInBlue/EventListener/AdherentEventSubscriber.php
  src/SendInBlue/Handler/AdherentDeleteCommandHandler.php
  src/SendInBlue/Handler/AdherentSynchronisationCommandHandler.php
  src/SendInBlue/SynchronizeMessageInterface.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/MembershipControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  tests/Controller/Renaissance/AdherentControllerTest.php
  tests/Controller/Renaissance/UnregistrationControllerTest.php
  tests/Test/SendInBlue/DummyClient.php
Labels: Ready for code review

#7981 Use GKE gcloud auth plugin
  .github/workflows/ci-cd.yml
Labels: Ready for code review

#7971 Election candidacies
  src/Controller/Renaissance/LocalElection/Summary/CandidaciesController.php
  src/Controller/Renaissance/LocalElection/Summary/ListController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadLocalElectionData.php
  src/LocalElection/LocalElectionCollection.php
  src/Repository/LocalElection/LocalElectionRepository.php
  templates/icons/calendar.svg.twig
  templates/icons/left-arrow.svg.twig
  templates/icons/right-arrow.svg.twig
  templates/renaissance/local_election/summary/candidacies.html.twig
  templates/renaissance/local_election/summary/list.html.twig
Labels: Work in progress

#7990 [VotingPlatform] new result calculator for partyList proportional mode
  assets/style/main.scss
  assets/style/pages/voting-platform/_layout.scss
  assets/style/pages/voting-platform/_results.scss
  config/services.yaml
  migrations/Version20221215150113.php
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/ElectionResult/ElectionPoolResult.php
  src/Entity/VotingPlatform/ElectionResult/ElectionRoundResult.php
  src/VotingPlatform/Election/PartyListProportional/Model/Election.php
  src/VotingPlatform/Election/PartyListProportional/Model/PartyList.php
  src/VotingPlatform/Election/PartyListProportional/Processor.php
  src/VotingPlatform/Election/ResultCalculator.php
  src/VotingPlatform/Election/ResultCalculator/AbstractResultCalculator.php
  src/VotingPlatform/Election/ResultCalculator/MajoritarianCalculator.php
  src/VotingPlatform/Election/ResultCalculator/MajorityJudgmentCalculator.php
  src/VotingPlatform/Election/ResultCalculator/PartyListProportionalCalculator.php
  src/VotingPlatform/Election/ResultCalculator/ResultCalculatorInterface.php
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_candidates_list.html.twig
  templates/voting_platform/results/_local_election_candidate_box.html.twig
  tests/VotingPlatform/Election/PartyListProportional/ProcessorTest.php
Labels: Ready for code review

#7992 Rework address form
  .eslintrc.js
  assets/components/Address/AddressForm.js
  assets/components/Address/GooglePlaceAutocomplete.js
  assets/listeners/address-autocomplete.js
  assets/services/utils/countdownClock.js
  assets/utils/dom.js
  features/registration.feature
  front/pages/profile_update.js
  front/services/address/AddressForm.js
  front/services/utils/countdownClock.js
  front/services/utils/imageCropper.js
  front/utils/dom.js
  src/Address/Address.php
  src/Form/AddressType.php
  src/Form/AutocompleteAddressType.php
  src/Form/AutocompleteInputType.php
  src/Validator/FrenchAddress.php
  src/Validator/FrenchAddressValidator.php
  src/Validator/FrenchZipCode.php
  src/Validator/FrenchZipCodeValidator.php
  templates/icons/info.svg.twig
  templates/renaissance/adhesion/fill_personal_info.html.twig
  templates/renaissance/form_theme.html.twig
  tests/Admin/AdherentAdminTest.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/Renaissance/AdherentControllerTest.php
  tests/Validator/FrenchZipCodeValidatorTest.php
Labels: Ready for code review

#8008 [OAuth] save lastLoggedAt only on new token
  src/OAuth/Store/AccessTokenStore.php
Labels: Bug, Ready for code review

#8011 [Adhesion] fix when autocomplete place is empty
  assets/components/Address/GooglePlaceAutocomplete.js
Labels: Ready for code review

#8013 [Admin] use Number form type for adherent lat & lng fields
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#8015 [Sentry] deny error from Axept lib
  assets/bootstrap.js
  front/kernel.js
Labels: Ready for code review

#7994 [LPN-1334] add department sites API endpoints
  features/api/department_sites.feature
  features/api/my_teams.feature
  features/api/scopes.feature
  migrations/Version20221222094329.php
  src/Api/Filter/DepartmentSiteScopeFilter.php
  src/DataFixtures/ORM/LoadDepartmentSiteData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/DataFixtures/unlayer/content.md
  src/DataFixtures/unlayer/json_content.json
  src/DepartmentSite/DepartmentSiteSlugHandler.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/Article.php
  src/Entity/DepartmentSite/DepartmentSite.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/UnlayerJsonContentTrait.php
  src/Repository/DepartmentSite/DepartmentSiteRepository.php
  src/Scope/FeatureEnum.php
  src/Validator/AbstractZonesInScopeZonesValidator.php
  src/Validator/AddressInScopeZonesValidator.php
  src/Validator/ZoneInScopeZones.php
  src/Validator/ZoneInScopeZonesValidator.php
  tests/Controller/Api/AdherentMessage/AdherentMessageControllerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#8014 [LPN-1334-BO] add department site in the BO and the view page
  .env
  config/services.yaml
  config/services/admin.xml
  src/Admin/DepartmentSite/DepartmentSiteAdmin.php
  src/Controller/Renaissance/DepartmentSite/DepartmentSiteController.php
  src/DepartmentSite/DepartmentSiteSlugHandler.php
  src/Entity/DepartmentSite/DepartmentSite.php
  src/Form/Admin/UnlayerContentType.php
  templates/admin/department_site/list_preview.html.twig
  templates/form_theme_admin.html.twig
  templates/renaissance/department_site/department_site.html.twig
Labels: Ready for code review
