Repository parti-renaissance/espace-adherent, pull requests merged in 2022-07, with the labels that each got.

#7386 Upgrade webpack to v5
  .github/workflows/ci-cd.yml
  Makefile
  config/packages/framework.yaml
  config/services/twig.yaml
  front/app.js
  front/kernel.js
  package.json
  src/Twig/AssetRuntime.php
  webpack.common.js
  webpack.development.js
  webpack.production.js
  yarn.lock
Labels: Work in progress

#7391 [Config] remove assets version stuff
  .gitignore
  config/packages/assets_version.yaml
  config/services/twig.yaml
  src/Twig/AssetRuntime.php
  webpack.production.js
Labels: Ready for code review

#7392 [VoteStatuses] Add voteOver email
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Mailer/Message/VotingPlatformVoteStatusesIsOverMessage.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
Labels: Ready for code review

#7394 [VoteStatuses] Add Vote confirmation email
  src/Mailer/Message/VotingPlatformVoteStatusesVoteConfirmationMessage.php
  src/VotingPlatform/Election/Listener/FinishVoteCommandListener.php
Labels: Ready for code review

#7407 Update css-loader lib
  package.json
  webpack.common.js
  webpack.development.js
  webpack.production.js
  yarn.lock
Labels: dependencies, front-end, npm

#7406 Replace GA by ABLA
  templates/base.html.twig
Labels: Ready for code review

#7410 [PHP] Update google libs
  .env.test
  composer.lock
Labels: Ready for code review, dependencies, composer

#7422 Add TailwindCSS framework
  .env
  Makefile
  assets/bootstrap.js
  assets/components/Home/Commitment.js
  assets/components/Home/CommitmentSlideOver.js
  assets/components/SlideOver.js
  assets/main.js
  assets/pages/home_page.js
  assets/style/main.scss
  assets/utils/dom.js
  assets/utils/sharer.js
  config/packages/twig.yaml
  config/routes.yaml
  config/services.yaml
  front/app.js
  front/kernel.js
  package.json
  postcss.config.js
  src/Controller/Renaissance/AdhesionController.php
  src/Controller/Renaissance/HomeController.php
  tailwind.config.js
  templates/admin/layout.html.twig
  templates/base.html.twig
  templates/base_ren.html.twig
  templates/jemengage/base.html.twig
  templates/oauth/base.html.twig
  templates/renaissance/adhesion/_layout.html.twig
  templates/renaissance/adhesion/index.html.twig
  templates/renaissance/adhesion/information.html.twig
  templates/renaissance/home.html.twig
  webpack.common.js
  yarn.lock
Labels: Ready for code review

#7425 Add admin for commitment
  assets/components/Home/Commitment.js
  assets/components/Home/CommitmentSlideOver.js
  assets/components/SlideOver.js
  config/services/admin.xml
  migrations/Version20220721160526.php
  package.json
  src/Admin/CmsBlockAdmin.php
  src/Admin/CommitmentAdmin.php
  src/Admin/ExecutiveOfficeMemberAdmin.php
  src/Admin/Extension/ImageRelationUploadExtension.php
  src/Admin/Extension/SimpleImageUploadExtension.php
  src/Admin/JeMengage/HeaderBlockAdmin.php
  src/Admin/Jecoute/ResourceLinkAdmin.php
  src/Admin/ThematicCommunity/ThematicCommunityAdmin.php
  src/Controller/Renaissance/HomeController.php
  src/DataFixtures/ORM/LoadCommitmentData.php
  src/Entity/Commitment.php
  src/Repository/CommitmentRepository.php
  templates/form_theme_admin.html.twig
  templates/renaissance/home.html.twig
  translations/messages.fr.yml
  yarn.lock
Labels: Ready for code review

#7427 [Committee] filter feed item linked to unpublished event
  src/Repository/CommitteeFeedItemRepository.php
Labels: Bug, Ready for code review

#7428 [LPN-914] add an endpoint for displaying jme data survey on dashboard map
  features/api/surveys.feature
  features/javascript/donation.feature
  src/Controller/Api/AdherentList/CountAdherentController.php
  src/Controller/Api/Jecoute/JemarcheDataSurveyKpiController.php
  src/DataFixtures/ORM/LoadJemarcheDataSurveyData.php
  src/Entity/Jecoute/JemarcheDataSurvey.php
  src/Repository/Jecoute/JemarcheDataSurveyRepository.php
  tests/Controller/EnMarche/DonationControllerTest.php
Labels: Ready for code review
