Repository parti-renaissance/espace-adherent, pull requests merged in 2023-03, with the labels that each got.

#8236 [PHP] Update Symfony 5.4.21
  composer.lock
Labels: dependencies

#8249 [Committee] get all used zones in managed zones
  features/api/committees.feature
  src/Controller/Api/Committee/CommitteesController.php
  src/Controller/Api/Committee/GetCommitteesZonesController.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Geo/Http/ZoneAutocompleteFilter.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#8253 [Admin] Donation destination is not required
  src/Admin/DonationAdmin.php
  templates/admin/donation/_macros.html.twig
Labels: Ready for code review

#8251 [Contribution] Start subscription at 1st or 15th day of month
  src/Controller/Renaissance/Formation/ContentController.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/GoCardless/Client.php
Labels: Ready for code review

#8250 [PHP] Update Twig v3
  composer.json
  composer.lock
  src/Interactive/MyEuropeMessageBodyBuilder.php
  src/TonMacron/TonMacronMessageBodyBuilder.php
  src/Twig/InstanceOfExtension.php
  src/Twig/ReferentPersonLinkExtension.php
  templates/admin/certification_request/_macros.html.twig
  templates/admin/donation/_macros.html.twig
  templates/admin/election/city_card/_form_theme_admin.html.twig
  templates/admin/interactive/choice_list.html.twig
  templates/admin/report/_status.html.twig
  templates/application_request/_form_theme.html.twig
  templates/application_request/space/_application_request_row.js.twig
  templates/base.html.twig
  templates/committee/all_committees.html.twig
  templates/committee/candidacy/candidacy_list.html.twig
  templates/committee_designation/votes_list.html.twig
  templates/elected_representative/show.html.twig
  templates/events/all_events.html.twig
  templates/form_theme.html.twig
  templates/interactive/mail.html.twig
  templates/jecoute/news/news_list.html.twig
  templates/jecoute/stats.html.twig
  templates/jecoute/surveys_list.html.twig
  templates/program/index.html.twig
  templates/referent/_form_theme.html.twig
  templates/search/_filters_radius.html.twig
  templates/search/results.html.twig
  templates/territorial_council/candidacy_list.html.twig
  templates/territorial_council_designation/election_results/votes_list.html.twig
  templates/ton_macron/mail.html.twig
  templates/voting_platform/_designation_banner.html.twig
  templates/voting_platform/results/_bulletins_list.html.twig
  templates/voting_platform/results/_poll_bulletins_list.html.twig
  tests/Fixtures/views/interactive/mail.html.twig
  tests/Interactive/MyEuropeMessageBodyBuilderTest.php
  tests/TonMacron/TonMacronMessageBodyBuilderTest.php
Labels: Ready for code review

#8255 [Admin] Fix mandate geo zone autocomplete
  src/Admin/ElectedRepresentative/MandateAdmin.php
  src/Form/ElectedRepresentative/ZoneType.php
  src/Form/Geo/ZoneType.php
Labels: Ready for code review

#8256 [API] add endpoint for count adherent in zones
  features/api/adherents.feature
  features/api/statistics.feature
  src/Controller/Api/AdherentList/CountAdherentController.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#8258 [Committee] disable CityCommunity zone with tag cc_multi_dpt
  src/Entity/Geo/ZoneTagEnum.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#8268 [Contribution] Enable in prod
  src/Controller/Renaissance/ElectedRepresentative/Contribution/AbstractContributionController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/FillInformationsController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/FillRevenueController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/SeeAmountController.php
  templates/renaissance/adherent/_menu.html.twig
Labels: Ready for code review

#8270 [LPN-1486]update zone filter for FDE PAD messages
  features/api/adherent_messages.feature
  src/JMEFilter/FilterBuilder/ZoneAutocompleteFilterBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentGeoZoneConditionBuilder.php
Labels: Ready for code review

#8272 [MyTeam] revoke access token on member change
  src/MyTeam/Api/Listener/PostWriteMyTeamMemberListener.php
  src/MyTeam/DelegatedAccessManager.php
Labels: Ready for code review

#8257 [LPN-1478] add committee election candidacies group
  features/api/committees.feature
  migrations/Version20230301155217.php
  src/DataFixtures/ORM/LoadCommitteeV2CandidaciesGroupData.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Entity/CommitteeCandidaciesGroup.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/CommitteeElection.php
  src/Entity/CommitteeMembership.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/VotingPlatform/Designation/BaseCandidacy.php
  src/Repository/CommitteeElectionRepository.php
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
Labels: Ready for code review

#8273 [Mailchimp] improve zone synchro by using sub zones
  migrations/Version20230307142934.php
  src/Entity/Geo/Zone.php
  src/Entity/Geo/ZoneTagEnum.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  tests/Test/Geocoder/DummyGeocoder.php
Labels: Ready for code review

#8276 [Committee] initialize CommitteeElection on designation creation
  features/sitemap.feature
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Command/VotingPlatform/InitializeElectionsCommand.php
  src/Committee/Api/Listener/InitializeCommitteeElectionListener.php
  src/Committee/EventListener/UpdateVotingCommitteeOnCandidateListener.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Mailer/Message/VotingPlatformPartialElectionIsOpenMessage.php
  src/Repository/CommitteeRepository.php
  src/VotingPlatform/AdherentMandate/Factory/CommitteeAdherentMandateFactory.php
  src/VotingPlatform/Election/RedirectManager.php
  src/VotingPlatform/Handler/NotifyPartialElectionVoterCommandHandler.php
  src/VotingPlatform/Listener/SendCandidacyInvitationEmailListener.php
  templates/admin/designation/list_zone.html.twig
  templates/admin/instances/election_list_details_column.html.twig
  templates/admin/instances/election_list_entity_column.html.twig
  templates/admin/instances/election_list_pools_column.html.twig
  templates/admin/instances/vote_list_action_column.html.twig
  templates/admin/instances/vote_list_designation_column.html.twig
  templates/admin/instances/vote_list_entity_column.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/SearchControllerTest.php
  tests/Repository/CommitteeRepositoryTest.php
Labels: Ready for code review

#8274 [LPN-1498] fix creation date 15 days before the vote start date
  features/api/designations.feature
  src/Api/Serializer/DesignationGroupsContextBuilder.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Normalizer/DesignationDenormalizer.php
Labels: Ready for code review

#8279 update committee election payload
  features/api/committees.feature
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
Labels: Ready for code review

#8278 Check author in AuthorVoter
  src/Security/Voter/AuthorVoter.php
Labels: Ready for code review

#8280 [Mailchimp] remove duplicated sub zone
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Bug, Ready for code review

#8281 [Mailchimp] use zone type to deduplicate zones
  src/Mailchimp/Synchronisation/RequestBuilder.php
Labels: Bug

#8283 [Admin] Add custom role for JME documents
  config/packages/security.yaml
  config/services/admin.xml
  src/Admin/AdministratorAdmin.php
  src/DataFixtures/ORM/LoadAdminData.php
Labels: Ready for code review

#8284 [Admin] Handle document file before flush
  src/Admin/DocumentAdmin.php
Labels: Ready for code review

#8287 [Admin] Handle formation file on prePersist
  src/Admin/FormationAdmin.php
Labels: Ready for code review

#8286 [Mailchimp] use contains operator for zone condition
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentGeoZoneConditionBuilder.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#8271 [LPN-1480] add candidacy to a group
  features/api/adherents.feature
  features/api/committees.feature
  features/api/statistics.feature
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCommitteeV2CandidaciesGroupData.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/Adherent.php
  src/Entity/CommitteeCandidaciesGroup.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/CommitteeMembership.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Normalizer/CommitteeCandidacyDenormalizer.php
  src/Repository/CommitteeCandidaciesGroupRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Validator/CommitteeMembershipZoneInScopeZones.php
  src/Validator/CommitteeMembershipZoneInScopeZonesValidator.php
  tests/Controller/EnMarche/MapControllerTest.php
Labels: Ready for code review

#8290 [MyCommittee] add getter for committee version
  src/Entity/Committee.php
Labels: Bug, Ready for code review

#8291 Remove duplicate wording
  templates/renaissance/elected_representative/contribution/confirmation.html.twig
Labels: Ready for code review

#8292 [MyCommittee] improve list of committees
  templates/icons/info-stroke.svg.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/adherent/my_committee/show_committees_list.html.twig
  templates/renaissance/adherent/my_committee/show_my_current_committee.html.twig
Labels: Ready for code review

#8306 [LPN-1381] add new menu for adherent creation
  config/packages/security.yaml
  src/Admin/AdherentAdmin.php
  src/Admin/AdministratorAdmin.php
  src/Controller/Admin/AdminAdherentCRUDController.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/Entity/Adherent.php
  src/EventListener/AdminMenuListener.php
  src/Form/Admin/Adherent/CreateRenaissanceType.php
  src/Form/Admin/Adherent/VerifyEmailType.php
  src/Membership/MembershipNotifier.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  src/Renaissance/Membership/Notifier.php
  templates/admin/adherent/renaissance/create.html.twig
  templates/admin/adherent/renaissance/create_button.html.twig
  templates/admin/adherent/renaissance/verify_email.html.twig
  tests/Admin/AdherentAdminTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8304 [Committee] update my-committee with new post address
  src/Adherent/Listener/AssignCommitteeByAdherentAddressListener.php
  src/Committee/CommitteeManager.php
  src/Committee/CommitteeMembershipManager.php
  src/Committee/CommitteeMembershipTriggerEnum.php
  src/Controller/Renaissance/MyCommittee/SaveCommitteeUpdateController.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/Adherent.php
  src/Entity/CommitteeMembership.php
  src/Entity/Geo/Zone.php
  src/Geo/ZoneMatcher.php
  src/Repository/CommitteeRepository.php
  tests/Repository/CommitteeRepositoryTest.php
Labels: Ready for code review

#8307 [Committee] update my-committee on adhesion
  src/Adherent/Listener/AssignCommitteeByAdherentAddressListener.php
Labels: Ready for code review

#8311 [LPN-1517] add committee filter on adherents autocomplete
  src/Adherent/AdherentAutocompleteFilter.php
  src/Controller/Api/AdherentAutocompleteController.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#8313 fix adherent committee update
  src/Controller/Renaissance/MyCommittee/SaveCommitteeUpdateController.php
  src/Controller/Renaissance/MyCommittee/ShowCommitteeListController.php
Labels: Ready for code review

#8314 add nationality field on adherent admin
  src/Admin/AdherentAdmin.php
Labels: Ready for code review

#8315 [Committee] update my-committee membership on each committee edition
  src/Committee/Api/Listener/RefreshCommitteeMembershipsListener.php
  src/Committee/Command/RefreshCommitteeMembershipsInZoneCommand.php
  src/Committee/CommandHandler/CommitteeCreationCommandHandler.php
  src/Committee/CommandHandler/CommitteeMergeCommandHandler.php
  src/Committee/CommandHandler/CommitteeUpdateCommandHandler.php
  src/Committee/CommandHandler/RefreshCommitteeMembershipsInZoneCommandHandler.php
  src/Committee/CommitteeAdherentMandateManager.php
  src/Committee/CommitteeFactory.php
  src/Committee/CommitteeMembershipManager.php
  src/Committee/CommitteeMembershipTriggerEnum.php
  src/Committee/DTO/CommitteeAdherentMandateCommand.php
  src/Committee/DTO/CommitteeCommand.php
  src/Committee/DTO/CommitteeCreationCommand.php
  src/Committee/DTO/CommitteeMergeCommand.php
  src/Controller/Admin/AdminCommitteeCRUDController.php
  src/Controller/Admin/AdminCommitteeController.php
  src/Controller/Admin/AdminCommitteeMergeHistoryController.php
  src/Controller/EnMarche/AdherentController.php
  src/Controller/EnMarche/Committee/AbstractCommitteeController.php
  src/Controller/EnMarche/CommitteeManagerController.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/AdherentMandate/CommitteeAdherentMandate.php
  src/Form/Admin/ApproveCommitteeCommandType.php
  src/Form/Admin/CommitteeMandateCommandType.php
  src/Form/Admin/CommitteeMergeType.php
  src/Form/CommitteeCommandType.php
  src/Form/CreateCommitteeCommandType.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeRepository.php
  src/Repository/Geo/ZoneRepository.php
  src/Validator/AdherentForCommitteeMandateReplacementValidator.php
  src/Validator/ApprovedCommitteeAddressValidator.php
  src/Validator/MergeableCommitteesValidator.php
  src/Validator/UniqueCommitteeValidator.php
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Committee/CommitteeCommandTest.php
  tests/Committee/CommitteeFactoryTest.php
Labels: Ready for code review

#8316 [LPN-1538] serialize vote and voter count
  features/api/committees.feature
  src/Normalizer/CommitteeElectionNormalizer.php
Labels: Ready for code review

#8318 [API] Send committee election status
  features/api/committees.feature
  src/Entity/EntityDesignationTrait.php
Labels: Ready for code review

#8321 [Donation] Make custom amount input larger
  assets/style/main.scss
  templates/renaissance/form_theme.html.twig
Labels: Ready for code review

#8324 Update city_community label
  features/api/zones.feature
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8327 [LPN-1531] fix committee assignment on adherent address update
  features/api/committees.feature
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/Adherent.php
Labels: Ready for code review

#8319 Rework ConfigureCommand for committee supervisor elections
  src/Command/VotingPlatform/ConfigureCommand.php
Labels: Ready for code review

#8328 update voters query
  src/Entity/Committee.php
  src/Repository/CommitteeMembershipRepository.php
Labels: Ready for code review

#8322 Add last contribution to elected representative payload
  features/api/elected_representatives.feature
  migrations/Version20230316170530.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/FillRevenueController.php
  src/DataFixtures/ORM/LoadElectedRepresentativeContributionData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/ElectedRepresentative/Contribution/ContributionRequestHandler.php
  src/Entity/ElectedRepresentative/Contribution.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  tests/Controller/Renaissance/ElectedRepresentative/Contribution/ContributionControllerTest.php
Labels: Ready for code review

#8353 update zone autocomplete filter label param type
  features/api/adherent_messages.feature
  features/api/adherents.feature
  features/api/elected_representatives.feature
  src/JMEFilter/FilterTypeEnum.php
  src/JMEFilter/Types/DefinedTypes/ZoneAutocomplete.php
Labels: Ready for code review

#8360 Handle RE error pages
  templates/TwigBundle/Exception/renaissance/error.html.twig
  templates/TwigBundle/Exception/renaissance/error403.html.twig
  templates/TwigBundle/Exception/renaissance/error404.html.twig
  templates/TwigBundle/Exception/renaissance/error500.html.twig
  templates/TwigBundle/Exception/renaissance/error_layout.html.twig
Labels: Ready for code review

#8365 [Elected] fix lastContribution filter
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
Labels: Bug, Ready for code review

#8366 Order committees by name, then by date
  src/Admin/AdherentAdmin.php
  src/Repository/CommitteeRepository.php
Labels: Ready for code review

#8367 [Committee] add command for updating memberships counters
  src/Command/UpdateAdherentsLastLoginGroupCommand.php
  src/Command/UpdateCommitteeMembershipsCountersCommand.php
  src/Repository/CommitteeRepository.php
Labels: Ready for code review

#8368 [LPN-1571] add committees uuid on audience filter
  migrations/Version20230322174658.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
Labels: Ready for code review

#8371 [Mailchimp] sync committee uuid as TextField instead of tag
  features/api/adherent_messages.feature
  migrations/Version20230323111246.php
  src/AdherentMessage/Listener/CreateStaticSegmentListener.php
  src/Entity/AdherentMessage/Filter/AudienceFilter.php
  src/JMEFilter/FilterBuilder/CommitteeFilterBuilder.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/JMECommitteeConditionBuilder.php
  src/Mailchimp/Synchronisation/EventListener/AdherentEventSubscriber.php
  src/Mailchimp/Synchronisation/Request/MemberRequest.php
  src/Mailchimp/Synchronisation/RequestBuilder.php
  tests/Controller/Admin/AdminCommitteeCRUDControllerTest.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Ready for code review

#8380 [LPN-1596] add committee name and uuid on adherents list payload
  features/api/adherents.feature
  migrations/Version20230324113203.php
  src/DataFixtures/ORM/LoadManagedUserData.php
  src/Entity/Projection/ManagedUser.php
  src/Entity/Projection/ManagedUserFactory.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#8379 [Election] fix division by zero on result page
  templates/voting_platform/_layout_committee_supervisor.html.twig
  templates/voting_platform/_layout_local_election.html.twig
Labels: Bug, Ready for code review

#8381 [Committee] remove email for new membership
  src/Committee/EventListener/SendEmailForNewFollowerListener.php
  src/Mailer/Message/CommitteeNewFollowerMessage.php
  tests/Controller/EnMarche/CommitteeControllerTest.php
Labels: Ready for code review

#8382 [LPN-1585] update elected representative list query
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Normalizer/ElectedMandateDenormalizer.php
  src/Normalizer/UpdateElectedMandateDenormalizer.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
Labels: Ready for code review

#8383 fix voting platform url in vote open message
  src/VotingPlatform/Notifier/ElectionNotifier.php
Labels: Ready for code review

#8393 [API] remove not_available for missing phone
  features/api/adherents.feature
  src/Entity/Projection/ManagedUser.php
  src/ManagedUsers/ColumnsConfigurator.php
  tests/Controller/Api/AdherentList/AdherentListControllerTest.php
Labels: Ready for code review

#8391 Rename Deputy label
  features/api/scopes.feature
  src/DataFixtures/ORM/LoadScopeData.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  templates/admin/adherent/statuses.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
  tests/Admin/AdherentAdminTest.php
  tests/Security/Voter/DataCornerVoterTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8396 [Admin] Add filters & column for elected representative contributions
  src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
  templates/admin/elected_representative/list_contribution.html.twig
Labels: Ready for code review

#8399 Mandate setters should be nullbale & validated by NotBlank
  src/Entity/ElectedRepresentative/Mandate.php
Labels: Ready for code review

#8405 [LPN-1602] update adherent autocomplete query
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#8406 [LPN-1598] order candidacies by created at asc
  src/DataFixtures/ORM/LoadCommitteeV2CandidacyData.php
  src/Entity/CommitteeCandidaciesGroup.php
Labels: Ready for code review

#8408 update elected representative author voter
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Security/Voter/ManageElectedRepresentativeVoter.php
Labels: Ready for code review

#8409 [VotingPlatform] cancel election without candidates
  migrations/Version20230329012543.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Entity/CommitteeCandidacy.php
  src/Entity/EntityDesignationTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Entity/VotingPlatform/Election.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/VotingPlatform/Designation/DesignationStatusEnum.php
  src/VotingPlatform/Election/ElectionStatusEnum.php
  src/VotingPlatform/Election/Enum/ElectionCancelRaisonEnum.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8410 [Committee] remove memberships when zone changes
  src/Committee/CommandHandler/RefreshCommitteeMembershipsInZoneCommandHandler.php
  src/Committee/CommitteeMembershipManager.php
  src/Entity/Committee.php
  src/Repository/AdherentRepository.php
Labels: Ready for code review

#8411 [LPN-1618] adherent readhesion process
  migrations/Version20230330173213.php
  src/Controller/Renaissance/Adhesion/PaymentController.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequestHandler.php
  src/Donation/TransactionSubscriber.php
  src/Entity/Adherent.php
  src/Entity/Donation.php
  src/Mailer/Message/Renaissance/RenaissanceReAdhesionConfirmationMessage.php
  src/Membership/MembershipNotifier.php
  src/Membership/MembershipRequestHandler.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  src/Renaissance/Membership/MembershipRequestProcessor.php
  templates/renaissance/adherent/_layout.html.twig
  templates/renaissance/adhesion/end_adhesion.html.twig
  templates/renaissance/home.html.twig
Labels: Ready for code review

#8413 Simplify ManagedUser filter
  config/services.yaml
  src/Controller/Api/AdherentList/AdherentListController.php
  src/Controller/EnMarche/ManagedUsers/AbstractManagedUsersController.php
  src/ManagedUsers/Filter/AbstractFilterFactory.php
  src/ManagedUsers/Filter/CandidateFilterFactory.php
  src/ManagedUsers/Filter/CorrespondentFilterFactory.php
  src/ManagedUsers/Filter/DeputyFilterFactory.php
  src/ManagedUsers/Filter/LegislativeCandidateFilterFactory.php
  src/ManagedUsers/Filter/ManagedUsersFilterFactoryInterface.php
  src/ManagedUsers/Filter/PresidentDepartmentalAssemblyFilterFactory.php
  src/ManagedUsers/Filter/ReferentFilterFactory.php
  src/ManagedUsers/Filter/RegionalCoordinatorFilterFactory.php
  src/ManagedUsers/Filter/SenatorFilterFactory.php
  src/ManagedUsers/ManagedUsersFilterFactory.php
  src/Subscription/SubscriptionTypeEnum.php
Labels: Ready for code review

#8412 [Committee] Add relation with adherent-supervisor of committee
  features/api/committees.feature
  migrations/Version20230330153931.php
  src/Committee/EventListener/InitializeSupervisorMandatesListener.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/Entity/Committee.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/VotingPlatform/AdherentMandate/Factory/CommitteeAdherentMandateFactory.php
  src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
  src/VotingPlatform/Listener/UpdateAdherentMandateListener.php
  tests/Controller/Renaissance/UnregistrationControllerTest.php
Labels: Ready for code review

#7697 Allow Supervisors on JME
  features/api/committees.feature
  features/api/scopes.feature
  migrations/Version20230331125853.php
  src/Committee/CommandHandler/RefreshCommitteeMembershipsInZoneCommandHandler.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Repository/AdherentRepository.php
  src/Scope/DelegatedAccess.php
  src/Scope/Generator/AbstractScopeGenerator.php
  src/Scope/Generator/AnimatorScopeGenerator.php
  src/Scope/Scope.php
  src/Scope/ScopeEnum.php
  src/Subscription/SubscriptionTypeEnum.php
Labels: Ready for code review

#8416 [RE-1641] add renaissance in political affiliation
  src/Admin/ElectedRepresentative/MandateAdmin.php
  src/Election/VoteListNuanceEnum.php
Labels: Ready for code review
