Repository parti-renaissance/espace-adherent, pull requests merged in 2023-02, with the labels that each got.

#8147 Add new scope - president departmental assembly
  features/api/adherents.feature
  features/api/scopes.feature
  src/Adherent/Authorization/ZoneBasedRoleTypeEnum.php
  src/Controller/Api/MyTeam/InitializeMyTeamController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/Adherent.php
  src/Entity/AdherentZoneBasedRole.php
  src/ManagedUsers/Filter/PresidentDepartmentalAssemblyFilterFactory.php
  src/Scope/Generator/PresidentDepartmentalAssemblyScopeGenerator.php
  src/Scope/ScopeEnum.php
  templates/admin/adherent/statuses.html.twig
  tests/Controller/EnMarche/BoardMemberControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8146 [VotingPlatform] fix seats round precision
  src/VotingPlatform/Election/ResultCalculator/PartyListProportionalCalculator.php
Labels: Ready for code review

#8160 display FDE on upcoming elections list
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/LocalElection/LocalElectionCollection.php
  src/Repository/LocalElection/LocalElectionRepository.php
  templates/renaissance/local_election/summary/candidacies.html.twig
  templates/renaissance/local_election/summary/list.html.twig
Labels: Ready for code review

#8162 [PAD] add new message type for president dpt assembly
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/PresidentDepartmentalAssemblyAdherentMessage.php
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
Labels: Ready for code review

#8163 Remove all delegated access (cascade) with removed adherent
  migrations/Version20230201185840.php
  src/Entity/AdherentCharter/AbstractAdherentCharter.php
  src/Entity/MyTeam/DelegatedAccess.php
Labels: Bug, Ready for code review

#8164 [Élections] fix elections with multiple zones display
  src/Admin/LocalElection/LocalElectionAdmin.php
  templates/admin/local_election/list_zone.html.twig
Labels: Ready for code review

#8089 Add elected representative contribution workflow
  config/packages/workflows.yaml
  config/services.yaml
  src/Adherent/AdherentRoleEnum.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/AbstractContributionController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/FillInformationsController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/FillRevenueController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/SeeAmountController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCmsBlockData.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/ElectedRepresentative/Contribution/ContributionRequest.php
  src/ElectedRepresentative/Contribution/ContributionRequestProcessor.php
  src/ElectedRepresentative/Contribution/ContributionRequestStateEnum.php
  src/ElectedRepresentative/Contribution/ContributionRequestStorage.php
  src/ElectedRepresentative/Contribution/ContributionRequestStoreListener.php
  src/Form/Renaissance/ElectedRepresentative/Contribution/InformationsType.php
  src/Form/Renaissance/ElectedRepresentative/Contribution/RevenueType.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Security/Voter/OnGoingElectedRepresentativeAdherentVoter.php
  templates/icons/check-circle.svg.twig
  templates/icons/credit-card.svg.twig
  templates/icons/money.svg.twig
  templates/renaissance/adherent/_layout.html.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/elected_representative/contribution/_layout.html.twig
  templates/renaissance/elected_representative/contribution/confirmation.html.twig
  templates/renaissance/elected_representative/contribution/fill_informations.html.twig
  templates/renaissance/elected_representative/contribution/fill_revenue.html.twig
  templates/renaissance/elected_representative/contribution/no_contribution_needed.html.twig
  templates/renaissance/elected_representative/contribution/see_amount.html.twig
  tests/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeControllerTest.php
  tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
  tests/Controller/Renaissance/ElectedRepresentative/Contribution/ContributionControllerTest.php
Labels: Ready for code review

#8135 [1378] create elected representative endpoints for JME
  features/api/my_teams.feature
  features/api/scopes.feature
  migrations/Version20230124144750.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Entity/Adherent.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Normalizer/ElectedRepresentativeDenormalizer.php
  src/Normalizer/ElectedRepresentativeMandateFromIdDenormalizer.php
  src/Normalizer/ElectedRepresentativePoliticalFunctionFromIdDenormalizer.php
  src/Normalizer/UpdateElectedRepresentativeDenormalizer.php
  src/Repository/ElectedRepresentative/PoliticalFunctionRepository.php
  src/Scope/FeatureEnum.php
  src/Security/Voter/CanManageElectedRepresentativeVoter.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8166 [ER] fix created/updated at column migration
  migrations/Version20230124144750.php
Labels: Bug, Ready for code review

#8168 Allow download static docx files
  src/Controller/AssetsController.php
Labels: Ready for code review

#8165 [LPN-1399] add elected representative collection and filter endpoints
  config/services.yaml
  src/Controller/Api/ElectedRepresentative/ElectedRepresentativeListController.php
  src/Controller/Api/ElectedRepresentative/GetFilterCollectionController.php
  src/ElectedRepresentative/Filter/ElectedRepresentativeFiltersGenerator.php
  src/ElectedRepresentative/Filter/FilterBuilder/ElectedRepresentativeBasicFieldsFilterBuilder.php
  src/ElectedRepresentative/Filter/FilterBuilder/ElectedRepresentativeFilterBuilderInterface.php
  src/ElectedRepresentative/Filter/FilterBuilder/MandatesFilterBuilder.php
  src/ElectedRepresentative/Filter/FilterBuilder/PoliticalFunctionFilterBuilder.php
  src/ElectedRepresentative/Filter/FilterBuilder/ZoneAutocompleteFilterBuilder.php
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
Labels: Ready for code review

#8167 [Committee] clean unused API routes
  features/api/committees.feature
  src/Controller/Api/AdherentController.php
  src/Controller/Api/CommitteesController.php
  src/Entity/Adherent.php
  src/Entity/Committee.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/EntityPersonNameTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Repository/CommitteeMembershipRepository.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8169 Add elected representatives api tests
  features/api/elected_representatives.feature
  src/Controller/Api/ElectedRepresentative/ElectedRepresentativeListController.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
Labels: Ready for code review

#8171 [LPN-1410] add new my team member role
  src/MyTeam/RoleEnum.php
Labels: Ready for code review

#8172 [LPN-1403] update sms subscriptions value
  features/api/adherents.feature
  src/Entity/Projection/ManagedUser.php
  src/ManagedUsers/ColumnsConfigurator.php
  tests/Controller/Api/AdherentList/AdherentListControllerTest.php
Labels: Ready for code review

#8173 fix rne filter
  src/ElectedRepresentative/Filter/FilterBuilder/MandatesFilterBuilder.php
  src/ElectedRepresentative/Filter/FilterBuilder/PoliticalFunctionFilterBuilder.php
Labels: Ready for code review

#7954 Adherent formations
  config/packages/api_platform.yaml
  config/services.yaml
  config/services/admin.xml
  features/api/adherent_formations.feature
  features/api/elected_representatives.feature
  features/api/my_teams.feature
  features/api/scopes.feature
  migrations/Version20230207174546.php
  src/Admin/FormationAdmin.php
  src/Controller/Api/FormationDownloadFileController.php
  src/Controller/Api/FormationUploadFileController.php
  src/Controller/Renaissance/ElectedRepresentative/Contribution/AbstractContributionController.php
  src/Controller/Renaissance/Formation/AdherentFormationControllerTrait.php
  src/Controller/Renaissance/Formation/ContentController.php
  src/Controller/Renaissance/Formation/DownloadController.php
  src/Controller/Renaissance/Formation/ListController.php
  src/DataFixtures/ORM/LoadAdherentFormationData.php
  src/DataFixtures/ORM/LoadAdminData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Encoder/MultipartDecoder.php
  src/Entity/AdherentFormation/File.php
  src/Entity/AdherentFormation/Formation.php
  src/Entity/AdherentFormation/FormationContentTypeEnum.php
  src/Entity/BaseFile.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/EntityScopeVisibilityTrait.php
  src/Entity/EntityTimestampableTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/PositionTrait.php
  src/EntityListener/AdherentFormationListener.php
  src/Form/Admin/BaseFileType.php
  src/Formation/FormationHandler.php
  src/Normalizer/FormationNormalizer.php
  src/Repository/AdherentFormation/FormationRepository.php
  src/Scope/FeatureEnum.php
  src/Validator/AdherentFormation/FormationContent.php
  src/Validator/AdherentFormation/FormationContentValidator.php
  templates/admin/adherent_formation/edit.html.twig
  templates/admin/list/list_administrator_blameable.html.twig
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/formation/_formation_preview.html.twig
  templates/renaissance/formation/list.html.twig
  tests/Controller/Renaissance/Formation/ListControllerTest.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#8178 fix access delegator message
  src/AdherentMessage/AdherentMessageTypeEnum.php
Labels: Ready for code review

#8180 [DptSite] add site url normalizer
  features/api/department_sites.feature
  src/Entity/DepartmentSite/DepartmentSite.php
  src/Entity/EntityIdentityTrait.php
  src/Normalizer/DepartmentalSiteUrlNormalizer.php
  templates/renaissance/department_site/department_site.html.twig
Labels: Ready for code review

#8181 add mandate endpoints
  features/api/elected_representatives.feature
  migrations/Version20230209153258.php
  src/DataFixtures/ORM/LoadElectedRepresentativeData.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Entity/ElectedRepresentative/PoliticalFunction.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Normalizer/ElectedMandateDenormalizer.php
  src/Normalizer/ElectedRepresentativeDenormalizer.php
  src/Normalizer/ElectedRepresentativeMandateFromIdDenormalizer.php
  src/Normalizer/UpdateElectedMandateDenormalizer.php
  src/Normalizer/UpdateElectedRepresentativeDenormalizer.php
  tests/Adherent/Handler/AdherentUpdateTerritorialCouncilMembershipsCommandHandlerTest.php
Labels: Ready for code review

#8182 [Assets] return 404 non-existing file
  src/Controller/AssetsController.php
Labels: Ready for code review

#8183 Add Donation destination & admin
  assets/components/Donation/DonationAmountChooser.js
  assets/components/Donation/DonationDestinationChooser.js
  assets/components/Donation/DonationWidget.js
  migrations/Version20230214143118.php
  src/Admin/DonationAdmin.php
  src/DataFixtures/ORM/LoadDonationData.php
  src/Donation/DonationFactory.php
  src/Donation/DonationRequest.php
  src/Donation/DonationRequestDestinationEnum.php
  src/Entity/Donation.php
  src/Form/Renaissance/Donation/DonationRequestAmountType.php
  src/Repository/Geo/ZoneRepository.php
  templates/admin/donation/_macros.html.twig
  templates/admin/donation/list_destination.html.twig
  templates/renaissance/donation/cheque_payment.html.twig
  tests/Donation/DonationFactoryTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8186 [API] add committee filter for zone autocomplete endpoint
  features/api/committees.feature
  src/Controller/Api/Zone/AbstractZoneAutocompleteController.php
  src/Controller/Api/Zone/ZoneAutocompleteController.php
  src/Controller/Api/Zone/ZoneAutocompleteSelect2Controller.php
  src/Geo/Http/ZoneAutocompleteFilter.php
  src/Repository/Geo/ZoneRepository.php
Labels: Ready for code review

#8189 [AdherentMessage] implement lock middleware for MC sync worker
  composer.json
  composer.lock
  config/packages/lock.yaml
  config/packages/messenger.yaml
  src/AdherentMessage/Command/AdherentMessageChangeCommand.php
  src/AdherentMessage/Command/AdherentMessageDeleteCommand.php
  src/Mailchimp/CampaignMessageInterface.php
  src/Messenger/LockMiddleware.php
  src/Messenger/Message/LockableMessageInterface.php
  symfony.lock
Labels: Bug, Ready for code review

#8191 [PHP] update Sentry bundle
  composer.json
  composer.lock
Labels: dependencies

#8192 [Test] remove useless step with setting content-type header
  features/api/adherent_messages.feature
  features/api/adherents.feature
  features/api/audience_segments.feature
  features/api/audiences.feature
  features/api/causes.feature
  features/api/coalition_events.feature
  features/api/department_sites.feature
  features/api/device.feature
  features/api/elected_representatives.feature
  features/api/email_templates.feature
  features/api/events.feature
  features/api/jecoute_news.feature
  features/api/jecoute_ripostes.feature
  features/api/legislative_newsletter_subscriptions.feature
  features/api/membership_avecvous.feature
  features/api/my_teams.feature
  features/api/pap_address.feature
  features/api/pap_campaigns.feature
  features/api/phoning_campaigns.feature
  features/api/push_token.feature
  features/api/quick_actions.feature
  features/api/surveys-replys.feature
  features/api/surveys.feature
  features/api/teams.feature
Labels: Ready for code review

#8193 [Formation] add delete endpoint
  composer.json
  composer.lock
  features/api/adherent_formations.feature
  migrations/Version20230217112001.php
  src/Entity/AdherentFormation/Formation.php
  src/Entity/PositionTrait.php
Labels: Ready for code review

#8187 [Committee] add create endpoint
  config/services/admin.xml
  features/api/committees.feature
  migrations/Version20230215084303.php
  src/Admin/AdherentAdmin.php
  src/Admin/CommitteeAdmin.php
  src/Controller/EnMarche/DonationController.php
  src/Coordinator/Filter/AbstractCoordinatorAreaFilter.php
  src/Entity/BaseGroup.php
  src/Entity/Committee.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/Geo/GeoTrait.php
  src/Entity/Geo/Zone.php
  src/Entity/NullablePostAddress.php
  src/Exception/PayboxPaymentUnsubscriptionException.php
  src/Form/CoordinatorAreaType.php
  src/Repository/AbstractGroupRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/CommitteeRepository.php
  src/Scope/ScopeGeneratorResolver.php
  src/Security/Voter/CommitteeShowVoter.php
  src/Security/Voter/ManageZoneableItemVoter.php
  templates/admin/committee/list_hosts.html.twig
  templates/committee_manager/list_members.html.twig
  tests/Committee/CommitteeAdherentMandateManagerTest.php
  tests/Security/Voter/CommitteeShowVoterTest.php
Labels: Ready for code review

#8195 [CORS] expose content-disposition header
  config/packages/nelmio_cors.yaml
Labels: Ready for code review

#8179 Add admin documents
  config/services/admin.xml
  features/api/documents.feature
  features/api/my_teams.feature
  features/api/scopes.feature
  migrations/Version20230217142406.php
  src/Admin/DocumentAdmin.php
  src/Admin/FormationAdmin.php
  src/Controller/Api/DocumentDownloadFileController.php
  src/DataFixtures/ORM/LoadDocumentData.php
  src/DataFixtures/ORM/LoadScopeData.php
  src/Documents/DocumentHandler.php
  src/Entity/Document.php
  src/Entity/EntityIdentityTrait.php
  src/Normalizer/DocumentNormalizer.php
  src/Repository/DocumentRepository.php
  src/Scope/FeatureEnum.php
  src/Scope/ScopeGeneratorResolver.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8196 add adherent membership filter on elected representative filters
  features/api/elected_representatives.feature
  src/Admin/AdherentAdmin.php
  src/ElectedRepresentative/Filter/ListFilter.php
  src/JMEFilter/FilterBuilder/RenaissanceMembershipFilterBuilder.php
  src/Repository/AdherentRepository.php
  src/Repository/CommitteeMembershipRepository.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Repository/Helper/MembershipFilterHelper.php
  src/Repository/Projection/ManagedUserRepository.php
Labels: Ready for code review

#8200 [Admin] allow to use custom zone for PaD role type
  src/Adherent/Authorization/ZoneBasedRoleTypeEnum.php
  src/Admin/AdherentZoneBasedRoleAdmin.php
  src/Entity/Geo/Zone.php
  src/Geo/ZoneMatcher.php
  src/Validator/ZoneBasedRolesValidator.php
  templates/certification_request/form.html.twig
  templates/committee/_form.html.twig
  templates/referent/territorial_council/official_report_create.html.twig
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#8199 [Message] improve committeeMember filter
  src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentInterestConditionBuilder.php
  templates/message/filter/message_filter.html.twig
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Ready for code review

#8194 [LPN-1414] add CRUD endpoints for designations
  config/services.yaml
  docker/dev/php.ini
  docker/prod/php.ini
  features/api/designations.feature
  features/api/my_teams.feature
  features/api/scopes.feature
  migrations/Version20230217143246.php
  src/Api/Serializer/DesignationGroupsContextBuilder.php
  src/Api/Validator/UpdateDesignationGroupGenerator.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/EntityIdentityTrait.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Normalizer/UuidNormalizer.php
  src/Scope/FeatureEnum.php
  src/VotingPlatform/Designation/DesignationTypeEnum.php
  tests/Scope/GeneralScopeGeneratorTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8201 [Procuration] adjust pages for new host and logo
  .env
  config/packages/nelmio_cors.yaml
  front/listeners/progressive-background.js
  src/Twig/AssetRuntime.php
  templates/procuration/_layout.html.twig
  templates/procuration/proxy/thanks.html.twig
  templates/procuration/request/my_request.html.twig
  templates/procuration/request/thanks.html.twig
Labels: Ready for code review

#8204 [LPN-1447] update committee election designation queries for voting platform initialization command
  features/api/committees.feature
  features/api/designations.feature
  features/sitemap.feature
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/DataFixtures/ORM/LoadCommitteeV2Data.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Normalizer/DesignationDenormalizer.php
  src/Normalizer/ElectedMandateDenormalizer.php
  src/Repository/CommitteeRepository.php
  src/Repository/VotingPlatform/DesignationRepository.php
  templates/admin/designation/label.html.twig
  tests/Command/ApiScheduleCommitteeCreationCommandTest.php
  tests/Controller/EnMarche/Committee/ReferentCommitteeControllerTest.php
  tests/Controller/EnMarche/CommitteeDesignation/ReferentDesignationControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/SearchControllerTest.php
  tests/Repository/CommitteeRepositoryTest.php
  translations/validators.fr.yml
Labels: Ready for code review

#8216 [Committee] update zone types available for committee
  src/Entity/Committee.php
  src/Entity/EntityNameSlugTrait.php
  src/Entity/Geo/Zone.php
  src/Geo/Http/ZoneAutocompleteFilter.php
Labels: Ready for code review

#8218 [GeoZone] add new type - vote_place
  migrations/Version20230224152955.php
  src/Command/Geo/SyncZonesCommand.php
  src/Entity/Geo/VotePlace.php
  src/Entity/Geo/Zone.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8217 [Committee] validate zone type
  features/api/committees.feature
  src/Entity/Committee.php
  src/Entity/Geo/Zone.php
  src/Geo/Http/ZoneAutocompleteFilter.php
Labels: Ready for code review

#8202 [Elected] update query condition for listing endpoint
  features/api/elected_representatives.feature
  src/Controller/Api/ElectedRepresentative/ElectedRepresentativeListController.php
  src/ElectedRepresentative/Filter/ListFilter.php
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Entity/ElectedRepresentative/Mandate.php
  src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
  src/Security/Voter/CanManageElectedRepresentativeVoter.php
  tests/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeControllerTest.php
Labels: Ready for code review

#8219 [Elected] fix permission check
  src/Entity/ElectedRepresentative/ElectedRepresentative.php
  src/Security/Voter/ManageZoneableItemVoter.php
Labels: Ready for code review

#8231 [LPN-1457] approve committee v2 automatically
  src/Normalizer/CommitteeDenormalizer.php
Labels: Ready for code review

#8233 [Documents] fix download endpoint
  src/Controller/Api/DocumentDownloadFileController.php
Labels: Bug, Ready for code review

#8235 Update renaissance procuration messages
  src/Mailer/Message/Procuration/AbstractProcurationMessage.php
  src/Mailer/Message/Procuration/ProcurationProxyReminderMessage.php
Labels: Ready for code review
