Repository parti-renaissance/espace-adherent, pull requests merged in 2023-01, with the labels that each got.

#8016 [PHP] update Symfony 5.4.17
  composer.lock
Labels: dependencies, composer

#8024 Fix UnregistrationFactory return type
  src/Adherent/Unregistration/UnregistrationFactory.php
Labels: Bug, Ready for code review

#8025 Make donatedAt & registeredAt the same field
  src/Donation/DonationRequest.php
  src/Entity/Adherent.php
  src/Form/Admin/Adherent/CreateRenaissanceType.php
  src/Membership/AdherentFactory.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
  templates/admin/adherent/renaissance/create.html.twig
  tests/Admin/AdherentAdminTest.php
Labels: Ready for code review

#8026 Adherent administrator blameable
  config/services/admin.xml
  features/admin/adherent.feature
  migrations/Version20230103112607.php
  src/Controller/Admin/AdminAdherentCRUDController.php
  src/Entity/Adherent.php
  src/Membership/AdherentFactory.php
  src/Renaissance/Membership/Admin/AdherentCreateCommandHandler.php
Labels: Ready for code review

#8037 fix regional coordinator scope
  features/api/adherent_messages.feature
  src/AdherentMessage/AdherentMessageTypeEnum.php
  src/AdherentMessage/Filter/FilterFactory.php
  src/AdherentMessage/Listener/CreateDefaultMessageFilterSubscriber.php
  src/Entity/Adherent.php
  src/Entity/AdherentMessage/AbstractAdherentMessage.php
  src/Entity/AdherentMessage/RegionalCoordinatorAdherentMessage.php
  src/Mailchimp/Campaign/Listener/UpdateCampaignSubjectSubscriber.php
  src/ManagedUsers/Filter/RegionalCoordinatorFilterFactory.php
  src/Normalizer/AdherentMessageNormalizer.php
Labels: Ready for code review

#8038 [DptElection] Send candidate invitation
  config/packages/doctrine.yaml
  src/Command/SendCandidatureInvitationForDepartmentalElectionsCommand.php
  src/Command/SendPostVoteStatusesMessageCommand.php
  src/Mailer/Message/Renaissance/DepartmentalElectionCandidateInvitationMessage.php
  src/Query/Mysql/Left.php
Labels: Ready for code review

#8042 [DptElection] Send report election
  src/Command/SendReportDepartmentalElectionMessageCommand.php
  src/Mailer/Message/Renaissance/DepartmentalElectionReportMessage.php
Labels: Ready for code review

#8044 send complementary message
  src/Command/SendComplementaryInformationMessageCommand.php
  src/Mailer/Message/Renaissance/DepartmentalElectionComplementaryInformationMessage.php
Labels: Ready for code review

#8040 [Dev] update dump DB for 2022
  Makefile
  dump/dump-2022.sql
Labels: Ready for code review

#8051 [Admin] add designation label filter
  src/Admin/LocalElection/LocalElectionAdmin.php
Labels: Ready for code review

#8052 [Admin] Change CSV delimiter for candidate import
  src/Controller/Admin/AdminCandidaciesGroupCandidateImportController.php
Labels: Ready for code review

#8053 [Admin] Use iCheck events for radio inputs
  templates/admin/adherent/renaissance/create.html.twig
Labels: Ready for code review

#8055 [DptElection] Improve result calculator
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Twig/VotingPlatformExtension.php
  src/VotingPlatform/Election/PartyListProportional/Model/PartyList.php
  src/VotingPlatform/Election/PartyListProportional/Processor.php
  src/VotingPlatform/Election/ResultCalculator/PartyListProportionalCalculator.php
  templates/voting_platform/_layout_local_election.html.twig
  templates/voting_platform/confirmation/candidate_box/local_election_content.html.twig
  templates/voting_platform/finish.html.twig
Labels: Ready for code review

#8056 [Adhesion] Validate adhesion even if token is used and adherent does …
  src/Controller/Renaissance/Adhesion/ValidateController.php
Labels: Ready for code review

#8057 fix coordinator messages
  src/Mailchimp/Campaign/SegmentConditionBuilder/SubscriptionTypeConditionBuilder.php
  tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Labels: Work in progress

#8058 fix gender label on donation form
  templates/renaissance/donation/fill_personal_info.html.twig
Labels: Ready for code review

#8067 [LPN-1354] change sender name in Email Admin
  src/Admin/EmailAdmin.php
  src/Entity/Email.php
Labels: Ready for code review

#8070 [DptSite] fix content rendering
  templates/renaissance/department_site/department_site.html.twig
Labels: Bug, Ready for code review

#8069 Update donator email on adherent email change
  src/Adherent/Listener/UpdateDonatorEmailSubscriber.php
  src/Repository/DonatorRepository.php
Labels: Ready for code review

#8066 Fix Local Election view page
  config/packages/doctrine.yaml
  src/Command/VotingPlatform/CloseElectionCommand.php
  src/Controller/Renaissance/LocalElection/LocalPollElectionController.php
  src/LocalElection/Manager.php
  src/Repository/LocalElection/LocalElectionRepository.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/Twig/VotingPlatformRuntime.php
  src/VotingPlatform/ElectionManager.php
  templates/admin/instances/election_dashboard.html.twig
  templates/voting_platform/results/_local_election_candidate_box.html.twig
  templates/voting_platform/vote_step/candidate_box/local_election_content.html.twig
Labels: Ready for code review

#8071 [Admin] validate custom amount on adherent creation
  src/Form/Admin/Adherent/CreateRenaissanceType.php
  src/Renaissance/Membership/Admin/AdherentCreateCommand.php
Labels: Ready for code review

#8072 [Test] fix paybox 3ds tests
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#8073 [VotingPlatform] send results-ready notifications
  migrations/Version20221202161505.php
  migrations/Version20230112170300.php
  src/Command/VotingPlatform/CloseElectionCommand.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Command/VotingPlatform/InitializeElectionsCommand.php
  src/Command/VotingPlatform/NotifyCommand.php
  src/DataFixtures/ORM/LoadDesignationData.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformResultsReadyMessage.php
  src/Repository/VotingPlatform/DesignationRepository.php
  src/Repository/VotingPlatform/ElectionRepository.php
Labels: Ready for code review

#8086 [DptElection] vote invitation email
  src/Command/SendComplementaryInformationMessageCommand.php
  src/Command/SendVoteInvitationForDepartmentalElectionsCommand.php
  src/Mailer/Message/Renaissance/DepartmentalElectionComplementaryInformationMessage.php
  src/Mailer/Message/Renaissance/DepartmentalElectionVoteInvitationMessage.php
Labels: Ready for code review

#8085 remove municipal manger supervisor role
  migrations/Version20230113162740.php
  src/Adherent/AdherentRoleEnum.php
  src/AdherentSpace/AdherentSpaceEnum.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/Controller/EnMarche/AssessorSpace/MunicipalManagerSupervisorAssessorSpaceController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/AbstractMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/MunicipalChiefMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/MunicipalManagerSupervisorMunicipalManagerAttributionController.php
  src/Controller/EnMarche/MunicipalManagerAttribution/ReferentMunicipalManagerAttributionController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadOrganizationalChartItemData.php
  src/Entity/Adherent.php
  src/Entity/MunicipalManagerSupervisorRole.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Entity/ReferentOrganizationalChart/ReferentPersonLink.php
  src/EntityListener/RevokeReferentTeamMemberRolesListener.php
  src/EventListener/ManageReferentTeamMembersListener.php
  src/Form/ReferentPersonLinkType.php
  templates/adherent/_list_my_sections.html.twig
  templates/adherent_space/_layout.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/assessor_attribution/_base_municipal_manager_supervisor_space.html.twig
  templates/assessor_attribution/_sub_menu.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
  templates/municipal_manager_attribution/_base_municipal_chief_space.html.twig
  templates/municipal_manager_attribution/_base_municipal_manager_supervisor_space.html.twig
  templates/municipal_manager_attribution/_base_referent_space.html.twig
  templates/municipal_manager_attribution/_layout.html.twig
  templates/municipal_manager_attribution/index.html.twig
  templates/municipal_manager_supervisor/_layout.html.twig
  templates/referent/edit_referent_person_link.html.twig
  templates/referent/organizational_chart_macros.html.twig
  tests/Controller/EnMarche/MunicipalManagerAttribution/MunicipalChiefMunicipalManagerAttributionControllerTest.php
  tests/Controller/EnMarche/MunicipalManagerAttribution/MunicipalManagerSupervisorMunicipalManagerAttributionControllerTest.php
  tests/Controller/EnMarche/MunicipalManagerAttribution/ReferentMunicipalManagerAttributionControllerTest.php
  translations/messages+intl-icu.fr.yml
Labels: Ready for code review

#8087 remove municipal manager role
  features/admin/committee_merge.feature
  features/api/adherents.feature
  migrations/Version20230113181056.php
  src/Adherent/AdherentRoleEnum.php
  src/AdherentSpace/AdherentSpaceEnum.php
  src/Admin/Filter/AdherentRoleFilter.php
  src/AssociationCity/Filter/AssociationCityFilter.php
  src/Controller/EnMarche/AssessorSpace/MunicipalManagerAssessorSpaceController.php
  src/Controller/EnMarche/Election/CityVoteResults/MunicipalManagerCityVoteResultController.php
  src/Controller/EnMarche/Election/MunicipalManagerCityController.php
  src/Controller/EnMarche/Election/VotePlaceResults/MunicipalManagerVoteResultController.php
  src/Controller/EnMarche/Election/VoteResultList/MunicipalManagerVoteResultListController.php
  src/Controller/EnMarche/ElectionResultsReporterController.php
  src/DataFixtures/ORM/LoadAdherentData.php
  src/DataFixtures/ORM/LoadCertificationData.php
  src/DataFixtures/ORM/LoadCommitteeCandidacyData.php
  src/DataFixtures/ORM/LoadCommitteeData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilAdherentMandateData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
  src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
  src/Entity/Adherent.php
  src/Entity/MunicipalManagerRoleAssociation.php
  src/Entity/MyTeam/DelegatedAccessEnum.php
  src/Form/CityFilterType.php
  src/Form/MunicipalManagerCityAssociationType.php
  src/Form/MunicipalManagerCityListType.php
  src/Form/ReferentCityFilterType.php
  src/MunicipalManager/MunicipalManagerAssociationValueObject.php
  src/MunicipalManager/MunicipalManagerRole/MunicipalManagerAssociationManager.php
  src/Repository/AdherentRepository.php
  src/Repository/CityRepository.php
  src/Security/Voter/ManageVotePlaceVoter.php
  templates/adherent/_list_my_sections.html.twig
  templates/adherent_space/_layout.html.twig
  templates/admin/adherent/statuses.html.twig
  templates/assessor_attribution/_base_municipal_manager_space.html.twig
  templates/components/_dropdown_user_mobile.html.twig
  templates/components/_nav_desktop.html.twig
  templates/election_result_list/_base_municipal_manager_space.html.twig
  templates/election_vote_results/_base_municipal_manager_space.html.twig
  templates/municipal_chief/_layout.html.twig
  templates/municipal_manager/_layout.html.twig
  templates/municipal_manager/cities.html.twig
  templates/referent/_sidebar.html.twig
  tests/Controller/EnMarche/CommitteeDesignation/CandidatureControllerTest.php
  tests/Controller/EnMarche/MapControllerTest.php
  tests/Controller/EnMarche/UnregistrationControllerTest.php
  translations/messages+intl-icu.fr.yml
  translations/validators.fr.yml
Labels: Ready for code review

#8088 [DptElection] use uuid for election view page
  src/Controller/Renaissance/LocalElection/DepartmentElectionController.php
  src/LocalElection/Manager.php
  src/VotingPlatform/Notifier/ElectionNotifier.php
  templates/renaissance/adherent/_menu.html.twig
  templates/renaissance/local_election/_nav.html.twig
  templates/voting_platform/_layout_local_election.html.twig
Labels: Ready for code review

#8090 [Election] add FDE only option for notification command
  src/Command/SendVoteInvitationForDepartmentalElectionsCommand.php
  src/Mailer/Message/Renaissance/DepartmentalElectionFdeVoteInvitationMessage.php
Labels: Ready for code review

#8100 [DptElection] display percents on result page
  templates/voting_platform/_layout_local_election.html.twig
  templates/voting_platform/results.html.twig
  templates/voting_platform/results/_local_election_candidate_box.html.twig
Labels: Ready for code review

#8110 Clean main account url
  features/javascript/donation.feature
  features/registration.feature
  features/user_controller_donation.feature
  src/Controller/EnMarche/UserController.php
  tests/Controller/EnMarche/AdherentControllerTest.php
  tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
  tests/Controller/EnMarche/UserControllerTest.php
  tests/Controller/Renaissance/AdherentControllerTest.php
  tests/Controller/Renaissance/Security/SecurityControllerTest.php
  tests/Security/InactiveAdminDisconnectionTest.php
Labels: Ready for code review

#8111 [dpt-elections] remove region code on the elections list
  templates/renaissance/local_election/summary/list.html.twig
Labels: Ready for code review

#8119 [VotingPlatform] add link for results page in notification
  src/Command/VotingPlatform/NotifyCommand.php
  src/Mailer/Message/Renaissance/VotingPlatform/VotingPlatformResultsReadyMessage.php
Labels: Ready for code review

#8118 [VotingPlatform] fix sending vote is open notification
  migrations/Version20230123015605.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/Command/VotingPlatform/NotifyCommand.php
  src/Entity/VotingPlatform/Designation/Designation.php
  src/Repository/VotingPlatform/DesignationRepository.php
Labels: Ready for code review

#8120 [ZoneBinding] clean french zone of type district/canton
  src/Deputy/Subscriber/BindAdherentZoneSubscriber.php
Labels: Ready for code review

#8125 [VotingPlatform] update round precision on results page
  templates/voting_platform/_layout_local_election.html.twig
  templates/voting_platform/results/_local_election_candidate_box.html.twig
Labels: Ready for code review

#8132 [PHP] update Symfony 5.4.19
  composer.lock
Labels: dependencies, composer

#8131 [VotingPlatform] display substitute candidates on voting step
  migrations/Version20230124152540.php
  src/Command/VotingPlatform/ConfigureCommand.php
  src/DataFixtures/ORM/LoadLocalElectionData.php
  src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
  src/Entity/LocalElection/CandidaciesGroup.php
  src/Entity/VotingPlatform/Candidate.php
  src/Entity/VotingPlatform/CandidateGroup.php
  src/Repository/AdherentRepository.php
  templates/voting_platform/vote_step/candidate_box/local_election_content.html.twig
Labels: Ready for code review

#8141 [VotingPlatform] display voters count on results page
  src/Admin/VotingPlatform/DesignationAdmin.php
  src/Entity/VotingPlatform/ElectionResult/CandidateGroupResult.php
  templates/voting_platform/_layout_local_election.html.twig
Labels: Ready for code review

#8142 [DptElection] display sas page only to registered users until 31st
  src/Repository/VotingPlatform/DesignationRepository.php
Labels: Ready for code review

#8134 Add additional parameters for 3DSv2 compliance
  composer.lock
  src/Donation/PayboxFormFactory.php
  tests/Controller/Renaissance/Adhesion/AdhesionControllerTest.php
Labels: Ready for code review

#8144 fix adherent profile menu
  src/Twig/AdherentRuntime.php
  templates/renaissance/adherent/_layout.html.twig
Labels: Ready for code review
